### ISSUE TITLE
Sorted lists in webmin configuration

### ISSUE THREAD

**Issue by majk-p** [qooob/authentic-theme#100]
This is more likely to be a suggestion than an issue. I wonder, wouldn't it be better if lists like *Webmin configuration* were sorted alphabetically. This only refers to **low screen resolutions**. As I were managing my server via 10'1 screen netbook *Webmin configuration* screen looked like this:
![webmin-sort](https://cloud.githubusercontent.com/assets/7260594/6098035/ec74d660-afd1-11e4-97bb-b4258bad12b1.png)
On smaller screens you don't see the icons so it may be a way to shorten the time one needs to find certain element. What do you think?

**Comment by qooob** [comment]
Sounds like an interesting idea. I will think of it. By the way, do you know that you have those unsorted links (that are on the right) in the left search drop-down? ;) Try typing `Lo`, when you in Konfiguracja Webmina.

**Comment by majk-p** [comment]
Everything to make the theme even more user-friendly :) Recently I've got a little more time, might take a look at the code and try implement it myself if you need a hand.

**Comment by qooob** [comment]
I just released version 9.5.0 - now you can inject custom _styles_ and _scripts_ to the theme, that will not be lost after theme update.

**Comment by majk-p** [comment]
Thank you! I'll surely try using the scripts to temporary solve the sorting. Have you thought about creating separate repository for theme specific user scripts if community creates some?

**Comment by qooob** [comment]
If there is a demand for that and there are interesting scripts, then, probably.

**Comment by majk-p** [comment]
I think personal scripts will do the trick. I only have one more suggestion, don't know if it's better to create new issue though. I think about creating a cookie or meta-tag in head section holding info about current position within webmin/usermin/virtualmin. Some kind or path or so. Such information would allow to perform actions only within certain sections of the system.

**Comment by qooob** [comment]
I see. You should not be doing it by theme means nor JavaScript. It's very easy to sorry array server-side. Address this issue to https://github.com/webmin, they can easily fix it.
