### ISSUE TITLE
Sysstats Panorama View - No Display

### ISSUE THREAD

**Issue by imfineru** [qooob/authentic-theme#1000]
I am still having issues with Sysstats Panorama View. V 19.0 all the way to 19.09 Beta 3. One of the fixes you did prior was to open up a new window, and it worked. However that fix has since gone away. This is happening on multiple browsers, multiple PC's. It is theme specific, as the view works perfectly in other Webmin themes. 
When clicking the Panorama View button, it takes about 30-45 seconds before this screenshot is displayed. 

![capture](https://user-images.githubusercontent.com/14332041/35514023-e594e386-04d2-11e8-81e7-75472cf9dd22.JPG)

Thanks!

**Comment by qooob** [comment]
Hi,

Thank you for reporting.

This has to be improved on the module's side.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/889#issuecomment-344231643
