### ISSUE TITLE
something is missing after webmin version?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1001]
It seems that something is missing after the webmin version or should it end with a dot?
![image](https://user-images.githubusercontent.com/5789283/35524418-d5c3c32e-0521-11e8-8088-42928667d5f7.png)

There is not a dot after 1.870:
![image](https://user-images.githubusercontent.com/5789283/35524552-34d7bbf4-0522-11e8-894a-e73e7ffdef21.png)

**Comment by qooob** [comment]
Whatever it is - nothing is missing. I saw it at some point as well.

Don't see anything to worry about really.

**Comment by Sopor-** [comment]
I have updated some of my other Webmin and it will show `1.873.0220.2122`. Are you sure it isn't cut off after the dot?
![image](https://user-images.githubusercontent.com/5789283/36544624-3423e00c-17e7-11e8-8177-f5fef7abcb01.png)

**Comment by qooob** [comment]
I'm not sure. I have double checked it by installing it from repo just now.

What is the output of 

```
cat /usr/libexec/webmin/version
```

**Comment by qooob** [comment]
It could be 

```
cat /usr/share/webmin/version
```

..on Debian OS.

**Comment by Sopor-** [comment]
All three is showing `1.873.` and one is showing `1.873.0220.2122`, exact the same as in the Dashboard. Why will it not show the same version? I have updated it by running the `update-from-repo.sh`.

**Comment by qooob** [comment]
This should be asked @gnadelwartz.

**Comment by gnadelwartz** [comment]
the update-from-repo script was broken in 1.872 and 1.873 and fixed in github now.
please download the fixed version with `wget https://rawgit.com/webmin/webmin/master/update-from-repo.sh` from within webmin dir and rub update-from-repo again.

the version number is then a real number without dots or -

**Comment by Sopor-** [comment]
It will now only show `1.873`, is that correct @gnadelwartz ?

**Comment by gnadelwartz** [comment]
not really but ok, maybe  git log -1 --format=%cd --date=format:'%m%d%H%M' is not working on your host.

what os and version?

check out webmin with git clone https://github.com/webmin/webmin.git to a temporary location
cd to webmin and run  git log -1 --format=%cd --date=format:'%m%d%H%M'

what's the output?

**Comment by gnadelwartz** [comment]
I implemented the following workaround:

- if sub version number can't retrieved use current date

if its something like 1.8732018... it's current date while running update

Try: https://raw.githubusercontent.com/gnadelwartz/webmin/update/update-from-repo.sh

**Comment by qooob** [comment]
Yes, git version 1x is not compatible with that part of the date formatting. 

@Sopor- Kay will fix it.

Thanks for reporting.

**Comment by Sopor-** [comment]
Now it will show `1.873201802222045`

**Comment by gnadelwartz** [comment]
fixed!

Thanks for reporting it!
