### ISSUE TITLE
warning about Usermin even if i don't have it installed

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1002]
I get this warning even if i don't have Usermin installed:
![image](https://user-images.githubusercontent.com/5789283/35524725-b0b6e862-0522-11e8-8368-62822213d088.png)
I have already updated Webmin to 1.873 so why show this message when Usermin is not installed?

**Comment by qooob** [comment]
Let me check..

**Comment by qooob** [comment]
Fixed. Please give it a try.
