### ISSUE TITLE
update beta 4

### ISSUE THREAD

**Issue by TMTYD** [qooob/authentic-theme#1003]
Hi

I can not run the update on the beta4, it comes an error message that is Usermin need to run the update

**Comment by qooob** [comment]
Isn't related and fixed? https://github.com/qooob/authentic-theme/issues/1002

**Comment by TMTYD** [comment]
ok thx

**Comment by qooob** [comment]
I created Webmin only VM to test it and double-check. Recent git version work correctly.

Thank you for reporting anyway.
