### ISSUE TITLE
Webmin's config file being overwritten

### ISSUE THREAD

**Issue by myopenflixr** [qooob/authentic-theme#1004]
Hi Qooob,

I'm not sure if this is due to the beta patch version of Authentic or not, but I've had two separate instances where my webmin config file was randomly overwritten with new data causing me to loose access to Webmin. Both times I had to manually rewrite my config file with its original settings to gain access to Webmin. The config file is located at /etc/webmin/config on my machine.

I'm running Ubuntu Server 16.04.03, Webmin version 1.870, Authentic Theme 19.09-beta3. I have noticed there is a beta4 version available and if I try to upgrade, I get a message stating that I should upgrade Webmin to unreleased version 1.872 to work properly.

Maybe I should not have even upgraded to beta3? Should I try and downgrade from beta3?

Any ideas what the cause of this is? Any ideas what I can do to prevent this from happening again?

Thanks,
Mike

**Comment by qooob** [comment]
Mike, hi.

I have never experienced it recently but encountered this before.

I could never find the link to the theme doing it.

Any steps to reproduce it?

**Comment by myopenflixr** [comment]
The only thing that stuck out to me as strange....I remember yesterday clicking on a link within Webmin and then immediately opening a new browser window and then opening a new instance of Webmin.

That second instance of Webmin threw an error (404 maybe...or maybe it just timed out)...and the page that was originally opened eventually timed out with an error as well.

Since I had this happen previously, I immediately SSH'd in to my config file and it was half erased and missing all the important stuff!

Luckily, I have several machines running Webmin, so I just copied and pasted the contents of another config file and made the appropriate adjustments....restarted Webmin and it worked fine again.

I have no idea if that had anything to do with it but that's how I remember the error happening yesterday.

**Comment by qooob** [comment]
I will let Jamie know. 

Did you save broken config file? It would help a lot.

**Comment by myopenflixr** [comment]
I did not save the old config...I just wrote over it......I'll try to reproduce the error tonight. Assuming I can, I'll be sure to report back with the steps to reproduce along with the broken config file.

**Comment by qooob** [comment]
Mike, thanks a lot. I'll be fantastic.

**Comment by qooob** [comment]
Ref.
https://github.com/webmin/webmin/issues/755
