### ISSUE TITLE
Authentic theme, Keyboard BOS Latin > @ at sign

### ISSUE THREAD

**Issue by arminba** [qooob/authentic-theme#1007]
Hi Ilia,

we have the following situation with the Usermin Authentic Theme v.19 .

Usermin, Webmin, Virtualmin (GPL) all components are up-to-date.
Desktop Win 10
Keyboard: BOS Latin (Bosnian Default)

After login to the Usermin panel ( Authentic Theme ) > Compose (New Message) > in the Fields "TO", "CC", "BCC" is not possible to write "@".
BOS keybord = Alt Gr + v

No problems with the EN (US) keyboard.

thanks

**Comment by qooob** [comment]
Not possible to write? What happens exactly if you try to write it? What is the key combo in your layout for `@`?

**Comment by arminba** [comment]
Hello, Ilia

What happens exactly if you try to write it? 
Nothing is happening :-), no charset, no space

What is the key combo in your layout for @?
AltGr+V
https://en.wikipedia.org/wiki/AltGr_key#South_Slavic_Latin

thanks

**Comment by qooob** [comment]
Fixed: 
https://github.com/qooob/authentic-theme/commit/942101ee9968765cf38112a36a9a467aec9c5fd2
