### ISSUE TITLE
small/single column breakpoint too wide

### ISSUE THREAD

**Issue by samatcd** [qooob/authentic-theme#101]
I find the 'small' breakpoint which puts menus into a single column is too wide, and gets triggered even on my laptop screen (MacBook Pro Retina 15"). Possible to add another breakpoint which shows two columns, or otherwise change the breakpoint?

![screen shot 2015-02-09 at 5 37 03 pm](https://cloud.githubusercontent.com/assets/1476991/6101071/8f93c4fe-b082-11e4-8c8c-2efb2d85c401.png)

**Comment by qooob** [comment]
Thanks, good point. Just fixed it. It's too small to add it to the update.

Please update manually re-downloading the theme and installing it using `Webmin->Webmin Configuration->Themes`.

URL: https://rostovtsev.ru/.git/authentic-theme/authentic-theme-latest.wbt.gz
