### ISSUE TITLE
ConfigServer Security & Firewall will open a new page

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1010]
When i press the `ConfigServer Security & Firewall` in the left tree view it will open a new page instead of open at the right side of the tree view.
You can see at the top of the page it show the Dashboard but the page is CSF.

![image](https://user-images.githubusercontent.com/5789283/36100576-fbaf479e-1006-11e8-891e-6433ba6f5135.png)

This is the page that will open:
![image](https://user-images.githubusercontent.com/5789283/36100728-8a77e5f8-1007-11e8-866a-60185dabaff9.png)

**Comment by qooob** [comment]
What is your theme/Webmin version?

I contacted CSF support to make new changes to their module, to provide support for new version of theme/Webmin.

**Comment by qooob** [comment]
It's possible due to Webmin 1.870.

**Comment by qooob** [comment]
It's surely not happening on the latest Webmin/theme/CSF. I tested it. 

Could you fetch latest `web-lib.funcs.pl` from Webmin repo, update it and restart Webmin?

**Comment by qooob** [comment]
You also have issues in case you disabled CSF UI option in it's configuration.

**Comment by Sopor-** [comment]
> What is your theme/Webmin version?

You can see all the version in the above screenshot

**Comment by qooob** [comment]
Yes, I already did.

**Comment by Sopor-** [comment]
I'm running another computer on
`Webmin version | 1.870 | Theme version | Authentic Theme 19.09` and i have no problems there.

**Comment by qooob** [comment]
Clear browser's cache?

**Comment by Sopor-** [comment]
Yes, i even tried it in 3 different web browser (Firefox, Chrome and SRWare Iron.), but it will still open in a new tab.

**Comment by qooob** [comment]
I'll try to reproduce it.

**Comment by Sopor-** [comment]
I can see this too
![image](https://user-images.githubusercontent.com/5789283/36108388-0c335702-101d-11e8-884e-68e539c459e0.png)

**Comment by qooob** [comment]
What is, if I remember correctly, `UI_CUSTOM` option in your CSF set to?

**Comment by Sopor-** [comment]
`STYLE_CUSTOM` and `STYLE_MOBILE` are both `ON` as in my other CSF configuration.

The URL change to
`https://192.168.0.100:10000/csf/index.cgi?xnavigation=1`
when i press on the CSF and in the new tab where  CSF open it will be
`https://192.168.0.100:10000/csf/index.cgi`.

**Comment by qooob** [comment]
Can you try incognito tab?

**Comment by qooob** [comment]
Oh, wait!! You have dated CSF 10.xx?? It's not supported.

Install 11.06 please.

**Comment by Sopor-** [comment]
It was an old CSF. Now it is working when i updated to 11.06. Maybe you should check what version a user is running to avoid this in the future?

**Comment by qooob** [comment]
Yes, maybe. I'll see what I can do.

**Comment by qooob** [comment]
Alright, it's done for basic software:

Webmin, Usermin, Virtualmin, Cloudmin and CSF.

Thanks for the idea!

**Comment by qooob** [comment]
This is how it's going to look like, just an example, version 1.872 is not outdated yet.

![screenshot from 2018-02-14 12-08-46](https://user-images.githubusercontent.com/4426533/36195887-fa222836-117f-11e8-998d-17fa5afdf2cb.png)
