### ISSUE TITLE
dashboard take over a minute to load / update

### ISSUE THREAD

**Issue by dontolbert** [qooob/authentic-theme#1011]
I also have update problem:
Failed to upgrade from www.webmin.com : Download timed out

System is Ubuntu 16.04 (recently upgraded from 14.04).  Webmin was working no problem after upgrade, this problem just started in last few days.

Could the two issues be related as you've previously discussed?
Using Authentic version 19.09-beta2  (I don't know why beta versions are being installed)
Webmin v1.870

Firefox, Chrome and IE all tested

**Comment by qooob** [comment]
Hi,

I prematurely removed the key file for sending version number.

It should be fixed now.

Try Force Udating the theme from Theme's Configuration.

Update notice will not work untill 19.09 is installed. There was a change in the way versioning is managed.

**Comment by dontolbert** [comment]
I'm sorry.  I cannot force update.

![dashboard_02122018](https://user-images.githubusercontent.com/36421738/36120517-11993b08-1009-11e8-8a1d-027171c3d4a5.PNG)

**Comment by qooob** [comment]
Why not? I should be just working? So you have `git` command installed?

**Comment by qooob** [comment]
You can do it from Theme's Configuration page.

**Comment by dontolbert** [comment]
I am trying.  It fails

![capture](https://user-images.githubusercontent.com/36421738/36121298-58e028a8-100b-11e8-9b4c-eb77b718e7e7.PNG)

**Comment by dontolbert** [comment]
Yes, git is installed.

**Comment by qooob** [comment]
Can you try console? Go to `/use/share/webmin/authentic-theme` and run `./theme-update.sh`.

**Comment by dontolbert** [comment]
Thank you for your help.  I appreciate your patience.

**Comment by qooob** [comment]
Did it work?

**Comment by dontolbert** [comment]
Yes it worked.  Some my fault, bad DNS configuration.  Thank you again.
