### ISSUE TITLE
Print Email

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#1012]
A customer discovered that when you click "Print" in Usermin, it won't print correctly. It prints the first page and that's all.

Thinking the customer was just doing something wrong, I checked and he was correct.

It seems, if you scroll down the email, it'll print just that portion of the email when you click the "Print" in the bottom menu of Usermin. Something definitely needs to be adjusted as this is a serious problem for those who print their email from Usermin.

For the moment, I've simply switched the Usermin theme back to the Virtualmin Framed Theme as the bug doesn't affect the older theme.

*** Webmin, User, and Virtualmin are all current BTW ***

**Comment by qooob** [comment]
It's all be reworked with new mail. There is huge amount of control over CSS in terms of what and how is printed.

**Comment by qooob** [comment]
It will be perfect when finished.

**Comment by qooob** [comment]
I'm going to use the mail myself, which means I'm making it outstanding. Starting at the end of April.

**Comment by qooob** [comment]
Wrong, at the end of February.

**Comment by qooob** [comment]
By the end of April we should have new and functional UI.

**Comment by gnadelwartz** [comment]
until new mail is finished, you may switch back to framed version of authentic for usermin. hoefully print mail is working there....

**Comment by qooob** [comment]
It should be trivial to fix. I'll check that tomorrow and add it to 19.09.1 in no time.

Framed Version of Authentic sounds scary. I'm endlessly happy it's gone forever.

**Comment by tpnsolutions** [comment]
The only reason I brought this topic up was the print functionality is essentially "broken". I'm not requesting a feature, which I understand is a bit moot given the newer UI being developed, but rather viewing this as a theme "bug". Sure I can and have switched back to the Framed Theme for Usermin, but this shouldn't be necessary generally speaking. Cheers.

**Comment by qooob** [comment]
Fixed.
