### ISSUE TITLE
different date format in Recent Logins but the Dashboard shows the same

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1013]
I run four Webmin and three of them show one date format (yyyy-mm-dd hh:mm) and one of them show another date format in the Recent Login. I have the exact same date format set in `Authentic Theme` but still it will show different date format. The rest of the Dashboard shows the same date format on all four Webmin's.
Is this something i can change in `Authentic Theme` or what?

![image](https://user-images.githubusercontent.com/5789283/36252123-d88957fc-1243-11e8-97bf-e79b90d7c7b8.png)

**Comment by qooob** [comment]
Yes, this info is coming from WebminCore, while theme has it's own API for doing it.

I will talk to Jamie if we just could provide backward compatibility to the theme.

**Comment by qooob** [comment]
You are welcome to continue there a bit latter.
https://github.com/webmin/webmin/issues/820

**Comment by qooob** [comment]
Follow this up. I'm adding full locale support.

https://github.com/qooob/authentic-theme/issues/1035
