### ISSUE TITLE
smartmatch warnings in error log

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#1014]
authentic-lib uses smartmatch

see https://sourceforge.net/p/webadmin/discussion/600155/thread/8edc58d3/

for explanation why smartmatch should be avoided see also https://stackoverflow.com/questions/16927024/perl-5-20-and-the-fate-of-smart-matching-and-given-when

**Comment by swelljoe** [comment]
I agree smart match needs to go; it'll break when 5.26 starts shipping with distros.

If I'm reading these bits of code right, a simple == would do the same thing as ~~ (which turns out to be the wrong thing in a number with multiple dots).

**Comment by qooob** [comment]
Iteresting.

Okay, then just using should be fine.

```
grep( /^$val$/, @arr )
```

**Comment by qooob** [comment]
It should be fixed, please have a look:
https://github.com/qooob/authentic-theme/commit/dd4b2010f7e62afdbea2f0d53d23c191f07675ce

**Comment by qooob** [comment]
> a simple == would do the same thing as ~~

It wouldn't, as it's not the exact match.

This is very disturbing that Perl doesn't have a set of very basic functions and almost each and every has to be reinvented manually.

I came up with using this, what are your thoughts on it, Perl-guys?


```Perl
sub string_contains
{
    my ($string, $search) = @_;

    if (index($string, $search) != -1) {
        return 1;
    } else {
        return 0;
    }

}

sub array_contains
{
    my ($e, $n, @a) = @_;
    my $m;

    if ($e eq 'exact') {
        if (grep(/^\Q$n\E$/, @a)) {
            return 1;
        } else {
            return 0;
        }
    } else {
        for (@a) {
            if (string_contains($_, $n)) {
                $m = 1;
                last;
            }
        }
        if ($m) {
            return 1;
        } else {
            return 0;
        }
    }
    return 0;
}
```

**Comment by gnadelwartz** [comment]
should do the same:
``` perl
sub string_contains
{
return index(@_[0], @_[1]) != -1);
}

sub array_contains
{
    my ($e, $n, @a) = @_;

    if ($e eq 'exact') {
        return (grep(/^\Q$n\E$/, @a));
   } else {
        return (grep(/\Q$n\E/, @a));
   }
}
```

**Comment by gnadelwartz** [comment]
universal and simple:

```
# array_contains(regex, array);
# examples for regex:
# /\Qstring\E/ contains string
# /^Qstring\E$/ contains exact string
# /^some*thing$/ starts with some and ends with thing
sub array_contains
{
    my ($n, @a) = @_;
    return (grep($n, @a));
}
```

**Comment by qooob** [comment]
Will it match `71` in `(1,2,7,7710,...)`? `Index()` is 3 time faster than using regex, as far as I'm aware. Not sure though, if grep in your example in Perl falls down to regex. I would need to test it.

**Comment by gnadelwartz** [comment]
yes, index is faster than a single match statement, but with an array grep should be equal or faster because the regex has to be compiled only once and no addtional loop

71 is a good question because its a number and index or regex matches strings, but it may work because of the perl auto conversion:

num -> string -> regex compares against array num -> string

if you mean "71" and an array of strings the answer is yes 😁

**Comment by gnadelwartz** [comment]
btw most examples use grep as regex compairson engine like grep on command line, its an universal filter engine. you can every perl expression to filter an array. IMHO the name grep  is a bit misleading

for an exact match you can use also

grep { $_ eq 'Engineer' } @array;

for an contains match index should work

grep { index($_, 'Engineer') !=-1 } @array;

https://www.cs.ait.ac.th/~on/O/oreilly/perl/cookbook/ch04_14.htm

**Comment by gnadelwartz** [comment]
an excellent post about what perl offers for testing if an array contains a value
http://blogs.perl.org/users/mascip/2013/05/the-clearest-ways-to-check-if-a-list-contains.html

**Comment by qooob** [comment]
I did actual tests myself, here is what I got.

### Case 1. Plain `grep` vs. custom `array_contains` that falls into `for` loop and later uses `index()`:
**Set-up:**

```Perl
use Benchmark;
my @array;
for (1..10_000) {
    push @array, $_;
}

timethese(10000, {
  'grep'    => sub {
            if ( grep { $_ eq '5000' } @array ) {
                # code
            }
        },
  'array_contains_loose'    => sub {
            if ( array_contains('loose', '5000', @array) ) {
                # code
            }
        },
});

```

**Result:** 

```Perl

Benchmark: timing 10000 iterations of array_contains_loose, grep...
--
  | array_contains_loose: 21 wallclock secs (19.01 usr +  0.00 sys = 19.01 CPU) @ 526.04/s (n=10000)
  | grep:                  4 wallclock secs ( 3.91 usr +  0.00 sys =  3.91 CPU) @ 2557.54/s (n=10000)


```





### Case 2. Plain `grep` vs. custom `array_contains` that falls into `grep` with `regex`:
**Set-up:**

```Perl
use Benchmark;
my @array;
for (1..10_000) {
    push @array, $_;
}

timethese(10000, {
  'grep'    => sub {
            if ( grep { $_ eq '5000' } @array ) {
                # code
            }
        },
  'array_contains_exact'    => sub {
            if ( array_contains('exact', '5000', @array) ) {
                # code
            }
        },
});

```

**Result:** 

```Perl




Benchmark: timing 10000 iterations of array_contains_exact, grep...
  | array_contains_exact: 27 wallclock secs (24.42 usr +  0.00 sys = 24.42 CPU) @ 409.50/s (n=10000)
  | grep:                  4 wallclock secs ( 3.97 usr +  0.00 sys =  3.97 CPU) @ 2518.89/s (n=10000)
 

```


### Case 3. Plain `grep` vs. plain `grep` with `regex`:


```Perl

use Benchmark;
my @array;
for (1..10_000) {
    push @array, $_;
}

timethese(10000, {
  'grep'    => sub {
            if ( grep { $_ eq '5000' } @array ) {
                # code
            }
        },
  'grep_regex'    => sub {
            my $ix = 5000;
            if ( grep(/^\Q$ix\E$/, @array) ) {
                # code
            }
        },
});

```



**Result:** 

```Perl

Benchmark: timing 10000 iterations of grep, grep_regex...
--
  | grep:        4 wallclock secs ( 3.89 usr +  0.00 sys =  3.89 CPU) @ 2570.69/s (n=10000)
  | grep_regex: 16 wallclock secs (14.83 usr +  0.00 sys = 14.83 CPU) @ 674.31/s (n=10000)


```


### Case 4. Plain `grep` with non-exact match vs. plain `grep` with `regex`:


```Perl

use Benchmark;
my @array;
for (1..10_000) {
    push @array, $_;
}

timethese(10000, {
  'grep_with_index' => sub {
            if ( grep { index($_, 5000) !=-1 } @array ) {
                # code
            }
        },
  'grep_regex'     => sub {
            my $ix = 5000;
            if ( grep(/^\Q$ix\E$/, @array) ) {
                # code
            }
        },
});
```


```Perl

enchmark: timing 10000 iterations of grep_regex, grep_with_index...
--
  | grep_regex:      17 wallclock secs (15.38 usr +  0.00 sys = 15.38 CPU) @ 650.20/s (n=10000)
  | grep_with_index:  6 wallclock secs ( 5.87 usr +  0.00 sys =  5.87 CPU) @ 1703.58/s (n=10000)


```


Thanks Kay, I will go with `grep { index($_, $val) !=-1 } @array` and `grep { $_ eq '5000' } @array`

Just in few moments, I will wrap `grep { $_ ... } @array` in a subroutines and run tests again.

**Comment by qooob** [comment]
I have a security concerns now.

Is this safe to use:

```Perl
grep { $_ eq $value } @array
```
`$value` is just falling into the `grep` with out any checks?

**Comment by qooob** [comment]
Funny. Changed `string_contains` to:

```Perl
sub string_contains
{
    return (index($_[0], $_[1]) != -1);
}
```

After running results, it seems that Perl gets slower even on calling subroutine, however, we're talking about 1ml iterations.

**Example:**

```Perl
use Benchmark;
timethese(10000000, {
  'string_contains' => sub {
            if ( string_contains('Authentic Theme is Webmin/Usermin theme', 'theme') ) {
                # code
            }
        },
  'index()'     => sub {
            if ( index('Authentic Theme is Webmin/Usermin theme', 'theme') != -1 ) {
                # code
            }
        },
});

```

**Result:**

```Perl



Benchmark: timing 10000000 iterations of index(), string_contains...
  | index():          1 wallclock secs ( 0.76 usr +  0.00 sys =  0.76 CPU) @ 13157894.74/s (n=10000000)
  | string_contains:  3 wallclock secs ( 2.46 usr +  0.00 sys =  2.46 CPU) @ 4065040.65/s (n=10000000)
 
```

This is ridiculous in my point of view. Using subroutine as very basic abstraction layer, should not slow things down so much. Having all over the code `index() != -1` is very ugly and not only.

**Comment by qooob** [comment]
Alright, here is what I finally got. Will add this to the repo, after Jamie's or Joe's confirmation on whether is it safe or not to use unescaped `$value` in `grep`.

```Perl
sub string_contains
{
    return (index($_[0], $_[1]) != -1);
}

sub array_contains
{
    my ($e, $n, @a) = @_;
    if ($e eq 'exact') {
        return (grep {$_ eq $n} @a);
    } else {
        return grep {index($_, $n) != -1} @a;
    }
}

```

**Comment by gnadelwartz** [comment]
you are correct, and this is why l avoid subs and modules in perl whenever possible. now you can see the cause why most perl programmers use index and grep direct.

expensive subs are a resulting from perl is an interpreted language . also javascript suffered from this but with modern JIT engines this and other performance bottlenecks are gone.

**Comment by gnadelwartz** [comment]
it should be save because its only used for filtering. the returned result are the matching array elements ir an epmty array. I would say the array content is more dangerous 😎

**Comment by qooob** [comment]
> You are correct, and this is why l avoid subs and modules in perl whenever possible.

This is not only ugly but deprives abstraction, and couples code a lot.
What if tomorrow, Perl language will have super fast, 10 times faster `inbuilt_string_contains_super_fast()` sub with returing `true/false`. What are you going to do? 😄 Use your notepad with regex to replace it??  

> It should be save because its only used for filtering. The returned result are the matching array elements or an empty array. I would say the array content is more dangerous.

What do you mean? Are you suggesting that anything from `@array` can expand into executable command? I honestly doubt, that any saint programmer would let this into programming language itself.

If I understood you correctly neither `$value` from `grep` nor array keys from `@array` will ever be evaluated?

**Comment by gnadelwartz** [comment]
yes

**Comment by gnadelwartz** [comment]
>  What if tomorrow, Perl language will have super fast, 10 times faster inbuilt_string_contains_super_fast()

this will not happen in core perl :-)

**Comment by gnadelwartz** [comment]
from what l found on the web, this module implements many list operations in C and has the grep aquivalent tests any and all which are much faster.

`use List::Moreutils qw(any all)`
https://metacpan.org/pod/List::MoreUtils

you will love it 😍

**Comment by qooob** [comment]
I do like it. It's a bit over that what I need though. 

Thanks.

**Comment by qooob** [comment]
Alright, it seems that I just realized what Joe was explaining me on [The Trickiest Thing About Perl (for beginners)](http://swelljoe.com/post/the-trickiest-thing-about-perl/), some time ago.

Passing array as reference, makes me put it at the beginning at the list of params.

Example:

```Perl

sub array_contains
{
    my ($arr_ref, $search, $strict) = @_;
    if ($strict) {
        return (grep {$_ eq $search} @$arr_ref);
    } else {
        return grep {index($_, $search) != -1} @$arr_ref;
    }
}
```

Usage:

```Perl

if (array_contains(\@arr, '4')) {
  print 1;
} else {
  print 0;
}

```

Does it look right and more efficient?

**Comment by swelljoe** [comment]
Isn't this just version comparison? Why care about performance for something that happens only once in a while? Performance doesn't matter for something that happens very rarely. Worry about correctness and conciseness; not performance.

An array ref can be anywhere in the list of arguments. That's the point of using a ref instead of the array itself. If passing an array, it has to be the last argument; but, it's not recommended to pass an array if you'll be using more than one argument. If you're only using one or two pieces of the array in your function, it may make sense to just pass the specific elements of the array you need (by value) rather than the whole array (by reference). Especially since it just returns true/false; passing an array reference makes sense when you need to make changes to the array or act on many elements of the array or return a modified version of the array.

As for safety, grep is a Perl built-in that operates on arrays. It is not calling out to the system grep; escaping doesn't make sense in this context at all. You pass it a filter function and grep checks the filter function against every element in the given array. As long as user data isn't being used to set the filter function, it is safe with user-provided data.

**Comment by gnadelwartz** [comment]
yes, the issue was originally about version compairson, but ilia did't like grep and index all over in perl scripts and want to write an efficient sub to replace them. I think this was an important improvement  for his (and my) perl knowledge ...

**Comment by qooob** [comment]
Actually it wasn't for version comparison. I got rid of `Version::Compare` and replaced it with few strings of my code.

That code, with smartmatch `~~` that I used, was for extracting server's scanned ports for slider notifications, only that were referenced by user in ConfigServer Security Firewall configuration file, instead of sending all, that were going through the logs. Now, it's very efficient and informative compared to the past and produces just few messages, only every few days. (for me at least.)

**Comment by qooob** [comment]
If I got everything correctly, I consider it's done with the latest commit.

Thanks, Joe and Kay!

**Comment by gnadelwartz** [comment]
for getting an array of unique values try this:

       my @unique = keys map { $_, 1 } @array;

**Comment by gnadelwartz** [comment]
the fastest starts with implemetation I found is this one

``` perl
sub begins_with
{
    return substr($_[0], 0, length($_[1])) eq $_[1];
}
```

see https://stackoverflow.com/questions/31724503/most-efficient-way-to-check-if-string-starts-with-needle-in-perl

**Comment by qooob** [comment]
Thanks a lot, I'll check tomorrow.
