### ISSUE TITLE
Theme appears to have broken Webmin

### ISSUE THREAD

**Issue by b0blee** [qooob/authentic-theme#1018]
I'm running under Ubuntu 16.04, and all of my packages are up to date.  Webmin has broken. I'm getting the following error message, which points a finger at authentic-theme:
Error - Perl execution failed
Can't locate /authentic-init.pm in @INC (you may need to install the ::authentic-init module) (@INC contains: /usr/share/webmin/authentic-theme/lib /usr/share/webmin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base . /usr/share/webmin/ ..) at /usr/share/webmin/authentic-theme/authentic-lib.pm line 18. Compilation failed in require at /usr/share/webmin/authentic-theme/index.cgi line 10.

I would normally install a module from within Webmin.  How can I install the ::authentic-init module with a broken Webmin?

**Comment by swelljoe** [comment]
You don't need to install the authentic-init module. It is part of the theme.

Restarting Webmin will probably fix it. But, if it doesn't, you can force a fresh download of the theme with the `theme-update.sh` script found in the authentic-theme directory (or just grab the tarball from the downloads page and extract it into place). Then restart Webmin.

**Comment by b0blee** [comment]
Thanks for your help. It turned out that I had to run Webmin's
update-from-repo.sh script first. All is well now. Not an issue.

**Comment by gnadelwartz** [comment]
l guess that's mainly because the script does everything joe mentioned as a side effect 😀
nice to now ...

**Comment by qooob** [comment]
> Can't locate /authentic-init.pm ..

This error happens when `/etc/webmin/config` is overwritten with any other config from any other module. It happended to me only once and I could never figure out how and why.

I'm surprised that it's okay after running `update-from-repo.sh` script as it shouldn't touch `/etc/webmin` files at all. 

Kay, is that true that update script doesn't do anything to configuration files?

**Comment by b0blee** [comment]
To the best of my recollection, I was on the System/Software Package Updates page.  I had clicked "Only New" and before it returned I clicked "Installed", and then the error appeared.  There was nothing in the Webmin Actions Log.

The machine is a small DigitalOcean "droplet" with 2 GB RAM (no virtual memory) and a 30 GB disk.  It runs Ubuntu 16.04 and nginx to serve about a dozen very low volume web sites.  I've never seen RAM usage go over 60% - right now it's idling at about 33%.  The disk is about half full.  It runs pretty cool all the time, and has been trouble free for the past year.

**Comment by qooob** [comment]
Bob, thank you for your report. We'll do our best to nail it and fix it.

**Comment by gnadelwartz** [comment]
yes and no, it runs Jamie's setup.sh which rewrites some files in /etc/config, so the fix may be a side effect of:

- setup.sh
- update of athentic-theme
- restart of webmin

update-from-repo.sh seems to be the universal fix 😂

**Comment by qooob** [comment]
Neither restart nor updating the theme going to fix this issue.

**Comment by gnadelwartz** [comment]
then it was setup.sh which seems to discard the wrong config file and wrote a new and working default config.

**Comment by qooob** [comment]
That is good to know. It seems very like it.
