### ISSUE TITLE
19.09.1 dashboard is reporting "this version is outdated"

### ISSUE THREAD

**Issue by FBachofner** [qooob/authentic-theme#1019]
19.09.1 dashboard is reporting on the webmin line: "1.870" in RED text and with a light-red background and "this version is outdated" (a tool-tip)

The Webmin.com website indicates 1.870 to be the most recent stable version . . .

**Comment by gnadelwartz** [comment]
yes, this is true. ilia made a change in theme which needs a feature from 1.873 version.

you have two possibilities: downgrade authentic to 19.08 or upgrade webmin to 1.873

**Comment by gnadelwartz** [comment]
did upgrade to 1.873 fix the problem?

**Comment by qooob** [comment]
In case everything works, just ignore this message. In repos there were already 1.872 available, as far as I remember.

**Comment by FBachofner** [comment]
Thank you @gnadelwartz for pointing this out and thank you @qooob for adding a warning dialog to the 19.0.2 update which points out that one can upgrade easily from repos with the script: "update-from-repos.sh"   [ I didn't know that script was there! ]

I am now running Webmin 1.873.0220.2122 and the error has gone away.

**Comment by gnadelwartz** [comment]
I created the script primarily for testing newest develooments and lang uodates,
now it is stable enough that ilia thinks its a great addition to 0oit to it.

schönes Wochenende...

**Comment by FBachofner** [comment]
Cool.  And I see you are committing both to Authentic-Theme _and_ Webmin.  This crossover is likely to really benefit both projects.

Thanks for all your help.

Und . . . ebenfalls!  :-)
