### ISSUE TITLE
Popup panel on Login

### ISSUE THREAD

**Issue by profpivec** [qooob/authentic-theme#1020]
I am using Authentic theme 19.07 on Ubuntu 16.04.2 with Webmin 1.872.  

I switched to the night screen sometime ago as I like the darker colours, but I have noticed that I get a Popup on Login that I have never seen before.  It may not be connected to the night theme, or even the theme itself, but I am at a loss as to what it is. Even my server hosting experts dont know :/

It does not always happen and I cannot reproduce it at will. I also do not know what to click when it appears. Has anyone seen this or know what it is Please.

![false](https://user-images.githubusercontent.com/30598444/36412790-f97774fe-161b-11e8-9278-9aab09d8a2e3.jpeg)

Thanks in advance.

**Comment by qooob** [comment]
Interesting.

When you see this screen, what happens if you reload the page simply?

You must update to 19.09.1, because 19.07 is dated.

**Comment by profpivec** [comment]
Thanks for the reply. I have updated to 19.07 by forcing an update (no idea why it didn't display that it needed one).

Referring to the above jpeg, if I click on the right button, the popup closes but some of the button text on other screens are labelled "false" and not what they should be labeled until I reload the page. 

If I click on the left button, the popup is closed and everything appears to be normal.

This popup does not always appear, usually at the start of day or if I have not been on WebMin for a while.

Thanks

**Comment by qooob** [comment]
Yes, it wouldn't display anything, there was a change at the code, regarding to versioning. 
Could you force update the theme to the latest?

**_But before that:_**

Can you make sure that the session is active? Like, click at Dashboard for example and make sure that it opens. _Then_ right click (context-menu) on the logout button and click Open at New Tab. _Then_  click Dashboard again, or any other link you can find.

_Will you get the same popup screen again??_

**Comment by qooob** [comment]
Did you use:

1. Proxy?
2. Servers Index?
3. Cloudmin?

**Comment by profpivec** [comment]
Not as far as I know. I am logging on from my home office system where I always work.

**Comment by qooob** [comment]
What browser are you using?

**Comment by profpivec** [comment]
Mac Safari V 11.0.3

**Comment by qooob** [comment]
Okay, I'll take a closer look on Safari. Thanks.

And it just happens after, supposedly your session expires?

**Comment by profpivec** [comment]
Appears so, but intermittently. I just tried on Firefox, I got the Session expired popup, but not the "false" (although I dont always get that on Safari either).

Thanks in advance

**Comment by qooob** [comment]
Interesting.

I tried Safari in incognito mode, then terminated the session, and clicked a link - popup came with all texts in-place. 

I can't reproduce it. It seems as caching issue.

**Comment by profpivec** [comment]
Thanks. At least I know what the popup is now and what the buttons should be.

Cheers.

**Comment by qooob** [comment]
Cheers.

You would not be able to get `false` strings only on that part of the interface. It would happen all over.

The only reasonable explanation that I have is server caching that doesn't push latest files.

What is your language set to?

**Comment by profpivec** [comment]
I don't recall setting any language field. My Mac is in English, but I dont remember setting Language on the server. Where should I check?

**Comment by qooob** [comment]
I think it's just English.

It's in Webmin Configuration/Language or in Webmin/Change Language and Theme.

**Comment by profpivec** [comment]
It defaults to Global Language. Should I set the choice to English?
![jpeg](https://user-images.githubusercontent.com/30598444/36424462-a5069c6a-1643-11e8-9aa8-5da7a156210a.jpeg)

**Comment by qooob** [comment]
Check what is global set to in _Webmin Configuration/Language_

**Comment by profpivec** [comment]
English US but use browser language is off.

![untitled](https://user-images.githubusercontent.com/30598444/36424582-08ba3a0a-1644-11e8-9319-8f5f7ba2d2b8.jpeg)

**Comment by qooob** [comment]
It's all cool.

All should be just fine.

**Comment by profpivec** [comment]
Excellent, thanks again.

**Comment by gnadelwartz** [comment]
hi ilia, I got the also the session expired popup with everything displaying 'false' on chrome.
strange ...

**Comment by profpivec** [comment]
gnadelwartz: this is the dialog box it is supposed to be.  It is your session timing out and for some reason the fields are not being updated in the popup. I have not had it since the latest update (19.09.2), but it only appears sporadically anyway, so time will tell.

![36416943-db58f6be-162a-11e8-93b1-be5bc5899c3f](https://user-images.githubusercontent.com/30598444/36638819-609dbf40-19fe-11e8-84d1-ccd2a0a46685.jpeg)

**Comment by qooob** [comment]
I'd like to know, if it happens again. I have an idea remotely of why it could happen but not sure yet.

**Comment by gnadelwartz** [comment]
here also! is it a issue of time?

**Comment by profpivec** [comment]
I use Safari exclusively for my WebMin server management. It usually happens when I have closed the window as I dont usually log out. Hence when I start the browser again and select the WebMin window from my bookmarks, the session has often timed out. 

I select the right "false" (re-authentice) and it unlocks things normally. Although sometimes I have seen other buttons labeled "false" even once I am in. I refresh the browser and all is labeled correctly. 

Hence it is only a text issue, the labels probably have localisation associated with them, and this is not being picked up correctly. My guess anyway, as this is what happen when I have screwed up localisation in Unity. 

Hope this helps. Dont stress, now I know what it is, it is no drama. ;)

**Comment by qooob** [comment]
No, no. It has to be perfect. I'll find the source of the issue; hate fixing just only the outcome.

Do you use private tab?

Thank you for reporting.

**Comment by profpivec** [comment]
No, I do not use a private window. Hence my password is always cached. But it is a private computer. ;)

Cheers.

**Comment by gnadelwartz** [comment]
the false problem happens also on update popup
![screenshot_20180228-074648](https://user-images.githubusercontent.com/4593242/36773808-c6d29b96-1c5b-11e8-8418-80da88cebf50.png)

**Comment by qooob** [comment]
Fixed at https://github.com/qooob/authentic-theme/commit/830ee347923146ed4fe237f9b103cc3cba7ecfb4

**Comment by profpivec** [comment]
Not sure it is fixed. Installed 19.10beta 1 and still got this.
![pic](https://user-images.githubusercontent.com/30598444/37078951-368a6df8-21e1-11e8-9e2b-a9438cb02552.jpeg)

**Comment by qooob** [comment]
I can not reproduce it.

Please provide steps to reproduce it. Starting from which browser and OS for client/server was that, installed browser plugins, Language settings.

Did you clear browser's cache after installing the update?

**Comment by profpivec** [comment]
Nope, didn't clear cache. Will do that and see if it happens again. 

Client is Mac osx 10.13.3, using Safari 11.0.3, no installed plugins.
Server is Ubuntu 16.04.2, Usermin 1.734, Webmin, 1.880, default language of English.

**Comment by qooob** [comment]
Here is the problem. I logged in to Safari, then I opened private tab, logged in and flushed the first session, when I came back, I saw the following:

![20180307_104446](https://user-images.githubusercontent.com/4426533/37079758-c619c488-21f4-11e8-96a8-c2aab1749b8f.jpg)

**Comment by gnadelwartz** [comment]
I have again the same problem on tablet with Yandex browser, but this is a strange beast regarding cache. even if you clear the cache it had files in the cache for 24 more hours, may be because of android doing also some caching :-(

On Desktop it work's like it should (Yandex, Vivaldi, Chrome, Firefox) ...
