### ISSUE TITLE
Server Index and adding Cluster

### ISSUE THREAD

**Issue by ReptoxX** [qooob/authentic-theme#1021]
I am currently facing two errors.

**1**: Still having the same issue like he did: #925 
**2**: Can not add servers to (When pressing on the button "Add server" nothing happens)
- *Cluster Webmin Servers*
- *Cluster Usermin Servers*
- *Cluster Software Packages*

But **Cluster Users and Groups** is working.

Everything works, when switching to an other Theme.

Webmin Version: **1.870**
Authentic Theme Version: **19.09.1**

**Comment by qooob** [comment]
It's fixed with the latest Git version of Webmin.

**Comment by qooob** [comment]
There are more fixes to be done.

**Comment by qooob** [comment]
Thank you for reporting. It will be fixed upon next Webmin release.
