### ISSUE TITLE
Slight alteration

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#1022]
We now have real tome graphs displaying CPU,Memory and disk space .. great  but perhaps the other data such as system up time and time on system also need to update

**Comment by gnadelwartz** [comment]
indeed, this comes to my mind yesterday also ...
to not push more load on the server time may increased locally in the browser

**Comment by gnadelwartz** [comment]
hm, time is updated, only system uptime not.so its the only not updated value ...

**Comment by qooob** [comment]
System update by default updated very 5 minutes.

All other important strings, such as Load Average, Running processes and others are updated in real-time.
