### ISSUE TITLE
English time format shown in dashboard with autodetected german lang

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#1026]
when I set system lang to en-utf8 and enabled use browser language webmin detects correctly german lang of my browser and use it.

on dashboard everything is displayed in german, only the system time is displayed in english time format...
![screenshot_20180224-131016](https://user-images.githubusercontent.com/4593242/36630324-0c335422-1965-11e8-8846-d24ada6083e8.png)

**Comment by qooob** [comment]
What is the output of `settings_window_replaced_timestamp_format_full` in console?

**Comment by qooob** [comment]
Then it should be displayed:

Okay, what is the output of `get_server_data("language-full")`?

**Comment by gnadelwartz** [comment]
it's "en"

**Comment by qooob** [comment]
That is strange.

What os the output of `get_server_data("language")`?

**Comment by gnadelwartz** [comment]
en

**Comment by qooob** [comment]
How is that possible? :smile: 

What are the settings in Webmin Configiration module?

**Comment by gnadelwartz** [comment]
![image](https://user-images.githubusercontent.com/4593242/36630446-b61979ca-1966-11e8-8510-8c9b799f5af4.png)

**Comment by qooob** [comment]
I see now.

**Comment by gnadelwartz** [comment]
last login is nearly correct, german time format, but with `/` instead of `:` 
![image](https://user-images.githubusercontent.com/4593242/36630481-44011c34-1967-11e8-88f2-2c0ded2a60ee.png)

**Comment by qooob** [comment]
It's always a pleasure to fix logic, fast, clean and straight forward, unlike presentation.
