### ISSUE TITLE
Checking for developmental versions even with option set to No

### ISSUE THREAD

**Issue by MorningSleeper** [qooob/authentic-theme#1028]
![image](https://user-images.githubusercontent.com/8920632/36692247-72e1633e-1aec-11e8-9ee4-153a465872c5.png)

![image](https://user-images.githubusercontent.com/8920632/36692342-a6237d5e-1aec-11e8-8df2-3109c971596f.png)

I used to have it set to Yes but have changed it to No, saved, cleared cache, yet it still keeps checking.

**Comment by qooob** [comment]
19.09.x in bit development version. 😉 Development version is marked with `-[beta|RC]`.

**Comment by qooob** [comment]
19.09.x is not a development version. 😉 Development version is marked with `-[beta|RC]`.

**Comment by MorningSleeper** [comment]
Well then how come when I go to update it it states that it is ...

![image](https://user-images.githubusercontent.com/8920632/36693161-409b5f44-1aef-11e8-981b-1b3de76ab479.png)

**Comment by qooob** [comment]
Yes, this exact translation ambiguity been fixed on 19.09.2.
