### ISSUE TITLE
DataTable Sorting

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#103]
I just discovered a bug with the "DataTable" sorting implementation.

When I sort the "Edit Users" page by "Quota used" (highest to lowest) I'm getting the following order.

888 kB
73.73 MB
712 kB
675.03 MB
6.80 MB
552 kB
3.69 GB

The order I was sorta expecting was

3.69 GB
675.03 MB
73.73 MB
6.80 MB
888 kB
712 kB
552 kB

Perhaps converting the measurements to say MB or GB for all values would fix this issue as I can sorta see why the "DataTable" might be doing what it is. Simply put it doesn't understand the different between the measurements used.

On a much much much more tinier note, should you continue to make use of "kB", "MB" and "GB" references, I believe "kB" needs to be converted to "KB" for the abbreviation.

Cheers!

**Comment by tpnsolutions** [comment]
It looks like the developer of DataTabe has taken into account the file size matter. Here's some info which may be helpful in making the appropriate fix.

https://datatables.net/plug-ins/sorting/file-size

**Comment by qooob** [comment]
Sounds good. I'm at (+0400). I will do that one day. Need to continue work on Karateka (karateka.org). 

P.S. Try adding this plugin and see if it works (and let me know). You could use new `script injection` mechanism. https://github.com/qooob/authentic-theme#how-do-i-load-custom-scripts

**Comment by tpnsolutions** [comment]
I'm attempting to apply the "file-size" plugin, but having some troubles identifying references from your plugin.

Here's the content of my "scripts.js" file:

```
jQuery.extend(jQuery.fn.dataTableExt.oSort,{
	'file-size-pre': function(a) {
		var x = a.substring(0,a.length - 2);
		
		switch((a.substring((a.length - 2),a.length).toLowerCase())) {
			case 'kb':
			var x_unit = 1;
			break;
			
			case 'mb':
			var x_unit = 1000;
			break;
			
			case 'gb':
			var x_unit = 1000000;
			break;
		}

		return parseInt(x * x_unit,10);
	},
	'file-size-asc': function(a,b) {
		return ((a < b) ? -1 : ((a > b) ? 1 : 0));
	},
	'file-size-desc': function(a,b) {
		return ((a < b) ? 1 : ((a > b) ? -1 : 0));
	}
});

$('#DataTables_Table_0').dataTable({
	'columnDefs': [{
		'type': 'file-size',
		'target': 0
	}]
});
```

The bottom "#DataTables_Table_0" was just a guess at implementing. Though the reference to this plugin doesn't really clarify anything, and I've never worked with the DataTable plugin before so I may be missing something.

**Comment by qooob** [comment]
Hmm.. Not sure, try the following:

```
if (($current_page_full.indexOf('.cgi') === -1 || $current_page_full == '/init/index.cgi') && ($current_page == 'virtual-server/' || $current_page == 'init/' || $current_page == 'mount/' || $current_page == 'quota/' || $current_page == 'fsdump/' || $current_page == 'inittab/' || $current_page == 'logrotate/' || $current_page == 'mailcap/' || $current_page == 'cron/' || $current_page == 'software/' || $current_page == 'syslog/' || $current_page == 'useradmin/' || $current_page == 'apache/' || $current_page == 'webalizer/' || $current_page == 'cpan/' || $current_page == 'htaccess-htpasswd/' || $current_page == 'fdisk/') || $current_page_full == '/man/search.cgi' || $current_page_full == '/proc/index_tree.cgi' || $current_page_full == '/proc/index_user.cgi' || $current_page_full == '/proc/index_size.cgi' || $current_page_full == '/proc/index_cpu.cgi' || $current_page_full == '/proc/index_search.cgi' || $current_page_full == '/software/search.cgi' || $current_page_full == '/virtual-server/index.cgi' || $current_page_full == '/virtual-server/list_users.cgi' || $current_page_full == '/virtual-server/edit_newplan.cgi' || $current_page_full == '/virtual-server/edit_newfeatures.cgi' || $current_page_full == '/virtual-server/edit_newtmpl.cgi' || $current_page_full == '/virtual-server/backuplog.cgi' || $current_page_full == '/package-updates/index.cgi') {
	$('table').each(function () {
		if ($(this).find('thead').length && $(this).find('thead tr th').length > 2) {
			$.fn.dataTableExt.sErrMode = 'throw';
			$(this).dataTable({
				'type': 'file-size',
				"order": [],
				"aaSorting": [],
				"bDestroy": true,
				"bPaginate": false,
				"bInfo": false,
				"bFilter": false,
				"destroy": true
			});

		}
	});
}
```

**Comment by qooob** [comment]
It actually works! :)

**Comment by qooob** [comment]
Support will be added in version 10.0.0. Thanks for pointing out! ;)
