### ISSUE TITLE
Explain Recent Login Colours

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#1030]
Hi 
something I have been looking at for a while and don't see a reason for it 
![rl](https://user-images.githubusercontent.com/4038510/36755799-2d7cdd40-1c05-11e8-9425-7bf6cb9b2154.png)
'This login' I get but I don't get the 2 colours for logged in ... I guess there is a reason but can you tell me what it is just in case I need to be aware

**Comment by qooob** [comment]
This question should be asked at @jcameron, as far as I understand. Theme doesn't don anything in this regard.

**Comment by jcameron** [comment]
Green = current user
Black = login from the system you're currently on
Orange = login from another system
