### ISSUE TITLE
Same Webmin version as Authentic theme?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1033]
Is this really correct?
![image](https://user-images.githubusercontent.com/5789283/36939803-e3695888-1f37-11e8-8f1d-33898d479a07.png)
After manual updating the theme, it is now showing `19.09.2`

**Comment by qooob** [comment]
Unless Jamie changed its version, this shouldn't happen.

**Comment by qooob** [comment]
It's not correct. :persevere:

**Comment by qooob** [comment]
Okay, the version 1.880 is not out yet?? :laughing: If so, this is great that you reported it. I let Jamie know!

**Comment by qooob** [comment]
Webmin compiler seems to be changing it.

**Comment by qooob** [comment]
Yes, right. New package in dev repo already. If you find any bugs please report it, as new release is about to come.
