### ISSUE TITLE
Theme: Respect theme configuration options for updates

### ISSUE THREAD

**Issue by dexterns88** [qooob/authentic-theme#1038]
Why beta version is in regular theme update. I get update for authentic-theme on my virtualmin 
'Authentic Theme 19.09.2. Latest available release 19.10' no info about beta version here. 
When try to update get error 

> Installing this version of Authentic Theme 19.10-beta1 requires latest and/or possibly unreleased version of Usermin 1.740 to work properly.

Beta update should be go on another branch not in master. Master need to be latest stable version.

**Comment by qooob** [comment]
How did you get this message? On right side notification panel?

What do you have set in _Theme Configuration/Software Updates_? Do you have `Including development versions` set to _Yes_?

**Comment by qooob** [comment]
After making more tests, I confirm that this is a bug.

**Comment by skoumal** [comment]
I have another issue with the version 19.10(-beta1). My webmin says: Authentic Theme 19.10-beta1. Latest available release 19.10. When I click on Update button, the version 19.10-beta1 is installed again, with the same message about 'latest available release'. When I try to download the version 19.10 I get to a 404-page.

**Comment by qooob** [comment]
It's a bug. I'll fix it when I get to the PC. 19.10 is not yet released. Only beta.

**Comment by qooob** [comment]
Thanks for reporting.

**Comment by dexterns88** [comment]
I still have an issue where he trying to install 19.10-beta1 with the message, "requires latest and/or possibly unreleased version of Usermin " in theme settings 

Including development version is off 

And after clear cache, it's the same situation.

**Comment by qooob** [comment]
Try to update to latest 19.10-beta1 and then, update again. The message should be right at that point and in the future.

I will double check.

**Comment by qooob** [comment]
Just to get more details: from which version you were trying to install an update?

**Comment by dexterns88** [comment]
![theme](https://user-images.githubusercontent.com/1290174/37057565-17307294-2188-11e8-86fa-61f056968ee0.PNG)

Can't update to 19.10-beta1 I'm sending screenshot.

**Comment by qooob** [comment]
Click here link and force install it? Or disable updating theme for Usermin in theme's configuration.

It's designed to display such message.
