### ISSUE TITLE
Theme: Add notification upon enabled caps-lock for password inputs

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#1039]
It would be great to let user know when the **caps lock** is on on entering passwords.

![screenshot from 2018-03-06 16-54-47](https://user-images.githubusercontent.com/4426533/37035969-52493a7e-215f-11e8-93e4-ea2a932a80b0.png)

**Comment by Sopor-** [comment]
Are users still struggling with caps lock :smiley:

**Comment by qooob** [comment]
I don't know. It's for the better UX. I just thought that not all users have indicators on the keyboard or at status bar.
