### ISSUE TITLE
Usermin Mailbox Folders

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#104]
I was parsing through Usermin this evening and notice that the "mailbox folder" tree is missing from the left panel of your theme.

Not sure if this was intentional, accidentally missing or something being worked on. However I thought I'd be bring it to your attention as this definitely needs to be addressed since most use Usermin if not for anything else but a "webmail" tool.

By folder tree I am referring to:

Inbox
Sent
Spam
Trash
etc
etc

Cheers!

**Comment by qooob** [comment]
Do you mean mentioned folders should be on the right? Can you please provide screenshot?

**Comment by tpnsolutions** [comment]
See screenshot below which shows the "folders" in the default Virtualmin Framed theme.

Further to the topic, I noticed just now that there are a bunch of other useful links within their theme including:

- Manage Folders
- Address Book
- Mail Preferences
- etc

![authentic-usermin-missing-folders](https://cloud.githubusercontent.com/assets/4305218/6105084/470e77da-b008-11e4-968a-4c981a904a05.png)

**Comment by qooob** [comment]
Uff. I see. Will try fixing it in the next release. Thanks.

**Comment by tpnsolutions** [comment]
As always, your attention to these matters is greatly appreciated!

BTW, where are you located (which timezone)?

I'm from British Columbia, Canada (3:00 am PST)

We should sit down and have a discussion sometime (over Skype) as I deal with quite a few Virtualmin users.

You can read what I'm all about, and the feedback folks have left at:

http://virtualmin.com/node/25081

Drop me a line on Skype sometime, my username is: tpnsupport

**Comment by qooob** [comment]
Sounds good. I'm at (+0400). I will do that one day. Need to continue work on Karateka (karateka.org). 

P.S. Try adding this plugin and see if it works (and let me know). You could use new `script injection` mechanism. https://github.com/qooob/authentic-theme#how-do-i-load-custom-scripts

**Comment by qooob** [comment]
What do you use as OS do you have Empathy (Fedora/Ubuntu have it)

**Comment by tpnsolutions** [comment]
On my desktop and laptop I run Ubuntu 14.04 and 14.10 respectively. I use Google Chrome (not Chromium) for my browser.

**Comment by qooob** [comment]
Can you install Empathy? I could call you using that (you would have to have Jabber IM) - free and nice alternatives to Skype/Viber and etc. If it's a problem I will install Skype on my Linux..

**Comment by tpnsolutions** [comment]
I'm more of a Skype guy... Don't really do voice chats very often either (not setup intentionally) as I find I can better multi-task over a "text-based" conversation.

**Comment by qooob** [comment]
When I jail Skype and have time, will let you know!

**Comment by tpnsolutions** [comment]
It turns out, I had Empathy installed all along... Lolz

Look me up by email address: pknowles@tpnsolutions.com

**Comment by qooob** [comment]
Yes, I know! It's default for Ubuntu.

**Comment by qooob** [comment]
How can you don't run xmpp server?

**Comment by tpnsolutions** [comment]
Let's take this chat over to: http://tpnsolutions.com

In the bottom right corner, click to expand the "chat". Not sure why I didn't about this earlier. Lolz

You can even "pop out" the chat window so it appears in an IM like way allowing you to multi-task.

**Comment by tpnsolutions** [comment]
Woah, totally just realized what time it was... Lolz... I'm gonna hit the hay for a few hours, gotta technically be operational within an hour... argh... Likely will sleep in til closer to 9am PST (if a client doesn't call or text me before then, knock on wood).

Later!

**Comment by qooob** [comment]
I'm at work for another 4 hours.

Later.

**Comment by qooob** [comment]
This feature and complete support for all parent folders and the rest of the left menu is added in version 10.0.0, which is released within couple of days!
