### ISSUE TITLE
File Manager: Stuck post-upload dialog

### ISSUE THREAD

**Issue by teryongster** [qooob/authentic-theme#1041]
File Upload Modal Not Closing After A Successful Upload
![screenshot from 2018-03-07 12-55-32](https://user-images.githubusercontent.com/25061004/37074286-f9c77688-2206-11e8-873f-46352e0516c6.png)

**Comment by BiLosxD** [comment]
I having this issue also. Please Help. Thanks

**Comment by qooob** [comment]
What theme version exactly do you run?

**Comment by dummyuserrr** [comment]
The default theme after a fresh install.

**Comment by qooob** [comment]
Please go to the Dashboard and tell me what is Authentic Theme number you got there?

**Comment by dummyuserrr** [comment]
I'm having this isseu when I use theme 19.09 to 19.10-beta1

**Comment by qooob** [comment]
It shouldn't happen on 19.10-beta1, just as not should happen on 19.09.2.

I double checked it. It's the cache issue. Please clear browser's cache and try again.

**Comment by dummyuserrr** [comment]
Clearing the browser's cache didn't fix it. I tried reinstalling everything and it's fine. The only issue left is it takes a very long time for the modal to close. I uploaded a 1KB file.

**Comment by qooob** [comment]
Have a look. Isn't it the same for you?

[Video-screencast example.](https://rostovtsev.ru/pub/src/authentic/19.10-beta1/dismiss_upload_screen.webm)

Could you make a video-screencast of how it works for you?

**Comment by dummyuserrr** [comment]
https://vimeo.com/258939800

**Comment by qooob** [comment]
I see now. Can you open the private window, login and try again?

What happens if you close the modal window by clicking the cross button and refresh directory content manually?

What happens if you upload large file?

**Comment by dummyuserrr** [comment]
The file uploads successfully. It just takes long time for the modal to close.

**Comment by qooob** [comment]
Open the private (incognito) tab in browser, login and try again. Waht do you get?

**Comment by dummyuserrr** [comment]
Same thing. The file uploads successfully but the modal doesn't close right away.

**Comment by fdmgit** [comment]
I have the same issue as dummyuserrr. 
Modal doesn't close after successful upload.
I've the latest dev version of authentic theme

**Comment by qooob** [comment]
And the exact installed version of the theme is?

**Comment by qooob** [comment]
@fdmgit What is your browser/OS?

**Comment by fdmgit** [comment]
Authentic Theme 19.10-beta1
Browser: 
Safari 11.1 (11605.1.29)
Firefox 59.0
Google Chrome 65.0.3325.146

OS: 
OS X 10.11.6 (15G20011)

**Comment by qooob** [comment]
I have tried it on my MacBook Air with MacOS 10.13.3 and Safari 11.0.3 - it worked just fine. (could provide video-screencast if needed).

Sorry guys, at the moment, I can't do much of anything!

**Comment by fdmgit** [comment]
Hi Ilia

did some additional testing. 

Case 1:     OSX 10.11.6  / Safari 11.1
Case 2:     OSX 10.11.6  / Firefox 59.0
Case 3:     OSX 10.13.3  / Safari 11.0.3
Case 4:     OSX 10.13.3  / Firefox 58.0.2

Server:
Webmin 1.880
Authentic Theme  19.10-beta1

For all cases I uploaded a small file (800kb). 

The results is for all cases the same: 60 sec delay after file upload before the modal closes. 

Guess that a dependency on OS or browser can pretty much be excluded.

**Comment by qooob** [comment]
@fdmgit Flavio, I can _not_ reproduce it. I tried with many files on different machines and OSs. It just works.


Do the following. Tell me what is the size of the loaded file `authentic-theme/extensions/file-manager/file-manager.min.js` in bytes?

**Comment by fdmgit** [comment]
the file size of file-manager.min.js is 172714 bytes.

**Comment by qooob** [comment]
Looks good. I need more debug info from you. Open network tab, when you hit upload, see what's happening? Better do video-screencast with opened console. It would help me a lot! :wink:

**Comment by fdmgit** [comment]
I run a quick network analysis (see attached HAR file). 
At the first glance it looks like the uptracker.cgi task needs 61 sec to complete. 

I'll do a more thorough analysis later on. 

[FileUpload.har.txt](https://github.com/qooob/authentic-theme/files/1793016/FileUpload.har.txt)
{---> rename file to FileUpload.har}

**Comment by qooob** [comment]
What is your server OS?

**Comment by fdmgit** [comment]
The server is running Ubuntu Server 16.04.3 with all security patches applied.

**Comment by Sopor-** [comment]
I can confirm it. I get the same behavior. I can see the file get added behind the upload window but then it takes minutes before it closes.
Operating system 	Ubuntu Linux 16.04.1
Webmin version 	1.880
Usermin version 	1.740
Virtualmin version 	6.02-3
Theme version 	Authentic Theme 19.10-beta2

**Comment by qooob** [comment]
Does it close immediately when trying it on the same system in Gray Theme, for example?

**Comment by Sopor-** [comment]
I tried `Old webmin theme` and it took 1 second and the window was gone.

**Comment by Sopor-** [comment]
@qooob when changing theme it will open a new tab in the browser. I haven't seen that before :(

**Comment by qooob** [comment]
Downloading Ubuntu 16.04.4 LTS. Is that 32bit or 64bit system?

**Comment by fdmgit** [comment]
On our servers we run the 64-bit server edition

**Comment by qooob** [comment]
Installing, setting up and let you know later. 

Thanks.

**Comment by qooob** [comment]
How much resources you have allocated to it? RAM, Disk and Swap?

**Comment by fdmgit** [comment]
Here the details

![testserver](https://user-images.githubusercontent.com/29498370/37330429-5fe78b80-26a1-11e8-92cd-e35e2272f7c8.png)

**Comment by Sopor-** [comment]
@qooob I get the same behavior in Ubuntu 14.04.3

**Comment by qooob** [comment]
Installed Ubuntu Linux 16.04.4 - no issue.

Do you use proxy or default setup?

**Comment by fdmgit** [comment]
@qooob

Hi Ilia

We have multiple Webmin users on our servers defined. 

Now if I login as e.g. 'administrator' then I get the effect described previously (= modal delay). 
However if I login as 'root' then it works perfectly. 

Have tested it on different servers and it's reproducible.

**Comment by qooob** [comment]
It's very hard to believe but I will double check with other user names. 

Thanks for nailing down the bug.

**Comment by trancef0rmer** [comment]
I have the same issue. v. 19.09.2, Debian 8 x64, Firefox 59, Chrome 65. fresh install

**Comment by qooob** [comment]
Thanks. I'll finish the tree-view and take very close look.

**Comment by gnadelwartz** [comment]
are you are using webmin users or from other sources?
e.g. pam, ldap etc.

does it work if you login as a real webmin user, eg. root or admin?

**Comment by gnadelwartz** [comment]
OK, I can confim updload dialog stay for ~30s after upload is done if you are logged in by a user from pam or LDAP. 

Logged in as directly as root it's working as expected.

**Comment by qooob** [comment]
I see the source of the bug. Fixing ..

**Comment by qooob** [comment]
Okay, it's fixed.

You will also now going to be able to see missing upload progress for large files.

Thank you for reporting and patience.

**Comment by Sopor-** [comment]
When i was starting with Linux i was told not to login as root and i have continued to do that and there is no reason to login as root in Webmin. The user only need to be able to use sudo.

**Comment by fdmgit** [comment]
It works. 👍

**Comment by gnadelwartz** [comment]
you are always work as user root from webmin, even you use an  other  username.
webmin uses usernames only for acls and settings.
