### ISSUE TITLE
Theme: Subversion Repositories Service, Virtualmin - No button clicked!

### ISSUE THREAD

**Issue by rwakcjr** [qooob/authentic-theme#1042]
Hi, I believe there is a bug reapearence in the theme because I get "No button clicked!" on all of the Actions buttons, but they work in the "Old Webmin Theme"

Operating system | CentOS Linux 7.4.1708
Webmin version | 1.880 
Usermin version | 1.734
Virtualmin version | 6.02 
Theme version | Authentic Theme 19.09.2
Kernel and CPU | Linux 3.10.0-693.17.1.el7.x86_64 on x86_64

**Comment by qooob** [comment]
Thanks a lot.

It's fixed and beautified.

**Comment by qooob** [comment]
Wait, something went wrong upon the commit. Fixing ...

**Comment by qooob** [comment]
Okay, done. Please give it a try.

**Comment by rwakcjr** [comment]
Works like a charm and looks great. Thank you.
