### ISSUE TITLE
Ie not supported

### ISSUE THREAD

**Issue by Zen4All** [qooob/authentic-theme#1043]
start RAND

Today I had to use IE11 to go to my server and got the unpleasant and very annoying warning that IE is no longer supported.
Why not????? It is still a supported browser by Microsoft. Not all people are able to use Edge, or something else. Also one warning is enough, it gets very annoying at each mouse click.

end RAND

Otherwise, i am a big fan of the theme.

**Comment by qooob** [comment]
Hi,

It's been discussed already. Please have a look. https://github.com/qooob/authentic-theme/issues/818#issuecomment-351792470

**Comment by Zen4All** [comment]
OK, had looked for an existing issue, as I could not image no one else complained. Will continue there
