### ISSUE TITLE
Unjustified prompt to upgrade Authentic in virtualmin

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [qooob/authentic-theme#1044]
Hello! As seen on the attached screenshots
![delete1](https://user-images.githubusercontent.com/29028445/37204237-6cb7d7c0-2390-11e8-94bb-c2388ce931af.jpg)
![delete2](https://user-images.githubusercontent.com/29028445/37204238-6cd071a4-2390-11e8-9f78-cc0f3c02a913.jpg)
I'm getting a notification to upgrade Authentic even though nothing in my virtualmin is officially compatible yet. As it's a production server, I'll be a good boy and wait for stable releases and - that's the proper philosophy and practice - virtualmin isn't sending me notifications about beta versions.

I think that's the way Authentic should behave, send notifications only for stable versions, leaving the testing of beta versions to those who enjoy the thrill of adventure.

I checked in the options for Authentic, still, and the option to be notified of testing versions isn't ticked:
![delete3](https://user-images.githubusercontent.com/29028445/37204355-dc5e8fce-2390-11e8-806e-fea5e1327271.jpg)

Good day to you!

**Comment by qooob** [comment]
I like the idea of combining beta version notification with enabling check for betas in theme configuration.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
I wouldn't have even imagined they were not already paired. I suspected getting beta version notifications requiring beta panel versions was an accident, my bad.So, yeah, I think we shouldn't be offered a beta update if both conditions aren't m met, have the proper webmin & usermin versions in place, and tick to receive test versions... Le 9 mars 2018 12:40, Ilia Rostovtsev <notifications@github.com> a écrit :I like the idea of combining beta version notification with enabling check for betas in theme configuration.

**Comment by qooob** [comment]
Done.

Thanks fore reporting.
