### ISSUE TITLE
System Logs Module Problem

### ISSUE THREAD

**Issue by strangealien** [qooob/authentic-theme#1045]
Using the system logs module, there is a problem: If I open the configuration for the module, I can add 'other log files to show'.
I have 5 additional files there, each one in a separate line. Saving and closing the configuration yields the new logfiles, and I can use them. But every time, when I open the configuration again, all the logfile paths are concatenated in a single line, without anything in between. If I change something other than the logfiles, I loose my logfiles, because it becomes an unreadable long string, which makes no sense.
So the /n symbols are not preserved, and using semicolons or something like this does not work also. I need to edit this window every time I open the configuration and save it afterwards.
To repeat the bug:
Add more than one log files strings (i.e. /var/log/something1.log and /var/log/something2.log) to the window, each logfile in one line. Save and close, and you will have the logfiles pinned. Then try to change something again in the configuration, and your log file strings will become one long string.
I am using 19.10-beta-1 Authentic Thema.
Very nice theme, btw. ! :)

**Comment by qooob** [comment]
Hi,

Thank you for reporting.

What would happen if you switched to Gray Theme and tried it there?

**Comment by qooob** [comment]
I confirm that this is the theme bug.

I'll fix it. Thanks.

**Comment by qooob** [comment]
It's fixed. Thanks.

It affected things globally, so this fix will be applied to all configuration pages, that are wrapped into accordions by the theme.
