### ISSUE TITLE
selectable default "show # entries" in File Manager

### ISSUE THREAD

**Issue by FBachofner** [qooob/authentic-theme#1048]
I have just requested a feature enhancement to Webmin to allow **_any_** theme the ability to set this default: https://github.com/webmin/webmin/issues/857

Given that changing this default is already available for "old" themes, perhaps there is a limitation which now forces such a decision on themes themselves.

If so, I hope that Authentic Theme (itself) could be enhanced to allow setting a default "show # entries" in File Manager

**Comment by FBachofner** [comment]
If this request "has" to be done in Authentic Theme (and not in Webmin itself for some reason),

perhaps you could add a file manager configuration section at "/webmin/edit_themes.cgi" -- the section could be descriptively named "File Manager" and other default configuration options could be added there.

Some other useful features to eventually add could be selecting which default columns are to be displayed, the default sort column, the default sort order.


Continued thanks for this awesome Webmin theme!

**Comment by qooob** [comment]
I'll check a little bit later today.

**Comment by qooob** [comment]
Done.

**Comment by FBachofner** [comment]
Works great in Authentic Theme 19.10-beta2

Thank you so much!
