### ISSUE TITLE
Error - Perl execution failed

### ISSUE THREAD

**Issue by jmottle** [qooob/authentic-theme#1049]
There seems to be an issue when using this theme.  We upgraded webmin the other day and immediately lost access to the app with the following error:

Error - Perl execution failed
Nested quantifiers in regex; marked by <-- HERE in m/(\S*link\.cgi/[\d]{8,16}+ <-- HERE )/ at /usr/libexec/webmin/authentic-theme/authentic-init.pm line 1103. Compilation failed in require at /usr/libexec/webmin/authentic-theme/authentic-lib.pm line 18. Compilation failed in require at /usr/libexec/webmin/authentic-theme/index.cgi line 10.

Our ISP reinstalled webmin again, a 1.7 series.  We upgraded to 1.8 series so the theme would become available.  The upgrade to 1.8 went fine, but as soon as we selected the Authentic theme and the page refreshed we get the error above.  Any ideas how to fix this?

**Comment by qooob** [comment]
What is your distro type and Perl version?

**Comment by qooob** [comment]
I suppose it's the version prior to 5.10, for example 5.8? You can check it by running `perl -v`

**Comment by jmottle** [comment]
Rackspace installed it from their RPM.  The Per version is: v5.8.8 built for x86_64-linux-thread-multi

**Comment by qooob** [comment]
Okay, I see now. Could you try editing `authentic-init.pm` on line 1103 and removing `+` sign after `{8,16}`?

**Comment by gnadelwartz** [comment]
per 5.8 on a new system, really?

**Comment by jmottle** [comment]
It's not a new system.  It's a legacy box supporting an older app.

**Comment by gnadelwartz** [comment]
nevertheless, webmin needs at least perl 5.10 as prerequisite, so I would recommend to update perl if possible.

in addition, a legacy box without current uodates is IMHO a big risc if connected to the internet

**Comment by jmottle** [comment]
OK, so the removal of the + has allowed us to get back in, however now we can only see the Java file manager which does not work. This was the primary reason we switched to the authentic theme.  Need the other File manager back.

**Comment by gnadelwartz** [comment]
try re check modules on re login after

**Comment by jmottle** [comment]
I tried Refresh Modules, but that did not help.  BTW, our server is backported, but that's not the topic of this thread.  :)

**Comment by qooob** [comment]
What do you have in miniserv.error? In case things run, it's probably Perl on other modules in Webmin, as I also know, we only support Perl 5.10+ .

**Comment by jmottle** [comment]
I have another server also with Java 5.8.8 and it works fine there.

**Comment by jmottle** [comment]
Sorry meant to say Perl 5.8.8

**Comment by jmottle** [comment]
I checked miniserv.error after running the refresh modules and it just shows a series of "Subroutine......"  no errors.

**Comment by qooob** [comment]
What Java has to do with all of it?

**Comment by jmottle** [comment]
Nothing. as I mentioned above, I meant Perl.

**Comment by qooob** [comment]
What if you downgrade to previous Webmin version and use latest theme with this patch?

**Comment by gnadelwartz** [comment]
does this other server has webmin 1.880 (new current) or older?

**Comment by jmottle** [comment]
We're running 1.870 on the other server.  Is there an easy way to downgrade this version?  Rackspace installed and the only option was to upgrade to the most recent version.

**Comment by gnadelwartz** [comment]
yes, it's possible, and go to webmin dir an run update-from-repo..sh -release:1.870

**Comment by jmottle** [comment]
don't see that command in that folder. I get a "command not found"

**Comment by qooob** [comment]
Kay, does Webmin 1.880 requires Perl 5.10+?

**Comment by gnadelwartz** [comment]
you have to put ./ before if you want to run a command from current dir, sorry to not mentoin it.

`./update-from-repo.sh -release:1.870`

**Comment by jmottle** [comment]
I still get "No such file or directory"  Not sure if it matters that webmin was installed originally from Rackspace's RPM.

**Comment by gnadelwartz** [comment]
ilia, 5.10+ is prerequisite since 1.800 IIRC, lets see if downgrade helps ...

**Comment by gnadelwartz** [comment]
where is wbmin installed, usually /usr/libexec/webmin?

**Comment by jmottle** [comment]
Ooops, was still in the miniserver webmin folder.  The command ran, but I'm getting this error:

./update-from-repo.sh: line 128: ${CYAN}Search for ${RPOD^} configuration ... ${NC}: bad substitution
found: /etc/webmin/miniserv.conf
./update-from-repo.sh: line 195: "Would you like to update "${PROD^}" from ${HOST}/${REPO}${BRANCH} [y/N] ": bad substitution
./update-from-repo.sh: line 216: ${CYAN}Pulling in latest release of${NC} ${ORANGE}${PROD^}${NC} $RRELEASE ($HOST/$REPO)...: bad substitution
 Error: update failed: git clone  1.870 https://github.com/webmin/webmin.git

**Comment by qooob** [comment]
Just copy the folder `webmin` from old system and delete this one?

**Comment by jmottle** [comment]
You mean copy it from our other server running 1.870?

**Comment by qooob** [comment]
Yes, from other server. Ususaly it's in `/usr/share/webmin` or `/usr/libexec/webmin`. It could also be at `/usr/local` or other depending on the distor. Try `whereis webmin` command to find this out.

**Comment by gnadelwartz** [comment]
ups, seems to be very old system. so you have to downlod from here:
https://sourceforge.net/projects/webadmin/files/webmin/1.870/

select the tar.gz version, transfer ut to your server and extract inna temporary dir.
change to extracted webmin and run ./setup.sh

**Comment by jmottle** [comment]
Ok, the version has now been rolled back to version 1.870, however I still only see Java File Manager

**Comment by qooob** [comment]
Did you restart Webmin?

**Comment by jmottle** [comment]
I should mention that even with the reinstall of the older version, the theme was already set to Authentic, so it obviously is reading a config file somewhere outside the webmin folder?

**Comment by qooob** [comment]
I have made a patch to support odler version of Perl.
https://github.com/qooob/authentic-theme/commit/41172189e9238aa133218c6f31776f6020e62012

What is the issue you're having there now, not sure?

I will close this as it's no long theme issue. You can still post your questions here, I'll do my best to help.

**Comment by jmottle** [comment]
Thanks for your help.  No idea what to do now.  This upgrade and theme have somehow got rid of the only feature we actually use. File Manager...ugg.

**Comment by qooob** [comment]
File Manager Java or File Manager HTML5?

Did you try to restore the backup of `/etc/webmin` and your lib folder of `webmin`?

**Comment by gnadelwartz** [comment]
is filemanager listet under unused modules?

**Comment by jmottle** [comment]
No it's not listed under unused modules.

**Comment by qooob** [comment]
It's probably broken ACL. Check it by clicking on the username next to log out and there find Available Modules tab.

**Comment by jmottle** [comment]
You rock!  That was it! Thank you. So to confirm, we can not move past Webmin 1.870 as versions past this will break, or do you suspect the missing HTML5 file manager was always an ACL issue but would need an edited authentic-init.pm on line 1103 and removing + sign after {8,16}?  Just trying to determine if we need to stay put from this point forward.

**Comment by qooob** [comment]
I have already fixed that issue. So if you install 1.880, you will only need to edit it once. Later it will just work. :wink:

**Comment by qooob** [comment]
Oh, yeah, Kay. This is even better.

**Comment by qooob** [comment]
Only ipdate to Webmin using script (I hope it's not broken at 1.87x).

**Comment by jmottle** [comment]
Thanks again! Really appreciate your assistance.

**Comment by gnadelwartz** [comment]
@jcameron I had similar issues with available modules in the past, because you have to enable "new" available modules for every user. it would be convenient if main user, eg. root or first defined user has access to all modules without enabling them first in available modules.

**Comment by qooob** [comment]
@jmottle Please let us know if Webmin 1.880 will work.
