### ISSUE TITLE
changing theme opens a new tab in the web browser

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1050]
When changing theme it will open a new tab in the web browser. I haven't seen that before but only when i change theme from authentic theme to another one, not the other way around.

Authentic theme 19.10-beta2

**Comment by gnadelwartz** [comment]
this seem to be the standard behavior since 19.00.
may be authentic should close the old window after opening the new one, because authentic is still active in the old one and this is somewhat unexpected.

**Comment by qooob** [comment]
It's fixed. Thanks for reporting.

It's impossible to close the tab. It's only possible to close the _window_ that was opened by the _script_.
