### ISSUE TITLE
Development versions being offered when not set

### ISSUE THREAD

**Issue by BrettRow** [qooob/authentic-theme#1051]
I have the "Including development versions" option in Software Updates set to no but I am still being offered an update to beta versions.

In addition, the update display states "Authentic Theme 19.09.2. Latest available release 19.10" and does not indicate that 19.10 is still a beta update. The only way to check that is to read the changelog.

**Comment by qooob** [comment]
It sounds like a duplicate of https://github.com/qooob/authentic-theme/issues/1028 and it's been fixed.

What is your current version?

**Comment by BrettRow** [comment]
I am on 1.880

**Comment by qooob** [comment]
In case you didn't run updates, what happens if you manually patch the file according to the commit https://github.com/qooob/authentic-theme/commit/397e864951d2253c36410811ecf3b4195eb6630e

**Comment by BrettRow** [comment]
That patch does fix the problem, thank you.
