### ISSUE TITLE
Behaviour while using authentic-theme for cloudmin

### ISSUE THREAD

**Issue by ja-finn** [qooob/authentic-theme#1053]
I've been having this issue for a long time with authentic-theme but couldn't find anything while googling so I assumed it was just my installation. I've now re-installed everything and its still showing the same behaviour and also tried it after a friend set up cloudmin with the same results.

When using "Open Webmin" to directly log into webmin on a VM, the file explorer shows the hosts files instead of the VMs. It also gives an error then jumps back to the host after clicking an apply button i.e. after changing theme or for the SSH server. The error is related to the host, i.e. database not found when doing something with an SQL database on the VM. The action is still applied to the VM though. The same is for issuing remote commands where the SSH prompt is for the host and not the VM, this used to work properly before the new terminal like window was implemented (not sure which version that was).

I've tried installing the theme via packages in webmin and directly from git with the same result. Gray theme behaves as expected when performing actions on the VMs and issuing remote commands.

OS: Host Debian 8, VMs Debian 8/9, Ubuntu 16.04/17.10 and FreeBSD
Webmin: 1.88 on all machines
Authentic-theme: 19.09.2

**Comment by qooob** [comment]
Hi,

What browser are you using?

Strange but for me Open Webmin surely worked on Webmin 1.880. Are you sure you have updated Webmin cross all of your server?

**Comment by ja-finn** [comment]
Apologize for the late reply, I've trying to figure out what changed.. Apparently it works as it should now, all of it. I've had this issue for the better part of a year with two different installations on my own equipment and recently at a friends. 

As I can't recreate the issue I apologize for wasting your time.

**Comment by qooob** [comment]
Thanks for reporting anyway.
