### ISSUE TITLE
Comodo WAF module

### ISSUE THREAD

**Issue by asuweb** [qooob/authentic-theme#1054]
The Comodo WAF module doesn't load with the authentic theme.  It works perfectly with the Grey Framed Theme.

The issue is JS / jQuery related.

It was first referenced in #259, however since that's a very old thread, I'm starting a new one.

Accessing Comodo WAF results in a blank page, with the following console errors:

![image](https://user-images.githubusercontent.com/13250955/37398542-cacdf134-2776-11e8-903e-48a7a6d44886.png)

If we disable line 3, of `/usr/libexec/webmin/cwaf/cwaf/tpl/index.html` 
`# document.write('<link type="text/css" href="cwaf/css/blitzer/jquery-ui-1.9.2.custom.min.css" rel="stylesheet" \/>');`

the theme then loads the module, but it is unusable due to JS errors (this "fix" is mentioned on a few threads, but isn't a solution).

![image](https://user-images.githubusercontent.com/13250955/37398589-eef1ab1e-2776-11e8-9076-893f96f8fb1a.png)
![image](https://user-images.githubusercontent.com/13250955/37398627-046a6ab2-2777-11e8-994e-40432015ff2d.png)

**Comment by gnadelwartz** [comment]
seems javascript of the module interferes with authentic-theme.
So the workaround is to use grey-framed theme.

IMHO it's Comodo who is reponsible to fix this Problem, but again IMHO
Ilja may see this different.

**Comment by qooob** [comment]
I'm sorry, but I will not be able to support dated modules. Please contact module's developers and ask them to improve the module. It's been months already as Webmin/Usermin switched to Authentic Theme.
