### ISSUE TITLE
Strange issue with Webmin's built in Webmin Update

### ISSUE THREAD

**Issue by myopenflixr** [qooob/authentic-theme#1055]
Hi Qooob,

I'm not sure if this is normal behavior or not or has anything to do with authentic-theme, but I find this odd and figured I'd let you know.

A few week's ago, I was alerted in Webmin that Webmin was eligible to upgrade to 1.880 which I did through Webmin. The upgrade worked just fine and I also recently upgraded authentic-theme to 19.10-beta2.

Well, I just logged into my VM via SSH and ran sudo apt-get update and sudo apt-get upgrade and I was informed that Webmin was eligible to upgrade. I went ahead and chose "y" to upgrade Webmin and it upgraded Webmin 1.880 over Webmin 1.880. And after logging back into Webmin I was prompted to upgrade my authentic-theme again to 19.10-beta2.

I would have assumed that my server knew it had the latest edition of Webmin and would not have prompted me for the update to Webmin.

I'm running Ubuntu Server 16.04.4 and have the Webmin Repository added to /etc/apt/sources.list.

Is this normal behavior?

Thanks,
Mike

**Comment by gnadelwartz** [comment]
yes, because webmin comes with an little older version apt, so you have to update authentic-theme again.

personally i use only thewbmin integeated update function and ignore updates for webmin from distribution, but IMHO 😁

**Comment by gnadelwartz** [comment]
@JimTR  did not understand, version 1.880 is not offered from your distribution?

no problem, just goto webmin configuration - upgrade and select upgrade from webmin.com

**Comment by qooob** [comment]
Yes, Kay is right. Package from repo has a little older version of the theme, so once you update from repo, you most like get older version, than actual.

There were the bug fixed, that displayed development version for stable channel but it's fixed and will be working correctly since 19.10.

Thank you for reporting.

There is no issue here.

**Comment by JimTR** [comment]
where is upgrade ?
![upgrade](https://user-images.githubusercontent.com/4038510/37486011-1ab5f0d4-2885-11e8-83a6-516b5db0e561.png)

**Comment by qooob** [comment]
You don't see an update, because Virtualmin repo delays updates a little bit.

Let me take a closer look to how to update. 

Please one moment.

**Comment by gnadelwartz** [comment]
may be its disabled by your distro:

![image](https://user-images.githubusercontent.com/4593242/37486321-729b98fe-288e-11e8-8f32-6acc9d3724cf.png)

**Comment by qooob** [comment]
Kay, I've just checked and I don't see this icon on Ubuntu installation, while Fedora displays it just fine.

I'll take a look at the code to figure things out.

Please wait a bit more ..

**Comment by JimTR** [comment]
the following was missing from souces.lst deb http://download.webmin.com/download/repository sarge contrib added this and the upgrade happend .. as I install from the script perhaps it should add the sources ? I now have 1.8 :)

**Comment by qooob** [comment]
Alright, good to know. :smiley:  This is surprisingly strange that _Upgrade Webmin_ icon wasn't there.

Probably, it's Virtualmin `upgrade.cgi` script that disables it on purpose, when installing using `install.sh` script.

**Comment by qooob** [comment]
The source, when installing from script is set from `webmin.com` to `virtualmin.com` on purpose, I suppose.

There is possibility that you might stop getting updates from Virtualmin repo. To fix it, just run from the console, with your `install.sh` script the following:

```Bash
./install.sh --setup
```

.. to _Setup software repositories and exit  (no installation or configuration)_.

**Comment by JimTR** [comment]
I looked again with the source enabled and there is still no icon in the webmin config page to update .. so as you think perhaps this is disabled for Ubuntu

**Comment by JimTR** [comment]
However I still have the virtualmin source set could this cause the issue ?

**Comment by 7starsone** [comment]
same here on CentOS 7, no upgrade button...

**Comment by qooob** [comment]
My best guess, is that it's done on purpose.

**Comment by swelljoe** [comment]
It is on purpose.

Virtualmin disables that button during installation for all distros. We roll updates to Webmin on a different cycle for Virtualmin to do more testing, and specific testing with Virtualmin, before release.

1.880 hasn't been rolled out yet because of a specific bug. Will be rolled soon.

**Comment by swelljoe** [comment]
Authentic generally shouldn't be making suggestions about Webmin versions. I know this particular version needs some patches in the latest Webmin, so it's not such a big deal here, but we need to get onto a cycle where the stable version of the theme isn't demanding new/unreleased Webmin versions. ;-)

**Comment by JimTR** [comment]
So Therefore I should remove the references to webmin from my sources.lst ?

**Comment by qooob** [comment]
Joe, correct. 19.10 will not notify about it, while user doesn't enable development version notification.

**Comment by gnadelwartz** [comment]
@JimTR yes, if virualmin is in your sources.lst

**Comment by myopenflixr** [comment]
I didn't realize my "simple" question would lead to such a big discussion. @gnadelwartz, so what you're saying is that my distro (Ubuntu 16.04.4 Server) "thinks" the upgrade version of Webmin is different solely because the repo version is slightly different because of the different version of authentic-theme. I just want to clarify that I'm understanding you correctly.....and assuming so, that makes total sense!!

Thanks everyone!

Again, keep up the work @qooob, I couldn't manage a damn thing as efficiently without Webmin and this amazingly designed theme :)

**Comment by gnadelwartz** [comment]
@myopenflixr it's simply the distro didn't noticed the internal upgrade of webmin, so it offers always to upgrade even already done internally by webmin.

so the distro upgrade in real-life is a downgrade
