### ISSUE TITLE
Webmin Servers Index

### ISSUE THREAD

**Issue by myopenflixr** [qooob/authentic-theme#1056]
Hi @qooob or @gnadelwartz ,

I have yet another issue/question.

First of all, I have Ubuntu Server 16.04.4 running multiple VM's (Virtualbox). Each VM has Webmin installed and I have everything accessible via Nginx reverse proxy which is installed one one of the VM's. And, everything works perfectly I must say!

Except....

My one issue/question is the Webmin Servers Index feature. With everything running behind my reverse proxy, I can ONLY access my servers' webmin via my registered domain name and not via https://ip-address:10000.

With that being said, is there any way to configure webmin to be able to use the Webmin Servers Index to allow me to jump from server to server while assigning the url's to be FQDN's? It seems that it will only function on local with a port versus having the ability to access each webmin server on the network via my registered domain name.

The way I have my reverse proxy (and all webmins) configured, I access each one at https:/www.servername.com/webmin/server1, https:/www.servername.com/webmin/server2, https:/www.servername.com/webmin/server3, etc.

Is it possible to configure the other network webmin servers to have direct links to my registered domain without needing to use a URL with a port number?

I hope that made sense :)

Thanks,
Mike

**Comment by gnadelwartz** [comment]
wow, this is really a not simple question!
but to make it short, if you have proxy setup with path its currently not possible to access webmin directly via IP:port

this is more a feature reuest for @jcameron  than authentic-theme.

**Comment by qooob** [comment]
Mike, 

At first glance, I would say that you need to make sure that your DNS is aware of those machines. In case it's the virtual-machine and you want to access them from other, non-local machines, you will have to setup the bride. There are a lot of posts on the net about how to do it. It's specific and not very trivial to do. This question is better to ask, I think, Jamie or Joe.

I will close it for keeping things in order, as I don't see an issue here. However, you are welcome to ask further questions and I will be happy to help with whatever I can.

**Comment by jcameron** [comment]
Right now the Webmin Servers Index module doesn't support access via a subdirectory URL path - and even if it did, features like remote RPC calls wouldn't work because they use ports 10001 and up.
