### ISSUE TITLE
File Manager: download broken in Firefox with no error in console

### ISSUE THREAD

**Issue by reidbiztech** [qooob/authentic-theme#1057]
See: https://www.virtualmin.com/node/56365

I can't find the issue, I suspect changes in the javascript are to blame, but it seems only the minified versions of the javascript is present here.

Is the original source for the file manager javascript for recent versions available somewhere so I can examine the files to try and find the issue?

**Comment by qooob** [comment]
It's been already fixed.

**Comment by reidbiztech** [comment]
Cool! Thanks for the update!
