### ISSUE TITLE
Not working dowloads in filemanager

### ISSUE THREAD

**Issue by Lolcsi** [qooob/authentic-theme#1058]
Hi qooob!
Open file manager and right click a file click download but nothing happen.
Im using 19.09.2. authentic -theme
Ubuntu Linux 14.04.3

**Comment by Lolcsi** [comment]
I update usermin and theme the last version my problem is solved.

**Comment by gnadelwartz** [comment]
@Lolcsi so please close the issue...

**Comment by qooob** [comment]
Yes, this bug been fixed already.
