### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by kosugikun** [qooob/authentic-theme#1059]
I would like to create a Japanese translation of this theme.

**Comment by qooob** [comment]
I have  [created _ja_JP_ file](https://github.com/qooob/authentic-theme/blob/ad065e9f17d1766c6549d7058e76c9aad3bad723/lang/ja_JP.UTF-8) for you to just use for the translation. It's all in English. You can edit it on your computer and then make a commit.

Please don't sort the lines, keep the order.

Arigatou Gozaimasu :bowing_man:
