### ISSUE TITLE
Can't load the "OpenVPN + CA" model 

### ISSUE THREAD

**Issue by tekintian** [qooob/authentic-theme#106]
cant't load the "OpenVPN + CA" model , Always show loading logo, can't show the content..........

And change to another theme, the model is ok,,,,,,,,,,,

----------------------------------------here is the loading area html---------------------------------------------------
<div class="loader-container" style="display: block;">
<div class="loader" id="loader-insertion-point" style="margin: -30px 0px 0px;"><div class="spinner" role="progressbar" style="position: absolute; width: 0px; z-index: 2000000000; left: 50%; top: 50%;"><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-0-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(90deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-1-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(99deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-2-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(108deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-3-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(117deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-4-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(126deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-5-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(135deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-6-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(144deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-7-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(153deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-8-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(162deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-9-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(171deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-10-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(180deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-11-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(189deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-12-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(198deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-13-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(207deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-14-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(216deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-15-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(225deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-16-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(234deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-17-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(243deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-18-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(252deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-19-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(261deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-20-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(270deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-21-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(279deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-22-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(288deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-23-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(297deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-24-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(306deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-25-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(315deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-26-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(324deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-27-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(333deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-28-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(342deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-29-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(351deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-30-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(360deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-31-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(369deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-32-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(378deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-33-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(387deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-34-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(396deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-35-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(405deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-36-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(414deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-37-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(423deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-38-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(432deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div><div style="position: absolute; top: 0px; opacity: 0.25; -webkit-animation: opacity-20-25-39-40 0.5s linear infinite;"><div style="position: absolute; width: 5px; height: 1px; background-color: rgb(78, 124, 200); -webkit-box-shadow: rgba(0, 0, 0, 0.0980392) 0px 0px 1px; -webkit-transform-origin: 0% 50%; -webkit-transform: rotate(441deg) translate(30px, 0px); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; background-position: initial initial; background-repeat: initial initial;"></div></div></div></div>
</div>

**Comment by qooob** [comment]
Double Shift or double mouse click will dismiss a loader. It's same problem as AWStat, search through closed issues.

**Comment by tekintian** [comment]
Maybe you can consider "Bootstrap 3 Webmin Theme" , this theme not the issue.........

**Comment by qooob** [comment]
Those modules are not following general rules of Webmin model. It's not the problem of neither Webmin nor Authentic Theme but those outdated modules.

Besides, it's not very hard to double click on the loader to dismiss it.

**Comment by qooob** [comment]
I will try adding some workaroind for old modules. Thanks for advising! 

Bootstrap 3 Theme doesn't support even a half of what _Authentic Theme_ does nor look same good...

**Comment by qooob** [comment]
Alright, I see the cause of this problem. Will fix it upon next release! Sorry about that!

**Comment by qooob** [comment]
This issue is going to be completely fixed in version 10.0.0, in few days. Thanks for reporting!
