### ISSUE TITLE
Usermin update stuck on "Checking for third-party modules .."

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#1060]
Hello,
i tried to update Usermin by `update-from-repo.sh`
and is stuck on `Checking for third-party modules ..`

now Webmin/Virtualmin page returns ERR_CONNECTION_REFUSED

what happens here? I'm on CentOS 7
thanks

**Comment by 7starsone** [comment]
found that Webmin service is stopped... is it by design? Is it trying to first update Usermin and then restart the services? Anyway, why this behavior?

**Comment by 7starsone** [comment]
now "**Warning!  In order to have System Information displayed you will need to enable System Status module in user settings.**"

**Comment by 7starsone** [comment]
what's up to Webmin, please, and how to fix now?

**Comment by qooob** [comment]
> why this _Checking for third-party modules_ never ending

Because _webmin.com_ site and the part of it, that let's you download modules is down. Jamie should've been notified about it.

It's the update script, not the theme issue. However, I'm glad to help. I'm just not sure what is the issue?

**Comment by 7starsone** [comment]
the issue now is that I can't do anything on Webmin
this is the screen
![Image webmin dashboards](http://i65.tinypic.com/dmcwgk.jpg)

**Comment by 7starsone** [comment]
and so on ""Checking for third-party modules .." wasn't set a check for the connection? And if this is the result...is wrong for sure. For an external connection, a check in the code must be set. Anyway, I can't understand what this has to do with this...it shouldn't happen

**Comment by qooob** [comment]
Well, it looks like ACLs are down. Backup `/etc/webmin/webmin.acl`, then edit it and find `root:` make sure that you add `*` after `root:` so it looks like:

```
root: *
```

Restart Webmin bu running `/etc/webmin/restart`

Please share backed up file, the string only for user _root_, did it have anything there?

**Comment by 7starsone** [comment]
this is for root on webmin.acl

`root: acl adsl-client ajaxterm apache at backup-config bacula-backup bandwidth bind8 burner cfengine change-user cluster-copy cluster-cron cluster-passwd cluster-shell cluster-software cluster-useradmin cluster-usermin cluster-webmin cpan cron custom dfsadmin dhcpd dnsadmin dovecot exim exports fail2ban fdisk fetchmail file filter firewall frox fsdump grub heartbeat htaccess-htpasswd idmapd inetd init inittab ipfilter ipfw ipsec iscsi-client iscsi-server iscsi-target iscsi-tgtd jabber krb5 ldap-client ldap-server ldap-useradmin lilo logrotate lpadmin lvm mailboxes mailcap majordomo man mon mount mysql net nis openslp package-updates pam pap passwd phpini postfix postgresql ppp-client pptp-client pptp-server proc procmail proftpd pserver qmailadmin quota raid samba sarg sendmail sentry servers shell shorewall shorewall6 smart-status smf software spam squid sshd status stunnel syslog-ng syslog system-status tcpwrappers telnet time tunnel updown useradmin usermin vgetty webalizer webmin webmincron webminlog wuftpd xinetd virtual-server virtualmin-mailman virtualmin-sqlite virtualmin-svn virtualmin-awstats virtualmin-dav security-updates virtualmin-init virtualmin-registrar ruby-gems php-pear virtualmin-htpasswd virtualmin-git authentic-theme firewalld filemin firewall6 changepass chfn commands cshrc forward gnupg htaccess language mailbox plan schedule ssh theme usermount`

**Comment by 7starsone** [comment]
it's like webmin became Usermin ... on the Title bar now I see Webmin 1.740 but Webmin is 1.881, updated yesterday on CentOS

**Comment by qooob** [comment]
Strange, it should work.

Again, how did you update, using `update-from-repo.sh` script or `yum` command? In this case the script did something wrong.

On RHEL systems you can safely run
```
yum reinstall usermin
```

**Comment by 7starsone** [comment]
I wanted to use your latest beta with Usermin, but it was reported outdated (1.731). just used `update-from-repo.sh`

**Comment by gnadelwartz** [comment]
this should be from Jamie's setup.sh script, I do not display zhis message.

when Jamie's script starts it stop webmin and copy files and third-party modules to webmin directory.
If it breaks wemin is not running and innsn inconsitent state.

**Comment by gnadelwartz** [comment]
ok, usemin, didn't see ehile compising my anser

**Comment by gnadelwartz** [comment]
can you provide conplete output please?

from what usrmin version you was updating?

**Comment by 7starsone** [comment]
reinstalled usermin (it installed 1.734), restarted Webmin but it does the same thing

**Comment by qooob** [comment]
Third-party modules are down right now. Probably that's what made things broken. It's worth checking if connections to the links first before running update, like grabbing some small file or something.

**Comment by qooob** [comment]
You need to restart Usermin, obviously.

**Comment by qooob** [comment]
Unless the script destroyed `/etc/usermin`, there should be no more issues. Otherwise, you would have to restore `/etc/usermin` manually and restart Usermin.

**Comment by 7starsone** [comment]
no way, restarted usermin and the same

![Image webmin dashboards](http://i65.tinypic.com/dmcwgk.jpg)

**Comment by qooob** [comment]
It doesn't look like Usermin?

**Comment by qooob** [comment]
Why are you logging in to Usermin as _root_ anyway?

**Comment by 7starsone** [comment]
Webmin doesn't work, I need the usual Webmin/Virtualmin with root access. This is root and it's not working, as you can see

**Comment by gnadelwartz** [comment]
ok, now im confused.

the picture you posted is after webmin or usermin login?

**Comment by 7starsone** [comment]
Webmin behaves like Usermin on port 10000 now.

Indeed, while before on Title bar I had `Webmin 1.740` now, instead, I have as Title `Webmin 1.734` just because I reinstalled usermin 1.734

**Comment by gnadelwartz** [comment]
so it looks like things are mixed up now

**Comment by qooob** [comment]
Do reinstall the same way for Webmin using `yum`.

**Comment by 7starsone** [comment]
and are the settings saved as before?

**Comment by gnadelwartz** [comment]
do you have a backup of usermin and webmin then restore /etc an /usr/libexec.

if not :
make. a backup of /etc/webmin and /etc/usermin, delete webmin and usermin, and install from scratch.
IMHO this us the best way

**Comment by qooob** [comment]
Running `yum` will be more than enough. If something goes wrong, restore `/etc/webmin` and `/etc/usermin` from backups and restart Webmin and/or Usermin.

**Comment by 7starsone** [comment]
so, I had to do `yum reinstall webmin` for a usermin update 🤣 I won't do it anymore... unless they solve this connection issue/code

thanks 👍

**Comment by qooob** [comment]
You're welcome.

**Comment by gnadelwartz** [comment]
@7starsone  its fixed. if you want to try:

- go to your usermin installation dir
- dwonload newest script:
   `wget https://raw.githubusercontent.com/gnadelwartz/webmin/master/update-from-repo.sh`
- run  `update-from-repo.sh`
  or if you want latest german translations also   run  `update-from-repo.sh -repo:gnadelwartz/usermin`

**Comment by 7starsone** [comment]
@gnadelwartz I trust you...but now I prefer to wait for the official update 😆 😄 😸 🤣
