### ISSUE TITLE
why don't i get any Webmin updates in Authentic theme?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1061]
When i was running the old Webmin theme i got a message that there was a new Webmin. I haven't seen that message for a long time but when i run the `apt update` i can see there is an update. It won't either show up on the Dashboard in the `X package updates are available`.

**Comment by qooob** [comment]
Try clicking on the spinner at the bottom left of the right side slider.

You probably disabled scheduled functions for Webmin Scheduled Jobs in Webmin Configuration?

**Comment by Sopor-** [comment]
What i know of i haven't disabled any Webmin updates. The module update is off but it has been like this forever. I have clicked on the spinner but nothing happens more than it spins :)
Why isn't it showing up in the `Software Package Updates`?

**Comment by qooob** [comment]
What do you have on _Webmin Configuration/Webmin Scheduled Functions_ on System Status (scheduled_collect_system_info) option?

Also what do you have  on _Webmin Configuration/Background Status Collection_ on _Collect system status in background?_ option?

**Comment by Sopor-** [comment]
All 4 have these setting except one of them also have the System Time.
![image](https://user-images.githubusercontent.com/5789283/37559842-447b8ce0-2a2d-11e8-8388-58913a9fcfff.png)

![image](https://user-images.githubusercontent.com/5789283/37559860-77e80342-2a2d-11e8-8ea7-f6f9598c1798.png)

**Comment by qooob** [comment]
Which updates are you expecting?

**Comment by qooob** [comment]
Did you try to go to Software Packages Updates and click refresh?

**Comment by gnadelwartz** [comment]
![screenshot_20180317-230945](https://user-images.githubusercontent.com/4593242/37560446-66e4d6d2-2a38-11e8-80b6-882f5fe6d782.png)

**Comment by Sopor-** [comment]
@gnadelwartz Yes, i have the exact same settings as your picture.

@qooob If i do `Refresh available updates` i get Webmin in the list.

I have 4 Webmin running and only one is updated. I will wait and see how long time it will take before i get a message about the Webmin update. Maybe i'm too eager and need to wait more?

**Comment by qooob** [comment]
It should be 5 minutes by default. Something went wrong and it is not the theme issue.

**Comment by Sopor-** [comment]
The updated Webmin is now running 1.881.

**Comment by Sopor-** [comment]
I can now see the Webmin in the `Software Packages Updates` but still no message about a new Webmin, but i continue to wait :)

**Comment by Sopor-** [comment]
Now i can see the message about the update, but i don't know when it was announced because i haven't been home for a week.
![image](https://user-images.githubusercontent.com/5789283/37877962-6be0ebfa-3062-11e8-9996-1aee397d095f.png)

**Comment by qooob** [comment]
This message is generated by WebminCore but not by your system package manager (like `yum` or `apt`).

You really should be able to see it on the package manager. What `apt update` says?

**Comment by Sopor-** [comment]
I also need to do a full refresh of the Dashboard page to get rid of the `Warning!` after an update.

**Comment by qooob** [comment]
@Sopor- It takes 5 minutes by default to automatically get rid of the message.

**Comment by Sopor-** [comment]
@qooob In that case something is wrong. I have waited for hours and it is still showing this message
![image](https://user-images.githubusercontent.com/5789283/37880513-e5731a98-3089-11e8-9aa6-c1ff7ec7109b.png)

**Comment by qooob** [comment]
Whatever it is, it's not the theme as data coming from WebminCore. I supposed want that could be above. Please double check, otherwise file new bug to Webmin repo.

**Comment by Sopor-** [comment]
Now the message is gone. Are you sure it is 5 minutes and not 5 days @qooob ;)

**Comment by qooob** [comment]
1.881 is the latest, what do you expect?

**Comment by Sopor-** [comment]
That it took 5 days for the message to auto disappear after i did an upgrade from a terminal. If it check this every 5 minutes it should take 5 days for it to disappear. You wrote it by yourself that it should take 5 minutes "https://github.com/qooob/authentic-theme/issues/1061#issuecomment-376005106"

**Comment by Sopor-** [comment]
Only for your information @qooob, this message won't go away either after 5 minutes. I deleted the file `reboot-required` and even if i deleted that file it will continue to show the message after 1 hour. It is no big deal, i can easy do an update of the page but when you are saying it should automatically go away after 5 minutes and it won't it sounds that something isn't right.
![image](https://user-images.githubusercontent.com/5789283/38148407-b75091f6-3456-11e8-95f6-bac95eaec20b.png)

**Comment by qooob** [comment]
This message, the one about Webmin update, that you were referring to above (not the _reboot notice_) should go away in 300 seconds by default, unless some settings were changed on your side intentionally, _or_ in case you reside at some other space-time continuum, where time flow is different to mine, and it simply takes 5 minutes for me, while 5 days for you; it's theoretically also possible and in this case I don't have the exact solution for you. :wink: 

Look, it shouldn't be an issue at all. I don't remember those messages being stuck like that. Besides, the theme just receives messages from _WebminCore_ and prints them. This kind of issue should've been reported to [Webmin repo](https://github.com/webmin/webmin/). Theme doesn't generate any notifications of such kind.

**Comment by Sopor-** [comment]
Today the message about `Recent package updates...` disappeared. Hmm, i will see if i report it or not to Webmin.
