### ISSUE TITLE
Authentic Theme 9.5.0 on webmin 1.73 (not working)

### ISSUE THREAD

**Issue by myrctech** [qooob/authentic-theme#107]
I just tried to install the authentic theme on webmin 1.73. 
nothing come up, only seeing a loading page after log in with usename/password. 

can anyone help? or advise how can I at least resume back the original themes.

great appreciated for help!!

**Comment by myrctech** [comment]
more info about my system
is Ubuntu + webmin 1.73, running at HTTPS

Great thanks!

**Comment by qooob** [comment]
Double click on the loader to see what's behind?Most likely you don't have required modules installed.

**Comment by myrctech** [comment]
OO so great, such a prompt response... 
sorry that I could understand what loader you referring to? I am quite new to webmin...
thanks!

**Comment by qooob** [comment]
Loader - the one that is rotating in the middle of the screen. Install `version`, read FAQ on main page!

**Comment by myrctech** [comment]
Yes sir, I was reading the FAQ after failures to login. 
However, at the moment, I cannot log into the system at all, what else could I do to solve or go back to original theme so that I can install the pre-requsite?

**Comment by qooob** [comment]
To prematurely dismiss the loader (spinner),  did you double click on it with your mouse? Also clicking Shift key two times would do the same. To get back, in URL add `/webmin`

**Comment by myrctech** [comment]
OO what a idot i am... great thanks, I am trying to install the CPAN as requested now.
great thanks for your support really!

appreciated for your work and time

**Comment by qooob** [comment]
Thats, ok! ;) You are welcome!
