### ISSUE TITLE
File Manager: Tree-view error on loading

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#1074]
#1066 I have tested the new tree view but it never loads and on the console the following errors are displayed on load:

![image](https://user-images.githubusercontent.com/32517724/37737255-7eab3626-2d53-11e8-8746-de5bf6b4c102.png)

Only the spinner keeps spinning:

![image](https://user-images.githubusercontent.com/32517724/37737316-a3d8a852-2d53-11e8-986c-3dc9052e798e.png)

Furthermore there are multiply processes that left open. these needed to be force closed otherwise they keep doing something :):
![image](https://user-images.githubusercontent.com/32517724/37738115-4c0a3796-2d56-11e8-9b0d-9159ac127d6a.png)

For your information I am using apache2 proxypass to access webmin
(I emptied browser cache, reloaded the page etc.)

**Comment by Abasz** [comment]
no, that did not help. 

FYI - these processes are quite persistent little buggers... :) they kept comming back after I killd the process even with the browser closed so I ended up with a webmin restart

**Comment by Abasz** [comment]
On addition note. A new error was produced at some point in the console:

![image](https://user-images.githubusercontent.com/32517724/37739533-ab673d70-2d5a-11e8-9d97-7bbf641ea213.png)

May be this helps too

**Comment by qooob** [comment]
Strange. I didn't notice it on my machines. My production by default took 5 seconds to build the tree for `/` (with huge amount of data) and my home PC with VMs less than a second. For particular dir, it's no time at all.

I'm missing something here for sure. I will take a closer look tomorrow. :disappointed: 

Can you post more data about your system? CPU, kind of disk drives and other related system specs.

Proxy causes the issue? Well, I will check it using proxy as well.

**Comment by qooob** [comment]
Okay, after taking a shower and thinking over the issue, I have an understanding of what's wrong. Find method doesn't care about the depth param that I thought was taken into consideration but instead it's traversing down the full file-tree. It should be done other way. I will tweak Perl sub tomorrow.

UI is getting correct depth and output but right now, it still makes the server to go through each folder, without respect to the depth option.

In case you have super fast SSDs you can't really tell a difference but if it's an ordinary drive, then it might take way to much time, and this is exactly what you're expecting, I suppose.

**Comment by Abasz** [comment]
Hi, that makes sense, as I have Snapshot like backup (monthly) directories with hard links that works similarly to mac time machine. This makes directory depth very significant!

**Comment by gnadelwartz** [comment]
for me it seems like `tree.cgi` does not run at all, even I set the x-bit on the file.
I'll try your perl script from SO if it gives any error message to me, e.g. about missing modules ...

**Comment by gnadelwartz** [comment]
webmin error log shows:
Error you have no permission to show / ...

And in webmin log no execution of `file-manager/tree.cgi` is displayed

**Comment by qooob** [comment]
Oh, I forgot about x-bit.

No, It also needs fixing. You need to do something like:

```
my $preprocess = sub {
        my $depth = $File::Find::dir =~ tr[/][];
        return @_ if $depth < $df;;
    };
```

I at the moment inclined to use `File::Find::Rule`.

Kay, how are you logged it? As root?

**Comment by qooob** [comment]
Testing it. It's so fast the right way.

**Comment by gnadelwartz** [comment]
yes as root and no problem (until now) to display/edit files in /

**Comment by qooob** [comment]
What OS?

**Comment by gnadelwartz** [comment]
in grey frame theme I can open /, with authetic it stalls forever.

Synology and OpenSuSE

**Comment by Abasz** [comment]
Operating system: Ubuntu Linux 16.04.3
Webmin version: 1.881 | 
Theme version: Authentic Theme 19.10-beta4
Kernel and CPU: Linux 4.4.0-116-generic on x86_64
Processor information: Intel(R) Pentium(R) CPU J3710 @ 1.60GHz, 4 cores

**Comment by qooob** [comment]
Okay, here is the super fast fix that should work. Replace it in `authentic-theme/extensions/file-manager-li.pl` and try again please.

```Perl

sub get_tree
{
    my ($p, $d) = @_;
    my $df = int($d);
    my %r;
    my @r;

    my $wanted = sub {
        my $td = $File::Find::name;
        my $dc = $td =~ tr[/][];
        if (-d $td) {
            $td =~ s|^\Q$p\E/?||;
            if ($r{$td} || !$td) {
                return
            }
            my ($pd, $cd) = $td =~ m|^ (.+) / ([^/]+) \z|x;
            my $pp = $p ne '/' ? $p : undef;
            my $c = $r{$td} =
              { key => html_escape("$pp/$td"), title => (defined($cd) ? html_escape($cd) : html_escape($td)) };
            defined $pd ? (push @{ $r{$pd}{children} }, $c) : (push @r, $c);
        }
    };
    my $preprocess = sub {
        my $dd = ($df > 0 ? ($df + 1) : 0);
        if ($dd) {
            my $d = $File::Find::dir =~ tr[/][];
            return @_ if $d < $dd;
            return;
        }

        sort @_;
    };
    find(
         {  wanted     => $wanted,
            preprocess => $preprocess
         },
         $p);
    return \@r;
}

```

**Comment by qooob** [comment]
Make sure to set  the depth to 1 or 2 to be super fast on systems with many files.

**Comment by gnadelwartz** [comment]
no difference on my side, tree.cgi does not run at all ...

**Comment by qooob** [comment]
My point was to create tree-view like in no other File Managers, so you could go to the search bar and filter out any directory on your system, based on the depth set in configuration. User would have to jeopardize time on the initial load but get amazing experience.

I have double tested it on my production server and it works perfectly. Depth 2 loads in no time and I will set it as default, instead of 5.

**Comment by qooob** [comment]
Kay, what is the output of on your system:

```
eval "use $File::Find;";
if (!$@) {
    print "My system can use \$File::Find";
}
```

**Comment by gnadelwartz** [comment]
file find is there, I can run you SO example

**Comment by Abasz** [comment]
one rather styling comment :) it would be better to have the filter on the top rather at the bottom to avoid scrillong all the time

**Comment by qooob** [comment]
@Abasz Yes, I checked it on different linux systems and it worked for me as well.

What is the real problem, Kay? What is about JSON?

**Comment by qooob** [comment]
@Abasz Tree is smart and will adjust the height. If you don't want to scroll things, just limit per page switch to 5 or 10. :wink:

**Comment by Abasz** [comment]
indeed it does if I do window resize but if I just type in filter there is a big white space left:

![image](https://user-images.githubusercontent.com/32517724/37764228-6f9c8680-2dc1-11e8-907a-0f3e5146b143.png)

**Comment by qooob** [comment]
:grinning: Thank you! I hope people will love it over time.

It's difficult to make it fully-responsive. It's already responsive but how do you expect to deal with deep nesting without vertical scrolling?

**Comment by gnadelwartz** [comment]
don't know, for mee it looks like tree.cgi is not started, I'll investigate more on this ...

made a fresh install, file manager works
updated theme to beta4, apply neu sub get_tree .... same behaivior spinning forever.

May be ist a config issue?

**Comment by qooob** [comment]
What is the first param that is received by the sub? Is it `/`?

**Comment by gnadelwartz** [comment]
yes, but even it may take very long on `/`, there is no running process `tree.cgi`

**Comment by gnadelwartz** [comment]
look like I have damaged my installation by experimenting a bit, again a new install :-/.
After I will set root for filemanager to /root.

**Comment by qooob** [comment]
Try to change it to home? Or anything else just to test it. Try to exclude proc, run and most importantly dev from traversing.

**Comment by qooob** [comment]
It's not possible to damage installation by this script. :)

**Comment by qooob** [comment]
Set level to 1 it just have to work.

**Comment by gnadelwartz** [comment]
tried to change, but changing in settings for root seems to ha no efect, is there an extra setting for filemanager?

**Comment by gnadelwartz** [comment]
damage was from  me, not the script :-) and until now the script was IMHO never called an my box.

**Comment by gnadelwartz** [comment]
on my old ubuntu tablet webmin was never installed, after installing 1.881, authenric beta4 and your patch, its working as it should ...

**Comment by qooob** [comment]
What happened to the icon next to refresh button in the menu?

**Comment by gnadelwartz** [comment]
don't know :-), BUT

did a clean install (deleting all condig files and removed webmin) on my OpenSuse box.
updated to authentic beta4, applied patch and ... din't work

The only difference to my old ubuntu hardware should be: proxy-setup!

**Comment by qooob** [comment]
Do you have any errors in the Network tab of the browser's console?

**Comment by gnadelwartz** [comment]
![grafik](https://user-images.githubusercontent.com/4593242/37768350-8f44c3f6-2dcd-11e8-87f9-1d0eefa1a39c.png)

**Comment by qooob** [comment]
Could you try at incognito mode please?

**Comment by gnadelwartz** [comment]
F*** and hurray its no more blocking and tree.cgi is running!

`root     31415 29925  2 12:40 ?        00:00:03 /usr/libexec/webmin/authentic-theme/extensions/file-manager/tree.cgi  `

![grafik](https://user-images.githubusercontent.com/4593242/37768677-c66a2c80-2dce-11e8-94c1-8ed87663f3e2.png)

**Comment by qooob** [comment]
Yes, it's due to the bug in the initial code. I'm making final, second revision, that will have useless dirs excluded from traversion. It will enable to keep default depth number higher.

It will be optional. For now I'm forcefully excluding the following:

```
cdrom, dev, lib, lost+found, lib64, proc, run, sys
```
**_Attention:_** Anyone reading it, please share your knowledge about what other temporary directories might be on other Linux distros that could be excluded on the first run for `/` partition query.

The updated code.

```Perl

sub get_tree
{
    my ($p, $d, $e) = @_;
    my $df = int($d);
    my %r;
    my @r;

    # Keep this option set to one for now
    $e = 1;

    my $wanted = sub {
        my $td = $File::Find::name;
        if (-d $td) {
            $td =~ s|^\Q$p\E/?||;
            if ($r{$td} || !$td) {
                return
            }
            my ($pd, $cd) = $td =~ m|^ (.+) / ([^/]+) \z|x;
            my $pp = $p ne '/' ? $p : undef;
            my $c = $r{$td} =
              { key => html_escape("$pp/$td"), title => (defined($cd) ? html_escape($cd) : html_escape($td)) };
            defined $pd ? (push @{ $r{$pd}{children} }, $c) : (push @r, $c);
        }
    };
    my $preprocess = sub {
        my $td = $File::Find::name;
        my $d  = $td =~ tr[/][];

        if ($e && $p eq "/" && $d > 0 && $td =~ /^\/cdrom|\/dev|\/lib|\/lost\+found|\/lib64|\/proc|\/run|\/sys/) {
            return
        }
        my $dd = ($df > 0 ? ($df + 1) : 0);
        if ($dd) {
            if ($d < $dd) {
                return sort @_;
            }
            return;
        }
        sort @_;
    };
    find(
         {  wanted     => $wanted,
            preprocess => $preprocess
         },
         $p);
    return \@r;
}
```

**Comment by gnadelwartz** [comment]
IMHO `/lib` and `/lib64` should be listed if used as root

others to exclude: '/snap /.snapper' 

may be make it configurable list ...

**Comment by qooob** [comment]
Listed? All of them will be listed but only if you specifically click on it. Do you need the content of `/lib` and `/lib64` be available for search on the first run, because this is what it's all about.

**Comment by gnadelwartz** [comment]
nevertheless, it doesn't hurt if they are in the tree.

The tree-view seems to list files in "physical" order, while I prefer alphabetcial order :-)

**Comment by qooob** [comment]
Kay, they **_will be tree_** but they will not be traversed!

I will also add snap and Trash-1000

**Comment by gnadelwartz** [comment]
`/^trash/i` ?

**Comment by Abasz** [comment]
keep media as people might have external storage attached and mounted there (auto usbmount e.g. uses that folder). 

I agree tmp and mnt.

**Comment by gnadelwartz** [comment]
scanning /media may also leads to spinup a mounted cdrom or other slow devices (ZIP-drive, floppy etc).... so so not travering /media is IMHO a good idea.

nevertheless as Ilia explains /media is display in the tree and also accessible

**Comment by Abasz** [comment]
ok it makes sense now :) I was thinking only about my setup where I might have a usb3 drive or an external HDD

**Comment by qooob** [comment]
Good to know it's fast! :) This is what I was intended to do at the beginning but as my drive reads almost 2gb per second - it didn't let me notice a difference at all.

Excluding trash like that isn't going to work. It starts with `.` and case insensitive match also wouldn't help here. Could be `..|.trash/i` but I haven't seen such trashes. 

Excluding _tmp_ and _mnt_ is a good idea too.

 @Abasz All of them are going to be listed -no folders are going to be left over. It's all about the initial scan.

----

Again, the point of my tree-view is to be able to type at search, after the first load, for example `virtual-serv` and instantly get the results of `/var/webmin/modules/virtual-server` and get there by single click. This is why I made it possible to choose depth, depending on the system specs.

Excluding mentioned folders will only display the folder, like: `/proc` - it will look 'empty' but when you click on it, it will deliver the list of subfolders, again based on the depth in configurations. Meaning that mentioned `/proc` folder could be searched but not after the first load, it will require the click. :)

Makes sense?

**Comment by Abasz** [comment]
It does indeed.

**Comment by gnadelwartz** [comment]
how can I collapse whole tree view without klicking an every open subtree?

**Comment by qooob** [comment]
You can't yet. Making a patch, with many small improvements.

**Comment by gnadelwartz** [comment]
usually the filter field is on the bottom, it stay also there if I serch for someting, but after resizing it jumps up:

![grafik](https://user-images.githubusercontent.com/4593242/37777117-1a78c90e-2de7-11e8-8662-9c269cf7e300.png)


![grafik](https://user-images.githubusercontent.com/4593242/37777186-41d5d3ac-2de7-11e8-9845-3b27e08f6a7c.png)

**Comment by qooob** [comment]
Use per page select above the tree to keep it as you need.

**Comment by gnadelwartz** [comment]
It was very fast with 2 Dirs depth, even faster with newest patch excluding dirs, but when cahged to 5 level it was slooooow again, over one Minute (10s CPU time).

So my proposal is to set it initally to 3 and let user change on the fly:
![grafik](https://user-images.githubusercontent.com/4593242/37778719-ec4b9008-2dea-11e8-9f8a-46f1abaa4b9d.png)

**Comment by qooob** [comment]
Yes, I already changed depth to 2 by default.

**Comment by gnadelwartz** [comment]
additionally it would be nice to exclude `/lib` and `.snapshots` also ...

**Comment by gnadelwartz** [comment]
3 works also in less than 2 seconds for me ..

**Comment by gnadelwartz** [comment]
simplyfied regex, simpler to read and may be faster
``` perl
if ($e && $p eq "/" && $d > 0 && $td =~ /^\/(tmp|cdrom|dev|lib|lost\+found|lib64|proc|run|sys|snap)/) {
       return
}
```

**Comment by qooob** [comment]
Okay, thanks. 

Tell me something, will Perl continue interpret `$p` in case `$e` is false?

**Comment by gnadelwartz** [comment]
IMHO: if `$e` is false the whole term is false and perl stops evaluation the following expressions.
this is why I use `$td==1`, if its <>1 following match is not evaluated.

**Comment by qooob** [comment]
Okay, thank you all. Pull latest changes and tell me how the thing work now in Tree-view. All should be great now.
