### ISSUE TITLE
Save changes stuck when URL is entered without port number

### ISSUE THREAD

**Issue by HerrBubbla** [qooob/authentic-theme#1080]
Hello,
I have changed Webmin's default port to 80 and can access Webmin without having the port number in the end of the web URL. 
The problem is when I save a change in webmin configuration tab. I get the error message: https://example.com/webmin/:80/webmin/ 404 (File not found) and nothing happen but the changes seems to be saved as they should. 
I do not get the same error with Webmin's old theme.
Using Authentic Theme 19.10-beta4 on a Ubuntu 16.04.4 server.

**Comment by gnadelwartz** [comment]
this setup is unusual but should work in general.

if you changed port only to avoid entering port number I would suggest a proxy setup, so you can have regular web pages, webmin and usermin in parallel on port 80.
https://doxfer.webmin.com/Webmin/Running_Webmin_Under_Apache
Webmin Proxied Through Apache

**Comment by gnadelwartz** [comment]
hat HerrBubbla die Empfehlung mal ausbrobiert?

**Comment by qooob** [comment]
I have no clue if he did.

**Comment by HerrBubbla** [comment]
I tried to add webprefix=/ and webprefixnoredir=1 in /etc/wemin/config but it did break the theme.

![image](https://user-images.githubusercontent.com/37714378/37866264-b8d74b50-2f88-11e8-9217-a1fab1758cfb.png)
Errors:
Content Security Policy: The page’s settings blocked the loading of a resource at https://unauthenticated/js/settings.js?1521907681 (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://unauthenticated/js/settings_bluerange.js?1521907681 (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://unauthenticated/js/bundle.min.js?19092 (“script-src”).

However, tried to add relative_redir= 1 instead and then everything worked except in Ports and Addresses and SSL Encryption settings.
Any idea why it does not work on those two settings?

**Comment by qooob** [comment]
> However, tried to add relative_redir= 1 instead and then everything worked except in Ports and Addresses and SSL Encryption settings.

What exactly doesn't work. Screenshot would always help a lot.

**Comment by HerrBubbla** [comment]
When i click on the save button the animation keeps spinning endlessly. Error in browser shows that it tries connecting to: https://example.com/webmin/:80/webmin/
![image](https://user-images.githubusercontent.com/37714378/37866936-9da2e886-2f91-11e8-918c-68cd2801a99f.png)
Seems like it adds :80/webmin/ in the url for some reason.

**Comment by qooob** [comment]
And what your actual URL looks like. Can you also make a screenshot?

**Comment by HerrBubbla** [comment]
My actual URL is https://dns.bluerange.se/webmin/change_ssl.cgi?xnavigation=1 after i press save in SSL Ecryption settings.

About one second after I press Save, I get the error message below
![image](https://user-images.githubusercontent.com/37714378/37867198-0da5a31e-2f95-11e8-8901-7b69efbac24e.png)

If i then go back to Webmin configuration the URL is https://dns.bluerange.se/webmin/:80/webmin/?xnavigation=1
Normaly it is: https://dns.bluerange.se/webmin/?xnavigation=1

**Comment by qooob** [comment]
Try adding to your:

Add the lines webprefix=`/webmin` to `/etc/webmin/config`.
Add the line `cookiepath=/webmin` to `/etc/webmin/miniserv.conf`.

Restart Webmin. What do you get now?

**Comment by qooob** [comment]
What is `referer` in `/etc/webmin/config` set to?

**Comment by HerrBubbla** [comment]
webprefix=/webmin to /etc/webmin/config. Breaks the theme. Same as when i tried adding webprefix=/

cookiepath=/webmin to /etc/webmin/miniserv.conf. Cant login after adding that. No error message.

referer in /etc/webmin/config. Have tried referer=1 and referer=0 with referers=dns.bluerange.se
If i have referer=0 with no referers i get the Security Warning below.
![image](https://user-images.githubusercontent.com/37714378/37867797-81515364-2f9d-11e8-97f1-5de9d6ca977e.png)

**Comment by qooob** [comment]
No.

You should set `referer` to your host name, i.g. `referer=dns.bluerange.se`.

You could also try `referers_none=0` for testing purposes but it's not recommended to leave it this way on production machine.

**Comment by HerrBubbla** [comment]
Sorrry, no improvement when pressing save on Ports and Addresses settings and SSL Encryption settings.
But as i said before, everything else works when i added relative_redir= 1 in /etc/wemin/config so its not a big deal for me now :)

**Comment by qooob** [comment]
I didn't close it cause I wanted to try this set-up. 

You said it worked in Gray Theme - is this still valid?

**Comment by HerrBubbla** [comment]
I set up a new clean installation and then I did not have to add relative_redir= 1 and i did not get any Trusted Referrers warning but all else is the same.

I was wrong about that all worked on Gray Theme. SSL Encryption savings receives the error message: Content Security Policy: The page’s settings blocked the loading of a resource at https://dns.bluerange.se:80/webmin/ (“frame-src”).

When I save settings under Ports and Addresses with Gray Theme, it goes through as it should, but I'm being redirected to https://dns.bluerange.se:80/

**Comment by qooob** [comment]
I see. This is indeed non standard setup.

I'm not sure if it's worth trying to support it.

Thank you for reporting.

**Comment by HerrBubbla** [comment]
OK, can i make a redirect from for example https://dns.bluerange.se to https://dns.bluerange.se:1024 without installing Apache?

**Comment by qooob** [comment]
I think it's possible. Read more about _Port Forwarding_. I think it's possible.

Why just not set it in Webmin configuration?

**Comment by HerrBubbla** [comment]
Thanks, never thought about port forwarding. I will probably use it.
But one thing is a bit strange when I have Redirect non-SSL requests to SSL mode on. It adds the port number if i try browsing to http://dns.bluerange.se. Webmin do not add the port number when i go directly to https:/dns.bluerange.se

**Comment by barrychapman** [comment]
I get this same error, I have a subdomain set up as: 

    webmin.mysite.io

This does a proxy rewrite with nginx to my.ip.255.0:10000 internally. When loading the site initially, it works. However, saves will append the port to the url:

    https://webmin.mysite.io/nginx/:10000/nginx

Any ideas?

**Comment by rostovtsev** [comment]
Do you have set `webprefixnoredir=1` in your config?
