### ISSUE TITLE
reset to default values does not ask for confirmation

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#1081]
today I reset my authentic setting by accident, l wanted to tap on update theme and hit reset config instead.
even l had not much settings changed, loosing HTML snippets and logo's leads to recreate and some search in my archive.

lt would be nice if authentic ask `are you shure?` before reset all values.

**Comment by qooob** [comment]
Done. Please give it a try.

**Comment by gnadelwartz** [comment]
really? OK 😁

**Comment by qooob** [comment]
Did it work for you?

**Comment by gnadelwartz** [comment]
I had problem updatting because rawgit block updating update-from-repo.sh see PR

**Comment by qooob** [comment]
I have never seen `raw.githubusercontent.com` being blocked.

**Comment by gnadelwartz** [comment]
when I do it from my VM at home where I'm authenticated to github it works, but on my server by a prvider I get:

```
 wget https://rawgit.com/webmin/webmin/master/update-from-repo.sh
--2018-03-24 17:07:35--  https://rawgit.com/webmin/webmin/master/update-from-repo.sh
Aufl▒sen des Hostnamen ▒rawgit.com (rawgit.com)▒... 104.18.62.176, 104.18.63.176, 2400:cb00:2048:1::6812:3fb0, ...
Verbindungsaufbau zu rawgit.com (rawgit.com)|104.18.62.176|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 301 Moved Permanently
Platz: https://raw.githubusercontent.com/webmin/webmin/master/update-from-repo.sh[folge]
--2018-03-24 17:07:35--  https://raw.githubusercontent.com/webmin/webmin/master/update-from-repo.sh
Aufl▒sen des Hostnamen ▒raw.githubusercontent.com (raw.githubusercontent.com)▒... 151.101.112.133
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... fehlgeschlagen: Die Wartezeit f▒r die Verbindung ist abgelaufen.
Erneuter Versuch.

--2018-03-24 17:09:44--  (Versuch: 2)  https://raw.githubusercontent.com/webmin/webmin/master/update-from-repo.sh
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... fehlgeschlagen: Die Wartezeit f▒r die Verbindung ist abgelaufen.

```

**Comment by gnadelwartz** [comment]
do you have access to a server not at home? pls try there ..

**Comment by qooob** [comment]
It's not what my link is in my commited script. :wink: 

This is the correct link.

```
https://raw.githubusercontent.com/webmin/webmin/master/update-from-repo.sh
```

**Comment by gnadelwartz** [comment]
from rawgit:

U```
se this URL for development

https://rawgit.com/user/repo/branch/file

New changes you push to GitHub will be reflected within minutes.

Excessive traffic will be throttled and blacklisted.
```

**Comment by qooob** [comment]
Just login to your GitHub account, click contact and wrote them a message. They will unblock you.

**Comment by gnadelwartz** [comment]
yes, thats possible, but what if others are using webmin also blocked? everyone aks for unblocking?

**Comment by gnadelwartz** [comment]
did aks for unblocking now ...

**Comment by qooob** [comment]
What if your server is unreachable or blocked by some counties?

This should not be an issue for anybody really. I have never had such issues even though I'm using it quite a lot. Users are not going to be debugging your script and run it 20 times in a row, and thus be blocked.

**Comment by gnadelwartz** [comment]
let's see what they respond.

your patch works by marking button redand adds a ? to text?

**Comment by gnadelwartz** [comment]
nevertheless ifyou are blocked by rawgit it curl waits very long and update from UI fails. did you implement a timeout for updating from UI? on command line it continues iafter 30s and finish the update

**Comment by qooob** [comment]
Yes, correct. It will require you to click the button twice.

Timeout? Isn't responds status code, when blocked going to be 403?

**Comment by gnadelwartz** [comment]
no, it blocks until curl gives up? this takes around 30s

**Comment by qooob** [comment]
Kay, 30 seconds is fine. It's something that most likely will never ever happen to ordinary user.

**Comment by gnadelwartz** [comment]
this is what I get in UI after 20s:
![screenshot_20180324-205812](https://user-images.githubusercontent.com/4593242/37868414-386920ec-2fa6-11e8-8004-2bb69e7c7bb0.png)

**Comment by qooob** [comment]
What would you want me to do? Improved error hadling?

**Comment by gnadelwartz** [comment]
may be we can limit curl connection time:

```
--connect-timeout <seconds>
Maximum time in seconds that you allow the connection to the server to take. This only limits the connection phase, once curl has connected this option is of no more use. See also the -m/--max-time option.
```

**Comment by qooob** [comment]
Yes, sure, why not.

**Comment by gnadelwartz** [comment]
here is the answer from github, in short using our url is not supported by github, instead we should use the official api:

Hi Kay,

Thanks for getting in touch! That endpoint isn't currently documented so we don't recommend relying on it. Instead, we recommend using the GitHub API to fetch the raw contents of a file:

https://developer.github.com/v3/repos/contents/#get-contents
https://developer.github.com/v3/media/#raw-2
Here's an example curl request:

curl -v -H "Accept:application/vnd.github.v3.raw" https://api.github.com/repos/webmin/webmin/contents/update-from-repo.sh

I hope that helps, but let me know if you have any other questions!

All the best,
Francis

**Comment by gnadelwartz** [comment]
already tested on my server while old version is blocked...
