### ISSUE TITLE
indicator never stop spinning after pressing the save button

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1085]
When i was turning off treeview in the file manager the indicator on the Save button never stop spinning. I tried to recreate it but i was not able to do it.
![image](https://user-images.githubusercontent.com/5789283/37967248-185bc21a-31cb-11e8-9287-288f6c65c40b.png)

Authentic Theme 19.10-beta4
Webmin 1.881

It seems that it won't take me back to the file manager as it normally should do. I will try do recreate it on my other three Webmin to see if it happens there too.

**Comment by qooob** [comment]
I can't reproduce it.

Probably it's stuck cache from previous installation.

**Comment by Sopor-** [comment]
I didn't manage to recreate it here either.
