### ISSUE TITLE
Tree-view toggle gets stuck

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1086]
When i press the Tree-view toggle button it get stuck and it will show the help message until i press on the page.
![image](https://user-images.githubusercontent.com/5789283/37968125-9b9777c6-31cd-11e8-85b8-fc91b12e2fef.png)

When i press somewhere at the page it look at this
![image](https://user-images.githubusercontent.com/5789283/37968213-cf59c640-31cd-11e8-958f-572304d09ec1.png)

I don't know if it should be as a button but the help text should not be there all the time and as you can see the highlight of the button will also go away even if tree-view mode is on.

**Comment by qooob** [comment]
Not a big deal. 

It will only happen if you click the button and while the button stays active. It's not really a bug. It's Bootstrap Tooltip plugin works this way.

Thank you for reporting.

**Comment by Sopor-** [comment]
So the button shouldn't looked pressed (active) when tree-view is enabled?

**Comment by rostovtsev** [comment]
Actually, I found the way to fix it globally.

It will be working as expected in upcoming `19.20-beta1`.

Thanks for pointing out.
