### ISSUE TITLE
File Manager: Ability to reset column sorting

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1088]
Is there a way to place all the folders first and than the files instead of mixing folders and files as it is now?

**Comment by qooob** [comment]
That's what is done when you first open the table and not use sorting. While sorting used it's sorting them without consideration to folder/file.

**Comment by Sopor-** [comment]
So i need to select the empty sort order to get the old sort order back?

**Comment by qooob** [comment]
Ref.: #19 https://github.com/qooob/authentic-theme/issues/629

**Comment by rostovtsev** [comment]
Added on 19.38.
