### ISSUE TITLE
File manager - why show the folder when it is the only one?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1089]
In the picture you can see that the Home folder only have one folder and when i open it, it will show that chevron that the parent folder seems to have more than this folder but when i press on it i get the same folder name as i'm already in.

![image](https://user-images.githubusercontent.com/5789283/37971600-a535d558-31d6-11e8-821c-9c29943382d7.png)

How hard is it to detect this and never show that chevron sign (or show something else) when the parent folder doesn't have any other folders?

I can then as user easy see if it contains any more folders or not. Maybe you have any bright idea?

**Comment by qooob** [comment]
Without creating extra load, you can't do it, as far as I remember. by the way, this shows _not_ the folder's content but the parent's folder content. 

There is noting to fix here.

Thanks for reporting.
