### ISSUE TITLE
Can't locate object method "parse" via package "version"

### ISSUE THREAD

**Issue by kisiellpl** [qooob/authentic-theme#109]
Seems that installing 'version' module to Perl 5.8.8 through Webmin CPAN form on CentOS 5.11 doesn't solve the problem...

Is there any workaround?
![screenshot 2015-02-16 21 45 25](https://cloud.githubusercontent.com/assets/11034176/6219049/487ce5de-b625-11e4-8d30-1f61450f2dd2.png)
![screenshot 2015-02-16 21 46 15](https://cloud.githubusercontent.com/assets/11034176/6219085/a09b1ed4-b625-11e4-84d6-7780e10d2b4b.png)

**Comment by qooob** [comment]
>Version objects were added to Perl in 5.10. This module implements version objects for older version of Perl and provides the version object API for all versions of Perl. All previous releases before 0.74 are deprecated and should not be used due to incompatible API changes. Version 0.77 introduces the new 'parse' and 'declare' methods to standardize usage. You are strongly urged to set 0.77 as a minimum in your code, e.g.

It's hard to tell. Try installing all `version::` that are there. Also probably installing `Perl::Version` could help. (only probably and less likely)

Other possibility that version is not on your Perl path. You could manually find version module [here](http://search.cpan.org/~jpeacock/version/lib/version.pod) and place it in your path.

Wierd thing that from your screenshot I could tell that the version of your `version` is 1.0203 - seems wrong as of the latest on CPAN 0.9912.
