### ISSUE TITLE
File manager not working in 19.10

### ISSUE THREAD

**Issue by antisect** [qooob/authentic-theme#1090]
File manager just stays at the loading spinner, i've tried resetting the cache and settings.

**Comment by qooob** [comment]
Try going to the theme settings and clear cache.

**Comment by qooob** [comment]
Did you try 19.10-betax?

**Comment by antisect** [comment]
i've already tried clearing the cache.
no i didn't test the beta, just on stable

**Comment by qooob** [comment]
Provide the screenshot please. What is your browser and server OS?

**Comment by qooob** [comment]
You need to clear the storage, using theme settings.

**Comment by antisect** [comment]
its on the latest chrome
the server OS is Ubuntu 16.04.2, ive tested on another server with exactly the same os and its working fine.

i've cleared bothe settings and cache in the theme settings

![webmin](https://user-images.githubusercontent.com/6940971/38026586-88f2ce74-3284-11e8-9f46-5db8425476b2.jpg)

**Comment by qooob** [comment]
What console (F12) says?

**Comment by qooob** [comment]
This shouldn't be happing. Clear localStorage cache by going to theme settings or running in the console: `localStorage.clear()` and _Shift+Ctrl+R_ to force reload the browser.

**Comment by antisect** [comment]
done all that, still no luck

**Console errors are:**

Uncaught TypeError: Cannot read property 'parent' of undefined
    at we.fn.init.preDrawCallback (<anonymous>:7:18570)
    at bundle.min.js?191099999999991:46
    at Function.map (bundle.min.js?191099999999991:2)
    at Nt (bundle.min.js?191099999999991:46)
    at H (bundle.min.js?191099999999991:45)
    at W (bundle.min.js?191099999999991:45)
    at rt (bundle.min.js?191099999999991:45)
    at p (bundle.min.js?191099999999991:46)
    at n (bundle.min.js?191099999999991:46)
    at Rt (bundle.min.js?191099999999991:46)

Uncaught TypeError: Cannot read property 'DataTable' of undefined
    at <anonymous>:12:2080
    at dispatch (bundle.min.js?191099999999991:3)
    at v.handle (bundle.min.js?191099999999991:3)

**Comment by qooob** [comment]
I can't reproduce it.

Try same browser, incognito tab please.

What's your Webmin version?

**Comment by antisect** [comment]
webmin version 1.881
still the same problem in incognito tab.

like i said its working fine on another server, same Ubuntu same webmin version...

**Comment by qooob** [comment]
Try reinstalling the theme again using theme's configuration. Probably something got wrong on your side, while installing. Try reloading Webmin by running `/etc/webmin/restart`.

As it's only that server for you, I will consider it to be not an issue, as I also can't reproduce it on 5 different servers - it works just fine.

Thank you for reporting.

I will be happy to provide further help if needed.

**Comment by antisect** [comment]
still no luck with a webmin restart.
i've had to revert to the old grey frame them.....which isn't very pretty :(

**Comment by qooob** [comment]
Can you go to `/usr/share/webmin/authentic-theme` and run:

```Bash
./theme-update.sh
```

**Comment by antisect** [comment]
still not fixed im afraid, its very strange as everything else works

**Comment by qooob** [comment]
Everything else? What about File Manager on other servers?

What is the URL for that server that doesn't work. Did you try clicking on the menu to enter it or just reloaded the page?

**Comment by qooob** [comment]
Can you backup and remove 

`/etc/webmin/authentic-theme/settings-yourusername.js`

If it helps, please share the file contents for me here.

After deleting the file, reload the browser's page.

**Comment by antisect** [comment]
also deleted this settings file, no difference.
i also deleted the theme and its folder, then reinstalled but still no luck.
i ended up putting version 19.09.2 back on and the filemanager works instantly.

the settings file contains below: (it wont let me attach it here).

config_portable_theme_locale_format_long='LL';
config_portable_module_filemanager_notification_type=1;
config_portable_theme_locale_languages='en';
settings_theme_options_button=true;
config_portable_module_filemanager_hide_toolbar=false;
settings_button_tooltip=true;
config_portable_module_filemanager_records_per_page='20';
settings_show_night_mode_link=true;
config_portable_module_filemanager_calculate_size=false;
config_portable_module_filemanager_hovered_toolbar=false;
settings_animation_tabs=true;
config_portable_module_filemanager_remember_tabs=true;
config_portable_module_xsql_fit_content_screen_height=false;
settings_background_color='gainsboro';
config_portable_module_filemanager_default_sort=0;
settings_animation_left=true;
config_portable_theme_locale_format_full='LLLL';
config_portable_module_filemanager_hide_actions=false;
config_portable_module_filemanager_tree_exclude_on_first_load=true;
config_portable_module_filemanager_tree_expand_search=true;
settings_leftmenu_button_refresh=false;
config_portable_module_filemanager_hide_tree_view=false;
settings_hotkeys_active=true;
config_portable_theme_locale_language=false;
config_portable_module_filemanager_tree_view_depth='2';
settings_font_family=0;
settings_cm_editor_palette='monokai';
config_portable_theme_locale_format_short='L';
settings_navigation_color='blue';
config_portable_module_filemanager_switch_user=true;
settings_force_night_mode=0;
settings_sysinfo_link_mini=false;
settings_hide_top_loader=false;

**Comment by qooob** [comment]
I'm sorry, could you update to 19.10 and reboot the server??

Just out of curiosity - I'll be super surprised if it works.

**Comment by antisect** [comment]
i updated to 19.10 and..........still no luck
its a mystery :)

**Comment by qooob** [comment]
That's crazy. Okay, back up all mentioned `settings-*` files go to theme settings and reset to default.

Could you try other browser and incognito tab?

**Comment by antisect** [comment]
>theme settings and reset to default >done that
filemanager not working in chrome, but its working in edge :/
Cleared all browsing data cookies etc in chrome but still not working.
Its obviously something at my end....but what, i don't know :D

**Comment by qooob** [comment]
I think I know it. Can you please check one more thing. I think it could be related/cause.


What is the URL for file manager? Check it and share it.

Then. 

Did you try clicking on the menu to enter it or just reloaded the page? Try clicking on the menu after all, it will work I guess, right?

**Comment by antisect** [comment]
yes i always use the menu link (never reload the page), the url is:
SITENAME/filemin/index.cgi?path=/&xnavigation=1

**Comment by qooob** [comment]
What is the file size in bites of `/extensions/file-manager/file-manager.min.js` when opened using your `//server:port/..` 

This is so odd.

**Comment by antisect** [comment]
not sure what you mean about //server:port/..
but just noticed if i middle click file manager in the menu to open it in a new tab, it works.
seems like an ajax thing.

![webmin](https://user-images.githubusercontent.com/6940971/38036245-33f85bf4-329e-11e8-9eb2-135dfbde4529.jpg)

**Comment by antisect** [comment]
just realized what you meant, file-manager.min.js is 189kb

**Comment by qooob** [comment]
I need it exactly in bites.

**Comment by antisect** [comment]
193,899 bytes

**Comment by qooob** [comment]
Okay, what is the size if viewed from console?

**Comment by antisect** [comment]
says 190kb, cant get it to show bytes

**Comment by qooob** [comment]
`ls -lsa`

**Comment by antisect** [comment]
ls -lsa
it says 193899 bytes

**Comment by qooob** [comment]
What is you default module for Webmin?

**Comment by qooob** [comment]
I'm logged in to my firend's machine where I can also see this error. This is very good as I can try to fix it now.

..and still it's very hard to believe. :open_mouth:

**Comment by antisect** [comment]
Great news, thanks for all the help.

**Comment by qooob** [comment]
It's fixed. It only affects the users with enabled _Action Column_.

Thank you and special thanks to @gnadelwartz for proving an access for the machine, where I could reproduce the bug.

Please give it a try.

**Comment by antisect** [comment]
works yay 😄
thanks for the help

**Comment by haseeb2k9** [comment]
@antisect can you please tell me how you Fix this, having the same issue after update from 19.09.2 to latest.

**Comment by rostovtsev** [comment]
This error has been fixed already months ago.

We've just released Webmin 1.900 with Authentic Theme 19.21. 

Please upgrade first.
