### ISSUE TITLE
Theme: Add an option to always display vertical scrollbar

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1092]
When expanding the menu and the web browser need to add the scrollbar the whole page change. It makes it impossible to close the menu again without moving the mouse. This because the menu row moves a bit down (it doesn't look nice either). Is this possible to fix so it won't moves?
![authentic_theme-menu_moves](https://user-images.githubusercontent.com/5789283/38166576-4ec5d4e0-3526-11e8-8b5f-900d8fdd19e9.gif)

I'm running Firefox 59.0.2

**Comment by qooob** [comment]
That is something that would only happen at certain resolutions. The reason why this is happening is the description text that is pushing to the second line as the scroll bar appears.

You can add a patch to you theme extensions CSS part, to always display vertical the scroll bar:

```CSS
#content.__page {
  overflow-y: scroll;
}
```

**Comment by qooob** [comment]
I added an option:

```
Hide persistent vertical scrollbar
```
