### ISSUE TITLE
Side slider get stuck over the Dashboard

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1093]
When enable `Keep always visible` in the `Side slider options` it will happen instantly. I don't even have to press Save. If i then press the Dashboard it will tell me that i haven't saved my settings but i continue without saving. Now this Side slider get stuck over the Dashboard like this and it won't close:

![image](https://user-images.githubusercontent.com/5789283/38166956-2dfd63fc-352d-11e8-9783-8edacb469866.png)

The only way to get rid of the Side slider is to refresh the page.

**Comment by gnadelwartz** [comment]
This is intended as authentic preview changes immediately,  nevertheless it should go away if you don't  save.

**Comment by qooob** [comment]
Fixed. Thanks.

**Comment by gnadelwartz** [comment]
He ilia it's  eastern in western Europe and you are working?  I assume you are Russian orthodox and have easter next week (like my wife)? ;)

**Comment by qooob** [comment]
Yes we do. :wink: 

Happy Easter!

**Comment by Sopor-** [comment]
When is Easter 2018 and how is the date decided?

This year Easter takes place from Good Friday on March 30 until Easter Monday on April 2 - making Easter Sunday fall on April 1, which is also April Fool's day.

The death of Jesus occurred around the Jewish Passover, which is traditionally held on first full moon following the vernal equinox.

As the full moon can vary in each time zone, the Church said that they would use the 14th day of the lunar month instead – the Paschal Full Moon – and host Easter Day on the following Sunday.

Once the date of the moon is known, Easter Day and the Easter holidays can be determined.
