### ISSUE TITLE
show installed Authentic theme version beside 'Check for Authentic Theme updates'

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1097]
It would be great if the latest installed Authentic theme could be showed somewhere on the manually update page. Here is one example:

![image](https://user-images.githubusercontent.com/5789283/38200111-6116363a-3693-11e8-990d-01472b7269a1.png)

**Comment by qooob** [comment]
Sure, and even more, like ability to downgrade to specific version.

**Comment by qooob** [comment]
Okay, done it.

Example of how it's going to look like. It's intelligent and should not pose any annoyance.

![screenshot from 2018-04-08 20-36-21](https://user-images.githubusercontent.com/4426533/38470856-926138ce-3b71-11e8-93d4-d368c44b308d.png)
