### ISSUE TITLE
Virtualmin should display menu links of default server after login

### ISSUE THREAD

**Issue by garas** [qooob/authentic-theme#1099]
I have set `Default tab after logging in to Webmin=Virtualmin` and `Default page for Virtualmin=mymainserver.com`.

After login I see active Virtualmin tab, selected server `mymainserver.com`, right side "Virtual Server Summary" for  `mymainserver.com`, but navigation links (`Edit Virtual Server`, `Configure Website`, `Apache Access Log`, ...) are for `aaa.domain.com` (first in servers menu).

After clicking on Virtualmin tab, correct menu of default server is loaded.

---

Looking at page source for `https://webmin.server.com:10000/`, it has
```html
<select class='ui_select' name="dom" data-autocomplete-title="Virtual Servers" disabled>
<option value="142573659620460">aaa.domain.com</option>
<option value="13676697391804" selected>mymainserver.com</option>
<option value="13676704652377">&nbsp;&nbsp;sub.mymainserver.com</option>
</select>

and links like

<a  href="/virtual-server/edit_domain.cgi?dom=142573659620460"><span>Edit Virtual Server</span></a>
<a href="/apache/virt_index.cgi?virt=aaa.domain.com:80"> <span>Configure Website</span></a>
```

**Comment by qooob** [comment]
Confirmed.

**Comment by qooob** [comment]
It's fixed. Thanks for reporting.
