### ISSUE TITLE
Missing "Force Update Theme" button

### ISSUE THREAD

**Issue by litebito** [qooob/authentic-theme#1103]
Hi,

I've 3 hosts installed with webmin. On one of them, I've the button "Force Update Theme" in theme settings, on the other 2 I've not.

All 3 hosts where installed in the last 30 days, with similar specs: 
- virtual machines
- Centos7
- Webmin standard install via yum

Any idea on how to get the "force update" button on the other installations, or why it is missing?

Is this a theme issue or a webmin issue?

Thanks,

**Comment by qooob** [comment]
Can you provide the screenshot?

**Comment by litebito** [comment]
![2018-04-08 12_52_01-webmin themes webmin 1 881 on centos linux 7 4](https://user-images.githubusercontent.com/3867999/38466596-dc1ffcca-3b2b-11e8-88aa-9be9f53a14e5.png)
![2018-04-08 12_51_40-webmin themes webmin 1 881 on centos linux 7 4](https://user-images.githubusercontent.com/3867999/38466597-dc38c336-3b2b-11e8-84ed-dda814d014c9.png)

**Comment by qooob** [comment]
This happens due to absence of _git_ command on your system.

Actually, this is not user friendly. I made a commit to show button in disabled state with tooltip instead, explaining what issue is (that _git_ command has to be installed).
