### ISSUE TITLE
Authentic theme does extra file copies on every Webmin action

### ISSUE THREAD

**Issue by jcameron** [qooob/authentic-theme#1104]
While looking at the Webmin Actions Log, I noticed that for all actions the following commands are run : 

<code>
cp -p \/etc\/webmin\/authentic\-theme\/settings\.js \/usr\/local\/webadmin\/authentic\-theme\/unauthenticated\/js

cp -p \/etc\/webmin\/authentic\-theme\/settings\.js \/usr\/local\/webadmin\/authentic\-theme\/unauthenticated\/js
</code>

Maybe these can be skipped if the file already exists or has the same size? Shelling out to `cp` is expensive.

**Comment by qooob** [comment]
Hi, Jamie.

Well, I used to have check on the size, but it's not always valid, as value can change from `0` to `1` and file size stays the same, while in fact the file is different.

Running `cp` would be expensive to run it on every call but this only should happen on the initial load - when you reload the page or reopen the browser.

Maybe it's worth to stop logging this command?

**Comment by qooob** [comment]
I have checked it. I can confirm that it only happens on initial load and thus have minimum impact.

I also couldn't find entries in my Webmin Action Log module.

Do you need to enable verbose logging for `copy_source_dest()` to be logged?

**Comment by gnadelwartz** [comment]
hi Jamie,

I can confirm Ilia, the copy command is only executed on login and reload.
Tested with debug log enabled on OpenSuse, Chrome browser, Theme Version 19.10, 19.12 and 19.13-beta1

Nevertheless, it's executed 4 times on reload for me:

```
11474 [09/Apr/2018 11:05:49.929102] kay ::1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/settings\.js \/usr\/libexec\/webmin\/authentic\-theme\/unauthenticated\/js "
11474 [09/Apr/2018 11:05:49.936928] kay ::1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/settings\-kay \/usr\/libexec\/webmin\/authentic\-theme\/unauthenticated\/js\/settings_kay\.js "
11479 [09/Apr/2018 11:05:50.113071] kay ::1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/styles\.css \/usr\/libexec\/webmin\/authentic\-theme\/unauthenticated\/css "
11479 [09/Apr/2018 11:05:50.129539] kay ::1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/settings\.js \/usr\/libexec\/webmin\/authentic\-theme\/unauthenticated\/js "
11479 [09/Apr/2018 11:05:50.134914] kay ::1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/settings\-kay \/usr\/libexec\/webmin\/authentic\-theme\/unauthenticated\/js\/settings_kay\.js "

```

**Comment by qooob** [comment]
Jamie, I enabled `error_stack=1` but I don't see those messages. I noticed that copy function has `main::opened_debug_log` global var call inside but I'm not sure where it's coming from. Any advice for quicker setup?

**Comment by gnadelwartz** [comment]
You have to enable debug log in webmin -webmin configuration - debug log

**Comment by qooob** [comment]
Okay, I'll take a look. Thanks, Kay.

**Comment by qooob** [comment]
I have done more tests, it's not exactly wrong.

The file is **being written only once**. Have a look. All other time it's just read:

_Write:_

```Log
10115 [13/Apr/2018 08:34:27.936997] root 192.168.122.1 - COPY "src=/etc/webmin/authentic-theme/settings.js dst=/usr/share/webmin/authentic-theme/unauthenticated/js"
10115 [13/Apr/2018 08:34:27.937240] root 192.168.122.1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/settings\.js \/usr\/share\/webmin\/authentic\-theme\/unauthenticated\/js "
10115 [13/Apr/2018 08:34:27.951014] root 192.168.122.1 - COPY "src=/etc/webmin/authentic-theme/settings-root dst=/usr/share/webmin/authentic-theme/unauthenticated/js/settings_root.js"
10115 [13/Apr/2018 08:34:27.951443] root 192.168.122.1 - CMD "cmd=cp -p \/etc\/webmin\/authentic\-theme\/settings\-root \/usr\/share\/webmin\/authentic\-theme\/unauthenticated\/js\/settings_root\.js "
```

_Read:_

```
10109 [13/Apr/2018 08:34:27.677256] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10115 [13/Apr/2018 08:34:27.784775] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10115 [13/Apr/2018 08:34:27.892352] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10137 [13/Apr/2018 08:34:30.318534] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10139 [13/Apr/2018 08:34:30.318769] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10136 [13/Apr/2018 08:34:30.331955] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10134 [13/Apr/2018 08:34:30.333017] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
10157 [13/Apr/2018 08:34:30.501682] root 192.168.122.1 - READ "/etc/webmin/authentic-theme/settings.js"
...
```

@jcameron I think it's not an issue? 

By the way, Jamie, I love your implementation of debug logging.

**Comment by jcameron** [comment]
By written once, do you mean per page view? Or only once per login session?

**Comment by qooob** [comment]
> By written once, do you mean per page view? Or only once per login session?

Authentic Theme is now single-page application. It will only run once per full-page reload. When you click navigation links in the theme, or perform any other actions it will not run that _copy_ command. The copy command is run:

1. On page reload (using browser's reload, opening new tab, logging in)
2. On manual settings save

Is there anything wrong with that?

**Comment by jcameron** [comment]
Ok, that makes sense to me.
