### ISSUE TITLE
FirewallD module show only 6 rules

### ISSUE THREAD

**Issue by lomcarlo** [qooob/authentic-theme#1106]
In FirewallD module the list of rules show only the first 6 also if there are more than 6.
![image](https://user-images.githubusercontent.com/5594220/38733050-cee15d4e-3f20-11e8-854e-f5d8ad0b607f.png)
`# firewall-cmd --list-all`
`public (active)`
`  target: default`
`  icmp-block-inversion: no`
`  interfaces: em1 em2`
`  sources:`
`  services: ssh http https`
`  ports: 10000/tcp 45882/tcp`
`  protocols:`
`  masquerade: no`
`  forward-ports: port=8443:proto=tcp:toport=443:toaddr=192.168.1.100`
`        port=821:proto=tcp:toport=21:toaddr=192.168.1.100`
`        port=55536-56559:proto=tcp:toport=55536-56559:toaddr=192.168.1.100`
`        port=822:proto=tcp:toport=22:toaddr=192.168.1.100`
`        port=8080:proto=tcp:toport=8080:toaddr=192.168.1.100`
`  source-ports:`
`  icmp-blocks:`
`  rich rules:`

**Comment by qooob** [comment]
What does it show if you switch to Gray Theme?

**Comment by lomcarlo** [comment]
The same problem, so i think is a Webmin problem, not a theme problem.

**Comment by qooob** [comment]
Yes, please submit it to the [Webmin repo](https://github.com/webmin/webmin/).
