### ISSUE TITLE
No graphs in system statistics

### ISSUE THREAD

**Issue by expertdecisions2** [qooob/authentic-theme#1107]
Graphs shown correctly when selecting _framed theme_ but with _authentic theme, graphs window appears black.
Pls see attached screenshots.

![framed_theme](https://user-images.githubusercontent.com/9258503/38767219-e1f38e3a-3fdd-11e8-9cfd-5c6d22a5c69e.png)
![authentic_theme](https://user-images.githubusercontent.com/9258503/38767222-e747d31e-3fdd-11e8-8212-0ec23e80af76.png)
![dashboard](https://user-images.githubusercontent.com/9258503/38767224-ebc85396-3fdd-11e8-8d7e-88fd6d91b481.png)

**Comment by qooob** [comment]
Hi,

I think this is due to outdated Virtualmin version. Please consider upgrading.

**Comment by expertdecisions2** [comment]
TKS I'll have a look (if I can find how to upgrade Virtualmin Pro :) )

**Comment by qooob** [comment]
I'll be glad to help with the upgrade. Let me know if you have any difficulties.

In case you have valid license, there should be no problem.

Go to console and run:

```
yum clean all && yum update
```

Do you have Virtualmin there upon the packages?

**Comment by expertdecisions2** [comment]
TKS a lot for you rapid answer

II already tried it before but no success.

I get this:

-bash-4.1# yum clean all && yum update
Limpiando repositorios:Webmin base epel extras remi-safe rpmforge updates webtatic
…
…
…
"No se han seleccionando paquetes para ser actualizados
-bash-4.1#! 
(In English: there are no selected packages to be updated.)

 "Packake details “ says I have latest version (5.99) ??

Perhaps I’m not using the correct repository.

...___Albert

**Comment by qooob** [comment]
What is the output of: 

```
yum repolist
```

**Comment by expertdecisions2** [comment]
-bash-4.1# yum repolist
Complementos cargados:fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.uv.es
 * epel: mirror.uv.es
 * extras: mirror.uv.es
 * remi-safe: mirror.netweaver.uk
 * rpmforge: mirror.de.leaseweb.net
 * updates: mirror.uv.es
 * webtatic: uk.repo.webtatic.com
id del repositorio                                nombre del repositorio                                                                     estado
Webmin                                            Webmin Distribution Neutral                                                                   116
base                                              CentOS-6 - Base                                                                             6.706
epel                                              Extra Packages for Enterprise Linux 6 - x86_64                                             12.493
extras                                            CentOS-6 - Extras                                                                              53
remi-safe                                         Safe Remi's RPM repository for Enterprise Linux 6 - x86_64                                  2.329
rpmforge                                          RHEL 6 - RPMforge.net - dag                                                                 4.718
updates                                           CentOS-6 - Updates                                                                          1.185
webtatic                                          Webtatic Repository EL6 - x86_64                                                              243
repolist: 27.843
-bash-4.1#

**Comment by expertdecisions2** [comment]
I thing I found it 

Need to install this repository.

http://software.virtualmin.com/gpl/centos/6/i386/virtualmin-release-latest.noarch.rpm

I’l try right now

**Comment by qooob** [comment]
Okay, I see now. Contact me using my website's contact form. I could help you further, if you proceed here, make sure you're not going to leak your Virtualmin Pro license id and key, that looks like 

```
0000000:XuwXKskXl
```

No, not _i386_ in your case.

**Comment by qooob** [comment]
Simply create the file in your `/etc/yum.repos.d`.

Run nano `/etc/yum.repos.d/virtualmin.repo`

Add as content:
```Text
[virtualmin]
name=RHEL/CentOS $releasever - $basearch - Virtualmin
baseurl=http://0000000:XuwXKskXl@software.virtualmin.com/vm/6/centos/$releasever/$basearch/
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-virtualmin-6
gpgcheck=1

[virtualmin-universal]
name=Virtualmin Distribution Neutral Packages
baseurl=http://0000000:XuwXKskXl@software.virtualmin.com/vm/6/universal/
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-virtualmin-6
[RPM-GPG-KEY-virtualmin-6.zip](https://github.com/qooob/authentic-theme/files/1910276/RPM-GPG-KEY-virtualmin-6.zip)
gpgcheck=1
```

Where `0000000:XuwXKskXl` your license id/key.

**Comment by qooob** [comment]
[RPM-GPG-KEY-virtualmin-6.zip](https://github.com/qooob/authentic-theme/files/1910277/RPM-GPG-KEY-virtualmin-6.zip)

**Comment by qooob** [comment]
You can get your credentials by signing to `virtualmin.com` website, and going to Account/Software Licenses.

**Comment by expertdecisions2** [comment]
Solved!
Now I have Virtualmin Pro version 6.02 and stats working like a charm.
TKS a lot for your helpful messages.
