### ISSUE TITLE
Let the pie charts remember lowest/highest value

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1109]
It would be nice if the live pie charts have some kind of memory function to show maximum (maybe minimum too) value.

![image](https://user-images.githubusercontent.com/5789283/38807966-b88a2e26-417e-11e8-93c5-c49c00d05ef2.png)

An extra smaller bar inside the original bar or only some small lines. A settings to set how long time it should remember them or a simple mouse click inside the pie chart will reset the value? You probably have some great ideas to improve my idea, if you like it of course :)

**Comment by qooob** [comment]
Yeah, maybe. It's all should go under Dashboard Improvements though https://github.com/qooob/authentic-theme/issues/896. It's not my priority. It's going to happen only after Mail re-work. It took way more time to catch up all loose ends, so now I can go and do mail freely .. _**FINALLY**_ (sooorry all about such delay in this regard).
