### ISSUE TITLE
This doesn't look nice

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1110]
It doesn't look nice when you need to wrap the line like this. Do you really need so much information?

![image](https://user-images.githubusercontent.com/5789283/38809148-d9b22cf8-4182-11e8-9115-84b2f719457d.png)

In that case i believe you should move `installed version 19.13-beta1, latest stable 19.12, latest beta 19.13-beta2` to the second line like this:

`In order to make this option work, git command has to be installed on your system`
`Installed version 19.13-beta1, latest stable 19.12, latest beta 19.13-beta2.`

**Comment by qooob** [comment]
Good idea. Fixed. Give it a try.
