### ISSUE TITLE
url parameters are duplicated

### ISSUE THREAD

**Issue by gerbier** [qooob/authentic-theme#1113]
I'm running webmin 1.881 with authentic theme 19.12
I have some code like 
  my $cgi = basename($PROGRAM_NAME);
  ui_form_start( $cgi);
  ui_form_end( [ [ 'log', 'web_log' ] ] );

but when the url is built, the log parameter appears 2 times, for example : https://localhost:10000/sysstats/log.cgi?log=web_log&log=web_log

**Comment by qooob** [comment]
What do you have in URL if you switch to Gray Theme and do the same?

Do you, by any chance, accidentally place two hidden `input` elements in the form with the same name?

Why not use _POST_ method?

**Comment by qooob** [comment]
To make it easier, if you have Jabber, Wire or Slack, send me the credentials using my website's contact form.

**Comment by qooob** [comment]
Is there an actual code that I could test on my machine?

**Comment by gerbier** [comment]
I have change my code to use POST method (in ui_form_start) and it seems to work.
Thanks !

**Comment by qooob** [comment]
Okay, great.
