### ISSUE TITLE
Changes you have made may not be saved

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1115]
I did an update and when i was about to leave the page i got this message:
![image](https://user-images.githubusercontent.com/5789283/39084345-9b0e2a92-4574-11e8-90f0-ff0e4ec5df86.png)

I was running 19.13-beta2 so maybe it is fixed already? It seems to happens on beta6 too.

**Comment by qooob** [comment]
Hi, Sopor. Thank you for reporting.

This message is only seen, when the actual request hasn't been finished. For the packages updates it's possible to see this message in case you wrongly think that it's done and click some link on the page. Webmin might do something else in background for this process to finish, even though you see the message from package manager `Complete! Updated`. 

The indicator that the page is fully finished loading is the blue button saying **Return to package list** and top loader to disappear.

Nothing to worry about here.
