### ISSUE TITLE
Auto Log-Out on Browser Close

### ISSUE THREAD

**Issue by myopenflixr** [qooob/authentic-theme#1118]
Hello,

Something I've noticed (which isn't a bug or anything) is that when I "close" out my browser without logging out of Webmin first, the next time I log into Webmin, my Recent Logins show that I have multiple "Logged In" states.

Is there a way that when a user simply closes their browser session, Webmin could recognize the session ended and show that session as "Logged Out"? Or, would it be possible to set an auto-logout feature after x minutes(or hours).

For example, I just logged in to Webmin and at the bottom of the main screen, "Recent Logins" show that I have 5 "Logged In" sessions....all of which are from my previous logins over the past few days. Technically, 4 of them should say "Logged Out" and my current session should say "This Login". But this isn't the case because I did not click "Sign Out" before closing my browser on the previous logins.

Just an idea. Keep up the great work!

Thanks,
Mike

**Comment by qooob** [comment]
Hi, Mike!

Yes, Webmin can be forced to remember the session on closing browser's window. When you login, in case you don't tick _Remember Me_ checkbox, it _should not_ remember you on closing/opening the browser, resetting the session. I just checked _**BUT**_ it remembers the user regardless of ticked checkbox, so it seems like _WebminCore_ bug and has to be reported to [Webmin repo](https://github.com/webmin/webmin/). In case it's fixed - it should be displayed as logged out.

Auto-logout feature is already there. Go to _Webmin/Webmin Configuration/Authentication_ and you will find there _Auto-logout after X minutes of inactivity_.

You can manually drop needed session by going to _Webmin/Webmin Users/Current Login Sessions_.

Tell me if I could provide you with more help.

**Comment by jcameron** [comment]
Also, there's no way to clear these sessions when the browser window is closed, because (as far as I know) the browser has no way of signaling back to the server that this has happened.

**Comment by qooob** [comment]
Yes, right, I forgot about the fact that it's not possible to do (as far as I also remember).

What is possible though, is to set session lifetime to something very short, pre-defined value, like 300 seconds for example. Anytime there is a call  to the server, _Webmin_ would check if it's greater than pre-defined value. If so, then the session should be terminated and login screen shown, if not, then session lifetime timer should be again reset to pre-defined value. Pre-defined should be short enough for _Remember Me_ to make sense to exist.

**Comment by jcameron** [comment]
Wouldn't that cause sessions to timeout if the browser is just sitting on a single page for a long time, perhaps if the user is filling in a large text box?

**Comment by qooob** [comment]
Well, that's the whole point of session timeout.

Jamie, look, it sounds like great improvement if you enroll this feature. Theme could determine for how long user been idle and for how long _pre-defined value_ was set to in _Webmin Configuration/Authentication_  section. If the time is reaching close to logout, the theme would through a pop up saying something like:

```
We're about to log you out due to inactivity. Click here to prolong your session.
```

If you do it, for Authentic Theme, for those who didn't check _Remember Me_ upon login, the value for timeout option, should be relatively small, like 300 seconds by default. For other themes might be greater. Like 3600 seconds. In this case _Remember Me_ will become really cool and secure feature, unlike right now.

What do you think?

**Comment by qooob** [comment]
> Actually, doesn't the authentic theme already make periodic requests to refesh status information? Does that happen regardless of what page the user is on?

It does and it's page regardless. However, it can be disabled. Ah, ok. I could make the theme ping server every 5 minutes for example, in case user is focused on the Webmin tab or doing some actions. So no popups - less work and less annoying.

**Comment by qooob** [comment]
So, _Auto-logout after X minutes of inactivity_ already exists?

How does it tie to _Remember Me_? Could we set default value for _auto-logout_ key?

**Comment by qooob** [comment]
Now I'm confused. Usermin acts exactly like I was requesting at the first place. Session is destroyed on browser close in case _Remember Me_ is not ticked. Am I being silly about something?

**Comment by jcameron** [comment]
No, that's expected - if remember isn't checked, the session cookie is only stored transiently in the browser.

**Comment by qooob** [comment]
Yes, I'll double check but obviously it wasn't the case for Webmin when I was checking it.

**Comment by myopenflixr** [comment]
Hi @qooob and @jcameron,

I just wanted to chime in. I realize you two are the own the application and/or the theme, but here's my issue from a user perspective.

So, I just now logged in to one of my Virtual Servers....and I'm "alerted" of all these active logins..Most are from different IP's as I access my servers from my home network, my office, and my cell phone. They all show a state of "Logged In". Some are days old and obviously not really "Logged In" as I closed out the browser on these sessions days ago...without clicking "Log Out".

Here's my dilemma:
![webmin session](https://user-images.githubusercontent.com/33140130/39730774-8e061e26-5231-11e8-9ab6-59b0e586c3f6.jpg)

Like @qooob mentioned, it would be nice to somehow have these session automatically log out after x number of minutes as set by the user. Whether this is a pop up message warning or a hard log out...that's up to you two to figure what you like best for your application/theme. And whether this is part of Webmin or Authentic Theme, the end result is what I'm concerned about as a user.

Either way, I would like a way to not show that I'm still logged in from a 4 day old session that is not actually logged in.

Whatever method you might choose, I'd be happy as the end user. I would just prefer not to be alerted of active session when they're not really active.

Thanks guys!

**Comment by myopenflixr** [comment]
The auto-logout option only seems to work if I keep my browser window open. If I log in and do some maintenance and then simply close my browser window when I'm finished, it shows that session as "logged In" next time i log into Webmin...even if it's days later and past the time I set in the Webmin Config module.

**Comment by myopenflixr** [comment]
So, I just pulled up Webmin's documentation and found something that may be causing my issue with the auto-logout function.

Here's an excerpt from Webmin's documentation: **"When using session authentication, Webmin can be configured to automatically log users out if they have been inactive for more than a certain amount of time. To enable this, check the Auto-logout after box and enter a number of minutes into the text field next to it. This feature and the next three are not available when using HTTP authentication."**

I use HTTP authentication because I run Webmin behind Nginx Reverse Proxy. So, I take it that there's no way I can utilize the auto-logout feature or have Webmin close out my old sessions?

Any suggestions anyone?

**Comment by qooob** [comment]
I don't think that using proxy has anything to do with Webmin authentication type.

@jcameron Closing the browser and then reopening it doesn't flush the session in case _Remember Me_ is unchecked. Jamie, can you reproduce it - it looks like a bug?

**Comment by jcameron** [comment]
For HTTP authentication, there is no session tracking at all - the browser sends the username and password for every request!
