### ISSUE TITLE
Theme: Load error on Debian 9 after recent update

### ISSUE THREAD

**Issue by jult** [qooob/authentic-theme#1119]
Running latest from git (19.13), and latest webmin on deb 9.
I no longer get it to run using Authentic theme.
Webmin simply does the blue bar swaying thing on top forever, no end in sight (I've waited 10 minutes..).
I tried restarting webmin, did not change it.

I have this happen on 2 separate machines after debian 9 updated to latest perl a couple of days ago. Seems related, could also be something else.
Changed miniserv.conf to use the gray-theme and voila, it loads immediately. 

I have not tested this with other browsers, perhaps it's something with Moz Firefox. Lots of weird issues since quantum update with that browser. I did load it in a private window, same result. If it's related to a cache, it does not seem session-related, or even browser side.

**Comment by qooob** [comment]
Hi, Julius.

I couldn't reproduce it on my Debian 9 dedicated machine. Neither before running latest update, nor after, nor after rebooting the machine.

![screenshot from 2018-04-25 14-18-05](https://user-images.githubusercontent.com/4426533/39243021-cf9b1b58-4894-11e8-9253-dab32379f13e.png)

I have just tested it in latest stable Firefox and latest nightly Firefox - again, all work just fine.

I don't see an issue here. It seems that you broke something manually.

Please provide more details, screenshot or video-screencast, console errors if any, server-side logs, from Webmin (/var/webmin) for more help.

**Comment by jult** [comment]
OK, fixed it on one of the two servers by deleting the Authentic theme, and then installing it anew. I'll see if I can find what caused it on the other server where it's still not loading.
