### ISSUE TITLE
Package Updates | Wrong number...

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#112]
here is the pic
![Image of packup](http://i60.tinypic.com/3093ts4.jpg)

as you can see it returns 152 but they are just 15 ATM... and also, after "of which" there should be a number...and nothing, instead
**body_upsec=$1 package updates are available, of which $2 are security updates**
![Image of packup2](http://i62.tinypic.com/2zf3ho3.jpg)
the first time it happened, it required many seconds to show the entire panel after the login... never happened before

**Comment by qooob** [comment]
I see why it's happening! I will fix it upon next release. Thanks for reporting!

**Comment by 7starsone** [comment]
;-) you're welcome

**Comment by qooob** [comment]
It will be fixed in version 9.6.0
