### ISSUE TITLE
Auto Refreshing In File Manager Directory

### ISSUE THREAD

**Issue by vemaxaisin** [qooob/authentic-theme#1120]
Hello i wanna ask, why file manager always refreshing directory if i change or moving browser tab ? 
It's bug or feature from new version ? Can't i disable this feature ?
Because for me this is very disturbing

![image](https://user-images.githubusercontent.com/37205558/39241035-d4b1957a-48af-11e8-9f5f-e618b58064b7.png)

Thank's

**Comment by qooob** [comment]
The very latest commit https://github.com/qooob/authentic-theme/commit/193324d4b9939dfad494bcb2f475d442c5b5e4d3 fixes this issue. It will only be triggered for directories with very little content without opened active windows (editor or modal).

Give it a try.

**Comment by qooob** [comment]
It's no longer going to post any issues. It's potentially very useful for some cases.

For example create a new dir, go to it. Open inbuilt command shell. Navigate to previously created dir and create a new file or a dir. Close the terminal and see what happens. :wink:
