### ISSUE TITLE
Search box suggestions keyboard issue

### ISSUE THREAD

**Issue by lunarovic** [qooob/authentic-theme#1124]
When you type something in the search box, press the down arrow (to select a suggestion) and press some key*, it will go to that module as if you pressed Enter.

*Keys: Ctrl, Alt, Shift, Tab, Left arrow, Right arrow, Home, End, Delete, Page up, Page down, Windows key, F keys (F1, F2...), basically any key which doesn't produce a character (except space/backspace and up/down arrows).

(I discovered this by accident because often I'm not sure where I need to go, and I do "Ctrl+A" to select what I just typed and type something else)

**Comment by qooob** [comment]
Fixed. Thanks.

**Comment by lunarovic** [comment]
Hm, it seems this is fixed for Ctrl, Shift and Alt (Alt also deletes text but doesn't matter), but this is still happening with a lot of keys, like left and right arrow, Tab, F keys, Home, End, etc.

Also, while testing now, I found another weird thing - if I type for example the letter "b" and then **quickly** press the down arrow to select something, it will take me to the first thing selected (in this case *Backup Configuration Files*), without ability to choose something else.

**Comment by qooob** [comment]
Well, I'll check tomorrow, okay.

Are you human? 😃

**Comment by lunarovic** [comment]
Haha, I knew something like that would come up sooner or later. 😄 I actually have 8 more issues prepared, but I didn't want to make too many at once, to overwhelm you. 😄

I'm not an alien, but that happened because I was writing down in notepad whatever bug I stumbled upon while using Webmin over a period of the last half a year or something, and I didn't have time to make them into proper GitHub issues (I only wrote bugs in a few words which probably only I could understand).

And amazingly, you already fixed some of them, before I had the chance to report them, bravo! 😃 For example, here are some fixed bugs from my notes (I rewrote them now to be more understandable):

- Clicking rightmost pixel on the screen does not select scrollbar (when there is no sidebar)
- Virtualmin => Select virtual server => Files and Directories => Right click on a file => Edit => Shows empty window, like the file is empty (and from File Manager it's working as it should)
- Virtualmin => Edit Users => Click on user => Email settings => Inbox mail file (click link) => Return to user list OR click Edit Users in left navigation => Dropdown box with virtual servers will display "/" instead of the domain list
- After uploading a file in File manager, the screen stays dimmed and cannot click anything (upload is successful though)
- In File manager when you click more than once on a folder, another spinning circle will appear for every click
- When desktop notifications are clicked, they should do the same as when you click on the notification in the sidebar

👽

**Comment by qooob** [comment]
Not bad at all.

The reason I fixed them because couple of few last release it's exactly what I was doing. I also have a notepad with list of bugs, some of them were over a year old.

I also keep track of every single issue I come across. I just don't always give it a priority.

My main priority is Mail now, so I would like to ask you to report unurgent issues a bit later.

I will take a quick look at already mentioned things to keep things in order.

**Comment by lunarovic** [comment]
All right! I just checked and none of them are urgent issues. Your mail design looks amazing by the way, I can't wait to see it in action. ✉️

I just donated you about 3000 руб worth of Bitcoin, to break the ice on that BTC address. 💸 Keep up the great work. 😄

**Comment by qooob** [comment]
Thanks a lot, appreciate this.

For all to watch and smile. 🙂
https://youtu.be/gz7IPTf1uts

**Comment by qooob** [comment]
Alright, fixed. Happy now? :sweat_smile: 

The other issue, where you super quickly click down on the first key entry, can be left alone as is, I think! Believe me, there is no one on Earth but us are going to notice it. It's below minor lever. 

Thanks overall. I like _search autocomplete_ much more now. I wanted to do it for ages but always put this off. (I actually could not find the straight forward solution to manage private events until now).
