### ISSUE TITLE
Typed text in the search box gets deleted

### ISSUE THREAD

**Issue by lunarovic** [qooob/authentic-theme#1126]
... if I type it fast, before the page has finished loading. I think it should be possible for the text to stay and suggestions can start appearing when they are ready. Or the other solution could be to disable the search box until the page is loaded.

**Comment by qooob** [comment]
This is how it's designed to work. It's not real world situation to invest time in it to fix. Autocomplete also analyses data on the right (content) side and uses it in search.

**Comment by qooob** [comment]
Okay, I've added a patch preventing user focusing on search while page is loading.
