### ISSUE TITLE
Theme: Inbuilt command shell freezes on broken response

### ISSUE THREAD

**Issue by lunarovic** [qooob/authentic-theme#1127]
When trying to use vi in the terminal, the following error appears:
```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```
And a bunch of strange characters and other things.

Also, UI bugs out - you can't select text, type on the keyboard or click the X button to close the terminal, but fortunately the Esc key works.

**Comment by qooob** [comment]
For your information - this is not the real terminal but Command Shell.

[Read more.](https://github.com/qooob/authentic-theme/issues/1037)

**Comment by qooob** [comment]
There is a red button with cross on the top-right of the window to close it with click. Same as in Favorites.

**Comment by lunarovic** [comment]
> For your information - this is not the real terminal but Command Shell.

I read that whole thread you linked and I don't know what you wanted to show me. Are you saying that _vi_ is not supposed to work in the "command shell"? Forgive me, I'm not familiar with the difference in those terms (terminal vs. command shell), I just googled it and it's still very confusing to me.

> There is a red button with cross on the top-right of the window to close it with click. Same as in Favorites.

What do you mean? Yes, that's the X button I mentioned which doesn't work after typing the _vi_ command. Clicking it doesn't close the terminal and you are stuck. The only way to exit is by pressing the Esc key on the keyboard. Please just try it, open Terminal and type:
`vi anyfile`
(replace "anyfile" with any file you find there)

**Comment by qooob** [comment]
Yes, it's the bug in inbuilt terminal. Anytime the call is not ended properly the whole thing breaks.

Needs fixing.. Thank you.

**Comment by lunarovic** [comment]
Thank **you** for taking care of bugs. 🙂 But after I read #1037, maybe you don't need to waste time fixing this if another terminal implementation will be added soon.

**Comment by qooob** [comment]
> will be added soon

It's still better to be fixed.

**Comment by qooob** [comment]
Fixed.
