### ISSUE TITLE
"Back" sometimes doesn't go immediately back, but to some other recently visited module

### ISSUE THREAD

**Issue by lunarovic** [qooob/authentic-theme#1128]
Sometimes when I click "back" in the browser (or on my mouse 🙂), it goes to some previously seen module, but not back in that menu. Most commonly when I jump to another module via search or something. I think this started happening after you enhanced the "back" functionality to not load the previous page every time, to make it quicker. I can't reproduce it now again, so maybe you've already fixed it. 🙂

**Comment by qooob** [comment]
Yes, it's possible but rare case. It's difficult to encompass all of the cases. However, I have it already on my todo. No reason for keeping this issue opened.
