### ISSUE TITLE
Bandwidth Graphs non-functional on System Information page

### ISSUE THREAD

**Issue by pierstaylor** [qooob/authentic-theme#113]
Hi,

The Bandwidth Graphs are non-functional on the Virtualmin System Information page.
Theme Version 9.5.0
Tested on Firefox and Chrome - same results.

The usage shows as 0% and the orange bar is all the way to the left.
Please see screenshot.

With best regards,

Piers

![bandwidtgraphproblem](https://cloud.githubusercontent.com/assets/11160269/6329027/c2b551ee-bb64-11e4-9de4-a3d4e3778e44.png)

**Comment by qooob** [comment]
Please take a look here and tell me it fixes your issue:  https://github.com/qooob/authentic-theme/issues/110

**Comment by pierstaylor** [comment]
Hi,

Yes, that fixes it. Sorry, I did not find that post when I searched. I was Googling for Bandwidth Graphs, rather than Quotas.

Many thanks for the super-fast response!

With best regards,
Piers

**Comment by qooob** [comment]
You are welcome! It will be added in the new version 10.0!
