### ISSUE TITLE
Module settings and controls missing on Apache

### ISSUE THREAD

**Issue by neubreed** [qooob/authentic-theme#1133]
Hi,

I've just noticed that the apache module config and server controls are missing at the top of the page .. Seems to be the case on a few other pages as well. 

![image](https://user-images.githubusercontent.com/309231/39495052-02074f7a-4ddc-11e8-81e0-ef52845ccac4.png)

**Comment by qooob** [comment]
Yes, I already fixed it. Noticed it this evening.

Update the theme and force reload the cache.

**Comment by qooob** [comment]
Thanks a lot for reporting.
