### ISSUE TITLE
Clicking on hlink generates javascript error

### ISSUE THREAD

**Issue by bsmith94** [qooob/authentic-theme#1134]
If I specify an hlink in my module code, clicking on the link doesn't do anything. In the browser's JavaScript console, it displays: 

```
TypeError: $help_body is undefined[Learn More]
bundle.min.js:206:17613
```

The relevant module code is:

```
hlink("Help", "sysinfo");
```

Help works fine when specified via ui_print_header(). However, my module needs multiple help links.

I am using Webmin 1.881 on CentOS 6.9. Browser is Firefox 59.0.2 on MacOS X 10.13.4.

**Comment by qooob** [comment]
Hi,

I am travelling right now. I will do my best to fix it as soon as possible. I think I know the source of the issue though.

**Comment by qooob** [comment]
It's fixed and checked. 

Thanks for reporting.

**Comment by bsmith94** [comment]
Thanks for the quick response.

**Comment by qooob** [comment]
You're welcome.
