### ISSUE TITLE
File manager - calculate selected size

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1136]
If i want to know the size of a folder i can open the context menu and use `calculate selected size` as you see here:
![image](https://user-images.githubusercontent.com/5789283/39677214-619f89f4-5177-11e8-861d-7314ec1addf2.png)

If i already have the size of other folders and i want to know the size of them all i select those folder but that won't work. It will not show the total size of the selected folders.
![image](https://user-images.githubusercontent.com/5789283/39677239-c6f93660-5177-11e8-92e4-1b7ac238ec9a.png)

If i want to get the total size of more than one folder i need to select them before i open the context menu. ~~I also need to open the menu at the right place, because if i point on the folder name instead of the folder icon it will unselect all other folders.~~

Why can't you use the already collected size and add them together when i already have calculated the size of a folder?

**Comment by qooob** [comment]
It's happening for the reason to let server-side to perform the calculations and unit conversion.

You can activate a feature to calculate size on selecting, using space, in File Manager configuration. 

Then it's not an issue at all?

**Comment by qooob** [comment]
When selecting, it's not the icon that you need to click to keep the selection but one of the selected rows.

**Comment by Sopor-** [comment]
But even if i calculate with space it still won't use the value on already calculated folder... If you can't do something about it there is nothing more to do :(

Btw, could you highlight the rows so it is possible to see what options i turn on and off in the Configurable options for File Manager, or at least make some line. It is hard to see when there are no lines or highlights which on/off to toggle.

**Comment by qooob** [comment]
Ref.: https://github.com/qooob/authentic-theme/issues/629
