### ISSUE TITLE
File manager - Properties

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1137]
When using properties it is a bit tricky to use the additional menu because if i'm not very precisely with the mouse it will close the menu and i have to go back to properties and try again.

![image](https://user-images.githubusercontent.com/5789283/39679401-2b229c92-519d-11e8-871c-f7777bbe06b6.png)

**Comment by qooob** [comment]
Yes, correct. I'll fix it.

I was actually trying to make context sub-menus to be more forgiving for inaccurate mouse movements but I couldn't easely make it work. I will try to do it for all menus in the future.

This particular issue should be very easy to fix. I'll do it a bit later.

**Comment by qooob** [comment]
Will be fixed in 19.17.
