### ISSUE TITLE
File manager - Change permission

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1138]
When changing permission the permissions are not showing the current state of the file. It shows 0 when the file has 0664. Shouldn't it pick up the permission of the file and show it?
![image](https://user-images.githubusercontent.com/5789283/39679935-8c11e426-519e-11e8-8776-4b77ef995e71.png)

**Comment by qooob** [comment]
It should use and show current file permission setting.

Do you select one file or many? How can I reproduce it, becase it's meant to work the way you described it.

**Comment by Sopor-** [comment]
1. Open `Properties / Change permissions` and you will see the permissions (shouldn't the check marks also be selected, something like this?).
![image](https://user-images.githubusercontent.com/5789283/39770860-8e8f6f18-52f0-11e8-8b3d-26ee5fa1060a.png)


2. Delete the permission so the field is empty or select any check marks and then press `cancel` so the window closes.
3. Open `Properties / Change permissions` again and all the changes you have made is still there.

Even if you press the Refresh button it won't change. To get the current state you need to press the File manager in the left menu. Now it will show the correct permissions again.
