### ISSUE TITLE
File manager - why will the distance change after a refresh?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1140]
When i open the file manager i have this empty space but after a refresh it will decrease. After a refresh it seems to keep the same distance.

![image](https://user-images.githubusercontent.com/5789283/39957670-01e0be78-55f7-11e8-8e6f-5fa369ebf29f.png)

**Comment by qooob** [comment]
I have also noticed this. I think it's internal dataTable issue. It's in my personal todo list, when release for  minor issues is going to come.

Thanks for noticing.

**Comment by Sopor-** [comment]
I don't know if this can be to any help?
It seems that if i get a scrollbar when i open the file manager it will be the smaller gap, but if the folders fit the web browser page it will be the bigger gap.

**Comment by rostovtsev** [comment]
Okay, latest commit fixes all issues with column's widths. The _name_ column will always have priority and try to expand to maximum. _Last modification time_ header label will become _Modified_ with next Webmin release. 

_Permissions_ header's label takes more space than the data in the columns itself, but I couldn't come up with better, non-abbreviated label for it.

Example.

![image](https://user-images.githubusercontent.com/4426533/52339147-5af5ff00-2a1d-11e9-915d-debedb7160cf.png)

Give it a try.
