### ISSUE TITLE
part of mouse menu diving in page bottom

### ISSUE THREAD

**Issue by mrjk990** [qooob/authentic-theme#1141]
hi 
as you can see i can't reach the rest of menu
i use Chromium 64.0.3282.140
and  authentic theme 19.18 

![default](https://user-images.githubusercontent.com/16126451/39960611-8a81e590-562e-11e8-9e17-e21edcebf88d.png)

**Comment by qooob** [comment]
Yes, it's plugin bug.

Does it only happen on this particular row, because menu actually does popup upwards.

**Comment by qooob** [comment]
Okay, fixed.

**Comment by mrjk990** [comment]
thanks
