### ISSUE TITLE
Touchscreen virtualmin dropdown pulls up keyboard and losses focus mby all dropdowns

### ISSUE THREAD

**Issue by Revenger** [qooob/authentic-theme#1143]
Oh my mobile and tablet whenever I click the domain dropdown my keyboard pops up and the dropdown closes.  This means I can't switch between domains on touchscreen devices.

I assume that other dropdowns might be bugged also.
I don't know when the bug started but it hasn't been there since initial release.

Desktop and mobile mode in the browser makes no differences.

**Comment by qooob** [comment]
I'll fix it in small 19.19 release. 

Thanks for reporting.

**Comment by qooob** [comment]
Do you mean dropdown select, right under Virtualmin switch? I tried it and I can only see it happening in case filter is on. The filter is hardcoded to be off for this matter. Interesting.

I also tested other un-native selects and they seem to work fine.

Which browser do you use on your mobile devices? Which mobile devices do you use?

**Comment by Revenger** [comment]
Yea its the dropdown.

Managed to get a quick screenshot when the keyboard pops up for a split second.
It's the input field.
What is happening is you click the dropdown it focuses on the input field the keyboard pops up then the dropdown and keyboard closes pretty much instantly.

[https://imgur.com/a/e3TXxqM](url)

**Comment by qooob** [comment]
Okay, it's fixed. I also fixed scrolling for navigation menu and made some other improvements for touch-enabled devices.

Please give it a try.

**Comment by qooob** [comment]
Oops, there was a bug between mentioned commit and now. Please force update in case you ran update  within last 30 minutes.

**Comment by Revenger** [comment]
Just tested, working fine now.

Cheers, I sometimes like to lay in bed with my tablet managing the sites so this help a lot.

**Comment by qooob** [comment]
Glad it works. Thanks for reporting.
