### ISSUE TITLE
multiple submit buttons and &error() preserves old clicks

### ISSUE THREAD

**Issue by bsmith94** [qooob/authentic-theme#1144]
I have a form with multiple submit buttons on it. If an error occurs, my handler script invokes ```&error($msg)```. If the user clicks "Return to previous page" and submits the form again, data representing the previous click is present in the POST data. I'm attaching a simple module that demonstrates this behavior. When you click on one of the three buttons, the next page displays a JSON representation of the POST. Click the buttons and the "Return to previous page" a few times and I think you'll see the problem. This does not occur when using the old webmin theme.

I'm using Firefox 59.0.2 on Mac OS X 10.13.4. Webmin is 1.881, authentic-theme is 19.16-2.

[sfw_test.zip](https://github.com/qooob/authentic-theme/files/2007221/sfw_test.zip)

**Comment by qooob** [comment]
When you click the back button, is it JavaScript `go.back()` or regular link?

**Comment by bsmith94** [comment]
The link is ```javascript:history.back()```.

**Comment by qooob** [comment]
I just came back home tonight. I will get back to you in couple of days, as settle things up.

**Comment by qooob** [comment]
Very nice global bug to disclose. Thanks. I'll fix it for 19.19. :wink:

**Comment by qooob** [comment]
It's fixed. Thanks a lot for reporting!!

**Comment by bsmith94** [comment]
Looks good. Thanks!
