### ISSUE TITLE
File manager - no highlighted rows in configuration

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#1145]
In issue #1136 i wrote about the rows that was not highlighted. These rows are not highlighted:

![image](https://user-images.githubusercontent.com/5789283/40117276-c4d2623e-5916-11e8-9940-0b55963f6895.png)

**Comment by qooob** [comment]
Do you mean on mouse hover? I will fix it, no problem.

**Comment by Sopor-** [comment]
Yes, it makes it much easier to see which Yes/No that belongs to what option.

**Comment by qooob** [comment]
Fixed.
