### ISSUE TITLE
The content does not appear in the notification.

### ISSUE THREAD

**Issue by kosugikun** [qooob/authentic-theme#1148]
<img src="https://mcpenano.net/1.png"></img>
<img src="https://mcpenano.net/2.png"></img>

**Comment by qooob** [comment]
What is the installed theme version?

Can you describe steps to reproduce it? I have it working fine on all servers with latest 19.19.

What is on the browser's console?

**Comment by kosugikun** [comment]
iOSのSafariです。
The version of the theme is 19.19.
Safari on iOS, this bug has always occurred.

**Comment by qooob** [comment]
Thanks, better late than never. It's good that I could reproduce it in my emulator.

Force update to the latest development version.
