### ISSUE TITLE
Touch scrolling of the right hand pane not working on iPad/iPhone

### ISSUE THREAD

**Issue by pierstaylor** [qooob/authentic-theme#115]
Hello,

I have been trying to use the Authentic theme on iPhone and iPad.

I found that the touch scrolling of the right hand (content) panel does
not work.

I have fixed this locally by adding the following css to my styles.css file.

/* scroll fix for iPad */
#content {
    -webkit-overflow-scrolling: touch !important;
    overflow-y: scroll !important;
}

You might care to add this to your core css file so that it works "out of
the box". Because of the css file calling order I have had to use 
!important;

You could probably dispense with this if you are adding it to the core 
files.

With best regards,

Piers

**Comment by qooob** [comment]
Piers, thank you very much! I will test it and add it to the general code!

It's great to have this fixed!! :)

....

I tested it it and it adds the second scroll bar on the right in normal desktop mode and possible other mobile, non iOS browser. Could you please test, if it's gonna work without the following:

`overflow-y: scroll !important;`

**Comment by pierstaylor** [comment]
OK, I think I already checked that, but I will check again. 

I didn't notice the double scroll bar! I'll take another look at the css and see if I can figure 
out how to lose that. It may need some JavaScript - I have had to do it that way before
when making stuff work for the iPhone/iPad.

I also noticed a 4 or 5 pixel margin at the bottom of the right hand panel (nothing to
do with the iPad fix) which doesn't really show up with your light grey background
but does with darker colours. I'll see if I can figure out where that comes from while
I'm looking into style sheet stuff.

P.

**Comment by qooob** [comment]
That was done intentionally as not having it added some extra scrolling. I will also take a loot at it. As far as I remember it's something about not making height 100% and 99%.

Here is the screen of double scrolling, look on the right:

![screenshot from 2015-02-26 11 53 49](https://cloud.githubusercontent.com/assets/4426533/6388773/7dafffda-bdae-11e4-8099-21de09e2986d.png)

I would think that removing `overflow-y: scroll !important;` doesn't change much. But it's better to be tested.

**Comment by pierstaylor** [comment]
> as I remember it's something about not making height 100% and 99%.

I think I've seen this kind of problem before, and it is solved by putting ```overflow: hidden``` on the container of the thing generating the scroll bars. 

> I would think that removing overflow-y: scroll !important; doesn't change much.

I think that this is the other part of the fix. ```-webkit-overflow-scrolling: touch !important;``` gets you the touch events (for iPad/iPhone) and then ```overflow-y: scroll !important; ``` allows these events to actually move the element. The iPad fixes the height of the iframe so you actually have to scroll the iframe within its container. Yes I know - that seems crazy because it is a bit crazy, but it is how apple have done this.

I'll look over the extra scroll bar issues (both the iPad fix induced one and the 99% one) when I can.
I'll test any fixes on a few browsers also.

P.

**Comment by qooob** [comment]
Thanks! Adding `overflow: hidden` adds extra scroll bar on the right!

Try not using styles.css. Please open default.min.css, beautify it online and try adding the same stuff to it. At the beginning of file there will be `#content.__page {` try putting your code right above it. It will make it easier to add it to the distro.

Looking forward to your results!

**Comment by pierstaylor** [comment]
> Adding overflow: hidden adds extra scroll bar on the right!

Yes, that's one of the pitfalls, but sometimes adding it to one of the containers will
solve this kind of problem. I will have to check out the nesting and compare to
projects where I have had this problem and fixed it. Still, we may need to settle
for the 99%!

> Try not using styles.css. Please open default.min.css...

Ok, I'll make changes in default.min.css

**Comment by qooob** [comment]
I have made that less than 4px or 5px - don't bother about it..

**Comment by qooob** [comment]
Besides if it add extra scroll bar and and it's doesn't work with out that `overflow-y: scroll !important`, no worries, I maked it work using JS.

**Please add it to the custom scripts.js and remove all extra CSS you made, let's see if it works for you (I believe it will):**


```
// Fix Apple's scrolling
if (window.location == window.parent.location && navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
	$('#content').attr('style', '-webkit-overflow-scrolling: touch !important; overflow-y: scroll !important;');
}

```

**Comment by pierstaylor** [comment]
Hi,

Yes, that should do it - I won't be able to test until later, I don't have my iPad here.

P.

**Comment by qooob** [comment]
Ok! Look forward for the tests!

**Comment by pierstaylor** [comment]
Ok, here are the results.

I added the following to *scripts.js*. I didn't include the *!important* because these styles are being added directly to the element, and therefore already have the highest priority.
```// Fix Apple's scrolling
if (window.location == window.parent.location && navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
    $('#content').attr('style', '-webkit-overflow-scrolling: touch; overflow-y: scroll;');
}```

This works exactly as intended, and the touch scrolling functions correctly on iPad and iPhone.

I also have some style sheet fixes that I'm testing for various scroll bar issues (not related to this)
but I will raise another ticket to deal with these and their proposed fixes when I have finished testing. I realise it's bad practice to deal with more than one issue in a single ticket!

Thanks for your help with all of this - and a great looking webmin theme!

P

**Comment by qooob** [comment]
Perfect, thanks to you too!! I will add it to version 10.0.0 very soon!

**Comment by qooob** [comment]
By the way `!important` in `.css` can override direct styling! AFSIK ;)

**Comment by sseninfo** [comment]
Try this it's working for me


if (window.location == window.parent.location && navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
    $('#orderpop').attr('style', '-webkit-overflow-scrolling: touch !important; overflow-y: scroll !important;');
}

	preventScroll : function(prevent) {
        var body = $('body'), html = $('html'), scroll;
        if (prevent) {
            var width = body.css('width');
            scroll = window.pageYOffset;
            // This is all you need to do to prevent scroll on everything except iOS.
            html.css({ 'overflow': 'hidden'});
            // For iOS, change it to fixed positioning and make it in the same place as
            // it was scrolled.
            // For all systems, change max-width to width; this prevents the page getting
            // wider when the scrollbar disappears.
            body.css({ 'position': 'fixed', 'top': -scroll, 'max-width' : width});
        } else {
            scroll = -parseInt(body.css('top'));
            html.css({ 'overflow': '' });
            body.css({ 'position': '', 'top': '', 'max-width': '' });
            window.scrollTo(0, scroll);
        }
    },
});

**Comment by qooob** [comment]
`window.location == window.parent.location` - will register this code for the left frame - _why?_

`$('#orderpop')` - there are no objects like that in the theme - _what does it do?_
