### ISSUE TITLE
Add ability to customize login page with company logo

### ISSUE THREAD

**Issue by dustindauncey** [qooob/authentic-theme#116]
It would be great to have the ability to customize the front login page with a company logo. That way we can hide or "re-brand" Webmin & Usermin from a users perspective and they will have more trust in logging in knowing the company logo is there as a customer might expect it to be.

**Comment by qooob** [comment]
Alright. How? Should be Webmin logo and title kept and your logo be put right below or somehow else?

**Comment by specktator** [comment]
hmmm... I think it should be in that form with or without placeholder 
![screenshot from 2015-02-28](https://cloud.githubusercontent.com/assets/3157413/6427032/949e6478-bf7c-11e4-8ccc-ab11f8d8c7fd.png)

**Comment by qooob** [comment]
Oh, that I can do! No problem, will add it to the most awesome, up coming, version 10.0.0! It's scheduled to be released within 48 hours.

**Comment by dustindauncey** [comment]
That's fantastic customer service! :-)

For what it's wowrh, my personal thought was simply to replace the Webmin logo, not add another logo to the bottom of the page. 

I hope that makes sense. :-)

**Comment by qooob** [comment]
Will see what works the best..

There is no customer service really!! :)) I just do it because of love!

**Comment by qooob** [comment]
The support for custom logo on login page will be added in version 10.0.0 shortly.
