### ISSUE TITLE
Loading screen stuck

### ISSUE THREAD

**Issue by fraksken** [qooob/authentic-theme#117]
Hey,
Running basic Debian 7,8 with virtualmin installation.
When going to System Settings => Edit server template (or create new template) => Bind DNS Domain:
Changing following settings triggers a never ending loading screen:
- DNSSEC Cryptographic Algorithm

I could reproduce this in chrome (win & mac) and safari.

**Comment by fraksken** [comment]
Same problem occurs when trying to change following settings:
- Webmin => Networking => Linux Firewall => Set Default Action To: [Dropdown] (changing dropdown menu triggers problem)

**Comment by qooob** [comment]
Confirmed! Thanks for reporting! I will fix it in version 10.0.0 in couple of days.

To work around the problem, please double click on stuck loader.

**Comment by fraksken** [comment]
Great! Thanks for the fast response!
