### ISSUE TITLE
Alt Gr + V (@) bug

### ISSUE THREAD

**Issue by ecrazor1911** [qooob/authentic-theme#118]
Hello,

When I press (Alt Gr + V) the Virtualmin redirect to virtualmin homepage.

**Comment by qooob** [comment]
:) Hotkey for Virtualmin takes you to Virtualmin? What did you expect?

**Comment by ecrazor1911** [comment]
I understood. But I can't write the e-mail address, just CTRL+C/V. :D

**Comment by qooob** [comment]
Hmmm.. Alright. I will make Hotkey work only for not-current state.

Thanks for advising!

**Comment by ecrazor1911** [comment]
Thank you! Btw. your design is awesome! I'm happy to found this. :-)

**Comment by qooob** [comment]
Thank you! I think you gonna like version 10.0.0 much more, I hope! ;) Coming very soon.
