### ISSUE TITLE
Webmin does not show after login

### ISSUE THREAD

**Issue by yakuz** [qooob/authentic-theme#119]
Hi,
I have installed this theme by uploading package on webmin panel. After that page has been refreshed. Now I can see only loader. Console is showing an error:
Failed to load resource: the server responded with a status of 500 (Perl execution failed).
I did something wrong?

I use Debian 7 with LAMP installed.

**Comment by qooob** [comment]
At first click on the loader twice to make it go away. Second try restarting Webmin and closing the tab in the browser, clearing the cache and then opening it again (in case it's Firefox, in case of Chrome just reload).

If you installed `authentic-theme-latest.wbt.gz` it should be fine. In case you downloaded from GitHub using `donwload` button, then you would need to rename `authentic-theme-master` to `authentic-theme`.

In case you need to revert to previous theme and install [missing Perl Modules](https://github.com/qooob/authentic-theme#requirements), just type in URL `host.example.com/webmin` and go from there again.

**Comment by yakuz** [comment]
Thank you so much. I have installed libwww-perl and and all works good :)
My bad, I have missed the requirements. Sorry for bothering you.

**Comment by qooob** [comment]
No problem, pal! :) Have a good day!
