### ISSUE TITLE
The loader is still an issue in the latest version (SOLVED) updated and it works great now -- Thank you

### ISSUE THREAD

**Issue by motionland** [qooob/authentic-theme#120]
Hello, 

I noticed the loader(stuck on spinner all pages) is still an issue. I disabled it and it worked fine so I thought you might want to disable the loader option until it is completely resolved.. Awesome work! Many Thanks for such a cool theme

**Comment by webdo** [comment]
I personally never had any problems with the loader.

**Comment by qooob** [comment]
Is issue resolved?
