### ISSUE TITLE
Increase size of command in cron jobs

### ISSUE THREAD

**Issue by Leen15** [qooob/authentic-theme#121]
Hi, would be fine if you can increase the size of command input box in cron jobs as "Input to command" box.

See attach.

Thanks
![command box](https://cloud.githubusercontent.com/assets/3629071/6572224/d1b29c3a-c710-11e4-83eb-8c334d8357de.png)

**Comment by qooob** [comment]
Thanks for using my theme! Well, sure I could increase it but you could easily do it yourself by using custom styles. Simply add the following to custom `style.css` to get desired result:

```CSS
input[name*="cmd"] {
	min-width:400px;
}
```

**Comment by Leen15** [comment]
Yes but you made a great theme and i'm trying to use it on some VMs, so it's not convenient to make it on every webmin session :)

**Comment by qooob** [comment]
I see. It that the only place where you think that `input`'s width should be increased?

**Comment by Leen15** [comment]
- Description field in same page
- View log file field in System Logs
- TCP Wrappers -> Edit Deny Rule -> Remote Hosts/Shell commands
- Partitions -> Filesystem label
- Disk and Network filesystem -> Edit Mount -> all fields in Swap file section

Should be enough for me :D

**Comment by qooob** [comment]
I will take a look closer to the next release and I will add it to the distro for you. Please keep searching for more and post it here.

Thanks for advising.

**Comment by Leen15** [comment]
Thanks a lot, of course!

**Comment by lukesUbuntu** [comment]
+1 for cron job increase hard to see what commands are been run.

Great job of the theme

**Comment by qooob** [comment]
Yes, yes I will add this for sure in the next release! :) Was releasing quickly a fix.
