### ISSUE TITLE
Drweb console for unix mail servers does not start

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#122]
the module gets 404 on /unauthenticated/js/default.src.js and does not start.

**Comment by qooob** [comment]
Can you find any of `src.` in authentic.pl??

**Comment by badfiles** [comment]
Where should I be looking for to find?

**Comment by qooob** [comment]
In `/usr/libexec/webmin/authentic-theme`

**Comment by badfiles** [comment]
/usr/share/webmin/authentic-theme# ls 
authentic-lib.cgi  buttons.cgi   changelog.pl  images     lang     navigation.cgi  session_login.cgi  theme.info       VERSION.txt
authentic.pl       CHANGELOG.md  config        index.cgi  LICENSE  README.md       sysinfo.cgi        unauthenticated

**Comment by qooob** [comment]
`authentic.pl`

**Comment by badfiles** [comment]
authentic.pl does not have substring "src."

**Comment by qooob** [comment]
Then I'm not sure what your initial issue is all about.. Could you please rephrase your question?

**Comment by badfiles** [comment]
One of my webmin modules does not start. Actually it does not show any output. Network analysys shows 
:10000/unauthenticated/js/default.src.js
Request Method:GET
Status Code:404 File not found

**Comment by qooob** [comment]
I can't understand what makes `default.src.js` requested. What module you're talking about?

**Comment by badfiles** [comment]
Drweb console for unix mail servers

**Comment by badfiles** [comment]
It does not requet default.src.js with default theme

**Comment by qooob** [comment]
Go to `unauthenticated/js/` in your shell and copy (or symlink) `default.min.js` to `default.src.js` and reload the page.. What do you get?

**Comment by badfiles** [comment]
I get this. The .cgi obviously does not start well.

:10000/drweb-maild/modules/quarantine.cgi
Request Method:GET
Status Code:500 Missing Headers

Connection:close
Content-type:text/html; Charset=iso-8859-1
Date:Fri, 13 Mar 2015 22:35:12 GMT
Server:MiniServ/1.730

**Comment by badfiles** [comment]
there are 2 conditions. When there are no default.src.js it is requested.

when I make it out of default.min.js it is not requested at all. How is this possible?

**Comment by badfiles** [comment]
the module has it's own js and jquery. Maybe the problem is there?

**Comment by qooob** [comment]
Hmmm. I will be able to cone back to this only tomorrow morning.. Night is moving on.. Will let you know more tomorrow..

**Comment by qooob** [comment]
cone=come

**Comment by badfiles** [comment]
ok

**Comment by badfiles** [comment]
There's a typo in update notice 'Don't forget nor be lazy to post to'

**Comment by qooob** [comment]
Where do I download a module for DrWeb and how do I install DrWeb itself?

**Comment by badfiles** [comment]
You probably dont'n need DrWeb itself to install the module, I'll make some research on a server without one and give you all the details to start testing the beast.

**Comment by badfiles** [comment]
DrWeb and its module are proprietary, but you can get an outdated version here http://officeshield.drweb.com/drweb/debian/dists/6.0.2/non-free/binary-amd64/drweb-maild-web_6.0.2.1-1203141319~lenny_all.deb. I don't think the latest version differs importantly for our case.
The .deb contains drweb-maild-web.wbm.gz.
On the first run it will find your system is missing some perl modules, choose 'make and install' (do not test -- I had problems with test on my system)
When it is satisfied with the modules you have, It will tell you have no configuration, init and MTA.
Put 'postfix' into MTA field, '/bin/true' into control script, and give a full path to a file containing the text below into 'Maild config full path'.

[Quarantine]
Path = /tmp

**Comment by qooob** [comment]
Why `postfix` I'm using `postfix` ;) OK. I got stuck with error message

`Error: Dr.Web MailD Quarantine path is not found. Set the path to Quarantine in Dr.Web MailD configuration file (as a value of Path parameter in the Quarantine section):`

The problem of what I can see already, is that Module developers don't use proper format, thus `header()` and `footer()` of Webmin API. It makes little sense to me.

Do you have stuck loader or error in the console?

**Comment by qooob** [comment]
Ah.. OK! I think I got it. Please open `/authentic-theme/unauthenticated/js/incompatibility.src.js` and replace in it default.src.js with `default.min.js`. My bad, forgot to change it back.

Does it help?

**Comment by badfiles** [comment]
To start the module you need to create a file 'name.conf' and put 
[Quarantine]
Path = /tmp
into it, then give the fill path to this file to the module (Maild config full path field)

the change in incompatibility.min.js does not help.

**Comment by qooob** [comment]
I started module the other way. Please clear cache. I made a change on that file, and error with default.src.is is gone. Please try again.

**Comment by badfiles** [comment]
Should I clear browser cache?
Which file has been changed? I don't see any theme changes except you told me to replace default.src.js with default.min.js.
There is no error with default.src.js  after I changed incompatibility.min.js,
the module still returns '500 Missing headers'.

Did you finally make it work well in your test environment?

**Comment by qooob** [comment]
No, I still have missing headers. Sometimes it runs out of no reason. I bet there are conflicts with loading scripts. DrWeb module loads some JS files that theme also loads, like jQuery for example. At the same time module loads no footer at all. It's not right. I would at first contact DrWeb support and asked them to write their module with proper standards. 

Why DrWeb and not ClamAV for instance? It's not proprietary?

**Comment by badfiles** [comment]
Ok, while your theme is not default I don't think they make any changes to the module. I had to add simple user rights based on webmin's user API on my own, the support is awful with this product. 

During our internal testing it showed the best performance against spam, almost no false positives, very low false negatives, antispam core is a compiled C library (best performance), above this simple integration to existing MTA, configuration and blacklist-whitelist management via webmin module, and separate quarantine management via the same module. It had no user rights, but it's not a problem now.

**Comment by qooob** [comment]
I understand what you mean, pal! I wish I could help you to solve the modules problems but I will not be able to do it. The main reason, is that I believe, those changes must be done by them and not by the theme workarounds. When _Authentic Theme_ becomes default (I hope it will happen one day or the other) they should do the change very easily.

Meanwhile, my frank recommendation to you, is to take a look at Spamassassin+ClamAV - they also show magnificent results and very flexible in setup. Besides, Webmin/Virtualmin supports both of them, making installation even easier. Even more, Spamassassin potentially should have much greater number  of users all over the world and thus, better both, performance and spam detection results.

Anyway, I'm closing this issue for now, as there is not much I can do about this. I'm truly appreciate that you have discovery that little bug.

**Comment by badfiles** [comment]
The issue is back with 17.70.
Dr.Web's support refuses to update module.

**Comment by qooob** [comment]
Could you remind me, what issue exactly are you talking about?

Was it there in 17.65?

**Comment by badfiles** [comment]
The module gives no output.
The issue appeared again in 17.70, 17.65 was OK.

**Comment by qooob** [comment]
Could you open source for the right frame and make a screenshot of it?

**Comment by badfiles** [comment]
On console
273 VM916 init.min.js?1770:6 Uncaught TypeError: $.url is not a function$__was @ VM916 init.min.js?1770:6
 
[out.txt](https://github.com/qooob/authentic-theme/files/132052/out.txt)

**Comment by qooob** [comment]
Can you please open `package.css` find and replace the following:

Find:
`body:not(.csf)`

Replace:
`body:not(.csf):not(.drweb-maild)`

Afterwards, reload browsers cache and try again?

Solved?

**Comment by qooob** [comment]
..how unwise by module's developers not to include `footer()`..

**Comment by badfiles** [comment]
Yep, this solves the issue. Thank you.

**Comment by badfiles** [comment]
But tons of this are on console:
init.min.js?1770:6 Uncaught TypeError: $.url is not a function$__was @ init.min.js?1770:6

**Comment by qooob** [comment]
It's because module's developers don't bother to include `footer()`.

Why are you using DrWeb? What it exactly does that Spammassassin + ConfigServer Security & Firewall can't do?

**Comment by badfiles** [comment]
How should a line including ui footer look like?

**Comment by qooob** [comment]
Find in module files `header()` or `&header()`. Exactly the same should be for footer, like `footer()`. Try including it. Should work, I guess.

**Comment by badfiles** [comment]
I found only ui_print_header(...)
No other relevant lines on key 'header('

**Comment by badfiles** [comment]
I plugged ui_footer, but console errors keep coming in,
[out (3).txt](https://github.com/qooob/authentic-theme/files/132166/out.3.txt)

**Comment by qooob** [comment]
You need something like `ui_print_footer("/", 'DrWeb');`

**Comment by badfiles** [comment]
I've found commented out ui_print_footer and plugged it back in.
The output is 2 comments above.

**Comment by qooob** [comment]
If you open source for right page now, do you see `authentic.min.js` at the bottom? Did you restart Webmin?

**Comment by badfiles** [comment]
Yes. No.

**Comment by qooob** [comment]
Don't bother about console errors. It must be something else. This issue should be addressed to modules developers.

**Comment by badfiles** [comment]
I would not, but the error rate is ~5 errors per second and the progress bar with spinner on the top are always shown.

**Comment by qooob** [comment]
I wish I could help you with this dated module.

In case it throws such errors, header must not be included in some frames. You could make a patch but that would take some effort.

**Comment by badfiles** [comment]
I see where to look for, thank you.

**Comment by qooob** [comment]
..or you could open it in new tab..

**Comment by badfiles** [comment]
In a separate tab works great, thank you again.

**Comment by qooob** [comment]
You're welcome.

**Comment by badfiles** [comment]
Will you please keep this
`body:not(.csf):not(.drweb-maild)`
because without it the module does not start even in a separate tab and even with proper footer?

**Comment by qooob** [comment]
It even doesn't work if it's added to exclusion list? (17.72). What is the module's folder name? What if you add it to exclusion list? It should work?

**Comment by badfiles** [comment]
Oops, it does. Didn't know about exclusion list, sorry.

**Comment by qooob** [comment]
Which name did you pass there to make it work?

**Comment by badfiles** [comment]
Well, excuse me again, but it was browser cache issue. After cleaning the cache I cannot start the module again. The name in exclusion list is `drweb-maild`.

**Comment by qooob** [comment]
It can't be browser's cache as this feature processed by the server. I would recommend restarting Webmin/server to fix the issue.

**Comment by badfiles** [comment]
I have made footer as you described, and it worked pretty well, but now (from 17.82) I cannot scroll the page down.
Why might that be?

**Comment by qooob** [comment]
Hi,

Could you please add this to your CSS extensions (on theme's settings) and tell me if it fixes the issue?

```CSS
body[data-module].__e__ {
    overflow: auto;
}
```

**Comment by qooob** [comment]
..or update your `authentic.min.css` with [beta](http://rostovtsev.ru/pub/src/authentic/17.84b/authentic.css) version..

**Comment by badfiles** [comment]
it works again in 17.84, thank you.
