### ISSUE TITLE
Log view & config edit

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#123]
Long lines in System logs are wrapped turning a log into a mess.

Unix line ending (0x0A) pops a strange symbol.
![screenshot from 2015-03-15 17 57 56](https://cloud.githubusercontent.com/assets/1597304/6656463/0d8a6e6a-cb3d-11e4-818b-1c39e3921221.png)

**Comment by qooob** [comment]
Alright, we have encountered it before. Please, go to `Webmin-Webmin Configuration->Language` and make sure that you set UTF-8 like english. It should fix the problem.

**Comment by qooob** [comment]
I just noticed: Did you change that dots in the menu? That's the way it's intended to look:
![screenshot from 2015-03-15 19 16 56](https://cloud.githubusercontent.com/assets/4426533/6656841/f15176ca-cb47-11e4-844b-f6c1f3d3428e.png)

**Comment by badfiles** [comment]
I haven't ever changed your code except the cases you told me to.
First thing I did was changing language to eng.utf-8, but it did not help. Strange.
What about the wrapped lines?

**Comment by qooob** [comment]
It should help. Restart Webmin please and refresh System Information (Green big button on SysInfo page). What OS and browser do you use?

**Comment by badfiles** [comment]
I use google chrome unstable and ubuntu 14.04

**Comment by badfiles** [comment]
The strange symbols in edit disappeared, webmin has to be restarted after language has been changed. This should be mentioned in language dialog, but that is webmin issue.

Still, what about wrapped strings in log view?

**Comment by qooob** [comment]
Ahh! :) OK! Never combine issues! It will create more issues!

Yes, I fixed it. Please download updated `.css` to double-check and see what you get.

Don't forget to purge cache:
https://rostovtsev.ru/pub/src/authentic/10.2-patches/default.min.css
