### ISSUE TITLE
Running process is hidden

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#124]
Running processes output (like webmin upgrade, or theme or module installation, or system packages update) is hidden by a rotating something and only the final result is shown. 

It is not good when you don't know what's going on and when it is going to end.

**Comment by qooob** [comment]
Do you know that there are [settings](https://github.com/qooob/authentic-theme#how-do-i-use-theme-settings) that let you disable a loader at all? 

Besides, there is inbuilt option, that let's you prematurely [dismiss the loader](https://github.com/qooob/authentic-theme#features) by double mouse clicking on it or double shift key? :)

Is it helpful?

**Comment by badfiles** [comment]
Of course I didn't know. I am testing your theme just for a couple of days. Will try when 
I get to my PC.
