### ISSUE TITLE
BIND DNS zones look real funky

### ISSUE THREAD

**Issue by virtualmin** [qooob/authentic-theme#126]
I believe these are in a table in the framed theme, and I think it counts as tabular data, so keeping it in a table might be wise. I know it's hard to do because Webmin uses tables for everything, including things that ought not be in a table. If we need backend changes to make it work, we can probably do that, since this is in a specific location and probably doesn't touch too much code.

http://i.imgur.com/34lrgcD.png

**Comment by qooob** [comment]
I totally agree!! :D And I prefer displaying that data in tables as well. Same about _Apache/MySQL_ modules and some other. I think you should let Jamie know that fact, that by default, it's displayed in ugly non-tabular way.

Meanwhile, all you need to do to get your tables back, is to click `Module Config` on top of the BIND DNS module and change `Display domains as` from `Icons` to `List`.

I believe it will help. Cheers! ;)

**Comment by jcameron** [comment]
One option would be for the theme to force display in a table, by setting the appropriate %config entry when that page is loaded.

**Comment by qooob** [comment]
Thanks, I will take a look. ;)
