### ISSUE TITLE
Module loading gets stuck

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#127]
Way to reproduce:
You need to have at least two HDDs and 'SMART Drive Status' module enabled.
By default the first drive is selected, so select the second one. 
No module could be loaded after that (page refresh helps), and the rotating thing appears, even though it is disabled in settings.js. Double click does not cancel it either.

**Comment by qooob** [comment]
Thanks, pal! You discovered general bug for all `select`s when loader is off. Please update `global.min.js` to double check.

Don't forget to clear cache:
https://rostovtsev.ru/pub/src/authentic/10.2-patches/default.min.js
