### ISSUE TITLE
User categorize setting ignored

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#128]
If a user has NO in UI settings / categorize modules, modules get categorized in spite.
You should  also check if global categorizing setting works properly.

**Comment by qooob** [comment]
Could you please explain more of what you mean, I didn't quite understand? Where the those settings?

**Comment by badfiles** [comment]
each user has its own UI settings. 
Webmin users / <user> / User interface options / Categorise modules?

**Comment by badfiles** [comment]
D-github ate \<user\>

**Comment by qooob** [comment]
Oh, man.. ok... Thanks..

**Comment by qooob** [comment]
Alright, it will be fixed shortly in version 10.3. Thanks for pointing out!
