### ISSUE TITLE
Main menu unavailable while sysinfo is starting

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#131]
Right after login in case of sysinfo slow start the main menu remains unavailable. The current default theme shows the main menu before sysinfo, and an operator can take control not having to wait for sysinfo's successful start.

Same thing happens with our buggy 'DrWeb module' if it is the only one user allowed to run. To see the main menu one has to open module config first.

**Comment by qooob** [comment]
Alright, makes sense. Will be added to the next 10.30 release soon.
