### ISSUE TITLE
Waste of space, short command line and buggy list markers.

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#132]
Why is the marked space wasted?
The command line is too short.
The list markers are drawn wrong in Chrome 42 and 43. (FF 36 is OK)

![screenshot from 2015-03-18 13 47 14](https://cloud.githubusercontent.com/assets/1597304/6707199/a2cd4256-cd75-11e4-9951-899189a2e7a3.png)

**Comment by qooob** [comment]
No worries, pal! It's already fixed in my dev built, which is going to go live within 48 hours.
