### ISSUE TITLE
Log file view is word wrapped making it very hard to look through log files.

### ISSUE THREAD

**Issue by sle44102** [qooob/authentic-theme#133]
I love the new authentic theme except for one big issue, log file view has wordwrap which makes them almost un-readable.  I modified the css to fix this, but though i would share/suggest the change to the css

CSS FILE:
    /usr/libexec/webmin/theme/authentic-theme/unauthenticated/css/default.min.css 
    after deminifying & beautifying the file at about line 2335 you have

pre {
    font-family: monospace;
    font-size: 12px;
    margin: 0;
    white-space: pre-wrap;
    border: 0
}

comment out the white-space: pre-wrap;

pre {
    font-family: monospace;
    font-size: 12px;
    margin: 0;
    /* white-space: pre-wrap; */
    border: 0
}

and the output for viewing log files is back to readable.

**Comment by qooob** [comment]
Yes, thank you! I have already fixed it in my dev built, as it was reported already, few days ago. It will be alright in version 10.30, which is released in few days.
