### ISSUE TITLE
Text editor adding weird Â everywhere

### ISSUE THREAD

**Issue by webdo** [qooob/authentic-theme#134]
On one of my server the text editor is adding some Â everywhere, of course there are none of them in the files.

Its only doing this in one of my server so i don't know where it come from, tried to change language.
I removed and reinstalled the theme and the problem is still here.

In authentic: 
![authentic](https://cloud.githubusercontent.com/assets/470782/6746801/d4467f8e-cea4-11e4-82c8-18c8a2bbf848.png)

In normal theme:
![old theme](https://cloud.githubusercontent.com/assets/470782/6746803/daec7384-cea4-11e4-946b-c8d4fe4fdc87.png)

**Comment by qooob** [comment]
Make sure to set language to `UTF-8` in `Webmin->Webmin Configuration->Language` and make sure your browser's encoding is also set correctly. You might need to set on of the force options in the configuration page mentioned above.

**Comment by webdo** [comment]
Thank you its working if i set it in english, it seems that there is a problem in the French UTF-8 file.

As i already said, awesome theme, and  also, congratulations for getting it part of official webmin!

**Comment by qooob** [comment]
Thank. You are welcome!

Does it work with French?

**Comment by webdo** [comment]
It seems that setting it from French UTF-8 to english UTF-8 and going back to French UTF-8 fixed the problem in french too, thats weird! lol

**Comment by qooob** [comment]
No, it's not. This simply happened because browser itself has to detect encoding correctly. Now it's set to `UTF-8` (I mean now your browser settings, not Webmin) and before it was probably something like `Windows-1252`.

**Comment by SavageCore** [comment]
I still get this issue, any ideas?

![Webmin language](http://i.imgur.com/tiGPugn.png)
![Chrome font settings](http://i.imgur.com/zb6T5rZ.png)

Chrome 44.0.2403.157 
Webmin 1.760
Authentic 15.50
