### ISSUE TITLE
Use Bower to maintain css/font/js libraries

### ISSUE THREAD

**Issue by Rvanlaak** [qooob/authentic-theme#137]
Wouldn't it be an idea to use bower to maintain your css / font / js libraries? Found most of the libraries you're using already, rest of them ofcourse can still stay at the /unauthenticated folder :+1: 

You can add a file `.bowerrc` in order to set the install directory. Maybe even make it `/unauthenticated/vendor` :
```json
{
  "directory": "unauthenticated"
}
```
And add a `bower.json` file to pin the dependencies:
```json
{
  "name": "qooob/authentic-theme",
  "authors": [
    "Ilia Rostovtsev <youremail@rostovtsev.ru>"
  ],
  "description": "Authentic is Webmin/Usermin/Virtualmin/Cloudmin theme based on Bootstrap and Font Awesome that is made with love.",
  "license": "MIT",
  "dependencies": {
    "bootstrap": "~3.3",
    "jquery": "~2.1.3",
    "font-awesome": "~4.3",
    "codemirror": "~5.0",
    "select2": "~3.5",
    "malihu-custom-scrollbar-plugin": "~3.0",
    "DataTables": "~1.10",
    "roboto-fontface": "~0.3",
    "bootstrap-file-input": "~1.0"
  },
  "devDependencies": {
  },
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```

**Comment by qooob** [comment]
Thanks for pointing out. Can you tell me what is the practical reason for doing it?

**Comment by Rvanlaak** [comment]
Using a dependency manager allows you to add new libaries, or update them without the hassle of downloading and unpacking them and sub-dependencies yourself. Currently your own css is mixed with the default jQuery css for example.

The libaries you use are included in your own version control system, using a dependency manager can be seen as a best practice :+1: https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

When you build the latest version, just call `bower install` from cli to get the latest versions. Thereafter the rest of the build process can be completed.

**Comment by qooob** [comment]
Thanks, Richard! I'll take a look at it whenever I have time.

**Comment by Rvanlaak** [comment]
:+1:
