### ISSUE TITLE
Infinite Loading Screen on Raspberry Pi 2

### ISSUE THREAD

**Issue by EpicLPer** [qooob/authentic-theme#138]
Hello there!

So I've installed the latest 1.740 Webmin on my Raspberry Pi 2 (Raspian) and activated this theme. I've even updated it already so there won't be a problem anymore, at least I thought so. When I try to access it from my Desktop browser nothing happens and is stuck in an infinite loading screen. Only the little loading-animation in the middle is turning around.
However when I make the browser window tiny so it'll trigger the little button on the left (for mobile devices) I can access other screens just fine and the theme starts working, it seems that there's a problem with the Dashboard display.

**Comment by qooob** [comment]
It's because some Perl modules are missing. Version 11.00 is coming very soon to completely fix this problem and bring new features. Meanwhile double click on the loader to make disappear and see the error message. There were familiar post just few days ago, it will help you to fix it. Please take a look:

https://github.com/qooob/authentic-theme/issues/135

**Comment by EpicLPer** [comment]
Ah, thanks for that tip! So, yeah. I'll post it here anyways, just in case :)

Error - Perl execution failed
Can't locate LWP/Simple.pm in @INC (@INC contains: /home/pi/webmin-1.740 /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl . /home/pi/webmin-1.740/ ..) at /home/pi/webmin-1.740/authentic-theme/sysinfo.cgi line 196.
BEGIN failed--compilation aborted at /home/pi/webmin-1.740/authentic-theme/sysinfo.cgi line 196.

**Comment by qooob** [comment]
Does the theme work for you now?

**Comment by EpicLPer** [comment]
After double-clicking I can choose different screens on the left, yes.

**Comment by govorox** [comment]
to fix the issue install the missing modules: 
apt-get install libwww-perl

**Comment by qooob** [comment]
To fix the issue simple update to version 11. It has no dependencies!

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-latest.wbt.gz

**Comment by Rvanlaak** [comment]
Where to extract it? The theme was installed in webmin after the latest update...

**Comment by qooob** [comment]
Don't extract it anywhere. Goto `Webmin->Webmin Configuration->Webmin Themes`, then there in tabs click on `Install Theme` and choose `From ftp or http URL`. Enter the link above and hit enter.

If you want to do it manually. Go to `/usr/libexec/webmin/authentic-theme` and copy all files there. You could delete all files from there first.

**Comment by Rvanlaak** [comment]
That was easy indeed! Would be nice if that could be added to the documentation. 

README.md is getting a bit long, do you mind if I create a `/docs` folder and separate the readme in multiple files?

**Comment by EpicLPer** [comment]
Awesome! Will try once I'm home ;)
Thanks for the fast fix :)

**Comment by qooob** [comment]
Thank you, Richard, but no. I don't think it's necessary. Using `Ctrl+F` in your browser and searching for  `install` is something that almost anybody could do.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme#how-do-i-install-authentic-theme

I made docs for this purpose.

**Comment by Rvanlaak** [comment]
:+1:
