### ISSUE TITLE
No Virtualmin domain dropdown showing?

### ISSUE THREAD

**Issue by Muffinman** [qooob/authentic-theme#141]
Hi,

I have this theme installed and up-to-date on several Virtualmin servers, however on one particular server I only get a search box appearing in the top *left* [correction], instead of the domain list. Perhaps I'm missing a setting somewhere in the theme? Switching back to one of the other themes the domain list appears again.

Server details are:

Operating system	Ubuntu Linux 12.04.4
Webmin version	1.740
Virtualmin version	4.06
Theme version	Authentic Theme 10.2.0
Kernel and CPU	Linux 3.2.0-76-generic-pae on i686

If you need any more info let me know.

**Comment by qooob** [comment]
Please add screenshot!

**Comment by Muffinman** [comment]
Screenshot attached.

![domain-list-missing](https://cloud.githubusercontent.com/assets/1319568/6778755/4af65f00-d14d-11e4-975b-374cbee7afdd.jpg)

**Comment by qooob** [comment]
You have outdate Virtualmin, required 4.15 ;)

**Comment by Muffinman** [comment]
Thanks, I had done an apt update but it seems the webmin apt sources were commented out so it hadn't upgraded.
