### ISSUE TITLE
Custom logo prevents link use

### ISSUE THREAD

**Issue by clawrie** [qooob/authentic-theme#143]
If the left side menu extends the full height of the screen and you have a custom logo in place, you cannot select the links that are displayed directly above the logo.  See images (note mouse pointer).
![authentic-1](https://cloud.githubusercontent.com/assets/9471257/6859570/40d675e4-d46a-11e4-8542-8b40a9b0199b.png)
![authentic2](https://cloud.githubusercontent.com/assets/9471257/6859572/4308c7d6-d46a-11e4-9354-facc37e1ea65.png)

**Comment by qooob** [comment]
Yes but I have just found out a solution a minute ago. It works in Chrome and should work in all other contemporary browsers. I think it's the best shot.

It will be added to the default styles on the next release but so far, add to your custom `styles.css` the following:

```CSS
.__logo {
   pointer-events: none;
}
```

Does it give you the expected result!? ;)

**Comment by clawrie** [comment]
I'll not be able to try this out until Monday - busy weekend - thanks for
the reply.
Craig

**Comment by qooob** [comment]
Alright, let's wait. But let me think it will just work! ;)

Thanks for pointing at the issue!

**Comment by qooob** [comment]
I will put it in 11.01 bug fix release in couple of hours.

**Comment by clawrie** [comment]
Thanks - saw it was fixed earlier today.
