### ISSUE TITLE
DHCP-server module shows no hostnames

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#145]
Hostnames are empty and unclickable if you set  'Display subnets and hosts' as 'icons'

**Comment by qooob** [comment]
Be kind adding screenshot.

**Comment by badfiles** [comment]
![screenshot from 2015-03-28 13 31 25](https://cloud.githubusercontent.com/assets/1597304/6880669/d5b9e3e6-d54e-11e4-973f-bd82c221f50a.png)

**Comment by qooob** [comment]
Is it alright if you set it table view (list)?

**Comment by badfiles** [comment]
'List' works perfect.

**Comment by qooob** [comment]
I think, I know why it's happening. Will see what I can do by the next release.

**Comment by qooob** [comment]
Will be fixed it Version 11.01 in an hour or so. Thanks for reporting!
