### ISSUE TITLE
Webmin Servers Index

### ISSUE THREAD

**Issue by ai-hosting** [qooob/authentic-theme#147]
When using Webmin Servers Index to navigate to other servers the link for virtualmin is not working. The url is linking to the main server and not to the remote server.

**Comment by qooob** [comment]
Could you please attatch a screenshot to make it more clear?

**Comment by ai-hosting** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/11756720/6946349/fae18026-d89f-11e4-90af-787542a9b8a1.png)
![screenshot2](https://cloud.githubusercontent.com/assets/11756720/6946351/fde99c54-d89f-11e4-9665-3052df55c634.png)

The first screenshot is taken after clicking one of the server links in Webmin Server Index so far so good (https://domain.tld/servers/link.cgi/123456789). In the Webmin tab everything is working. Url still
contains the 123456789 referring to the corresponding server. When clicking the Virtualmin tab 123456789 disappears and loading halts. In my case because the server used to connect to the remote server doesn't have virtualmin. The remote server does have virtualmin installed only the url reffering to the remote server is gone.

**Comment by ai-hosting** [comment]
![screenshot3](https://cloud.githubusercontent.com/assets/11756720/6946699/7a686c04-d8a2-11e4-887e-b98ba4a4fe0c.png)

**Comment by qooob** [comment]
Does it happen with `Link type` _Login via Webmin with username_? What should be happening as you think? Because I opened Virtualmin Framed Theme and I came across the same behavior as in my theme. What happens if you go to Module Config and set `Show servers as: Table`?

> When clicking the Virtualmin tab 123456789 
Not sure how to get there? Could you please explain?

**Comment by ai-hosting** [comment]
To test you need to login in Webmin at server 1 and connect to server 2 with webmin module servers index. As soon you use virtualmin the theme loads the virtualmin module at server 1 instead of server 2.

123456789 is an example. In my case (screenshot) the number is 1357987894. This number is reffering to cloud1 in my case. The number is generated by webmin servers index.

**Comment by ai-hosting** [comment]
this only happens in authentic-theme. Gray frame, caldera, bootstrap 3, MSC themes tested without any issues.

**Comment by qooob** [comment]
I will test it a bit later and let you know what I got.

**Comment by sagosS** [comment]
![2015-04-05 22-46-05](https://cloud.githubusercontent.com/assets/11809744/6998395/b56d8398-dbea-11e4-9ab1-388f1c357b76.png)
![2015-04-05 22-46-32 2](https://cloud.githubusercontent.com/assets/11809744/6998396/b56dfb98-dbea-11e4-8c74-784e14e9ff90.png)
![2015-04-05 22-47-22](https://cloud.githubusercontent.com/assets/11809744/6998394/b56c6f62-dbea-11e4-9a2b-ea90c7f46a6e.png)
![2015-04-05 22-48-38](https://cloud.githubusercontent.com/assets/11809744/6998397/b56e057a-dbea-11e4-9eee-2be110efa885.png)
![2015-04-05 22-50-11 2](https://cloud.githubusercontent.com/assets/11809744/6998393/b56c679c-dbea-11e4-81d7-1a9877658412.png)

**Comment by qooob** [comment]
@sagosS Вам нужно обязательно оформить New Issue, нельзя соединять темы так. Просто удалите все фото отсюда и оформить новую проблему, отдельно.

**Comment by qooob** [comment]
It will be fixed in version 11.10 shortly. Thanks for reporting!
