### ISSUE TITLE
Usermin: Mail Sub-Folders

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#148]
First off, great job adding better support in Usermin for email.

I've noticed for a while now that "sub-folders" done get listed in your folder view at the top left corner when viewing from the "Mail" tab.

The only way to access the sub-folders at the moment is to either click on "View Folders" in the bottom part of the menu then clicking "View" next to the folder, or using the dropdown list inside the Inbox window (right side) and navigating to the sub-folder.

Just thought I'd let you know :-)

-Peter

**Comment by qooob** [comment]
Thanks, Peter for reporting. I'm aware of it. Making left menu multi-nested requires a lot of time. I will do it one day but just not right now.
