### ISSUE TITLE
FreeBSD 10.1

### ISSUE THREAD

**Issue by jwhulette** [qooob/authentic-theme#149]
When selecting the theme I get Error - Missing Content-Type Header after the page refreshes

**Comment by qooob** [comment]
Just refresh the page using F5. It just should work.

**Comment by jwhulette** [comment]
I have tried that several times. Did now work. If I use the url in another web browser, I get the default login theme, but as soon as I log in same error.

**Comment by qooob** [comment]
Restart Webmin and set the theme globally in Webmin Configuration.

**Comment by jwhulette** [comment]
Ok, i'm using a VM so it's easy to test. I reinstalled the os, installed webmin, changed the theme and it works. I installed the LWP::https module then ran the update to 11.01 from the link and then it gives the same error.

**Comment by qooob** [comment]
How did you install the theme? What folder it's in? Version 11.00 works and 11.01 not? Only System Information page doest work or everything else?

**Comment by jwhulette** [comment]
Fresh install of webmin, theme works fine, use link on system info page to update, after installing entire page turns white with Error - Missing Content-Type Header. No sidebar or anything. Tried refreshing multiple times. does not work.

**Comment by qooob** [comment]
Add screenshot please!

**Comment by jwhulette** [comment]
![webmin_1_740_on_freebsd__freebsd_10_1_](https://cloud.githubusercontent.com/assets/4930051/6984291/49a56e1a-d9f5-11e4-977f-a91134a38379.png)

**Comment by qooob** [comment]
What is your Webmin version?

**Comment by jwhulette** [comment]
Webmin version	1.740

**Comment by qooob** [comment]
Try downloading the theme manually from GitHub and unpacking it to `/usr/libexec/webmin/authentic-theme`

**Comment by qooob** [comment]
...and make sure that in settings, you have language set as UTF-8.

**Comment by jwhulette** [comment]
Language set to UTF-8, and tried manual upload, same error.

**Comment by qooob** [comment]
What happens if you pass to URL /index.cgi.

**Comment by jwhulette** [comment]
Same error

**Comment by qooob** [comment]
Do you use proxy?

**Comment by jwhulette** [comment]
No, using VirtualBox VM on local machine.

**Comment by qooob** [comment]
...and it doest happen with the theme that is in Webmin package? Only after update?

**Comment by jwhulette** [comment]
Fresh install of FreeBSD 10.1, installed webmin from packages. Works.
![webmin_1_740_on_freebsd__freebsd_10_1_](https://cloud.githubusercontent.com/assets/4930051/6984996/783f5c5c-d9fc-11e4-9275-7e07791e5675.png)
As soon as I update to latest version same error.
This is in the error log:
restarting miniserv
[02/Apr/2015:20:58:23 -0400] Restarting
Pre-loaded WebminCore
[02/Apr/2015:20:58:23 -0400] miniserv.pl started
[02/Apr/2015:20:58:23 -0400] Using MD5 module Digest::MD5
[02/Apr/2015:20:58:23 -0400] PAM authentication enabled
Subroutine setup_ca redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 77.
Subroutine install_webmin_module redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 127.
Subroutine grant_user_module redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 439.
Subroutine delete_webmin_module redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 480.
Subroutine file_basename redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 589.
Subroutine gnupg_setup redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 603.
Subroutine list_standard_modules redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 631.
Subroutine standard_chooser_button redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 663.
Subroutine list_third_modules redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 676.
Subroutine third_chooser_button redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 708.
Subroutine get_webmin_base_version redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 719.
Subroutine base_version redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 729.
Subroutine get_newmodule_users redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 740.
Subroutine save_newmodule_users redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 762.
Subroutine get_miniserv_sockets redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 786.
Subroutine fetch_updates redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 834.
Subroutine check_update_signature redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 901.
Subroutine find_cron_job redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 932.
Subroutine get_ipkeys redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 944.
Subroutine save_ipkeys redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 965.
Subroutine validate_key_cert redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 997.
Subroutine detect_operating_system redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1018.
Subroutine show_webmin_notifications redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1053.
Subroutine get_webmin_notifications redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1069.
Subroutine get_system_uptime redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1271.
Subroutine list_operating_systems redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1318.
Subroutine shared_root_directory redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1343.
Subroutine submit_os_info redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1380.
Subroutine get_webmin_id redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1408.
Subroutine ip_match redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1424.
Subroutine prefix_to_mask redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1519.
Subroutine valid_allow redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1533.
Subroutine get_preloads redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1598.
Subroutine save_preloads redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1610.
Subroutine get_tempdirs redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1621.
Subroutine save_tempdirs redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1638.
Subroutine get_module_install_type redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1657.
Subroutine get_install_type redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1674.
Subroutine list_cached_files redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1704.
Subroutine show_restart_page redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1723.
Subroutine cert_info redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1741.
Subroutine cert_pem_data redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1782.
Subroutine cert_pkcs12_data redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1797.
Subroutine get_blocked_users_hosts redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1823.
Subroutine show_ssl_key_form redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1851.
Subroutine parse_ssl_key_form redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1895.
Subroutine parse_ssl_csr_form redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 1968.
Subroutine build_installed_modules redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2042.
Subroutine get_latest_webmin_version redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2084.
Subroutine filter_updates redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2117.
Subroutine get_clone_source redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2159.
Subroutine retry_http_download redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2175.
Subroutine list_twofactor_providers redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2206.
Subroutine show_twofactor_apikey_authy redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2216.
Subroutine validate_twofactor_apikey_authy redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2228.
Subroutine show_twofactor_form_authy redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2253.
Subroutine parse_twofactor_form_authy redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2269.
Subroutine enroll_twofactor_authy redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2284.
Subroutine validate_twofactor_authy redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2315.
Subroutine validate_twofactor_apikey_totp redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2361.
Subroutine show_twofactor_form_totp redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2375.
Subroutine parse_twofactor_form_totp redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2389.
Subroutine generate_base32_secret redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2405.
Subroutine enroll_twofactor_totp redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2419.
Subroutine message_twofactor_totp redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2428.
Subroutine validate_twofactor_totp redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2442.
Subroutine canonicalize_ip6 redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2464.
Subroutine list_visible_themes redefined at /usr/local/lib/webmin/webmin/webmin-lib.pl line 2491.
Subroutine list_keys redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 23.
Subroutine list_keys_sorted redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 74.
Subroutine list_secret_keys redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 82.
Subroutine key_fingerprint redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 88.
Subroutine get_passphrase redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 105.
Subroutine put_passphrase redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 116.
Subroutine encrypt_data redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 128.
Subroutine decrypt_data redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 167.
Subroutine sign_data redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 224.
Subroutine verify_data redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 283.
Subroutine read_entire_file redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 327.
Subroutine write_entire_file redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 339.
Subroutine get_trust_level redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 349.
Subroutine delete_key redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 371.
Subroutine default_email_address redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 398.
Subroutine fetch_gpg_key redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 415.
Subroutine search_gpg_keys redefined at /usr/local/lib/webmin/webmin/gnupg-lib.pl line 442.
[02/Apr/2015:20:58:48 -0400] [10.50.8.16] /sysinfo.cgi : Missing Content-Type Header

**Comment by qooob** [comment]
That doesn't make sense. Can you manually unzip new version to the folder?

**Comment by jwhulette** [comment]
![webmin_1_740_on_freebsd__freebsd_10_1_](https://cloud.githubusercontent.com/assets/4930051/6985293/d8852c10-d9ff-11e4-9e5c-24fa7903d517.png)
same issue.

**Comment by qooob** [comment]
Try deleting update file?

**Comment by jwhulette** [comment]
Ok.. oddly enough, I have the left rail. So I can get to different modules, they seem ok. The only place I get the error is clicking System Information.

**Comment by qooob** [comment]
You mean after automatically updating?

**Comment by qooob** [comment]
I think your facing weird Webmin's cache problem. I don't thinkg there is an error in the theme somewhrere. Try going to Webmin,Webmin Configuration, Webmin Scheduled Functions and check and run all of them.. Does System Information page starts working?

**Comment by jwhulette** [comment]
I can keep the left rail with the modules if I install but using Webmin Configuration > Install Theme. I tried running all the scheduled functions and no change. I refreshed the entire page and the error came back.

**Comment by jwhulette** [comment]
It's failing on sysinfo.cgi

**Comment by qooob** [comment]
What if you use sysinfon from version 11.00?

**Comment by jwhulette** [comment]
When I upload the theme authentic-theme-latest.wbt.gz using the upload theme in webmin the directory /usr/local/etc/webmin/authentic-theme only has one file, config is that normal?

**Comment by qooob** [comment]
Yes, that is OK.

**Comment by jwhulette** [comment]
Should I just upload the sysinfo from 11.00 into that folder?

**Comment by qooob** [comment]
It should be usually /usr/libexec/webmin/authentic-theme.

**Comment by qooob** [comment]
...or whereever Webmin dir is.

**Comment by qooob** [comment]
Try `where is webmin`. Where is it in your case?

**Comment by qooob** [comment]
`whereis webmin`

**Comment by jwhulette** [comment]
Ok, tried copying just sysinfo into folder (usr/local/lib/webmin/authentic-theme), no good, copied all files from 11.00 no good, tried copying all files from 10.1.2 and no good. I restarted webmin after each copy.

**Comment by qooob** [comment]
What was the output of the command above?

**Comment by jwhulette** [comment]
whereis output: /usr/ports/sysutils/webmin

I enabled debugging, then switched the theme here is the last couple of lines from the file:
1309 [02/Apr/2015 21:20:30.552314] npmg 10.50.8.16 - UNLINK "/usr/local/etc/webmin/miniserv.conf.webmintmp.1309"
1309 [02/Apr/2015 21:20:30.552668] npmg 10.50.8.16 - UNLINK "/usr/local/etc/webmin/miniserv.users.webmintmp.1309"
1309 [02/Apr/2015 21:20:30.552788] npmg 10.50.8.16 - UNLINK "/usr/local/etc/webmin/webmin.acl.webmintmp.1309"
1309 [02/Apr/2015 21:20:30.552898] npmg 10.50.8.16 - UNLINK "/usr/local/etc/webmin/config.webmintmp.1309"
1309 [02/Apr/2015 21:20:30.553006] npmg 10.50.8.16 - STOP "runtime=1"

**Comment by qooob** [comment]
I would think that authentic-theme should be in /usr/ports/sysutils/webmin, right?

**Comment by qooob** [comment]
OK, here is the test. What happens if you install the theme from this link?

https://rostovtsev.ru/pub/src/authentic/11.01/authentic-theme-latest.wbt.gz

Everything works fine?

**Comment by jwhulette** [comment]
Sorry for the late response. The link above has the same issue. Error - Missing Content-Type Header

**Comment by qooob** [comment]
Alright, good then!! The link above had absolutely the same package that is in Webmin right. **It seems, that Webmin is not installing the theme correctly on your system**  We just discovered Webmin bug. Please report it to https://github.com/webmin/webmin.

**Comment by qooob** [comment]
Alright, I have an idea for you! Can you open `sysinfo.cgi` and remove any kind of `#!/usr/bin/perl` at the top of the document (first line). Does it help? Probably doing the same for other `.cgi` could fix the issue?

**Comment by jwhulette** [comment]
I tried that but it still didn't work. The odd thing is if I have a fresh install with version 10 of the them, and I export the theme, then delete it, then reimport it I have the same issue.

**Comment by qooob** [comment]
Try checking permissions that are set on the files in the theme by running `ls -lsa` in that folder?

**Comment by jwhulette** [comment]
That was the issue. I changed all the files to 755.

**Comment by qooob** [comment]
Alright! I will also do it in my theme.

**Comment by qooob** [comment]
By the way, which files did you change permissions on? .pl or .cgi?

**Comment by jwhulette** [comment]
I did it on all the files in the directory. I match the permissions from the webmin directory.

**Comment by qooob** [comment]
It was 755 on all files? Even .js?

**Comment by jwhulette** [comment]
Yes, every file and folder in the directory /authenic-theme directory

**Comment by qooob** [comment]
OK, I see.
