### ISSUE TITLE
Проблема с отображением станицы редактирования полей баз данных.

### ISSUE THREAD

**Issue by sagosS** [qooob/authentic-theme#150]
![2015-04-05 22-46-05](https://cloud.githubusercontent.com/assets/11809744/7004019/931b8bae-dc6d-11e4-96bf-595cf1c6fbc2.png)
![2015-04-05 22-46-32 2](https://cloud.githubusercontent.com/assets/11809744/7004020/931c7bd6-dc6d-11e4-8e2a-35fb92b090bc.png)
![2015-04-05 22-47-22](https://cloud.githubusercontent.com/assets/11809744/7004023/931f3b1e-dc6d-11e4-8703-7d55bbb0348f.png)
![2015-04-05 22-48-38](https://cloud.githubusercontent.com/assets/11809744/7004022/931e26c0-dc6d-11e4-8f73-cb325241aaa0.png)
![2015-04-05 22-50-11 2](https://cloud.githubusercontent.com/assets/11809744/7004021/931cfe62-dc6d-11e4-933d-85f4a9f7a5f2.png)

**Comment by qooob** [comment]
Подтвержденно! Постараюсь исправить к следующему релизу! Спасибо что сообщили!

**Comment by qooob** [comment]
Будет исправленно в версии 11.10, совсем скоро. Спасибо что сообщили!
