### ISSUE TITLE
Просьба, реализовать кнопку перезагрузки сервера на главной странице

### ISSUE THREAD

**Issue by sagosS** [qooob/authentic-theme#151]

**Comment by qooob** [comment]
В меню слева? Её можно включить через настройки!

**Comment by qooob** [comment]
.. не понял.. Кнопку перезагрузки? :) в смысле выполнение команды `/sbin/reboot`?

**Comment by sagosS** [comment]
Да

**Comment by qooob** [comment]
В будущей версии попробую сделать програмируемые кнопки.

**Comment by qooob** [comment]
Проблема в том, что это не будет работать, вот прям так как вы хотели бы - нажал и все и комманда `/usr/sbin/reboot` выполненна.. :) Так можно теоритически сделать, но только посредством использования JavaScript.. Это не совсем то, следуют делать.

И на мой взгляд это не очень удачная идея и ее явно не поддержат многие. В будущем, я сделаю програмируемые кнопки, опционально.
