### ISSUE TITLE
Login screen lacks link to Virtualmin Password Recovery

### ISSUE THREAD

**Issue by h9k** [qooob/authentic-theme#152]
Virtualmin Password Recovery allows users to reset or recover their password if they forgot it.
This feature is optional, but if activated, it shows up a link on the login screen.
However, if using Authentic as default theme, the link does not show.
The URL is something like https://foo.bar:10000/virtualmin-password-recovery/
Would be nice if Authentic could support that :)

**Comment by qooob** [comment]
Hmmm.. I will try adding it to the version 12. But you would have to wait for some time! I'm covered in some other work from head to toes! ;)

**Comment by qooob** [comment]
Could you please add a screenshot of how it looks in default theme? By the way, you said it's optional? Does this feature automatically activated when module `virtualmin-password-recovery` is installed or it was to be enabled somewhere?

**Comment by qooob** [comment]
Alright, figured this out. It will be added to version 11.10 shortly.

**Comment by h9k** [comment]
Sorry for not getting back to you sooner, but glad you figured it out already :)
