### ISSUE TITLE
Unable to use Webmin after installing

### ISSUE THREAD

**Issue by RaddishIoW** [qooob/authentic-theme#153]
I am unable to use Webmin after installing this theme as it repeatedly gives the error:
Can't locate LWP/Simple.pm in @INC (@INC contains: /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/ ..) at /usr/libexec/webmin/authentic-theme/sysinfo.cgi line 196.
BEGIN failed--compilation aborted at /usr/libexec/webmin/authentic-theme/sysinfo.cgi line 196.
and refuses to load any other interface items.

I've installed LWP::Simple, and all other Perl dependencies listed, but it still doesn't work.

Can you please advise on how to fix this?

**Comment by qooob** [comment]
Easily! Its all in README.MD or simply update to the latest version (11.01) which has no dependences. Don't forget to restart Webmin.

**Comment by qooob** [comment]
It's actually in the old README.md, see couple of diffs before the actual one. If you update to the latest, it will just work out of the box.

**Comment by RaddishIoW** [comment]
Thank you so much for the quick reply.
I fixed it in the end by manually switching the theme (in the web min config files) and then using the "Recommended Modules" in the Perl Modules in Webmin to install the last dependancy I was missing.
Works a treat now.
Thanks!

**Comment by qooob** [comment]
You are welcome! :)
