### ISSUE TITLE
Некорректные права на .cgi в теме

### ISSUE THREAD

**Issue by AjaxOdessa** [qooob/authentic-theme#154]
После установки темы посредством заливки через веб-интерфейс, на файлах .cgi не установлен бит исполняемости, из-за этого постоянно вылазила ошибка "Content Header". Хорошо что нашел Issue 149, он натолкнул на мысль покопаться в правах файлов.

**Comment by qooob** [comment]
OK, исправлю.

**Comment by qooob** [comment]
Будет испрвленно в версии 11.10, совсем скоро! Спасибо что сообщили! ;)
