### ISSUE TITLE
Images provided by modules are not loaded.

### ISSUE THREAD

**Issue by Real-Gecko** [qooob/authentic-theme#155]
After page loaded every image src is changed to absolute path from relative, so if any image is provided by the module it is not loaded.
For example src for "images/icons/home.png" changed to "/images/icons/home.png".
I can see images during page load, but then they disappear because src for every image is changed.
If I manually edit image src with firebug then image is showed correctly.
You can check this by enabling http://labs.libre-entreprise.org/projects/wbmtranslator/ and going to module page.

**Comment by qooob** [comment]
Alright, confirmed and will be fixed in version 11.10 very soon.

**Comment by Real-Gecko** [comment]
Can you please add "filemin" to your exclusion list? :)
https://github.com/Real-Gecko/filemin

**Comment by qooob** [comment]
To my exclusion list? :)) You want me _not to look at it_? `Exclusion` meaing is to `exclude`? 

Can you please post screenshots in your repo?

**Comment by Real-Gecko** [comment]
As far as I can see there is a function in unauthenticated/js/default.min.js

`$('img[src^="images"]').each(function(b,a){if($current_page!="sysstats/"&&$current_page!="translator/"){$(a).attr("src",""+$webprefix+"/"+$(this).attr("src"))}})`

Can filemin be added like this `&&$current_page!="filemin/"` too?

**Comment by qooob** [comment]
Ahh that! :)) I just commented here, let's move tho this thread. Post your previous answer here:

https://github.com/qooob/authentic-theme/issues/164#issuecomment-98584896
