### ISSUE TITLE
Хотелось бы увидеть кнопку перезагрузки контента на странице...

### ISSUE THREAD

**Issue by sagosS** [qooob/authentic-theme#156]
![2015-04-13 18-24-41](https://cloud.githubusercontent.com/assets/11809744/7118901/c8cb92ec-e20a-11e4-92cd-575a1fb09b6c.png)

**Comment by qooob** [comment]
А эта кнопка есть в левом меню снизу? Не удобно?

**Comment by sagosS** [comment]
Кнопкой, отвечает ошибкой.

**Comment by qooob** [comment]
Простите, что вы имеете ввиду? Вы закрыли вопрос? Все заработало?

**Comment by qooob** [comment]
А теперь понятно.. Хмм. Гляну..

**Comment by qooob** [comment]
Будет исправленно в версии 11.10 совсем скоро! Спасибо, что нашли баг!
