### ISSUE TITLE
Strange UI in Filemanager

### ISSUE THREAD

**Issue by simbus82** [qooob/authentic-theme#159]
Thanks for this great theme!
But i see some problems in the webmin file manager. With this templates icons are "ugly". I know filemanager is a Java App, maybe is an OS dependant problem?

![filemanager-ui](https://cloud.githubusercontent.com/assets/1375730/7142546/ace11a96-e2d9-11e4-8f99-94c8df990764.PNG)

**Comment by qooob** [comment]
Just try to unpack to `authentic-theme` directory (/usr/libexec/webmin/authentic-theme) the following pack of images that are used in Virtualmin Framed Theme. It might work.

https://rostovtsev.ru/pub/src/authentic/file.zip

Restart Webmin, and most importantly clear browser's cache.

**Comment by simbus82** [comment]
Thank! It works! Another little UI problem is in the upload window in the File Manager, a probem with radio button misaligned.

**Comment by qooob** [comment]
Add screenshot please

**Comment by simbus82** [comment]
Ops sorry!
![upload-uthentic-theme](https://cloud.githubusercontent.com/assets/1375730/7177188/e366bc82-e424-11e4-910f-4c59aa5c0248.PNG)

**Comment by qooob** [comment]
Will take a look. Thanks.

**Comment by qooob** [comment]
It's fixed in Version 11.50. Please update!
