### ISSUE TITLE
VNC window in flash mode too small.

### ISSUE THREAD

**Issue by ddemuro** [qooob/authentic-theme#161]
The window height is like 120 px wide. Making it 900px or something similar like the original theme should make it more comfortable.

**Comment by qooob** [comment]
Can you please add the screenshot?

**Comment by qooob** [comment]
Can you please add the screenshot?

**Comment by qooob** [comment]
How do I install it to check?

**Comment by qooob** [comment]
This module was updated 8 years ago? What is the point. In case you can debug it for me, I will make a patch for you. Otherwise you're on your own here. The theme is extensible with CSS/JS and such things can be injected with custom scripting. Keep posting here, in case you have further questions.

**Comment by ddemuro** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4421555/7449026/600f04b2-f201-11e4-884b-49c544998074.png)

Sorry for the late Reply!, the theme is awesome. I haven't tried to patch it yet, I was more like in reporting in a rush.
Sorry for that, whenever I get a minute i'll check it.

Normally fixed if you select the <p></p> that contains the flash object, and you set the height to something like 900px / 520px.

That way you avoid scrolling up/down.

Again thank you for the awesome theme.

**Comment by qooob** [comment]
Do you say that all is fine or you would want to make it load different by default? Can you use `ChromeDev Tool` and send what you got there, when you hover on this object? Try clicking `Ctrl+Shift+C` and then hover on that window and post a screenshot of the content, in case you need more help here.
