### ISSUE TITLE
multiple charset

### ISSUE THREAD

**Issue by Albirew** [qooob/authentic-theme#162]
There is multiple charset  in theme (FR.UTF-8).
See screens to get what I mean.
browser charset in UTF-8:
![charset in UTF-8](https://cloud.githubusercontent.com/assets/2805161/7319889/3e3683d4-ea99-11e4-963d-5f834c1a6a57.png)
and browser charset in ISO-8859-1:
![charset in ISO-8859-1](https://cloud.githubusercontent.com/assets/2805161/7319953/a96036aa-ea99-11e4-969a-549c2defa2da.png)

**Comment by qooob** [comment]
You can force it to UTF-8 in Webmin configuration, Language settings, right?

**Comment by Albirew** [comment]
It is already forced to FR.UTF-8 but the problem right here is that there is 2 different charset mixed in the same page

**Comment by qooob** [comment]
Go to browser settings and make sure that you have UTF-8 encoding set and not auto-detect.

**Comment by Albirew** [comment]
aw... looks like my problem was corrupted cache since I don't see double charset anymore...

Sorry for the time taken for almost nothing...

**Comment by qooob** [comment]
I'm glad to hear that it was solved!

**Comment by 7starsone** [comment]
pardon, Ilia... I don't see the language quick switch button anymore, why?

**Comment by qooob** [comment]
It's just off by default, as very few people need this on every day basis. You can enable this using settings. ;)

**Comment by 7starsone** [comment]
where? thanks

**Comment by qooob** [comment]
Please be kind reading README.md, I put a lot of stuff there, after each update. ;)

```JavaScript
// Show/hide left menu's language button/link
settings_leftmenu_button_language = false;
```
