### ISSUE TITLE
Unused modules

### ISSUE THREAD

**Issue by tbnv** [qooob/authentic-theme#167]
Hi,

Why do you use #888888 for the "Unused modules" label in the sidebar? Looks like an inactive element even if it is actually active. And I think it doesn't go well with the other sections labels, especially because the icon remains in the same color as the other sections icons.

Icon + label should be both in #888888 or in #c0cbde but not mixed. And again, I wouldn't see a reason to make it look like inactive, even if it's for *unused* modules.

**Comment by qooob** [comment]
Thanks, good point!! It stayed there since the very beginning. I will make it the same color, since you can completely hide it using settings.
