### ISSUE TITLE
Missing images when Webmin is under a subdirectory

### ISSUE THREAD

**Issue by 1rover1** [qooob/authentic-theme#168]
To replicate, 

1. Set up Webmin under a subdirectory e.g. http://localhost/administrationpage.
2. Log in, navigate to Webmin -> Webmin Configuration
3. GIFs for configuration items are 404

I've fixed this by

1. Editing authentic.pl
2. Add "        $__icon = $gconfig{'webprefix'} . $__icon;" to line 474

I'd submit as a pull request but I'm n00b.

**Comment by qooob** [comment]
Yes, I already noticed this bug and fixed it days ago. It will all be fixed in epic version 13.00 very soon!
