### ISSUE TITLE
Drive temperatures in sysinfo not correct

### ISSUE THREAD

**Issue by chandlben** [qooob/authentic-theme#171]
With smartmontools installed on the system, disk temperatures are reported in System Information, as well as any errors a drive may have.

```
sda: 31°C
sdb: 30°C
sdc: 30°C
(100 errors!)sdd: 30°C
sde: 29°C
```

This is the output for one of my servers and the problem here is 'sdc' is actually the drive with 100 errors, not 'sdd' which is what you would think based on the output. SMART Drive Status verifies this. I also have a server with 11 drives and the output with every drive on a new line is very long.

Is there a way we can correct the problem with the errors as well as clean up the output with a table or something of the sort, to use more of the horizontal space in System Information rather than vertically down the page?

**Comment by qooob** [comment]
What output do you get in Webmin, old Theme?

I could make it displayed in a line, this makes sense! For many drives!

Are you saying that errors are shown in a row for the other drive?

**Comment by qooob** [comment]
I understood what you mean and want! I will do and fix it in next relaese version 13 very soon and make it optional to make drives list in a line! Thanks!

P.S. Any idea what do I need to do make it show in CentOS? In Fedora it's shown alright?

**Comment by chandlben** [comment]
It appears output in other themes shows in a single line exactly like this,

`sda: 30℃ sdb: 30℃ sdc: 29℃ (100 errors!) sdd: 30℃ sde: 28℃`

What would be nice is if there was someway to put the items in a table with equal spacing for neatness:

`sda: 30°C (1 error) | sdb: 30°C (1 error) | sdc: 30°C (1 error)`
`sdd: 30°C (1 error) | sde: 30°C (1 error) | sdf: 30°C (1 error)`
`sdg: 30°C (1 error) | sdh: 30°C (1 error) | sdi: 30°C (1 error)`
`sdj: 30°C (1 error) | sdk: 30°C (1 error) | and so on...`

I have tried playing with this myself to no success. But a clean line would be alright as well.

On every update for your theme, I usually just overwrite the section of code in sysinfo.cgi which deals with the drives to make it appear like this:

| sda: 45°C || sdb: 44°C (10 errors!) || sdc: 42°C || sdd: 47°C || sde: 42°C |
| sdf: 45°C (6 errors!) || sdg: 47°C (6 errors!) || sdh: 46°C (2 errors!) || sdi: 43°C (2 errors!) || sdj: 44°C |
| sdk: 44°C |

I can give you the code I used to do that but it's really just a horrible hack because I have so many drives.

P.S. That is strange that it shows alright in Fedora. I am running Ubuntu Server on all of my machines and they all show exactly how I described in the Authentic Theme.

**Comment by qooob** [comment]
I already fixed it and I hope you are gonna like it! Please write it back after you get version 13 installed.

No, they are displayed all the same in version 12 - it doesn't matter if it's Fedora or CentOS.

What I meant that I have `smartmontools` installed both on Fedora and CentOS but Drive Temperatures are only exist in Fedora.
