### ISSUE TITLE
Broken link on left top "Webmin" image

### ISSUE THREAD

**Issue by TrakerBG** [qooob/authentic-theme#172]
When I click on the "Webmin" icon (above the Search field, the most upper left icon), the link is doubled. For example, if Webmin works on 
http://192.168.1.129:10000/
the link points to
http://192.168.1.129:10000/192.168.1.129:10000/

**Comment by qooob** [comment]
Will be fixed in minutes in 13.01. Please check!

**Comment by TrakerBG** [comment]
Fixed, works as expected. Thank you!
