### ISSUE TITLE
Unusable in Safari after upgrade to 13.00

### ISSUE THREAD

**Issue by kierandelaney** [qooob/authentic-theme#173]
When you log into Webmin after the upgrade to 13.00, Safari on Mac immediately reloads the page and then jumps back two places in the history.

Client:
OS X 10.10
Safari 8.0.6

Server:
RHEL 6
Webmin 1.750
Authentic Theme 13.00

We've tested Chrome on the mac and that works fine. We've tested with a new install of OS X and safari to rule out any caching issues.

**Comment by qooob** [comment]
You mean it's login screen again?

**Comment by kierandelaney** [comment]
It actually jumps back to *before* the login screen. So the new tab screen or the site you were browsing before you went to the web min address.

**Comment by qooob** [comment]
Ok, understood. Let me. I will make a fix as soon as possible.

**Comment by qooob** [comment]
Will release an update in 10 minutes. Please take a look! Thanks for reporting! Sorry about that!
