### ISSUE TITLE
Cant navigate within Webmin Servers

### ISSUE THREAD

**Issue by ignaworn** [qooob/authentic-theme#178]
Hi, 
After the last update (13.00 and 13.02) I could not navigate to other webmin servers. I use "Login via Webmin" method..

![image](https://cloud.githubusercontent.com/assets/6243125/7875232/9d7eb3c2-0590-11e5-9da2-b6d2b8edc66e.png)

So... I connect from my main server to another server and I get doubled sidebars
![image](https://cloud.githubusercontent.com/assets/6243125/7875158/bde95a1e-058f-11e5-8591-58c57b9bd770.png)

If I press anything from the side pannel it sends me back to the main server information page
![image](https://cloud.githubusercontent.com/assets/6243125/7875183/ff1f2fcc-058f-11e5-9e73-bd0dad90308d.png)

Thanks

**Comment by qooob** [comment]
I got it! Will fix it in 13.03 very soon. After update please report here if it's working or not! Thanks for reporting!
