### ISSUE TITLE
Where's this option?

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#179]
Hello Ilia ;-)
pardon, when I enter Virtualmin the first time, the opened tab on the bottom is "New Virtualmin Features".
How to choose another opened tab? eg. Status....

thanks

**Comment by qooob** [comment]
In options you can open all tabs but not specific

**Comment by qooob** [comment]
I mean you can set to expand all

**Comment by 7starsone** [comment]
"Make all accordions expanded" ? if so, is already on yes... but only "New Virtualmin Features" is opened...

**Comment by qooob** [comment]
Do you read change logs? :) goto `Webmin->Webmin Configuration->Webmin Themes`

**Comment by qooob** [comment]
Oh you mean it doesn't work?

**Comment by 7starsone** [comment]
indeed, it doesn't work...

**Comment by qooob** [comment]
Hmm.OK, pal! Will take a look as get back to PC. What happens if you click hide new features button?

**Comment by 7starsone** [comment]
if i click that, nothing is opened :-D
![Image of tabsclosed](http://i61.tinypic.com/a5c39.jpg)

**Comment by qooob** [comment]
Do you click on the text? I'm confused. All is opening in my case. What browser are you using?

**Comment by 7starsone** [comment]
I clicked the hide new features button... "Make all accordions expanded" is already set on ***Yes*** in Authentic options... so it doesn't work. 
I'm forced to click on a tab to expand it...
Chrome or Firefox do the same thing...

**Comment by qooob** [comment]
There is one error that I just  fixed - but it didn't break functionality...

Ok, I think I know what you mean. Just if you goto theme options and click save button - it will work for you after that, right? There was in error in default settings. Just fixed it.

**Comment by 7starsone** [comment]
right... on 13.02 it works only if you Save settings...

**Comment by qooob** [comment]
OK. I will fix it! Why didn't you just say that right away.. :)

**Comment by qooob** [comment]
Thanks!

**Comment by 7starsone** [comment]
:-D 'cause i didn't try before, really... thank you
