### ISSUE TITLE
Generate icon's titles

### ISSUE THREAD

**Issue by specktator** [qooob/authentic-theme#180]
Initially found it under "Webmin servers Index" section. I couldn't select virtualmin/webmin server to delete or to do any other action by check boxes while check boxes are missing.

Note: You can always change from module display options from "icons" to "table" in order to see and/or manipulate modules items, in my case servers.

![screenshot from 2015-05-30 16 58 23](https://cloud.githubusercontent.com/assets/3157413/7897705/50a8b688-06ee-11e5-8fef-3253acb7c198.png)

**Comment by qooob** [comment]
Yes, thank you for reporting! I will an add extensive support for such data-structures very soon in version 13.03
