### ISSUE TITLE
Cannot add custom logo

### ISSUE THREAD

**Issue by ArcanumSK** [qooob/authentic-theme#181]
Options in "Theme logos" #116 are greyed out. I can select yes for both options but nothing else (save will return it to no and nothing happens.

**Comment by qooob** [comment]
Select yes, then you are able to click on a file attach button (clip), select a file and click save.

**Comment by qooob** [comment]
Uupss.. That was working last release! Sorry will fix it soon.

**Comment by jamieisboss** [comment]
A bit more detail, removing the classes disabling the buttons lets me access the filepicker and choose my logo but when I click save i get an error

      Failed to open /etc/webmin/authentic-theme/logo.png for writing : Permission denied

i tried the old-school way of copying the logo into that directory and it seems to get removed when i navigate anywhere inside webmin.

Hope this helps

**Comment by qooob** [comment]
What is output of `ls -lsa /etc/webmin/authentic-theme`

**Comment by jamieisboss** [comment]
me@server:/usr/share/webmin/authentic-theme$ ls -lsa /etc/webmin/authentic-theme
    total 16
    4 drwxr-xr-x   2 root root 4096 May 31 06:22 .
    4 drwxr-xr-x 123 root root 4096 May 31 06:06 ..
    4 -rw-r--r--   1 root root  114 May 31 06:06 config
    4 -rw-r--r--   1 root root 1396 May 31 06:22 settings.js

**Comment by qooob** [comment]
what about `ls -lsa /etc/usermin/authentic-theme`

**Comment by jamieisboss** [comment]
I don't have usermin installed sorry

**Comment by jamieisboss** [comment]
To correct myself, i was trying to copy the logo.png manually into /usr/share/webmin/authentic-theme

when i copied it into /etc/webmin/authentic-theme it works as expected the folder structures are identical and i got confused   :dizzy_face:  apologies

**Comment by qooob** [comment]
Actually, you have discovered horrible BUG, that I have just fixed and will release version 13.04, very soon! Thank you!!

**Comment by jamieisboss** [comment]
Any time you need a confused guy, give me a call. :smile: 

Glad i could help, even if it was more of a shotgun than a sniper approach, seriously though, Thanks for all the work you've put into this, you've turned webmin from some dated looking (but wonderful) thing into something i can show clients and have them be impressed. Makes a world of difference.

**Comment by qooob** [comment]
:+1:  So good to hear this! Thanks!! :D

**Comment by jamieisboss** [comment]
Sorry man, just tried this after updating to the newest version

![error](https://cloud.githubusercontent.com/assets/5108847/7923777/106c82ae-08ae-11e5-8bf7-d71cb946996b.jpg)

It works fine up until that point though

**Comment by qooob** [comment]
Just as root first delete `/etc/webmin/authentic-theme/logo.png` and try again. And before that post

`ls -lsa /etc/webmin/authentic-theme/logo.png`

and 

`lsattr /etc/webmin/authentic-theme/logo.png`

**Comment by qooob** [comment]
...and `ls -lsa /etc/webmin/authentic-theme`

**Comment by qooob** [comment]
I have some changes in regards to your issue in up-coming version 13.05. It should work. 

However, in case you will face this issue again, post the output from suggested commands above.. I think you have uploaded logo under some other user or made it immune.
