### ISSUE TITLE
Feature request - more editable Shortcuts

### ISSUE THREAD

**Issue by Sarge2013** [qooob/authentic-theme#183]
Hello !
First of all - thank you for the excellent theme with convenient updates !
Just let me note an issue about latest update where hotkey to System Information page (Ctrl+I) - on Mozilla it calls Bookmarks...why not ALT+I ?

Let me also offer to extend your idea of hotkeys.

Any sysadmin uses a few links from Webmin very often - for example a monitoring or log view, i.e.
http://example.com:10000/syslog/save_log.cgi?oidx=0&omod=proc&view=1
Could you offer a list of available shortcuts - ALT+0...ALT+9, also ALT+A....ALT+Z - where sysadmin just can copy paste the links like above
/syslog/save_log.cgi?oidx=0&omod=proc&view=1
etc...

So any sysdamin can setup a list of his own shortcuts for the modules/pages under Webmin what he uses in an often way. 
IMHO it could be very convenient,

Have a nice day !
Best regards,
Serge

**Comment by qooob** [comment]
Thank you for your idea. However, you can change hotkeys and its modifier using theme settigns.

About the hotkeys 0, 1 .. 9 I will keep this idea in mind.

**Comment by qooob** [comment]
And actually it's Alt+I for System Information by default. It was a typo there!

**Comment by Sarge2013** [comment]
Thank you, Ilya ! :) yes ALT+I works.
And thank you too for "About the hotkeys 0, 1 .. 9 I will keep this idea in mind."
Idea is simple :) just give a ready list of empty shortcuts - so user can assign ALT+7, for example, with /syslog/save_log.cgi?oidx=0&omod=proc&view=1
etc
Have a nice day !

**Comment by qooob** [comment]
MAN!! I have done it and it's so convenient!! :) Thanks for the idea. It will be working in version 13.05..

**Comment by qooob** [comment]
Tell me how does it work for you in updated 13.05?

**Comment by Sarge2013** [comment]
LIKE A BREEZE ! :+1: 
While an only one problem I met is Awstats...where link like
/awstats/awstats.pl?config=01.COM&configdir=/etc/awstats
and it does not open...may be because of specific link for AwStats in spite with all other links.

**Comment by qooob** [comment]
:) Good to hear! This was one of the best feature requests. I like it so much!

did you try not to use first `/`?

**Comment by Sarge2013** [comment]
This is the good feature just because your theme is good :+1:  IMHO :)
Yes, I tried with and without / and even full http://... - but Awstats does not open.
I suppose this is because of mechanism of the hotkeys - they open what belongs to Webmin and what is INSIDE Webmin.
Same Awstat config hotkey works ! because inside Webmin
/awstats/schedule_stats.cgi?file=/etc/awstats/awstats.example.conf
But this one - does not work - because it opens a new script outside Webmin
/awstats/awstats.pl?config=example.com&configdir=/etc/awstats

But it just a small issue, not every dream happens :) 

Let me offer you another improvement - but visual one.
You have two empty blocks on the left to corner (where Webmin logo)
Empty space on the left from logo and from right.
Why not put a system time in one of these empty blocks ?
It's informative and looks attractive.
...because just to see a system time now you should open a whole ALT+I page.

Have a nice day !
