### ISSUE TITLE
Theme extensions error

### ISSUE THREAD

**Issue by tbnv** [qooob/authentic-theme#186]
Hi,

I can't access theme extensions because of this error:

> Error	
> The Unix user [my username] does not exist.

And... it correct, as I don't use Unix users in Webmin for security purposes. So it's impossible to use theme extensions in this case?

**Comment by qooob** [comment]
Jmm, hard to tell. Can you open `settings-*` in theme folder and comment out the line `&switch_to_remote_user();` Does it work now?

What do you mean? You don't run Webmin as root?

**Comment by tbnv** [comment]
I mean the user I use to log in to Webmin is not a Unix user.

**Comment by qooob** [comment]
Try what I offered. I don't know what you're talking about really .. :)

**Comment by tbnv** [comment]
Mmm ok.

**Comment by qooob** [comment]
Can you comment out what I asked you?

**Comment by tbnv** [comment]
It looks like it doesn't work. Not a big deal for me anyway, I don't plan to use theme extensions, I was just reporting the error I got when I tried to access that page. :smile:
