### ISSUE TITLE
Navigation menu animation

### ISSUE THREAD

**Issue by tbnv** [qooob/authentic-theme#187]
Hello,

Could it be possible to add an option to disable the navigation menu slide-from-left animation, occuring on each page reload? Would be awesome. :smile:

**Comment by qooob** [comment]
OK, maybe ..but it only happens on the first load, right?

**Comment by qooob** [comment]
What is the big deal about it for you?

**Comment by tbnv** [comment]
I wouldn’t say it’s a *big* deal but it makes the interface feel slow-ish.

**Comment by qooob** [comment]
Alright! It seems not a big deal really.. and it seems, that all others are ok with this, in including me. Not sure why it looks slow-ish, probably it's your GPU settings. Maybe in the future I will do it.. will see. I will keep this in mind anyway.

If you have any other, not minor suggestions, please feel free posting under new issue!
