### ISSUE TITLE
Error - Missing Content-Type Header

### ISSUE THREAD

**Issue by severt** [qooob/authentic-theme#188]
Webmin	1.750
Virtualmin	4.16
Authentic 13.04
webmin ui is ok
but virtualmin:
![01](https://cloud.githubusercontent.com/assets/990671/7935798/23baa05a-093c-11e5-8ad4-6625a7796594.jpg)

**Comment by qooob** [comment]
What is your default page in settings? It shouldn't be the case really.  How to reproduce it. Try going to settings and select default page for Virtualmin

**Comment by qooob** [comment]
What is your default page in settings? It shouldn't be the case really. How to reproduce it? Try going to settings and select default page for Virtualmin
