### ISSUE TITLE
Unable to view Email in IE 11

### ISSUE THREAD

**Issue by siteshackinc** [qooob/authentic-theme#191]
When going to read mail, After selecting the user to see a list of emails, the page is blank.

Confirmed in IE 11 on Windows 8.1

**Comment by qooob** [comment]
I will be able to test it by the end of the month, when I get to my debug server.

**Comment by jamesmacwhite** [comment]
Its not just limited to IE 11, its versions 9 and 10 as well. I guess maybe older versions of IE also, but supporting those is debatable these days!

The cause of this is a jQuery exception:

`Object doesn't support property or method 'remove'`

![webmin-readmail-js-ie](https://cloud.githubusercontent.com/assets/8067792/8377692/4ad60f26-1c0b-11e5-8fbe-859058b1cbd9.jpg)

The quick fix I did was replace `a.remove` with `$(this).remove`. If I'm honest I haven't had much time to test it or debug it further, but hope the further details are helpful to this issue.

**Comment by qooob** [comment]
This is helpful, thanks pal! I will fix it upon next release by the end of the month! ;)

**Comment by qooob** [comment]
Ahh, ok! Please test the following - clear browsers cache after replacing default.min.js

Does it work now?

https://rostovtsev.ru/pub/src/authentic/13.05-patches/issue191/default.min.js

**Comment by jamesmacwhite** [comment]
The patch is working for me in IE 11.

**Comment by qooob** [comment]
:) good to hear.

**Comment by qooob** [comment]
Will add it to version 13.10 very soon.
