### ISSUE TITLE
New system key (ALT+1 / 2) : Not possible to create an @ with a belgium keaboard

### ISSUE THREAD

**Issue by GMo888** [qooob/authentic-theme#196]
Il's possible to disabled the new system key (ALT + 1; ALT +2) ?

With a Belgium Azerty Keyboard, it's used for the @ ... 

Thank you,
Gaëtan

**Comment by qooob** [comment]
Yes. Two ways. 1. Change modifier key. 2. Leave those keys with empty values. 

Helps?

**Comment by GMo888** [comment]
Hello,  Thank you.
I work with Webmin / Virtualmin.  
I have changed the file authentic-lib.cgi but this doesn't disable the Hotkey :-(

**Comment by qooob** [comment]
No, no, you shouldn't edit that file. Goto Webmin->Webmin Configuration->Webmin Themes. There you can chamge/remove existing hotkeys. Got it?

**Comment by GMo888** [comment]
Yes, thank you, perfect for Webmin.  
But for Usermin, I don't have the same option.

**Comment by qooob** [comment]
You mean you want to have different hotkey options for Usermin? :) Well, so far you can only edit `/etc/usermin/authentic-theme/settings.js` and edit it manually.. but every time you save theme settings in Webmin, it will be overwritten.

However, if you don't do it very often, you could just make `settings.js` immunable, by running as root:

`chattr +i /etc/usermin/authentic-theme/settings.js`

afterwards, run `lsattr /etc/usermin/authentic-theme/settings.js` to see that is has that `i` flag:

`----i--------e- /etc/usermin/authentic-theme/settings.js`

**Comment by qooob** [comment]
However, I will make a new option for you to completely disable all animation on the left menu and in tabs.

**Comment by qooob** [comment]
...and also you will be able to disable tabs animation and get back to what you get used to! Thanks for the ideas!
