### ISSUE TITLE
SQUID-Acl: IP fields are too short

### ISSUE THREAD

**Issue by badfiles** [qooob/authentic-theme#197]
And also the menu markers render still being wrong.

![screenshot from 2015-06-29 15 15 41](https://cloud.githubusercontent.com/assets/1597304/8407789/eec8be9e-1e72-11e5-9c9e-6d3efde8b8b7.png)

**Comment by qooob** [comment]
OK, will improve it. Menu is wrong? You mean white dots on the lines? If so, what is your OS/Browser?

**Comment by badfiles** [comment]
Yes, I mean the dots. Linux/Chrome  44.0.2403.52 beta

**Comment by qooob** [comment]
I also have Linux Chrome on the video and it's perfect. Did you make fonts look larger in SysConf?

**Comment by qooob** [comment]
Input will be the right size on the next release, 13.10. However, I have 3 systems (Fedora Linux with GNOME, Windows 7 and Apple OS), where I can't reproduce those funky big circles.

![screenshot from 2015-06-30 09-02-24](https://cloud.githubusercontent.com/assets/4426533/8424736/f536aa0e-1f06-11e5-9ff8-37094567f289.png)

Unless you provide me with extensive debug information about your system configuration, I will not be able to assist here.
