### ISSUE TITLE
Hardcoded path to Perl

### ISSUE THREAD

**Issue by AjaxOdessa** [qooob/authentic-theme#198]
Isn't the best practice. For example FreeBSD does keep perl binary in /usr/local/bin/ instead of /usr/bin/ This gave me a lot of frustration while trying to find out what gives me "Error - Missing Content-Type Header" every time I enable the theme.

Not a major issue, just isn't the best practice.

**Comment by qooob** [comment]
I will pass this to Webmin developers. I proposed not to use it at all, as it works better without it. Can you please double check if it's true for your system, when completely removing `/usr/local/bin/` from all files?

**Comment by AjaxOdessa** [comment]
You mean try to remove `/usr/bin/perl` from theme scripts?

**Comment by qooob** [comment]
Yes, remove all `#!/usr/bin/perl` from the top

**Comment by jcameron** [comment]
The Webmin source uses a fixed path so that checked-out files can be executed directly. For actual installation on a user's system, the path gets correct either at install time or during RPM/Deb package creation.

**Comment by qooob** [comment]
I see. But what about those who installs it manually, using Webmin Themes?

**Comment by AjaxOdessa** [comment]
My bad. On a clean system everything works fine: looks like Webmin fixes path to Perl while installing theme. Problems on existing machines most probably were due to residue of old webmin/theme.

**Comment by jcameron** [comment]
Yes, all modules/themes that get installed from a wbm.gz file get their perl paths updated at install time.

**Comment by qooob** [comment]
Great. Didn't know that! Thanks, Jamie!
