### ISSUE TITLE
CSF Page does not allow you to edit the configs

### ISSUE THREAD

**Issue by Cronus89** [qooob/authentic-theme#199]
When I go to edit a file with the webmin csf module, such as "Firewall Allow IP's" which is /etc/csf/csf.allow

It will not let me change any text, type new characters etc. Sometimes it will but very rarely.

**Comment by qooob** [comment]
I remember fixing it but I will take a look again. To make it work so far, as work around, just simply click with the mouse outside of the editor box and then again inside of it. It should work.

I had hard times understanding why it happens.

**Comment by qooob** [comment]
Did it help?

**Comment by Cronus89** [comment]
I haven't had to edit lately, and I just tested and its letting me edit it for now.

**Comment by qooob** [comment]
Alright, good to hear. Issue is closed for now.

**Comment by Cronus89** [comment]
I don't know why you closed this honestly.  It's not "fixed" it just wasnt breaking at the time I replied.  Its still broken,and I can't edit again.  The workaround does not work.

**Comment by qooob** [comment]
Clicking outside worked for me. I knew about this issue since the very beginning. I have no idea why this is happening, really.

..but will do my best to figure out and fix it. I might remove code mirror on CSF completely, in the future release to solve this.

**Comment by Cronus89** [comment]
After clicking willy nilly all over the place, the workaround works..somewhat. You can't select text though.  hopefully that helps a tiny bit.

I honestly was gonna reccomend removing it from csf all together.  I kinda like their UI anyhow.

Appreciate all the fine work, this theme really is the best, and brought a new light to webmin.

**Comment by qooob** [comment]
Thanks, pal. I will try to make it work.

**Comment by qooob** [comment]
There are issues familiar to our problem. Seems the origin is still unknown:

https://github.com/codemirror/CodeMirror/issues/3261
https://github.com/codemirror/CodeMirror/issues/2219

**Comment by qooob** [comment]
This will be fixed in version 14 in couple of days. I will remove CodeMirror from it but make some heights adjustments to make it fix properly. It's alright without it. It will work just fine.
