### ISSUE TITLE
View Data::Select Row

### ISSUE THREAD

**Issue by rrcatto** [qooob/authentic-theme#200]
When viewing table data, I want to select individual rows - can't be done. Only select all works.

**Comment by qooob** [comment]
Why not? To select a row just click on the checkbox on the very left OR just right mouse click on the row to select the row. Works? Not? Please add a screenshot to make it more clear!

**Comment by rrcatto** [comment]
right clicking the row works, but not left clicking the checkbox. Using google chrome.

**Comment by qooob** [comment]
Left clicking works perfectly for me in Chrome. Probably module specific. Where it doesn't work?

**Comment by qooob** [comment]
Which module you're experiencing this problem?

**Comment by qooob** [comment]
Which module is that you're experiencing the problem with?

**Comment by rrcatto** [comment]
Webmin->servers->mysql database server.

click on a database name.
click on a table
View data

then I try to left click on the square to select the row and nothing happens. right click works.

**Comment by qooob** [comment]
Ohh. That was deep! __Confirmed!__ Thanks for pointing this out! ;)

**Comment by qooob** [comment]
Will be fixed in version 14, most likely today! Thanks for pointing out!

**Comment by qooob** [comment]
...will also fix the table editor mode, when table is shrieked..

**Comment by sz00gun** [comment]
Version 14 ?!? Sounds great. I look forward version 14 more of your extension, than Windows 10!

PS. you told me about Filemin - superb file manager, and even your screen video: Authentic Theme 13 for Webmin/Usermin/Virtualmin/Cloudmin (May 24, 2015) shows me another nice module: csf

Nice!

**Comment by qooob** [comment]
:)) So good to hear it! Thanks!!

Yes, CSF is absolutely great. Filemin is going to replace old Java file-manager. ;)

**Comment by sz00gun** [comment]
Any other essential module for Webmin/Virtualmin? can you recommend? all modules looks nice on your theme ;) even cPanel looks ugly now... directAdmin as well, Plesk is OK, but it's not "light" so you won!

**Comment by qooob** [comment]
:) Good to hear! I hope that bunch of guys/companies won't be angry with me! I don't know what else I could recommend other than what we already have in Webmin, besides mentioned CSF and Filemin.

**Comment by qooob** [comment]
Please update to version 14. Bugs should be gone!
