### ISSUE TITLE
Broken Server Index

### ISSUE THREAD

**Issue by CyberianIce** [qooob/authentic-theme#201]
When browsing Webmin Servers Index, one is unable to make any selection in order to manipulate with objects. "Select All" do not work, select individual do not work as well.

Authentic Version: 13.10 and problem appears only in webkit browsers

**Comment by qooob** [comment]
What OS/browser are you using?

**Comment by CyberianIce** [comment]
Bug is present on both Debian 8 Jessie under amd64 kernel and Windows 7 x64 with Chrome. However, IE works normally.

**Comment by qooob** [comment]
To select/deselect you can use right mouse click when hovering on the icon. I just checked with both Icon view and Table view - all is working fine on Chrome. Here is videoscreencast:

https://rostovtsev.ru/pub/src/authentic/13.10/videoscreencasts/selections_in_webmin_server_index.webm

Isn't it the same for you?

**Comment by qooob** [comment]
How does it work for you compare to the videoscreencast?

**Comment by qooob** [comment]
Could you please say, how does it work for you compare to the videoscreencast? You the first to report this issue? It works, with me. Tested Chrome/Firefox on Linux and Opera/IE in Windows.

**Comment by qooob** [comment]
Yes, mess confirmed. Will be fixed in version 14 very soon! Thanks for reporting!!
