### ISSUE TITLE
Too light colour some buttons

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#202]
Hi,

Some buttons are not visible on low quality laptop screens, eh. mine ;p

eg. https://www.virtualmin.com/files/serial-bind.jpg

I'm talking about these top icons, specially top left ->settings. 

I spent 5hs looking on my screen and I couldn't see, 

This can be fixes,

ps. yours theme is the best of all themes for Virtualmin ;)

**Comment by qooob** [comment]
Alright, at first thanks! ;) 

Ok, :D you need to user a camera to show me how bad your buttons look like, because when you do a screenshot and showing it to me it looks just fine on my system. 

Ok, theme has CSS/JS extensions. Just got to theme settings and in the bottom of the screen find `Theme Extensions`. There in CSS section you can change/override defaults, example:

```
#headln2l > a.btn-link {
	color: #888 !important;
    background: lightGrey !important;
    border-color: #888 !important;
}
```

Click save and the code above will change your top buttons. To get proper selectors names use browser's console.

**Comment by qooob** [comment]
Did it work for you?

**Comment by sz00gun** [comment]
Hi, it is working fine! superb! Thank you, now it looks better than before, so it can be implemented in next version, better for people with poor displays ;)  it is just my 5 cents... but its up to you.

Regards

and thank you for the amazing theme, 

ps. I didn't like Virtualmin, because ... the theme... now it is like a new product. 
ps. sorry for my late answer - been on holidays

Would be nice if you make a theme for java files upload, the original one looks very bad!  any chance?

**Comment by qooob** [comment]
Alright, I will keep this in mind and add contrast extension to `https://github.com/qooob/authentic-theme-extensions`.

Java Files Uploads? What is that? In case you mean FileManger - there is already a great replacement and it's getting better and better: https://github.com/Real-Gecko/filemin

**Comment by sz00gun** [comment]
yes you are right - FileManger, thanks for the new filemin extension ;)

amazing

**Comment by qooob** [comment]
You're welcome.

**Comment by qooob** [comment]
@sz00gun In case you need more help with making elements more contrast, please let me know. I don't want to spend much time doing a patch as I beileve most people have more or the lest ok monitors. I'm ready to provide you help in case you need to but so far I will keep the issue closed as proposed piece of code works fine for you.

All patches that you make will be stored upon theme update, so no worries! ;)
