### ISSUE TITLE
Loader animation breaks node-webkit view

### ISSUE THREAD

**Issue by CyberianIce** [qooob/authentic-theme#203]
When deployed with node-webkit, loading animation (rotating circle at center of viewport) won't fade away, it keeps rotating until user interact with barely visible "x" sign in upper right corner of preloader animation (visible only on mouse hover) and afterwards return to star screen (System Information). This problem persist on all three platforms, Windows, OS X and Linux, preventing Webmin with Authentic theme to be deployed as node-webkit desktop client app. After user click on preloader's "x", he will be always returned to System Information page.

**Comment by qooob** [comment]
Hmm. Are there any errors in console? How do you make it run as `node-webkit`?

**Comment by CyberianIce** [comment]
It runs easily as client server platform, this is what you need:
Webmin server is installed on 192.168.1.224 and listening up on port 50001/tcp, (self-signed SSL cert generated with sha256 and installed in local machine Trusted Root CA to avoid questions). On the client side, this is configuration of node-webkit:

package.json
```javascript
{
  "main": "https://192.168.1.224:50001/",
  "name": "webmin",
  "description": "Webmin",
  "version": "1.0.0",
  "keywords": [ ""webmin", "test", "server" ],
  "window": {
    "title": "Webmin",
    "icon": "webmin.png",
    "toolbar": false,
    "frame": true,
    "width": 1300,
    "height": 800,
    "position": "center",
    "min_width": 480,
    "min_height": 640
  },
  "webkit": {
    "plugin": true,
    "java": true,
    "flash": true
  }
}
```

That would be everything you need to use webim as node-webkit desktop app. With this javascript embedded in footer of webmin web interface I was able to put app in system tray:
```javascript
var gui = require('nw.gui');
var tray = new gui.Tray({
    title: 'Webmin',
    icon: 'assets/css/images/menu_icon.png',
    alticon: 'assets/css/images/menu_alticon.png',
    iconsAreTemplates: false
});

var params = {toolbar: app.devMode, frame: false, transparent: true, resizable: false, show: false};
window = gui.Window.open('templates/panel.html', params);

function showPopup (x, y) {
  window.on('document-end', function(){
    window.moveTo(x - (window.window.width / 2) - 6, y);
    window.show();
    window.focus();
  });
}

tray.on('click', function (evt) {
  showPopup(evt.x, evt.y);
});
```

**Comment by qooob** [comment]
OK.

1. What are there errors in console/logs when you run this? 

2. What is the practical point, to run Webmin such unusual way?

**Comment by CyberianIce** [comment]
2. It is practical for deployment on remote XServer/MS terminal server: one installation, simle and fast browser engine, no need for web browser. One shortcut for all users and best thing is possibility to keep webin in system tray and create custom right click interface,  menus and notifications/alarms for various events.

1. I cant see console log atm :(

**Comment by qooob** [comment]
Can you click F12 to look at console? Or you said there is no browser? Original theme works with your setup or it also has issues?

**Comment by CyberianIce** [comment]
Default theme works as usual.

Here is log you requested:
```
2
Invalid CSS property name: -webkit-overflow-scrolling default.min.css:5
2
Invalid CSS property name: moz-border-radius default.min.css:5
Invalid CSS property value: -10px default.min.css:5
2
Invalid CSS property value: transform default.min.css:5
Invalid CSS property name: backface-visibility default.min.css:5
Invalid CSS property name: -webkit-overflow-scrolling default.min.css:5
Invalid CSS property name: -webkit-hyphens default.min.css:5
Invalid CSS property name: hyphens default.min.css:5
2
Invalid CSS property name: -webkit-overflow-scrolling default.min.css:5
2
Invalid CSS property name: moz-border-radius default.min.css:5
Invalid CSS property value: -10px default.min.css:5
2
Invalid CSS property value: transform default.min.css:5
Invalid CSS property name: backface-visibility default.min.css:5
Invalid CSS property name: -webkit-overflow-scrolling default.min.css:5
Invalid CSS property name: -webkit-hyphens default.min.css:5
Invalid CSS property name: hyphens default.min.css:5
2
Uncaught ReferenceError: require is not defined
```

**Comment by qooob** [comment]
Everything before `Uncaught ReferenceError: require is not defined` is not fatal.

`Uncaught ReferenceError: require is not defined` - doesn't seem like theme error. What is the stack of this error (Are there more? I need refs to my code, otherwise I can even think of what is wrong).

**Comment by qooob** [comment]
Sorry, pal! I will not be able to support this, unless you provide self-made patch, as this is out of the scope of the project.

I would think this problem happens on your side and has nothing to do with the theme at all.

I will have to leave you here on your own. Good luck.
