### ISSUE TITLE
'Apply Zone' Missing Icon

### ISSUE THREAD

**Issue by DJFraz** [qooob/authentic-theme#205]
Hello there! I would like to report a minor icon missing for applying zone edits to individual zones.

As you can see from the screen shot, in BIND DNS Server after you select a specific zone, the icon for "Apply Zone" does not exist. This isn't a bug, but looking at the text where there are nice icons sitting makes it look odd. 

Thanks!

![zone](https://cloud.githubusercontent.com/assets/13461917/8843026/3db98776-30b7-11e5-9b81-3ff5975a9453.jpg)

**Comment by qooob** [comment]
Ah, right, missed it:) thanks. Will fix it in the next release.

**Comment by qooob** [comment]
Please reinstall the theme from the repo. It will be fixed. Thanks for pointing out the bug!

**Comment by qooob** [comment]
Don't forget to click right mouse button and `Reload Frame`.

**Comment by DJFraz** [comment]
Excellent! Thank you for your work!

**Comment by qooob** [comment]
Alright, thanks, pal!
