### ISSUE TITLE
Spinning forever

### ISSUE THREAD

**Issue by expertdecisions2** [qooob/authentic-theme#206]
Since version 14.0 in Virtualmil Pro, when selecting System Statistics, the red bar goes rapidly to the right and the circles remains spinning forever. Framed Theme presents System Statistics as usual with no problems at all

**Comment by qooob** [comment]
You most likely need to clear browsers cache and restart Webmin. It was tested with Virtualmin Pro and it was working on my machine.

In case it still doesn't work, please go to theme settings and disable right content page loader and try again to see the actual error message. Also, I would need to know what is the script name that runs ib content page, by clicking right mouse button and opening `frame source`, there will be a script name. Is it `history.cgi`?

**Comment by expertdecisions2** [comment]
No success by clearing caches. 
Opening the frame in a new windows I get the url https://mydomain.com:10000/virtual-server/history.cgi and the system statistics frame with no graph at all and CPU Load checked. Y I check other links in the frame I get  a blank graph. "Download raw data" link works and displays a list of   numerical data
![captura de pantalla 2015-07-24 a las 22 26 09](https://cloud.githubusercontent.com/assets/9258503/8883990/50ca3a0c-3253-11e5-8499-69a2ecd7b68f.png)

**Comment by qooob** [comment]
What browser/OS your using?

**Comment by expertdecisions2** [comment]
Mac OS X Safari, Chrome & Firefox . All three same problem.

**Comment by expertdecisions2** [comment]
Disabling spinning in Theme settings I get this (no graphs at all): 
![captura de pantalla 2015-07-24 a las 22 36 03](https://cloud.githubusercontent.com/assets/9258503/8884121/761bb1a4-3254-11e5-9bb5-d23b438b8c8a.png)

**Comment by expertdecisions2** [comment]
And switching to Virtualmin Framed Theme everything is OK:
![captura de pantalla 2015-07-24 a las 22 57 54](https://cloud.githubusercontent.com/assets/9258503/8884538/b1b0727e-3257-11e5-8de4-731b245ca9e5.png)

**Comment by qooob** [comment]
Yes, confirmed.

**Comment by sz00gun** [comment]
Version 14 looks OK to me, on all Internet Browsers apart from the latest Firefox. I can noticed a crash sometimes 
![debug](https://cloud.githubusercontent.com/assets/7549566/8888922/728c7800-32ba-11e5-972f-5fa542bf5a5d.jpg)

**Comment by qooob** [comment]
I will fix this issue with Statistics a bit later. Sorry for that. Probably this is what's causing it in Firefox.

**Comment by qooob** [comment]
It will be fixed in version 14.01.

**Comment by expertdecisions2** [comment]
TKS!

**Comment by qooob** [comment]
You're welcome!
