### ISSUE TITLE
Theme version reported wrong (12 in state of 14) in Usermin / System information

### ISSUE THREAD

**Issue by ThierryMasson** [qooob/authentic-theme#208]
Dear,

With the last update of "authentic-theme" (release 14), "Usermin" / "system information" reported this :
Authentic Theme 12.00. Latest available release 14.00

Or the release 14 is installed, and "Webmin" / "system information" reported well:
Theme version 	Authentic Theme 14.00

Restart webmin/usermin as no effect.
Or... the update of usermin is not applied well with the webmin theme update ?

Best regards,

**Comment by qooob** [comment]
Not applied. Just go to Usermin Themes and install it manually by giving it a link or downloading the latest version and uploading it.

**Comment by ThierryMasson** [comment]
I'm sorry, 
Perfect...downloaded and installed "manually".
I was supposed that Usermin theme is updated as well Webmin (in the same time...) when update purposed...
;-)

**Comment by qooob** [comment]
:)
