### ISSUE TITLE
Another spinning forever issue

### ISSUE THREAD

**Issue by LTerik** [qooob/authentic-theme#209]
In webmin 1.760 w/ Authentic Theme 14.00, if your session times out and you click on any link in the interface, instead of taking you to the login screen with the time-out notification, a blank screen with the spinning circle will be shown.

Tested with Firefox 38 and Google Chrome 44.

**Comment by qooob** [comment]
Hm, I see. And if you manually reload that page, then it takes you to the login screen?

**Comment by LTerik** [comment]
Apologies for late reply, been a busy day. Yes, a Shift-Reload will take me to the "Session timed out" screen.

**Comment by qooob** [comment]
Thanks for reporting! It will be fixed in version 14.01.
