### ISSUE TITLE
Adding to favorites feature

### ISSUE THREAD

**Issue by cybermarmotte** [qooob/authentic-theme#210]
What about being able to "star" a module/page that we are using frequently and being able to browse through it from a new category named for example favorites. I'm using less than 10modules frequently. 

Just my 2 cents

**Comment by qooob** [comment]
It's actually there already. It's implemented using Custom Hotkeys. Just the URL and you can get there by clicking Alt+1, Alt+2, Alt+3. You can set it up in Authentic Theme Settings.

Is this alright with you?

**Comment by cybermarmotte** [comment]
I'm not the kind of shortcuts person but will try to use it. I really think it should be nice to have the little star on each pages, and being able to access the one activated.

**Comment by qooob** [comment]
Star on each page? I thought you said the menu on the left?

Ok, listen what you can try right now: Webmin has inbuilt-functionality for doing it.

Go to `Webmin Configuration`:
   1. Open Edit Categories and create new category, let's say Favorites (`favorites   Favorites`)
   2. Then goto `Reassign Modules` and reassign modules you want to that category

You will get all your often used modules in Favorites category. On the next release, I will add an icons for label/labels like favorite.

If it's not good enough, please explain what you mean by `to have the little star on each pages, and being able to access the one activated`

**Comment by cybermarmotte** [comment]
I understand the reasign in categories and you understand what I mean with what you called label/lables. So everything is fine. Thanks

**Comment by qooob** [comment]
Oh. Having a star _on each page_ - sound like a great idea!! I will do this (most likely) in version 15.

**Comment by qooob** [comment]
Alright, this feature seems to be great but very hard to do! However I will implement this in the new up-coming release of _Authentic Theme_ __15__!

**Comment by cybermarmotte** [comment]
You rock, congrats! You deserve to be the default theme for webmin
Le 16 août 2015 10:09, "Ilia Rostovtsev" <notifications@github.com> a
écrit :

**Comment by qooob** [comment]
:+1:

**Comment by cybermarmotte** [comment]
Gorgeous implementation! Congrats!

**Comment by qooob** [comment]
Thanks! I'm glad you liked it!
