### ISSUE TITLE
Problem after update (virtual-server::list_system_info failed line 3617) (Fixed)

### ISSUE THREAD

**Issue by Goeny** [qooob/authentic-theme#211]
I just updated to v14.01 (or something like that) And the system info page won't load anymore.
Now i get the following message.. How should i fix this? (or how to revert to v14.0)

virtual-server::list_system_info failed : Undefined subroutine &net::active_interfaces called at /usr/share/webmin/virtual-server/virtual-server-lib-funcs.pl line 3617.

**Comment by qooob** [comment]
You probably edit those files manually. At the moment I have no clue and based on the error message it seems that it's not theme related? Tried to restart Webmin?

**Comment by qooob** [comment]
Are you installing Webmin from the repo or rpm?

**Comment by qooob** [comment]
What OS you're on and how do you upgrade?

**Comment by HansKristoffer** [comment]
I have exactly the same problem as Goeny after update

**Comment by elaphos** [comment]
Same here. Updated two servers, one Debian 6 the other Debian 7

**Comment by qooob** [comment]
Restart Webmin!

**Comment by elaphos** [comment]
Restarting Webmin didn't help. Going back to 14.0...

**Comment by qooob** [comment]
Is this only happenging on System Information page?

**Comment by HansKristoffer** [comment]
Yes

**Comment by qooob** [comment]
Can you please open `sysinfo.cgi` and let's say replace `&foreign_available("net")` with, let's say `&foreign_available("netss")` (anything). Does it work this way?

**Comment by elaphos** [comment]
Not only System Information:

Webmin: Network -> Linux Firewall: Undefined subroutine &net::boot_interfaces called at debian-linux-lib.pl line 121.

Virtualmin: Backup & Restore -> Restore Backup: Undefined subroutine &net::active_interfaces called at /usr/share/webmin/virtual-server/virtual-server-lib-funcs.pl line 3617.

**Comment by elaphos** [comment]
Changing &foreign_available("net") doesn't work.

**Comment by qooob** [comment]
You will be surprised to know, that I haven't changed `sysinfo.cgi` since last update.

Your error has nothing to do with the theme. Change to default theme and you should experience that same issue, I bet!

How and when did you install/update Webmin?

**Comment by Goeny** [comment]
I actually switched theme... Problem is not there with other themes.
Installed virtualmin with install.sh on Debian 7.
Already restarted webmin, didnt help.

**Comment by elaphos** [comment]
Bet lost! ;)

authentic-theme 14.0 and Virtualmin Framed Theme are ok

Both server installed via Virtualmin GPL install.sh script and updated via package manager.

One (Debian 6) two years ago, Webmin 1.760/Virtualmin 4.17
the other (Debian 7) 7.7.2015, Webmin 1.760/Virtualmin 4.18

**Comment by qooob** [comment]
Hmm. Will see. Let me take a look again! I will post a bit later.

**Comment by qooob** [comment]
1. Did you recently pull from Webmin repo?
2. How did you upgrade install the theme?
3. What is the output of `ls -lsaZ /usr/share/webmin/authentic-theme`

**Comment by specktator** [comment]
Guys its all fine from Ubuntu 14.04.2 LTS , authentic 14.01 and Webmin 1.760 ... cleard cache memory etc... restared Webmin .... just fine from my side.

**Comment by qooob** [comment]
The error from virtual-server.lib.func.pl, 3617 says there is no method `active_interfaces` on class `net`.

```Perl
# From interface detected at check time
	&foreign_require("net", "net-lib.pl");
	local $ifacename = $config{'iface'} || &first_ethernet_iface();
	local ($iface) = grep { $_->{'fullname'} eq $ifacename }
			      &net::active_interfaces();
	if ($iface) {
		return $iface->{'address'};
		}
	else {
		return undef;
		}
	}
```

Tell me how does it tie to Authentic Theme?

**Comment by qooob** [comment]
Hm. If you running Debian, actually you could experience this problem, as `net/debian-linux-lib.pl` doesn't really have this (`active_interfaces`) method.

I would say, that you should have faced this issue long before. Will notify Joe.

**Comment by elaphos** [comment]
Strange... But what could trigger this issue? Tried a third server (Debian 6) same behaviour: Other themes and 14.0 work fine, 14.01 -> throws this `active_interfaces` error

**Comment by qooob** [comment]
What is the output of authentic-theme folder of `ls -lsaZ` command?

**Comment by qooob** [comment]
No, this method is there, my bad, as `debian-linux-lib.pl` pulls `linux-lib.pl`.

What is causing it? I have no clue yet. I'm not at the machine.

I will ask again, please:

1. Did you recently pull from Webmin repo?
2. How did you upgrade/install the theme?
3. What is the output of `ls -lsaZ /usr/share/webmin/authentic-theme` (or whereever your theme folder is)

**Comment by cooperdk** [comment]
I have it too, qooob.

It is 100% certainly an error in 14.01.

14.00 and later work FINE. I just tested the last three versions.

All other themes work FINE. The original, virtualmin framed, and  the bwtheme (bootstrap).

I both tried upgrading and installing manually. The error is the same no matter how 14.01 is applied.


===== Output of ls command

root@*******:~# ls -lsaZ /usr/share/webmin/authentic-theme
total 292
 4 drwxrwxrwx   6 root root ?  4096 Jul 31 05:45 .
20 drwxr-xr-x 138 root root ? 20480 Jul 31 05:45 ..
60 -rwxrwxrwx   1 root root ? 58872 Jul 31 05:45 authentic-lib.cgi
44 -rwxrwxrwx   1 root root ? 43327 May 31 12:24 authentic.pl
 4 drwxrwxrwx   2 root root ?  4096 May 31 12:24 .build
 4 -rwxrwxrwx   1 root root ?  2584 Jul 31 05:45 buttons.cgi
32 -rwxrwxrwx   1 root root ? 31097 May 31 12:24 CHANGELOG.md
 8 -rwxrwxrwx   1 root root ?  7212 May 31 12:24 changelog.pl
 4 -rwxrwxrwx   1 root root ?   116 May 31 12:24 config
 4 drwxrwxrwx   3 root root ?  4096 May 31 12:24 images
12 -rwxrwxrwx   1 root root ? 11323 Jul 31 05:45 index.cgi
 4 drwxrwxrwx   2 root root ?  4096 May 31 12:24 lang
 4 -rwxrwxrwx   1 root root ?  1084 May 31 12:24 LICENSE
 8 -rwxrwxrwx   1 root root ?  6783 Jul 31 05:45 navigation.cgi
 8 -rwxrwxrwx   1 root root ?  7438 May 31 12:24 README.md
 8 -rwxrwxrwx   1 root root ?  6421 Jul 31 05:45 session_login.cgi
 4 -rwxrwxrwx   1 root root ?   732 Jul 31 05:45 settings.cgi
 4 -rwxrwxrwx   1 root root ?  2441 Jul 31 05:45 settings-editor_read.cgi
 4 -rwxrwxrwx   1 root root ?   655 Jul 31 05:45 settings-editor_write.cgi
 8 -rwxrwxrwx   1 root root ?  7347 Jul 31 05:45 settings-upload.cgi
 4 -rwxrwxrwx   1 root root ?  2614 Jul 31 05:45 settings-upload_save.cgi
28 -rwxrwxrwx   1 root root ? 26619 Jul 31 05:45 sysinfo.cgi
 4 -rwxrwxrwx   1 root root ?   197 May 31 12:24 theme.info
 4 drwxrwxrwx   5 root root ?  4096 May 31 12:24 unauthenticated
 4 -rwxrwxrwx   1 root root ?     6 May 31 12:24 VERSION.txt

**Comment by elaphos** [comment]
1. No pulls from repo, all updates via apt-get
2. Tried both: Update button and a fresh install from authentic-theme-latest.wbt.gz (deleted the whole "authentic-theme"directory before)
3. 

insgesamt 292
 4 drwxr-xr-x   5 root root ?  4096 Jul 31 00:33 .
20 drwxr-xr-x 133 root root ? 20480 Jul 31 00:33 ..
64 -rwxr-xr-x   1 root root ? 64156 Jul 31 00:33 authentic-lib.cgi
40 -rwxr-xr-x   1 root root ? 38156 Jul 21 16:43 authentic.pl
 4 -rwxr-xr-x   1 root root ?  2584 Jul 31 00:33 buttons.cgi
36 -rw-r--r--   1 root root ? 34036 Jul 21 18:20 CHANGELOG.md
 8 -rwxr-xr-x   1 root root ?  6147 Jul 21 19:08 changelog.pl
 4 -rw-r--r--   1 root root ?   118 Jul 19 22:51 config
 4 drwxr-xr-x   3 root root ?  4096 Jul 21 18:25 images
12 -rwxr-xr-x   1 root root ? 11242 Jul 31 00:33 index.cgi
 4 drwxr-xr-x   2 root root ?  4096 Jun 30 12:02 lang
 4 -rw-r--r--   1 root root ?  1082 Jul 19 22:52 LICENSE
 8 -rwxr-xr-x   1 root root ?  6841 Jul 31 00:33 navigation.cgi
 8 -rw-r--r--   1 root root ?  7736 Jul 21 19:10 README.md
 8 -rwxr-xr-x   1 root root ?  6715 Jul 31 00:33 session_login.cgi
 4 -rwxr-xr-x   1 root root ?   732 Jul 31 00:33 settings.cgi
 4 -rwxr-xr-x   1 root root ?  2441 Jul 31 00:33 settings-editor_read.cgi
 4 -rwxr-xr-x   1 root root ?   737 Jul 31 00:33 settings-editor_write.cgi
 8 -rwxr-xr-x   1 root root ?  7347 Jul 31 00:33 settings-upload.cgi
 4 -rwxr-xr-x   1 root root ?  3183 Jul 31 00:33 settings-upload_save.cgi
28 -rwxr-xr-x   1 root root ? 28479 Jul 31 00:33 sysinfo.cgi
 4 -rw-r--r--   1 root root ?   199 Jul 19 22:52 theme.info
 4 drwxr-xr-x   5 root root ?  4096 Jul 18 00:59 unauthenticated
 4 -rw-r--r--   1 root root ?     6 Jul 19 22:52 VERSION.txt

**Comment by qooob** [comment]
I can't believe  to what I'm seeing and why actually Perl didn't fail. This is horrible.

I simply placed parenthesis in the wrong place that I would expect to fail in _any programming language_ but it __worked__ in Perl taking the error to the other place?

I will ask Joe or Jamie about this as it's completely rediculus. Probably it's the Perl bug.

Was:
`index( $ENV{'REQUEST_URI'}, '/virtual-server/history.cgi' != -1 )`

Has to be:
`index( $ENV{'REQUEST_URI'}, '/virtual-server/history.cgi' ) != -1 `

I will do the update in few minutes.

**Comment by qooob** [comment]
Alright, guys, please upgrade! Very sorry about this and thanks for pointing out!!

Could you please report your Perl versions?

**Comment by elaphos** [comment]
Working! 👍
Perl v5.10.1 (Debian 6)
Perl v5.14.2 (Debian 7)

**Comment by qooob** [comment]
I see!! That is _so_ wrong that it passed compilation on my machines.

I got __Perl v5.20.2__

**Comment by Goeny** [comment]
Sorry for the late reply...
Fixed with new update! Thank you!!

I am on Perl 5.14.2 (Debian 7)

**Comment by cooperdk** [comment]
I have Perl v5.14.2 too

The 14.02 update fixed the issue for me, too. Thanks! :-)

**Comment by qooob** [comment]
You are welcome, guys! Good luck! ;)

Thanks for reporting!
