### ISSUE TITLE
Domain selection does not work properly in Microsoft Edge

### ISSUE THREAD

**Issue by h9k** [qooob/authentic-theme#212]
There is a problem with the Edge browser, which renders the template pretty unusable.
The problem is, that if you select a domain from the dropdown menu under Virtualmin, the correct summary page gets displayed on the right and the domain is selected in the dropdown. But as soon as I click on something like "Edit Virtual Server", it opens the page for the very first domain in the list, not the one that is currently selected.
Also, when logging in, it does not load the correct domain as default, but always the first one in the list even if configured differently.
This only affects the Microsoft Edge browser, other browsers seem to cope fine.

**Comment by qooob** [comment]
Microsoft Edge, huh? What the heck is that anyway? :D When I get my free update of Microsoft Windows 10 on my debug machine I will take a look, promise.  Maybe submit a bug to [Microsoft Edge](https://github.com/MicrosoftEdge)? ;))

**Comment by qooob** [comment]
My friend, hi! I have installed Windows 10 on my debug machine and tried Microsoft Edge wit. I will not be able to share all of my resentment over this 'new' OS and it's internet browser. 

I'm not sure why only domain selection didn't work for you. For me, nothing really worked the expected way. It seems that Edge is blocking background calls or treats them somehow differently. I tried to debug it and couldn't find logical explanation to why it was happening, and it's DevTools only pointed to `jquery.js` file. Probably it's jQuery bug itself, I don't know.

In the end, I will not be able to support Microsoft Edge browser (meanwhile at least) and warn other people not to use it with popup message.

**Comment by h9k** [comment]
Too bad. I like the OS, and I think the browser has potential... once it gets extensions.
Anyway, let's wait and see, mabye MS or jQuery will fix the issues by themselves and at some point the theme might work properly :)

**Comment by qooob** [comment]
Yes, the problem really not in the theme of how I could see it. I really tried and was surprised that AJAX in iframe didn't work even inside same domain. This is very wrong and has no security issues. On the other hand edge has that switch `Open in Internet Explorer` and it seems that they potentially expect that things will not work correctly. Please keep me posted about this as I'm intended to fix this. If you find a solution please let me know.

Does it work alright with Internet Explorer browser? Do you like Edge more than Chrome? If so, couuld you please tell why?

**Comment by qooob** [comment]
Alright, I made its harsh way through making to support Edge browser. It will be alright and working in version 16.

Report back after you try, please!

**Comment by h9k** [comment]
Sorry for the delay. Yeah, seems to work fine now :) Thanks!
