### ISSUE TITLE
Virtual Server list won't populate.

### ISSUE THREAD

**Issue by n3cr0mantlc** [qooob/authentic-theme#213]
I had this issue for several versions now and it still doesn't work after your latest update.  If I click on List Virtual Servers the spinner spins and the progress bar goes all the way across, but no list appears.

I'm running Centos 6.x on my server and using Firefox on OpenSuSe desktop.  Konqueror and Chrome have the same issue.  It appears on two different servers with the same underlying OS.  It works fine with all other themes tested.

**Comment by qooob** [comment]
Interesting. I just double checked and it seems to work perfectly fine on by systems. Open Chrome console (F12) and reload the page, then click the link. Are there any errors?

**Comment by n3cr0mantlc** [comment]
I didn't see any errors.  What file log the errors?

**Comment by qooob** [comment]
When you click on close button, when you cover on the spinner, what do you see afterwards?

**Comment by n3cr0mantlc** [comment]
It goes back to the System Information page.

**Comment by qooob** [comment]
Then disable the content page (right frame) loader in theme settings (Webmin Configuration->Themes) and try again. When no loader is there, what is happening?

**Comment by n3cr0mantlc** [comment]
Do you mean this setting?

Load default content page
When switching tabs, right frame content page is reloaded. Do not keep currently opened right frame content page and reload with default?

**Comment by qooob** [comment]
No, this `Enable spinner for content page`

**Comment by n3cr0mantlc** [comment]
Bar goes all the way across the top, but never loads the page , still seeing System info page.

**Comment by qooob** [comment]
Can you please make videoscreencast with Chrome console opened? I don't see it's possible.

**Comment by n3cr0mantlc** [comment]
What's a Chrome console?  I'm using Firefox, do you mean developer console?

**Comment by qooob** [comment]
Yes, you said you tested it in Chrome, this is why I preferred Chrome.

**Comment by qooob** [comment]
Start video-screencast, fully reload the page and the with console openned click on the link.

**Comment by n3cr0mantlc** [comment]
OK, I've got Chrome open, but I don't see this video-screencast you speak of.   How do I start this?

**Comment by qooob** [comment]
I mean to take a video-screenshot. It has noting to do with Chrome.

When I say it it's working, I mean the following video. Do the same:
https://rostovtsev.ru/pub/src/authentic/14.02/issue213/Screencast_from_02-08-15_20:27:22.webm

**Comment by n3cr0mantlc** [comment]
OK,  I have to break for a bit, but will get back on it later tonight.

**Comment by n3cr0mantlc** [comment]
It may work on yours but not mine.  Same result in either Chrome or Firefox

http://www.area510.net/images/temp/webmin-2015-08-02_13-14-49.mkv

**Comment by qooob** [comment]
That is so strange! I wish you opened console, and made video with console opened, so I could see what is going on. Click `Ctrl+Shift+C` and hover on that link in the left menu, on the right you will see the HTML code. What is it, can you paste and copy please?

**Comment by n3cr0mantlc** [comment]
http://www.area510.net/images/temp/webmin_1-2015-08-02_13-14-49.mkv

**Comment by qooob** [comment]
It seems like the same video?

**Comment by qooob** [comment]
I get `ERROR 404: Not Found.`

**Comment by n3cr0mantlc** [comment]
Sorry about that.  Try this.

http://www.area510.net/images/temp/webmin_1-2015-08-02_20-03-25.mkv

**Comment by qooob** [comment]
My friend, I see, that you have tried but you don't seem to feel comfortable with console, yet. What you should do, and try it this time without video, just clicking on `magnifying glass` in console (I did it in my video) / or clicking `Shift+Ctrl+C` will give you the same result,  and __try to copy and paste the content of that link__ (List Virtual Servers), here how it should look:

```HTML
<li>
     <a target="page" class="navigation_module_trigger" data-href="/virtual-server/index.cgi"><i class="fa fa-fw fa-tasks"></i> <span>List Virtual Servers</span></a>
</li>
```

**Comment by qooob** [comment]
Any luck with it?

**Comment by n3cr0mantlc** [comment]
<li>

    <a class="navigation_feedback_trigger" data-href="/virtual-server/index.cgi" target="page" href="">
        <i class="fa fa-fw fa-tasks">
            ::before
        </i>
        <span>

            List Virtual Servers

        </span>
    </a>

</li>

**Comment by n3cr0mantlc** [comment]
The text appears to be wrong.  If I insert "module" in place of "feedback" it works as expected.  Syntax error.  How could I be the only one experiencing this?

**Comment by n3cr0mantlc** [comment]
Confirmed.  I've change the text in the navigation.cgi from feedback to module and it works as expected.

**Comment by qooob** [comment]
This is wrong.. Now sure yet.. Thinking..

**Comment by qooob** [comment]
you have `navigation_feedback_trigger` instead?

**Comment by qooob** [comment]
Hold on... I think I got something..

**Comment by qooob** [comment]
OMG!! Are you using OLD Webmin/Virtualmin?? What are your versions??

**Comment by qooob** [comment]
So far, go to `navigation.cgi`, line 144 and replace `navigation_feedback_trigger` with `navigation_module_trigger` - it's ok now, right??

**Comment by qooob** [comment]
You have to upgrade your Webmin version!!

**Comment by qooob** [comment]
What you got is definitely below 1.730

**Comment by n3cr0mantlc** [comment]
I upgrade every time an upgrade is available.  1.76 with Authentic 14.02

**Comment by qooob** [comment]
Ok, let's get slower here! How do you install Webmin? Latest from RPM is 1.760?

**Comment by qooob** [comment]
Ohh. And version of Virtualmin??

**Comment by n3cr0mantlc** [comment]
Virtualmin 3.91

**Comment by qooob** [comment]
This is the reason! You have two options! Either fix line `144`, like I mentioned above (and it will be fix in the next release of Authentic Theme as well) or upgrade Virtualmin to the latest one (4.18)! Both will work but I recommend updating your Virtualmin! ;)

**Comment by n3cr0mantlc** [comment]
I've already edited the line.  I will upgrade.  Thanks for helping identify the problem.  Good work on the themes.  Donation coming your way soon.

**Comment by qooob** [comment]
Thanks, pal, any time! Good luck!! ;)
