### ISSUE TITLE
Entire row clickable at "Script Installers" list

### ISSUE THREAD

**Issue by j0bb13** [qooob/authentic-theme#214]
Server: Debian 8 64bit
Client OS/Browser: Windows 8.1, Chrome 44 64bit

Where: System Settings -> Scripts Installers -> Disable Scripts
The entire row of each script links to their associated websites, which makes it difficult to use the versions drop down menu. Click and drag works, but just clicking on the drop-down menu opens another website.

At *Some Virtual Server* -> Install Scripts it works better, there only the name of the scripts links to a website.

![authentic bug scripts installers](https://cloud.githubusercontent.com/assets/2331451/9027633/1e05a078-395d-11e5-9bc3-7a1fa9fb4038.png)

**Comment by qooob** [comment]
I will check and try fixing it. It sound very possible. Thanks for reporting!

**Comment by qooob** [comment]
Yes, confirmed and will be fixed in version 15. Thanks for reporting! ;)
