### ISSUE TITLE
better css for config.info titles

### ISSUE THREAD

**Issue by gerbier** [qooob/authentic-theme#218]
config.info file contains parameters descriptions, such : ssleay=Path to openssl or ssleay program,3,Automatic
but may also have "titles" such : line2=System configuration,11
(examples were taken from acl/config.info )

the css for titles is not different from thus for parameters, so the configuration is difficult to read.
Could you improve the css to allow the titles appear clearly ?

**Comment by qooob** [comment]
Not sure what titles are you talking about?

**Comment by gerbier** [comment]
this is the config lines beginning by "line" : line1, line2 ...
it helps grouping parameters in "sections"

**Comment by qooob** [comment]
You mean adding them to where? Theme doesn't have `config.info` file but only `config`. I honestly have no idea what are you talking about.

Please express your self differently in more detailed, accurate way.

**Comment by gerbier** [comment]
the best way will be to show you 2 screenshots of the config screen of "Bootup and Shutdown" module:

![authentic](https://cloud.githubusercontent.com/assets/900794/9244044/b5a521dc-4197-11e5-9246-ce53616a12d7.jpg)
![gray](https://cloud.githubusercontent.com/assets/900794/9244043/b5a310b8-4197-11e5-9a2c-f9cb1fc15781.jpg)
with old theme, "sections names" (I do not kow how to tell them) are in blue , for example "configurable options", "system configuration"
this matches the /usr/libexec/webmin/init/config.info file :

line1=Configurable options,11
expert=Allow selection of individual runlevels?,1,1-Yes,0-No
desc=Display actions with descriptions,1,2-Yes&#44; and show all runlevels,1-Yes,0-No
order=Show boot order of actions?,1,1-Yes,0-No
status_check=Show current status of actions,1,2-On index and action pages,1-On action page only,0-No
sort_mode=Sort actions by,1,1-Boot order,0-Name
line2=System configuration,11
init_mode=Boot system,4,-Detect automatically,init-SysV init,upstart-Upstart,systemd-Systemd,osx-MacOS,rc-FreeBSD RC scripts,win32-Windows s...

**Comment by qooob** [comment]
Now, I understood, finally! Thanks, good point. I will try doing it by next release! ;)

**Comment by gerbier** [comment]
thank you !

**Comment by qooob** [comment]
Alright, that was a very good point! I will add it to the Authentic Theme 15 very soon! Thanks! ;)
