### ISSUE TITLE
Chrome 29 Endless Redirect Loop

### ISSUE THREAD

**Issue by dcrdev** [qooob/authentic-theme#219]
In version 29 of Chrome the authentic theme will continuously try to redirect back to your referring location. It becomes impossible to access anything within Webmin for example the ability to change themes back to the default.

I appreciate that Chrome 29 is somewhat outdated, but it's only 2 years out of date - I'm sure there are many people who use far older browsers. I'm only raising this because unfortunately it's the standard browser on my company laptop and I would like to manage my server at work (if needed).

To Reproduce:
Centos 7.1 Minimal
Webmin 1.760
Google Chrome 29.0.1547.66

**Comment by qooob** [comment]
Alright, where I could get version 29 to test it? What particular error do you get in console?

Did you think that this bug could be related to browser itself? Chrome is very easy to upgrade?

**Comment by dcrdev** [comment]
Should be able to get it from:
http://en.softonic.com/s/google-chrome-29 
or here:
http://dl.google.com/chrome/win/29.0.1547.66_chrome_installer.exe

I'm getting this endlessly in the console and nothing else:
Resource interpreted as Font but transferred with MIME type application/octet-stream: "http://mydomain.com:10000/unauthenticated/fonts/roboto/7KXg6nyyqN8gyMoNwQ7aOQ.woff". 

Yeah chrome is easy to upgrade, but like I said I'm trying to use this in the office on my company laptop - which as you can imagine is not so easy to upgrade software on.

**Comment by qooob** [comment]
I'm sorry my friend, you are here on your own. Chrome 29 is almost 20 version behind the current one. It could be browser's bug itself and I will not be able to figurethis out. Convince your boss to upgrade your Chrome browser, referring to security issues and Google recommendations.
