### ISSUE TITLE
Usermin login problem

### ISSUE THREAD

**Issue by acosonic** [qooob/authentic-theme#221]
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.670 Date: Fri, 14 Aug 2015 13:12:21 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close 
Error - Perl execution failed
Undefined subroutine &main::print_session_login_head called at /usr/share/usermin/authentic-theme/session_login.cgi line 75.

**Comment by qooob** [comment]
How did you install the theme?

**Comment by acosonic** [comment]
I don't remember... I did update trough virtualmin's modal box today.

**Comment by qooob** [comment]
I see. I would expect that you need to set proper, executable permissions on .CGI theme files.

Besides makes sure, that you have latest Webmin/Virtualmin installed. What are your versions!  Did you restart Webmin after installing the theme?

**Comment by qooob** [comment]
.. this function seems to be from the old release. It's either stuck in cache or you need to reinstall your theme. I can see Webmin 1.670 you got there so it shouldn't be the problem.

**Comment by qooob** [comment]
How did it go? Does it work now?

**Comment by qooob** [comment]
Any luck, news?

**Comment by acosonic** [comment]
Restarted, refreshed, now it's all cool!

Thanks!
