### ISSUE TITLE
missing h3 titles on help display

### ISSUE THREAD

**Issue by gerbier** [qooob/authentic-theme#223]
I'm running webmin 1.760 on fedora 22, with Authentic Theme 14.02

and I wrote a dummy help file for a module with the following code :
<h1>test h1</h1>
<h2>test h2</h2>
<h3>test h3</h3>
<h4>test h4</h4>

and I can see in the pop-up window 
test h1
test h2
test h4
but not "test h3"

**Comment by qooob** [comment]
You want to tweak it with your own `CSS`?

**Comment by gerbier** [comment]
no, I do not use my own css 
In fact, a just was checking the help file for my webminstats's module, and I do not see what was expected, so I have a test with a very simple help file : the h3 line is missing

**Comment by gerbier** [comment]
with a screen copy : I can see h1, h2, h4, not h3 !
![webmin_help_h3](https://cloud.githubusercontent.com/assets/900794/9406248/02c4c072-47ff-11e5-8089-4f2d43f75557.jpg)

**Comment by qooob** [comment]
You don't see it as my theme probably overrides it in it's own way. You could re-write it using `.h3` class on some other element.

It's removed by the script `$parent.find('._tmp_help_content h3').remove();`

I think I had some reasons behind it when doing it. Bootstrap has a set of `.h1, .h2, .h3,.h4, .h5, .h6` to use on other elements? Why not try this?

**Comment by gerbier** [comment]
yes, I've found it in unauthenticated/js/authentic.min.js : `$help_body=b.find("._tmp_help_content h3").remove()`
it's just strange to remove only this title (and nothing about others h1, h2, h4, h5, h6.

the problem is that I'm lazzy : I have hundred of help files with h3 title
and many other core modules too, for example cron/help/help.html

[eric@localhost webmin]$ find . -type d  -name help -exec grep -i -r h3 {} \; -print | wc -l
1569

**Comment by qooob** [comment]
Hmm.. :) I will see what I can do.. Let me test it..

**Comment by qooob** [comment]
Actually it seems like a bug. I will replace it with: `.find('._tmp_help_content h3.ui_subheading').remove();`

Now you should be safe. Edit `authentic.min.js`  and make sure to replace `$help_body=b.find("._tmp_help_content h3").remove()` with `$help_body=b.find("._tmp_help_content h3.ui_subheading").remove()` - does it do the right work for you?? It does for me and if so, I would prefer to keep it this way in upcoming version 15. ;)

**Comment by qooob** [comment]
..besides I will add to that `h3` a class called `h3_help', that will work like this:

```CSS
h3.h3_help {
    font-size: 17px;

    margin-top: 5px;
}
```

Thanks for pointing out this bug!

**Comment by gerbier** [comment]
I just test your authentic.min.js patch, and it is now ok for me

thanks for fixing this
