### ISSUE TITLE
Dashboard tab in main menu

### ISSUE THREAD

**Issue by tbnv** [qooob/authentic-theme#224]
Hi,

Since the latest update, I have Webmin and Dashboard tabs at the top of the main menu. A click on the Webmin tab doesn't do anything, except that I see the spinner and nothing appears. Clicking on Dashboard seems to lead to the system information page. But we didn't need that Dashboard tab because there was a System Information link in the main menu.

Also the option "Display System Information link as a button" doesn't seem to work anymore.

**Comment by qooob** [comment]
This switch is only meant to work only in Webmin mode to remove that two black squares on the left and right. The switching not meant to do anything, as the menu content the same.

In case you don't have `sysinfo` page opened, when clicking on the Dashboard tab will open the sysinfo page. In case you have sysinfo opened, clicking on switches will not do anything as there is nothing to do.

Do you expect other behaviour?

Thanks for the point` Display System Information link as a button` has to disappear in this mode.

**Comment by tbnv** [comment]
Hi,

I think there was no issue with the black squares. The issue is here:

* When viewing the sysinfo, clicking on Dashboard button shouldn't do anything. That's ok, obviously.
* When not viewing the sysinfo, clicking on the Webmin button shows a blank page with the spinner, indefinitely. Nothing appears in the main container but the spinner makes me think that something is loading or should happen.

Why not just this? http://shrrr.it/5uzdxjr1fd_image.png
It looks like you're adding complexity to a non-existing problem. :smile:

**Comment by qooob** [comment]
Yes, there were a lot of complexity over that. You say the spinner starts when clicking on Webmin tab? That should not be the case. It's not happening on my end. What browser you're using

**Comment by tbnv** [comment]
I’m using Google Chrome (latest version) on OS X.

Yes, I’m *allowed* to click on the Webmin tab when I’m not on the sysinfo page (which leads to the spinner then nothing), that’s why it’s so confusing. ;)

**Comment by qooob** [comment]
Can you show how your screenshot would look without zooming? Just do the whole left menu without changing aspect.

Thank you, pal! I will try fixing it soon.

**Comment by tbnv** [comment]
Here you are:

![](http://shrrr.it/i8qsbui2t6_image.png)

I'm not zooming btw, I have a Retina display maybe that's why you see it bigger.

**Comment by qooob** [comment]
I see! Thank you for the screen shot. I have Apple Laptop, I will test it and fix it somehow! ;)

**Comment by qooob** [comment]
I tested it all the way I could on my Mac and could not reproduce another problem, when loading starts when you switch to Webmin. In my case the switch is only moving and thats it. It doesn't start the loader. Can you try again clearing cache and/or trying other browsers, just out of curiosity?

I will fix that issue when system information button should not be displayed in this mode.

**Comment by tbnv** [comment]
Which browser are you using? I just tried with Safari and I have the same behavior.

For example, if I go to `Webmin > Webmin Configuration` and then I click on `Dashboard` switch I go to sysinfo (which is okay). But if I am on `Webmin > Webmin Configuration` and then click on the `Webmin` switch instead, I see the spinner.

**Comment by tbnv** [comment]
Also, for the switch function to be complete (regarding the UX), when a switch changes it **must** do something. Therefore, I think that when you are not on the sysinfo page, the switch should not allow a click on `Webmin` tab but only on `Dashboard` in order to get back to the sysinfo. What do you think?

**Comment by qooob** [comment]
AHH! Now I confirm the loader is appearing. I din't understand what you meant.

Yes, it should do something. And I'm willing to make it switch to default Webmin Page that is set in Index Page Options, which should make it perfectly logical, right?

**Comment by qooob** [comment]
Will be fix in version 15.01. Thanks!
