### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by zerberos** [qooob/authentic-theme#225]
Hi Ilia

I would like to contact you , but your website does not work due to SSL Certificate error.

I would need a custom modification in the authentic theme, I don't think it is terribly complicated.

Of course I would pay the work.

If you are interested please let me know how I can contact you.

Thanks!

**Comment by qooob** [comment]
How about karateka.org? Which browser, OS are you using? It's important for me not to have those errors!?

About your request, well, sure but it depends on what you need. You can email me at programming at rostovtsev dot ru.

**Comment by zerberos** [comment]
I use Chrome and try to access rostovtsev.ru - it shows an error. Obviously the SSL communication does not work, Chrome does not understand what your site sends.

Also Safary can not access, there is no error but Site does not load.

I will send an email immediately...

**Comment by qooob** [comment]
Here we go. The problem is that I use Chrome on phone and desktop - works just fine. What version on Chrome are you using?

**Comment by zerberos** [comment]
44.0.2403.157 (64-bit)

**Comment by zerberos** [comment]
I now tried FF also - with that it works fine. But still not in Chrome and Safari

**Comment by zerberos** [comment]
IE 11 also does not work.

**Comment by andreychek** [comment]
Howdy -- I wanted to mention that I wasn't able to reproduce that issue.

Using Chrome 44.0.2403.39 and 45.0.2454.78 on my desktop, I didn't receive any errors when browsing to rostovtsev.ru.

Also, the SSL checks out using this here:

https://www.sslshopper.com/ssl-checker.html#hostname=rostovtsev.ru

Do you happen to have a different PC you could try it from? I'm curious if maybe it's PC related.

**Comment by qooob** [comment]
By the way, thanks Andrey! ;)

Zerberos, do you happen by any chance use proxy in IE and Chrome, that has, so called paranoid setup, which kills all of the main headers?

**Comment by zerberos** [comment]
No proxy used here.

IE is on a different PC and in different network, and Website does not work there.

Safari and Chrome are on a Mac and do not work, FF (which works) also on this Mac

On PC in same network as Mac it works on Chrome, but also not in IE.

So I have tried on 3 Computers, on every one at least one Browser type does not work!

I have also done the SSLLABS check and there everything looks good.

Up to now I have no idea what the problem is...

**Comment by zerberos** [comment]
I have also tried to access both IPs directly through Chrome on Mac which also does not work.

I can send you the error message if you want but it is in german language.

**Comment by zerberos** [comment]
Here the error from Chrome on Mac (Screenshot)
![window_und_datenschutzfehler](https://cloud.githubusercontent.com/assets/6003314/9508166/bb49a8c6-4c53-11e5-86c0-ac5853f66f0b.jpg)

**Comment by qooob** [comment]
I have tested it on Mac. Yes. On Mac, in Chrome, there is a problem with 8192 SSL certificates. Not sure why it's happening. Safari loads alright.

About your question, well my friend, I take for programming $100/hour. This price doesn't include searching, learning, understanding of the issue/task - it only means clear programming when I know exactly what to do. Usually such work will be programmed in 2.5-3 hours but overall it might take 2-6 hours (including testing). I would say it would be around $250-$300. However, even if the price doesn't scare you I would not be able to start right now as I have urgent fixes to do over the theme and most of all, now I have a dead line about new features to integrate to beta.karateka.org, where bunch of people are going to work with within days.. So unless you will be kind waiting by the end of September, I would recommend you trying to hire some geeks on freelancer's websites. In case you want me to do this work, well, I would but please forgive me for now, I simple have no time at the moment, even though, I'm interested in doing what you want.

**Comment by zerberos** [comment]
I think $300 would be ok. I'll rather wait because I know you have long experience with Virtualmin. Other developers have no experience with that, so it will take them more time and the risk is bigger for me. Just let me know once you have time. Of course it would also be great if you find some time before end of September...

**Comment by qooob** [comment]
Alright, thank you! I will let you know.
