### ISSUE TITLE
UI Bug in Edit Virtual Server

### ISSUE THREAD

**Issue by singhdd93** [qooob/authentic-theme#226]
![screen shot 2015-08-27 at 7 15 43 am](https://cloud.githubusercontent.com/assets/2651445/9510633/c138baa0-4c8b-11e5-8750-6e87a41fb3de.png)
This is what I get in Enabled features on latest version of theme. I am using latest stable webmin + virtualmin. 
This happens both in Firefox and Chrome on Mac. (Dont have any other OS to try)

BTW Thanks for a great theme

**Comment by qooob** [comment]
Upps. Confirmed. I will fix it shortly! Thanks! I happens in all OS/browser.

**Comment by qooob** [comment]
This bug is actually global so thanks for pointing out.

**Comment by qooob** [comment]
Will be fixed in version 15.01

**Comment by singhdd93** [comment]
thanks
