### ISSUE TITLE
Reboot warning after updates

### ISSUE THREAD

**Issue by tbnv** [qooob/authentic-theme#227]
Hello,

Does this warning depend on the Authentic theme or Webmin itself?

`Warning!
Recent package updates (such as a new kernel version) require a reboot to be fully applied`

The server has already been rebooted, but not from Webmin.

When we upgrade the kernel, we usually do it from the command line, and reboot from the command line as well. But it seems it's not taken into account for that warning.

**Comment by qooob** [comment]
Hm. Well it has nothing to do with the theme. Webmin does it. I would think that this message goes away after you do manual update and then refresh (green button) the system info or just wait for 5 minutes.

Tell me, by the way. How do you reload kernel from cmd?

**Comment by tbnv** [comment]
It's a DigitalOcean server. Dist upgrade from command line, choose new kernel in DO interface, reboot server from command line.

Thanks for the information.

**Comment by qooob** [comment]
So did it work? Did the message go away?

**Comment by andreychek** [comment]
Howdy -- if you're using Ubuntu/Debian, and the "/var/run/reboot-required" file exists, Webmin/Virtualmin will notify you that a reboot is required.

That particular file is added by apt during the package update process, Webmin/Virtualmin just checks to see if it exists.

However, some things can be cached on the System Information screen.  It's possible that the Status Collection process hasn't run yet to update the page ("refresh" as Ilia suggested should help with that).

**Comment by tbnv** [comment]
No it didn't work. I gave up and restarted the server from Webmin. :wink:

**Comment by qooob** [comment]
I see. Next time you could start from restarting Webmin first. Might have worked. ;)
