### ISSUE TITLE
Interface hangs on OpenVPN Plugin

### ISSUE THREAD

**Issue by jzielke-nli** [qooob/authentic-theme#228]
When configuring OpenVPN using the webmin plugin and creating a new VPN Server using a configured CA, the interface hangs in case any part of the server configuration form is filled out wrong or has missing values. The interface shows a spinning circle forever but is not showing any errors which appear in the standard theme.

**Comment by qooob** [comment]
Which version of the theme are you using?

If latest, 15 please be kind step by step describe an issue so I could reproduce it.

**Comment by jzielke-nli** [comment]
I'm using the latest one. First I create a CA, which works fine and appears in the Certification Authority List. Then I switch to the "VPN List" section and click on "New VPN Server" having the created CA selected in the drop-drown menu above that button. The following form then let's you create a VPN server using all it's configuration possibilities. But when you for example leave a required field blank or or enter a wrong value, the theme just keeps spinning without showing the error (which would normally appear in a box at the top of the page in the standard-theme).

**Comment by qooob** [comment]
The problem is that I need to configure openvpn to even start it. So far could you please test it with release candidate 15.01 (it's safe to try, will not hurt in any way), and I made a lot of changes there related to page loader.

Maybe the problem will solve its self.

Please clear cache and restart your both Webmin and the browser after updating the theme (what is your browser by the way?)

https://rostovtsev.ru/pub/src/authentic/15.01b/authentic-theme-latest.wbt.gz

**Comment by jzielke-nli** [comment]
Thanks for the link. I upgraded to the latest RC and deleted chrome's cache but stil the same issue. If you create a new VPN server with garbage data in one of the configuration fields (for example IP-Address/Gateway "foo.bar" instead of a correct IP, the spinning wheel appears and the red bar at the top moves from left to ride for 5 seconds and then nothing happens.
![bildschirmfoto 2015-08-29 um 12 09 31](https://cloud.githubusercontent.com/assets/13448042/9561455/e8a2ae04-4e46-11e5-8237-14a8f0146590.jpg)

**Comment by qooob** [comment]
I don't have anything in `/etc/init.d/openvpn` and I get `Command Execution Error` on start. Any quick way to run the service so I could try creating New VPN server, as I don't have this button? It's all I got:

![screenshot from 2015-08-29 13-22-39](https://cloud.githubusercontent.com/assets/4426533/9561496/1045e714-4e51-11e5-9343-6182ea511949.png)

**Comment by qooob** [comment]
..ok started it.. testing..

**Comment by qooob** [comment]
.. ok.. now I can't create new server as it says `No server keys configured`, however I did configure them. Honestly, I don't like the way this module build. It has no Webmin footer and doesn't use Webmin API properly. 

Is there a way to ask developers to change module to be properly complient with Webmin. It hasn't been updated for 2.5 years?

Why not just clicking ESC key when this error happens?

**Comment by jzielke-nli** [comment]
If I would have known that esc is an option I would have used it. Well it's working with the latest standard-theme so I thought it sticks to the standards of webmin.

Contact: http://www.openit.it/index.php/en/contatti

**Comment by qooob** [comment]
It really doesn't. For instance, there is no footer. .. and other elements look broken/not nice. I will try to fix it a bit later!

**Comment by qooob** [comment]
Ok, I managed to emulate this module and I fixed the error you were talking about. Will be fix in 15.51.

**Comment by qooob** [comment]
Please update to 15.51

**Comment by jzielke-nli** [comment]
Thank you very much for working on that issue, even if it wasn't your interface being the culprit.  :-)

**Comment by qooob** [comment]
You're welcome!
