### ISSUE TITLE
JSON text must be an object or array: HTTP/1.0 500 Perl execution failed Server

### ISSUE THREAD

**Issue by unixjeff** [qooob/authentic-theme#230]
When loging in it takes me to a blank page, when i change the theme in the console loads just fine, i removed it and reinstall in and still no luck. any suggestions?

not sure if that error is related
**
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.760 Date: Mon, 31 Aug 2015 06:33:27 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close 
Error - Perl execution failed
JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /usr/share/webmin/authentic-theme/authentic-lib.cgi line 868.

**Comment by qooob** [comment]
Hmm. I see. Probably this fix will make it work.

Open line 868 and replace this line

```Perl
$fc = decode_json( $f =~ /\{(?:\{.*\}|[^{])*\}/sg );
```

with:

```Perl
my ($f) = $f =~ /\{(?:\{.*\}|[^{])*\}/sg;
my $fc = decode_json( $f );
```

Works now?

**Comment by unixjeff** [comment]
Perfect that worked!

**Comment by qooob** [comment]
Alright, thanks!

**Comment by qooob** [comment]
Please update to 15.51
