### ISSUE TITLE
Cloudmin - Graphical Console Size

### ISSUE THREAD

**Issue by DJFraz** [qooob/authentic-theme#231]
While attempting to use the graphical console in Cloudmin, the console displays very small and cannot be resized, nor can it be expanded to full screen. If you need to see the rest of the screen, you must scroll up and down.

![gc](https://cloud.githubusercontent.com/assets/13461917/9587388/33b77e24-4fd7-11e5-8c7a-68b4b5e87bd8.png)

Edit - This is the latest available version of Authentic.

**Comment by qooob** [comment]
Can you please open Chrome DevTool F12 ( in case it's Chrome) and hover on the element trying to debug it? Try to on the right enter the `min-heigh` on the container. I have never seen that Flash/Java Console. Why not using text one? I remember I was making it precise.

**Comment by DJFraz** [comment]
I had to install off of an ISO. There is no image for this particular OS.

![gc](https://cloud.githubusercontent.com/assets/13461917/9587997/786933fc-4fda-11e5-85cf-d47ea5d34e51.png)

On this particular object line, I changed the height from 85% to a set pixel height and it made it look just fine.
````
<object id="Flashlight" width="100%" height="85%" type="application/x-shockwave-flash" data="flashlight/Flashlight.swf">
````

**Comment by DJFraz** [comment]
Here is the Flash console itself
![gc](https://cloud.githubusercontent.com/assets/13461917/9588160/82bf42a0-4fdb-11e5-8b29-81cdb344b342.png)

**Comment by DJFraz** [comment]
Here is the Flash console itself

![gc](https://cloud.githubusercontent.com/assets/13461917/9588206/c0a95498-4fdb-11e5-80ef-91c816a0d91d.png)

**Comment by qooob** [comment]
Can you try adding to the theme extension JS the following:

```JS
$('body.server-manager p > object').unwrap();
```

You could also run this in the console, before that changing the target to from `top frame` to `page`.

**Comment by qooob** [comment]
Don't forget to clear cache. When __console is opened__ try holding the reload button and choosing 3 option from the dropdown.

**Comment by DJFraz** [comment]
Added that to the Theme extensions JS under theme options and that did not work. It still displays as it did previously.

**Comment by qooob** [comment]
Can you trying again selecting object (first red circle) tag and try adding to the object (see second circle) some attributes, like:

```CSS
height: 400px !important;
```

or


```CSS
height: 600px !important;
```
or
```CSS
min-height: 600px !important;
```
![c0a95498-4fdb-11e5-80ef-91c816a0d91d](https://cloud.githubusercontent.com/assets/4426533/9588797/ce6b3a4a-5032-11e5-85b6-18ed35164a07.png)

**Comment by qooob** [comment]
..ohh.. so it works if you change it into pixels? (didn't see you post above)..ok try this code.

```JS
$('body.server-manager p > object').parent('p').attr('style', 'display: block; height: 400px');
```

P.S. Can you also please tell me the name of the right frame (`server-manager/.....`). You can do this by seeing the `frame content` using the right mouse click on the right frame.

**Comment by DJFraz** [comment]
Yes, pixels. Both options from your last posts work. I went with the most recent in the Theme Extensions file, currently. I sized it to `650px`.

The name of the right frame is `/server-manager/gvnc.cgi`

Again, thank you for your assistance and timely responses.

**Comment by qooob** [comment]
Alright, thank you! Final test please. Remove all previously used `css` and `js` codes. Then add in js extension:

```JS
if ($current_page_full == $_____link_full + "/server-manager/gvnc.cgi") {
    $('body.server-manager p > object').parent('p').attr('style', 'display: block; height: ' + parseInt($(window).outerHeight() / 1.3) + 'px');
}
```

Don;t forget to reload cache.

**Comment by DJFraz** [comment]
It allows the console to be larger, but leaves a big gap under it. I'm wondering if the console already has a set size, but the capsule that it is in is forcing its size to be smaller?

![gc](https://cloud.githubusercontent.com/assets/13461917/9589760/56b40e8e-4fe5-11e5-9367-5379c9c52313.png)

**Comment by qooob** [comment]
How about this then:

```JS
if ($current_page_full == $_____link_full + "/server-manager/gvnc.cgi") {
    $('body.server-manager p > object').css('height', '100%').parent('p').attr('style', 'display: block; height: 100% !important');
}
```

**Comment by DJFraz** [comment]
That made it small again. If I change it slightly then it works.
````
if ($current_page_full == $_____link_full + "/server-manager/gvnc.cgi") {
    $('body.server-manager p > object').css('height', '100%').parent('p').attr('style', 'display: block; height: ' + parseInt($(window).outerHeight() / 1.3) + 'px');
}
````

**Comment by qooob** [comment]
Ahh ok, better idea:
```JS
if ($current_page_full == $_____link_full + "/server-manager/gvnc.cgi") {
    $('body.server-manager p > object').css('height', '100%').parent('p').attr('style', 'display: block; height: ' + parseInt($('.panel-body').outerHeight()) + 'px');
}
```

Better?

**Comment by DJFraz** [comment]
Caused it to shrink again. This is exactly what I'm using this second and it works perfect here:
```javascript
if ($current_page_full == $_____link_full + "/server-manager/gvnc.cgi") {
    $('body.server-manager p > object').css('height', '100%').parent('p').attr('style', 'display: block; height: ' + parseInt($(window).outerHeight() / 1.4) + 'px');
}
```

Note the `/ 1.4` is left.

**Comment by qooob** [comment]
I don't understand why `.panel body` makes it shrink. Will check.

**Comment by qooob** [comment]
Alright, now I got it. I emulated that flash part. `$('.panel-body').outerHeight()` will not work obviously! :)

Yes, you last example looks perfect. Will fix it soon! Thanks!!

**Comment by qooob** [comment]
Please update to 15.51 and don't forget to remove the code from custom scripts.

**Comment by DJFraz** [comment]
Excellent! Thank you, sir!

**Comment by qooob** [comment]
:+1:
