### ISSUE TITLE
alignment dashboard graphs not correct

### ISSUE THREAD

**Issue by jorgvloet** [qooob/authentic-theme#233]
The allignment of the graphs on the dashboard page isn't correct. This problem only concerns FireFox, when opened in Chrome the alignment is correct.
See image.

![2015-09-02_17-16-36](https://cloud.githubusercontent.com/assets/7492610/9635395/9645d78c-5196-11e5-80bd-0e4626c15fb3.png)

**Comment by qooob** [comment]
That is strange. I never noticed it. Can you please clear browser's cache and restart the browser? Also check that you haven't put any wrong code into extensions?

This video-screencast will shows that it can't be reproduced on my side:
rostovtsev.ru/pub/src/authentic/15.51/issue_233_dashboard_charts.webm

**Comment by jorgvloet** [comment]
I have cleared the cache, disabled all browser plugins and the problem still isn't over.
The only difference is the browser, I said that is was in Firefox, I need to say that it is in Firefox Developer edition (42.0a2 (2015-09-02)) when I open webmin in the normal Firefox then the problem isn't there

**Comment by qooob** [comment]
Then don't worry about that!
