### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by j0bb13** [qooob/authentic-theme#234]
Similiar issue as #103. The ordering seems to be off when I go to "List Virtual Servers" and I configured to show Total quota and Total used. 
The Virtualmin Framed Theme has the same issue, so I don't know if it is a Virtualmin issue or a theme issue. Isn't there a default ordering algorithm somewhere in Virtualmin that's used for lists?

![total used ordering](https://cloud.githubusercontent.com/assets/2331451/9659060/3f518f94-524e-11e5-88c0-eda75d1b4227.png)

Sorting does work at the Edit Users list (which was #103) and at Webmin -> System -> Disk quota:

![quota ordering](https://cloud.githubusercontent.com/assets/2331451/9659134/c30b392a-524e-11e5-9500-ff901c75434d.png)

**Comment by qooob** [comment]
I think I know why it's happening. I will send you the patch to try a bit later. Stay tuned.

**Comment by qooob** [comment]
After investigating on the issue, it appears that I should not be fixing it. It should be done in Virtualmin by adding label `bytes`. It should be `0 bytes` not just 0.

**Comment by jcameron** [comment]
Do you have an example of a page in Webmin that is showing "0" instead of "0 bytes" ?

**Comment by qooob** [comment]
It's in Virtualmin. Can be seen in the first picture of this post. (Marked red, column Total Used)

**Comment by jcameron** [comment]
I don't see "0" in that list though. Also, Webmin already uses "0 bytes" when printing a nicely formatted size of 0 : https://github.com/webmin/webmin/blob/master/web-lib-funcs.pl#L8373

**Comment by qooob** [comment]
Jamie, `virtual-server-lib-funcs.pl`, line 3432:


```Perl
# Quota used
if ($d->{'alias'} || $d->{'parent'}) {
        # Alias and sub-servers have no usage
	push(@cols, "0");
}
```

`push(@cols, "0");` should be `push(@cols, &nice_size(0));`

**Comment by jcameron** [comment]
Doh! I don't know how I missed that - I'll fix it in the next release.
