### ISSUE TITLE
Link cannot be clicked in ConfigServer Security Firewall temporary IP entries

### ISSUE THREAD

**Issue by jjozsi** [qooob/authentic-theme#238]
![screen shot 2015-09-08 at 09 55 24](https://cloud.githubusercontent.com/assets/14176641/9730755/903acd2e-5610-11e5-9096-7abeac4fd34b.png)

The link to perform *Flush all temporary IP entries* is not clickable, hence it's impossible to flush the entries (or do anything about them)

**Comment by qooob** [comment]
I see. I just tried this in Chrome it it's working and I can see the icon. Do you use Firefox by any chance?

**Comment by jjozsi** [comment]
I use Safari 8.0.8 on OSX Yosemite.

**Comment by qooob** [comment]
I see. I will test it and fix it in next small release. So far you can use CLI to do it running `csf -tf` or on the main page to flush all blocks. Thanks for reporting!

**Comment by jjozsi** [comment]
Thanks a million, the CLI command helped. And thanks for the great theme anyway!

**Comment by qooob** [comment]
You're welcome!
