### ISSUE TITLE
При клике на "PHP 5.x configuration" переходит в Webmin

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#239]
1. Открыть Virtualmin
2. Выбрать сайт
3. Раскрыть Service\PHP 5.3 configuration
https://xxxxx:10000/phpini/list_ini.cgi?file=/var/www/Ftest/etc/php5.3/php.ini

Ожидается, что меню останется не измененным
Фактически меню изменяется (Webmin\Othe\PHP Configuration)

**Comment by qooob** [comment]
Ах, да! Понял! Исправлю! Спасибо что сообщили!

**Comment by qooob** [comment]
Посмотрите апдейт. Очистите кэш после замены файла в теме: https://github.com/qooob/authentic-theme/raw/master/unauthenticated/js/authentic.min.js

**Comment by Romich777** [comment]
![php](https://cloud.githubusercontent.com/assets/14110152/9771526/7eff2b6a-573f-11e5-9c55-ffc79b5af4ed.PNG)
В момент первого выбора и загрузки - все ок.
После загрузки все варианты выглядят выбраными

**Comment by qooob** [comment]
:) Понятно! Скажите, а какой URL (во всех 3 случаях - 5, 5.3 и 5.5) в правой части (в правом фрейме), если посмотреть right frame source?

**Comment by Romich777** [comment]
Извиняюсь, недопонял о "right frame source"

https://xxxxx:10000/phpini/list_ini.cgi?file=/var/www/Ftest/etc/php5/php.ini
https://xxxxx:10000/phpini/list_ini.cgi?file=/var/www/Ftest/etc/php5.3/php.ini
https://xxxxx:10000/phpini/list_ini.cgi?file=/var/www/Ftest/etc/php5.5/php.ini

**Comment by qooob** [comment]
А все, есть. Вы все правильно сделали. Можно было и с левого скопировать. Сапасибо. Попробую исправить. Никогда не ставил несколько версий PHP :)

**Comment by qooob** [comment]
Скоро, сегодня, выпущу апдейт. Все будет исправленно. Спасибо за сообщение!

**Comment by Romich777** [comment]
Спасибо за оперативность!

**Comment by qooob** [comment]
Придётся чуть задержать. Кое что еще нужно поправить. Скорее всего завтра.
