### ISSUE TITLE
Sysinfo.cgi line 46 error

### ISSUE THREAD

**Issue by jaxpr3394** [qooob/authentic-theme#240]
Hey,

Thank you for the awesome Webmin theme!  I love it!  When loading sysinfo, it gives the following error:

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.760 Date: Tue, 8 Sep 2015 23:36:57 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Undefined subroutine &WebminCore::list_combined_system_info called at /usr/share/webmin/webmin-1.760/authentic-theme/sysinfo.cgi line 46.

Line 46 of sysinfo.cgi reads:

my @info = &list_combined_system_info( { 'qshow', 1 } );

Any help would be greatly appreciated!  Thank you for your time!

**Comment by andreychek** [comment]
Howdy -- just to rule out that you aren't seeing something unusual, you may want to try restarting Webmin with this command:

/etc/init.d/webmin restart

If doing that doesn't help, do you see any other errors occurring in /var/webmin/miniserv.error?

**Comment by jaxpr3394** [comment]
Hey sorry it took so long for me reply!

I have tried restarting several times - both the server itself and Webmin.  As far as miniserv.error, I see the error that I mentioned in there - one for each time I tried to get it to work, and I also see

"Use of uninitialized value in string eq at /usr/share/webmin/webmin-1.760/acl/edit_user.cgi line 345."

In there if that helps at all?  (Unlikely?)

**Comment by andreychek** [comment]
Hmm, and just to verify -- if you switch back to the default theme, does the problem stop occurring?

There's a handful of folks who saw a similar issue back in February, the thread for that is here:

https://www.virtualmin.com/node/36096

I have a sneaking suspicion that the issue you're seeing isn't related to Authentic, though unfortunately we never did figure out what the root case was, and weren't ever able to reproduce the problem.

One other thought crossed my mind, what is the output of this command:

ps auxw | grep miniserv

**Comment by qooob** [comment]
There is a file `web-lib-funcs.pl` (in your case I think located in `/usr/share/webmin/..`). Make sure that it's same as on the Webmin repo and has `sub list_combined_system_info` string or `list_combined_system_info`.

Afterwards make sure to clear Webmin's cache. You can do it different ways. Easiest way to go to `Webmin->Webmin Configuration->Webmin Scheduled Functions`, tick those checkboxes (`cleanup_temp_files`, `scheduled_collect_system_info`) and click `Run Selected Functions Now`.
Don't forget to restart Webmin after all using CLI.


Further..
I don't know how did you install Webmin but having `webmin-1.760` on its path could be the possible cause. 
The other possible cause is that your Perl pointer, like '#!/usr/bin/perl' is wrong in case of manual installation. 

Reboot the system if nothing works.

I think it's just the cache issue. In case you use Chrome it's very possible. Open DevTools (F12) and then hold refresh button to make hard reset. After close and reopen your browser. Try other browsers, like Firefox.

**Comment by jaxpr3394** [comment]
@andreychek the output of that command is:
root          2710   0.0   1.5   19268 15548 ?          Ss    06:01     0:00  /usr/bin/perl  /usr/share/webmin/webmin-1.760/miniserv.pl  /etc/webmin/miniserv.conf
pi          7565   0.0   0.1     3560   1832  pts/0     S+     08:46     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn miniserv

@qooob let me look into everything that you suggested and I will get back with you; thank you both for the helpful responses!

**Comment by jaxpr3394** [comment]
@qooob I logged into my pi and replaced my web-lib-funcs.pl file with the one located on the repo and that did the trick!  Thank you both for your help; I love the theme and was dying to use it!  For good measure, I cleared the cache as well.

Are there any other files that you would recommend me pull from the repo?

**Comment by qooob** [comment]
:) glad it helped. You must pull all of the files really or better install an rpm or other pre-build package. Good luck! ;)

**Comment by jaxpr3394** [comment]
Okay; I installed it using the pi's package manager for anyone else wondering that may be reading this facing the same problem.  I will do as instructed, @qooob.  Thank you!
