### ISSUE TITLE
Проблемы с кодировкой

### ISSUE THREAD

**Issue by kry4a** [qooob/authentic-theme#241]
Здравствуйте! При входе в Webmin меню отображается корректно. Если перейти на вкладку Virtualmin а затем вернуться обратно в Webmin слетает кодировка меню.

Так же, некорректная кодировка в настройках темы.
Скриншот прикрепил.

![encoding error](https://cloud.githubusercontent.com/assets/14092668/9815281/7b946d14-589d-11e5-8a67-1dbb8e0ed3fa.jpg)

**Comment by qooob** [comment]
Вам в настройках Webmin Configuration->Language нужно выбрать язык в формате UTF8.

**Comment by kry4a** [comment]
Стоит Russian (RU.UTF-8), пробовал после установки чистить кеш и пр. - к сожалению не помогло.

**Comment by kry4a** [comment]
upd. Не заметил пункт меню Webmin -> Сменить язык и тему, там указал RU-UTF8, теперь все хорошо со страницей Webmin и с настройками темы - везде локализованные значения. Остались только два пункта на странице Virtualmin.

Прошу прощения за ошибочную информацию в предыдущемо ответе.

![test](https://cloud.githubusercontent.com/assets/14092668/9824972/1df9f886-58d9-11e5-9be6-0d51b8543719.png)

**Comment by qooob** [comment]
Да, все правильно! Именно это я только что и писал! Хорошо! Спасибо, что сообщили. Те заначения на странице Virtualmin вам лучше добавить самостоятельно и отправить в https://github.com/webmin/webmin, они не имеют отношения к теме.

Также далеко не все [значения для настроек темы](https://github.com/qooob/authentic-theme/blob/master/lang/ru.UTF-8) переведены (локализованны) на русский. Если есть желание и возможность перевести, милости прошу. А то я все ниак не доберусь..

Удачи.

**Comment by kry4a** [comment]
Спасибо! И спасибо за тему, приятно с ней работать! Удачи!
