### ISSUE TITLE
Webmin 3rd Party Module Custom Link 1.5 fails to open

### ISSUE THREAD

**Issue by sn1999** [qooob/authentic-theme#242]
If you add the 3rd Party Module **[Custom Link 1.5](http://www.webmin.com/cgi-bin/search_third.cgi?search=custom+link)** the links won't open, even if set to open in new Tab.
SHIFT + click however works.

Seems to be the same issue as in [#130](https://github.com/qooob/authentic-theme/issues/130)

**Comment by qooob** [comment]
Thanks. Will fix it version 16.
