### ISSUE TITLE
Navigation in Clone of Filemin not possible

### ISSUE THREAD

**Issue by sn1999** [qooob/authentic-theme#243]
If you clone the Filemin Module (Webmin Configuration -> Webmin Modules -> Clone) you can't Navigate in the created Clone.
If you're clicking on a directory all entrys turn gray and simply stay that way.
Tested in Firefox and Opera.

**Comment by qooob** [comment]
My friend, that just won't work! Sorry.

**Comment by qooob** [comment]
However.... when you clone it it makes it's name filemin2.... hm.. this might work.. let me see.

**Comment by qooob** [comment]
..ok.. that was a lot to change! As long as Filemin module contains `filemin` label - it will be working. 

It be fixed in version 16!!
