### ISSUE TITLE
Button Color in Custom Commands Module

### ISSUE THREAD

**Issue by sn1999** [qooob/authentic-theme#244]
Not quite sure if it is a bug or intended.
If you create a Custom Command including **Stop** (case-sensitive) in the Description the button of this command turns orange (css class btn-warning is added).
If it is a Bug, it would be great if we had a config option to add specific colors if a specific String is used in the buttons description of Custom Command.
As an example:
Set all custom commands containing 'Start' to green (by selecting css class btn-success or adding a own css class to it).
This would be awesome if you use Custom Commands to Start/Stop Gameservers/Teamspeak.
![customcmd](https://cloud.githubusercontent.com/assets/14289015/9870785/48ca6fd8-5b8f-11e5-8202-6417927643c4.png)

**Comment by qooob** [comment]
I don't support yet this mode of Custom Commands. I will in the future but not just right now. I had the discussion about this with Jamie (Webmin dev) and I keep this in my to-do list.

Meanwhile, you could get what you want, if you change the mode in settings:  `Module Settings->Main page shows->Links to commands`.

Then you will see a nicer list of custom commands.

To give color to it, use theme extension CSS part and add the following code:

```CSS

body.custom a[href="view.cgi?id=1438250349"] {
	color: red
}

body.custom a[href="view.cgi?id=1438269117"] {
	color: green
}
```

It's a nice idea! Thanks!
