### ISSUE TITLE
Firewall CSF - Firewall Profiles

### ISSUE THREAD

**Issue by manukieli** [qooob/authentic-theme#245]
Hi,

They is a small issue to the Firewall Profiles section into Firewall CSF.
The select input of Restore Backup and Compare Configurationes are to small.
Will be better to put the height to 200 or 250px.
![2015-09-15_15-51-36](https://cloud.githubusercontent.com/assets/14294794/9878280/2a328b22-5bc2-11e5-9678-1797ce1273de.jpg)

**Comment by qooob** [comment]
Alright, will fix it in version 16! ;)

**Comment by manukieli** [comment]
Ok, thank you.
