### ISSUE TITLE
Perl execution error

### ISSUE THREAD

**Issue by Deepcuts** [qooob/authentic-theme#246]
hello,

Thank you for the theme.

When I click the Logout button in Usermin, I receive the following error:

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.670 Date: Fri, 18 Sep 2015 00:15:17 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

Undefined subroutine &main::print_session_login_head called at /usr/share/usermin/authentic-theme/session_login.cgi line 75.

**Comment by qooob** [comment]
This caused because of stuck cache. You need to restrat your Usermin. Possibly refreshing system info page in Webmin as well.
