### ISSUE TITLE
Undefined subroutine &main::parse_virtual_server_access_level called at /usr/libexec/usermin/authentic-theme/index.cgi line 144

### ISSUE THREAD

**Issue by chriswheeler** [qooob/authentic-theme#248]
I've just upgraded to Version 16 and get the following message when logging in to Usermin (with Authentic Theme set for Usermin)

### Error - Perl execution failed

Undefined subroutine &main::parse_virtual_server_access_level called at /usr/libexec/usermin/authentic-theme/index.cgi line 144

**Comment by qooob** [comment]
This is stuck cache. Restart both Webmin and Usermin.

**Comment by chriswheeler** [comment]
I've just restarted webmin and usermin - but still get the same error.

**Comment by qooob** [comment]
The problem has been happening many times. I deleted this function from release 16. Your server uses the old theme's files.

You could manually list through the theme directory to make sure that you see version 16 in headers' comments. If not, then something went wrong and you need to unpack theme files manually. If files are ok, then rebooting the server might help.

**Comment by qooob** [comment]
Did it work?

**Comment by chriswheeler** [comment]
Yes, rebooting the server fixed it...
