### ISSUE TITLE
Usermin load bug

### ISSUE THREAD

**Issue by j0bb13** [qooob/authentic-theme#249]
First of all: Restarting Usermin/Webmin didn't solve this, but rebooting the server got me to Usermin again. But now Usermin reports:

    Authentic Theme 13.05. Latest available release 16.00

Prior to the 13.05 notice and server reboot Webmin functioned properly with 16.00, but Usermin gave this error when trying to open it in incognito mode:
![2015-09-22 1](https://cloud.githubusercontent.com/assets/2331451/10016151/42f53642-6125-11e5-9156-7d962359975b.png)

    HTTP/1.0 500 Perl execution failed Server: MiniServ/1.670 Date: Tue, 22 Sep 2015 10:24:06 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
    Error - Perl execution failed

    Undefined subroutine &main::print_session_login_head called at /usr/share/usermin/authentic-theme/session_login.cgi line 75.

And this if I was already logged in to Webmin and go to Usermin:
![2015-09-22](https://cloud.githubusercontent.com/assets/2331451/10016136/22811e76-6125-11e5-9a4f-45af360f989d.png)

    Logged in:
    Error - Perl execution failed

    Undefined subroutine &main::parse_virtual_server_access_level called at /usr/share/usermin/authentic-theme/index.cgi line 170.

**Comment by qooob** [comment]
There were just recently an issue about it: [#248](https://github.com/qooob/authentic-theme/issues/248)

You must make sure that the Usermin version of the theme is also update. Go to Webmin->Usermin Configuration and update the theme manually from the link below:

https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz

**Comment by j0bb13** [comment]
Aah, missed that one. I assumed both Webmin and Usermin were updated when I clicked update on the Authentic theme, but this clears things up :)

It's weird then that restarting the server fixed it, since that didn't update the Authentic version on Usermin... Aaah well, it works again. Thanks!

**Comment by qooob** [comment]
Your welcome! I maybe will add automatic update for Usermin as well.

**Comment by chriswheeler** [comment]
+1 for including auto update of Usermin theme :)

**Comment by qooob** [comment]
+1 as well! ;)
