### ISSUE TITLE
Mail alias.

### ISSUE THREAD

**Issue by ai-hosting** [qooob/authentic-theme#251]
When a normal user creates alias in virtualmin an error is displayed. 
Creating alias as root doesn't give errors and using some other theme (old-theme) also no errors.
![182e8ea95fce59576c1c2899aee0198c](https://cloud.githubusercontent.com/assets/11756720/10025304/e76cad6e-615b-11e5-86ab-c4217fe387a4.png)
![51eb78e35d8225ef80a24fbb17481543](https://cloud.githubusercontent.com/assets/11756720/10025305/e7a31af2-615b-11e5-80ae-d34a024e8168.png)

**Comment by qooob** [comment]
I'll take a look.

**Comment by qooob** [comment]
Hey, pal! ;) You're not using Authentic Theme! Go grab Authentic Theme and try again! I remember I was fixing it months ago!

https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz

**Comment by qooob** [comment]
I double checked.. in Authentic it works just fine when login in as user and root, using _Basic mode_
or _Advanced mode_.

**Comment by ai-hosting** [comment]
thanks, normaly the default theme is authentic and the customer changed 
it.  We removed the other buggy theme.
thanks for the quick support.

Op 23-9-2015 om 09:58 schreef Ilia Rostovtsev:

**Comment by qooob** [comment]
You're welcome. Make sure please to run version 16.00. It's fully reworked in comparison with 15.
