### ISSUE TITLE
Bind module's zone won't open in Internet Explorer 11

### ISSUE THREAD

**Issue by binagun** [qooob/authentic-theme#252]
When the bind module's Display options, Display domains as is set to list. the theame fails to display an zone, when set to icons zone opens normaly

**Comment by andreychek** [comment]
Howdy -- I wasn't able to reproduce that issue using Authentic version 16.00.  I tried both the list and icon mode, and saw the zone files.

Which Authentic version is it that you're using there?

**Comment by binagun** [comment]
version 16

**Comment by andreychek** [comment]
Nuts! Could you share a screenshot of what you do see on the BIND module screen when this issue occurs?

Also, do you see any errors or warnings in /var/webmin/miniserv.error?

Lastly, do those zone files show up as expected when using the Virtualmin Framed Theme?

**Comment by qooob** [comment]
This is strange as I always use this mode and would surely noticed a problem. 

Can you please make a video-screencast to show us exactly what you got so I could easily understand of what is going on? 

What browser/OS are you using? Did it happen after upgrade to version 16 or it was happening before? Did you try restarting Webmin or rebooting the machine in case it didn't work?

**Comment by binagun** [comment]
im using windows 7 pro x64 with ie 11. As for the video, i just made an short clip but i dont know where to put it its only 18MB but i can only add 10 .
most of the systems had the theme fresh installed.
as for the os of the systems 2X CentOs 6.7 x64 and 2X i686

**Comment by qooob** [comment]
You can post it to YouTube as private video or make a screenshot. Also please try other, old theme, like Grey Theme. At last try to use Chrome or Firefox on Windows.

My personal, strong recommendation is to stay away from IE with all means. Microsoft is really bad in making browsers.

**Comment by binagun** [comment]
https://youtu.be/nMzIVpMpz1M
short video.

as for witch browser, ie isnt bad these days but i do also have firefox and will test it.

**Comment by binagun** [comment]
well suprisingly it does work with firefox, when loading a zone while running the developer tools of IE 11 it does shouw 2 errors refencing authentic.min.js line 6 column 40 and package.min.js line2 column 38687 if that helps

**Comment by qooob** [comment]
I see now. I think I remotely understand why it's happening. I bet if you use Chrome you will get two amazing advantages. 1. Your Webmin will work faster 2. Things will work flawlessly.

Meanwhile you could dismiss the loader by hovering on it and clicking cross button, to close it or simply clicking eclscape key.

You should open console and post error message that pops up there, when you trying to enter a zone.

Can you also check other modules, like Bootup and Shutdown, for instance, do you face same issue when using IE?

**Comment by binagun** [comment]
okee ather clicking away the loading circle i found that it gave me an error about trusted referals, when referal checking is disbled it loads just fine on ie, and indeed boot up and shutdown gives the same problem

**Comment by qooob** [comment]
..I will try to fix it by next release if I can reproduce it on my debug IE.

**Comment by qooob** [comment]
What do you mean by 'trusted referals'?

**Comment by binagun** [comment]
to give you the message webmin tels me

Warning! Webmin has detected that the program https://192.168.50.1:16689/init/edit_action.cgi?0+dhcpd was linked to from an unknown URL, which appears to be outside the 

Webmin server. This may be an attempt to trick your server into executing a dangerous command.
Make sure your browser is configured to send referrer information so that it can be verified by Webmin.

Alternately, you can configure Webmin to allow links from unknown referers by :
•Login as root, and edit the /etc/webmin/config file.
•Find the line referers_none=1 and change it to referers_none=0.
•Save the file.

**Comment by qooob** [comment]
Oh, I see now. I will try to fix it but I can't promises that it will be practically possible in IE. In few days, I will come back to you after testing.

**Comment by qooob** [comment]
Will be fixed in version 16.01

**Comment by qooob** [comment]
Please update to 16.01 and try again after clearing browsers cache in case things don't work. It should. Does it?

**Comment by binagun** [comment]
confirmed working, thanks

**Comment by qooob** [comment]
:+1:
