### ISSUE TITLE
Local Disk Space [%] - System information

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#253]
How does the Local Disk Space [%] calculate the size?

on my server I have 22% right now.
however, I have 2 partitions:
/ (33%)
and  
/home (19%)

Is this a bug in calculating?

Is possible to shows on the main page either just / or /home value? or both seprate?

Please advise
![stat-serv2](https://cloud.githubusercontent.com/assets/7549566/10124175/88566344-6546-11e5-8735-66ca279bf7cd.png)

![stat-serv](https://cloud.githubusercontent.com/assets/7549566/10124180/9db7fd6a-6546-11e5-9068-bada9f0c7b8b.png)

**Comment by qooob** [comment]
Theme doesn't calculate the size. Webmin does it. In case you think it's wrong, please submit a ticket to [GitHub Webmin](https://github.com/webmin/webmin) and make a reference to this issue as well.

**Comment by sz00gun** [comment]
Thank you, is there any other "place" in Webmin what shows Local Disk Space [%] on the server? Do you know where does this value come from? (22% in my case)   is this an avg. of all partitions? or what? any idea?

PS. is possible to change the value in your theme to show only any specific partition?  eg. /  or /home?

**Comment by qooob** [comment]
You can see the reference in `authentic-lib.cgi` on line 861:

```Perl
# Disk usage
if ( $info->{'disk_total'} ) {
    ( $total, $free ) = ( $info->{'disk_total'}, $info->{'disk_free'} );
    my $percent = ( $total - $free ) / $total * 100;
    print_easypie_chart(
        $columns, $percent,
        (   ( $current_lang eq 'ru' || $current_lang eq 'ru.UTF-8' )
            ? $text{'body_disk2'}
            : $text{'body_disk'}
        )
    );
}
```

**Comment by andreychek** [comment]
Yeah Webmin should be adding up all available disk space, and all available free space -- and then determining the percent free based on those totals.

You can see individual partitions in Webmin -> System -> Disk and Network Filesystems.

**Comment by qooob** [comment]
Yes, all seems correct. You can't add up available disk space and get correct result. :) 

To check what you got, go to System Information page, find `Local disk space` and divide `(free/total) * 100` and you will get correct number, right? ;)

**Comment by sz00gun** [comment]
Correct, you are right, however it is not very handy information for me, My server was down for couple of hours yesterday, because stupid ConfigServer Security & Firewall version 8.05 saved so many reports to the: /root/Maildir/new/  and Webmin saved 12GB !!! of data to: /var/webmin/miniserv.error (including billions of lines including: "finished reading - shutting down socket") don't know why

My 20GB / partition had no free space ;( 

In my opinion Local Disk Space [%] indicator should shows any of partition, in my case eg.: / or /home

What do you think?

**Comment by qooob** [comment]
CSF really did that? What did Webmin really saved? What happened?

I don't know I think `Local disk space` percentage should show total in overall system. Otherwise it makes little sense. `Disk and Network Filesystems` can provide you with data per partition.

**Comment by andreychek** [comment]
Yeah you may want to open up a Webmin issue where Jamie can address the disk space problem you're referring to, where you can't see the space available on your various partitions from the System Status screen.

That said, you could always use Webmin to setup monitoring of your various partitions. That can be done in Webmin -> Others -> System and Server Status, and there you can setup a Disk Space monitor for your various partitions..

**Comment by qooob** [comment]
:+1:

**Comment by sz00gun** [comment]
I've done the monitor today... uffff

CSF had 4GB of reports, each report had 2KB, 22KB or 96KB - millions of files 
eg.: 
![1](https://cloud.githubusercontent.com/assets/7549566/10124503/4a580aae-654e-11e5-903a-0583b2f5b854.png)

more here: http://forum.configserver.com/viewtopic.php?t=8932
https://internetlifeforum.com/linux-forums/1670-lfd-*-suspicious-process-running-under-user-*/

I couldn't find any solution for 12GB file:  /var/webmin/miniserv.error 
![err](https://cloud.githubusercontent.com/assets/7549566/10124512/85ee22a6-654e-11e5-88be-f11da9cea374.png)

I still have this file - just 12GB, but after rar - less than 1 MB,

the content eg:
billion of lines:  !!!!!!
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket
finished reading - shutting down socket

finished reading - shutting down[26/Sep/2015:12:35:25 +0100] miniserv.pl started
[26/Sep/2015:12:35:25 +0100] Using MD5 module Digest::MD5
[26/Sep/2015:12:35:25 +0100] Perl module Authen::PAM needed for PAM is not installed : Can't locate Authen/PAM.pm in @INC (@INC contains: /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 13) line 1.
BEGIN failed--compilation aborted at (eval 13) line 1.
