### ISSUE TITLE
Firewall module - Activate at boot

### ISSUE THREAD

**Issue by albertovincenzi** [qooob/authentic-theme#255]
If in firewall module I set "activate at boot" to yes, once I save the setting, the flag is reverted to "no".
With the default theme I don't have the same issue

**Comment by qooob** [comment]
Confirmed. This bug is happening when in settings `Enable customized checkboxes and radio buttons` is enabled (default).

I will try to figure out the source of the problem and fix it by next release.

Thanks!

**Comment by qooob** [comment]
It is happening in all modules with `bootup.cgi` form, which is technically incorrectly build, having no  form data on the inside. It works for some funky reason with default checkboxes but not custom.

Add the following script in theme's extenison (JS) to fix this issue across all modules:

```JavaScript
if (t___wi.location != t__wi_p.location) {
     $('form[action="bootup.cgi"]').on('submit', function () {
          $(this).append('<input type="hidden" name="boot" value="' + $('input[name="boot"]:checked').val() + '">')
     });
}
```

In the future release I will add this to the package.

Thanks for reporting on this wild bug!

**Comment by albertovincenzi** [comment]
I'm having the same problem with last version of the theme.

**Comment by albertovincenzi** [comment]
17.84 on debian wheezy. I thought that was updated because didn't mentioned about a new version of the theme, then I set auto update check to on (default was off). Even if I set to auto update, I don't get the new version. Click on force update didn't solved.
I manually done it: downloaded 18.03 solved the problem but still don't notice the 18.04 update by autoupdate feature.

**Comment by qooob** [comment]
Update notice will work with the next Webmin release.

**Comment by qooob** [comment]
Or apply this fix:

https://github.com/webmin/webmin/issues/393#issuecomment-226986304
