### ISSUE TITLE
Postfix Header Checks loading error

### ISSUE THREAD

**Issue by SavageCore** [qooob/authentic-theme#257]
Upon clicking on Header Checks the following is printed to console

`Uncaught Error: Syntax error, unrecognized expression: label[for="d_/^Content-(Disposition|Type).*name\s*=\s*"?(.*(\.|=2E)(ade|adp|asp|bas|bat|chm|cmd|com|cpl|crt|dll|docm|exe|hlp|ht[at]|inf|ins|isp|jse?|lnk|md[betw]|ms[cipt]|nws|\{[[:xdigit:]]{8}(?:-[[:xdigit:]]{4}){3}-[[:xdigit:]]{12}\}|ops|pcd|pif|prf|reg|sc[frt]|sh[bsm]|swf|vb[esx]?|vxd|ws[cfh]))(\?=)?"?\s*(;|$)/ix"]
`

package.min.js?1551:8

The page infinitely spins and red loading bar is stuck at end.

**Comment by qooob** [comment]
As workaround, click ESC key or loader close button to dismiss loading page.

I will try to reproduce the issue a bit later.

**Comment by qooob** [comment]
What version of the theme are you using? I can't reproduce the issue? When I click on `Headers Check` all loads fine?

**Comment by SavageCore** [comment]
Version 15.51 

It only happens on one server with the following check:

`/^Content-(Disposition|Type).*name\s*=\s*"?(.*(\.|=2E)(ade|adp|asp|bas|bat|chm|cmd|com|cpl|crt|dll|docm|exe|hlp|ht[at]|inf|ins|isp|jse?|lnk|md[betw]|ms[cipt]|nws|\{[[:xdigit:]]{8}(?:-[[:xdigit:]]{4}){3}-[[:xdigit:]]{12}\}|ops|pcd|pif|prf|reg|sc[frt]|sh[bsm]|swf|vb[esx]?|vxd|ws[cfh]))(\?=)?"?\s*(;|$)/ix`

Perhaps it does not like the `"` near the end? `?"?\s*(;|$)/ix`

**Comment by qooob** [comment]
At first, please update the theme to 16.01. Then restart Webmin using console by running `/etc/webmin/restart` :) Try again and tell us what you got?

**Comment by SavageCore** [comment]
That fixes it :)
