### ISSUE TITLE
Comodo WAF module

### ISSUE THREAD

**Issue by madzoni** [qooob/authentic-theme#259]
Comodo waf webmin module in Servers menu is not loading. It loads with virtualmin framed theme though

more info about the module here: https://help.comodo.com/topic-212-1-514-5928-.html 

Thanks for this great theme!

**Comment by qooob** [comment]
Can you please provide download link from this module so I could test it?

**Comment by madzoni** [comment]
Here it is: https://waf.comodo.com/cpanel/cwaf_client_install.sh
Info: https://help.comodo.com/topic-212-1-514-5935-using-the-cwaf-agent.html
thanks

**Comment by qooob** [comment]
This script contains compiled part. I will not be able to install it. Please just pack the directory with your module and send it to me to the email. You can get my mail from the files  headers. The other oportinity is to open console and make video screencast while using your module.

**Comment by madzoni** [comment]
I notice if I close the loading gif the module loads, so that solves my problem

Thanks

**Comment by qooob** [comment]
I see why this happening. Try this fix. After putting it to the theme folder please clear cache and restart the browser.

https://rostovtsev.ru/pub/src/authentic/16.01/issue-259/init.min.js

**Comment by qooob** [comment]
Any luck?

**Comment by madzoni** [comment]
Where exactly I have to put this file? in the root folder? /usr/libexec/webmin/authentic-theme

**Comment by qooob** [comment]
Yes, but `unauthenticated/js`

**Comment by madzoni** [comment]
The problem remains, however in chrome I can see the loading gif and after I close it the module loads fine. In firefox I can not even see the loading gif. But I think I can manage with chrome, thanks

**Comment by qooob** [comment]
Is issue solved? Does it work? You should not see the loader (it's not the gif by the way, it's CSS)

**Comment by madzoni** [comment]
No unfortunately it did not solve the problem, I placed the file  init.min.js in theme´s folder, but no luck. I I said I can work around using chrome and closing the loading animation each time I need to use comodo waf, so no worries

**Comment by qooob** [comment]
In the themes folder? No, you should replace the exising `init.min.js` file in `/usr/libexec/webmin/authentic-theme/unauthenticated/js` folder.

**Comment by madzoni** [comment]
Yes, I copied the file to /usr/libexec/webmin/authentic-theme/unauthenticated/js, yet no luck

**Comment by qooob** [comment]
Cleared cache, restarted Webmin?

**Comment by madzoni** [comment]
I didn't start webmin (missed that!), will do that tonight and I´ll get back to you, many thanks.

**Comment by qooob** [comment]
It seems to be working fine on my machine! The loader must not even appear.

**Comment by qooob** [comment]
Ahh.. Hold on.. Maybe not.. Let me check again.

**Comment by qooob** [comment]
No, you're right. It happened to be a bit more complex. I will fully fix it (I hope) in 16.03.

So far, do a small test for me. Using latest script update (already installed above). Test expected behaviour using _Autocomplete_. For example start typing `comodo` and then hit enter. Do you get expected (working properly) behaviour across all browsers, right?

**Comment by qooob** [comment]
.. I meant in 16.02 :)

**Comment by madzoni** [comment]
Hi, searching for comodo I see auto complete "comodo waf", I press enter and I have the same result as going to Servers=>>Comodo Waf, in firefox nothing happens while in chrome it keeps loading until I press the close button, only then the module loads.

**Comment by qooob** [comment]
Yes, this is correct. Version 16.02 should fix all of that!
