### ISSUE TITLE
Drive temperatures

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#260]
Is possible to add Drive temperatures as in on the original theme to the authentic theme - System Information?
![ff](https://cloud.githubusercontent.com/assets/7549566/10264287/f8958b0a-69fe-11e5-95e5-8126c470ef7c.png)

**Comment by qooob** [comment]
Do you see drive temperature in default theme and don't in Authentic, all on the same machine?

**Comment by sz00gun** [comment]
My bad... the temp. is no showing on the SSD machine, on the HDD all looks OK.
