### ISSUE TITLE
Usermin logo 404 (File not found)

### ISSUE THREAD

**Issue by silenx** [qooob/authentic-theme#261]
Hello,
usermin got a 404 error on logo when setting it in webmin theme configuration.

Failed to load resource: the server responded with a status of 404 (File not found)
http://domain.tld:20000/images/logo.png 

![virtualmin1](https://cloud.githubusercontent.com/assets/14348822/10304342/d3bd9030-6c19-11e5-960e-5ee76ad09378.png)

**Comment by qooob** [comment]
This should not be the case. I just double checked it and it works expected way.

What is the console output of `ls -lsa /usr/libexec/webmin/authentic-theme/images/logo.png` and `ls -lsa /usr/libexec/webmin/authentic-theme`?

**Comment by silenx** [comment]
i don't have that path.
i have:
~# find / -name *logo.png* | grep authentic
/usr/share/webmin/authentic-theme/images/logo.png
/usr/share/webmin/authentic-theme/images/__logo.png
/usr/share/usermin/authentic-theme/images/__logo.png
/etc/webmin/authentic-theme/logo.png
/etc/usermin/authentic-theme/logo.png

I'm on Debian 8.2 .. virtualmin/webmin installed with virtualmin install.sh script

**Comment by qooob** [comment]
Seems to be my bad, you're right. I always used a _symlink_ to Authentic Theme installed in Webmin, this is why it was working. I will fix it in 16.02.

**Comment by qooob** [comment]
Thanks for reporting!

**Comment by silenx** [comment]
Thanks to you for this great UI

**Comment by qooob** [comment]
Actually, I think it's still working on my end. I misjudged the reason above.

What is the permissions rights on files. What is the output:

`ls -lsa /etc/webmin/authentic-theme`
`ls -lsa /etc/usermin/authentic-theme`
`ls -lsa /usr/share/webmin/authentic-theme`
`ls -lsa /usr/share/usermin/authentic-theme`

What theme version are you using??

**Comment by silenx** [comment]
http://pastebin.com/1CZhuEsC

Operating system	Debian Linux 8
Webmin version	1.760
Virtualmin version	4.18
Theme version	Authentic Theme  16.01

**Comment by qooob** [comment]
All seems fine. Do you have any errors in `miniserv.log`?

**Comment by silenx** [comment]
This log , on loggin into usermin:
[07/Oct/2015:10:58:19 +0200] "POST /session_login.cgi HTTP/1.1" 302 0
[07/Oct/2015:10:58:19 +0200] "GET /unauthenticated/js/settings.js HTTP/1.1" 200 1681
[07/Oct/2015:10:58:19 +0200] "GET /?mail HTTP/1.1" 200 6820

[07/Oct/2015:10:58:20 +0200] "GET /images/logo.png HTTP/1.1" 404 32   <----- 404 Here

[07/Oct/2015:10:58:20 +0200] "GET /unauthenticated/fonts/roboto/El-bgsteBznJNL5pgUfFLA.woff2 HTTP/1.1" 200 63104
[07/Oct/2015:10:58:20 +0200] "GET /sysinfo.cgi HTTP/1.1" 200 2236
[07/Oct/2015:10:58:20 +0200] "GET /unauthenticated/js/authentic.min.js?1601 HTTP/1.1" 200 226800

**Comment by qooob** [comment]
Did you try to restart Usermin/Webmin?

**Comment by silenx** [comment]
Yes of course..

i noticed this is miniserv.error when i login to usermin

sh: 1: mail: not found

Warning: something's wrong at /usr/share/usermin/authentic-theme/authentic.pl line 8.

Warning: something's wrong at /usr/share/usermin/authentic-theme/authentic.pl line 8.

[07/Oct/2015:11:05:20 +0200] [82.52.105.46] /images/logo.png : File not found

Warning: something's wrong at /usr/share/usermin/authentic-theme/authentic.pl line 8.

**Comment by qooob** [comment]
can you comment out (`#`) line 8?

**Comment by silenx** [comment]
i commented out line8: ( #warn $@; )

now in miniserv.error i got only

sh: 1: mail: not found
[07/Oct/2015:11:09:48 +0200] [82.52.105.46] /images/logo.png : File not found

**Comment by qooob** [comment]
That is so strange! What is the output of 
`ls -lsaZ /usr/share/webmin/authentic-theme/images`
`ls -lsaZ /usr/share/usermin/authentic-theme/images`

> sh: 1: mail: not found
You should install `mail` command to let notification features work.

**Comment by silenx** [comment]
http://pastebin.com/eyxP3cAy

**Comment by silenx** [comment]
I forgot two things:
on webmin/virtualmin Logo work. ( only usermin problem )
My usermin is in http ( not https )

**Comment by qooob** [comment]
I can not reproduce your bug :( Whenever I click save logo and reload Usermin, the logo automatically copied from `/etc/usermin/images` to `/usr/share/usermin/authentic-theme/images`.

You can make 2 workarounds:

1. Copy logo.png to theme directiry manually (oh by the way do you get any errors when running as root??)
`cp /etc/usermin/authentic-theme/logo.png /usr/share/usermin/authentic-theme/images/`

2. Create a symlink to Usermin theme, using Webmin copy of the theme:
`rm -rf /usr/share/usermin/authentic-theme`
`ln -s /usr/share/webmin/authentic-theme /usr/share/usermin/authentic-theme`

**Comment by silenx** [comment]
Thank you. 
number1 solution fixed ( copied by root )

**Comment by qooob** [comment]
No errors/warnings on the console?

**Comment by silenx** [comment]
i only have this in miniserv.error when i login/logout
Using a hash as a reference is deprecated at /usr/share/usermin/authentic-theme/session_login.cgi line 181.

and this on miniserv.log

[07/Oct/2015:11:47:31 +0200] "GET / HTTP/1.1" 401 1990
[07/Oct/2015:11:47:44 +0200] "POST /session_login.cgi HTTP/1.1" 302 0
[07/Oct/2015:11:47:45 +0200] "GET / HTTP/1.1" 302 5444
[07/Oct/2015:11:47:46 +0200] "GET /?mail HTTP/1.1" 200 6820
[07/Oct/2015:11:47:46 +0200] "GET /sysinfo.cgi HTTP/1.1" 200 2236

**Comment by qooob** [comment]
I see. Allright. I will keep this in mind. At the moment I believe this is system specific and I can not reproduce it. In case you have any other problems, just start a new issue please.

**Comment by 7starsone** [comment]
hello, how to add the logo on Usermin login page?

**Comment by qooob** [comment]
Just add it in Webmin and then `Ctrl+R` to reload the theme. It will appear in Usermin as well.

**Comment by 7starsone** [comment]
that works on Webmin/Virtualmin, but the logo for usermin is the original logo...

**Comment by 7starsone** [comment]
may be why I never used Usermin with your theme before?

**Comment by qooob** [comment]
All you need is to make sure that you have both 18.30 installed on Webmin and Usermin, then go to _Logo Control_ from Webmin and set the logo. It will just work after you hit safe.

Just tested it worked.

**Comment by 7starsone** [comment]
why usermin is 18.10 if authentic theme was updated? is it a bug?

**Comment by qooob** [comment]
Yes, there were some broken automatic updates. I'm aware. It's the last thing I'm going to fix before 18.31 release.

**Comment by 7starsone** [comment]
ok :-) thanks

**Comment by 7starsone** [comment]
I still see this, even after the 18.31 update and another click on Save into the logo control page...
![Image of usermin](http://i67.tinypic.com/2isbi87.jpg)

**Comment by qooob** [comment]
There are 2 different types of logos. For authenticated users and for not-authenticated.

If you think you did everything correctly then check if `/etc/usermin/authentic-theme` directory exists and writable. 

The workaround is to manually copy logo files there from `/etc/webmin/authentic-theme`.

**Comment by 7starsone** [comment]
that directory doesn't exist. Why? just /etc/usermin/authentic-theme as a file... but not directory

**Comment by qooob** [comment]
Probably it's symlink. Just create a dir and copy stuff there from `/etc/webmin/authentic-theme`
