### ISSUE TITLE
Highlighting text in custom commands file editor

### ISSUE THREAD

**Issue by MorningSleeper** [qooob/authentic-theme#263]
If one creates a custom command at Others > Custom Commands > Create a new file editor and then clicks on the newly created button to edit a file, when one selects some text, it is not highlighted as one would expect. Don't know if it is this theme or not but thought I'd report in case it was related.

**Comment by qooob** [comment]
:) Thanks! It was just reported few days ago. It's fixed and will be working fine in version 16.02 pretty soon.

**Comment by MorningSleeper** [comment]
Ok thanks, in case your fix was limited to the custom commands textbox, I also just noticed it in Fail2Ban, Dovecot, Postfix and Spam Assassin edit config files, rest look ok.

**Comment by qooob** [comment]
Thanks, no, it will be global for all! ;)
