### ISSUE TITLE
Predefined color palette

### ISSUE THREAD

**Issue by livestant** [qooob/authentic-theme#264]
Having many webmin copies on different systems it's hard to not confuse one with each other. So I think it will be usefull to have feature to quickly select primary color for a current copy instead of the standard blue. 
It may be done simply by selecting a color from a palette in the theme configuration panel. It may be enough 8 colors like in the Google Keep.

**Comment by qooob** [comment]
Great point. Was planning to do this a while ago. Will try upon 16.02 update.

**Comment by livestant** [comment]
Oh, that'll be awesome! Thank you so much for your great work!

**Comment by qooob** [comment]
It will be there in version 17.00 actually, not 16.02.. Also pretty soon. Thanks for advising!

**Comment by qooob** [comment]
How about something like that:
![screenshot-pallets](https://cloud.githubusercontent.com/assets/4426533/10417515/62d5380a-7047-11e5-9a2c-b610e9869498.png)

It will be there in version 17.00 shortly.

**Comment by kimfull** [comment]
About the color palette theme: Why not just offer the hex color field (#123456) ?

**Comment by qooob** [comment]
Well, it's not that easy to do. There are many elements with different shades and colors. Its not only about the main color. However it's doable. I'm just not sure it will be used by many.

**Comment by ilkr** [comment]
Awesome!

**Comment by livestant** [comment]
> qooob

I'm not really feel comfortable trying to correct you, but in my opinion the colors must be more distinctive. Because it's not a matter of decoration, but of a color coding. I mean, user must unambiguously recognize each server by just its color. So having too similar colors is not good from this point of view. I tried to make my variant of the pallette by tuning only hue and saturation. 
 
![palette](https://cloud.githubusercontent.com/assets/5904161/10481167/a33f4584-7277-11e5-9a8e-06a18de66c3a.png)
 
The first colour in the palette is the current (default) color. The next four colours are made by changing only the hue, so they are completely coincide with each other and the first one by contrast. The sixth is made by dropping saturation to zero. Others are made by changing hue and saturation, they are contrast versions of previous colours. Please ignore the color of a pointer aside a selected item in the menu: it must be choosed individually.

> kimful

I don't think the hex color is useful for the task we are solving. Theme must have all colors predefined, so that they match its style. Hex codes may be easly specified individually with CSS.

**Comment by qooob** [comment]
Thanks, nice example, will improve by next release!

**Comment by qooob** [comment]
Version 17.01 will have extra predefined _sea green color_ and ability to set ten custom color themes. I think it will satisfy all picky users! ;)

**Comment by ilkr** [comment]
I have an idea for autogenerated theme from one main color. Both navigation menu color and content page color. 
May be you add options like this.
http://paletton.com/

**Comment by qooob** [comment]
Maybe, one day. Thanks.
