### ISSUE TITLE
Webmin update, Theme problem?

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#265]
During Webmin update from 1.760 to 1.770 the installation script shows these errors:

Webmin install complete. You can now login to https://ns2733xx.ip-94-23-xx.eu:10000/
as root with your root password.
warning: file /usr/libexec/webmin/authentic-theme/update: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/transition.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/tinymce/langs/readme.md: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/tinymce/jquery.tinymce.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/timeplot/virtual-server/timeplot.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/timeplot/virtual-server: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/timeplot/server-manager/timeplot.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/timeplot/server-manager: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/timeplot: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/spin.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/select2.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/login.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/loader.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.scrollbar.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.purl.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.easypiechart.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.datatables.plugins.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.datatables.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.autocomplete.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/icheck.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/fileinput.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/default.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/codemirror.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/bootstrap.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/autosizeinput.min.js: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/fonts/roboto/roboto.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/select2.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/login.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/jquery.scrollbar.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/jquery.datatables.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/jquery.autocomplete.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/fontawesome.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/fontawesome-animation.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/default.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/codemirror.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/css/bootstrap.min.css: remove failed: No such file or directory
warning: file /usr/libexec/webmin/authentic-theme/images/_empty.gif: remove failed: No such file or directory

Wondering why?... I have authentic theme...

**Comment by qooob** [comment]
After the update do you have version 16.01?

It happens because rpm compares initial files and as you installed updates aside from Webmin rpm package, I think this is why warnings happen.
