### ISSUE TITLE
What about being able to see the services status monitor on the dashboard and multi cpu

### ISSUE THREAD

**Issue by cybermarmotte** [qooob/authentic-theme#266]
What about being able to see the multi cpu gauges and services status monitor (such as mysql, apache...) on the dashboard?

Thanks

**Comment by qooob** [comment]
Interesting idea. By `multi cpu gauges` you mean charts for multiple CPU cores?

Services status monitor is already provided by Virtualmin in case it's installed?
![screenshot from 2015-10-09 13-28-23](https://cloud.githubusercontent.com/assets/4426533/10391819/3d60472c-6e8a-11e5-9928-0d1163258b24.png)

**Comment by cybermarmotte** [comment]
Yes, one gauge for each cpu.

I'm only using webmin so I have not the services status..

**Comment by qooob** [comment]
This is part of job that Webmin core should be doing. Adding multiple charts for CPU makes not much sense, because some servers can have 24 cores or more. Besides, the load usually balanced among all cores and adding carts for each will not provide with any useful information!
