### ISSUE TITLE
can not empty login alerts on config page

### ISSUE THREAD

**Issue by keinwort** [qooob/authentic-theme#267]
hi folks,

i tryed to just empty the login-alert-fields(on bottom) on the themes 1st config page,
because i was nerved of "for me" useless ;) mails.
 
the empty fields doesn't seems to get saved, because if you go to webmin 1st page, after saving
 (NOT BY BACK-BUTTON) 
and enter the config again, the fields are filled like before.

changing the fields to something "not empty" seems to be okay by the way.

is there a way to change a "config-file" by "hand" which does not get deleted/changed with an update?
option to disable the allert: or do i missed a button to disable the alerts? is there one or two.... ;)?

wkr
kein wort

**Comment by qooob** [comment]
Hi, there. What you're asking is already done in upcoming version 17, just in about 24 hours. New update will have this option, both for Webmin and Usermin.

So far, you can add your IP in exclusion set and it will avoid sending emails to you! ;)

**Comment by qooob** [comment]
By hand edit `/etc/webmin/authentic-theme/settings.js` and leave values for security notifications empty (don't remove quotes).

**Comment by keinwort** [comment]
thx for the very fast reply,
but as my ip is dynamic i have to change it every day, and every time i access the page i get TWO mail.
one for just viewing it and one for login in. 

so a little bit of a "nice paradox" here ;)
have fun

so far i just deleted the last two words in the messages "alert" + "root"
that works around it also

**Comment by qooob** [comment]
Ok, wait till tomorrow and you got it.
