### ISSUE TITLE
Evertime when edit a webmin user, after saved the Two-Factor Auth for the user will auto removed..

### ISSUE THREAD

**Issue by kimfull** [qooob/authentic-theme#270]
![image](https://cloud.githubusercontent.com/assets/3871491/10519326/bbe910a8-7397-11e5-9790-e1cd692ced9e.png)

**Comment by qooob** [comment]
Really? I used to think that it is Webmin bug. I will take a look and fix it by next release. Thanks for reporting.

**Comment by qooob** [comment]
What browser/OS are you using?

**Comment by kimfull** [comment]
Chrome 45.0.2454.93 m , Windows 7



regards.Kim.gmail
----------------------------------------------------------------------------------------
it's easier to invent the future than to predict it.

2015-10-17 22:59 GMT+08:00 Ilia Rostovtsev <notifications@github.com>:

**Comment by qooob** [comment]
This happened to be Webmin bug. [Reported](https://github.com/webmin/webmin/issues/235). Thanks for posting!
