### ISSUE TITLE
I can't upload a custom logo.

### ISSUE THREAD

**Issue by ecrazor1911** [qooob/authentic-theme#271]
Hi,

I received this error message when I try upload a custom logo:

**Failed to open /etc/usermin/authentic-theme/logo.png for writing : Not a directory**

This is a unique problem or general? My OS is very outdated (Debian 6.x)

**Comment by qooob** [comment]
Most likely it's OS specific. Try to check if destination directory exists, if not create it with right permissions.

**Comment by ecrazor1911** [comment]
Hmm... this is a regular file:
/etc/usermin/authentic-theme

**Comment by ecrazor1911** [comment]
Hmm... this is a regular file:

ecrazor1911@hosting:/home/dani# file /etc/usermin/authentic-theme
/etc/usermin/authentic-theme: ASCII text

It's possible?

**Comment by qooob** [comment]
That is wrong. Delete this file and replace it with directory. Don't forget to put there config file. After, resave the theme settings and reupload the logo. You should be fine.

**Comment by ecrazor1911** [comment]
Thank you for help! It's working correctly.
