### ISSUE TITLE
Wrong AJAX request in Filemin when using Webmin prefix

### ISSUE THREAD

**Issue by zweckh** [qooob/authentic-theme#273]
I use the webminprefix to access webmin behind an apache server. In the authentic theme 16.01 filemin does not use the webminprefix in ajax calls.
Ex: it calls https://(server)/filemin/create_file.cgi instead of https://(server)/(webminprefix)/filemin/create_file.cgi
In authentic-theme/unauthenticated/js/authentic.js most urls in ajax calls seem to miss $_____link_full

**Comment by qooob** [comment]
Oh, yeah, you're right! Missed that! Thanks! ;) Will fix it in 17.01
