### ISSUE TITLE
Usermin - Perl Execution Failed

### ISSUE THREAD

**Issue by DJFraz** [qooob/authentic-theme#275]
Good evening,

Logging in to Usermin using the Authentic theme creates the following error:

![untitled-2](https://cloud.githubusercontent.com/assets/13461917/10708289/22ca8e3e-79b8-11e5-9d57-66ddd930d35e.jpg)

Usermin works just fine with any other theme. Also, I do not see any error log entries for this.

**Comment by qooob** [comment]
This issue seems to be happening many times. It's not theme related. It's the stuck cache problem. Restart Webmin/Usermin to solve this issue. In case it still doesn't work, restarting machine solves this all the time.

**Comment by DJFraz** [comment]
Thank you. A reboot fixed it.
