### ISSUE TITLE
Weird characters in textareas Opera

### ISSUE THREAD

**Issue by neubreed** [qooob/authentic-theme#277]
Hi there,

This has been happening for a while ... I'm seeing an ascii character displaying on new lines and also the cursor in most textareas .. See attached screen shot. I'm using Opera 32.0.1948.69 
![2015-11-06 15_51_40-start](https://cloud.githubusercontent.com/assets/309231/10989718/13ae9160-849f-11e5-97d3-62c47209a2b5.jpg)

**Comment by qooob** [comment]
It's documented in [Troubleshoot](https://github.com/qooob/authentic-theme#troubleshoot). Please read it.

**Comment by qooob** [comment]
Did it work?

**Comment by qooob** [comment]
If it didn't make sure to also check `Webmin->Language and Theme` module as it overrides global settings!

**Comment by neubreed** [comment]
Sorry I didn't read the troubleshooting section .. but that's done it .. Thanks for your help!
