### ISSUE TITLE
Select all and delete Server Selected don't work

### ISSUE THREAD

**Issue by manukieli** [qooob/authentic-theme#278]
From Webmin -> Webmin Servers Index, when i click to select all and click to delete selected, they don't work. Say me this error message:
<code>
Failed to delete servers : None selected
</code>
![2015-11-06_8-57-03](https://cloud.githubusercontent.com/assets/14294794/10992260/a0853cc8-8464-11e5-8e71-9292c8d2684d.jpg)

And if i want to select one to one, it's not possible, because they open a blank page.

**Comment by qooob** [comment]
To select one, you can click right mouse button. I will test `Select All` deletion and let you know. As workaround you could open module's settings and change the view. It should work as expected.

Get back to your issue a bit later.

Thanks for reporting.

**Comment by qooob** [comment]
What version of the theme are you using? Also what is your browser and OS?

**Comment by manukieli** [comment]
OS: CentOS Linux 6.7
Theme: Authentic 16.01

Right click good :+1:

**Comment by qooob** [comment]
Alright, I see. I already debugged it. I couldn't reproduce it in version 17.02. 

Example:
https://rostovtsev.ru/pub/src/authentic/17.xx/issue-278/Screencast_from_11-06-2015_11:08:32_AM.webm

Turn on theme automatic updates notification in theme's settings.

Update to the latest version. Feed this link to `Webmin->Webmin Configuration->Themes->Install Theme`: https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz
