### ISSUE TITLE
MySQL Edit Previous not working

### ISSUE THREAD

**Issue by MorningSleeper** [qooob/authentic-theme#279]
In MySQL module when you click on a database and then Execute SQL, then Edit Previous, it does not put the selected previous statement in the form field above as I would expect.

**Comment by qooob** [comment]
Confirmed! It will be fixed on the next small release! Thanks for reporting! ;)

**Comment by MorningSleeper** [comment]
Great, thanks.

**Comment by qooob** [comment]
Will be fixed in 17.04 shortly. Stay updated and tell me if it works alright for you then.

**Comment by qooob** [comment]
You can update now!

**Comment by MorningSleeper** [comment]
Thanks, working fine now.
