### ISSUE TITLE
MySQL navigation

### ISSUE THREAD

**Issue by Anialation81** [qooob/authentic-theme#280]
While navigation databases and tables for a MySQL Database Server, there doesn't seem to be any indication as to what database and table I'm looking at. I should know since I just navigated there, but I have to leave the page in order to confirm the exact naming of the table. Also, if I left a tab open on that table and come back to it later, I won't know for sure if it's the table I need or not.

**Comment by qooob** [comment]
You know, it was my kinda global bug. I will fix it in 17.05 very soon!

**Comment by Anialation81** [comment]
Awesome, thanks!
