### ISSUE TITLE
Version 17.10 CPU Temps

### ISSUE THREAD

**Issue by chandlben** [qooob/authentic-theme#281]
As of this 17.10 update, my CPU temps have disappeared. I noticed some changes to make the CPU temps look the same and have the same options as the drive temps.

I was going to request this as a feature just a few days ago, but you read my mind. Now to figure out why they don't show at all...

**Comment by qooob** [comment]
Upps. `my` should not be there making its scope local. It will be fixed in version 17.11 in a bit.

Thanks for reporting!
