### ISSUE TITLE
Encoding issue since 17.10

### ISSUE THREAD

**Issue by cybermarmotte** [qooob/authentic-theme#282]
Hye,
Here is a link to a screenshot showing an encoding problem since 17.10:
![webmin_1_770_sur_vps129101_ovh_net__debian_linux_8_](https://cloud.githubusercontent.com/assets/3687099/11265016/0152ab4c-8e99-11e5-8444-2775597d193e.jpg)

**Comment by qooob** [comment]
Confirmed and will be fixed in 17.11 shortly.

Thanks for reporting!

**Comment by qooob** [comment]
http://stackoverflow.com/questions/33802155/perl-json-encode-in-utf-8-strange-behaviour
