### ISSUE TITLE
Critical PERL error after upgrade to Version 17.11

### ISSUE THREAD

**Issue by dmitrijev** [qooob/authentic-theme#283]
Error - Perl execution failed

Can't locate JSON/backportPP.pm in @INC (@INC contains: authentic-theme/lib /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . ..) at (eval 35) line 2.
 at /usr/libexec/webmin/authentic-theme/index.cgi line 15.
Compilation failed in require at /usr/libexec/webmin/authentic-theme/index.cgi line 15.
BEGIN failed--compilation aborted at /usr/libexec/webmin/authentic-theme/index.cgi line 15.

**Comment by qooob** [comment]
Upps. Could you please reinstall the theme manually? I already fixed that in the update just now.

**Comment by dmitrijev** [comment]
I wish I knew how to do it manually =)

**Comment by qooob** [comment]
Go to console and:

1. `cd /usr/libexec/webmin`
2. `rm -rf authentic-theme`
3. `wget https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz`
4. `tar -zxvf authentic-theme-latest.wbt.gz`
5. `rm -f authentic-theme-latest.wbt.gz`

That is all.

**Comment by qooob** [comment]
Worked?

**Comment by dmitrijev** [comment]
Worked like a charm! Спасибо, Илья!

**Comment by qooob** [comment]
Пожалуйста!! :)
