### ISSUE TITLE
Changing theme in Usermin doesn't reload the page

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#284]
I have added a new category under  Edit Categories and assigned some modules to it, however the new category did not appear in the left hand menu .... so I switched themes and ended up with 
![screenshot from 2015-11-19 11 47 36](https://cloud.githubusercontent.com/assets/4038510/11270125/31209ad0-8eb4-11e5-92d3-f7bdcfb84314.png)
as you can see I have ended up with 2 left menus on the theme change ... oddly enough my new category did not appear in the framed theme either (so this must be either I have configured the new category incorrectly or webmin has a bug) but I guess the theme change bug is authentic based

**Comment by qooob** [comment]
Very strange. If you didn't change the theme - then it's not the theme bug. What happens if you just `Ctrl+Shit+R` in your Chrome browser? Reload the page. What do you get? Did you try to restart Webmin/Usermin?

**Comment by JimTR** [comment]
I did change the theme ... I'll do some more tests

**Comment by qooob** [comment]
However, the same issue happens when you switch back to Authentic Theme or switching among other themes. I think it's Usermin related. Please submit a bug to [Usermin](https://github.com/webmin/usermin) developer if you think it's worth it.
