### ISSUE TITLE
Warning: something's wrong at /usr/libexec/webmin/authentic-theme/authentic.pl line 8.

### ISSUE THREAD

**Issue by MichaelW1998** [qooob/authentic-theme#285]
Hi,

My Webmin automatically shutsdown at random moments, and then I need to restart webmin again.
When I check the error file of Webmin, the only thing I see is this:

Warning: something's wrong at /usr/libexec/webmin/authentic-theme/authentic.pl line 8.
Warning: something's wrong at /usr/libexec/webmin/authentic-theme/authentic-lib.cgi line 1124.

Screenshot of logfile at:
http://www.michaelwijnands.eu/i/img-CEmjs2f.png

Thank you!

**Comment by qooob** [comment]
What you see in concern of a theme is just warnings. Fatal error happens because you don't have Authen:PAM installed. Install it first. It's not the theme issue, I think.

**Comment by qooob** [comment]
Did it work? Tell me please which version do you use?

**Comment by MichaelW1998** [comment]
I've installed that module so I don't get that error anymore. However, the random shutdown before could take like 7 days or so before it happened. So I will keep an eye out and reply here if I get it again. 

Thanks for your help!

**Comment by qooob** [comment]
Michael, random shutdowns have absolutely nothing to do with the theme. I don't mean to shutdown anything in my theme.. :D What version of the theme did you use when you made that screenshot?

**Comment by MichaelW1998** [comment]
What does this warning mean? 

17.11

**Comment by qooob** [comment]
Those are just warning for strict standards! No worries about this. It only affects my programming quality (which I do my best to improve in Perl - quite new here..) and not the general performance.

Enjoy!
