### ISSUE TITLE
Error in authentic.pl line 8

### ISSUE THREAD

**Issue by ThierryMasson** [qooob/authentic-theme#286]
Dear,

I have notice that when I run a command like this:
virtualmin modify-user --domain "xxxxx.yyy" --user "zzzz" --disable-email

I have the following error:
Warning: something's wrong at /usr/share/webmin/authentic-theme/authentic.pl line 8.
(event the command was "successfully" executed)

Best regards,

**Comment by qooob** [comment]
Alright, open `/usr/share/webmin/authentic-theme/authentic.pl` and remove `warn $@;` It will be fine after that I believe!
