### ISSUE TITLE
No log on spinner pages

### ISSUE THREAD

**Issue by ic5y** [qooob/authentic-theme#287]
Hi!

We found your theme for Webmin and we really like it at our company. Although in the default theme, you can see some log messages when restarting, creating hosts, servers, but when using this theme, we only see the spinner. Is there any option to turn it on?

**Comment by qooob** [comment]
Well, in case Webmin/Virtualmin uses `pre` tag to wrap the code the theme automatically disables the spinner and scrolls the page down. I discussed this with the VM team but it hasn't been done yet. I agree, it requires improvement.

So far, if you click escape key (if focused on the right frame. Focus can be achieved by simply clicking somewhere on the right frame), the spinner should be disappeared.

We'll see how we could improve it.

**Comment by qooob** [comment]
.. you also can disable right page content spinner in theme's settings.

**Comment by qooob** [comment]
How did it go?

**Comment by ic5y** [comment]
Hi!

Sorry, forgot to write back, we found the settings page and could turn it off. Working properly! Thanks :) :+1:
