### ISSUE TITLE
Editing files in Filemin returns empty editor field

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#288]
I have the latest version of Authentic Theme and Filemin, I cannot edit any of txt/php files. I'm not saying it's a bug.... however,

do others have the same problem? It worked before...

Regards

**Comment by qooob** [comment]
I have things working just as expected. Opened PHP file and edited it successfully. Make a video-screencast. What exactly doesn't work for you?

**Comment by sz00gun** [comment]
Please have a look the screencast at: http://screencast-o-matic.com/watch/coXTX2hr7m

**Comment by qooob** [comment]
The only thing that could be happening is that your session expired. While your trying to access Filemin being unauthorized, it just hangs.

As you reload the page, it should take you to login screen.

I see no left menu? Where is it?

**Comment by sz00gun** [comment]
Hi,

I'm logged in, the session is OK. There is a left menu, I just cropped it using screen casting. Done some other tests, and still cannot edit files, other Internet Browsers the same... No errors in debugger. Any other idea what to do?

**Comment by qooob** [comment]
Any special settings for  minserver? What version of Webmin/Filemin you got?

**Comment by sz00gun** [comment]
No special settings... I guess
Webmin 1.770
Filemin 0.9.6

**Comment by qooob** [comment]
What OS browser did you take the screencast?

**Comment by sz00gun** [comment]
Windows 7 and FireFox  v42

**Comment by qooob** [comment]
Can you got to console, open Network tab, fileter XHR requests only and click this button. What is the server's reply?

**Comment by sz00gun** [comment]
Well there is no error, however I discovered something... I don't want to publish sensitive server data online, so could you please reply for my email and I will email you full screen cast   reply please for: greg121@mailplus.pl   of course if needed... 

but first have a look this: http://screencast-o-matic.com/watch/coXOXwh3Fl

**Comment by qooob** [comment]
It seems like stuck cache. Can you clean all browser's cache and stored temporary data. Probably trying in incognito mode?

**Comment by sz00gun** [comment]
This didn't help. Removed cache using ccleaner + in the browser + open incognito mode, and the problem still there ;(

**Comment by qooob** [comment]
I will reload to my test Windows installation to check in Firefox 42. Will come back to you later after that!

**Comment by sz00gun** [comment]
Thank you, do you know why: 
![filemin33](https://cloud.githubusercontent.com/assets/7549566/11422782/a0e7a44e-9436-11e5-9ba0-d7c5328b2c5f.png)

**Comment by sz00gun** [comment]
the latest Opera, Chrome FF not working, I don't think this is Internet Browser related... but who knows...

**Comment by qooob** [comment]
`redirect` cookie belongs to the theme. I have the reset too, it's ok. You shared `sid`. I would logged out and log in again as soon as possible.

**Comment by sz00gun** [comment]
Ups... Thank you so much for this advice ;) Shall I change the password? Just in case?

**Comment by qooob** [comment]
No, you should not.

I have checked your issue in my Windows installation - all is fine. In all browsers, even Microsoft Explorer and Edge.

**Comment by qooob** [comment]
Do you use https connection?

**Comment by qooob** [comment]
Does regular listing through directories feature work in Filemin?

**Comment by qooob** [comment]
Also check in theme settings that you didn't load broken CSS extension!?

**Comment by sz00gun** [comment]
I use https connection,regular listing through directories feature is working fine in Filemin, and I don't use aby customers CSS. I use only 1 additional module, which is csf Firewall.

**Comment by qooob** [comment]
I honestly don't see an issue here and don't understand how come it doesn't work only for you!?

**Comment by sz00gun** [comment]
Thank you for the help. The problem is with my PC, because editing files working on my smartphone using FF Android... I have to format my PC now....

**Comment by qooob** [comment]
Alright, I see! I deeply recommend Linux distribution, like Fedora 23, for example!

**Comment by sz00gun** [comment]
Ohhh noooo, what a crap! I had no problem on Android FF, however I still cannot edit files on stock Internet Browser from Cyanogenmod 5.1.1

It must be a problem with my server (...)

I'll make more tests to find out where the problem is.

**Comment by qooob** [comment]
Alright! Let me know if you find anything! Cheers.

**Comment by sz00gun** [comment]
Not sure what I have done but it is working now for me. I uninstalled the theme including the Filemin, installed it back and it is working.  ;)  now I can see what I'm editing.

**Comment by qooob** [comment]
Good to hear! ;)

**Comment by sz00gun** [comment]
Got it!
I can retrieve that problem.... and I think this is a bug...

Editing files aren't possible when I start Filemin from the Favorites, and Virtualmin tab is active... When Webmin tab is active editing files are possible ;)

![tab](https://cloud.githubusercontent.com/assets/7549566/11874583/696c9300-a4d8-11e5-89fe-63d5807ea27e.png)

**Comment by qooob** [comment]
Great point, pal! Confirmed! I will fix it in 17.21! Thanks!

**Comment by Real-Gecko** [comment]
Is it a theme bug or Filemin bug?

**Comment by qooob** [comment]
This is the theme bug, I think! I see in code.

**Comment by Real-Gecko** [comment]
Ah, OK :)

**Comment by Real-Gecko** [comment]
I hope I'll have some time after NY to fix existing FM bugs :)))

**Comment by qooob** [comment]
Sure! But in general it works very well. Thank you!

**Comment by Real-Gecko** [comment]
Well, there're still some major issues :D

**Comment by qooob** [comment]
Let's nail it down then! :D

**Comment by rodentooth** [comment]
I have the same problem, but in some directorys editor works, in some not. I dont know if that matters, but it is a new created sub-domain in which edit it is not working.
Please see the youtube video: https://www.youtube.com/watch?v=vwCbevHb2c8

**Comment by qooob** [comment]
It looks like you simply don't have permissions to read a file. In case you try Gray Theme just to test, what result do you get? The same, right?

**Comment by rodentooth** [comment]
no in gray theme it shows everything

**Comment by qooob** [comment]
What are the actual URLs that are being requested in case of non-working and working file editor? The easiest way is to open console and take a look at Network tab or switch to Gray Theme and copy link's URL, while hovering on the editor's icon.

**Comment by qooob** [comment]
What are the actual URLs that are being requested in case of non-working and working file editor? The easiest way is to open console and take a look at Network tab or switch to Gray Theme and copy link's URL, while hovering on the editor's icon.

**Comment by rodentooth** [comment]
I deleted the cache of the Browser (Chrome) and then it worked
