### ISSUE TITLE
blank virtualmin list

### ISSUE THREAD

**Issue by skacco** [qooob/authentic-theme#289]
It works perfectly on a lot of server .. but in one server I cannot use it because virtualmin tab was empty.
I think problem is russian character .. I have a russian domani..
could you help me to solve this problem?

**Comment by qooob** [comment]
Yes, just update Webmin to the latest.

**Comment by skacco** [comment]
I have already installed webmin 1.770

**Comment by qooob** [comment]
Then VM?

**Comment by qooob** [comment]
This is the reason why it happed in past. What are your Virtualmin and the Theme versions?

**Comment by skacco** [comment]
I update also virtualmin and now it works correctly thank you!!!!

**Comment by qooob** [comment]
You are welcome! ;)
