### ISSUE TITLE
Re-editing in "User & Groups" turns the user-id into something invalid

### ISSUE THREAD

**Issue by bonojunior** [qooob/authentic-theme#290]
When creating a new unix user, everything goes fine, and the user receives a valid id (e.g. "1004").
However, when returning to this user to re-edit some settings, the user-id has "jumped" to MY NAME (= the name of the web min-user currently working).

**Comment by qooob** [comment]
Does this happen in Gray theme? Please check?

**Comment by bonojunior** [comment]
no, only in "Authentic"... (I have v. 17.11 (on Webmin 1.770))

**Comment by qooob** [comment]
You mentioned re-edit. How do you get there? Using a mouse click or browser's back button?

**Comment by qooob** [comment]
I can't reproduce what you're saying.

Please take a look of how it works for me: [Video Screencast](https://rostovtsev.ru/pub/src/authentic/17.xx/issue-290/Screencast_from_11-26-2015_10:30:44_AM.webm
)
Isn't it the same for you? If not, can you provide video screencast?

**Comment by bonojunior** [comment]
Can I quickly help you with some screenshots...


1) my webmin settings “users and groups”




2) creation of new user (= OK)



3) confirmation user is well created 



4) upon returning to a user (simply by clicking on the name of the user). Doing NOTHING else ! 
My name (= current webmin user) appears automatically in a yellow userid box instead of id (blurred by me for this demo) 





I’ll see if I can provide more information later

**Comment by qooob** [comment]
Can't see the screenshots?

**Comment by qooob** [comment]
My best guess is that browser's auto-complete function doesn't fill correctly. I remember it was happening in the past on my MacBook. In case you're using Safari try to disable auto-complete feature, it might solve the problem.

**Comment by bonojunior** [comment]
Excellent ! That was it indeed. Stupid of me that I did not think of it before. I disabled the auto-complete function in Safari and the problem is gone. 
Thanks for your great support !

**Comment by qooob** [comment]
You are very welcome! ;)
