### ISSUE TITLE
CSS, LESS, or Sass - creating dark right frame content page with ease

### ISSUE THREAD

**Issue by dahlskebank** [qooob/authentic-theme#291]
Mmmmm. I love this theme! Thanks for making Virtualmin bearable to use in 2015. ;)

Do you have any of the stylesheets in LESS or Sass? Since this is built on Bootstrap, I would like to restyle the theme to something dark, which is rather easy if you've built the theme from Bootstrap LESS. There's too much white for my eyes... I can do this step by step, per class and such, but I do prefer working from LESS.

Or do you have a dark theme in the plans?

**Comment by qooob** [comment]
You are welcome! I'm fully agree with having SASS but at the moment it would required a lot of work. Maybe one day in the future.

Do you know that in theme settings you can make it darker and choose other colors? It's not dark enough and you wanted it to be darker?

**Comment by dahlskebank** [comment]
LESS also works nice. Bootstrap is originally LESS, not working from those files? Didn't see any in the github project...

http://bootswatch.com/darkly/
Although not this style, but that kind of dark. I didn't find any settings that make the whole theme dark (dark background, bright text). I can still restyle only those elements of Virtualmin I use, but rather time consuming compared to LESS when the theme is already based on Bootstrap.

How do you add all your custom CSS to the theme?

**Comment by qooob** [comment]
There is `authentic.css` in the repo, take a look. It's not done that nicely as LESS or SASS. I will think of creating dark right frame panel. It's not easy and will take some work. Good idea thought! Thanks! I have added to my future todos.

**Comment by dahlskebank** [comment]
Is 'package.min.css' pure and original bootstrap.css?

**Comment by qooob** [comment]
Yes. https://github.com/qooob/authentic-theme/blob/master/unauthenticated/css/authentic.css

**Comment by qooob** [comment]
Have a look at the patch above. 

Dark theme for the right content page finally here. :wink: 

I hope you will like it! Give it a try by updating from GitHub.
