### ISSUE TITLE
something's wrong at authentic.pl line 8.

### ISSUE THREAD

**Issue by gerbier** [qooob/authentic-theme#292]
I'm running webmin 1.770 with authentic-theme 16.01 on ubuntu 15.10 and I have warning messages in my log files on sysstats (http://webminstats.sourceforge.net/)  module
[Sun Nov 29 18:34:27 2015] log.cgi: Warning: something's wrong at /usr/share/webmin/authentic-theme/authentic.pl line 8.
[Sun Nov 29 18:37:54 2015] index.cgi: Warning: something's wrong at /usr/share/webmin/authentic-theme/authentic.pl line 8.
[Sun Nov 29 18:38:00 2015] log.cgi: Warning: something's wrong at /usr/share/webmin/authentic-theme/authentic.pl line 8.
[Sun Nov 29 18:38:00 2015] log.cgi: Warning: something's wrong at /usr/share/webmin/authentic-theme/authentic.pl line 8. 

If I comment the line 8, it's good ... , but

**Comment by qooob** [comment]
Yes, right. Update to the latest,  17.11.

**Comment by gerbier** [comment]
done : It is now ok
but I had to install manually the last release : it was not proposed on webmin dashboard as usual

**Comment by gerbier** [comment]
sorry , I still have the same warning message with 17.11

**Comment by qooob** [comment]
You need to manually enable it in settings.

**Comment by qooob** [comment]
You need to restart Webmin. If doesn't help restart  the server.

**Comment by gerbier** [comment]
restart does not help ( same problem on fedora 22 )

**Comment by qooob** [comment]
Yes, for some reason it's still there! I thought that I removed it. I just did and it will be fixed on the next release! So far please remove it manually.

**Comment by bcutter** [comment]
Same here. What exactly should I remove? As you can see, line 8 of authentic.pl is an empty line the one between 'do' and 'sub':

```
#
# Authentic Theme 17.40 (https://github.com/qooob/authentic-theme)
# Copyright 2016 Ilia Rostovtsev <programming@rostovtsev.ru>
# Licensed under MIT (https://github.com/qooob/authentic-theme/blob/master/LICENSE)
#

do "authentic-theme/authentic-lib.cgi";

sub theme_header {
    print '<!DOCTYPE html>', "\n";
    print '<html data-background-style="'
        . __settings('settings_background_color')
        . '">', "\n";
    print '<head>',                 "\n";
    print '<title>',                $_[0], '</title>', "\n";
´´´

**Comment by qooob** [comment]
There was this on that line:

```Perl
warn $@;
```

It was removed since 17.20+. You shouldn't be having it. In case you still have it, please make sure:

1. That you really have latest authentic-theme in Webmin folder.
2. Make sure to restart Webmin
3. In case it doesn't help, please reboot the server.

I ask you please, in case, it only works after rebooting the server, please let me know here.

Looking forward for your reply.

**Comment by bcutter** [comment]
My fault, I mis-interpreted the web_log view; the log entry was an old one:

```
[Thu Dec 31 01:00:29 2015] index.cgi: Warning: something's wrong at /usr/share/webmin/authentic-theme/authentic.pl line 8. 
´´´

Everything fine; sorry bout that.
