### ISSUE TITLE
NaN% Virtual Memory

### ISSUE THREAD

**Issue by UTCWebDev** [qooob/authentic-theme#295]
It's not a number, I know... but for those of us who choose not to run virtual memory, is it possible to not include this in the charts?

<img width="1153" alt="screen-shot 2015-12-06 at 2 21 13 pm" src="https://cloud.githubusercontent.com/assets/2539685/11615123/23170e22-9c26-11e5-8155-42affe85f7b2.png">

**Comment by qooob** [comment]
Nice idea, I'll take a look, thanks.

**Comment by qooob** [comment]
Will be fixed in version 17.20

**Comment by ootws** [comment]
I've a similar issue on FreeBSD 10.2-RELEASE, but for me NaN% is on the CPU and Virtual Memory.

**Comment by qooob** [comment]
I can tell that this is not the theme issue. I would report it to Webmin. Probably some other libs are missing that pass information to the module. However, I will fix it.

**Comment by ootws** [comment]
Well, rather than disabling it, perhaps finding out the software needed for it would be better. Unless of course you mean add an option to disable those them.

**Comment by qooob** [comment]
Upgrade to version 17.20 and tell me how it is!

**Comment by Pathel** [comment]
Just started seeing this after updating to 1.780 / 17.20.

![webmin](https://cloud.githubusercontent.com/assets/159472/12071255/7f40fbaa-b070-11e5-95f1-5e1c9a7efbd1.jpg)

**Comment by qooob** [comment]
Yes, because Webmin package had outdated theme! Please upgrade the theme over again. Just enable it in settings and you will see the update button on system information page.

**Comment by FrancYescO** [comment]
Updated from 17.20.to 17.22 Hoping to Fix "NaN",  CPU and virtual memory just disappeared.

**Comment by qooob** [comment]
You mean to 17.72 (latest)? Works correctly, right?

**Comment by FrancYescO** [comment]
Yeah sorry 17.72, works but i have no CPU (and virtual memory) gauge :(

**Comment by qooob** [comment]
They are not gathered then, I suppose. Default theme shouldn't show it as well?
