### ISSUE TITLE
Possible character encoding issue, in browser tab title?

### ISSUE THREAD

**Issue by ahmgithubahm** [qooob/authentic-theme#296]
![scr](https://cloud.githubusercontent.com/assets/701588/11696098/83c15c9c-9eaa-11e5-900b-18f24b00062b.png)

The tab title has incorrect characters in it, see screenshot.  Seems to be true, whichever module I go to.  It's OK when on the Dashboard though.

I don't know how long this issue has been there - several versions, I think, just got round to reporting.

This is the same in Google Chrome latest, running in ChromeOS, Windows XP and WIndows 7, and also IE in Windows 7.

Many thanks!

**Comment by qooob** [comment]
Sounds like very possible. I'll take a look!

**Comment by qooob** [comment]
Do you have language set to UTF-8?

**Comment by ahmgithubahm** [comment]
Hi.  Just checking...   I have the encoding is set to 'Western (Windows 1252)'.  Behaviour is the same if I switch to UTF-8 too.

thanks

**Comment by qooob** [comment]
I can't confirm your issue! I think I know why.

In case you went to `Webmin->Webmin Configuration->Language` and set there proper language (like .UTF-8), you must also make sure that you have two things set-up correctly:

1. Module `Webmin->Change Language and Theme` can _override_ global settings!
2. Make sure that your browser really detects encoding as `UTF8`, if not set it manually!

**Comment by qooob** [comment]
Do you have other options set in `Webmin->Webmin Configuration->Language`, like `Character set for HTML pages` and `Use language specified by browser`?

With the following settings it works fine in all browsers:
![screenshot from 2015-12-15 10-57-36](https://cloud.githubusercontent.com/assets/4426533/11805187/d66e6a42-a31a-11e5-8e90-a6260794faa2.png)

Same should be done with `Webmin->Change Language and Theme`:
![screenshot from 2015-12-15 11-00-33](https://cloud.githubusercontent.com/assets/4426533/11805218/2c742300-a31b-11e5-966e-9393257d6651.png)

Anyway, first, you must make sure that the UTF-8 is set in both cases and that your browser detects it correctly. Go to browser tools, encoding options and in case it's set to `Windows 1252` or automatically, try forcing to UTF-8 and reload the page.

P.S. While I was writing it, I was many years ago also a Windows user (:() and I remember there were locale settings that affected the way plain text documents encodings are shown. For example, I always used English as system language and at the same time, when I was trying to view/edit plain text in Russian things always didn't work. Make sure to make system settings correct as well.

I believe it is your system specific thus non theme related issue. Closed.

**Comment by ahmgithubahm** [comment]
Hi, just checked on the settings you mentioned, and all is now sorted, many thanks!

On Webmin->Webmin Configuration->Language, it was 'English US (EN)', changed that to 'English UK (EN_GB.UTF-8)'.

And then Webmin->Change Language and Theme, was Personal Choice, 'English UK (EN_GB)', changed that to 'Global language'.

I didn't select any of these on purpose, but who cares, making the changes you suggested has sorted it.

thanks, Andy

**Comment by tpnsolutions** [comment]
Hi,

Just thought I'd chime in. I am seeing an error specifically when I am viewing the "Virtualmin" side of the interface, Webmin side works without any issues. I've confirmed that all the encoding settings as described here have been setup correct including both Webmin and browser.

![virtualmin-title-encoding-error](https://cloud.githubusercontent.com/assets/4305218/12714323/d65eaeb6-c888-11e5-958f-e0044e71a602.png)

-Peter

*** BTW: I dumped my chat server which is why you haven't seen me online. Perhaps I'll either setup a new one, or get an account somewhere so we can resume our chats. ***

**Comment by qooob** [comment]
Peter, I will re-post this issue to Joe, as I can't reproduce it.

**Comment by tpnsolutions** [comment]
Hi,

It should be noted, I've only noticed the issue in a Virtualmin Pro installation as my GPL copies do not present the same issue. Also, the system in question I DID NOT originally do the install so it could be related to something that I haven't thought of yet.

-Peter
