### ISSUE TITLE
Warning: something's wrong at /usr/libexec/webmin/authentic-theme/authentic.pl line 8.

### ISSUE THREAD

**Issue by Stinkykiller** [qooob/authentic-theme#297]
I applied your suggestion from https://github.com/qooob/authentic-theme/issues/285 but didnt help and this error is flooding my log file. I know this must be something new/recent because before i never saw this lines in my log files.
I'm using this server as test so aside of normal updates what comes with Vmin nothing changed for months.
And before anyone ask, yes everything is updated to last version provided by Vmin.

OS: Centos 7

**Comment by qooob** [comment]
What is the output of `cat /usr/libexec/webmin/authentic-theme/VERSION.txt`

**Comment by Stinkykiller** [comment]
16.01

**Comment by qooob** [comment]
Please upgrade to 16.11 and enable automatic update notifications in settings.

**Comment by Stinkykiller** [comment]
Ok i turned on updates for the theme as i dont know how ended with disabled so now it show 17.11 but the error is still here

**Comment by qooob** [comment]
Error is there as in most cases it's healed by restarting the server. You can try from restarting Webmin but in mosted case only full machine rebooting helps. I know it's weird but has been always true.

**Comment by Stinkykiller** [comment]
Already done, didnt help.

**Comment by qooob** [comment]
What donyou have on the line 8 in that file, `authentic.pl`? What version there is in headers.

**Comment by Stinkykiller** [comment]
#
# Authentic Theme 17.11 (https://github.com/qooob/authentic-theme)
# Copyright 2015 Ilia Rostovtsev <programming@rostovtsev.ru>
# Licensed under MIT (https://github.com/qooob/authentic-theme/blob/master/LICENSE)
#

do "authentic-theme/authentic-lib.cgi";
warn $@;

**Comment by Stinkykiller** [comment]
Removed "#" but "warn $@;" is line 8.

**Comment by qooob** [comment]
Yes remove `warn $@;` - I'll surely fix it in 17.20. Worked?

**Comment by Stinkykiller** [comment]
I just commented out and now is ok.

**Comment by qooob** [comment]
I really thought I did it before.
