### ISSUE TITLE
Разделители между версиями PHP

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#298]
Открыть информацию о PHP для сайта
Virtualmin -> Server Configuration -> Website Options -> PHP Information

![php-inf](https://cloud.githubusercontent.com/assets/14110152/11776715/0996c8e8-a252-11e5-8e6f-8fe456d10ea8.png)

Нужно добавить разделитель между версиями PHP чтобы было понятно какие модули для какой версии установлены.

**Comment by qooob** [comment]
Конечно, я посмотрю что можно сделать и добавлю к версии 17.20 скорее всего! Спасибо за совет!

**Comment by qooob** [comment]
Вот как будет это выглядеть начиная с версии 17.20. Надеюсь понравится:

![screenshot from 2015-12-15 11-14-43](https://cloud.githubusercontent.com/assets/4426533/11805519/64e3ff10-a31d-11e5-983f-ef6d0e663142.png)

Спасибо за совет! Следите за обновлениями. Удачи!

**Comment by Romich777** [comment]
Спасибо за оперативность и отзывчивость!
