### ISSUE TITLE
Centos version

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#299]
My original Linux installation was CentOS Linux 7.1.1503. I upgraded CentOS to the latest 7.2 version,  however the Webmin don't recognize the new version, why? 

I restarted Webmin etc. apart from the hard reboot.

Is this the theme related?

![centos-v](https://cloud.githubusercontent.com/assets/7549566/11816846/37a7e8e0-a34a-11e5-9b30-fe2b027b4a7d.png)

**Comment by qooob** [comment]
Please refer with this issue to Webmin repo.

**Comment by sz00gun** [comment]
Sorted... couple hours after upgrade Webmin informed me about this, and it started working, after accepting this.

![centos-v2](https://cloud.githubusercontent.com/assets/7549566/11822830/8984a860-a368-11e5-901a-37f84854c56b.png)

**Comment by qooob** [comment]
Yes! Exactly! Alright! ;)
