### ISSUE TITLE
Bookmarks not showing in filemin dropdown

### ISSUE THREAD

**Issue by systemm0** [qooob/authentic-theme#300]
FreeBSD 9.3-RELEASE-p28
Authentic Theme 17.11
Webmin 1.770

I have 8 jails running webmin+authentic theme and all have the same bug.

you can save bookmarks, which allow the bookmarks to be read from the dropdown, but if you navigate elsewhere (out of filemin and say php config) and come back to filemin, the dropdown will be empty.

looking at the module config shows the bookmark filepath listing, but still no longer appears in dropdown.

if you go the opposite direction and add a filepath to the module config and then try to choose a bookmark via the dropdown it yields no results.

Im thinking either a permission issue that FreeBSD has that is different from Linux, however I have not been able to nail it down.

it also doesn't matter if you disable pagination or change toolbar styles.

**Comment by qooob** [comment]
Do you use default `miniserv` setup without proxy?

**Comment by systemm0** [comment]
Yes I do

**Comment by qooob** [comment]
The thing is that I have tested it in Fedora 22 and 23, Centos 6 and Ubuntu.. things are working fine (bookmarks are just added)!

Alright, let's see. 1. How do you run Filemin? As root user? What is the output of `cat ~/.filemin/.bookmarks`??

**Comment by systemm0** [comment]
`> cat ~/.filemin/.bookmarks
cat: /root/.filemin/.bookmarks: No such file or directory`

however, inside ./filemin/ there is a .buffer file with `cut
/usr/local/www/oo
o
`

**Comment by qooob** [comment]
How do you run Webmin/Filemin as root user? If so make sure to create a file `~/.filemin/.bookmarks` by running `touch ~/.filemin/.bookmarks`. if you put in this file `/etc` or anyother link separated by "/n" will you see it Filemin after reload?

**Comment by systemm0** [comment]
it's FreeBSD, so just adding webmin to the rc init and it runs as root. which in retrospect is probably not a good idea. however I guess I would have to install sudo in order for a user to run webmin.

at any rate, I created the .bookmarks file. reloaded webmin and attempted to add a new bookmark, both through module config and using the drop down for adding the current directory.

the path/s is/are listed in the .bookmarks file, however does not show up in the drop-down.

upon further investigation, the miniserver log show and error `Warning: something's wrong at /usr/local/lib/webmin/authentic-theme/authentic.pl line 8.`

not sure if it has anything to do with it because the line is just `warn $@;`

**Comment by qooob** [comment]
What theme version are you running?

**Comment by systemm0** [comment]
forgot to choose the look for automatic updates for authentic theme. upgraded to 17.20 the miniserv error has stopped.

of course filemin is still not saving... well looks like more like reading the bookmarks since the paths I save are in the .bookmarks folder.

**Comment by qooob** [comment]
This is definitely not _Authentic Theme_ issue! Can you change to _Gray Theme_ and try it?

**Comment by systemm0** [comment]
Same Results.

if not authentic theme, then filemin?

**Comment by qooob** [comment]
Yes. Report to RealGecko/Filemin and he'll take a look.
