### ISSUE TITLE
Notification Slider IE Bug

### ISSUE THREAD

**Issue by ThierryMasson** [qooob/authentic-theme#302]
Hi,
I just would like to submit you this little bug with the new Notification Slider.
In IE (always the bad guy !) version 11 (I don't have tested with other release) the slider bar is always on top (and more annoying we couln't click anymore the Inbox because still in front of..).

![ie_bug](https://cloud.githubusercontent.com/assets/13097715/11911669/a0986d2c-a61d-11e5-8988-a889b6b6b214.jpg)

I have tried to disabled the notification, but it seams there is no way to disable it.

best regards,

**Comment by qooob** [comment]
I will take a look! Thanks for reporting!

**Comment by qooob** [comment]
What about Webmin?

**Comment by ThierryMasson** [comment]
Hi,

Same think (cf. in annex).


STUDIO MT®

*Thierry Masson*
/Gérant/

Gsm: +32 (0) 479 33 99 67
Fax: +32 (0) 87 22 52 32
thierry.masson@studio-mt.be <mailto:thierry.masson@studio-mt.be>
www.studio-mt.be <https://www.studio-mt.be>

Skype Call : STUDIO-MT <skype:STUDIO-MT> Skype Chat : STUDIO-MT 
<skype:STUDIO-MT?chat>

**Comment by qooob** [comment]
Will be fixed in 17.21. Thanks for reporting!
