### ISSUE TITLE
menu button on mobile viewport

### ISSUE THREAD

**Issue by topjor** [qooob/authentic-theme#304]
I have Configured the `Sea Green` navigation menu color, But the menu button on smaller screens stays blue when the navigation menu is hidden. It does change to green when the I tap the menu icon and the navigation menu expands.
I have not tried the other styles so I do not know if it is just this style or all of them.

![untitled](https://cloud.githubusercontent.com/assets/6335056/11920232/99459c64-a769-11e5-879e-6cf979e17914.png)

**Comment by qooob** [comment]
I didn't change styles to fit the theme unless it's active (clicked). By default it's always blue. Do you expect it to be green by default!?

**Comment by qooob** [comment]
I think it would make more sense to leave inactive menu button blue in all themes as it represents the link. (and all links on the right are blue). When you click it, it receives the menu color and looks nice! In case you don't like it, you can easily make custom CSS code and add it to your theme extension (which will survive updates).
