### ISSUE TITLE
Switch from codemirror to ace.js

### ISSUE THREAD

**Issue by pabloko** [qooob/authentic-theme#308]
Hey, i've worked on original codemirror implementation for filemin. as i see now authentic theme handles the assets for codemirror so i post this issue here.

I dindt had the good experience i've expected of codemirror, recently switched some projects to ace.js that is working way better and has a lot more lexers support and better integration.

Maybe switching it could be a good idea...

Ive also noticed that codemirror isnt working on standalone filemin access (no ajax) i'd like to have lexer on non ajaxed version, since its almost impossible to use the ajaxed one (works very slowly, almost unusable) maybe this settings could be configured on theme preferences

regards

**Comment by qooob** [comment]
I also like Acejs but CodeMirror works also very stable for me in all browsers. Isn't it for you too?

However, I didn't understand what you meant about no ajax at the last paragraph?

**Comment by pabloko** [comment]
Well, when you open filemin or edit a file in a new tab codemirror wont load. Also ajax loading not working. (fe. you access to webmin.url:10000/filemin)

For me its important the ability of editing several files at same time, thats why I always edit files on a new tab. Maybe having the ability of minimize and maximice edit dialogs could do the trick...

**Comment by qooob** [comment]
That is for sure, I will make tabs and minimization in the future.

So far, right clicking on the top left switch will create new window of Webmin. 

.. and yes, you should open the whole thing yo make scripts work properly.

**Comment by Real-Gecko** [comment]
I'm planning to create another Webmin module that will be central point for storing and managin all JS and CSS stuff. So maybe when it will be done selecting desired editor will become just a one click deal :)

**Comment by qooob** [comment]
...ohh. That will be difficult!

**Comment by Real-Gecko** [comment]
Maybe :)

**Comment by qooob** [comment]
> Maybe having the ability of minimize and maximice edit dialogs could do the trick...

Will be added to 17.21

**Comment by qooob** [comment]
+ hotkeys.

* Added new hotkeys for _Filemin_:
	* `Meta+F4` - close active editor window
	* `Meta+Shift+F4` - minimize active editor window

**Comment by pabloko** [comment]
Superb project and owner, many thanks @qooob for your effort and quick enhancement craft. 10/10 will donate something by end of the month!

**Comment by qooob** [comment]
Your are very welcome! :) Thank you and a Happy New Year!
