### ISSUE TITLE
CPU and/or Virtual Memory Graph Issue

### ISSUE THREAD

**Issue by jwhulette** [qooob/authentic-theme#310]
![webmin 1 770 on mulitisite ubuntu linux 14 04 3](https://cloud.githubusercontent.com/assets/4930051/11981507/46d3166e-a971-11e5-975a-b15e90fcf49d.png)
![webmin 1 770 on stage easycloses com freebsd 10 1](https://cloud.githubusercontent.com/assets/4930051/11981508/46e1990a-a971-11e5-8294-f7d2729a5588.png)

**Comment by qooob** [comment]
That is very strange. I think you should find out why you don't have those shown. I have never seen no CPU information - it's definitely not the theme fault!

I just noticed that your username is `admin` - what happens if you login as `root`?

**Comment by jwhulette** [comment]
Were does cpu and virtual pull the values from?

**Comment by qooob** [comment]
From Webmin supplied data.

**Comment by jwhulette** [comment]
Is it from CPU load averages? Just wondering because if I switch to gray theme there is no cpu.

**Comment by qooob** [comment]
Oh yeah?? Will take a look! How do you think it's possible not to have data about CPU? Do you miss CPU :D

**Comment by qooob** [comment]
Here is why it's not being hidden in the theme, when it should as `NaN` not a string.. Will fix it in 17.21. Thanks!

The rest should be submitted to Webmin, as theme only parses data.
