### ISSUE TITLE
Missing theme_select_server?

### ISSUE THREAD

**Issue by mlbarrow** [qooob/authentic-theme#312]
When using Authentic and initiating a package update, I eventually get an error about an undefined subroutine. See screenshot.
![cloudmin-authentic-error](https://cloud.githubusercontent.com/assets/1889714/11995337/0170102a-aa04-11e5-9d46-e4b1220865ca.png)

**Comment by qooob** [comment]
Sorry but this is not the theme issue. You should submit this bug to Webmin repo.

**Comment by mlbarrow** [comment]
I was looking at the gray theme and it has a file theme.pl, which defines a theme_select_server. It appears that this function is used by Cloudmin and so it looks to the theme to supply it. Is Authentic recommended for Cloudmin?

**Comment by qooob** [comment]
I have spent a lot of time debugging and testing the theme under Cloudmin. I would say it's stable enough to use. In case you find any issue post it and I will do my best to fix it as soon as possible.

Regarding your current issue, I will forward this thread to Cloudmin developer to clarify things. The function you mentioned doesn't _has_ to be included in the theme in my opponion, as it's only used to override the default one.

**Comment by mlbarrow** [comment]
Per your advice, I opened a ticket with the Cloudmin folks and referred them to this issue here.

**Comment by qooob** [comment]
Alright, thanks. I have also reported it.

**Comment by jcameron** [comment]
FYI, this will be fixed in the next Cloudmin release.

**Comment by qooob** [comment]
Thanks, Jamie! :)
