### ISSUE TITLE
CSF location

### ISSUE THREAD

**Issue by KeiroD** [qooob/authentic-theme#313]
So I installed the `CSF` module for Webmin to enable usage of the ConfigServer Firewall via the UI... however, I don't see CSF enabled anywhere using `authentic-theme`.

Unless... it's hiding under `Networking` > `Linux Firewall`. In which case, why is it not displaying a `CSF` front-end?

I'm pretty sure I'm not blind because I have no idea where you've hidden `CSF`.

**Comment by qooob** [comment]
My friend, you need to manually install CSF module for  Webmin after installing CSF using install.sh script. Of this is what you did and you don't have it, go to Webmin users (or just click your username (presumably root), next to logout button).. There you will see tabs. Look at available modules and make sure that ConfigServer Security Firewall is enabled. Reload the page with Ctrl+R in case left menu is not updated.

Afterwards just go to search and start typing Firewall. Then you should find it.. 

It's not the theme issue! ;)

**Comment by qooob** [comment]
Got it?

**Comment by KeiroD** [comment]
@qooob Actually, I'm pretty sure it is because that's what I did. See image.

![webmin-authentic](https://cloud.githubusercontent.com/assets/3938118/12004786/b87e4870-ab3c-11e5-8442-df22e8a4552e.png)

**Comment by qooob** [comment]
I might add those instructions, even though you would experience the same in other themes. It sounds again like non theme related, an old issue with cache.

Glad it worked, good luck.

**Comment by KeiroD** [comment]
True, I would experience the same.

But I think your theme needs to have those instructions included, at least if only to confirm that yes, Authentic Theme does see CSF is installed and used by Webmin and that it's a cache issue.

Though I'm still not sure what it was that required a full reboot for mine to show the changes as usually a `CTRL-F5` is enough to force a fresh pull from the server itself and not from the cache... I guess I'll just mark it up as a mysterious WTF.

Thanks for telling me where to confirm that Authentic Theme is seeing CSF!

**Comment by qooob** [comment]
Alright. Webmin team is aware of cache issues. I think it will be fixed one day or the other
