### ISSUE TITLE
Cloudmin change password screen is wonky

### ISSUE THREAD

**Issue by mlbarrow** [qooob/authentic-theme#314]
Cloudmin Pro 8.3; Authentic 17.30; Webmin 1.770; Chrome  47.0.2526.106
![aerie_vh_-_change_password_ _webmin_1_770_on_murder_eug_mlbarrow_com__ubuntu_linux_14_04_1_](https://cloud.githubusercontent.com/assets/1889714/12005093/59208238-ab43-11e5-96f1-5e313931cb13.png)

The "Change login used by Cloudmin" text seems to be misplaced.

**Comment by mlbarrow** [comment]
Nevermind.

**Comment by qooob** [comment]
It was there by default and I wrote small code to fix it. You can see the result in SpamAssassin module, where this bulgy blocks turns into beautiful button.

Report more if you find, I will try fixing it soon.

**Comment by qooob** [comment]
How to invoke `Change login used by Cloudmin`, I created dummy host but don't see it there?

**Comment by qooob** [comment]
Ahh.. Ok, pal! I imitated it. It will be working automatically on the next, release. So far, I have a fix for you. Just go to theme options and add the following code to the theme's `Extensions->Scripts.js` file and click safe. After all go to that page and click reload. You should have it nicely now. Tell me if you like it and please keep searching for more! ;)

```JS
// Cloudmin `Change Password` deuglifed sticking out link #314
if ($current_page_full == $_____link_full + "/server-manager/edit_pass.cgi" && $('form[action="save_pass.cgi"]').find('a[href*="edit_pass.cgi?"]').length) {
	var target = $(".ui_form .table-responsive table.table.table-striped.table-rounded.table-condensed.table-subtable > thead tr th:first-child"),
		container = $(".ui_form .table-responsive table.table.table-striped.table-rounded.table-condensed.table-subtable > thead tr th:last-child"),
		link = container.find("a");
	target.append(link);
	container.remove();
	target.find("a").addClass("table_title_links pull-right btn btn-info btn-tiny").attr("style", "position: absolute; right: 20px; margin-top: 3px !important;");
}
```

**Comment by mlbarrow** [comment]
Ahhh -- that looks much better!

I closed the ticket because I thought I was being too picky. But, since you've asked for feedback...I will let you have it all! :-)

**Comment by qooob** [comment]
Thanks! If you find anything else just post it here or open another issue! Good luck!
