### ISSUE TITLE
Bug on editing files in Filemin with Webmin 1.780 update

### ISSUE THREAD

**Issue by FilipeGNU** [qooob/authentic-theme#315]
In Filemin module, there is a bug, when editing files on Webmin v1.780+

**Comment by qooob** [comment]
What bug? Did you upgrade to 17.30?

**Comment by qooob** [comment]
Yes, confirmed. It will be fixed in 17.31 very soon. Thanks!

**Comment by qooob** [comment]
Fixed in 17.31. Please update.
