### ISSUE TITLE
Webmin 1.780 update brings out-dated release (17.20) of Authentic Theme

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#316]
Couples hours ago there was an update: Webmin version to v. 1.780 

My authentic theme version was: 17.30 (updated week ago)

During updating there was an error:
![webmin error](https://cloud.githubusercontent.com/assets/7549566/12070694/1819be50-b07d-11e5-8bd3-2c2d778209ee.png)

is this something bad? 

After Webmin update to the latest version I have noticed another theme update to 17.30... but I already updated to that version.... weird...

**Comment by qooob** [comment]
There is nothing bad! Webmin developer didn't put latest version of the theme (but previous) to his 1.780 package. All you do, just upgrade the theme once again.

**Comment by qooob** [comment]
Make sure to update to **Version 17.31**! 

Thank you!

**Comment by FilipeGNU** [comment]
Thank you very much!

**Comment by qooob** [comment]
@FilipeGNU You are welcome!

**Comment by swelljoe** [comment]
Authentic is currently moving very rapidly, so it is getting a lot of releases. Webmin will resync each time a new release comes out...but, it will often fall slightly behind the current Authentic release. New Webmin releases happen about every 2 months.
