### ISSUE TITLE
Quick access to Favorites

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#318]
Favorites facility is awesome stuff in the theme, however is possible to make even faster access with favorites buttons eg. like this?

Something like this would enhance the theme

![fav](https://cloud.githubusercontent.com/assets/7549566/12071816/922b327a-b0b7-11e5-8d3f-5f6d9e5cb08f.png)

**Comment by qooob** [comment]
There are 10 hotkeys that you can setup to open any module/link? Not good enough??

**Comment by qooob** [comment]
Like `Alt+1`, `Alt+2` and etc.

**Comment by qooob** [comment]
You can set them up in theme's settings (options)
