### ISSUE TITLE
Change Theme using webmin 1.780 crashes

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#319]
Changing theme like so 'old webmin ->authentic' causes webmin to fail 
![at1](https://cloud.githubusercontent.com/assets/4038510/12075093/52c057e0-b16c-11e5-97dd-77688724d6d1.png)

you need to reload the CP URL directly eg <host>:port this then reloads webmin but with the wrong version displayed in the tab title 
![ab2](https://cloud.githubusercontent.com/assets/4038510/12075125/c90f7a7a-b16c-11e5-8910-599f190868b1.png)
this may be a webmin issue but I would guess it to be a theme issue

**Comment by qooob** [comment]
Thanks! I noticed it before! I think this is Webmin's theme issue because redirect happens before Authentic is loaded?

**Comment by JimTR** [comment]
not sure .. if you change authentic->authentic it also fails ...

**Comment by qooob** [comment]
Yes, true. I'm not sure if we should bother at all. Besides, that seems like Webmin issue..If you wish please submit this as a bug to Webmin repo.

People don't change their themes much too often to worry about. :)

**Comment by JimTR** [comment]
I only changed the theme as Authentic failed ....

**Comment by qooob** [comment]
:) Thanks. When Authentic failed for you last time?

**Comment by JimTR** [comment]
it failed on update  to 17.31 ....

**Comment by qooob** [comment]
When you were updating to 17.31 from 17.20?

**Comment by JimTR** [comment]
I always update from the previous version so if 17.20 .. but I think I 
updated from 17.30

**Comment by qooob** [comment]
Alright but what really failed for you?

**Comment by JimTR** [comment]
the update was done with the update to webmin 1.780 ... the theme just died ... I had to change the theme to just see webmin again

**Comment by qooob** [comment]
Alright, I see! It was because Webmin had out-dated version of the theme by mistake. We'll try to avoid such problems in the future.

**Comment by JimTR** [comment]
after that error the page (tab) description shows as  the wrong version of webmin
![screenshot from 2016-01-02 18-36-29](https://cloud.githubusercontent.com/assets/4038510/12075689/fc1e7f0c-b17f-11e5-8a61-ca9d12a7a076.png)
you will see the window title returns webmin  version 1.770 & the statistic returns webmin version 1.780
but everything now appears to work

**Comment by qooob** [comment]
Yes, please go to theme's settings and clear cache. Then click `Ctrl+R` to reload.

**Comment by JimTR** [comment]
clearing the cache cured the problem ... perhaps on theme update the cache should be cleared by default or was this an issue of updating the theme and webmin at the same time ?

**Comment by qooob** [comment]
That is because Webmin upgrade! I will keep this in mind and try fixing it. Thanks!
