### ISSUE TITLE
NaN% on status gauges, and missing status details

### ISSUE THREAD

**Issue by cserem** [qooob/authentic-theme#321]
Hello!

We have just switched to this theme, and all I can say is awsome work, thank you!

One thing that I have bumped into is that the system information page  after loggin in looks like this:
![kepkivagas1](https://cloud.githubusercontent.com/assets/6615721/12142859/a5d99a74-b47b-11e5-81a5-defd65fd3b26.PNG)
and looks like this if I select the information page specifically:
![kepkivagas](https://cloud.githubusercontent.com/assets/6615721/12142721/a80dd8ba-b47a-11e5-9a64-fc1df08591d0.PNG)

With our previous theme (Virtualmin Framed theme) it shows all the informations correctly (webmin version, load, cpu, etc.) both after log in, and after navigating to /sysinfo.cgi

The system runs a Linux/Webmin 1.780/Authentic Theme-17.31 .

So far I have tried to "Resoter defaults" and "Clear cache", and "Force update" on the theme setup page.

Please tell me what additional information do you need to squash this issue.

Thanks,
cserem
UPDATE1: seems so I am not using Authentic Theme 17.31, but 17.20 (version information on was available upon usermin login), how could I verify which version I am using?
This is really interesting since I have deleted the theme, and reinstalled it from:
https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz

**Comment by qooob** [comment]
This is exactly the issue [#317](https://github.com/qooob/authentic-theme/issues/317).

If you hit Force Upgrade and it doesn't work - this is network cache issue. It happens. Download it on your local machine and then install theme using uploaded file. Then hit `Ctrl+Shift+R` to hard reload browsers cache. Did it help?

**Comment by cserem** [comment]
I have client side caching disabled altogether, for other reasons. 

I have also deleted the theme,  re-uploaded it directly from the url via webmin, and also uploaded it from my desktop,  but the results are the same. 

Just like with #315 it is  a  Debian system,  but it is 7 not 8.

**Comment by qooob** [comment]
Did you try to reload Webmin? Or if doesn't help reload server completely?

**Comment by qooob** [comment]
If you go to the directory, in File Manager do you see 17.31 in file VERSION.txt?

**Comment by cserem** [comment]
Yes,  webmin-base/authentic-theme/VERSION. TXT,  and usermin-base/authentic-theme/VERSION.TXT  contains 17.31 (now that I upgraded  the theme for usermin too,  it states the version correctly on the web too) 

Yes,  I have stopped and started, both usermin and webmin.

**Comment by qooob** [comment]
That is very strange and should not be happening. The other guy stated in the thread that it was fixed by it self after he re-installed Webmin. Did you try to restart the server? It sounds like cache issue (that happened 100 times already).

**Comment by cserem** [comment]
If it is a caching issue, then it must be on the server side.
So you are recommending the restart of the debian host?

**Comment by qooob** [comment]
Yes, in 99% of cases it solved the issue. Please try.

**Comment by cserem** [comment]
I see, and will try that when it is possible.
In the meantime I have figured out that the XHR request to /index.cgi/?xhr-info=1 returns an empty json object: '{}'

According to authentic-theme/authentic-lib.cgi:2902
 `if ( &foreign_available("system-status") )`
is false.

What could cause that behaviour?

**Comment by qooob** [comment]
You might want to enable system-status module, clicking root, near logout button and going to Available Modules. It shouldn't cause any issue however.

If you click context menu and choose reload frame while being on system information page, does it look broken right away or in few seconds?

**Comment by cserem** [comment]
That did the trick!
For the user I was working with, the system-status module was disabled for some reason.
After enablig it "User icon > Available Webmin Modules > System status" it works as expected.
Thank you!

**Comment by qooob** [comment]
Oh, my goodness!! I reproduced the issue by disabling system status module!! I will fix it in 17.32.

Thanks!

**Comment by qooob** [comment]
This will be fixed in 17.40 in few days. Thanks!!
