### ISSUE TITLE
Page title is stuck displaying wrong (previous) version after Webmin upgrade

### ISSUE THREAD

**Issue by alexantr** [qooob/authentic-theme#322]
First I updated Webmin to 1.780 and what i saw:
* warning was appeared:
![Warning](https://sc-cdn.scaleengine.net/i/796d58abbd6f6a4d89813b9e91a96bf6.png)
* when dashboard page loaded, page title "Webmin 1.780 on example.com (Debian Linux 8)" replacing with "Webmin 1.770 on example.com (Debian Linux 8)" or "Webmin Configuration — Webmin 1.770 on example.com (Debian Linux 8)".

Try to update authentic theme to 17.31, warning was disappeared, but bug in title is still there.

Have same bug on other server with CentOS 6.7: "Webmin 1.780 on other.example.com (CentOS Linux 6.7)" replacing with "Webmin 1.770 on other.example.com (CentOS Linux 6.7)"

**Comment by mlbarrow** [comment]
What browser are you using? I saw a similar issue with Chrome which seemed
to subside after kicking the browser, from what I recall.

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by qooob** [comment]
This is known bug. Please go to theme settings and Clear Cache or run in console `localStorage.clear()` and reload. It will be fixed in next release!

I will keep the issue opened until I actually fix it.

**Comment by qooob** [comment]
Did it work?

**Comment by alexantr** [comment]
```localStorage.clear()``` is working.

**Comment by qooob** [comment]
:+1:

**Comment by qooob** [comment]
Will be fixed in 17.40. Thanks!
