### ISSUE TITLE
Configurable HTML snippet in navigation menu (new feature for 17.30) will not recall content after theme update to newer version

### ISSUE THREAD

**Issue by drkskwlkr** [qooob/authentic-theme#323]
I find tremendous value in the feature called "Added ability to use configurable HTML snippet in navigation menu, for identification purposes" introduced in Authentic Theme version 17.30.

However the HTML markup I entered disappeared as soon as I updated from 17.30 to 17.31 (observed on two unrelated servers under my management, both running Ubuntu 14.04 LTS and Virtualmin 4.18gpl).

The markup is stored in `authentic-theme/unauthenticated/js/settings.js` under `settings_leftmenu_user_html=` as expected, but version 17.31 will not display it.

Also, if I may use this ticket to put forward an extension of this feature for consideration. The input field size is presently too small to accommodate anything but 10-12 characters of text plus small HTML markup. It could host a lot of important information (e.g. phone number/email support contact; links to 3rd party services like external server monitors; hardware configuration) but such information would be difficult to view/edit within the limited text box.

Will @qooob consider modifying the style of the input field by:
1. Making it a bit wider by increasing the value of `display: inline; width: 40%;` to `80%` or thereabous (looks great on browser window width between 1000 and 2500 pixels wide)
2. Allowing resizing by mouse for cases where longer bits of text and HTML markup need to be entered/edited.

Thank you Ilia!
Ivan

**Comment by qooob** [comment]
Sure I will! The reason why it's not displayed is probably because you tried to use `'` there, like `class='class-name'` in your HTML to avoid HTML break-up on theme page settings reload (before 17.31). Version 17.31 has correct escaping and does things right. So now to display your previously entered HTML just make sure that you update to 17.31. Thene open theme's `settings.js` manually and edit it manually, making sure to have `"` instead of `'`. If you have `'` and edit it manually make sure to escape it by typing instead `\'`. If it doesn't work, just send me your snippet, I'll try figuring this out.

**Comment by drkskwlkr** [comment]
I just checked, I do not have single quotes inside my markup.
I am sending you the snippet contents via email as it is semi-private.

**Comment by qooob** [comment]
Ivan, bug is confirmed! I will try to figure out what happened! Thanks!!

**Comment by qooob** [comment]
Ivan, can you please edit `authentic-lib.cgi`

Find: 
```Perl
for ( values %in ) {s/(.*)/'$1';/}
```
Add after:

```Perl
for ( values %in ) {s/"/'/g}
for ( values %in ) {s/\/\//&#47;&#47;/g}
```
Next,

Find and delete this line:
```Perl
$m =~ s/"/&quot;/g;
```

Re-save your settings. Working now? :)

**Comment by qooob** [comment]
I will also make CSS fix for the links in snippet.

**Comment by drkskwlkr** [comment]
I found the lines in `webmin/authentic-theme/authentic-lib.cgi` and made the changes but the string still does not show.

**Comment by qooob** [comment]
Hmm. It should. Reload Webmin, then go to settings and insert your HTML string. Then save and `Ctrl+R`. After reload all should be fine.

**Comment by drkskwlkr** [comment]
Ah, I did not re-insert the HTML string the first time; I expected that the script would be able to interpret the old snippet. Sorry.

Now that I typed the HTML string for the second time and saved it, I confirm that it works. The saved snippet in 'settings.js' now looks different (the `https://` are now encoded) and the text is displayed as expected.

Lovely!

**Comment by qooob** [comment]
Glad to hear! ;) Thank you, Ivan!
