### ISSUE TITLE
Custom language and custom URL, logo settings

### ISSUE THREAD

**Issue by AlexShapka** [qooob/authentic-theme#324]
Hi Ilya, 

Even-though Eric has responded to the question:

> Where to report Authentic theme's issues?

on https://www.virtualmin.com/node/39221, I'd like to hear from you where you personally would prefer Authentic Theme issues to be reported to?

Also could you please respond to

> How to make Authentic Theme to work with custom-lang file?

on https://www.virtualmin.com/node/39228

and to

> Authentic Theme does not respect some custom URL, logo settings 

on https://www.virtualmin.com/node/39225

**Comment by qooob** [comment]
Alex, hi! ;)

I will respond to everything and fix everything!

I'm in different time zone. It's very rare that I can last up to 2am - this is why I didn't answer. My time zone is +0300, add this to your clock please.

I prefer GitHub for managing issues but I will respect and read each issue posted to the tracker.

**Comment by qooob** [comment]
All issues will be fixed in version 17.40.
