### ISSUE TITLE
How to set default navigation menu color

### ISSUE THREAD

**Issue by AlexShapka** [qooob/authentic-theme#325]
Virtualmin.com is currently being migrated and upgraded, so I'm filing this support request here.

When switching to Authentic Theme it is set to Royal Blue by default. How can we use one of 10 User Palettes in the select list to define our own color palette and set it to default? I mean we would like our custom palette to automatically load every time we switch to another theme and back to Authentic Theme by default.

**Comment by qooob** [comment]
By choosing pallet you like and clicking save at the bottom of theme settings page?

I didn't understand what you are asking. Please rephrase the question.

**Comment by qooob** [comment]
What did you mean, Alex?

**Comment by qooob** [comment]
Did you figure this out?
