### ISSUE TITLE
Virtualmin Server Dropdown

### ISSUE THREAD

**Issue by davenir** [qooob/authentic-theme#326]
Just installed your theme and it seems very impressive. One immediate thing I noticed however was that the older version of the Virtualmin theme italicised disabled severs in the Server drop down menu (top left) while yours does not. This was a very useful feature to identify quickly the status of servers.

Also - a small point; the character limit on the server name in the drop down can be increased (now that your theme uses a smaller font size in the drop down).. but perhaps this is a webmin thing.

Many thanks

**Comment by qooob** [comment]
Hi,

Yes, you can control the length in Virtualmin Configuration.

I mark disabled servers in red. What version of the theme are you using?

**Comment by qooob** [comment]
You mean when they are not selected.. I see. Ok

**Comment by davenir** [comment]
Yes exactly Ilia - when they are not selected. 
Thanks also for domain character length tip - I never saw that before.

Many thanks

**Comment by qooob** [comment]
You are welcome. :)

**Comment by qooob** [comment]
It will be working in 17.40.

Meanwhile, if you want it already just add this to theme->extensions->js the following:

```JS
t__wi_p.$("aside select").on("select2:open", function (a) {
			$.each($("select > option"), function () {
				if ($(this).attr("style") && $(this).attr("style").indexOf("italic") > -1) {
					var $this = $(this);
					setTimeout(function () {
						t__wi_p.$("body").find('li[id$="' + $this.attr("value") + '"]').attr("style", "color: #e73c38 !important; font-style:italic !important; ")
					}, 1);
				}
			})
		});
```

Tell me if it's what you expected.

Don't forget to remove it when upgrading to 17.40.

**Comment by davenir** [comment]
FYI - I tried this and it made no difference for me but I'm happy to wait for next version.

[010](https://cloud.githubusercontent.com/assets/15016459/12197439/e59ec218-b5fe-11e5-8e2f-d7efe17c579a.JPG)

**Comment by qooob** [comment]
Well. Save the file and hard reload the theme (Ctrl+R or Shift+Ctrl+R)
