### ISSUE TITLE
Cloudmin "List Managed Systems" column sorting

### ISSUE THREAD

**Issue by mlbarrow** [qooob/authentic-theme#328]
With the default theme, the "List Managed Systems" function allows you to sort by columns. With the Authentic theme, I lose this capability. Is this by design, or a bug?

I'm running v 17.30 with Webmin 1.780 and Cloudmin 8.4 Pro on Ubuntu 14.04.

**Comment by mlbarrow** [comment]
Correction: I'm running Authentic 17.31.

**Comment by qooob** [comment]
You will have it in 17.40 within an hour.

**Comment by mlbarrow** [comment]
You are way too awesome!

**Comment by qooob** [comment]
Thanks! :)
