### ISSUE TITLE
Logging in on a Cloudmin system puts me on the Webmin tab...

### ISSUE THREAD

**Issue by mlbarrow** [qooob/authentic-theme#329]
Without Authentic, when I log into my Cloudmin master, I am on the Cloudmin tab. When I use Authentic, I end up on the Webmin tab after login. And, this is even though I have "Cloudmin" set to the default tab in Authentic.

It doesn't even show the Cloudmin tab if I set a default Cloudmin system as well.

Thoughts?

**Comment by qooob** [comment]
Yes, you don't have login screen as well from Authentic Theme, and having old one, right? Well, this default tab options and other stuff can only work correctly in you set Authentic Theme as default globally, not for one user.

**Comment by mlbarrow** [comment]
Oops -- I found the error: I went and selected Authentic under Webin:Webmin Configuration:Change Themes.

THANKS!!!!

**Comment by qooob** [comment]
;)
