### ISSUE TITLE
Webminstats error with 17.40

### ISSUE THREAD

**Issue by dgzambrx99** [qooob/authentic-theme#330]
After updating the theme this error is now displayed in the webminstats module

`Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: .. . /usr/share/webmin /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/arm-linux-gnueabihf/perl5/5.20 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl) at ../authentic-theme/authentic-lib.cgi line 3302.
BEGIN failed--compilation aborted at ../authentic-theme/authentic-lib.cgi line 3302.`

**Comment by qooob** [comment]
Hi, 

Attach the screenshot please or better video-screencast.

**Comment by qooob** [comment]
It's a very weird module, as I can even make it run without headache. I installed all dependencies and it's still complaining about `RRDs.pm` on two different systems.

I doubt that this is directly _Authentic Theme_ issue. I think developer should take are of this.

**Comment by qooob** [comment]
..in short you could install `JSON` using Perl Modules in Webmin.

**Comment by dgzambrx99** [comment]
Here is a screen shot

[image: Inline image 1]

http://snag.gy/GhxbG.jpg

**Comment by dgzambrx99** [comment]
Its very picky on its dependencies depending on which linux distribution
you are running

**Comment by dgzambrx99** [comment]
I just installed perl json and doesn't seem to have any effect on getting
rid of that message

**Comment by dgzambrx99** [comment]
Correction, that fixed it. I had installed the wrong perl json module.
Installing from apt-get libjson-perl made the error message go away.

David

---------- Forwarded message ----------
From: David Zambrano <david.zambrano@gmail.com>
Date: Mon, Jan 11, 2016 at 9:32 PM
Subject: Re: [authentic-theme] Webminstats error with 17.40 (#330)
To: qooob/authentic-theme <
reply@reply.github.com
>


I just installed perl json and doesn't seem to have any effect on getting
rid of that message

**Comment by TrakerBG** [comment]
For CentOS 6.7 and 7.2 (and probably all yum-based):
yum install perl-JSON
fixes that message.
Offtopic: About rrd-tool: I have installed rrdtool, rrdtool-perl AND perl-rrdtool to make that thingy work.

**Comment by qooob** [comment]
Installing _JSON_ is a very easy task. Besides there is an explicit message and people who uses this module will be able to install JSON on one-two-three.

Thank you for pointing this out. I will keep this in mind but for now issue is closed.

**Comment by bcutter** [comment]
I can confirm having had the exactly same issue, an 'sudo apt-get install libjson-perl' fixed it.
