### ISSUE TITLE
Authentic theme uses symbolic links for non-UTF-8 language files pointing to UTF-8 encoded files.

### ISSUE THREAD

**Issue by darkshram** [qooob/authentic-theme#332]
Authentic theme uses symbolic links for language files pointing to UTF-8 encoded files instead of plain non-UTF-8 encoded files (ISO-8859-1). This means if Webmin is configured to use a non-UTF-8 language, all non-US-ASCII characters will look bad. 

Non-UTF-8 language files should not be UTF-8 encoded files. A workaround could be to replace characters with HTML entities, but text in links in Info page will be shown as HTML code. It would be easier to remove simbilic links and use iconv to encode non-UTF-8 language files.

Some webmin modules lack of UTF-support in language files, which means non-UTF-8 (ISO-8859-1) is a better choice for some people.

**Comment by qooob** [comment]
Can you please list modules that don't have UTF support?

**Comment by darkshram** [comment]
My bad. All webmin modules have UTF-8 support. But still if users choose to use non-UTF-8 or if webmin if configured to detect language from browser ant it detects browser uses a non-UTF-8 language, some text looks like the one in the attachment.
![screenshot at 2016-01-12 13 34 29](https://cloud.githubusercontent.com/assets/10327500/12276871/d6e295c8-b93d-11e5-9d2e-5d1182d1eabd.png)

**Comment by qooob** [comment]
But most languages require UTF8, right? What is the point of all of this? Isn't better to switch to UTF8 by default in settings?

I'll ask Webmin developer if we could completely drop non UTF8 support as it gets very confusing, I agree!

**Comment by jcameron** [comment]
Webmin now uses UTF-8 as the default encoding for all new installs, and offers a UTF-8 character set for all existing languages. So supporting non-UTF-8 encodings probably isn't necessary.

**Comment by qooob** [comment]
Sounds reasonable. Maybe completely removing non UTF8 mentionings from Webmin selects/options made things easier for all?

**Comment by darkshram** [comment]
Many servers with existing installs have been using non-UTF-8 languages for many-many-many years. Updating to latest webmin and then switching to authentic theme as suggested by virtualmin forces everyone not using UTF-8 to default settings to UTF-8 in all servers to have everything to look Ok. Removing non-UTF-8 files would make things easier, yes.

**Comment by qooob** [comment]
I will remove non UTF8 files, along with Jamie, when he also does the same. I think new Webmin update could do it and automatically switch existing users of none UTF8 to UTF8.
