### ISSUE TITLE
Theme does not default to virtualmin

### ISSUE THREAD

**Issue by sgrayban** [qooob/authentic-theme#333]
If you still logged in and you go back to your VM server the them does not open the default virtualmin tab but instead shows the webmin tab.

This should not happen as it never happened with the Virtualmin Framed Theme

**Comment by qooob** [comment]
I don't understand what you mean. You logged in, right? How do  you go back to VM server? By clicking top left switches?

Did you set default tab in theme's options?

**Comment by sgrayban** [comment]
So lets say I was working at the url https://domain:10000/?virtualmin and when I finsihed working in it I go to cnn.com to read the news but then I go back to https://domain:10000/ even though I never logged out I go to the webmin tab when I go back to the url

**Comment by sgrayban** [comment]
look im not stupid... I know how to set the settings so yes of course I set the default tab to be virtualmin

**Comment by qooob** [comment]
I see now. Look, that theme's option explicitly says `Default tab after logging in`. It's technically gonna be impossible to go to Webmin then, if you want to use URL query, if I changed that the way you wish.

My recommendation, is to use concrete URL, like `https://domain:10000/?virtualmin` to get where you want or even to keep the tab pinned and always open.

**Comment by sgrayban** [comment]
That makes this default tab theme settings pointless if I have to keep switching the tab back to virtualmin.

**Comment by qooob** [comment]
It's not pointless? It works on login. Later, just provide proper URL and you get where you request. 

Why this is a problem?

**Comment by qooob** [comment]
Alright, I will do this optional and add `Force default tab` option, maybe it will be useful for some else as well.

**Comment by qooob** [comment]
I'll close it when finished, so I don't forget.

**Comment by qooob** [comment]
It will be there in 17.50. The option is called `Force default tab for Webmin`.
