### ISSUE TITLE
Saving theme settings switches tab

### ISSUE THREAD

**Issue by sgrayban** [qooob/authentic-theme#334]
When we click on your settings icon and we are in the virtualmin tab and then save the theme settings the tab switches to webmin and that should not happen.

**Comment by qooob** [comment]
Why this is shouldn't happen? This is done intentionally.

**Comment by sgrayban** [comment]
And it shouldn't

**Comment by sgrayban** [comment]
All your code needs to is refresh the frames -- that accomplishes the same thing

**Comment by qooob** [comment]
It's taking you to Webmin _(Webmin Configuration->Themes)_ module, that was nothing to do with Virtualmin and this is why the tab is changed. Theme's options are not edited that often and opening Virtualmin/Cloudmin unrelated modules, should trigger corresponding left menu, in my opinion.

**Comment by sgrayban** [comment]
Virtualmin framed theme never did this when I edited any settings in webmin configuration...

Another point for me to not use this theme -- it doesn't work like the default framed theme does.

BTW just because you like it doesn't mean everyone else does.

**Comment by qooob** [comment]
You actually alone on this one here. I'm sticking to the obvious logic and not my preferences.

The menu doesn't always switch when you work in Webmin modules but only in unrelated once.

I discussed this matter with Virtualmin developers and we came up to such conclusions.


I could technically do it optional in the next release..

**Comment by qooob** [comment]
Alright, first of all it doesn't change the tab when you click save button, right? It changes navigation swtich right when you go to theme settings. 

What exactly is your complain? This or that you could get to theme settings somehow and on saving it changed back the tab?

**Comment by qooob** [comment]
I will also make this optional for you, as it seems possible and not gonna break anything.

Next time, don't submit existing option as a bug but as feature request.

**Comment by sgrayban** [comment]
How am I suppose to know if its a bug or a option ?? It's not like I started using VM yesterday.

I used the original theme for 6-7 years before you came along and I am comparing that theme functions against yours. I like the html 5 but if I gotta go back to school for a theme change my clients aren't going to like it either.

**Comment by qooob** [comment]
It's self explanatory, e.g. `..tab after login`. ;)

**Comment by sgrayban** [comment]
Behind every person that uses your theme there are all their clients as well so its not just me or anyone else here that is doing the exact thing I am doing.... compare your theme to the original they used for years.

**Comment by qooob** [comment]
..and think for more if you got..I will try adding them all at once.

**Comment by qooob** [comment]
..alright, I understood your point.

**Comment by qooob** [comment]
It will be available by default since 17.50. Thanks for your points.
