### ISSUE TITLE
If option gotomodule=virtual-server is set in webmin, authentic theme won't let switch to webmin tab.

### ISSUE THREAD

**Issue by darkshram** [qooob/authentic-theme#335]
If 'gotomodule=virtual-server' is set in webmin configuration, Authentic theme lets to switch to Webmin tab but 1 second later returns to Virtualmin tab. Doesn't give enough time to click Webmin Configuration (or any other thing in Webmin tab) to change Index page options. Removing gotomodule=virtual-server lets switch tab freely.

**Comment by qooob** [comment]
Do you use Webmin config file or settings in configuration? Why not use theme internal settings for selecting where to go by default on login? Is that what you're asking?

**Comment by darkshram** [comment]
Many years ago I did set 'Webmin Configuration' -> 'Webmin Index Page' -> 'After login, always go to module': Virtualmin. I use that setting in all my servers, as many other sysadmins surely do. Switching to the Authentic theme with that setting makes Webmin modules unaccesible.

Yes I saw Authentic the has an internal setting. The issue is many sysadmins (like me) has been using Webmin with gotomodule=virtual-server for many years. Many sysadmins that switched theme might be going crazy right or switching back to old theme if they cant't figure out they have to remove gotomodule=virtual-server to use other webmin modules. I had to ssh and edit webmin/config in way to remove setting.

Authentic theme should check for that setting and warn o disable that setting before switching theme.

**Comment by qooob** [comment]
I think I could edit Webmin config and get rid of the value for that setting and thus making default for Webmin equal System Information page, ok?

**Comment by qooob** [comment]
Done automatically on theme load, I mean.

**Comment by qooob** [comment]
There is no need to edit config. I will fix it easier way. Thank you for the great advice - it's really annoying. I will also remove Virtualmin and Cloudmin ref from setting it as default (in index page options).

**Comment by darkshram** [comment]
You are welcome. I like Authentic theme. Looks and works really good. Hope Webmin pushes an update.

**Comment by qooob** [comment]
Thank you!

**Comment by qooob** [comment]
It will be fixed in 17.50.
