### ISSUE TITLE
The 'size' parameter is ignored when calling the webmin 'ui_textbox' function.

### ISSUE THREAD

**Issue by Ben-HID** [qooob/authentic-theme#336]
Hi,
There is no size attribute in the rendered HTML after a call to the webmin 'ui_textbox' function (`<input type="text">`).
The size attribute is present for password input (`<input type="password">`) rendered with the webmin 'ui_password' function.

Note: A workaround is to pass the size attribute in the 'tags' parameter of the 'ui_textbox' function.

**Comment by qooob** [comment]
Why are you reporting this? Does it cause the issue somewhere?

**Comment by Ben-HID** [comment]
We are creating / adding our own modules to Webmin and we use the Webmin API and your great theme for that.
So, for example, if we want to create a form with textfields and passwords, all with the same width, the specified size (used as parameter in 'ui_textbox' and 'ui_password' functions) is taken into account for passwords but not for textfields.

**Comment by qooob** [comment]
Alright, I understood. I will take a close look and do my best to fix in the next release!

Thanks for reporting.

**Comment by qooob** [comment]
It will be fixed in 17.50. Thanks.

**Comment by Ben-HID** [comment]
Great !
Thank you.
