### ISSUE TITLE
Problems with Webminstats after update to 17.40

### ISSUE THREAD

**Issue by expertdecisions2** [qooob/authentic-theme#337]
I use Webminstats module http://webminstats.sourceforge.net to obtain graphs of  a lot of historic stats.
Until now there was only a minor issue with authentic theme: the Panorama General didn't display correctly.
But after updating to authentic 17.40 the Webminstats is giving errors.
If I switch back to Virtualmin Framed theme, everything works OK.
This is the error message I get when selected some graphs:

Can't locate JSON.pm in @INC (@INC contains: .. . /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ../authentic-theme/authentic-lib.cgi line 3302.
BEGIN failed--compilation aborted at ../authentic-theme/authentic-lib.cgi line 3302.

Also when I select Panorama General, the circle in the middle stays spinning forever

**Comment by qooob** [comment]
Hi,

Just install JSON module. 

https://github.com/qooob/authentic-theme/issues/330
