### ISSUE TITLE
Dashboard HDD temp issue ?

### ISSUE THREAD

**Issue by ochbob** [qooob/authentic-theme#338]
Hi, 

have some problem to show HDD temps in dashboard, yesterday everythings works great.
But now, i'm not able to see my HDD temps into the Dashboard.

Any suggest ?

Thx !

**Comment by qooob** [comment]
That doesn't sound like theme issue? If everything work fine yesterday it hsould be find today, unless you deleted some dependencies that supplay such information. Theme only process pushed data.

**Comment by ochbob** [comment]
That's right.
But i don't made lot of modification :/

I have smartctl, and everythings looks fine:

![capture](https://cloud.githubusercontent.com/assets/16723954/12361790/6837751e-bbc0-11e5-98b9-db4c9e650f19.JPG)

What is use to push HDD data temp into the dashboard page exactly ?

**Comment by qooob** [comment]
Webmin does the push, using its internal functions. You should revert your packages changes when it worked fine.

It doesn't sound like the theme issue.

**Comment by ochbob** [comment]
I understand you point of view.

Do you have any tracks to resolve this problem ?

**Comment by qooob** [comment]
I don't. I would like to know too honestly, as on some servers I miss this data too and never had it displayed, while on others it shows it fine. Please let me know if you find this out.

**Comment by ochbob** [comment]
I find the solution, pretty sure it's my problem, i made the RAID last night:

http://www.overclock.net/t/991966/no-hdd-temp-readout-or-s-m-a-r-t-info-on-drives-in-raid-format

**Comment by qooob** [comment]
I see. Thanks, I will take a look.
