### ISSUE TITLE
Panel divs not displaying like they should for dashboard. 

### ISSUE THREAD

**Issue by SergeantSeven** [qooob/authentic-theme#339]
Hi, Thank you for the wonderful theme. 
First thing i noticed after installing the newest version is that the dashboard is not displaying like it shows in the video. I do notice that the dashboard displays the panels divs in the background when it displays the update info modal. but goes away after dismissing the notice and the page reloads the dashboard. 
So the dashboard where the wonderful charts display server status is completely white without any borders or a contrast against the gauges, text and charts all display correctly but are hard to read against the pure white background. i've tried several things to make sure it wasn't broken upload or cache. any ideas?

**Comment by qooob** [comment]
Hi,

I'm very sorry but I didn't completely understand what you mean.

Could you please attach a screenshot?

**Comment by SergeantSeven** [comment]
![screenshot 2016-01-16 00 01 01](https://cloud.githubusercontent.com/assets/15938327/12371064/5dbfe6f6-bbe4-11e5-89f3-0ee960a88c65.png)

**Comment by SergeantSeven** [comment]
as opposed to the screen shot from the video on your you tube channel. where the system information screen has the bootstrap stylized divs with the panel class, or what i assume is the panel class.

**Comment by qooob** [comment]
Oh, you mean below the System Information table? :)

**Comment by SergeantSeven** [comment]
I just forced an update and tried to capture the system info panel in the background before the update info modal spins in to the viewport. 
![screenshot 2016-01-16 00 06 45](https://cloud.githubusercontent.com/assets/15938327/12371100/3759e3da-bbe5-11e5-9809-34031846e914.png)
And then this pops up, if you dismiss it then it goes back to the way it looks in the first screen shot.
![screenshot 2016-01-16 00 06 49](https://cloud.githubusercontent.com/assets/15938327/12371102/5084f7f0-bbe5-11e5-9a30-0ae2834be9d5.png)

**Comment by SergeantSeven** [comment]
the system information table has a nice header styling and the gauge charts have a nice detente around the edge. which disappears after the first time you load the theme. ideally the way it looks in the second screenshot i posted is how i wished it would look all the time. 
Hope that makes sense.

**Comment by qooob** [comment]
Nick, are you saying that System Information disappears after you close the modal? Can you make video-screencast?

**Comment by qooob** [comment]
Is your browser Firefox?

**Comment by SergeantSeven** [comment]
My browser is firefox. No, the system information does not disappear. just the borders and border radius etc from the div (or table) for the system information. refer to the screenshots above.

**Comment by SergeantSeven** [comment]
Never mind i feel like an idiot now. Apparently after i replace my computer monitors the display settings were set to something wacky, I couldn't see what i was talking about because my monitors where washing out the lighter colors. when the modal pops up it greys out everything in the background and i can see it, but when it returns to light colors again i couldn't see it. i just played with my monitor settings and it fixed it. I really appreciate your responses and I'm sure i confused the hell out of you. great theme and great work. thanks.
