### ISSUE TITLE
Orphaned sidebar notification shows up even when sidebar is disabled

### ISSUE THREAD

**Issue by drkskwlkr** [qooob/authentic-theme#340]
Steps to reproduce the issue:
1. Disable sidebar from Authentic settings
2. Wait for new package updates

As soon as Webmin updater discovers that there are new package updates, the Authentic notifier (the bell icon) will show up. You can click on it, and it will move to the left as if to make room for the sidebar. Another click will return it to the right:
![authentic-bug](https://cloud.githubusercontent.com/assets/6951698/12404947/aa897d7e-be48-11e5-95d3-01546baa4d09.jpg)

Note: A hard refresh (Ctrl+F5) after packages are updated will make the bell icon disappear.

**Comment by qooob** [comment]
Haha :D Thanks, great bug! Will fix it in 17.50!

**Comment by qooob** [comment]
Please expect 17.50 to be released soon. It fixes this issue.

Thanks for reporting.
