### ISSUE TITLE
Collapsable navigation menu in non-mobile mode

### ISSUE THREAD

**Issue by spaziod** [qooob/authentic-theme#341]
I see you now animate left panel sliding upon page open..

How do we close the left panel when not needed?  It chews up a ton of page when not used...

thx

**Comment by qooob** [comment]
I didn't implement this on big screens. If you make window small enough it will be hidden automatically and the trigger appears.

**Comment by qooob** [comment]
What is your screen resolution?

**Comment by spaziod** [comment]
1920 x 1080

just trying to resolve to the parts that are necessary...
thx for checking







*Bob Willingham*

Founder/CEO


*NaviSource Solutions Group <http://www.navisource.com>*

Phone: 800.233.5573 ext.305

Direct:  850.588.4121

Fax:     305.723.0146

**Comment by qooob** [comment]
Do you think it's nessesary to have collapsible left menu even with such resolutions?

**Comment by spaziod** [comment]
nothing is necessary...however, I have moved from the webmin filemanger to
winscp so the window will only display relevant part...   do not need the
menu..

hey, its cool like it is...just wondered why it wasnt collapsible since
that is part of the base code







*Bob Willingham*

Founder/CEO


*NaviSource Solutions Group <http://www.navisource.com>*

Phone: 800.233.5573 ext.305

Direct:  850.588.4121

Fax:     305.723.0146

**Comment by qooob** [comment]
Alright, will keep in mind then for the future. Thanks for advising!

**Comment by qooob** [comment]
Oh, by the way, what do you mean `moved from Webmin Filemanager`? Which one you mean old Java or new Filemin? If the latest, what is missing for you what, what made you switch?

**Comment by spaziod** [comment]
I used the java app for years then had to move to the html.....it is a dog
compared to java app...too slow...not all features or too hard to do basic
tasks so moved to stand alone app

**Comment by qooob** [comment]
Alright, when I finish webmail transformation, I will do my best to make Filemin shine, with Sasha's help (Filemin dev.). I'm not sure why all those features that where in Java filemanager weren't transformed yet to Filemin. I see no particular difficulties there..

Anyway, we'll work it out somehow! ;)

**Comment by qooob** [comment]
I have it in my todo. Probably will do it one day.

Thanks.
