### ISSUE TITLE
new version breaks filemin edit function

### ISSUE THREAD

**Issue by sle44102** [qooob/authentic-theme#342]
New version of theme seems to break FileMin.
If you try to edit a .conf file, you get a right click menu where most are showing as Undefined.
If you turn of right click with js override, it works as in the old days.

**Comment by qooob** [comment]
What browser are you using and what is the Filemin version?

Post a screenshot please, as I don't completely understand where it's not working. I tested it and it worked fine.

Did you reload Webmin/cleared cache?

**Comment by qooob** [comment]
In case you've just updated Webmin  -  you must update the theme manually as it delivers the old version of the theme. https://github.com/qooob/authentic-theme/issues/316

**Comment by sle44102** [comment]
Was going to reply on git but thread is closed.
I think your comment about fresh update must have been it.
I restarted the system and manually updated, now the behavior is gone!

**Comment by qooob** [comment]
Good to hear. ;)
