### ISSUE TITLE
Webminstats fails in Authentic

### ISSUE THREAD

**Issue by expertdecisions2** [qooob/authentic-theme#343]
Webminstats module (http://webminstats.sourceforge.net) fails to shows "panorama general" option", until previous version of Authentic, Panorama General was visible (but badly formated). Now I get the circle spinning for ever. Rest of Webminstats functions are working correctly.

If I switch to Virtualmin Framed Theme, everything goes OK.
What I'm unsure is if the issue comes from Webminstats or Authentic but what is true is Wenminstats does well with other Themes.
![captura de pantalla 2016-01-24 a las 11 32 23](https://cloud.githubusercontent.com/assets/9258503/12535808/f3174c24-c28f-11e5-8004-7b8326ab1f57.png)
![captura de pantalla 2016-01-24 a las 11 33 01](https://cloud.githubusercontent.com/assets/9258503/12535811/002107c0-c290-11e5-80d2-13929aba1fed.png)
![captura de pantalla 2016-01-24 a las 11 34 55](https://cloud.githubusercontent.com/assets/9258503/12535812/07a9adee-c290-11e5-8e54-8bc6899786d2.png)

**Comment by qooob** [comment]
This module has to be updated to fully follow default standards. Having default `footer()` and `header()` is a must in my opinion.

You can dismiss the loader by clicking on the cross button near the loader or clicking escape key.

Probably, resetting browser's cache could help and restarting Webmin. Latest theme release didn't do anything in relation to the loader to be stuck. Loader can also be disabled in theme's settings.

Regards,
Ilia
