### ISSUE TITLE
Blinking cursor

### ISSUE THREAD

**Issue by Deepcuts** [qooob/authentic-theme#344]
I see a problem with the blinking cursor in Usermin.
In almost all user input fields, the blinking cursor is displayed like this:
![1](https://cloud.githubusercontent.com/assets/4704834/12543303/d3be744a-c336-11e5-88fe-f8bc5b3db4a2.png)

The problem is seen in Chrome & Internet Explorer.(the only two I tested with)

**Comment by qooob** [comment]
Please read Troubleshoot section on main page (README.md). You need to set UTF8 encoding to make it go away.
