### ISSUE TITLE
Strange characters in page title

### ISSUE THREAD

**Issue by Deepcuts** [qooob/authentic-theme#345]
Not a real problem but just wondering what might cause these weird characters to appear in both Webmin/Virtualmin & Usermin page titles
![3](https://cloud.githubusercontent.com/assets/4704834/12543398/d5b9d806-c337-11e5-8690-eef3687a4e7e.png)

**Comment by qooob** [comment]
Read Troubleshoot on main page please. It's non UTF encoding issue.
