### ISSUE TITLE
File Manager - Feature Suggestions

### ISSUE THREAD

**Issue by jbrice** [qooob/authentic-theme#346]
1 - Need to be able to find out target of symlinks (essential).
2 - Be able to copy/paste back into same location with auto-rename e.g. with appended .copy (very useful for making local copies of .conf files).

**Comment by qooob** [comment]
When we come to the general conclusion of what it's going to be [#89](https://github.com/Real-Gecko/filemin/issues/89) further with Filemin support in Authentic Theme, I will either implement all _features_ in forked version of Filemin or all feature request and UI problems would be directed to initial Filemin developer. It'll take some time to sort the things out.

Thank you for your suggestions.

**Comment by qooob** [comment]
Will do soon. Thanks for the idea. Probably in 17.54.

**Comment by qooob** [comment]
17.54 will show you the target for symlinks.. All you gonna need is to hover on symlink or it's icon to find out the symlink's source! ;)

**Comment by jbrice** [comment]
Excellent! Thank you - suddenly the File Manager is 100% more usable. :-)

**Comment by qooob** [comment]
:)

**Comment by qooob** [comment]
However, hovering only on icon's link (the one on the left), would make more sense. So, I will keep it only to the img. ;)

**Comment by qooob** [comment]
Second option is added to todo.

**Comment by qooob** [comment]
It's there - please upgrade. Is that what you wanted?
