### ISSUE TITLE
File Manager bookmarks

### ISSUE THREAD

**Issue by Schnuecks** [qooob/authentic-theme#347]
Hello i added dirs to the bookmarks but they not shown.

The bookmarks are shown in the list after adding, but after reload its gone.

![bookmarks_conf](https://cloud.githubusercontent.com/assets/4294371/12550875/c4a33790-c366-11e5-9614-4b1196a3a580.png)

![bookmarks_open](https://cloud.githubusercontent.com/assets/4294371/12550879/c94c722a-c366-11e5-91cf-5e7c80e134d2.png)

**Comment by Real-Gecko** [comment]
[Update Filemin](https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-1.0.0.linux.wbm.gz), be happy :)

**Comment by qooob** [comment]
@Schnuecks Hi,

In case you're using bundled with Webmin version of Filemin 0.9.6 - there is no problem. Make sure that you have installed latest 17.52 version of the theme. Clear cache afterwards. In case you still have a problem, please make video-screencast with opened console to sort the things out.

**Comment by Schnuecks** [comment]
Hello thanks for reply,
i dont want to update to filemin 1.0 because its opened with an own ui.
So i use 0.9.6, but it doesn't work as intend for.

Here the screencast, thanks.
http://www.screencast.com/t/wjd5lg2pNgk

**Comment by qooob** [comment]
I see. This is informative. I also noticed some other bugs.

Are you using IE? Could you try Chrome or Firefox? I have never experienced such problems. I'm releasing 17.53 in an hour, it will support all possible actions from context menu and will have options to remove toolbar completely and make it look even more sleek.

**Comment by Schnuecks** [comment]
Ah ok, 

i've tried it in ie and chrome, both show the same behavior. If the update is available i will try again. If you need more information or logs let me know.

**Comment by qooob** [comment]
Thanks! I would need to see, what is happening in Network tab of the browser's console when you click `Bookmark this folder`.

Oh.. Maybe you would need to do few things.
  1. Make sure that both Webmin global settings and Webmin Language and Theme module have language set to UTF-8.
  2. Completely remove (or save somewhere else current favorites..)

This is what I mean when it works fine:
https://rostovtsev.ru/pub/src/authentic/17.52b/filemin_working_bookmarks.webm

Try reloading Webmin if doesn't help. and reloading the server as the last solution.. If doesn't help, please check in Chrome in Firefox.. and if still doesn't work, please post data from Network tab of browser's console.

**Comment by qooob** [comment]
Does it work for you now?

**Comment by qooob** [comment]
I think it's Filemin bug that happens on some Linux distros as a result of permission problem.

https://github.com/qooob/authentic-theme/issues/389

**Comment by qooob** [comment]
Please read more in #389

**Comment by qooob** [comment]
Hi, Schnuecks !

Authentic Theme 17.80 will have new mechanism for working with bookmarks. Options will not be needed anymore. You will just need to click on the little remove button near the bookmark to remove it and adding will be the same intuitive way.

Your issue with wheel users will be also fixed. You will need `Filemin` that is distributed with Webmin.

Thanks for reporting! ;)
This is how it's going to work in 17.80+
http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-new-bookmarks.webm

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
