### ISSUE TITLE
Cloudmin start page settings should include system overview

### ISSUE THREAD

**Issue by datenimperator** [qooob/authentic-theme#348]
Authentic start page config options include

- Default tab after logging in: Webmin or Cloudmin (I assume Virtualmin as well on those systems)
- Default page for Cloudmin: <any configured system>

However, best start page for me is the "List managed systems" page, because it's easy to see pending updates there. Please add that as a config option.

**Comment by qooob** [comment]
Sure, I will. In 17.53. Thanks for the good idea.

**Comment by qooob** [comment]
It's a good idea. I also added the same option for Virtualmin. Please upgrade to 17.53. 

Is this what you expected?

**Comment by datenimperator** [comment]
Much better now, thanks a lot!

**Comment by qooob** [comment]
Sure. You're welcome.
