### ISSUE TITLE
Have a "select all" for groups

### ISSUE THREAD

**Issue by datenimperator** [qooob/authentic-theme#349]
I wanted this in Cloudmin for a very long time: Managed systems can be organized in groups. There's a global "select all…" option, but none for groups. Having the new theme, I wonder if a "select all" for groups would be feasible, too.

**Comment by qooob** [comment]
Where exactly this is? Could you please provide the screenshot?

**Comment by datenimperator** [comment]
Sure, there you go:

![list_managed](https://cloud.githubusercontent.com/assets/112130/12554135/60f6b39c-c37b-11e5-9a8c-32e8795e7840.png)

This is "List managed systems" on Cloudmin.

**Comment by qooob** [comment]
I will talk with Cloudmin developer and in case they will not do this in the next release.. I will do it with ease. I just think that the theme shouldn't do such functionality.

Let's wait for developer reply.

**Comment by jcameron** [comment]
This is really a Cloudmin bug - I'll fix it up.

**Comment by qooob** [comment]
Thank you for clearing this up.

**Comment by jcameron** [comment]
A fix has been committed for the next Cloudmin release.

**Comment by datenimperator** [comment]
@jcameron any news regarding the next release which would include this fix?

**Comment by qooob** [comment]
What Cloudmin version do you have? I have `Select Webmin systems` under `8.4 Pro`?

**Comment by datenimperator** [comment]
```
Operating system	Debian Linux 7
Webmin version	1.791
Cloudmin version	8.4.real Pro
Theme version	Authentic Theme 17.83
Kernel and CPU	Linux 3.2.0-4-686-pae on i686
```

As I wrote before, "Select webmin systems" is there but no "select all" per group.

**Comment by qooob** [comment]
Ah, alright. Jamie probably missed that. Let's wait to his reply.

**Comment by jcameron** [comment]
The next release which will include this fix should be out this week.
