### ISSUE TITLE
calculate folder's size With filemin for clients after upgrade to 17.53

### ISSUE THREAD

**Issue by hasanalsamra** [qooob/authentic-theme#350]
I have noticed after i have upgraded to 17.53 that when the client click on calculate folder's size at context menu it will not calculate its size always displays 0 byte.
Thx.

**Comment by qooob** [comment]
I will take a look.

Meanwhile, reload/clear browser's cache and restart Webmin. If you go to theme's settings and choose autocalulation feature, will it work then?

**Comment by hasanalsamra** [comment]
I Cleared the cache and i have restarted Webmin and i changed the setting to autocalculate but it did not solved the problem

**Comment by qooob** [comment]
Are you sure that you have upgraded the theme for the users. You're talking about Usermin, right?

It works for me and others I talked with in Webmin/Usermin and in other distributions... in both root and user modes.

Have a look. 
https://rostovtsev.ru/pub/src/authentic/17.54b/working_file_size_detection.webm

In case it's not the same for you, please make video-screencast with opened console and will figure this out.

Which browser are you using by the way?

**Comment by hasanalsamra** [comment]
The problem is in virtualmin and only for clients it is working with root only
in usermin it is working very well for all clients
I am using Google Chrome
but anyway i will give you a link for a screencast after i did in couple mins.

**Comment by qooob** [comment]
Mmm.. I see. I'll test in VM mode.

**Comment by hasanalsamra** [comment]
Here is the link http://hasanalsamra.tk/sc/sc.ogv

**Comment by qooob** [comment]
Thanks! I see. I will try fixing it in 17.54 very soon.

**Comment by hasanalsamra** [comment]
Thanks alot for your response and your time
+1 Keep good job!

**Comment by qooob** [comment]
..I'm already fixing it.. I got the cause! Thanks for reporting!

**Comment by qooob** [comment]
Please update to 17.54. All should be working fine.

**Comment by hasanalsamra** [comment]
Yes working thank you so much
:+1:  :)

**Comment by qooob** [comment]
:)

**Comment by sz00gun** [comment]
Indeed calculating folder size is working fine, however what if eg. someone has 25 or more websites to check... Select one by one is a bit annoying process. Is possible to check folder size for all catalogs after clicking on eg.: "Select All" or just add another button "Calculate size"

**Comment by qooob** [comment]
Yes. It's in my list! ;)

**Comment by sz00gun** [comment]
Wow! Sounds good. Hope you won't stop developing this great project after starting work for eg. Google.... ;)

Thanks again for your time developing the theme.

**Comment by qooob** [comment]
This feature will be supported in 17.64. ;) Thank you for the great ideas!

**Comment by qooob** [comment]
..I meant 17.63

**Comment by qooob** [comment]
17.63 will also provide an ability to enter path manually. Read changelog please,

**Comment by qooob** [comment]
Please upgrade.
