### ISSUE TITLE
Bandwidth calculation

### ISSUE THREAD

**Issue by thomasgg** [qooob/authentic-theme#351]
Bandwidth usage is being displayed a bit strange. Running version 17.54.
![screen shot 2016-01-27 at 01 18 47](https://cloud.githubusercontent.com/assets/987519/12599728/b0faae56-c494-11e5-9412-9af68e07b088.png)

Keep up the good work!

**Comment by qooob** [comment]
Hi,

Thanks.

I bet it's not displayed properly in the default theme, right?

**Comment by thomasgg** [comment]
It's not 100% but slightly better
![screen shot 2016-01-27 at 13 04 36](https://cloud.githubusercontent.com/assets/987519/12613000/f9aa7bba-c4f6-11e5-8fd2-53a8a93bfd90.png)

**Comment by qooob** [comment]
You have data set to unlimited?

**Comment by thomasgg** [comment]
Yes, but I assume it would show me how much of all used bandwidth is used per domain?
foo.tld 60%
bar.tld 30%
etc

**Comment by qooob** [comment]
I'll take a look tomorrow morning and I will send you the patch before releasing. I just think all I can do here is to disable line-chart when quotas are set to unlimited.

**Comment by qooob** [comment]
Alright, I managed to fix it and test it. Please let me know if there are some issue... It should be alright in 17.60.

Thanks for reporting.

**Comment by 7starsone** [comment]
I see this on 17.60
![Image of bandwidth issue](http://i65.tinypic.com/16063qh.jpg)

**Comment by qooob** [comment]
Oh, I think I know why it's happening. I'll fix it in 17.61. Thanks for reporting.

**Comment by qooob** [comment]
However, I don't know why..

Can you make a screenshot with opended console and pointing to this bar, please?

**Comment by 7starsone** [comment]
sorry, that's not on bandwidth but on QUOTAS.... hope this helps

**Comment by qooob** [comment]
Please upgrade to 17.61

**Comment by 7starsone** [comment]
same behavior on quotas... I see that 14% with red bar...

**Comment by qooob** [comment]
I don't see how it could be happening. Can you please make video-screencast? If it's private info there for you, send me the link using my website.

Did you try clearing browsers cache, restarting Webmin and refreshing sysinfo page?

**Comment by 7starsone** [comment]
yes, done... but no change always the total red bar and 14%

**Comment by qooob** [comment]
Make video-screencast please with opened console pointing (debugging ) to this element

**Comment by 7starsone** [comment]
no time to do a video now...sorry
![Image of quota1](http://i67.tinypic.com/kw289.jpg)

![Image of quota2](http://i67.tinypic.com/20qhyja.jpg)

**Comment by qooob** [comment]
Wow. I see. I'll take a look in the morning. No video needed at the moment.

**Comment by thomasgg** [comment]
Still showing percentages while all bandwidth is unlimited.
And displaying 'Unlimited' in the quota section while none of the domains are set to unlimited.
This is happening with 17.61.
![screen shot 2016-02-01 at 01 29 29](https://cloud.githubusercontent.com/assets/987519/12706385/cf9a62aa-c883-11e5-816a-d287641c48e4.png)

**Comment by qooob** [comment]
Hi,

Will you be able to assist me, we while I'm fixing it? I never had such content produced? Can you email me or chat using Jabber? If not we could so it here?

**Comment by thomasgg** [comment]
Sure, but I'm having trouble locating your email address. Where can I find it?

**Comment by qooob** [comment]
Please upgrade to 17.62. It should be all fixed. Others already reported that it's fixed. Is it for you?

**Comment by thomasgg** [comment]
Yes :) Thanks!

**Comment by qooob** [comment]
:) Great to hear.
