### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NZCyrus** [qooob/authentic-theme#352]
When a logo is uploaded to display in Virtualmin/Webmin it does so as a floating image and looks great! However, Usermin displays a floating 404 image and not the uploaded logo.

As a side note, I can't find the link where I uploaded this logo in the Virtualmin GUI. Thanks ☺

**Comment by qooob** [comment]
Hi, 

This is right. It's not controlled anymore by VM but by the theme instead.

Yes, I could reproduce the issue. Will be fixed in 17.56

**Comment by qooob** [comment]
..in 17.60 in couple of days. Thanks for reporting.
