### ISSUE TITLE
Left Column Width

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#353]
Hi,

I'm sure this is an easy one, perhaps I've overlooked something so forgive me in advance.

Is there an easy way to set the width the of the "left" column in the theme? I want to make mine a little bit wider.

-Peter

**Comment by qooob** [comment]
Left for navigation menu? :) Hmm. Not yet possible. 

Do want it wider ... will see what I can do.

**Comment by qooob** [comment]
Peter, hi!

It was a bit difficult to make... but next version will have such option for adjusting navigation menu width.

Thanks for the good idea! ;)

P.S. Never seen you for ages in XMPP.. Could you re-add me up again? qooobATjabbers.im
