### ISSUE TITLE
CSF Firewall IPTables Log view

### ISSUE THREAD

**Issue by menditsa** [qooob/authentic-theme#354]
The first column Time overlaps the second column From.

![mwsnap 2016-01-27 01_41_25](https://cloud.githubusercontent.com/assets/3509336/12601334/3e540024-c498-11e5-9085-9a72aa4ffa33.png)

Great work tho

**Comment by qooob** [comment]
That I saw.. Will try fixing it.. Thanks!

**Comment by qooob** [comment]
It will be fixed in 17.60
