### ISSUE TITLE
Search Bar steals focus from Graphical Console

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#355]
Trying to use the graphical console to administer a Windows VM and while trying to enter the password, the search bar steals focus from the password field in the graphical console making login impossible. I have to switch back to an older theme and then back again.

**Comment by qooob** [comment]
Can you please provide more details? Is this Text Login module? Have a screenshot or video-screencast? In case it happens but it really shouldn't, did you try to just make a click in a right frame window to bring focus to it?

**Comment by SteffanCline** [comment]
Graphical Console (VNC through the browser) not Text Console. I clicked in the frame several times to take focus off the search box and back to the console. I'll see if I can make some kind of screen cast or arrange a way for you to view it directly yourself. This happens in Chrome although I didn't try any other browsers.

**Comment by qooob** [comment]
In Chrome, click view frame source. What is the frames URL?

**Comment by SteffanCline** [comment]
view-source:https://xxxxx.com:10000/server-manager/gvnc.cgi?id=1426688912240100

**Comment by SteffanCline** [comment]
Were you able to figure it out or do you still need a screencast?

**Comment by qooob** [comment]
I'm about to get to resolve this issue. I hope I can manage it with any screencasts. I'll let you know in a bit. ;)

**Comment by qooob** [comment]
Thanks for reporting. It will be fixed in 17.60. Tell me how it goes after updating (release is about tomorrow)

**Comment by SteffanCline** [comment]
Yes, it's fixed. Thank you!!
