### ISSUE TITLE
Text Areas and Line Numbers

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#356]
The areas where you have text area with line numbers like when manually editing a BIND zone, the font should be a monospaced font. Your styling doesn't properly show tabs so a tab is converted to a white space.

**Comment by qooob** [comment]
In default theme was there monospace font in default textarea?

**Comment by SteffanCline** [comment]
Yes. All tabs were preserved.

**Comment by davenir** [comment]
I don't know if this is related but I'm seeing strange characters in editors and in the browser title also. I didn't have this on previous theme. Love this new theme though.

![screen shot 012](https://cloud.githubusercontent.com/assets/15016459/12650913/93e17b4e-c5dc-11e5-8b9e-6614b3b9ec41.JPG)
![screen shot 013](https://cloud.githubusercontent.com/assets/15016459/12650914/93e7285a-c5dc-11e5-8e92-b287c9ef6f1e.JPG)
![screen shot 014](https://cloud.githubusercontent.com/assets/15016459/12650915/93ed7e08-c5dc-11e5-876f-c192fcf087b5.JPG)

**Comment by qooob** [comment]
Read front page of the repo. You need to set UTF8.

After you change the encoding does it solve your initial issue?

**Comment by davenir** [comment]
Thanks Ilya - I did this but it made no difference in Virtualmin.
![screen shot 015](https://cloud.githubusercontent.com/assets/15016459/12651841/3421f9c8-c5e0-11e5-977a-d844109ac627.JPG)

**Comment by qooob** [comment]
Check for global Webmin settings and Webmin Language and Theme module.

**Comment by davenir** [comment]
Yes they are both set - no change

![screen shot 017](https://cloud.githubusercontent.com/assets/15016459/12653028/82c5fb10-c5e5-11e5-8387-a27a07e02067.JPG)

**Comment by qooob** [comment]
Checked for VM language? If you can't find, the theme has a language linkbin navigation menu. Enable it in options and then you'll be able to get VM language when on VM.

**Comment by qooob** [comment]
I think the issue should go after you set proper encoding.

I can not reproduce this issue.. all spaces are tabbed.

![screenshot from 2016-01-29 22-01-48](https://cloud.githubusercontent.com/assets/4426533/12685225/1e88e51e-c6d4-11e5-871f-ad0a750a0667.png)

I will update codeMirror with the new release and fix some issues on the black theme for BIND module. If issue persists after 17.60, please let me know, attaching the video-screencast.

Thanks for reporting!

**Comment by davenir** [comment]
Thanks. Still no change for me but I'll see if future updates make a difference.

**Comment by qooob** [comment]
Post a screen shot for the file please? I think your file itself is not properly formatted, maybe?
