### ISSUE TITLE
Position of Webmin and Virtualmin Tabs as they were

### ISSUE THREAD

**Issue by applejack1923** [qooob/authentic-theme#358]
Hi 

This is a very minor issue. I have been using WM / VM for years and am used to having the Virtualmin tab to the left of the WM tab. Not sure why you changed it.

Also the drop down list for the sites could do with being a bit longer which is useful if there are a lot of sites.

Also clicking on the lock icon to view the username and password at least for Safari, desktop the height of the pop up window initially you can only see the username as you have to scroll down to view the password.

As I said very minor, but every bit helps.

After using the new theme I'm beginning to like it a lot, the search and favourites is very useful, so thank you and keep up the good work.

**Comment by qooob** [comment]
Hi,

Thank you for your kind words.

1. New release will have new option - Reverse switch order in _Navigation Menu Options_
2. Select's dropdown will be now 40% of the screen's height
3. I'm not sure how to reproduce it or where to look - give me more info.. direct place where to find it or the screenshot.

**Comment by applejack1923** [comment]
Hi

That's great and thanks for replying so quickly.

Screenshot enclosed of the pop when you click the key icon for a user in VM.

![authentic](https://cloud.githubusercontent.com/assets/1639744/12619817/a72a863a-c511-11e5-94e6-1a55cac4a91b.png)

**Comment by qooob** [comment]
Is this in Edit Virtual Server->Configurable settings?

**Comment by applejack1923** [comment]
Yes and Virtual domain user mailbox details

**Comment by qooob** [comment]
Aha.. Ok.. I will replace these old popup windows with tooltip. Thanks!

**Comment by applejack1923** [comment]
As long as with the tooltip you can copy and paste from

**Comment by qooob** [comment]
Aha.. I'll make sure if there is a selection inside, it will not close.. like with helps now..

**Comment by applejack1923** [comment]
ok great as it is important to be able to copy from.
