### ISSUE TITLE
Virtualmin Domains List in Dropdown Doesn't Hold State

### ISSUE THREAD

**Issue by applejack1923** [qooob/authentic-theme#359]
Previously in the dropdown list of domains in VM if you chose a domain if you then accessed the drop down list again it would position the list at that domain not at the top as is now. It makes it easier to manage things such as sub -servers and aliases etc if the list position is kept at the current selection.

**Comment by qooob** [comment]
I see. It seems that it's default select2 behavior. I doubt that I can/should fix it but I will take a look.

Why not using dropdown search? Are you searching domains manually?

**Comment by qooob** [comment]
However, I just looked at the select2 demo pages and it seems that the position of the dropdwon is saved. I will check and update to the latest version, probably this is what is causing the issue.

**Comment by qooob** [comment]
Does the examples work for you as expected or you having an issue?
https://select2.github.io/examples.html

**Comment by applejack1923** [comment]
Hi Yes those example work.

**Comment by qooob** [comment]
I found out why it's happening. Of course, the select and content is rebuild each time. I found the way to fix this bug and make it work expected way.

Thanks for reporting.
