### ISSUE TITLE
Server Dropdown Doesn't Always Stay Open From A Tap

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#360]
I have not tested this in any other browser than Chrome but from time to time the dropdown menu will not stay open with a tap as from a laptop. I'll tap on my trackpad and it opens and closes immediately. I am forced to click and drag. Is there a timeout option or something in your UI for this that can be adjusted?

**Comment by qooob** [comment]
No timeout, just the default select2 functionality. I have updated select2 to the latest version and did small changes to the code in this regard. In 24 hours I'm releasing 17.60.

In case it doesn't work after update please post the video-screencast with opened console and I'll try to figure this out.

**Comment by SteffanCline** [comment]
You're sure on top of these things!

**Comment by SteffanCline** [comment]
This is not fixed. It's just as bad as before although I like the fact it opens up further without the scroll bars.

**Comment by qooob** [comment]
Steffan, could you post video-screencast please? I can't imagine how it can look bad?

**Comment by SteffanCline** [comment]
[tapping-closing.mov.zip](https://github.com/qooob/authentic-theme/files/111760/tapping-closing.mov.zip)
