### ISSUE TITLE
Progressive Page Loading

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#361]
The spinner is a nice touch but can you build in something where if a page has progressive page loading such as backups which take a long time, there will be no spinner. It's hit or miss. I have clicked the X on the spinner and it cancelled page loading and other times it stops the spinner and displays the progressive page load status.

**Comment by qooob** [comment]
The spinner should be automatically dismissed upon server data is push to the screen. Which module exactly it didn't work for you?

There is no way that clicking on the cross will tell the server to interrupt page from loading - it will only removes the veil.

You can disable right page loader in theme's settings.

**Comment by SteffanCline** [comment]
"Create New System" is one I am in right now. It's creating a VM from a large image. Backing up numerous images creates a LONG load time too. Spinner is great for forms but not so much for response pages. I'll try disabling the spinner and see how it looks.

**Comment by qooob** [comment]
Ok, let me know what you got palese.

**Comment by qooob** [comment]
Any updates here?

**Comment by qooob** [comment]
I'm closing the issue due to inactivity.
