### ISSUE TITLE
Automatic updates for theme

### ISSUE THREAD

**Issue by lp86** [qooob/authentic-theme#362]
Is there or will there be an automatic update for the theme?

**Comment by qooob** [comment]
It's already there! ;) Enable it in theme's settings!

**Comment by lp86** [comment]
The only thing I see is "Check for Authentic Theme updates" but nothing about automatically installing them.

**Comment by qooob** [comment]
I requires you to click update button from System Information page or Notification Panel. Aside from that the theme is update with Webmin.

**Comment by qooob** [comment]
Maybe I'll create a repo one day.. :)
