### ISSUE TITLE
Updating issue

### ISSUE THREAD

**Issue by minakolta** [qooob/authentic-theme#363]
I have 17.54. and Latest available release 17.60.
when i try to update it redirects me to the dashboard without errors and it's not updated, anybody encountered this before?

**Comment by qooob** [comment]
It happened to me once on the past in Firefox browser. Hard reload the page by Ctrl+Shift+R. It's not the theme's issue I guess. However I have this in the list of hunted/happened bugs. 

You can always try the other browser and/or install theme manually by uploaded file.

**Comment by qooob** [comment]
Did it work?

**Comment by sz00gun** [comment]
I have notice: "Make all accordions expanded" not working, just after the latest update.

qooob could you please confirm this?

![acc](https://cloud.githubusercontent.com/assets/7549566/12699167/f1be2d74-c7a9-11e5-9617-6602f1fd399f.png)

**Comment by qooob** [comment]
Yes, I have made as fix after 30 minutes of first push. Just go to the theme settings and click `Force update`. Forgot one line of code in sysinfo.cgi.

Tell if it worked but it _must_.

**Comment by sz00gun** [comment]
Not sure but I have noticed broken Quotas chart too after last update, have a look
![chart](https://cloud.githubusercontent.com/assets/7549566/12705326/4838c5fc-c867-11e5-9cec-7e8beafc38fe.png)

**Comment by minakolta** [comment]
@qooob Sorry for the late update, I found it working after restarting the browser, a Ctrl+Shift+R as you suggests solves the problem

**Comment by qooob** [comment]
Good to hear! :)
