### ISSUE TITLE
Logo for unauthenticated user isn't been displayed

### ISSUE THREAD

**Issue by Overlord23** [qooob/authentic-theme#364]
Hi, 
nice work man! I love this theme!

I've noticed that the logo for unautenticated users isn't been displayed since version 17.60.
This issue occourred immediately after yesterday's theme update, with the previous version (17.54) the problem is not present.
I tried to upload my system logo again but unfortunately it didn't solve the problem; it seems that the upload ends as expected but the logo isn't been displayed neither on the login page nor in the logo preview.

**Comment by qooob** [comment]
Please just delete the `logo` and `logo_welcome` that you should have in `/etc/webmin/authentic-theme`. Reload Webmin and reupload the logo again. There were some code change on that side. I have test logo upload and it worked for me on both RHEL and Debian distributions.

**Comment by qooob** [comment]
Hmm. It really doesn't work now - confirmed.

Thanks for reporting. I will fix it in 17.61 very soon.

**Comment by qooob** [comment]
Please upgrade to 17.61
