### ISSUE TITLE
Update from status page does not clear the alert on the pop out

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#365]
When I log in, my landing page is the status page. I see there's an update and I click the update button. It works great but does not clear the alert in the right pop out when it finishes.

**Comment by qooob** [comment]
You mean it doesn't mark notification panel's (on the right with the bell) messages as read?

**Comment by SteffanCline** [comment]
No, it does not. I just updated the themes on 8 instances from the status landing page but did not clear/mark as read on the notification panel. It prompts me to install again.

**Comment by qooob** [comment]
Ahh.. Yes I noticed it..I'll take a look, I know about this. You can marknit as read by the right click.

**Comment by qooob** [comment]
Will be fixed in 17.62. Thanks.

**Comment by qooob** [comment]
Please upgrade. The issue must be fixed now.

**Comment by SteffanCline** [comment]
Will update and let you know if it's cleared
