### ISSUE TITLE
After creating a new VM, refresh the left pane so the new VM is in the menu

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#367]
After creating a new VM, it should either refresh the left pane so that the new VM is in the menu OR refresh the left pane AND select the newly created VM.

Example:
OLD WAY
1) Create new Xen instance
2) fill in form
3) creation complete
4) staus is displayed
5) refresh entire window to see the new VM in the left pane drop down
6) select the new VM.

NEW WAY:
1) Create new Xen instance
2) fill in form
3) creation complete
4) staus is displayed
5) refresh the left pane and select the new VM in the drop down as you will most likely need to make some kind of configuration changes.

**Comment by qooob** [comment]
Please make video-screencast as I can't reproduce your issue.

**Comment by qooob** [comment]
The theme does the same logic, as default theme based on Cloudmin running `post_save_server()` function in the following files:

```
boot.cgi
edit_newlinks.cgi
edit_serv.cgi
failover.cgi
find.cgi
get_images.cgi
index.cgi
list_ec2s.cgi
list_gces.cgi
list_ifaces.cgi
mass.cgi
mass_move.cgi
mass_update.cgi
move.cgi
pause.cgi
reset.cgi
save_ec2address.cgi
save_limits.cgi
save_pass.cgi
save_serv.cgi
unpause.cgi
boot.cgi
edit_newlinks.cgi
edit_serv.cgi
failover.cgi
find.cgi
get_images.cgi
index.cgi
list_ec2s.cgi
list_gces.cgi
list_ifaces.cgi
mass.cgi
mass_move.cgi
mass_update.cgi
move.cgi
pause.cgi
reset.cgi
save_ec2address.cgi
save_limits.cgi
save_pass.cgi
save_serv.cgi
unpause.cgi
boot.cgi
edit_newlinks.cgi
edit_serv.cgi
failover.cgi
find.cgi
get_images.cgi
index.cgi
list_ec2s.cgi
list_gces.cgi
list_ifaces.cgi
mass.cgi
mass_move.cgi
mass_update.cgi
move.cgi
pause.cgi
reset.cgi
save_ec2address.cgi
save_limits.cgi
save_pass.cgi
save_serv.cgi
unpause.cgi
```

In case it doesn't, please open _frame's source_ and report filename, where you believe the spinner has to be dismissed.

Thanks.

**Comment by qooob** [comment]
Any updates here?

**Comment by SteffanCline** [comment]
Something recently changed and it *seems* to be working. Please go ahead and close this. I'll post back if it changes.

**Comment by qooob** [comment]
Alright, good to hear.
