### ISSUE TITLE
Process bar at Quotas section showing full after update to 17.61

### ISSUE THREAD

**Issue by iaroel** [qooob/authentic-theme#368]
Thanks for the great theme.

I've just noticed that the process bar is showing full on quotas (on status page sysinfo.cgi) even they are not.
Here is the html:
````
    <strong class="bar" style="width: 100%;">&nbsp;13%</strong>
````

Which should be:

````
    <strong class="bar" style="width: 13%;">&nbsp;13%</strong>
````

I hope that makes sense.

**Comment by qooob** [comment]
Yes, I'm aware of it. Working on it.

**Comment by andyhirsch** [comment]
Similar problem here:
<img width="1103" alt="quota" src="https://cloud.githubusercontent.com/assets/14921186/12712258/5f73b10e-c8c7-11e5-92bb-f8c6cf5d0803.png">

**Comment by qooob** [comment]
Unlimited label is also incorrect?

**Comment by qooob** [comment]
..and 16% doesn't look correct either.

**Comment by andyhirsch** [comment]
Yeah. See on the right. All servers have limited quota. Dont' know why this two are shown as not unlimited. But percentage is wrong anyway.

**Comment by andyhirsch** [comment]
Second server:
<img width="1108" alt="quota2" src="https://cloud.githubusercontent.com/assets/14921186/12712433/97f0f4c8-c8c8-11e5-9526-10f4b6f203a9.png">

**Comment by andyhirsch** [comment]
Percentage over 100% seems ok

**Comment by qooob** [comment]
Ok. Can you print the raw output? So I could figure this out? Because I have totally different output.. 

It's safe:
Open `authentic-lib.cgi` file and

1. Go to Perl modules in Webmin and make sure that you have installed `Data::Dumper` or just install it using Webmin interface (it's very small array printer for Perl)
2. Uncomment last commented block of text, so it looks like this:
```Perl
sub print_array {
    my ($____v) = @_;
    use Data::Dumper;
    print '<pre style="color: red">';
    print Dumper $____v;
    print '</pre>';
}
```
3. Add to the line 609 after `foreach my $t ( @{ $info->{'chart'} } ) {`
The following:
`print_array($info->{'chart'});`

Go back to the browser and reload the Sysinfo Page. Post that raw output from the second server too because it prints data differently. Later tonight, if I can't figure this out myself, will stick with Joe (VM dev) to fix it.

**Comment by qooob** [comment]
Maybe `Data::Dump` should also be installed. However on Debian it just works as it is.

**Comment by andyhirsch** [comment]
Hm, uncommented the print_array subroutine but i'm getting
Undefined subroutine &main::print_array called at /usr/share/webmin/authentic-theme/authentic-lib.cgi line 609.

**Comment by qooob** [comment]
Did you install `Data::Dumper`?

**Comment by qooob** [comment]
..you know.. stay here please.. I think I found the universal way of fixing it..

**Comment by qooob** [comment]
..if you can print it great, if not.. I think I'll do it.

**Comment by andyhirsch** [comment]
Can't get it to work.
Install of Data::Dumper was successful, but it doesn't show up in installed modules...

**Comment by qooob** [comment]
Like I mentioned installing `Data::Dump` is also need.

**Comment by andyhirsch** [comment]
Data::Dump is installed

**Comment by qooob** [comment]
Strange. and the function doesn't run?

**Comment by qooob** [comment]
restaring Webmin maybe?

**Comment by andyhirsch** [comment]
copied the subroutine to the top, now it works...
`$VAR1 = [
          {
            'chart' => [
                         100,
                         101,
                         0
                       ],
            'value' => '101.91 MB of 100 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         101,
                         0
                       ],
            'value' => '101.42 MB of 100 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         101,
                         0
                       ],
            'value' => '50.57 MB of 50 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         100,
                         0
                       ],
            'value' => '100.84 MB of 100 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         96,
                         0
                       ],
            'value' => '192.70 MB of 200 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         93,
                         0
                       ],
            'value' => '102.75 MB of 110 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         91,
                         0
                       ],
            'value' => '200.89 MB of 220 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         90,
                         0
                       ],
            'value' => '90.36 MB of 100 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         85,
                         0
                       ],
            'value' => '85.76 MB of 100 MB',
            'desc' => 'xxx'
          },
          {
            'chart' => [
                         100,
                         85,
                         0
                       ],
            'value' => '127.79 MB of 150 MB',
            'desc' => 'xxx'
          }
        ];`

**Comment by qooob** [comment]
Yeah! Cool! I know how to fix it now!

I will post here when 17.62 is ready! Thanks! ;)

**Comment by qooob** [comment]
Please upgrade. The issue must be fixed now.

**Comment by andyhirsch** [comment]
:+1:  Looking good!

**Comment by qooob** [comment]
Uff. :D

**Comment by 7starsone** [comment]
ok, my bar now is green at the right place, with the expected 14%

**Comment by qooob** [comment]
Good. ;)

**Comment by iaroel** [comment]
Thanks looking great.
