### ISSUE TITLE
Tabs are taking 100% page's width in Internet Explorer 11

### ISSUE THREAD

**Issue by BrettRow** [qooob/authentic-theme#369]
Using 17.62 in Webmin 1.780 on Internet Explorer 11, the Webmin and Dashboard tabs at the top of the window now occupy 100% of the page width and not just the width of the navigation menu as previously done.
The same anomaly is not present in Chrome or Edge. I have tried resetting the cache but nothing seems to help.

**Comment by qooob** [comment]
Provide screenshot please?

**Comment by BrettRow** [comment]
![authentictheme17 62](https://cloud.githubusercontent.com/assets/8628540/12716152/2c008638-c8e7-11e5-8bf3-a82955bbf4d6.png)
Hope this is okay.

**Comment by qooob** [comment]
I see. IE explorer is a dinosaur :) I'll fix it in the next release. Thank you very much for reporting!

**Comment by qooob** [comment]
Please upgrade.

**Comment by BrettRow** [comment]
All fixed up - Thank you

**Comment by qooob** [comment]
:) You're welcome!
