### ISSUE TITLE
Apply limits from new plan if un-ticked doesn't save state

### ISSUE THREAD

**Issue by applejack1923** [qooob/authentic-theme#370]
In Edit Virtual Server > Configurable settings > Account plan. The tick box for Apply limits from new plan if changed always stays ticked even after saving as un-ticked. This is not Authentic specific as the same happens in the framed theme.

**Comment by qooob** [comment]
This is true. I will notify developers about this bug.

**Comment by qooob** [comment]
I have notified developers. Thanks for reporting.
