### ISSUE TITLE
webmin / virtualmin menu width issue (Theme V17.62)

### ISSUE THREAD

**Issue by Chaots** [qooob/authentic-theme#371]
in IE11 (win 7) the global menu options (Webmin / Virtualmin) cover the full horizontal width. this makes restart buttons in the top right vavigation inaccessable.

the webmin / virtualmin "tabs" should be contained in the horizontal width that the left menu has.

Firefox seems to work fine.

**Comment by Chaots** [comment]
never mind this report,
duplicate of #369 

Kind regards

**Comment by qooob** [comment]
Yes, it will be fixed most likely tomorrow.

**Comment by qooob** [comment]
Please upgrade.
