### ISSUE TITLE
Issue /  Firewall Dashboard Notification

### ISSUE THREAD

**Issue by montgomerykern** [qooob/authentic-theme#374]
I have noticed in recent updates that even though my CSF firewall is running on the server and functioning as expected the theme dashboard status always says "Stopped" in addition to this while viewing notifications on the New right hand notifications even though its at the latest revision it is generating large multiple update notifications for the firewall. 

I am attaching an image of the issue in firefox osx all most recent releases, however i have cross browser and platform tested this and regardless of the platform or browser this issue persists. 

![dashboard-firewall-stopped-but-running](https://cloud.githubusercontent.com/assets/6721390/12834307/74b2154c-cb74-11e5-90c1-3feb961cec66.png)

**Comment by montgomerykern** [comment]
There are new notifications since I cleared out approx 50 about 45 mins ago.

Cheers!

![new_notifications-since-removal](https://cloud.githubusercontent.com/assets/6721390/12834601/a985294c-cb76-11e5-834a-44218b7d06b9.png)

**Comment by montgomerykern** [comment]
I have manually made some changes and restarted Webmin a couple times  and the first issue has ceased to display a "stopped" firewall. I have cleared the notifications as well and am waiting to see if that is still an issue. I apologize this may not have been a needed report. 

It may have just been difference in environment and setup with webmin.

**Comment by qooob** [comment]
You must pay close attention to this label. Because if you have firewalld installed, upon boot it autostarts (at least on Fedora 23) even though its disabled and lfd goes disabled. On the main page of CSF it says that all is fine but its not.

Do the following, 

1. service firewalld status (if enabled turn it of and restart csf and lfd `csf -ra`)
2. service csf status 
3. service lfd status

About notifications, if you still have this issue, go to theme's settings and clear cache.

Another point is that you have to update the theme (yours is very old. 17.62 is our already). I also recommend enabling auto updates notification feature to be enabled. (Webmin->Webmin Configuration->Themes).

**Comment by qooob** [comment]
You should uninstall firewalld completely to avoid accidental problems...or do checks upon each reboot.

**Comment by qooob** [comment]
Theme check for the running lfd in a very simple and relying way: `pgrep lfd`.

Anyway, write back and reopen the issue in case you face a bug again.

Good luck.

P.S. Update to 17.63 please.

**Comment by montgomerykern** [comment]
I really appreciate the suggestions and help with this. I did update the theme manually and checked to make sure it was set to autocheck for updates it was so not sure why it was not telling me an update was available.

I ran through the cli instructions you gave me, ( Thanks for that also ) and I do not have firewalld installed on this box. Its actually a debian 8 box catered to a NGINX server and I have verified that the firewall service is running. That problem has resolved now. 

I have after the update cleared the cache and restarted webmin and shortly after doing so I got two more notifications of an update for CSF in the notifications panel on the right side. Curiously they always say _NULL_ like above in the image.

I go to the CLI and do a csf -u 

/#csf is already at the latest version: v8.12

I am still getting a footing for webmin template creation but do look to do development help more as soon as I get more familiar with it.

Cheers!
Monte

**Comment by qooob** [comment]
Thank you.

**Comment by montgomerykern** [comment]
Greetings Ilia,

I can confirm in the latest version of the theme. That the Notifications for CSF firewall on the dashboard something is clearly wrong with it. I am constantly having to remove upwards of 20 notifications that a new version of the firewall is available the version is _NULL_ as before and I am attaching another screenshot.

I don't believe this is due to a misconfiguration issue. Let me know if there is any information I can grab or etc. to assist with this bug.

![webmin_auth_screen_notifications_capture](https://cloud.githubusercontent.com/assets/6721390/12904277/3ebf122a-ce9c-11e5-9972-a4b3fa29959b.png)

**Comment by qooob** [comment]
I see now. I have made a fix for that and you will not see`

**Comment by qooob** [comment]
I see now. I have made a fix for that and you will not see this message again.

However, there are reasons why you're seeing it at the moment.
1. There is no connection to `download.configserver.com`
2. `download.configserver.com` - `85.10.199.177` IP is blocked?

Tell me which one is that for you? ;)

Next version will prevent those messages in case reasons above are met and will not disturb you any further. Don't forget to clear cache after theme upgrade.

Thanks for reporting.

**Comment by qooob** [comment]
Try to search if CSF blocked their IP for some reason?

`csf -g 85.10.199.177`

Is it there?

**Comment by qooob** [comment]
If it's not there, then `ping 85.10.199.177` must not work for you..

**Comment by montgomerykern** [comment]
root@atom:/# csf -g 85.10.199.177

Chain            num   pkts bytes target     prot opt in     out     source               destination         
No matches found for 85.10.199.177 in iptables
You have new mail in /var/mail/root
root@atom:/# ping 85.10.199.177
PING 85.10.199.177 (85.10.199.177) 56(84) bytes of data.
64 bytes from 85.10.199.177: icmp_seq=1 ttl=45 time=121 ms
64 bytes from 85.10.199.177: icmp_seq=2 ttl=45 time=120 ms
64 bytes from 85.10.199.177: icmp_seq=3 ttl=45 time=122 ms
64 bytes from 85.10.199.177: icmp_seq=4 ttl=45 time=121 ms
64 bytes from 85.10.199.177: icmp_seq=5 ttl=45 time=121 ms
64 bytes from 85.10.199.177: icmp_seq=6 ttl=45 time=122 ms
64 bytes from 85.10.199.177: icmp_seq=7 ttl=45 time=119 ms
64 bytes from 85.10.199.177: icmp_seq=8 ttl=45 time=119 ms
^Z
[17]+  Stopped                 ping 85.10.199.177
root@atom:/#

**Comment by qooob** [comment]
Hm. Then it's some other reason. I have fixed it anyway and you mustn't see any false messages anymore. Thanks.

**Comment by qooob** [comment]
17.64 is out, please upgrade.
