### ISSUE TITLE
Mailman Mailing Lists containing "new" have all-green buttons

### ISSUE THREAD

**Issue by ElpyDE** [qooob/authentic-theme#375]
Hi,

I found a small bug that seems to be related to this theme:

In any table showing mailman mailing lists (per domain or global), the buttons of each list which has _new_ in its name, are shown in green (first screenshot).

It happens that they have the class ```btn-success``` assigned for which the background-color is defined in ```/unauthenticated/css/package.min.css```

Example (Delete button of the _unnewsworthy_ list):
```html
<input style="margin-left: 3px;" class="btn btn-default submitter ui_submit btn-danger btn-success heighter-28" name="unnewsworthy" id="unnewsworthy" value="Delete" type="submit">
```

The old theme does not add any similar classes. This is why I suppose a small bug in the logic which adds classes to buttons in Authentic Theme.

__Authentic Theme:__
![authentic_theme](https://cloud.githubusercontent.com/assets/13076019/12852405/1eb4d376-cc2f-11e5-9597-cda4294ab061.png)

__Virtualmin Framed Theme:__
![framed_theme](https://cloud.githubusercontent.com/assets/13076019/12852406/1ed25a68-cc2f-11e5-904b-080a7600463e.png)

Finally: I really like the new authentic theme. It makes using virtualmin fun again. Thanks to anyone who contributed to this great work!

**Comment by qooob** [comment]
You are welcome, :)

I agree that mechanism for guessing colors of the buttons should be _improved_. I will leave this issue open until next release - then I'll fix that.

Thank you for reporting.

**Comment by qooob** [comment]
If you open right frame content's page, what its URL?

**Comment by qooob** [comment]
I mean `view-source`

**Comment by ElpyDE** [comment]
The problem occurs at all tables of _Virtualmin Mailman Mailing Lists_:
Let ```myhost.example.com``` be the host where virtualmin is running and ```example.org``` be one virtual server on that host. Then the green buttons will be on:
```https://myhost.example.com:10000/virtualmin-mailman/``` (mailing lists of all virtual servers)
and on
```https://myhost.example.com:10000/virtualmin-mailman/index.cgi?show=example.org``` (mailing list of only the example.org virtual server)

**Comment by qooob** [comment]
It will be fixed upon next release. Please stay tuned and let me know if it's alright after upgrade.

Thanks for reporting.

**Comment by qooob** [comment]
17.64 is out, please upgrade.

**Comment by ElpyDE** [comment]
__Green buttons have gone now, thanks for your work!__

Unfortunately, the previously red _Delete_ buttons are now gray, too. But that's okay (a confirmation page is shown before any delete action is excecuted) and probably better than accidentally colored buttons, I think.

Without digging further into your code for guessing colors, I'm afraid I cannot suggest any better or even unique selection criteria :-(

**Comment by qooob** [comment]
Yes, they should be labeled by the module itself. Other than that it's all guessing and can't be 100% reliable.
