### ISSUE TITLE
Tab-order / tabindex on forms

### ISSUE THREAD

**Issue by tothand** [qooob/authentic-theme#376]
When filling out a form (eg. new user or new virtual server) I click on the first field, enter the data then press tab the focus is not on the next input box but I guess it is on the label.

The problem with this (beside the number of tabs I have to press :) ) is if the hotkeys are enabled and after finished with one form field I press tab and 'blindly' start typing the data for the next field I can end up in 'weird places' because the focus is on a non-input element and the hotkeys are enabled.

**Comment by qooob** [comment]
Hi,

What hotkeys has to do with all of this, could you please explain, as I didn't get it?

When you press tab, what else did you expect? It's default behaviour? What if you don't have a mouse and that would be the only way to togle radio/checkbox, right?

**Comment by tothand** [comment]
Sorry I wasn't clear.

The hotkeys are just an example of what could happen if the tab order is not what the user expects.
I've expected that if I fill out the username and press TAB I'll end up in the next input field so I continued to type the description but because the focus was not on the next input field as I've anticipated I've ended up pressing some hotkeys and navigated away from the page.

So the hotkeys are NOT part of the problem! The problem is the tabindex of the input fields. The user has to press TAB 2 times to move the focus to the next input field instead of just 1 TAB.

I hope I've managed to describe the situation, sometimes I complicate simple things :)

**Comment by qooob** [comment]
I will take a look and do my best to fix it. What browser are you using?

**Comment by tothand** [comment]
Google Chrome, version 48.0.2564.97

**Comment by qooob** [comment]
It's very funky bug that you're talking about. It's only happening on some page of Virtualmin. I couldn't yet find the cause really. It also works the same in the default theme.

I have made a fix for it and it will be available in the next theme's release.

Thanks for reporting.

**Comment by qooob** [comment]
17.64 is out, please upgrade.

**Comment by tothand** [comment]
Perfect, thx for the fix!
