### ISSUE TITLE
Can't click the message indicator in the top right anymore since 17.63

### ISSUE THREAD

**Issue by Braintelligence** [qooob/authentic-theme#377]
Hey there,

as the title says.

I'm using Chrome Version 48.0.2564.103 on Windows 10 64 Bit with Virtualmin on Ubuntu 14.04 LTS server.

Any ideas?

**Comment by qooob** [comment]
Could you please provide a screenshot or a screencast, as I'm not sure what you mean by message indicator?

Thanks for reporting.

**Comment by Braintelligence** [comment]
![image](https://cloud.githubusercontent.com/assets/6761196/12869238/e5568200-cd19-11e5-8679-2e332345ccea.png)

This thing =).

**Comment by Braintelligence** [comment]
Hmm, it seems to work now, but I don't know what might have caused the functionality to return...

Thanks for the consideration and for your work :).
