### ISSUE TITLE
Virtual Server dropdown menu on mobile device/responsive view

### ISSUE THREAD

**Issue by Braintelligence** [qooob/authentic-theme#378]
Since the other problem was solved by itself I wanted to contribute with something else I have witnessed:

When using authentic theme with a mobile device/in a more tight responsive view there appears a menu button on the top left side, which drags the main menu from the left side. So far, so good.

If you go into the Virtualmin menu and press the virtual server dropdown menu the smartphone keyboard appears, because you can type something in there (to search for a particular virtual server) and as soon as you let go from the dropdown menu it disappears within seconds.

This makes choosing a server in the lower, not visible section almost impossible because you don't have enough time to scroll down and pick something else, nor do you have enough time to type something in and choose anything because the whole dropdown menu disappears within 2~3 seconds after letting go.

I don't know if authentic theme is designed to be useful with a mobile device as well, but if yes, then maybe you should take another look at this :).

Device used: Android 5.1 with Chrome.

**Comment by qooob** [comment]
Yes, good point!

I will improve mobile support and make the issue that you have now disappear.

Thanks for reporting!

**Comment by qooob** [comment]
17.64 is out, please upgrade.
