### ISSUE TITLE
Usage Meter line width

### ISSUE THREAD

**Issue by kreationnext** [qooob/authentic-theme#380]
The usage meter(cpu, ram, etc in the pie chart canvas) line width if made a bit thicker(by 2px to 3px), it would look much better. Not a issue though only a suggested request.

**Comment by qooob** [comment]
Sure, good point, thanks! Will add it to 17.64.

**Comment by qooob** [comment]
17.64 is out, please upgrade.

**Comment by kreationnext** [comment]
I love the authentic theme cuz its elegant and simple. The new update is
great.

but I couldn't stop myself from this.

take a look at the attachment.

**Comment by qooob** [comment]
See no attachment.

**Comment by kreationnext** [comment]
​
tell me you can see the photo.

**Comment by qooob** [comment]
Nope.

**Comment by kreationnext** [comment]
can you send me an alternative email id?

or take a look at
https://drive.google.com/file/d/0B1yUtDYgrFZwdEdqMTRia2ZkQUU/view?usp=sharing

**Comment by qooob** [comment]
I see. I don't like it that think really. I might make this optional in the future.

**Comment by kreationnext** [comment]
thanks for the consideration!

**Comment by qooob** [comment]
Please upgrade to 17.65.

**Comment by qooob** [comment]
There is an option now to satisfy your needs.

**Comment by kreationnext** [comment]
thanks for the update. Its really great! Is there a way to to remove the
hairs on the circle?

**Comment by qooob** [comment]
NO!! :D :D ..at least not yet!

**Comment by qooob** [comment]
Not to scare others with version ~~17.66~~, I just updated the same version (17.65) of the theme, with new option - `settings_sysinfo_easypie_charts_scale`. Go ahead to the theme's settings and __force update__.

You will be able to shave your piecharts' circles and have it smooth, with no _'hair'_ :D.. Minimum recommended value is `0.1` - it will hide the scale and at the same time will prevent cutting on the top.

Good luck! ;)

**Comment by kreationnext** [comment]
okay! will wait for it then.

I will point out something for you here.

The meter is in light grey, and the usage part is  in dark[not so dark
though] green with light grey border.

now when you put it on a white background page, the light grey border isn't
quite visible. So why use the border?

for any border to be visible, it should follow linear color sequence

a. light(background) - dark(border) - light(object)
b. dark(background) - light(border) - dark(object)

but in the meter its
light(white background) - light (light grey border) - dark (green usage
meter)

as such when you look normally, the border is not visible

**Comment by qooob** [comment]
You shouldn't wait for it. It's already repacked in the version 17.65 - just reinstall current version and you will have it now.

I think I know what you mean and it will be gone after you reinstall 17.65.

**Comment by kreationnext** [comment]
That is "awesome" in one word.

You are superb. And definitely you have a sharp razor.

Just changed the chart width to '8" and scale to "0.1". It looks wonderful.

**Comment by qooob** [comment]
Good to hear, thank you!

**Comment by kreationnext** [comment]
webmin has a configuration for updating packages automatically.

Now you have put in options like check updates for authentic theme as well
as csf.

So why don't you enable an option to update it automatically?

**Comment by qooob** [comment]
It's on for GPL users and probably will be for Pro as well in the future.

I'm discussing it with *mins developers.

**Comment by kreationnext** [comment]
I am using GPL. But I don't see it getting automatically updated in any of
my servers.

Another thing I would point out.

the refresh button on webmin home [top - right hand side green refresh
button], the save button [example: webmin theme save button]... etc where
there are any ajax circles going round, they shake a lot. I started
observing it from last year mid november or december [can't remember]

**Comment by qooob** [comment]
They only shake in Firefox but not Chrome. I will try fixing it later if it's technically possible.

By automatic updates I meant, `Update Notification`, not automatic updates itself. For doing fully automatic, I would need to create a repo. As Authentic Theme bundled with Webmin, it's also updated with Webmin. We will try to stick to this logic in the future, as getting so many updates annoys some users, especially if you have to update hundreds of servers.

**Comment by kreationnext** [comment]
Hello,
You changed the canvas width from 160=>170 and the circles are getting cropped.
https://drive.google.com/file/d/0B1yUtDYgrFZwMUY4R2hfX25MLTg/view?usp=sharing

**Comment by kreationnext** [comment]
Hey,

I just signed the petition ". @narendramodi @PMOIndia @imrankhanPTI @United
Nations: Release of Indian Wing Commander Abhinandan with honour from
Pakistan" and wanted to see if you could help by adding your name.

Our goal is to reach 35,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/kSrbYNLDSM

Thanks!
Chandra
