### ISSUE TITLE
Usermin page refresh

### ISSUE THREAD

**Issue by NZCyrus** [qooob/authentic-theme#382]
I have set seconds between automatic mailbox refreshes to 120 in Usermin. I notice that the mailbox is refreshed and displays new mail if arrived.

However, this mail arrived should also display as (1) or (2) in the browser tab as well as a display of new mail alongside the inbox menu tab, but doesn't do so as the menu items are not refreshed along with the mailbox page. For it to do so for both instances, I have to refresh the entire page in my browser. The unread mail then show correctly in the browser tab as well as alongside the Inbox menu tab. 

This is a helpful indicator when mail arrives when I am browsing with other tabs and lets me know that there is new mail in my inbox.

Thanks for your invaluable contribution and hope that my above query makes sense :)

**Comment by qooob** [comment]
Yes, it makes sense but I'm going to completely rebuild mail and make it look and feel much more contemporary.

At the moment I will not do such small fixes as soon it'll be changed overall.

**Comment by NZCyrus** [comment]
Not a problem. Thanks for your response and looking forward to your new build :+1:

**Comment by qooob** [comment]
In my prognosis it will happen in version 18.00 of the theme (around middle of the spring-summer). Will see how the things go.

Thanks for reporting.
