### ISSUE TITLE
Filemin Option

### ISSUE THREAD

**Issue by mitguru007** [qooob/authentic-theme#383]
Hello!
First thanks for authentic theme.
In v 17.64 filemin option missed. only shortcuts available. but option was good then shortcuts. so please add same filemin option of v 17.62 in new version theme. 
![2016-02-11_145513](https://cloud.githubusercontent.com/assets/13175392/12973290/3a3347ee-d0d1-11e5-9ce3-0e89ff8d61c2.jpg)

Thanks,

**Comment by qooob** [comment]
It will be added to module's options in the feature. Meanwhile, you can enable Toolbar back in the theme settings.

**Comment by mitguru007** [comment]
yes, got it, Thanks
