### ISSUE TITLE
17.64 broke search clicking

### ISSUE THREAD

**Issue by Braintelligence** [qooob/authentic-theme#384]
Hello,

since 17.64 (I verified it worked in 17.63) I can't click on search results in the webmin search bar anymore so as to invoke a link visit.

For example: If in Webmin you type postfix into the searchbar it shows one search result postfix mail server but if you click on it nothing happens.

**Comment by qooob** [comment]
Clicking with mouse in Chrome?

It works with keyboard, right? Also works in Firefox.

**Comment by Braintelligence** [comment]
I confirmed keyboard works. 

Clicking with mouse in Chrome doesn't.

**Comment by Braintelligence** [comment]
Let me check FIrefox real quick.

**Comment by Braintelligence** [comment]
Firefox Portable v40 clicking doesn't work.
Checking newest version now.

**Comment by Braintelligence** [comment]
Firefox Portable v43.0.1 clicking doesn't work for me.

**Comment by Braintelligence** [comment]
Firefox Portable v44.0.1 also clicking doesn't work for me.
Will wait for further instructions now.

**Comment by qooob** [comment]
I'll take a look.

**Comment by qooob** [comment]
Will be fixed upon next release.

Meanwhile, you can find this `t__wi_p.t__au__c___i("c", true)` string in autentic.min.js and replace it with `setTimeout(function () { t__wi_p.t__au__c___i("c", true) }, 300);`.Afterwards don't forget hard reload browsers cache.

Good luck.

**Comment by qooob** [comment]
Please upgrade to 17.65.
