### ISSUE TITLE
Firefox support is broken?

### ISSUE THREAD

**Issue by MyEternity** [qooob/authentic-theme#385]
![issue](https://cloud.githubusercontent.com/assets/4238023/12994465/ed44afe8-d131-11e5-87c1-7091b96a487b.png)

**Comment by qooob** [comment]
Not sure what is is but after reloading it's ok, right?

**Comment by qooob** [comment]
Tested it and again, it's not a bug, as it only happens sometimes after upgrading the theme and _only_ if you manually interrupt page reload.

In case you think it's happening occasionally with you, please make video-screencast and post it here.
