### ISSUE TITLE
Encoding in Text Areas

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#387]
This screenshot is from me manually editing a zone file in the BIND module. I have not changed any charsets on anything, just the default install. Notice the odd characters for a tab and so forth?
![screen shot 2016-02-13 at 1 31 34 pm](https://cloud.githubusercontent.com/assets/1323544/13029908/404674a4-d256-11e5-9838-2d513e264337.png)

**Comment by qooob** [comment]
Please read [Troubleshoot](https://github.com/qooob/authentic-theme#troubleshoot).

**Comment by SteffanCline** [comment]
The troubleshoot did not fix it.
![screen shot 2016-02-15 at 9 45 20 am](https://cloud.githubusercontent.com/assets/1323544/13054823/e4eb39ae-d3c8-11e5-8951-76ec698b05bf.png)
![screen shot 2016-02-15 at 9 44 50 am](https://cloud.githubusercontent.com/assets/1323544/13054822/e4e9d924-d3c8-11e5-873e-8bc799b72df9.png)

**Comment by qooob** [comment]
Take a look at this video screencast. It's quite the same issue.

The module `Webmin-Webmin Change Language and Theme can override global settings.`

http://rostovtsev.ru/pub/src/authentic/17.70b/Screencast_from_15-02-16_20:21:04.webm

**Comment by SteffanCline** [comment]
That did not fix it.

**Comment by qooob** [comment]
Hmm. It should. How does the browser detects the page? Can you force it to UTF-8?

**Comment by SteffanCline** [comment]
Odd. Something just changed...
![screen shot 2016-02-15 at 10 10 26 pm](https://cloud.githubusercontent.com/assets/1323544/13067736/fc8ee9ee-d430-11e5-8229-f59918c7bfe6.png)

**Comment by qooob** [comment]
Alright. Restarting Webmin could be needed as well.
