### ISSUE TITLE
problem french accent

### ISSUE THREAD

**Issue by achatom** [qooob/authentic-theme#388]
![screen](https://cloud.githubusercontent.com/assets/17252922/13051393/5775e7be-d3f9-11e5-9055-5d3ccc1a7acc.jpg)

**Comment by qooob** [comment]
You need to set encoding to UTF8

**Comment by qooob** [comment]
The module `Webmin-Webmin Change Language and Theme` can override global settings.

Have a look at video screencast. It's all fine.

http://rostovtsev.ru/pub/src/authentic/17.70b/Screencast_from_15-02-16_20:21:04.webm
