### ISSUE TITLE
File Manager: Existing bookmarks are not shown

### ISSUE THREAD

**Issue by chrispolley** [qooob/authentic-theme#389]
Bookmark dropdown says "No bookmarks yet" when I have 5 bookmarks saved. Possibly related to https://github.com/Real-Gecko/filemin/issues/91 ?

**Comment by qooob** [comment]
It only happens 'first time' - add at least one bookmark, then reload the page. Now when you add new bookmark, it will be added properly.

I know about this bug. It will be fixed in the future releases.

Thanks for reporting.

**Comment by chrispolley** [comment]
No, this has persisted for a while. (several months).  There were some extra LFs at the end of the config, which I deleted, but no change was observed.  But if you have already fixed, go ahead and close this report; I will check back.

**Comment by qooob** [comment]
I have a feeling that it's not fixed.

Please install 17.70 and try again?

**Comment by qooob** [comment]
There should be a directory under your home - `~/.filemin`

And you should have a file called `.bookmarks`.

You must make sure that permissions are correct for the folder. (it should be done automatically).

What linux distros are you at, guys?

**Comment by Schnuecks** [comment]
Hello,
i use Centos 6.x the folder ~/.filemin exist the .boomarks file too.
the creation was not the problem the readout seems not working correctly

I fixed it with the installation of current filemin 1.x 
than I renamed index.cgi to index.old and linked filemin.cgi to index.cgi so that no new tab in webmin is opened, and it works fine, for me.

**Comment by qooob** [comment]
Alright. However, I might be fixing it in the future.

Thanks for reporting.

**Comment by chrispolley** [comment]
It works in filemin 1.1

But I think previously it was because I am logged in to webmin as "admin"
but it acts as if the user is "root" since the bookmarks are in
/root/.filemin/.bookmarks.  Perhaps it was that it wasn't picking up the
correct userid when retrieving bookmarks, although the module config
correctly retrieved them from the ~root folder.

**Comment by qooob** [comment]
Understood. Thanks.

**Comment by qooob** [comment]
Even though it seems to work correctly, Filemin 1.1 doesn't save `bookmarks` to the user home directory.

Administrator users, those that are in the `wheel` group (but not root user itself) doesn't seem to be properly recognized by Webmin. I posted an issue, will see what Jamie thinks about it.

I'll try to enhance bookmarks functionality and detach it from settings page by 17.80 or 17.90 max.

**Comment by qooob** [comment]
Hi, chrispolley!

Authentic Theme 17.80 will have new mechanism for working with bookmarks. Options will not be needed anymore. You will just need to click on the little remove button near the bookmark to remove it and adding will be the same intuitive way.

Your issue with wheel users will be also fixed. You will need `Filemin` that is distributed with Webmin.

Thanks for reporting! ;)

**Comment by qooob** [comment]
This is how it's going to work in 17.80+

http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-new-bookmarks.webm

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
