### ISSUE TITLE
File Manager: Making a copy of existing files in a folder

### ISSUE THREAD

**Issue by NettSite** [qooob/authentic-theme#390]
Hi,

I have a use case where it does make sense to copy and paste into the same folder: making a backup of a file for some purpose. 

I used to copy the file, rename it and then paste.

Now I get a message that it makes no sense.

I should either be able to do the above, or the paste action should rename the file being pasted as "Copy of filename.ext" or similar.

Otherwise, awesome job, you have made Virtualmin into a proper client facing control panel.

**Comment by qooob** [comment]
I totally agree. I just haven't had time to get to it. It's in my todo.

**Comment by NettSite** [comment]
Looking forward to that.

I am impressed that with what I would imagine is quite an extensively used
and complex project, you have only 3 outstanding issues.

Well done!

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by taphawane** [comment]
Thank for your time and the hard work you have done!
There 2 missing feature. 
- Make copy same file in same folder then rename it.
- Search containing text in folder of files.

**Comment by qooob** [comment]
Hi,

Thank you for your kind words.

I will do it a bit later. We haven't  fully decided upon certain things that are related.

Expect it around 17.80, after Webmin upgrade to 17.90.

**Comment by taphawane** [comment]
Great!

**Comment by NettSite** [comment]
I like that second suggestion as well.

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by divyeshsachan** [comment]
This is one of the most required feature by me too but unfortunately is missing and because of this missing feature i have to use another file managers which i don't want.

Hope to see it in next release...

**Comment by qooob** [comment]
Thank you for your kind words.

It's in my to do and going to be done on the next theme release.

I need to finish another part of enormous work on another project.

**Comment by qooob** [comment]
First is done. With 17.80 you will be able to paste to the same folder with new name:

https://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-pasting-files-with-the-same-name-into-current-directory.webm

:wink:

**Comment by qooob** [comment]
..it will also work the same way for directories.

**Comment by qooob** [comment]
..and when copying to the other directory, there will be a prompt for replacing/copying with new name..

http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-pasting-files-with-the-same-name-into-different-direcotry-using-prompt.webm

**Comment by qooob** [comment]
Please upgrade 17.80 is out!

**Comment by NettSite** [comment]
Nice! Thanks.
