### ISSUE TITLE
Strange character at cursor in code editors

### ISSUE THREAD

**Issue by TomasRiker** [qooob/authentic-theme#391]
I'm seeing a strange character ("Â") to the right of the blinking cursor bar in all code editors.
Browser: Chrome on Windows 10, Version 48.0.2564.109 m (64-bit)

![cursor-bug](https://cloud.githubusercontent.com/assets/295205/13073401/e2a293aa-d49e-11e5-8a20-222c6d19a852.png)

**Comment by qooob** [comment]
Please read Troubleshoot.
