### ISSUE TITLE
Strange character in editors.

### ISSUE THREAD

**Issue by leesimple** [qooob/authentic-theme#392]
I've notice that on only one of my installations of Webmin, there is an odd character appearing near the cursor or sometimes on blank lines.  It does not occur on other installations of Webmin using the theme.  All themes are kept up-to-date to the latest versions.

Here is a screenshot showing the character in the "Aliases" box of a virtual domain:

![image](https://cloud.githubusercontent.com/assets/6718986/13084661/1e47ee24-d48f-11e5-8dfb-006e62d1d55c.png)

Here is another shot of the characters within the default http config file editor:

![image](https://cloud.githubusercontent.com/assets/6718986/13084727/6c4b0106-d48f-11e5-9bfb-609f4415bfb6.png)

I've uninstalled and re-installed both Webmin and the theme.

Any suggestions?

Thanks.

**Comment by qooob** [comment]
Please read Troubleshoot. It's encoding settings issue.
