### ISSUE TITLE
Upload option is missing from Filemin

### ISSUE THREAD

**Issue by jumangs** [qooob/authentic-theme#393]
I see the right click option for more file operation options.

But there is no way to upload file inside file min.

**Comment by jumangs** [comment]
![image](https://cloud.githubusercontent.com/assets/4320971/13095067/14662898-d535-11e5-8e9f-683fe7bb935f.png)

I see the option as seen in the image. It would be nice to make it prominent as the download option

**Comment by qooob** [comment]
I didn't understand? To make make what? Could you please write more?

Let me guess, do you want to place `transfers` to the root of the contextmenu?

**Comment by qooob** [comment]
I think, I got what you mean. In case you make this in the root of the context menu, the menu will get even longer. I don't know how often this features is used but I don't like very long context menus. Keeping under new, makes perfect sense.

However, in the future (like major release), I will make upload/download accessible using hotkeys (Like `Ctrl+U` / `Ctrl+D`)

Thanks for the idea.

**Comment by qooob** [comment]
Ok, shortkeys will be added in 17.71. Upload - `F10`, Download `F9`.

**Comment by qooob** [comment]
Please upgrade.
