### ISSUE TITLE
Missing Virtualmin menu

### ISSUE THREAD

**Issue by tehsquidge** [qooob/authentic-theme#395]
Hey,

I having an issue with the virtualmin menu not being loaded, as shown in the screenshot below. I can't see any JS errors and all the http requests return OK. I'm not sure what else you'll need, so let me know what relative information to add!

Thanks,
Liam

![image](https://cloud.githubusercontent.com/assets/3792060/13106524/99887f82-d560-11e5-9eab-6b648424edcc.png)

**Comment by qooob** [comment]
Ahh, ok! You need to update to at least VM 4.16.. but VM 5.0 is out. Just update your packages and you will be fine.

**Comment by tehsquidge** [comment]
Thanks, that fixed it! :)

I actually installed the packages myself, rather than use the script. I didn't realise that only the install script adds the repo, so I've fixed that too.

Cheers,
Liam

**Comment by qooob** [comment]
:+1:
