### ISSUE TITLE
Please bring back ability to turn off content pane spinner

### ISSUE THREAD

**Issue by cruiskeenconsulting** [qooob/authentic-theme#396]
I realize what the intent was here -- to have the spinner disappear when virtualmin/webmin creates screen output.  But it seems not to really work in a lot of different places -notably if you do updates to modules, the spinner takes over and you see absolutely nothing.  Could we get the ability to just turn the thing off back - it's really getting in the way of a lot of work here.

Also --- Just a comment - the number of updates you're producing is maddening when you have a whole lot of servers to maintain

**Comment by qooob** [comment]
I'm planning to slow down update rates. I was asked about this and I remember.

I don't think it would worth it to bring it back. In 90% of the modules/cases, it just makes things feel and look faster.

You're having to show the top progress and the spinner on the top right (they both replace the old, big spinner).

In case you turned it off, you need to manually edit settings.js file or rest theme's settings to default.

I have a thought, that you disabled that top progress bar and now don't see the top and small right progress/spinner?

**Comment by qooob** [comment]
> it seems not to really work in a lot of different places

Could you tell me, where exactly this happens?

**Comment by cruiskeenconsulting** [comment]
Well -- for me just about everywhere the server is putting out information.  For example, as I said, doing RPM updates on the server - the right hand screen is always blank so I have NO idea what is going on - I just get the spinner at the top.  

We're just about ready to go back to the old theme since the new one changes every day and keeps breaking our ability to do work.

**Comment by qooob** [comment]
At first, when you do updates and/or server outputs data - you _must_ see what is happening and the veil _must_ go away, while the screen is scrolled down. It's not? Please name the modules where it's not happening, I will double check.

I made sure, that the user sees server output in all modules, including VM/CM. I can easily provide you with video screencast of how it works. I would like to ask you to do the same, it would make things easier to comprehend.

 > ..since the new one changes every day and keeps breaking our ability to do work.

Theme doesn't change but improves, everyday and all the time. It definitely doesn't break anything. I'm willing to improve whenever I want, and in the end, it's the only reason, why we all have Authentic today.

In case you don't like to see updates or perform updates, just go ahead and turn off notifications for theme updates - your theme will be updated automatically with Webmin (about every 2-3 months).

Why this is an issue at all?

**Comment by cruiskeenconsulting** [comment]
Like I keep saying -- it is not working on our servers.  Every time we do updates, ALLL we ever see is the spinner at the top of the screen.  The whole content pane remains grey until the RPM updates complete -- I see this more or less EVERYWHERE that the server produces updates.  On multiple machines.  All running the latest update.   You can say it runs on your system all you want, but it does not work, for us, and it's really maddening that you're unwilling to accept this as a bug report.

**Comment by qooob** [comment]
I'm very willing to accept it. Did it work before?

**Comment by qooob** [comment]
What browser are you using?

**Comment by qooob** [comment]
I have just made the update and the content of the page was seen.

**Comment by qooob** [comment]
Could you please point out where exactly _EVERYWHERE_ __else__ it doesn't work?

**Comment by qooob** [comment]
This is how it goes on my two different server in two different browsers!

Please have a look:

[Video Screencast](http://rostovtsev.ru/pub/src/authentic/17.71/dismissed_page_loader_upon_server_deta_is_pushed.webm)

**Comment by mlbarrow** [comment]
​For what it's worth, that's what happens for me in Chrome on OS X.​

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by cruiskeenconsulting** [comment]
Not how it works for us at all --- as I said, All I ever see is the spinner until the task completes.

Running on a Fedora Linux desktop, using either Firefox or Chrome I see the same behavior.

**Comment by qooob** [comment]
Did it work before?

I will check it on my MacBook.

**Comment by qooob** [comment]
I checked it exactly on Chrome and Firefox. What is the server OS that it doesn't work with?

**Comment by cruiskeenconsulting** [comment]
Okay so I can confirm - works in Windows, doesn't work in Fedora Linux on the desktop.

**Comment by cruiskeenconsulting** [comment]
Server OS is CentOS 6 or 7 - the problem seems to be that it just doesn't work on a Linux desktop - which I'm perfectly willing to accept if we could turn the spinner off -- everything worked fine in Linux with the spinner off.

**Comment by qooob** [comment]
I'm glad to hear it works in Windows. I don't use it, so for me it's one OS less to test in. ;)

I made those tests in Linux.

Do you use Server Index module to run package updates or the regular way?

Could you please provide video-screencast of how it ~~works~~ on your side with opened console. In case it's private just send me the link using my website.

**Comment by qooob** [comment]
> accept if we could turn the spinner off -- everything worked fine in Linux with the spinner off.

So you just want the ability to turn it off?? Or the spinner itself?

**Comment by qooob** [comment]
How about this?

```CSS
body .container-fluid {
    pointer-events: auto !important;

    opacity: 1 !important;
}
```

Add this to your CSS extensions in theme's settings.

Is that what you wanted really?

**Comment by qooob** [comment]
I know what I'm going to do - provide overall support for all different kind of modules, that don't follow the rules and don't use the footer.

Instead of running that code for all modules (99% of all in-bult modules follow that rule and thus work properly) I will provide a user to specify the list of modules for exclusion.

It means you and anyone using unstandard modules, will be able to add it in exclusion list in theme's settings and be totally happy.

Now I feel _grateful_, as more than one hour of our time wasn't wasted in vain and will provide complete solution for all in the future!! 

Thanks for reporting!

P.S. Are you psychologically ready for another update? :question:  Version 17.72 is coming soon.

**Comment by cruiskeenconsulting** [comment]
Thanks --- that seems helpful.  The CSS change you provided does what I'd like. 

By the way -- the same bad behavior happens if you try to work on the site from the Kindle Fire Silk browser.  Just happens I tried that last night and had the same issue.

**Comment by qooob** [comment]
Very strange. I have tested all of this on CentOS 6/7, Fedora 23, Debian 8, and Ubuntu 13 (server) and (client) on Chrome (Chromium, Opera), Firefox, IE in Linux, Windows and Safari in iOS - all was working.

But it will not matter, since 17.72 will have the ability to disable such functionality selectively by module's `name` or for all modules across Webmin by passing `*` as the value. You will see it at the bottom of `Window options`. The defaults are already set to `sysstats drweb-maild`.

From now on, I will not get any messages about not working modules.

**Comment by qooob** [comment]
Please upgrade to 17.72.
