### ISSUE TITLE
LDAP: List/Table in Users and Groups not sortable

### ISSUE THREAD

**Issue by bdunnaway** [qooob/authentic-theme#399]
The main List/Table in LDAP Users and Groups is no longer sortable by heading.  The sort function works fine in the classic Users and Groups module with this theme.

**Comment by qooob** [comment]
Can you `inspect` the table you're talking about? In Chrome, you could right click on that table that missing sorting and make a screenshot of the source code?

I don't have this module setup?

**Comment by qooob** [comment]
It's easy. Any help?

**Comment by bdunnaway** [comment]
The source is easy enough to access, but the account information is sensitive, since I'm working for a state agency.  I've tried to review it myself, but I can't seem to find any major differences in how the tables are implemented in LDAP Users and Groups and the standard Users and Groups module.

As a matter of fact, the LDAP Users and Groups module calls functions from the Users and Groups module to create the table.  Could it be that you're making an exception for that module to force the table to be sortable?  If so, perhaps LDAP Users and Groups could be included in such an exception.
It very much appears to have used the core Users and Groups module as a base for it's own code, and simply modified it to look up LDAP entries.  They're almost identical.  

I've done a little toward trying to sanitize the page source, to remove sensitive information, but there's still a lot there.  If you feel that's essential to solving the problem, I can spend more time on it.

**Comment by qooob** [comment]
I just need you to copy the selector path using console. I don't care about data.

**Comment by bdunnaway** [comment]
I might need help with that.  I can get the selector for the table, but I don't know how to get the selector path.

**Comment by bdunnaway** [comment]
Best I can tell, the table on the LDAP UaG module has 
#att_users > form > table.table.table-striped.table-condensed

Here's the selector tags for the table:
`<div class="tab-content">
<input class="ui_hidden" type="hidden" name="mode" id="mode" value="users">
<div id="att_users" class="tab-pane active">
<form class="ui_form" role="form" action="mass_delete_user.cgi" method="post"><table class="ui_grid_table table-hardcoded" width="100%">
<tbody><tr class="ui_grid_row"><td align="left" valign="top" class="ui_grid_cell"><a class="select_all btn btn-inverse btn-tiny ui_link_replaced" href="#" onclick="var ff = document.forms[0].d; ff.checked = true; for(i=0; i<ff.length; i++) { if (!ff[i].disabled) { ff[i].checked = true; } } return false"><i class="fa fa-check-square-o"> </i> Select all</a><a class="select_invert btn btn-inverse btn-tiny ui_link_replaced" href="#" onclick="var ff = document.forms[0].d; ff.checked = !ff.checked; for(i=0; i<ff.length; i++) { if (!ff[i].disabled) { ff[i].checked = !ff[i].checked; } } return false" style="margin-right: 3px !important;" data-original-title="" title=""><i class="fa fa-share-square-o"> </i> Invert selection</a><a class="ui_link btn btn-inverse btn-tiny ui_link_replaced" href="edit_user.cgi?new=1"><i class="fa fa-plus-square-o"> </i> Add a new LDAP user</a><br></td>
<td align="right" valign="top" class="ui_grid_cell"><a href="batch_form.cgi" class="btn btn-inverse btn-tiny ui_link_replaced">Run batch file</a><br></td>
</tr></tbody></table><table class="table table-striped table-condensed">
`

**Comment by bdunnaway** [comment]
The original U&G module's tags are like this:
`<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer"><div id="DataTables_Table_0_filter" class="dataTables_filter"><label> <input type="search" class="" placeholder="Filter" aria-controls="DataTables_Table_0"></label></div><table class="table table-striped table-condensed dataTable no-footer" id="DataTables_Table_0" role="grid">`

**Comment by qooob** [comment]
Go to Chrome's console, switch `top frame` to `page` and run the following code:

`__init_dt_($('form > table.table.table-striped.table-condensed'))`

Does it work?

In case it does, take a look at the right frame source and tell me the name of the URL, like `http://example.com:10000/ldap...`

**Comment by bdunnaway** [comment]
Uncaught ReferenceError: __init_dt_ is not defined(…)(anonymous function) @ VM12640:2InjectedScript._evaluateOn @ VM12630:875InjectedScript._evaluateAndWrap @ VM12630:808InjectedScript.evaluate @ VM12630:664

**Comment by qooob** [comment]
What OS browser you have?

**Comment by bdunnaway** [comment]
Just in case it still has some troubleshooting value, the frame source is https://server.example.com:10000/ldap-useradmin/index.cgi  for LDAP UaG, and
https://server.example.com:10000/useradmin/ for the Webmin UaG module

**Comment by qooob** [comment]
Ok, good. What if you add the code I provided to js extension using theme settings?

**Comment by bdunnaway** [comment]
Windows 7 / Chrome Version 48.0.2564.116 m (64-bit)

**Comment by qooob** [comment]
Can you add this `__init_dt_($('form > table.table.table-striped.table-condensed'))` code to `.JS` extension using theme settings?

**Comment by qooob** [comment]
It should initialize your sortings in case you got the selector correctly.

**Comment by bdunnaway** [comment]
I assume you mean to to Webmin Configuration>>Webmin Themes>>Current Theme>>Theme Extensions>>Edit scripts.js and add the line:
__init_dt_($('form > table.table.table-striped.table-condensed'))

**Comment by bdunnaway** [comment]
I tried that, and it doesn't seem to change anything.

**Comment by qooob** [comment]
Then try removing `form >`, try different selector.

**Comment by qooob** [comment]
Any luck?

**Comment by bdunnaway** [comment]
Haven't had the time to do any more troubleshooting.  I did discover that LDAP UaG uses the default sort order from the settings of the standard UaG module, so there's a workaround to tell it to sort by name, but default, but it's still not displaying like a sortable data table.

**Comment by bdunnaway** [comment]
This is working fine after 1.791-1 upgrade.

**Comment by qooob** [comment]
I'm not sure what you mean. Nothing was changed in this regard on the theme's side.

You should still have no ability to sort, I guess.

**Comment by bdunnaway** [comment]
Yeah, I couldn't find any related changes, either.  But it started working.  I have no idea why.
![image](https://cloud.githubusercontent.com/assets/5379537/13757183/47a31506-e9f1-11e5-9817-46dc0e572bd3.png)

**Comment by qooob** [comment]
Can you click bluе back button OR back button on top and see if issue comes back? I have a feeling, that I don't catch URL properly in some cases and when modules name starts to have `index.cgi` it fails.. I already noticed this happening in some cases.

**Comment by bdunnaway** [comment]
I've tried both.  I don't see any change.  Sorting works as expected and everything.  I haven't had time to check, but perhaps the LDAP U&G addon was updated with the last Webmin update.
It appears to be based on, and nearly identical to the standard U&G module.  Since the update it behaves identically, also (the batch processing function was missing before, etc).

**Comment by bdunnaway** [comment]
This is interesting:   On the two servers I have Webmin running on, one of them is not showing the table under "Network Interfaces" as sortable, and the other one is. They are both on Webmin 1.791 and 	Authentic Theme 17.72.

**Comment by bdunnaway** [comment]
I'm getting "uncaught TypeError: __init_dt_ is not a function" on the server that DOES display the table as sortable.  The console shows no error for the other server.

**Comment by qooob** [comment]
I don't see how is this possible in case versions are the same. Did you restart `Webmin` (`# /etc/webmin/restart`) after applying updates?

**Comment by qooob** [comment]
Probably it's something that you left and forgot in theme's custom extensions? Check for it.

**Comment by qooob** [comment]
LDAP started working after Webmin update? LDAP was updated 2 months ago.

**Comment by bdunnaway** [comment]
Wait a second.  The server that's working now, still has the code you asked me to add.
__init_dt_($('form > table.table.table-striped.table-condensed'))

Perhaps that's why other tables are working/sortable (Network Interfaces, Webmin Actions Log, etc), whereas they are not on the server that doesn't have LDAP UaG

**Comment by qooob** [comment]
Try removing that code and see if anything changes - it should, right?

**Comment by bdunnaway** [comment]
Yes.  When I do that, I lose the sortable columns in the Webmin Actions Log (using that for an example)

**Comment by bdunnaway** [comment]
And in LDAP UaG, but not the standard UaG module

**Comment by bdunnaway** [comment]
Okay, so for some reason, putting the code back into scripts.js and restarting the server, does NOT bring the sortable tables back.  Even the ones that worked prior to removing that line of code.

**Comment by bdunnaway** [comment]
So maybe the code fixed it, but it didn't get applied until the Webmin update?  I'm not sure how to get it to re-read that scripts.js file.

**Comment by qooob** [comment]
Script file is re-read each time when the page is reloaded (It should by the browser, no need for restarting Webmin).

Hard reload the page. Which browser are you using?

**Comment by bdunnaway** [comment]
Chrome Version 49.0.2623.87 m (64-bit)

**Comment by qooob** [comment]
Hard reloading will fix stuck cache.

**Comment by bdunnaway** [comment]
Did a hard reload.  The LDAP UaG is now sortable again, but for some odd reason, the Webmin Actions Log table is not; on either server. I was working yesterday before I removed the code.

**Comment by bdunnaway** [comment]
The URLs for the frames that work, and the one's that don't seem very different.
view-source:https://sdoscvsp0022.state.mo.us:10000/ldap-useradmin/  ((SORTABLE))
view-source:https://sdoscvsp0022.state.mo.us:10000/webminlog/search.cgi?uall=1&user=bdunnaway&nuser=bdunnaway&ouser=&mall=1&module=global&tall=1&from_d=&from_m=1&from_y=&to_d=&to_m=1&to_y=&desc=&long=0   ((NOT SORTABLE)
view-source:https://sdoscvsp0022.state.mo.us:10000/net/list_ifcs.cgi  ((SORTABLE))

**Comment by qooob** [comment]
To make Webmin log sortable you would need

`__init_dt_($('table.table.table-striped.table-condensed'))`

Ok, I will make things work well by the 17.80 ;)

**Comment by qooob** [comment]
I'll need you to test things before release, so stay tuned please.

One more time: LDAP sorting is working for you with out an issue?

**Comment by bdunnaway** [comment]
Yes. LDAP Users and Groups sorting works without issue.

**Comment by bdunnaway** [comment]
I'll be happy to help test.  I appreciate your time and patience!

**Comment by qooob** [comment]
LDAP works and you have *nothing* in custom `scripts.js`, right?

**Comment by bdunnaway** [comment]
No.  I still have __init_dt_($('form > table.table.table-striped.table-condensed')) in scripts.js.
If I remove it, LDAP U&G stops being a sortable datatable

**Comment by bdunnaway** [comment]
![image](https://cloud.githubusercontent.com/assets/5379537/13879101/966fb2f8-ece3-11e5-916e-47fddac7093e.png)

**Comment by bdunnaway** [comment]
Here's the URL for that frame: https://sdoscvsp0022.state.mo.us:10000/ldap-useradmin/

**Comment by qooob** [comment]
Great, thanks for saying.

**Comment by qooob** [comment]
Hi,

Could you please remove/comment out `__init_dt_` from extensions `scripts.js` file, update theme's js with this update [17.80b](http://rostovtsev.ru/pub/src/authentic/17.80b/authentic.min.js), clear browser cache (or hard reload, Ctrl+Shift+R) and see if your LDAP Users and Groups are sortable and things look good, could you provide the screenshot of the top of the table starting with `select all` and other switches and ending with the table header in case it works?

Thanks.

**Comment by qooob** [comment]
Will be fixed with 17.80.

Thanks for reporting.

**Comment by bdunnaway** [comment]
Thank you for all your work on this! :+1:

**Comment by bdunnaway** [comment]
I'm actually behind a Websense proxy that blocks .ru addresses.  Can you post that code here?

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
