### ISSUE TITLE
Virtualmin Virtual Servers problem with 17.71 version and Debian 8

### ISSUE THREAD

**Issue by datarush** [qooob/authentic-theme#400]
Hi.
We recently upgraded wing version 17.71 on servers with Debian 8 and Webmin version 1.780. The problem we have found is that no option is not listed in the section Virtualmin Virtual Servers (GPL). I've tried different versions (17.0, 17.2) and all this fails. In systems with Debian 7.8 it does not occur.

Regards.

**Comment by qooob** [comment]
You mean the menu is empty? It means you need to update you're VM installation to at least 4.16 but 5.0 is already out, so I would say to 5.0.

**Comment by qooob** [comment]
This is surely not the theme's bug. I do tests at the moment on Debian 8.

In case you need help, just post it here. I hope/bet all is working fine for you.

Regards,
Ilia
