### ISSUE TITLE
File Manager: Option to overwrite existing files with same name

### ISSUE THREAD

**Issue by Lesrad** [qooob/authentic-theme#401]
Hi,

Please add the option to overwrite an exact match file name from within the file manager.

Currently File Manager does not permit uploading a fresher same named file to replace an existing file it gives an error that the file already exists.

Many thanks

**Comment by qooob** [comment]
I will, in the future as we sort other things out.

**Comment by Real-Gecko** [comment]
Filemin 1.1.0 prompts for overwrite during file upload :D

**Comment by qooob** [comment]
Authentic Theme version 17.80+, when copying to the other directory, will provide user prompt for replacing/copying with new name..

http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-pasting-files-with-the-same-name-into-different-direcotry-using-prompt.webm

**Comment by qooob** [comment]
Expect an update very soon.

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
