### ISSUE TITLE
Small bug in filemin

### ISSUE THREAD

**Issue by ChriZathens** [qooob/authentic-theme#402]
Hello!
I would like to report a small bug:
When in filemin, I select a folder by checking it (_BTW I remember there was a setting to automatically calculate the size of the selected, but can't seem to find it now_), I right click and select Properties ---> calculate selected size.
In the upper left corner it displays ... 

> **Selected: 1 entries 400MB** 

Having left the previous folder checked, I repeat the process 
In the upper left corner it displays ... 

> **Selected: 2 entries 656MB** 

So far so good..
But now, If I uncheck any one of the two selected folders now I have 

> **Selected: 1 entries**

 and no space reported.
If this is on purpose, due to any reason you have, then fine..
Just thought I should report it..
Thanks for your great theme!!!

**Comment by qooob** [comment]
Thank you for your kind word.

This is exactly on purpose, as when selection happens, the size also should change.

**Comment by ChriZathens** [comment]
OK, I see! Great then, thanks!

I also noticed another thing while fiddling around with those filemin selections
Clicking on "select all" button, in the upper left corner it does not realize that all is now selected and it displays 

> **Selected: 0 entries **

even after this , if I right click anywhere on the selected items and select Properties ---> calculate selected size it displays 

> **Selected: 0 entries 880.73 GB**
(It calculates the size, but still says 0 entries)

**Comment by qooob** [comment]
Oh, that must be a bug.

Thanks for reporting, will fi, that.

**Comment by qooob** [comment]
Great discovery, thanks for reporting. It will be fixed in 17.72

**Comment by qooob** [comment]
Please upgrade to 17.72.
