### ISSUE TITLE
Please add CWAF to exclusion list

### ISSUE THREAD

**Issue by TheKigen** [qooob/authentic-theme#403]
The Comodo WAF (ModSecurity rules) module needs to be added to the exclusion list.  Its name for the purposes of exclusion is "cwaf".  I've manually added it and it works now.

http://waf.comodo.com - Requires free registration to get the module.

**Comment by qooob** [comment]
It's added to default exclusion list and will be there since next release.

Thanks for reporting.

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
