### ISSUE TITLE
system and server status in dashboard

### ISSUE THREAD

**Issue by JaySwe** [qooob/authentic-theme#404]
I have opted to see the system and server stati on the dashboard page, but all items are allways green.
While in "- Others - System and Server Status" it shows correctly if the server/service is up.
![webmin dashboard](https://cloud.githubusercontent.com/assets/7734083/13212648/1904d2e8-d943-11e5-9803-23840c4cfa45.PNG)
![webmin sass](https://cloud.githubusercontent.com/assets/7734083/13212649/1909d482-d943-11e5-9e04-fd5bf4a0f2d8.PNG)

Apologies if I have not found the correct way to inform you. I appreciate webmin greatly and one day when I have money I will donate.

**Comment by qooob** [comment]
Hi,

Thank you!

What happens if you refresh system information, will it show correctly then?

I think you should wait a little as System Information not gathered immediately.

**Comment by qooob** [comment]
It's really not the theme issue but Webmin's core. 

We'll try to fix it upon next release! 

Thanks for reporting.

**Comment by qooob** [comment]
I just found out that there is no bug in Webmin and `Scheduled Monitoring` needs to be enabled.

There is a switch called `Scheduled checking enabled?`, enable it and choose time to update.

**Comment by JaySwe** [comment]
Hi Ilia,

I think the issue lies in the fact that i'm running apache and MySQL on a
fixed IP for development, The dashboard seems to listen to default settings
rather then the configured settings (in module/conf/ini ).
The monitor is on 90 seconds, but no status change on dashboard.

No biggie for me, but I guess a dashboard needs accuracy
Thanks for the quick feedack


On 22 February 2016 at 11:08, Ilia Rostovtsev <notifications@github.com>
wrote:

> I just found out that there is no bug in Webmin and Scheduled Monitoring
> needs to be enabled.
>
> There is a switch called Scheduled checking enabled?, enable it and
> choose time to update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qooob/authentic-theme/issues/404#issuecomment-187106215>
> .
>



-- 
Jay van Doormalen

**Comment by JaySwe** [comment]
Hi Ilya,

I think your tip solved it.!

Thanks
Jay

On 22 February 2016 at 11:08, Ilia Rostovtsev <notifications@github.com>
wrote:

> I just found out that there is no bug in Webmin and Scheduled Monitoring
> needs to be enabled.
>
> There is a switch called Scheduled checking enabled?, enable it and
> choose time to update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qooob/authentic-theme/issues/404#issuecomment-187106215>
> .
>



-- 
Jay van Doormalen

**Comment by qooob** [comment]
Ah, ok then.
