### ISSUE TITLE
File Manager - Text editor

### ISSUE THREAD

**Issue by smg** [qooob/authentic-theme#405]
Incorrect TAB code rendering under OS X 10.11 in Safari  and Crome 48.0.2564.116
Attached
![screen shot 2016-02-15 at 16 16 03](https://cloud.githubusercontent.com/assets/175665/13214259/e130b07e-d94e-11e5-96a8-5aa28395ce63.png)
 a screenshot

**Comment by qooob** [comment]
Please read [Troubleshoot](https://github.com/qooob/authentic-theme#troubleshoot), Section 2.

**Comment by smg** [comment]
Thanks for your good work.

It is working.
Regards
Sergio Molino

**Comment by qooob** [comment]
You're welcome.
