### ISSUE TITLE
System Information - Package Update not refreshing after applied

### ISSUE THREAD

**Issue by tac-1** [qooob/authentic-theme#406]
Dashboard - System Information
Package updates shows (11) updates yet all are installed, refreshed, rebooted and Package updates does not reset.
This symptom started on Theme 17.71, I also applied the latest update 17.72 and the problem remains.
Thanks

**Comment by qooob** [comment]
It defenetly has nothing to do with theme updates, especially recent.

There is refresh button for packages on system information page. Click it and it will be refreshed. Theme just processes received data and doesn't do anything on its own.

**Comment by qooob** [comment]
It usually takes 5 minutes to reset package information on the page.

Is it so?

**Comment by tac-1** [comment]
I refreshed, rebooted, even powered off the system and powered back on. Still stuck with (11) updates. 
Software Package Updates
It will not clear. I have it set to check for updates daily (default). I tried changing from the default Only Updates to Installed and the script crashes. Have to stop the script otherwise the browser locks up.
I cannot get the count of (11) updates to clear at all.

**Comment by qooob** [comment]
Please file this issue to Webmin repo and refer to this repo (paste this issue's link to Webmin issue). It doesn't sound as theme issue at all.

**Comment by qooob** [comment]
On System Information page there is another, blue refresh button for packages only, when you hover on packages row. You tried clicking it, right?

**Comment by qooob** [comment]
I just made an update for my server. The package updates notice is not dismissed right away from System Notification page after upgrade. It took about 2-5 minutes to completely disappear.

I will re-post this issue to Webmin developer as it doesn't seem as the theme issue.
