### ISSUE TITLE
File Manager: Copy path to clipboard

### ISSUE THREAD

**Issue by EdisAganovic** [qooob/authentic-theme#408]
Hello,

It would be useful to have this option for files' paths in File-Manager to copy it in the clipboard.

**Comment by qooob** [comment]
Ohh, sounds like a great idea. Will try doing it later. Thanks.

**Comment by EdisAganovic** [comment]
Main purpose I needed this was path for the cron job.

**Comment by qooob** [comment]
Whatever it is, it's great idea.

**Comment by qooob** [comment]
This is a great idea and it's going to be implemented in 17.80, example:

http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-clipboard-func.webm

**Comment by qooob** [comment]
...and in case you didn't know, you can manually enter path by right clicking on it:

http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-manual-path.webm

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
