### ISSUE TITLE
Showing non-existant updates

### ISSUE THREAD

**Issue by BrettRow** [qooob/authentic-theme#409]
Using 17.72 with WebMin 1.780 on Internet Explorer 11.
I updated 8 packages on Unbuntu, which were shown on the dashboard. When I reopen WebMin later the dashboard will initially show that no updates are required then, a few seconds later, show that 8 package updates are required. Going to the updates page shows no actual updates available.

![webmin_1](https://cloud.githubusercontent.com/assets/8628540/13311431/2e904786-db97-11e5-9a83-85762f3fb70e.png)
![webmin_2](https://cloud.githubusercontent.com/assets/8628540/13311435/36c8584e-db97-11e5-98fd-68dc1d25e1f0.png)
![webmin_3](https://cloud.githubusercontent.com/assets/8628540/13311437/3b46f9e8-db97-11e5-8609-e33592912599.png)

**Comment by qooob** [comment]
Same would happen in the default theme. It's not theme issue. It's reported.

https://github.com/webmin/webmin/issues/282#issuecomment-188618520
