### ISSUE TITLE
index_cpu.cgi causing 100% CPU spikes using Authentic Theme

### ISSUE THREAD

**Issue by dylanrhysscott** [qooob/authentic-theme#410]
Hi,

I think I have found a bug when using the Authentic Theme. Periodically when using the theme 	/usr/share/webmin/proc/index_cpu.cgi spikes to 100% CPU usage for about 5 - 10 minutes. I have been doing a bit of tracing and initially thought it was down to MySQL but under the processes tab of Virtualmin I found this to be the cause.

For now I have switched back to the Virtualmin Framed Theme and will monitor if this is indeed the cause. I am running a VPS on Digitalocean:

Ubuntu 14.04 LTS
1GB RAM
30GB SSD
2GB Swap

Anyone else had this issue?

Cheers

Dylan

**Comment by qooob** [comment]
I have never experienced this issue and I truly doubt that it has anything to do with the theme.

**Comment by dylanrhysscott** [comment]
Swapping back to Virtualmin Framed Theme has pushed this value down to 3% CPU usage I have been monitoring it for the last few hours. This person here also has had a similar issue when running the theme - http://www.webhostingtalk.com/showthread.php?t=1530070

**Comment by qooob** [comment]
I understand. Every 5 minutes (300 sec), System Status, `scheduled_collect_system_info` also happens in Webmin Configuration->Webmin Scheduled functions.

It's not a bug. I have found out on my server (64gb RAM, SSD, and 12x2 CPU Cores), that `index_cpu.cgi` goes upto 4-5%. In case I switch to VM Framed Theme then it drops down to 0.4-0.5%. Well, it's true that Authentic Theme is more resourceful. When you reload `index_cpu.cgi` page it makes the whole theme load from the beginning and thus it uses a lot of CPU power. In case of not very powerful machine it will be 100%. In reality the load will not be there as long as you don't reload the page.

Thank you for reporting but it's not a bug. Theme does a lot of calculations and stuff upon load. I don't think I can help it. But overtime, that is for sure, I will try my best to do more and more optimizations,  in case it's technically possible, to make theme shine in every possible way.

**Comment by dylanrhysscott** [comment]
Hi,

Thanks for your in depth answer it's most helpful. In some cases when I was on Virtualmin and SSHing into the VPS the SSH would suffer (i.e take longer to connect) . Its a fantastic theme and I love the look it gives but does raise some concerns when it max outs the CPU. Its true in the case of my low power VPS the CPU takes a hit. - If you need any more info from me drop me a line but great work and keep it up! Probably just needs some tweaking :)

**Comment by qooob** [comment]
Thank you for your kind words and you are welcome.

I totally agree with you, that there is some room for code optimisation. Please understand, that making usable, optimised and great build (architect wise code) is a very very difficult task. 

VPS is very specific. I remember, before having separate server, I couldn't even reload a page (http), when ffmpeg was running. 

There should be a possibly on limiting CPU/RAM usage, this could be a solution.

Before I got a server of my own, I used to use ServInt - it was very good for me and I reccomend trying it.

**Comment by dylanrhysscott** [comment]
Thanks for the recommend - Will take a look! Yeah I agree writing well optimized code is a daunting task. I come from a web development background and am constantly looking for ways to refactor it. Nothing on the same league as VM but still. Do you prefer dedicated over VPS then?

**Comment by qooob** [comment]
Yes, I do. I eventually had a chance to buy (3 years ago) personal server and put to DC - now I get maximum fun. ;)

But dedicated will provide much much better experience. However, it's all based on your tasks.

**Comment by lisandi** [comment]
The problem seems to still exist with up to 11% and more 
root	11.0 %	/usr/share/webmin/proc/index_cpu.cgi
---
It is also strange that webmin got updated today with same version number and only GPL changed to GPL-3 but 16GB more diskspace gotused. Perhaps webmin has a problem?

**Comment by qooob** [comment]
It's surely not the theme issue. It's probably only happens exactly at the moment when this page is loaded. It's not happening afterwards.

You can check it using `top` command in the console.

Webmin update? What's that?

**Comment by lisandi** [comment]
Thanks qooob for your fast response - just right now I was asked by webmin to update - same version but gpl changed to gpl-3 it says

**Comment by qooob** [comment]
Probably you're talking about Virtualmin?

Anyway, `top` command should not and will not list `proc/index_cpu.cgi` as the process, I believe.

**Comment by lisandi** [comment]
I am using virtualmin right

cp -p \/usr\/share\/webmin\/sendmail\/autoreply\.pl \/etc\/webmin\/virtual\-server 
cp /usr/share/webmin/sendmail/filter.pl /etc/webmin/virtual-server

Changed file /etc/webmin/webmincron/crons/147108047115071.cron

seems to be an update with sending mails problems. right! Probably this was causing also the cpu usage problems before and they tried to fix it. I will monitor it. Thanks for the hint!

**Comment by Asahajit** [comment]
I am also facing same kind of issue some time its rebooting my raspberry pi also for high CPU usage

**Comment by qooob** [comment]
Simply update to the latest version of the theme (19.08) using Theme Configuration.

**Comment by thejae** [comment]
![cpu](https://user-images.githubusercontent.com/738694/35517483-8a6e8e9a-0549-11e8-9572-a3d74045f00d.PNG)

I have the same problem here, not sure if it's caused by the theme or the process of pulling cpu usage data itself.

**Comment by qooob** [comment]
It only happens while querying data. It's not an issue. 

You can check it by using `top` command in console.

**Comment by kalaolani** [comment]
Authentic Theme 19.09 seems to have resolved the issue for me. Now, I see an expected spike when data is queried, but not a persisted usage of the CPU or any hangs in the GUI.

**Comment by pierr0t** [comment]
Hello

I know this thread is quite old but I have the same problem:

I have 7 vps's all installed the same way (debian9) with the same provider and the same Webmin/Virtualmin setup and only one of them is showing that behavior where I have the CPU going up and down. This one is the only one that shows processes "/usr/share/webmin/proc/index_cpu.cgi" at the top of the processes list whereas all the other have mysql and fail2ban at the top.

The theme is Authentic for all of them, v19.18, I of course have a normal spike of CPU when arriving on the "dashboard" but if I stay on that page doing nothing, the CPU stays stable and low on all of them but this one where it goes regularly up to 50% and back down like every 30 sec.

Before I move everything out of this server to reinstall it, is there anything I should try, test, report ?

Thks.
Pierre

**Comment by qooob** [comment]
It's normal, if you are in Running Processes module. It's not related to original issue.

**Comment by pierr0t** [comment]
Hi
Thks for answering, but not sure I understand  ... I understand the "not related to original issue", maybe I read it too fast (although I have the same screen as @thejae), but my question is about explaining the different behavior between identical servers for the dashboard:

Is there a possible explanation for that server having all the time /usr/share/webmin/proc/index_cpu.cgi at 50% and on the others this process being max 5% in the middle of the list ? Maybe I am misunderstanding but I thought that /usr/share/webmin/proc/index_cpu.cgi was related to the theme ..

**Comment by qooob** [comment]
It just includes itself and by the time the page is displayed it's actually 0. I'll talk to Jamie to exclude this process from the list as it's useless and confusing.

You can make sure and check what I'm saying by running `htop` in the console.

**Comment by pierr0t** [comment]
I did already (because I read the complete thread) but still, that does not explain why this server (up and down between 0 and 50%) and not the 6 others (never above 3% and never up and down like that). Same machines almost.

**Comment by qooob** [comment]
Side bar (Slider) is what comes out after clicking on the bell. 

What is the output of top command? Do you see there any abnormal data?

**Comment by qooob** [comment]
The CPU usage can be caused by anything. What makes you think it a bug? Run `htop` command to get more data for analysis. I don't see theme issue here. 

I think some process is happening in background, like Webmin Scheduled function that runs every 5 minutes by default.

**Comment by pierr0t** [comment]
Ok I understand the slider. Gives exactly the same information:

<img width="317" alt="capture d ecran 2018-05-18 a 18 06 39 18" src="https://user-images.githubusercontent.com/1298608/40245591-7a08d1be-5ac6-11e8-9386-4cc3d281d8cf.png">

I don't see abnormal data in htop (I have a regular stats.cgi at 4% max) and I understand this spike could be caused by anything else and I do not know if it's a bug, it's just that I had that same exact symptoms as the OP (regular spikes of cpu usage on a server that is very lightly loaded) with /usr/share/webmin/proc/index_cpu.cgi at the top of the running processes. And comparison with my other 6 servers that do not have those cyclic spikes. And the cycle is more like 30 sec, not 5mn.

Anyway I will try to find more data, maybe move some virtual host to another place to see if it follows a specific VH.
Thanks for you answers.

**Comment by qooob** [comment]
Disk query could take a lot of load on large file sistems. It's planned to make possible to chose what to gather for the real-stats.

**Comment by karlegas** [comment]
> Hi,
> 
> I think I have found a bug when using the Authentic Theme. Periodically when using the theme /usr/share/webmin/proc/index_cpu.cgi spikes to 100% CPU usage for about 5 - 10 minutes. I have been doing a bit of tracing and initially thought it was down to MySQL but under the processes tab of Virtualmin I found this to be the cause.
> 
> For now I have switched back to the Virtualmin Framed Theme and will monitor if this is indeed the cause. I am running a VPS on Digitalocean:
> 
> Ubuntu 14.04 LTS
> 1GB RAM
> 30GB SSD
> 2GB Swap
> 
> Anyone else had this issue?
> 
> Cheers
> 
> Dylan

Hi I have the same problem with my Webmin and Authentic Theme, but I don't have installed Virtualmin how I can install the Virtualmin Framed Theme or other similar that not consume so much resources?

Thanks

Karl

**Comment by rostovtsev** [comment]
It's not the theme issue. It spikes at the moment it runs the module's query and then it goes to results, that you see. By the time you see it it's no longer running.

You can opt-out printing such results using module configuration.

You can see that there is no load when you check the graphs from live-monitoring (in right side slider).

**Comment by rostovtsev** [comment]
Oh, I missed that it's all about `stats.cgi`. In case it's the hog for you, you can disable it using theme configuration.

I would guess that you have too many drives mounted to your system. You can selectively disable drives stats gathering.

**Comment by karlegas** [comment]
> Oh, I missed that it's all about `stats.cgi`. In case it's the hog for you, you can disable it using theme configuration.
> 
> I would guess that you have too many drives mounted to your system. You can selectively disable drives stats gathering.

I went to the Webmin Themes configuration and selecte NO on both Real-time monitoring options

Enable real-time monitoring | Yes                                          No
-- | --
Enable for disks | Yes                                          No
Interval for performing update |  

That is the correct site?

**Comment by rostovtsev** [comment]
Yes.

**Comment by karlegas** [comment]
> Yes.

Than you very much for your prompt answer.

**Comment by rostovtsev** [comment]
What did you do eventually? Was it due to the disks or real stats in general?

What is your server specs?

**Comment by karlegas** [comment]
![2019-07-18_13-02-08](https://user-images.githubusercontent.com/53014016/61490273-6997f900-a961-11e9-9415-ef70c8dae908.png)
Operating system | Ubuntu Linux 16.04.6
-- | -- | -- | --
Webmin version | 1.920 | Authentic theme version |  

![2019-07-18_13-41-08](https://user-images.githubusercontent.com/53014016/61490406-b8de2980-a961-11e9-9354-a0946c328714.png)

Was it due to the disks or real stats in general? I don't understand that question. How I see the real stats?
![2019-07-18_13-43-46](https://user-images.githubusercontent.com/53014016/61490565-15d9df80-a962-11e9-90d2-f512e26b2a4f.png)

**Comment by rostovtsev** [comment]
Real-time monitoring in general, I just meant, that if you disable only _Enable for disks_, and leave real-time monitoring enabled, would that still be slow and cause 30% load?

**Comment by karlegas** [comment]
I will see I activate again the Real-time Monitoring. I have a question is possible have a web browser inside Webmin, to run some downloads from Telegram webclient?.

Regards
Karl

**Comment by wernerm** [comment]
We are still experiencing the issue, even now on Authentic Theme 19.50. 

Some `htop` output to illustrate...

![htop-authentic-theme](https://user-images.githubusercontent.com/411270/83033511-7da78f00-a037-11ea-8d09-922855198bef.gif)

**Comment by iliarostovtsev** [comment]
> We are still experiencing the issue, even now on Authentic Theme 19.50.

What makes it an issue?

**Comment by wernerm** [comment]
> What makes it an issue?

Sorry, I was referring to the issue of CPU spikes caused by `/usr/share/webmin/authentic-theme/stats.cgi`

**Comment by iliarostovtsev** [comment]
> Sorry, I was referring to the issue of CPU spikes caused by /usr/share/webmin/authentic-theme/stats.cgi

Yes, I understood that. Why is it an issue? It's just CPU usage?

You can disable live stats at theme configuration page.

**Comment by lisandi** [comment]
We have the same problem here and they spike up to 100% when you load the
Dashboard and sometimes also in-between - couldn't figure out why
in-between. Then the CPU gets a full load You can see that also in the
graph. On the other hand the stats still don't redirect properly to the run
processes pages as nothing shows up here. Also the memory usage climbed up
every day about 2-5%. After a reboot it starts again with 8-10% what would
currently be normal. Live stats are actually good to see as they usually
give a great overview in a fast and easy accessible way - before we updated
to the latest version. But as mentioned the fact that they still link but
that the run processpage doesn't show anymore the values is a real handicap
- but probably a problem of virtualmin itself and not of the theme. Strange
is that the theme actually can present the stats while the processes can't
even be listed. Perhaps the theme developer and the virtualmin developer
should sit together and exchange each other so also the virtualmin shows
again the values.

Disabling would be more contra productive - my question would be if the
values shown in the theme are actually accurate as the virtualmin can't
show any values in Ubuntu 20.04. What and how is the Theme calling or
receiving the values and why can't that work the same way in virtualmin
itself.

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,
*
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Andreas Becker about.me/andibecker
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
**LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Phone: +66 (0)76 530 595
VoIP: +49 (0)711 50 88788 50
Fax:   +49 (0)711 50 88788 50
GTalk/Facetime/eMail:  andi@lisandi.com
Mobile/WhatsApp: +66 (0)81 606 3378
Facebook/Line/Messenger: andibecker
Appear.In/Skype: lisandi
--------------------------------------------------

**Comment by iliarostovtsev** [comment]
> We have the same problem here and they spike up to 100% when you load the
Dashboard and sometimes also in-between

That is perfectly normal, especially for Dashboard load and especially on machines with low CPU resources.

> On the other hand the stats still don't redirect properly to the run processes pages as nothing shows up here. 

Stats load in background, either updating data on Dashboard and right side slider and/or just collecting it for future representation.

> Also the memory usage climbed up every day about 2-5%. After a reboot it starts again with 8-10% what would currently be normal.

I am more than sure, it has nothing to do with neither Authentic Theme nor Webmin/Virtualmin.

> Live stats are actually good to see as they usually give a great overview in a fast and easy accessible way - before we updated to the latest version.

What last version number you're referring to? What exactly happened with last update? What is your server specs?

>  But as mentioned the fact that they still link but that the run processpage doesn't show anymore the values is a real handicap - but probably a problem of virtualmin itself and not of the theme.

I don't understand what is not working or broken? Can you please provide some graphical content?

> Perhaps the theme developer and the virtualmin developer should sit together and exchange each other so also the Virtualmin shows again the values.

What value, again, please be kind elaborating, I have no idea what's wrong?

> my question would be if the values shown in the theme are actually accurate as the virtualmin can't show any values in Ubuntu 20.04.

So, the actual problem is not working proc module in Ubuntu 20.04. In that case, it [was fixed](https://github.com/webmin/webmin/commit/613f3a5f41fd094037629965e4cea1b815ac2b7d#diff-6844acdce7e192c21c184914d73ab6be) on our side, even though it's Ubuntu 20.04 bug itself. You can fix this problem by running the following command locally, on your server:

~~~
curl https://raw.githubusercontent.com/webmin/webmin/master/proc/linux-lib.pl -o /usr/share/webmin/proc/linux-lib.pl
~~~
