### ISSUE TITLE
Mail Scanner: Doesn't show any captions

### ISSUE THREAD

**Issue by kreationnext** [qooob/authentic-theme#411]
Hello again,

The mailscanner module under authentic theme doesn't show any captions. That may be any button, label, or header text. as if it cannot connect to/identify the language file.

**Comment by qooob** [comment]
What do you mean by captions? Could you provide screenshot, please?

**Comment by kreationnext** [comment]
https://drive.google.com/file/d/0B1yUtDYgrFZwWFhvYk4yNXpTaHc/view?usp=sharing

**Comment by qooob** [comment]
What does it show under Grey Framed Theme?

**Comment by kreationnext** [comment]
https://drive.google.com/file/d/0B1yUtDYgrFZwdlpMOHowYUdMdUU/view?usp=sharing

**Comment by qooob** [comment]
Interesting. I must point out that this is not standard module and it's 9 years old.

It must be module's issue.

However, I will take a look closer to another release.

**Comment by kreationnext** [comment]
Sure! But I have tested it with other themes like "finally theme" and it
works well.

Authentic is your child. And as much as I know you, you will take care of
it and the issue as well.

Good night!

**Comment by qooob** [comment]
Thanks. Yes, I will do my best.

**Comment by qooob** [comment]
Hi,

This seems to be the same issue as [#426](https://github.com/qooob/authentic-theme/issues/426) and will be fixed in 17.80.

Thanks for reporting.

**Comment by qooob** [comment]
Please upgrade 17.80 is out!

**Comment by kreationnext** [comment]
Great Job!
