### ISSUE TITLE
Theme: Time display is wrong on System Information page

### ISSUE THREAD

**Issue by hasanalsamra** [qooob/authentic-theme#412]
Hello again, Ilia
i have noticed that the hour is not the same of system time at theme's main page.
Here is a screenshot:
![1](https://cloud.githubusercontent.com/assets/15183857/13406654/acdc064e-def2-11e5-9187-dac19f7a7f31.png)
On gray framed theme:
![2](https://cloud.githubusercontent.com/assets/15183857/13406679/c7e7588a-def2-11e5-829c-a0133f19d10d.png)

Thanks,

**Comment by qooob** [comment]
Hi,

Time format can be manipulated at theme's settings and set anything you want. Did you try it?

**Comment by hasanalsamra** [comment]
Sorry i meant the time is invalid in your theme the time is: 2:38 PM
The real time at system is: 10:38 PM

**Comment by qooob** [comment]
That is indeed!

Go to theme's settings and replace 

**Full date/time format** to `LLLL` 

and

**Short date/time format** to `L, LTS`

Thanks for reporting! It will be fixed in the next release.

**Comment by qooob** [comment]
It will be having correct values by default in 17.80.

**Comment by hasanalsamra** [comment]
Yeah solved
Thx alot.
+1
