### ISSUE TITLE
Problems with font in nginx module

### ISSUE THREAD

**Issue by Shevraar** [qooob/authentic-theme#413]
First of all, thank you for this awesome theme, it really is a pleasure to the eyes!
I'm having this problem when editing any nginx conf file:

[http://i.imgur.com/2hCzZ2p.gifv](http://i.imgur.com/2hCzZ2p.gifv)

Am I missing something from the installation?

**Comment by qooob** [comment]
Hi,

You are welcome.

**From Troubleshoot**

>  Strange Â character is appeared in text-editor mode or other encoding issues    This happens because of encoding disparity. To fix this, just set language in Webmin to UTF-8 and make sure that your browser also has detected it as UTF-8. Pay attention, that Webmin in-built module, named Change Language and Theme can override global settings;
