### ISSUE TITLE
Theme: Ability to open needed module's link using URL request

### ISSUE THREAD

**Issue by jeroencusters** [qooob/authentic-theme#414]
Version 17.72
When opening links from update emails, i.e:
/security-updates/
/virtual-server/edit_newscripts.cgi?mode=upgrade

Screen is blank (grey) with the following Javascript errors (authentic.min.js:6):
Uncaught TypeError: Cannot read property 'contentWindow' of undefined
Uncaught TypeError: Cannot read property 'trim' of undefined

**Comment by qooob** [comment]
Did you just update the theme? Did you try clearing cache? Have you experienced such problem before?

**Comment by jeroencusters** [comment]
I didn't have these issues before. First I tried with 17.71. Then I saw that there was an update available. I updated and tried again. 

After your reply I cleared the cache again, but this doesn't help. And I have tested it with Firefox (normally I use Chrome). Same problem here.

**Comment by qooob** [comment]
You said opening links from email?

What is the full link's path?

**Comment by qooob** [comment]
I think I understand. This will not work, at lease at the moment.

How did you enable email messages for such things?

**Comment by jeroencusters** [comment]
Webmin -> System -> Software Package Updates
Check for updates on schedule?: Yes
Email updates report to: Email
Action when update needed: Just Notify

2016-03-03 10:35 GMT+01:00 Ilia Rostovtsev <notifications@github.com>:

**Comment by qooob** [comment]
Thank you, sounds like a nice improvement.

I will try making it possible in the next release.

**Comment by jeroencusters** [comment]
Thanks!

**Comment by qooob** [comment]
It will be fixed in 17.80.

Thanks for reporting!

**Comment by qooob** [comment]
Please upgrade 17.80 is out!

**Comment by jeroencusters** [comment]
I don't see the update in virtualmin

**Comment by qooob** [comment]
It's on System Information page, in case you enabled check for theme updates option in theme's settings. `Check for Authentic Theme updates`

**Comment by jeroencusters** [comment]
I see, I didn't disable it and in the past I received updates for theme automatically. I just re-enabled the check for authentic theme updates and updated to 17.83

This issue is solved. I can use the link from the email now. Thanks!

**Comment by qooob** [comment]
Sure, you're welcome!
