### ISSUE TITLE
french translation icharacter not printed properly

### ISSUE THREAD

**Issue by aqueos** [qooob/authentic-theme#415]
hi,

 when i put virtualmin in french the accent do not print correctly:

Nom d'hÃ´te du SystÃ¨me 
instead of
Nom d'hôte du système

etc...

regards,
Ghislain.

**Comment by qooob** [comment]
Hi,

Please read Troubleshoot, 2:

https://github.com/qooob/authentic-theme#troubleshoot

P.S. I will enroll pop-up messages for non-UTF8 charsets in the next release. Thanks.
