### ISSUE TITLE
Theme: Include server name to security notification's template

### ISSUE THREAD

**Issue by taphawane** [qooob/authentic-theme#417]
Is that possible to include the server name in side the login alert email like this:
"Webmin [Server_name] login page is accessed by unauthenticated user from 1.2.3.4"

Just in case if you have more than on server so you will know, which server someone is trying to access.

**Comment by qooob** [comment]
You would want to happen this automatically?

At the moment I can't recall that it's possible. It sounds like an improvement.

Meanwhile, entering it manually in theme's settings not possible for you to do at the moment?

**Comment by taphawane** [comment]
Thanks for expertise and time!!!

**Comment by qooob** [comment]
This will be added to 17.80.

Thanks for great feature request! ;)

**Comment by qooob** [comment]
Please upgrade 17.80 is out!
