### ISSUE TITLE
Theme: Opening links in new tabs doesn't work as before

### ISSUE THREAD

**Issue by marius-luca-87** [qooob/authentic-theme#419]
In previous versions of the theme I used to open various links in new tabs (logs/emails/etc).
Ex: https://webminurl:10000/syslog/edit_log.cgi?idx=3

Now a blank page is displayed and when checking the javascript console 2 errors are present:
TypeError: t__wi_p.$(...).get(...) is undefined
__lle()
 authentic.min.js:6
<anonymous>
 authentic.min.js:6
n.event.dispatch()
 package.min.js:2
n.event.add/r.handle()
 package.min.js:2
.trigger()
 package.min.js:2
z()
 package.min.js:2
.send/c/<()
 package.min.js:2
 authentic.min.js:6:22143
TypeError: t__wi_p.$(...).val(...) is undefined
<anonymous>
 authentic.min.js:6
n.event.dispatch()
 package.min.js:2
n.event.add/r.handle()

**Comment by campones** [comment]
same after updating last google chrome 49.xxx

**Comment by qooob** [comment]
Hi,

This is true. I didn't expect that happening really! I will find the way to fix this on the next release.

Meanwhile, modules that you want to show properly on the new tab, you should add to exclusion list (on theme settings). For example, if you want to show **System Logs** in the new tab properly, add to exclusion list `syslog`.

**Comment by qooob** [comment]
This issue is annoying, I'm sorry.

It will be fixed in 17.80 (quite soon, as I'm working every day on the theme now)

Thank you very much for reporting.

**Comment by qooob** [comment]
Tell me if you wish to have a patch right now. I'll post the links.

**Comment by qooob** [comment]
Please upgrade 17.80 is out!

**Comment by tss3000** [comment]
Issue is fixed now in 17.80. Thanks for your time.
