### ISSUE TITLE
Rename and Edit on known textfiles in file explorer

### ISSUE THREAD

**Issue by norsve** [qooob/authentic-theme#420]
Hi,

After i upgraded my webmin server (and this theme), the edit icon on known textfiles and rename icon disappeared. Do anyone know how to get them back?

/Svein Thomas

**Comment by qooob** [comment]
Hi,

Are you talking about File Manager module? You can use context menu (right-mouse click or menu key) to invoke the menu with all available options, including `Rename` and `Edit`. In case it's not enough and you still would want to see it, you can go to the theme's settings and under `Third-parties modules options` you can toggle `Hide actions column` to `No`.

Good luck.
