### ISSUE TITLE
Theme: Display date/time of last access with IP on System Information page 

### ISSUE THREAD

**Issue by fagner2010** [qooob/authentic-theme#421]
Hello that such a System information, date, and time of last access with the ip?
Thank you.

**Comment by qooob** [comment]
Hi,

You mean after login or after last page refresh?

**Comment by fagner2010** [comment]
Hi, after last page

**Comment by qooob** [comment]
But there background calls and System Information page is refreshed by default every 10 minutes?

**Comment by fagner2010** [comment]
Hi, exemple http://postimg.org/delete/xeb54sz3i/

**Comment by qooob** [comment]
Hmm. Ok. 

What do you want to achieve, so I could understand better what you want. You want to know who used Webmin besides you and when?

What about `Webmin Users->Current Login Sessions` and `Webmin Actions Log` - it has it all?

**Comment by qooob** [comment]
:up:

**Comment by qooob** [comment]
:up:
