### ISSUE TITLE
Theme: Dashboard scrolling issue (Safari iOS 9)

### ISSUE THREAD

**Issue by izeen** [qooob/authentic-theme#422]
Hi!

This issue has been there for aslong as i have used Autentic-Theme for Webmin i belive,

If you go to the webmin dashboard on a mobile device, specifically iPhone(iOS 9) safari and scroll down a bit you automatically get pulled back up to the top of the site, a little annoying. Any fix i can do to solve this?

**Comment by qooob** [comment]
To be honest, I have no idea why this is happening (only on iOS) and most importantly I can't really work it out as I don't use iPhone.

I bet it works fine on mobile Chrome? Is there a way you could debug it and provide a fix?

https://github.com/qooob/authentic-theme/issues/394

**Comment by izeen** [comment]
I tried to download Chrome for iOS but its the same there, when you scroll down on the Webmin dashboard it hops back up again when you reach the bottom of the Dashboard.

**Comment by SteffanCline** [comment]
If you have a Mac you can install XCode which has an iOS Simulator built in and it has Safari. It's what I use to preview web sites in the various iOS display sizes.

**Comment by qooob** [comment]
Alright, sounds like a deal. It doesn't work for you on the real phone or on simulator? Or it doesn't work on both?

**Comment by SteffanCline** [comment]
I haven't even checked. I am just letting you know it exists since you said you don't use iPhone.

**Comment by qooob** [comment]
Alright. I'll check and try to fix by the next release.

**Comment by yd021976** [comment]
Hi, the slow scrolling problem appears on safari on Imac too. I tried with google chrome on the Imac and there is no slow scrolling problem.

I think this bug affect only safari (haven't tried firefox).

**Comment by yd021976** [comment]
hi, in addition there is no slow scrolling problem on safari with ios9.1 with an iphone 6.
Still get the problem with my imac (core i7 3,4 ghz) even with all extensions uni stalled and cleared caches.
So i dont know how inspect the slow scrolling problem with developper tools, so i cant help you more with this deal.

**Comment by qooob** [comment]
What kind of problem exactly exists on your iMac? Scrolling problem? I have MacBook and iMac so I could reproduce the problem.

Please describe it how and when it happens.

**Comment by yd021976** [comment]
Hi, yes the problem is very slow scrolling issue.
To reproduce, in webmin select any menu item that shows a page that need to scroll (for exemple "startup and shutdown actions" or "theme options").
Then when i want  to scroll, the page is very slow to scroll.

With google chrome, there is no slow scrolling problem.

Thank you.

**Comment by yd021976** [comment]
Hi, did you reproduced the problem or do you need more explanations ?

Thank you

**Comment by qooob** [comment]
This is what I'm doing right now. I got my MacBook Air and 2267 records of installed packages listed in Software Packages Updates.

I don't know what you mean by slow though. It's scrolling - not smooth and happily but works.

Could you please make video with your phone so I understood what you mean?

**Comment by yd021976** [comment]
made two videos (safari and chrome) but can't send them with github. Do you have private email ?

**Comment by qooob** [comment]
You can upload it to Google drive and share it. You can find my email in the theme's files.

**Comment by yd021976** [comment]
done ! I sent you an invitation to my shared google drive (email : programming@rostovtsev.ru)

**Comment by qooob** [comment]
There is no need for invitation. Click more options and share the link publicly, without log in. This email doesn't have gmail account.

**Comment by yd021976** [comment]
the link : 
https://drive.google.com/folderview?id=0B0ystTrJ8hBVbGdWTjNlYWZUY1U&usp=sharing

**Comment by qooob** [comment]
Alright, thanks! Understood. That is the reason I only use Chrome for development.

My friend, I don't see how this related to the theme? There are thousand or questions on Google asking _Why Safari scrolling is slow_.

It doesn't happen in default theme as it doesn't have (~0.5mb package.min.css) attached to the head of a page. If you in the Safari console remove it, then things start to work much much faster.

I can't tell you how frustrated I am having _lagging_ Firefox nowadays, while having high-end hardware on my desktop PC. I did so many tweaks and still no luck. Again, Chromium/Chrome works perfectly. Probably Mozilla, Apple and Microsoft must learn few things from Google.

I see the slow page rendering tied to a lot of dependencies. 0.5mb for CSS + ~1.4mb for JS. That slows things down BUT hey, when you have (like you do) very powerful hardware and browser can't allocate more resource to make it work smoothely? Don't know.. I'll be looking but at the moment I have no other thoughts yet..

I was hoping to use `iframe-seamless` [option](http://caniuse.com/#feat=iframe-seamless) but it's not supported.

Any ideas anyone?

**Comment by qooob** [comment]
However I found that `icheck` on large pages crashes Firefox and when removed all seems fine.. It's a good discovery. I'll try figuring out why and if it's the scripts problem.

**Comment by yd021976** [comment]
cool ! hope it will fix the problem !

**Comment by qooob** [comment]
No, I don't think it will. You can go now to theme settings and set to `No` -> `Enable customized checkboxes and radio buttons`. 

Does it change anything for you?

**Comment by yd021976** [comment]
tried changing settings, but with no luck => still get very slow scrolling

**Comment by qooob** [comment]
Did you notice checkboxes must change as you disabled this option. I actually found some problems with icheck.

**Comment by qooob** [comment]
But it doesn't affect anything if it's still slow when it disabled.

**Comment by yd021976** [comment]
yes checkboxes changed after tweaking theme. But no change about scrolling pb

**Comment by yd021976** [comment]
maybe it's a firefox/safari/microsoft webbrowser related pb... but very strange that only google chrome works fine !

**Comment by yd021976** [comment]
...and i don't want google chrome on my machine :-)

**Comment by qooob** [comment]
Well, if you're going to use Safari - you're not gonna get more privacy/security, I believe. Using proprietary OS makes things even worse.

I would use Linux + Chromium to get privacy, or Firefox if it works fast on your machine.

Install Chromium - it's open source unlike Safari. Besides you can run it as another user if you are afraid for your files being accessed by malicious browser. ;)

**Comment by yd021976** [comment]
thanks, but it's not only privacy/security concerns. But agree that chrome rocks with performance !

**Comment by qooob** [comment]
I would love to know your reasons on why not using it?

Actually, I can't think of where Chrome doesn't rock!? :D

**Comment by yd021976** [comment]
You're right : I'm going to use google chrome as it is more powerfull :-)

**Comment by qooob** [comment]
Ok,

Because of that request, I took a close look to that part of the code and improved it - it will be must much faster as there were couple unneeded loops. 

Now Firefox doesn't crash on long tables (like 2000+ rows) and loads decently fast(er).

I don't think it will solve slow scrolling issue but it will definitely be more productive on 17.85+.

**Comment by qooob** [comment]
By the way, now I understood why some people could not click on the checkboxes (using left click). I could reproduce it with 2000+ rows using old code.

**Comment by qooob** [comment]
Alright, I have done some code change and lightened the theme a lot.

I can't promise you that it will solve all of the scrolling issues in _Safari_, as I simply it can't be done on the theme side, I believe.

However, there will be no more slow JavaScript checkboxes/radios, moreover each window (frame) will only load needed dependencies. Default palettes are going to be removed from the package and shipped separately, again, to make things lighter and faster.

Yes, and Firefox will not be crashing on large pages as well.

There will be more change/improvement.

Expect it in version 18.00 in around two weeks as there is enormous amount of work to be done.

Regards,
Ilia
