### ISSUE TITLE
File Manager: Right click menu clips on few last items on page

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#425]
Hi, 
First of all thanks for such a wonderful theme.
I've an issue. When i right click on some last items/files in filemanager, menu opens starting from item position and browser scrollbar extends, but scrolling down doesn't shows last menu options and it clips.
I'm attaching screenshots in sequence...

![filman](https://cloud.githubusercontent.com/assets/5191867/13883203/6ad0ee30-ed4e-11e5-8a1c-6c4c01690991.jpg)
![filman1](https://cloud.githubusercontent.com/assets/5191867/13883201/6acfc546-ed4e-11e5-86ce-8cc18cae2a8a.jpg)
![filman2](https://cloud.githubusercontent.com/assets/5191867/13883202/6ad0bf78-ed4e-11e5-8a69-e69f8e9be5ff.jpg)

Thanks... :-)

**Comment by qooob** [comment]
Yeah, I know about this problem but I always needed to scroll and it worked. The fact it's half-way invisible is something new for me.

I can see your using Edge? Can you reproduce it in Firefox or Chrome?

**Comment by divyeshsachan** [comment]
No, its firefox 45.0 on Windows 10 Pro. I'll check it on edge and chrome and will report back.

**Comment by qooob** [comment]
I'll double check again.

**Comment by divyeshsachan** [comment]
Checked on Edge and Chrome and everything is fine, double checked on firefox it clips. It seems like a browser specific issue.

**Comment by qooob** [comment]
I just double checked it in Firefox 45 under Linux - all is fine! 

Did you try to run in Incognito Tab, some extensions could break functionality?

**Comment by divyeshsachan** [comment]
Thanks. i re-cheked it on another machine running Firefox 44 on Win 10 and Firefox 36 on centos 6 the issue exists. When menu is upside everything is fine but whenever menu opens downside starting from the item location, it clips on all of machines i checked. I even checked multiple servers running webmin+authentic theme and i can reproduce it everywhere (only in firefox).

I hope you can reproduce it.

**Comment by qooob** [comment]
I will do my best! Thanks!

**Comment by divyeshsachan** [comment]
after updating to 17.83, its working fine.

**Comment by qooob** [comment]
Good to hear, thansk for reporting.

**Comment by qooob** [comment]
17.84 is out. Please upgrade.
