### ISSUE TITLE
Dansguardian: broken formatting and functionality

### ISSUE THREAD

**Issue by jcerqueira** [qooob/authentic-theme#426]
The latest version seems to break the formatting and functionality of the Dansguardian Webmin Module. Works with default theme.  Screenshot attached.
![screenshot](https://cloud.githubusercontent.com/assets/17992877/13934713/ddd2e158-ef89-11e5-9b8a-c4fdc662a217.jpg)

**Comment by qooob** [comment]
Thanks for reporting. I'll take a look and try fixing it upon next release.

**Comment by qooob** [comment]
Could you specify, what exactly is broken?

**Comment by jcerqueira** [comment]
It seems to be mostly display issues.  On all screens, the submit, cancel, update, etc buttons are all missing labels (they still work but it's a game of Russian roulette trying to figure out which is which). Search for phrase words is completely missing all display and displaying silhouettes for the fields and radio button options.  Also, the top banner of the page displays random text and screens. Some are phrases from a previous page that seem to just get stuck and others are just completely random gibberish. Here is a screenshot of the search page with the random text circled.
![screenshot2](https://cloud.githubusercontent.com/assets/17992877/13964641/0e88ea42-f041-11e5-978f-ffec9d4c8239.jpg)

Thank you for your awesome theme and your time and interest in resolving this!

**Comment by qooob** [comment]
:) You are welcome!

In few days I will be back fully on working with the theme, I will find where to download this module and try to figure out what is happening.

**Comment by jcerqueira** [comment]
https://sourceforge.net/projects/dgwebminmodule/

^This is the project page for that module.

Also I should mention that this was only tested on the latest version of chrome as shown in the screenshots. I can't test in IE as this theme does not work for me in IE. This is what happens when I login on IE 11 (tested on multiple machines and compatibility view made no difference).  Have not tried any other browser and unfortunately am not able to do so.

![screenshot3](https://cloud.githubusercontent.com/assets/17992877/13964865/3fcfee60-f042-11e5-8c5d-20963704d7eb.jpg)

**Comment by qooob** [comment]
Nothing really works in IE. What you're experiencing is the cache issue. Hard reload the page and you will get it right. Theme works in IE but the only browser that makes the theme work perfectly is Chrome.

**Comment by jcerqueira** [comment]
That's what I figured. I never use IE (got IE tab in Chrome for the rare occasions you're forced to use it). Just tried it to see if it was a browser specific issue or something else. Thank you again!

**Comment by qooob** [comment]
That is the interesting issue that you reported. It potentially could have global effect on some modules.

It will be fixed in version 17.80!

Thanks for reporting!

**Comment by jcerqueira** [comment]
No problem! And thank you kindly for the replies, fix, time, and an awesome theme! I'll be sure to send a few beers your way in the very near future (money is tight but definitely I will try to scavenge what I can in appreciation!)

**Comment by qooob** [comment]
I deeply appreciate this, pal!!

**Comment by qooob** [comment]
:smile:

**Comment by jcerqueira** [comment]
Least I can do for all your hard work and for a theme that makes web-based management via Webmin very stylish and a breeze ;)

Please allow me until next week before being able to do so!

**Comment by qooob** [comment]
Thank you again.

Please enjoy the theme. There are more improvements coming with 17.80.

**Comment by qooob** [comment]
Please upgrade 17.80 is out!

**Comment by jcerqueira** [comment]
Installed the update and can confirm all is working again. Thank you so much! Hopefully you received my donation as well and keep up the amazing work!

**Comment by qooob** [comment]
:) Thank you.
