### ISSUE TITLE
Empty pages when i try to open multiple tabs

### ISSUE THREAD

**Issue by JohnnyKing94** [qooob/authentic-theme#427]
When i try to open multiple tabs inside the webmin panel with pressing the mouse wheel or just "right click>>Open in new tab", i get empty pages... instead if i try to simply click the link, i can open it regularly...
This is an example of empty pages i get:
![Empty page](https://dl.dropboxusercontent.com/u/89718989/Screenshot%202016-03-25%2012.04.22.png)

**Comment by qooob** [comment]
Hi,

This [known issue](https://github.com/qooob/authentic-theme/issues/419) and it will be fixed upon next release.
