### ISSUE TITLE
Color for disabled WebServer in Webmin -> Server -> Apache Webserver

### ISSUE THREAD

**Issue by simbus82** [qooob/authentic-theme#428]
Is it possible to show a color or filter for the disabled webservers?

In the Virtualmin selector if a site is disabled it is shown with a red color and in italic font.

Can we have the same effect in Apache webservers list?

Thanks

**Comment by qooob** [comment]
Interesting but this feature could and should be easily implemented using Webmin.

I will let Jamie know.
