### ISSUE TITLE
dashboard unicode

### ISSUE THREAD

**Issue by peekaa** [qooob/authentic-theme#429]
In Czech, utf8, there are wrong displayed unicode signs in dashboard. All other pages are OK. 
![screenshot_1](https://cloud.githubusercontent.com/assets/3026590/14305782/2f1c1d44-fbc0-11e5-9a84-c3f8ddee57e0.png)

Thank you.

**Comment by qooob** [comment]
It's encoding issue, please read Troubleshoot on README.md
