### ISSUE TITLE
Pages blank on direct links

### ISSUE THREAD

**Issue by zackoch** [qooob/authentic-theme#430]
If you try to link directly to a page say http://page:10000/dhcpd/list_leases.cgi it will show a blank page, however the source of the page has all of the content.

This breaks features which redirect you such as the setting to change user password at first login. 

Please see the attached link:
http://imgur.com/a/BHiSR

Latest version of Webmin & Theme.

**Comment by qooob** [comment]
Actually it was targeted in the latest release, 17.80. Cab you make the screenshot of the sourse starting from the top?

**Comment by zackoch** [comment]
http://pastebin.com/GrPDJ69M

or 
![image](https://cloud.githubusercontent.com/assets/17418138/14388577/63cbdeb6-fd74-11e5-97f1-f680c15e01c8.png)

**Comment by qooob** [comment]
You've upgraded, right. 17.80 solves this issue.

**Comment by zackoch** [comment]
I'm sorry - you're right, you must have just released this?! 

All is working :) Amazing. Thank you.

**Comment by qooob** [comment]
Yes, couple of hours ago.

Thanks, you're welcome.

**Comment by Reverze** [comment]
Hello!

I have installed version 17.84 of this version and I have exactly same problem. Blank page after login and I can only navigate using urls.

**Comment by qooob** [comment]
You must hard reload browser's cache manually. It will be done automatically again in 17.85+.
