### ISSUE TITLE
Quota Bars dont show unlimited

### ISSUE THREAD

**Issue by singhdd93** [qooob/authentic-theme#432]
I have all servers with Unlimited storage. The quota bars on sysinfo page (default 1st Page) shows a large value in percentage rather than Unlimited.
This was working fine in 17.72

Thanks for a great theme

**Comment by qooob** [comment]
Hi, this is will be fixed in 17.83 shortly!

**Comment by singhdd93** [comment]
Thanks a lot

**Comment by qooob** [comment]
Please update to 17.83. Is it fixed?

**Comment by singhdd93** [comment]
Yes. Its fixed.
Thanks
