### ISSUE TITLE
Theme: Install module popup page not displaying the page scroll

### ISSUE THREAD

**Issue by hasanalsamra** [qooob/authentic-theme#433]
Hi,
I was trying to install a module to webmin from Third party modules but the problem is that i cannot scroll down because of hidden scroll to see another of modules.
I just bypass it with temporary removing the overflow: hidden; in your css.
Thx, Great updates!

**Comment by qooob** [comment]
Hi,

I have done some changes in this regard. It should work. In case it still doesn't work for third-party module, make sure adding it to the `Modules to exclude` option on the theme settings.

**Comment by qooob** [comment]
Please upgrade to 17.83.

**Comment by hasanalsamra** [comment]
LOL, Yes the third parties page solved but the standard webmin modules still has the issue

**Comment by hasanalsamra** [comment]
But thx anyway.

**Comment by qooob** [comment]
What browser are you using? Do you open the module in the window or having left menu?

**Comment by hasanalsamra** [comment]
Chromium, it is a popup window:
![1](https://cloud.githubusercontent.com/assets/15183857/14427872/57ba9134-ffff-11e5-8da9-3549a379e684.png)
![2](https://cloud.githubusercontent.com/assets/15183857/14427873/57e6c916-ffff-11e5-8aaa-57dd88ea9514.png)

**Comment by qooob** [comment]
I see. I'll fix it on the next release.

**Comment by hasanalsamra** [comment]
Ok thx for your response.

**Comment by qooob** [comment]
I will try to workaround all `window.open` events and turn it into beautiful modal.

I will not add this to 17.84 but most likely in 17.85.

**Comment by hasanalsamra** [comment]
yes, that will be better, you are the best thx

**Comment by qooob** [comment]
Thank you for using my theme! :)

**Comment by hasanalsamra** [comment]
:) your theme is the best

**Comment by qooob** [comment]
:+1:

**Comment by humantex** [comment]
Just to chime in... I've seen the same issue with almost every scrollable page that ends up as more than one screen high - even the deeper ones like hard drive smart-status reports, and the generated software updates/installs. It isn't just individual modules or functions for webmin / virtualmin / usermin. There's no way to see what specific errors were displayed for critical issues if it appears upwards in the page.

**Comment by qooob** [comment]
Yes, it happens on the popup. I will migrate popups very soon. Meanwhile, make sure that you're using the latest 17.84.

**Comment by qooob** [comment]
Will be fixed in 18.00.

Thanks for reporting.

**Comment by hasanalsamra** [comment]
Thank you man :+1:
