### ISSUE TITLE
Поведение нового всплывающего окна пароля базы данных

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#434]
Virtualmin / Edit database / Passwords

![index](https://cloud.githubusercontent.com/assets/14110152/14442169/f6f331fc-0040-11e6-84c1-5f1e557f445e.png)

Немного неудобно копировать данные доступа базы данных: всплывающее окно закрывается при клике вне полей имени и пароля, так же и при выделении двойным кликом.

Всплывающее окно должно закрываться при потере фокуса.
Возможно добавить иконку копирования в буфер обмена?

**Comment by qooob** [comment]
Да, возможно. Только сейчас, если вы нажмете и потянете образовав выделение текста, то окно закрываться не будете. Я специально сделал эту функцию. Но я согласен, об этом нужно знать и если выделять данные двойным кликом, то окно закрывается.

Да, попробую добавить кнопку копировать в буфер в 17.84.

**Comment by qooob** [comment]
В следующей версии, окно при клике вовнутрь будет оставаться открытым, позволяя с легкостью скопировать данные.

**Comment by Romich777** [comment]
Спасибище Вам!
Вы делаете хороший продукт!

**Comment by qooob** [comment]
Спасибо!

Делаю хороший - потому, что люблю это делать! ;)

**Comment by qooob** [comment]
Если есть возможность и желание, было бы здорово заняться русской локализацией - у меня не хватает на это сил.

**Comment by qooob** [comment]
17.84 готова. Обновитесь пожалуйста.
