### ISSUE TITLE
Is there anyway to disable the "Update Notice" from displaying when you login after an update?

### ISSUE THREAD

**Issue by agileware** [qooob/authentic-theme#435]
Hi Qooob!

Is there anyway to disable the "Update Notice" from displaying when you login after an update? When an update is pushed out it is shown on every server and it's very repetitive.

Really love your work, great job.

**Comment by qooob** [comment]
Hi,

Yes. In theme's settings (Webmin->Webmin Configuration->Themes). At the very bottom of the page, you can see `Security Alerts options`. You can disabled it.

However, I made it possible to use a pattern to exclude some IPs from notifications.

`%3 successful login alert for user %1 from %2|%3 successful login alert|root|1.2.3.4,5.6.7.8`

By using this pattern and adding in the end `|1.2.3.4,5.6.7.8` the script will ignore IPs: 1.2.3.4 and 5.6.7.8 from sending notifications. Just set there the IP(s) you would like to exclude from checking.
