### ISSUE TITLE
refresh problem on webminstats module

### ISSUE THREAD

**Issue by gerbier** [qooob/authentic-theme#436]
The webminstats module goal is to display graphs about system or applications parameters.
It is using the standard ui_print_header sub, and use the 9th parameter ( head-stuff ) to add
<meta http-equiv=Refresh content=60>
in html header.

With the last authentic-theme releases, I do not find anymore my meta line in html code (and the graph does not resfresh). Does authentic-theme rewrites html headers ?

**Comment by qooob** [comment]
Hi,

As you can see, I didn't really override `ui_print_header` function.

I'm just guessing that you doing debugging the right way? What is not working for you now what worked in 17.72? Did you double check?

**Comment by qooob** [comment]
The right way to do is to reload parent page. That what will be happening in the future after each CSF upgrade.

All you needed to do back then is just to reload the whole theme.

**Comment by qooob** [comment]
..wrong issue..

**Comment by qooob** [comment]
Any luck with this?

**Comment by gerbier** [comment]
I checked yesterday on fresh debian 8 with authentic-theme, then with the default theme (gray theme).
I just had a look at html code (CTRL+U on firefox), and I do not find my meta refresh when I use authentic-theme.
I just tests again today on a Mageia 5, I have the same result.

I use webmin 1.791 and authentic-theme 17.83

**Comment by qooob** [comment]
Hi,

I was checking through my code and installed all other versions of the theme, down to 14.00 - I could not find `<meta http-equiv=Refresh content=60>` that is produced by your `meta_refresh()` (it seems to be always an issue, not latest release ).

I could see the `meta` tags being displayed by running Gray Theme but like I mentioned and as you can see by looking at the theme's code - I do nothing with `ui_print_header.` 

Later I found out that my theme didn't print 7th argument for the header. I have fixed that and it will be working as expected on 17.84+.

Thanks for reporting! ;)

**Comment by qooob** [comment]
17.84 is out. Please upgrade.

**Comment by gerbier** [comment]
Hi

I just upgrade and check : it's working again : thanks for this quick release !



----- Mail original -----
