### ISSUE TITLE
File Manager: File compression to zip has no output

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#437]
Hi,
While New->create new archive-> select .zip format ends up with message "compression has successfully finished." but it results in no output file. 
Where as .tar.gz.is working fine.

Please check and confirm

**Comment by divyeshsachan** [comment]
Also delete file function is not working. After confirming to "Remove Selected" button, message "deleting selected, please wait..." disappears with no action.

**Comment by qooob** [comment]
Hi,

The most possible reason why this is happening is that you don't have `zip` command installed or it's not on the path. Try `whereis zip` on the CLI, what is the output? If non install `zip`.

It's working fine on my side.

The good point is to add a notification for the user to install zip.

**Comment by qooob** [comment]
Tried it?

**Comment by divyeshsachan** [comment]
Apologize for delayed response.
I checked, zip was not installed in my machine, after installing zip everything worked perfectly.

Now, the point is, instead of showing "compression has successfully finished." message to those users who don't have zip installed show them some error message like "zip is not installed, compression unsuccessful." or to prompt them to install zip before continuing.  It'll be clear to those users who don't have zip.

Thanks :-)

**Comment by qooob** [comment]
Yes, I think I'll add it to my extensions.

**Comment by qooob** [comment]
Alright,

17.84+ will show user-friendly message, in case _zip_ command is not installed - [Example](http://rostovtsev.ru/pub/src/authentic/17.84b/fm_no_zip_command_installed.webm)

**Comment by qooob** [comment]
17.84 is out. Please upgrade.

**Comment by divyeshsachan** [comment]
That's perfect.... :-)

**Comment by qooob** [comment]
Thanks. :D
