### ISSUE TITLE
CSF 8.21

### ISSUE THREAD

**Issue by DJSADERS** [qooob/authentic-theme#438]
CSF 8.21 is not themed, and the main page is stuck on a loop

**Comment by qooob** [comment]
Why did you close the issue? All is fine?

**Comment by DJSADERS** [comment]
It was a strange one, after i updated CSF last night it showed using the standard CSF design and kept reloading the page, on checking it again today (after not touching a thing) it seemed to be themed and working perfectly... possibly a cache issue?

**Comment by qooob** [comment]
No, I don't think so. I will take a look and make things more user friendly.

Thank you!

**Comment by qooob** [comment]
The right way to do is to reload parent page. That what will be happening in the future after each CSF upgrade.

All you needed to do back then is just to reload the whole theme.
