### ISSUE TITLE
Problem with CSF

### ISSUE THREAD

**Issue by vhortex** [qooob/authentic-theme#439]
The theme is blocking CSF saving and only display a spinning wheel that never completes. This is when editing the configuration file. Started with the last 3 updates.

**Comment by qooob** [comment]
What is your `csf` version? Run `csf -v` in CLI?

**Comment by vhortex** [comment]
Authentic Theme 17.72
ConfigServer Security & Firewall 8.21

This may help

Webmin version 1.791

**Comment by qooob** [comment]
Because there was a change in CSF. Update the theme please to the latest.

**Comment by qooob** [comment]
17.84 is out. Please upgrade.

**Comment by clem44** [comment]
Hi I'm using Authentic theme:17.84 and ConfigServer Security & Firewall 9.07.
When I go to the CSF module settings the y-overflow is disabled (I can't scroll down. No scrollbars).
I've only tested this on chrome browser and haven't seen if the problem persist in firefox.

**Comment by qooob** [comment]
That shouldn't be the issue. Try resetting browser's cache. If it doesn't help, try reinstalling (force upgrading) CSF by running `csf -uf`.

But first of all, update theme to the latest 18.03.

**Comment by durangod** [comment]
i am having the same issue, i just ran csf -uf and updated that, but when i go to force update the theme all i get is a update notice page and not sure what to do.  How do i check my version of the theme and how do i get the new version.  thanks

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/547

**Comment by qooob** [comment]
To check the theme version go to the Dash board. The latest is 18.10

**Comment by durangod** [comment]
ok so i have 18.10 webmin and 18.10 authentic theme and virtualmin 5.04  and i still cant access csf, it tries to load and then goes to the dashboard.

**Comment by qooob** [comment]
What is your CSF version?

**Comment by durangod** [comment]
hi, its 9.20

**Comment by qooob** [comment]
Just purge/remove csf*.* under theme extensions golder. It'll work for now.

**Comment by durangod** [comment]
OK thank you sir.. :)

**Comment by durangod** [comment]
Just got an update from csf 9.22 and installed.  It works and page is static and good... However just so you know those two csf js files i removed in extensions dir were not replaced.  But it seems to be ok for now.

**Comment by dnosker** [comment]
I can't get it to work. Still keeps redirecting back to the home webmin page.
Webmin: 1.810
Theme: 1.810
CSF: 9.23

In a previous comment above you said "ust purge/remove csf. under theme extensions golder. It'll work for now." - Not sure exactly how to do this?

**Comment by qooob** [comment]
After deleting it make sure that you clean browsers cache.

**Comment by dnosker** [comment]
I commented out everything in the file: csf.min.js
That worked. does not look so great but at least I can access it now.

Thanks!

**Comment by qooob** [comment]
Sure, yes I will make it look even nicer than it was. ;)

**Comment by hrace009** [comment]
I have this problem, with csf
Authentic Theme 18.10 + CSF 9.24 (Generic), when i try to open CSF menu, it always loading.

**Comment by qooob** [comment]
Just remove `csf.min.js` located in `/usr/(libexec|share)/webmin/authentic-theme/extensions/csf.min.js`

Debian systems have it under `share` and RHEL under `libexec`.

It will be fixed in 18.20

**Comment by Mecanik** [comment]
Removing csf.min.js worked for me, and I use 18.20 ( it was bugged ).

**Comment by qooob** [comment]
Yes. Correct.
