### ISSUE TITLE
Autorefresh system information

### ISSUE THREAD

**Issue by janderk2** [qooob/authentic-theme#441]
It would be really cool to have the system info and graphs refresh every (few) second with an Ajax call.

**Comment by qooob** [comment]
Hi,

Actually graphs are refreshed every 10 minutes by default (using AJAX call).

You can change this time in theme's settings. However, even if you make it less, let's say 60 seconds, it will not work unless Webmin updates data same fast. By default Webmin updates info every 300 seconds. You can change this value by goring to `Webmin->Webmin Configiration->Scheduled Functions` and change `scheduled_collect_system_info` value to the desired one. It will add additional load to your server.
