### ISSUE TITLE
File Manager: Dropdown menu in breadcrumb navigation

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#442]
Hi again,

All Features in authentic theme's File manager has almost reached to perfection. I've already stopped all other web based file managers after recent features addition and bug fixes in authentic file manager.
Once again I've came up with a another suggestion for file manager i.e. adding dropdown menu in file manager's Breadcrumb navigation like breadcrumb navigation in windows10 file manager where each breadcrumb item has selectable folder names in same parent directory in dropdown.

Its not necessary, but feel like missing when i need to move to another parent branch which has multiple folders. Currently you can go to parent folder by a single click in breadcrumb but when there are multiple folders which are spanned across multiple pages it needs multiple click and scroll.

OR instead of adding dropdown in breadcrumb navigation, you could also consider adding a left side bar in filemanager with expandable/collapsable folder names like in file manager in windows. It'll also serve the same purpose of easy navigation across multiple folders.

**Comment by qooob** [comment]
Hi,

Thank you for your kind words.

I even rebooted to my Windows 10 debug installation to take a look. Well, yeah, it's not bad.

However, I always used `Ctrl+L` and just typed what I needed to. This is why I added the same feature to File Manager (it also working by right clicking on breadcrum). What is missing is autocomplete dropdown with folder content of the current directory. I would rather implement that..or may be will do callable Folder Tree like in Windows Explorer. I judge things from my experience (obviously) and I never used it of found this useful. I also consider other people's ideas and you're not the first one to mention Folder Tree listing.

I will implement it one way or another, making sure that it would be useful for different kind of users, at the same time works fast.

I'm also thinking of creating instances for the current window (tabs), adding media viewers/editors and do more enhancements.

The only problem that things get slightly heavier each time. It's not a problem with current hardware but sometimes software does nasty things. For example, I debug and develop in Chromium under Linux (even though ideologically I would like to use Firefox). In case all users used Chromium/Chrome - it would make me totally happy as I would know that users will get interface/speed/usability the way I design them. It's not always the case unfortunately. For example, I have truly high-end hardware on my development desktop PC and Firefox is slow in Fedora Linux with 20-30 tabs opened, of which 2-4 is Authentic Theme with Webmin - this is making me cry.

There are other so called internet browsers like Microsoft Internet Explorer, Apple Safari and etc. They are nice for ordinary use but if you give it a harder "push", they start to "leak" like a pumpkin flask, that looks fine at the first look, right before you put water in it.

My only limitation is the end user's software, really. All the rest seems like lots of fun. :smile: 

I will consider your great (including mail) proposals and try my best to embody it as soon as possible.

**Comment by divyeshsachan** [comment]
I never right clicked on breakcrumb and never knew that typing path option is available in File Manager and even about shortcut Ctrl+L. Its good and serves the purpose of navigation for me and for those who know the exact path. I was going to suggest it but DUMB ME :laughing: , its already there. 

IE sucks ! I never use IE for browsing, but as a developer for perfection i always check and fix everything in IE before releasing it for my users. From my experience if everything is working as expected in IE then it'll work in almost every browser and you never know which browser your users are going to use.

I never used audio/video/tabs for the purpose of managing and editing files, but after these additions "File Manager" will be "Multimedia File Manager" and as you said it'll be heavy for some end users with poor hardware or browsers.

**Comment by qooob** [comment]
I will try ro stop loading libs in general for all modukes and will load it on demand.

**Comment by qooob** [comment]
This is why I made helper (on top left of the container, question mark), so people could take a look and see what's under the hood.

Loading things on demand seems the only reasonable solution though,

**Comment by qooob** [comment]
Did you take a look at version 18.00? How is it?

Anything else there is still missing? Like folder tree?

**Comment by divyeshsachan** [comment]
Apologies for delayed response, i missed to see your reply.

version 18.04 is good, Filemin has some minor changes, but the breadcrumb navigation / folder tree is still missing. It'd be great if you add a dropdown on each level of breadcrumb navigation to get a selectable list of folders of each level. It'd be sp useful while navigating to other tree when exact folder name is not known.

**Comment by qooob** [comment]
Sure, I'll add both a bit later. Or having tree would be enough?

**Comment by divyeshsachan** [comment]
Both will have their own advantages. It'd be great to have both features.

**Comment by qooob** [comment]
I'll think about that.

**Comment by qooob** [comment]
Enhancements will be done in 18.30. Please be patience.

**Comment by divyeshsachan** [comment]
I appreciate your efforts. No issues.

**Comment by qooob** [comment]
Hi,

I have finally made it possible. It's just exactly as in Windows Explorer. It will be useful in some cases.

Thanks for advising.

Here is the videoscreencast teaser. ;) 

It will be available in 18.30. 

I hope it's what you wanted:
http://rostovtsev.ru/pub/src/authentic/18.30b/new_file_manager_dropdown_tree_structure.webm

**Comment by divyeshsachan** [comment]
Yeah !!! This is what I've expected. Perfect.
Thanks a ton for your efforts. 

Eagerly waiting for 18.30  :-)
