### ISSUE TITLE
Authentic Theme - Configserver Firewall Page issues on 17.84 release version

### ISSUE THREAD

**Issue by apurva577** [qooob/authentic-theme#443]
Hello

There is an issue in Authentic Theme Release Version 17.84.

Case 1
After Updating the theme to 17.84 configserver firewall page hangs up and comes without scroll. Sometimes come without theme style. I have tried re-installing theme to 17.83 and its working perfectly on it. Again I updated to 17.84 and again same issue occured.

My config server firewall version is 8.21

I have Virtualmin installed on 25 servers with authentic theme. onfigserver firewall page works perfectly on 17.83 but not in 17.84

**Comment by qooob** [comment]
I had tested it and didn't have such issue. I sounds like cache issue in the browser.

Close Webmin's tab, clear browser's cache and try again. What browser are you using?

**Comment by qooob** [comment]
Any updates here?

**Comment by apurva577** [comment]
Hello

Ya its an cache issue only.

**Comment by qooob** [comment]
Alright.
