### ISSUE TITLE
Export and install authentic theme with custom logos and settings

### ISSUE THREAD

**Issue by AlexShapka** [qooob/authentic-theme#444]
I'd like to customize authentic theme, for example, by uploading logos on the Theme Logos page, and to copy the same configs to multiple servers. I tried to export and then install the theme on the new server, but unfortunately the logos and other settings are gone. Is it possible somehow to copy authentic theme with its custom settings to other servers?

**Comment by qooob** [comment]
Hi,

Yes, you need to copy themes settings that are in `/etc/wrbmin/authentic-theme` as well.

**Comment by AlexShapka** [comment]
Thanks qooob, with your advice I've managed to get custom logos migrated, but unfortunately other custom settings failed to properly migrate. For example, I don't want end users to see slider, so I set the "Enable slider" option to "No" in the "Notification Slider options" section and I can't export this configuration setting to other servers. Can you elaborate how I could copy this settings over multiple servers with the backup file?

**Comment by qooob** [comment]
Yes, after you copied the _configurations_ simply reload _complete window_, by hitting `Ctrl+R` in most browsers.

By doing that, the theme will check for configuration files and updates them. Make sure that the copied files have proper permissions (they are most likely)

**Comment by qooob** [comment]
..or if you don't want to reload the theme and use inly backup script, then you would need to copy all .js files to `unauthenticated/js` and all .css files to `unauthenticated/css` manually. They are rewritten over theme complete reload (first start) or saving the settings.

**Comment by qooob** [comment]
> by all files I mean files from configuration folder that we discussed above.
