### ISSUE TITLE
ConfigServer Security & Firewall: Opened in the new tab shows an empty page

### ISSUE THREAD

**Issue by tswestendorp** [qooob/authentic-theme#445]
When opening CSF from Webmin in a new tab, the page stays blank. The issue is caused by ```<body style="opacity: 0; pointer-events: none;">```.

When removing ```opacity: 0;``` the page shows correctly (not themed though)

**Comment by qooob** [comment]
Yes, at the moment that's the way it is.

It would work under other themes.

Why would you want to open it in new tab?

**Comment by tswestendorp** [comment]
I open it in a new tab because I prefer the unthemed CSF and I think it worked before.

**Comment by qooob** [comment]
Alright, no problem, I will try to do something about that on 18.00+.

Thanks for reporting.

**Comment by qooob** [comment]
The UI of CSF will be improved upon 18.01 even more.

I beg your pardon but I'm not willing to do very complex workaround to support unthemed version of this amazing module.

Please tell me what exactly is missing for you in themed version and I will do my best to improve it.

Version 18.01 will have improved UI of configuration page and server output.
