### ISSUE TITLE
System information page on start page

### ISSUE THREAD

**Issue by abhishekawanti** [qooob/authentic-theme#446]
Hi,
   Firstly i don’t know how bad this idea is to ask.
I am thinking to change the first page i.e. System Information page to some other module as per my wish.That means whenever i login to the webmin the first page to show would be my module.
Can this possible to do?If any chance of achieving this please let me know how it would be?

Thanks in advance.

**Comment by qooob** [comment]
Hi,

Goto `Webmin->Webmin Configuration-> Index Page Options` and set _After login, always go to module_ to whatever you wish.

**Comment by abhishekawanti** [comment]
thanks a lot. :+1:

**Comment by qooob** [comment]
Don't mention it! :wink:

**Comment by abhishekawanti** [comment]
That is the least we can do it for your extraordinary work.. :)
