### ISSUE TITLE
Not enough margin between logos and selection box on certain cases.

### ISSUE THREAD

**Issue by AlexShapka** [qooob/authentic-theme#448]
Certain case is when you have all three Virtualmin, Cloudmin and Webmin installed and replaced their names by custom strings. The logo section then overlaps the selection (or search) box, because of the following css style:

`.select2 {
    margin-top: 4px;
    margin-bottom: 4px;
}`

Changing it to:

`.select2 {
    margin-top: 15px;
    margin-bottom: 4px;
}`

helps in our case. Could you please consider when you have longer replacements names for Virtualmin, Cloudmin and Webmin like shown on the attachment.
![screen shot 2016-04-25 at 4 53 37 pm](https://cloud.githubusercontent.com/assets/9372724/14802647/62cc5d2e-0b07-11e6-937b-b594ef1b23b9.png)

**Comment by qooob** [comment]
Yes, I'll try. Thanks.

**Comment by qooob** [comment]
Isn't better to decrease line-height?

**Comment by qooob** [comment]
Well, actually, this is why we have an ability to inject .CSS code. Why not just:

```CSS
#sidebar ul.navigation {
	margin-top: 15px;
}

```

**Comment by AlexShapka** [comment]
I know about using CSS, but then custom modifications will get overriden by future releases, so that's why this kind of inconsistencies are good to be addressed on developer level.

**Comment by qooob** [comment]
No, this is why they are there. It's not overridden!

Got to `Webmin->Webmin Configurations->Themes->Current Theme`. At the very bottom fine `Theme Extensions`. Add that piece of code and hit save.

It's work for as long as you don't remove it manually.

**Comment by AlexShapka** [comment]
Fair enough. Thanks!
