### ISSUE TITLE
Package update spinner stayed active quite long

### ISSUE THREAD

**Issue by j0bb13** [qooob/authentic-theme#449]
The update of webmin-virtual-server failed, after which the spinner in the top right kept spinning for quite some time and I couldn't scroll up without being dropped to the bottom immediately. Even though no more text was appearing and it already said _Successfully installed 7 packages_. I didn't check exactly, but I think the spinner disappeared after about a minute.

When the page reports being done, the spinner should also disappear right?

![virtualmin update error](https://cloud.githubusercontent.com/assets/2331451/14848888/36a16d88-0c70-11e6-8cfe-e833b839326a.png)

P.S.
I posted my request for a more informative summary like _Successfully installed 7 packages and failed to install 1 package_ at https://github.com/webmin/webmin/issues/315, since I assumed this was Webmin core and not theme related.

**Comment by qooob** [comment]
Yes, spinner would disappear but the moment you're talking about - it shouldn't. The reason is that the page is still processing at that point by the server. When the blue back button appears than it's done.

It's not theme related.

**Comment by qooob** [comment]
Take a look here:
https://github.com/webmin/webmin/issues/282

**Comment by j0bb13** [comment]
Aaaaah, true. My mistake :)

**Comment by qooob** [comment]
You can see that the page is still loading on your screen shot, at the tab, there is also a browser's spinner! ;)

**Comment by j0bb13** [comment]
Yes, I didn't notice the missing button and I assumed it was done because it said _Successfully installed 7 packages_, because the button usually appears almost instantly. But this explains it, thanks! :+1:
