### ISSUE TITLE
IP Address on dashboard

### ISSUE THREAD

**Issue by cguhring** [qooob/authentic-theme#450]
Hello,

This theme is really awesome and pushes webmin into a new era... :)

It would be great if the IP address displayed in the dashboard, on the first line (Hostname) could be the actual network IP, or at least show all active interfaces if the one relevant can not be identified.

On 3 of 4 webmin installlations, this ip shows 127.0.1.1 instead of 192.x.x.x or other external IP.

**Comment by qooob** [comment]
Hi, thanks! :)

What do you have in Network Configuration settings? Webmin uses first address from the static configuration as far as I'm aware. Do you have same output in Gray Theme?

**Comment by cguhring** [comment]
Yes, the output is the same on the grey theme (i haven't noticed at all that the dashboard = system information, I thinked that Authentic theme  crated the dashbord itself...)

Have you an idea on how make webmin display the right ip address ? In all servers, the first static conf is eth0....

**Comment by cguhring** [comment]
OK... I've searched around with other query (I've been focalised with authentic theme before)

Webmin uses hostname/ip adress defined in /etc/hosts

so simply edit the hosts file accordigngly.
I've tested with removing the line, webmin dislplay only the short hostname without ip...
It's not 100% what i'm excpected, but it works... :)

Thanks

**Comment by qooob** [comment]
This could be tricky to answer exactly, as it's system dependent and dependent on your configuration as well.

Probably [this](http://askubuntu.com/questions/627899/nameserver-127-0-1-1-in-resolv-conf-wont-go-away) will help.

**Comment by qooob** [comment]
Alright, good to hear than! ;)
