### ISSUE TITLE
Theme: Cloudmin version detected incorrectly.

### ISSUE THREAD

**Issue by rubenszolt** [qooob/authentic-theme#452]
On fresh install cloudmin GPL with virtualmin GPL, detect my cloudmin version incorectly PRO.
Cloudmin version 	8.4.kvm Pro

**Comment by qooob** [comment]
Ok, I'll take a look.

Thanks for reporting.

**Comment by rubenszolt** [comment]
Thanks, I have another request, it is posible to display the drivers temperatures in line, not under each other. I have 4 drivers on server.

**Comment by qooob** [comment]
You can change it in theme settings already.

**Comment by qooob** [comment]
Once again, you have installed GPL versions only?

**Comment by qooob** [comment]
Do one more thing please. Open page source and find `data-virtual-server-license` and `data-server-manager-license`, what are the values for it?

**Comment by qooob** [comment]
..but you must open the source of the left frame by clicking on the navigation menu and selecting the `show source`..

**Comment by rubenszolt** [comment]
Yes I installed just GPL version. 
data-virtual-server-license="0"

**Comment by rubenszolt** [comment]
Today I updated the cloudmin-server-manager to 9.0.kvm GPL version, and same issue.

**Comment by qooob** [comment]
Ok, I'll take a look.

**Comment by qooob** [comment]
Please test it with 18.00. I suppose it's still not displaying it correctly? If not just report here and I will do a fix look in 18.01.

**Comment by rubenszolt** [comment]
Same issue, i tested under 18.00 version
[http://server.rubencom.hu/images/authentic-theme2.jpg](url)

**Comment by qooob** [comment]
If you switch back to default theme, what do you see??

What is the output of `/usr/share/webmin/server-manager/module.info` or for RHEL systems `/usr/libexec/webmin/server-manager/module.info`?

**Comment by qooob** [comment]
Will be fixed in 18.01. But please double check and tell what is the output of above.

**Comment by rubenszolt** [comment]
Hi, today i updated to 18.02 version and same issue (BUG), I install authentic theme to other two servers and not detect the corect Cloudmin licence. 
 
/usr/share/webmin/server-manager/module.info output
desc=Cloudmin GPL for KVM
category=webmin
depends=servers net proc 1.480
os_support=*-linux
version=9.0.kvm
onehost=kvm
vm2=kvm
gpl=1
desc_cz=Cloudmin GPL pro KVM
desc_cz.UTF-8=Cloudmin GPL pro KVM

**Comment by qooob** [comment]
Alright, I will test it later and come back to this issue.

**Comment by qooob** [comment]
Can you find in `authentic-lib.pl`

```Perl
sub licenses {
    my ($id) = @_;
    if ( &foreign_available("virtual-server") && $id eq "vm" ) {
        my %virtualmin = &get_module_info("virtual-server");
        if ( $virtualmin{'version'} =~ /gpl/i ) {
            return 0;
        }
        else {
            return 1;
        }
    }
    elsif ( &foreign_available("server-manager") && $id eq "cm" ) {
        my %cloudmin = &get_module_info("server-manager");
        if ( $cloudmin{'version'} =~ /gpl/i ) {
            return 0;
        }
        else {
            return 1;
        }
    }
    else {
        return 0;
    }
}

```

And replace it with:

```Perl
sub licenses {
    my ($id) = @_;
    if ( &foreign_available("virtual-server") && $id eq "vm" ) {
        my %virtualmin = &get_module_info("virtual-server");
        if ( $virtualmin{'version'} =~ /pro/i ) {
            return 1;
        }
        else {
            return 0;
        }
    }
    elsif ( &foreign_available("server-manager") && $id eq "cm" ) {
        my %cloudmin = &get_module_info("server-manager");
        if ( $cloudmin{'version'} =~ /pro/i ) {
            return 1;
        }
        else {
            return 0;
        }
    }
    else {
        return 0;
    }
}

```

That part seems to be making the problem. Reboot Webmin afterwards. Does it fix the issue?

**Comment by qooob** [comment]
I have updated 18.02 which will fix your bug. Just force upgrade.
