### ISSUE TITLE
Theme: Blinking navigation menu

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#453]
There appears to be a bug ( I guess this to be a Chrome issue) using the above browser 
symptoms are if you try to load a module in the right frame the left frame (menu) flashes with a white background along with the notification Bell image (this gets a white background also) I have not tested this using the windows OS. I posted this just in case some else is getting the same using the same config.

>Linux Chrome Version 49.0.2623.108 Ubuntu 16.04 (64-bit) Issue

**Comment by qooob** [comment]
I use Linux with Chrome and it seems alright for me?

Could you post a screenshot or at best video-screencast please?

**Comment by qooob** [comment]
Chrome 50 is out, why not upgrade?

**Comment by JimTR** [comment]
This is a new 16.04 install as it is out of the box it comes with that version of chrome ? .... I'll send a video soon

**Comment by qooob** [comment]
Ok, please do.

**Comment by qooob** [comment]
Gnome has inbuilt video-recording, at least in Fedora.

**Comment by JimTR** [comment]
Here is the movie
[out.zip](https://github.com/qooob/authentic-theme/files/243863/out.zip)

**Comment by qooob** [comment]
Wow. That is strange, my friend!

I will test it on my Macs. Version 18.00 is coming soon. It will have great amount of changes/improvement. Maybe it will resolve itself. 

Does it happen in other browsers on the same machine? I look to me like video-drivers issue?

**Comment by JimTR** [comment]
just tried firefox on the same machine no problems at all I also tried opera this does have the issue , this sort of indicates that perhaps it a webkit/blink problem

**Comment by qooob** [comment]
I would think this is Chrome version specific. Could you install `chrome-beta` to double check?

**Comment by JimTR** [comment]
I have just tried Version 51.0.2704.29 beta (64-bit) and the prolem is worse, it now flashes about ten times ! I am using the Xorg driver for graphics as there is no support in Ubuntu 16.04 for skylake hardware

**Comment by qooob** [comment]
Ahh, I see. Anytime I used `nouveau` on my system everything was flashy and falling apart.

I bet you could reproduce this issue with other web-sites. Find some 'heavy' webiste and try.

I will not be able to help you with that.

Version 18.00 will be much lighter so issue might resolve itself.

**Comment by qooob** [comment]
(Linux 4.4 kernel emerges with better support for Intel Skylake and Raspberry Pi)[http://www.theinquirer.net/inquirer/news/2441309/linux-44-kernel-emerges-with-better-support-for-skylake-raspberry-pi-and-amd]

**Comment by JimTR** [comment]
I tested some site using Chrome no flashing at all, with one exception if the site contains sliders I do get a slight flash but you really have to look for it .... Playing games on steam (this is very heavy) is rock steady, I guess they must have based the interface on Firefox. 
I guess for now I'll use Firefox to view my webmin installs as it does not suffer from the problem. I guess there will a graphics driver written for my hardware at some point

**Comment by qooob** [comment]
Left menu has `transition` and other filters allied. This probably causing the issue.

You could try to run Chrome with out GPU acceleration this might help.

**Comment by JimTR** [comment]
> You could try to run Chrome with out GPU acceleration this might help.
this has fixed the issue

**Comment by qooob** [comment]
It's alright now?

**Comment by JimTR** [comment]
I have tested in the stable version and yes it now works as expected, but has thrown another slight display issue ... I'll send another video

**Comment by JimTR** [comment]
new video
[out-1.ogv.zip](https://github.com/qooob/authentic-theme/files/245380/out-1.ogv.zip)

**Comment by qooob** [comment]
Yeah, I see. This is definitely software/hardware issue. I had in the past.

Nothing else I can do here.

Good luck.

**Comment by JimTR** [comment]
it is now usable so perhaps I don't need to use a firefox browser after all ... it is odd Firefox works perfect & chrome does not using exactly the same hardware. so I guess the software that is failing is chrome

**Comment by qooob** [comment]
Firefox doesn't have acceleration enabled, I think this is why issue doesn't happen. I bet you will see it all across your OS unless you install proper drivers.

Take a look and try installing

**Comment by qooob** [comment]
`mesa-vdpau-drivers`

or other `vdpau-` like drivers..

It might work.

**Comment by JimTR** [comment]
Just so you know
Chrome works in the following way using Ubuntu 16.04 with skylark hardware
1) turn off acceleration - nearly fixes it
2) clear the cache in the theme setup - doing this shows a figure again on the bell if there is an update to do ... this feature did not work until the cache was cleared note Theme cache & not browser cache.

Please note this only effects any chrome based browser so if you are getting this problem and don't wish to use a firefox based browser use the above, with the install of Ubuntu 16.04  Firefox & the Ubuntu browser are installed ... so you can view webmin straight away after install

**Comment by qooob** [comment]
Thanks for letting know.

**Comment by JimTR** [comment]
In the end there was so much problem with chrome I took the point to use firefox instead as chrome is so unstable .. sometime I get errors other times I don't .... worst error clicking the virtualmin tab as an admin the select box containing the domains you can administer is missing you have to use the list virtual servers link and choose the domain from there. As pointed out earlier in this thread this may be due to a driver problem within the client but this should not happen so you can access the data from any connection from any platform sadly not

**Comment by qooob** [comment]
This is surely driver problem.

**Comment by JimTR** [comment]
you are 100% right but there is the point that a user logs into there webmin/virtualmin site and gets lots of problems and therefore thinks webmin is a poor product (which it is not) due to the gui not performing as it should. There may be a few people who have upgraded to Ubuntu 16.04 with near the same hardware as I have got and discontinue using the product thro bad display. as said before I don't care as I am now aware I need to use firefox

**Comment by qooob** [comment]
I'll consider making manual about it.

**Comment by JimTR** [comment]
cool

**Comment by qooob** [comment]
Isn't there proprietary driver for your hardware? It would solve the issue most likely!?

**Comment by JimTR** [comment]
as I said before Ubuntu 16.04  removed the skylark driver from their repositories so therefore you can only use the default one .... if you try to install a different driver Ubuntu just ignores it .. all the advice on drivers you have given using apt-get  returns 'at the latest version'
