### ISSUE TITLE
two return Usermin configuration button

### ISSUE THREAD

**Issue by rubenszolt** [qooob/authentic-theme#454]
On Usermin / Edit Categories I have two Return to Usermin configuration button.

**Comment by qooob** [comment]
This is Webmin bug, not the theme. I will let Jamie know, he will fix it.

Thanks for reporting.

**Comment by jcameron** [comment]
I see the cause - this will be fixed in the next webmin release.

**Comment by qooob** [comment]
Ok, thanks.
