### ISSUE TITLE
virtulamin-analytics not open corectly

### ISSUE THREAD

**Issue by rubenszolt** [qooob/authentic-theme#458]
When I click on virtualmin-analytics menu, it is disapear the left navigation menu and open the first System Information page.

**Comment by qooob** [comment]
Not sure what you mean. Could you please provide a screenshot or at best video-screencast?

The other way is to describe exactly how to reproduce the problem. Is it ok in old theme?

**Comment by rubenszolt** [comment]
It is an virtualmin issue, I tested on old theme and same issue, if i click to virtualmin-analytics menu it disappear the left navigation menu.

**Comment by qooob** [comment]
I will notify Virtualmin developer to see what he says.

Thanks for reporting!
