### ISSUE TITLE
Cannot modify the Resource limits of CPU

### ISSUE THREAD

**Issue by rubenszolt** [qooob/authentic-theme#459]
I attach a screenshot
http://server.rubencom.hu/images/authentic-theme1.jpg

**Comment by qooob** [comment]
Can you edit this in the default theme?

**Comment by rubenszolt** [comment]
I Think is an Cloudmin issue, on previous version is working, but after update I tested on default theme It also does not cannot modify.

**Comment by qooob** [comment]
I will notify Cloudmin developer. Will see if it's really a bug.

Thanks for reporting.

**Comment by jcameron** [comment]
What type of VM is this? Not all of them support editing CPU limits

**Comment by rubenszolt** [comment]
I use KVM VM, before on previous versions I have this setting.

**Comment by jcameron** [comment]
Damn, this is a bug in Cloudmin 9.0. The work-around is to change the CPU limit using the shell API command `cloudmin modify-limits --host your-vm-name --cpu 55`

**Comment by qooob** [comment]
Jamie, probably it's also related? https://github.com/qooob/authentic-theme/issues/458

**Comment by jcameron** [comment]
No, I think that other issue is a different problem
