### ISSUE TITLE
Theme: Log display and escaped HTML issue?

### ISSUE THREAD

**Issue by latitudehopper** [qooob/authentic-theme#460]
webmin > system > system logs

The < and > characters are encoding incorrectly.

![system logs webmin 1 791 on cdbx eu ubuntu linux 14 04 4](https://cloud.githubusercontent.com/assets/6178463/15091190/cc0758fe-1438-11e6-8267-a7263bf90a11.png)

**Comment by qooob** [comment]
What do you see in Gray Theme? Isn't it the same? Could you please check?

**Comment by qooob** [comment]
Oh, ok! I've checked it myself. True. It shouldn't be happening!

Thanks for reporting. I will try fixing it in 18.00

**Comment by qooob** [comment]
It will be fixed in up-comming version 18.00 very soon.
