### ISSUE TITLE
Radio Buttons disoplaying strangely

### ISSUE THREAD

**Issue by NettSite** [qooob/authentic-theme#461]
Hi,

I am seeing strange characters instead of radio buttons. This happened once before, but corrected after an upgrade - I can't remember which one. However, a few upgrades later, it is back.

I have uploaded a screen shot, hope it is visible.

![selection_031](https://cloud.githubusercontent.com/assets/11553107/15113208/317f955a-15f3-11e6-88d1-99f218d363da.png)

**Comment by qooob** [comment]
:) This is very strange! All of the radios are completely reworked in upcomming 18.00.

Did you try to reload the current frame?

**Comment by qooob** [comment]
I can see them in my dev 18.00.

**Comment by NettSite** [comment]
All the radio buttons on all the forms are like that, on two different installations, and from two different workstations, both Chrome / Fedora.

I must be an edge case, I have all the weird problems.

**Comment by qooob** [comment]
Expect it to be fixed in 18.00! ;)

Thanks for reporting.
