### ISSUE TITLE
BIND DNS Server: Loading animation keeps running endlessly

### ISSUE THREAD

**Issue by ET-Bent** [qooob/authentic-theme#463]
Using `Authentic Theme 17.84` on `Webmin 1.791`.

Once clicking a *safe* or *create* button or anything rather then loading a new page, an endless loading animation is started, which will slowly move from left to right. The action itself is saved, but the page is not automatically reloaded.

![auswahl_021](https://cloud.githubusercontent.com/assets/5788982/15358797/8c95826e-1d06-11e6-88bc-748615bf173d.png)

Webmin is running behind an NGINX reverse proxy, Vhost config:

```
upstream backend {
  # the webmin server
  server 127.0.0.1:1000;
  keepalive 64;
}

server {
  listen 80;
  server_name *** SECRET ***;
  return 301 https://$server_name$request_uri;
 }

server {
  listen 443 ssl http2;
  server_name *** SECRET ***;

  # strenghen ssl security
  ssl_certificate /etc/letsencrypt/live/*** SECRET ***/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/*** SECRET ***/privkey.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
  #ssl_dhparam /etc/ssl/certs/dhparam.pem;

  # Add headers to serve security related headers
  add_header Strict-Transport-Security "max-age=15768000; preload;";
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";

  location / {
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host:$server_port;
      proxy_pass http://backend;
      proxy_http_version 1.1;
      proxy_pass_request_headers on;
      proxy_set_header Connection "keep-alive";
      proxy_store off;
  }
}
```

**Comment by qooob** [comment]
Just the spinner? Nothing else? Does it save things?

**Comment by ET-Bent** [comment]
Yes just the spinner, it saves all changes but the site does not reload.

**Comment by ET-Bent** [comment]
Edit: Once clicking `save` (or similar) I get the following in Chromes console:
```
edit_record.cgi:1 Mixed Content: The page at 'https://** SECRET **/' was loaded over HTTPS, but requested an insecure form action 'http://** SECRET **:443/bind8/edit_recs.cgi?zone=powereclipse.com&view=any&type=A&sort='. This 
```

The issue itself is clear as NGINX provides ssl for Webmin. To allow a reverse proxy to work I had to disable ssl in Webmin itself. If I did not do this I cannot access Webmin anymore getting an error that I shall use `my.foodomain.tld:1000` which obviously is not the point of a reverse proxy.

**Comment by qooob** [comment]
Has it been fixed for you in 18.00?

**Comment by ET-Bent** [comment]
No, error is still present in there.

What additional information is needed?

**Comment by qooob** [comment]
Can you open console and check for errors?

**Comment by qooob** [comment]
Any luck?

**Comment by ET-Bent** [comment]
Chrome console output:

(Sorry for late reply)

```Mixed Content: The page at 'https://SOMESERVER/' was loaded over HTTPS, but requested an insecure form action 'http://SOMESERVER:443/bind8/edit_recs.cgi?zone=SOMESERVER&view=any&type=A&sort='. This request has been blocked; the content must be served over HTTPS.```

**Comment by qooob** [comment]
Can you switch to Gray Theme and try again? It doesn't seem to me as theme issue.

**Comment by qooob** [comment]
I expect this error also happen in _Gray Theme_, because theme doesn't change `action` attribute for `form` tag.

It should be tweakable on the Webmin side, I bet Jamie had forseened it!

In this case scenario, in case you still need help, post a question to `/webmin` repo as this issue has been inactive for about 3 months already and I can't reproduce it in default (non proxy) mode, using _miniserv_.

**Comment by marktamis** [comment]
I fixed this on my install by making the redirect path relative rather than absolute

https://github.com/webmin/webmin/issues/267
