### ISSUE TITLE
CSF Settings will not scroll

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#464]
On a Mac, CSF Firewall Configurations will not scroll on Firefox or Chrome. I can refresh a bunch of times in a row and intermittently it will work.

**Comment by qooob** [comment]
I will fix it in 18.00, thank you for reporting.

**Comment by SteffanCline** [comment]
Is there a timeline?

**Comment by qooob** [comment]
I've been working on it every single day for many hours since last release. I'm about 3/4 trouhgh.. About a week or so and it's out.

**Comment by SteffanCline** [comment]
Is there a list of planned features?

**Comment by qooob** [comment]
Not the one I could predefine in the first place. The list is growing evey time a do something, like avalanche. I could send you current dev changelog in FB if you wish.

**Comment by SteffanCline** [comment]
It's already so great I just can't image what's left to add.

**Comment by qooob** [comment]
Ohh. No, it's not. It'll be notable improvement, especially seen in tables rendering across everywhere, not mentioning new features - a lot of which for File Manager.

**Comment by SteffanCline** [comment]
Well, I look forward to it!

**Comment by qooob** [comment]
Alright, thanks.

**Comment by qooob** [comment]
Theme Version 18.00 is out - please upgrade as soon as possible!
