### ISSUE TITLE
system information does not seem to refresh properly

### ISSUE THREAD

**Issue by designerjason** [qooob/authentic-theme#468]
![webmin](https://cloud.githubusercontent.com/assets/4128631/15556163/6e2e78da-22c4-11e6-989e-dc1b95613a26.jpg)
Some elements of the system information page don't seem to update when I hit refresh, i.e the piechart values. But some info is correct like the number of processes. When I go to running processes the values seem to be correct

**Comment by qooob** [comment]
The theme gets data from WebminCore.

If true we'll investigate that,

**Comment by qooob** [comment]
It's updated within 300 seconds by default. It's coming from WebminCore. You could change this value in Webmin Configuration->Scheduled Functions to get faster System Information updates.

In the future, this might be reworked.

**Comment by designerjason** [comment]
it actually seemed to be some kind of cache issue, I rebooted the server and it fixed it.

**Comment by qooob** [comment]
Alright. Good to hear.

Cache issue is the most often problem that causes unexpected behaviour.
