### ISSUE TITLE
Theme: Crontab selection in scheduled backup

### ISSUE THREAD

**Issue by albertovincenzi** [qooob/authentic-theme#470]
If you try to schedule a backup in Virtualmin and you open the complex schedule, the pop-up window isn't themed.

**Comment by qooob** [comment]
I know. It's in my to do. It's complicated to do. Will be there.

Upgrade to 18.00. Just out.

**Comment by albertovincenzi** [comment]
I just update and then noticed it.
Anyway, thanks!

**Comment by qooob** [comment]
It wasn't themed before, right?

**Comment by albertovincenzi** [comment]
No, it wasn't but I noticed it today for the first time, only after update the theme I tried that option

**Comment by qooob** [comment]
Version 18.01 made some things on that part of of the page look strange. I will fix it right away in 18.02.

Theming for all popup is comming in the future.

**Comment by qooob** [comment]
Please upgrade.
