### ISSUE TITLE
Theme: Version 18.00 patches security vulnerability - Immediate upgrade is necessary

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#472]
It's important for anyone using **Authentic Theme** between versions **17.81~17.84** with enabled _Security Alerts_ to upgrade to the latest version _18.00_ as soon as possible. https://github.com/qooob/authentic-theme/issues/467 https://github.com/qooob/authentic-theme/issues/471

_Security Alerts_ were removed from the theme and promised to be added to _WebminCore_ in the near future.

_Webmin_ 1.800 has patched version of _Authentic Theme_ 17.84 but brings some other issues. https://github.com/qooob/authentic-theme/issues/469 

------

###### I bring an appology personally to everyone for such horrible oversight  :disappointed:

**Comment by sz00gun** [comment]
Thanks for it, however since I have Authentic Theme 18.00, my CPU works on **100%** all the time, all websites works very slow..... twice server went down :(

I have old Webmin theme now.... please advise what to do now? Also upgraded Webmin to 1.801 just...

**Comment by qooob** [comment]
It's not the theme for sure! Please check https://github.com/qooob/authentic-theme/issues/471.
Search for Running Processes. Try rebooting the server.

**Comment by andreychek** [comment]
Yeah if the CPU of your server is at 100%, it sounds like something else is going on.  You may want to review the processes running on your server (which you can do with "ps auxw" and "top"). The top command can help you figure out which processes are using a lot of CPU.

You may want to open up a new Forum thread over at virtualmin.com to discuss that, as you may be seeing a general server problem.
