### ISSUE TITLE
ConfigServer Security & Firewall: Configuration Page Cannot be Scrolled

### ISSUE THREAD

**Issue by alexp999** [qooob/authentic-theme#473]
You cannot scroll down to change or save anything in CSF configuration page.

There is an overflow hidden applied to the body of the iframe it is displayed in.

If I use inspect element and turn that off I can scroll the page and use it normally.

**Comment by qooob** [comment]
If you open console, does it show an error?

**Comment by qooob** [comment]
When did you install the 18.00 theme? You might start from doing the following:

Go to theme settings and force upgrade. I pushed couple of updates after right into 18.00 exactly with CSF updates.

If doesn't help. 1. Clear browser cache. 2. Restart Webmin.

If still no luck, please open the right frame source and copy/paste it here (you can remove sensitive info (if there is any))

**Comment by alexp999** [comment]
Force update and cache clear fixed it.

Must have been fixed after I updated :)

Thanks.

**Comment by qooob** [comment]
Yes! Good to know. Please be kind doing more extensive CSF testing and report back if you find anything!
