### ISSUE TITLE
No hdd temps after upgrading to version18.00

### ISSUE THREAD

**Issue by ChriZathens** [qooob/authentic-theme#474]
Hi there!
Thanks a lot once again for your great theme!
I am facing a small issue: Logged in today in webmin and had both webmin 18.01 and authentic theme 18.00 update prompts.
After both upgrades I  can no longer see the drive temperatures.
I haven't changed anything and smartctl results showing normally the info.
Any ideas?

**Comment by ChriZathens** [comment]
OK... Scratch that..
Someone is messing with me...
It started appering normally a minute after I posted the issue... Apologies

**Comment by qooob** [comment]
Yes, I also see it. Should be no problem.

Webmin has strage cahce issues - that is for sure.
