### ISSUE TITLE
ConfigServer Security & Firewall: No scrolling on Iptables Log pages

### ISSUE THREAD

**Issue by rubenszolt** [qooob/authentic-theme#475]
Not work the scrolling on Iptables Log pages. I use 18.00 version

**Comment by qooob** [comment]
I just was checking it everywhere. All was fine. 

How do I get to the page where you have no scrolling? Make a videoscreencast please.

Try to reliad Webmin and clear browser's cache - it'll be OK!

**Comment by rubenszolt** [comment]
I tested again, under Chrome I can scroll but under Firefox 45.1.1 not, I clear cache from browser, cache from webmin but same issue.
[http://imgur.com/bAi0jQF](url)

**Comment by qooob** [comment]
Just double checked - there is scrolling on IPtable log. 

What can happen:
  1. You enter to CSF using right notification panel - then yes, there is a bug, which I will try to fix in 18.01
  2. You installed version 18.00 of the theme right after it was released. Few hours after initial release I release repacked version of 18.00 with CSF fixes.

Try force upgrading the theme from theme settings, clear cache and tell me if you can scroll IP log by going to it from CSF module (not notification panel).

Theme CSF is very hard. Version 18.01 will make things look perfect. I'm adding couple more nice tweaks.
