### ISSUE TITLE
Undefined subroutine &main::notify called at /usr/share/usermin/authentic-theme/session_login.cgi line 66.

### ISSUE THREAD

**Issue by stefanmoldoveanu** [qooob/authentic-theme#477]
No login screens appears, instead the specified Perl error is thrown.

Operating system 	Ubuntu Linux 14.04.4
Webmin version 	1.801
Usermin version	1.701 
Virtualmin version 	5.03 Pro
Theme version 	Authentic Theme 18.00
Kernel and CPU 	Linux 4.2.0-36-generic on x86_64

**Comment by qooob** [comment]
`sub notify()` has been removed. What you experiencing is Webmin cache issue that happened already 100 of times.

To solve it:
   1. Reload webmin - `/etc/webmin/restart`
   2. Reboot the server

**Comment by stefanmoldoveanu** [comment]
Thank you.

**Comment by qooob** [comment]
You're welcome! ;)
