### ISSUE TITLE
File Manager: Tabs information should be user-specific between sessions

### ISSUE THREAD

**Issue by alexp999** [qooob/authentic-theme#478]
If you login as a non-admin webmin site use and use filemin, when you log in as a different user (e.g. root), it tries to load the previous path opened in filemin when you open it (I assume set via cookie which isn't cleared on logout?), but returns an error as it can't find it, disclosing the path the last user was looking at.

I realise this isn't a big deal as it requires two different users to be using the same PC and browser, however as I frequently flick between the admin account and site user accounts, I've noticed it and I thought I'd better bring it up in case it is just part of a bigger issue.

**Comment by qooob** [comment]
Hi,

It sounds as very possible issue. I will try add user checking. It happens because of new feature - tabs.

Thanks for reporting!

**Comment by qooob** [comment]
That was hard.

Version 18.01 will make it possible.

Thanks for the idea.
