### ISSUE TITLE
Usermin stuck in loading state

### ISSUE THREAD

**Issue by aminkh17** [qooob/authentic-theme#479]
Hi all,

recently in my server Usermin stuck in loading state.

Any idea to how to debug and find the issue?

Thanks

**Comment by qooob** [comment]
That is possible. I noticed it. What Webmin/Usermin/Theme version do you have installed?

**Comment by aminkh17** [comment]
Webmin 1.801
Virtualmin 5.03
Authentic Theme 17.84

**Comment by aminkh17** [comment]
Today updated to Authentic Theme 18.00

**Comment by qooob** [comment]
Latest Usermin that I see is `1.701`. Jamie promissed to deal with that bug that you're experiencing. After upgrading UM don't forget to reload it.

**Comment by qooob** [comment]
And update the theme to Usermin manually.

**Comment by aminkh17** [comment]
Thank you, 
I'll try

**Comment by qooob** [comment]
How did it go?
