### ISSUE TITLE
Feature Request: Hyperlinks from sysinfo data

### ISSUE THREAD

**Issue by chrispolley** [qooob/authentic-theme#480]
Hi, this is a low-priority feature request... it would be convenient if the sysinfo dashboard data (sysinfo_cpu_percent, sysinfo_mem_percent, sysinfo_virt_percent, and sysinfo_disk_percent pie graphs) were linked to appropriate detailed reports, such as sysinfo_cpu_percent -> /proc/index_cpu.cgi, sysinfo_mem_percent & sysinfo_virt_percent -> /proc/index_size.cgi, and sysinfo_disk_percent -> /disk-usage/.  This could allow for quick (one-click in some cases) diagnosis of an abnormal reading.

Thanks!

**Comment by qooob** [comment]
What a nice idea.. Let me take a look...

**Comment by qooob** [comment]
It will be added to 18.01 - nice.

What is `disk-usage`??

**Comment by chrispolley** [comment]
The disk-usage module.  Shows a collapsable/expandable tree of usage by
directory node. Sorry, it is a third-party module by Jamie Cameron;
http://www.webmin.com/download/modules/disk-usage.wbm.gz  I was thinking it
was a built-in.  Maybe the linked module could be configurable.

**Comment by qooob** [comment]
ok, I see now. I will make it also work with `disk-usage`. ;)

**Comment by chrispolley** [comment]
Thanks!  That was much quicker than I had hoped!

**Comment by qooob** [comment]
;)
