### ISSUE TITLE
File Manager: Extracting an archive

### ISSUE THREAD

**Issue by NettSite** [qooob/authentic-theme#481]
Hi,

I don't see an option to extract an archive when I right click one. It has been gone for a few versions, I was hoping it would be back in 18 but it isn't.

18 is great, BTW, all radio buttons are radio buttons again, and tabs are awesome. I miss the filter being always open and visible, though.

**Comment by qooob** [comment]
Hi,

You don't need the filter to be opened. Just start typing whenever you're focused on FM content window (pretty much always), the search/filter will automatically start. It will be different for each tab.

What extract method is missing for you? Did it work in 17.84 on the same machine?

**Comment by NettSite** [comment]
Hi,

No, it didn't work on 17.84. I can't remember when it stopped working.

Just tried the filter - that is so clever! Holy shit.

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by qooob** [comment]
William, thanks! I'm glad you like it. It was my point. ;) Another useful point, if it's only one entry after applying the filter, hitting enter in the search filed will actually open that only folder.

It's simple - version 18.00 overrides all default actions for FM. In case you don't see _Extract_ icon it means binary is not installed.

Even though you have `tar` installed not all commands will work, check that you have all of the listed below to support all possible archives:

`7z, unrar, unzip, bzip2, gzip, xz` and of course tar.

In case you got it all - the icon will be there. Just reload the FM page after applying the update. 

Note: Ubuntu has almost all of them installed by default, where in RHEL you would need to install them manually.

**Comment by qooob** [comment]
How is it?

**Comment by XhmikosR** [comment]
@qooob: even if I disable in File Manager the option "Hide actions column", it's gone after I log out, clear cache and log in again. The same happens for "Hide actions column".

**Comment by qooob** [comment]
Yes, it's the way it works at the moment.

Later, will make is save on the server.

**Comment by NettSite** [comment]
@qoob: I am not getting the "extract" option - I need to open an terminal each time, and that works, so the binaries must be there. I am on Ubuntu 14.04.

**Comment by qooob** [comment]
You don't see an icon or Extract option at all? This is strange as I'm testing in on Ubuntu (16.04) now and it seems to work.

**Comment by NettSite** [comment]
Nothing - and the file icon is a little "binary" image instead of the
"archive" image.

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by qooob** [comment]
Oh, what is written in Type field?

**Comment by qooob** [comment]
Alright, I see now. In case you don't see it's type correctly, it means that your MIME type is not detected. Jamie changed it to internal library since last release. You might want to check your default MIME types and that they are installed correctly.

It's not File Manager issue. In case you believe it should work and it doesn't please file an issue to Webmin repo.

Do we need .rpm/.deb extraction?

**Comment by qooob** [comment]
Ok, tell me something, I have doubts now..

Go to that directory where you have an archive, reload the page using context menu of the browser (reload only right frame) - now, do you have correct MIME type detection??

**Comment by qooob** [comment]
..and working extraction?

**Comment by qooob** [comment]
..and again.. No, my bad. Jamie unckecked those changes I was thinking about before.

Strange that you don't have correct MIME type working. I'll ask for help, will see.

**Comment by Real-Gecko** [comment]
Install `shared-mime-info` package on your system.

**Comment by Real-Gecko** [comment]
https://pkgs.org/search/shared-mime-info

**Comment by qooob** [comment]
Oh, cool! Thanks for advising, Sasha! :) That might be it!

**Comment by qooob** [comment]
I've added to 18.01 `.rpm` and `.deb` extraction, when needed dependencies are installed.
