### ISSUE TITLE
running backups, checkbox not selectable

### ISSUE THREAD

**Issue by perler** [qooob/authentic-theme#482]
at ../virtual-server/list_running.cgi you cannot select the running backup. clicking the checkbox opens the backup (instead of checking the box), which makes it impossible to stop running backups.

**Comment by qooob** [comment]
Could you please provide a screenshot?

**Comment by perler** [comment]
![running backups webmin 1 801 ubuntu linux 14 04 3](https://cloud.githubusercontent.com/assets/623092/15804467/6e47e5c0-2b09-11e6-8839-bf77002a4865.png)

This seems to happen only if the destination column wraps, if it is a short destination on one line I can select the checkbox just fine.

**Comment by perler** [comment]
the same seems to happen on the scheduled backups page, so maybe it is a general problem with wrapped columns.

this is chrome btw.

**Comment by qooob** [comment]
Please be kind upgrading to 18.00 - it should fix your issue. This version has a lot of improvements and security issue fixing. Also upgrade Webmin to 1.801.

**Comment by perler** [comment]
looks good, thanks!

On Tue, Jun 7, 2016 at 10:38 AM Ilia Rostovtsev <notifications@github.com>
wrote:

> Closed #482 <https://github.com/qooob/authentic-theme/issues/482>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qooob/authentic-theme/issues/482#event-684043337>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAmB9IgbPSD7xoSHNHKsNwpw8sRxbvbAks5qJS39gaJpZM4IuTvD>
> .
>
--
