### ISSUE TITLE
Encoding issue on some pages

### ISSUE THREAD

**Issue by ebretteville** [qooob/authentic-theme#483]
As you can see there is some encoding issues, on some pages.

![software package updates webmin 1 801 sur vps129101 ovh net debian linux 8 - mozilla firefox_002](https://cloud.githubusercontent.com/assets/3687099/15822455/2621252a-2bf6-11e6-995d-70fd1385783a.png)

**Comment by qooob** [comment]
Hi,

This is encoding issue. Please read main page, Troubleshoot section.
