### ISSUE TITLE
Theme: Usermin menu out of place

### ISSUE THREAD

**Issue by Stinkykiller** [qooob/authentic-theme#485]
Centos 7 on VPS

When i use Authentic theme in Usermin both menus, top and bottom, are positioned at the top and in line:

http://i.imgur.com/xeh2hqy.jpg

**Comment by qooob** [comment]
How does it look in old theme? Could you make video-screencast please?

**Comment by qooob** [comment]
You mean something doesn't work or it looks not that nice: rows stuck together and some buttons are too close to each other?

**Comment by Stinkykiller** [comment]
1. Old theme works great, both menus are on their appropriate places.
2. I wont do any additional video or picture aside one i already linked in my first message as i have some confidential emails and dont want to risk.
3. You should see from the picture that two menus, top and bottom, are glued together on the position reserved for the top menu. Situation doesnt change if there are emails or is empty.
4. Tested with FF 47.0, IE 11 and Opera 37.0. Forgot to update Opera to 38.0 but i'm sure it will not change anything.

Hope this helps.

**Comment by qooob** [comment]
AHHH! Ok. I see why it's happening now. I will fix it in 18.01.
