### ISSUE TITLE
Donations: Bitcoin QR code contains email address

### ISSUE THREAD

**Issue by chriswheeler** [qooob/authentic-theme#486]
The QR code for your Bitcoin donations is encoded with your email address, rather than a bitcoin address.

**Comment by qooob** [comment]
I thought it's violating the Bitcoin policy to reuse addresses?

Can't you send it using email? I just updated it a minute ago, please re-scan :laughing: 

So, what do I do? Leave the email address or Bitcoin?

**Comment by qooob** [comment]
https://en.bitcoin.it/wiki/Address_reuse

**Comment by chriswheeler** [comment]
Yes, many people would argue you should not be re-using addresses. For small donations I don't really see the issue. 

The technically correct way to do it would be to set-up a HD wallet which would generate a new address on request for each new payment.

Unfortunately I can't just email over some Bitcoin - they need to be sent to a bitcoin address...

**Comment by qooob** [comment]
Alright. I will re-encode it in few minutes.

**Comment by qooob** [comment]
Updated, thanks.

**Comment by qooob** [comment]
Nobody could use my email for sending Bitcoins or it depends on the provider?

**Comment by chriswheeler** [comment]
Almost there! I can see from the message you have encoded the address you are using is 1AUpmkNSYfKpAUcs5Rz7pPvguRmZU5nPvP - and I've sent you a donation to that address.

What you really want to encode into the QRCode is simply 'bitcoin:1AUpmkNSYfKpAUcs5Rz7pPvguRmZU5nPvP' and also link it as a<href="bitcoin:1AUpmkNSYfKpAUcs5Rz7pPvguRmZU5nPvP"><img src="qrcodeimage.png"></a>

If you do that, anyone who scans the qr code with a mobile bitcoin wallet, or click the link on a mobile or desktop PC with a wallet installed will be able to send you a donation. It is not possible for anyone to send bitcoin to an email address (without the use of a third party provider - which kinda defeats the point of bitcoin!).

You can get a qr code from somewhere like http://numberfacts.com/1AUpmkNSYfKpAUcs5Rz7pPvguRmZU5nPvP

You can view the donations you have received on a 'block explorer' website such as https://tradeblock.com/bitcoin/address/1AUpmkNSYfKpAUcs5Rz7pPvguRmZU5nPvP

It will show as 'unconfirmed' until a 'block' has been mined containing the transaction, but after that you can send it on to someone else, or another address you own.

If you are new to bitcoin, the key thing to remember is if you lose the private keys to your wallet then you will never be able to access your bitcoins, and if someone else gets hold of the private keys to your wallet they will be able to take your bitcoins from you. So make sure you have a backup somewhere safe :)

**Comment by qooob** [comment]
Thank you for your donation.

In case I use a provider, than I shouldn't worry about saving my account data?

Will my provider let me use the same Bitcoin address again? It seems that new address is regenerated again (for my wallet default).

I will try to use a link in few moments and ask you to verify it (if it's done correctly).

Yes, I'm new to Bitcoins.

**Comment by qooob** [comment]
Alright, I've updated the QR code.

**Comment by chriswheeler** [comment]
Yes, that looks great. If you are using a 'web wallet' from someone like Coinbase or Circle then you don't need to worry about backing up your wallet so long as you trust the service you are using. However you are of course at the mercy of the third party. If they get hacked, or go bust, or the owner decides to run off with your cash you have little recourse.

**Comment by qooob** [comment]
Understood. Thanks!
