### ISSUE TITLE
Theme: Popup selector for directories is broken

### ISSUE THREAD

**Issue by bgtron** [qooob/authentic-theme#487]
After updating from v17.84 to v18.00, I have a problem where the home directory selector pop up windows has a bug.  Here's where I see the problem: 

Navigate to "System">"Users and Groups".  Select "Create a new user".  At the far right side of the "Home Directory" row, click on the folder selector button.  That will open a new window that will allow you to walk the directory and select a home directory.  After upgrading, when clicking on a folder, a new button will show up next to the "OK" button with the text being the path of the folder I just clicked on.  The path is supposed to be populating in the text field to the right of the "OK" button.  Clicking the new button does nothing, and clicking "OK" selects the default "/" instead of the path in the new button.

I've had to revert back to 1.791 until this can be resolved.  I've also attached 3 screenshots to show the before and after upgrade behavior.

-------------------------------
![version 17 84](https://cloud.githubusercontent.com/assets/19859144/15968355/d155fd36-2ee8-11e6-9e78-006abeadaf94.png)
Version 17.84

-------------------------------
![version 18 00 initial window](https://cloud.githubusercontent.com/assets/19859144/15968354/d155ca82-2ee8-11e6-81db-b6815167ba0c.png)
Version 18.00 Initial window

-------------------------------
![version 18 00 after selecting a folder](https://cloud.githubusercontent.com/assets/19859144/15968353/d153e12c-2ee8-11e6-8db7-8eafce564b87.png)
Version 18.00 after selecting a folder

**Comment by qooob** [comment]
Alright, this feature is next in line to be transformed into beautiful modal popup.

Meanwhile, I have fixed your bug. Please just do `Force Upgrade`. Afterwards - clear cache - it will work.
