### ISSUE TITLE
File Manager: Remember all options across sessions

### ISSUE THREAD

**Issue by XhmikosR** [qooob/authentic-theme#488]
Currently the options "Hide actions column" and "Restore previously used tabs on first load" are not saved across sessions.

Using Webmin 1.801 with Authentic theme v18.02.

Thanks!

**Comment by qooob** [comment]
Yes, meanwhile it's not saved on the server. I will make it possible in the future.

**Comment by qooob** [comment]
Enhancements will be done in 18.30. Please be patience.

**Comment by qooob** [comment]
It's enrolled in 18.30. 

It will be able to keep all of the injected config options on the server side and it's user based as well.

**Comment by XhmikosR** [comment]
Thanks, I'll test it when it's out!
