### ISSUE TITLE
Virtualmin: Width of dropdown for domain select

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#489]
Увеличил размер панели навигации, но названия доменов по прежнему не отображаются.
Сделать подбор длины строки по ширине блока и добавить title для элементов списка с полным названием домена (возможно стилизованный data-original-title только с увеличеной задержкой, чтобы не всплывал без надобности)

![a2x3v7ntyj3lzm](https://cloud.githubusercontent.com/assets/14110152/16045217/30ddb040-3250-11e6-8730-5f38fa7558ed.jpg)

**Comment by qooob** [comment]
Здравствуйте,

Я не понял. Вы увеличили размер левой части. А размер селекта не изменился?

**Comment by Romich777** [comment]
Размер селекта изменился, но названия доменов по прежнему отображаются сокращенно. Красным отмечено пустое пространство в селекте.
Ожидал, что домен будет отображаться полностью, если панель будет достаточной ширины. Но длина строки не изменилась. Она такая же как и в списке серверов: http://joxi.net/brRlvdxuQqPxB2 (в синем блоке системные пользователи отображаются без сокращения)

**Comment by qooob** [comment]
Понял. Это не правильно. Исправим.

**Comment by qooob** [comment]
Привет,

Оказывается в настройка Virtualmin у нас уже есть возможность регулировать эту опцию. По умолчанию длинна строки домена равна 20 символам. Вы можете поставить 40, например, чтобы получить желаемый результат.

> Virtualmin Configuration->User interface settings->Maximum domain name length to display: 20
