### ISSUE TITLE
File Manager: Bookmarks issue with virtual users

### ISSUE THREAD

**Issue by zweckh** [qooob/authentic-theme#490]
I'm using webmin 1.801 with authentic theme 17.84
My webmin users have no corresponding system user.
When they use filemin for ex. the Webmin user demo has set in acl work_as_user=www-data.
In the home dir of www-data .filemin/.bookmarks is set to /var/www

The problem is that the bookmark is not displayed. I cornered the problem to line 13 in
authentic-theme/extensions/file-manager/bookmark.cgi
When i changed it to
@remote_user_info || switch_to_remote_user();
the bookmark displays.

Looks like the remote_user_info is already set in initialization of file-manager-lib.pm in the function get_paths.

**Comment by qooob** [comment]
Hi,

First of all update to the latest 18.02.

I have tested it with virtual users and it was fine.

**Comment by andreychek** [comment]
Thanks for the report zweckh!

I did some testing, and found that in the case of a virtual user (that is, I added a Webmin user, with no associated system user), it doesn't appear that bookmarks are being saved.

They work for the current session. But if the file manager is reloaded, they are lost.  That occurred with and without the fix provided by zweckh.

Now, as I re-read the initial post, I see that in the case that's been described, the option "work_as_user=www-data" had been set, which is something I didn't do. That might cause the results to be different, as the data may be stored in www-data's home directory.  I'll do some additional testing with that setting.

**Comment by zweckh** [comment]
You have to apply the patch of https://sourceforge.net/p/webadmin/bugs/4773/# too.
https://github.com/webmin/webmin/commit/8d6124321f2eccace52add5cb29dad8feb5b5a66

It fixed for me the bug in writing ~/.filemin/bookmarks

**Comment by andreychek** [comment]
Thanks for the link!

Just to clarify, you're saying that the patch Jamie provided in your link, along with the one you shared above -- both patches would be needed to resolve this issue (or, perhaps, Jamie's patch resolves a slightly different issue)?

**Comment by zweckh** [comment]
Jamie's patch solves the problem reading the bookmarks in ~/.filemin/.bookmarks
in my setup.
Mine fixed writing the file in authentic theme for me.
There is still an issue writing the file in "Grey Framed Theme"

**Comment by andreychek** [comment]
Hmm, one of two things is occurring.

Either I'm not understanding what the problem is, or I'm not able to reproduce it :-)

After applying Jamie's patch, that causes bookmarks for virtual users to save/load properly, bookmarks appear to be working correctly for me.

Can you describe what's happening when they don't work in your case, or perhaps even upload a screenshot of what you're seeing?

**Comment by zweckh** [comment]
to reproduce the problem on a newly install webmin 1.801 (Ubuntu 12.04.4) I took these steps:
a) apply Jamie's patch to filemin/filemin-lib.pl (restart webmin if needed)
b) create a webmin user "bugtest" and give him access to change-user  and filemin with "Allow access to directory" /var/www and "Access files as Unix user" www-data
c) switch to this user and change Theme to "authentic theme" (Lang = EN.UTF8)
d) change to "File Manager" and bookmark the current dir (or any other). The bookmark is displayed.
e) check in the filesystem ~www-data/.filemin/.bookmarks (it is not created)
f) reload the page. The bookmark is gone.
g) apply my change in authentic-theme/extensions/file-manager/bookmark.cgi (restart webmin if needed)
h) redo d) and e) The file .bookmarks is created and its content is / (or the dir you bookmarked)
i) reload the page. The bookmark is still there

I hope this helps

**Comment by qooob** [comment]
You mentioned:

> when I substitute switch_to_remote_user(); with &get_paths(); in filemin/bookmark.cgi line 8

Is this true for Authentic as well? Because, when I was testing it for _wheel_ users (non-root user, with admin rights, created by system, not just Webmin), `get_paths();` **was not** getting user home directory correctly and pointed to _root_ all the time.

This is why I proposed such patch to `bookmarks.cgi`.

**Comment by zweckh** [comment]
In the Authentic extension for bookmark.cgi "remote_user_info" is already set (as far as I can see). So switch_to_remote_user() should not be called at all when my change is applied. Otherwise the behaviour is as it has been before.
Maybe there are side effects with get_path(), I could not see, but it works for my configuration. I think, there is still a problem with system users with no home or users with no write access in their home. I suggested Jamie to save the filemin setting somewhere else on webmin user basis for ex. /var/webmin/filemin/<webminuser>/ that could solve the problem entirely. That is no minor change, when you want to keep current setting valid.

**Comment by qooob** [comment]
I can see that this is not theme bug, right?

**Comment by zweckh** [comment]
the original patch is for authentic-theme/extensions/file-manager/bookmark.cgi which is part of the theme. Jamie fixed/closed the part in filemin/bookmark.cgi which is referred to in the second paragraph of my last post.

**Comment by qooob** [comment]
So, you're saying that I need to do the same for the theme?

I changed that, as it didn't work with wheel users?

Or after applying [this](https://github.com/webmin/webmin/commit/8d6124321f2eccace52add5cb29dad8feb5b5a66#diff-31dad6811c7725a7e5b26c79fced76bc):

```
 -   local @remote_user_info = getpwnam($remote_user);
 -   local $uid = @remote_user_info[2];
```

things will work with `get_paths();`, right?

**Comment by zweckh** [comment]
Jamies patch solved my issue with bookmarks in authentic theme when I applied
@remote_user_info || switch_to_remote_user();
in line 13 of authentic-theme/extensions/file-manager/bookmark.cgi

The get_paths() solved my issue in "grey framed" theme which uses filemin/bookmark.cgi

In sub get_paths, among others, the remote_user_info is set global and should not have to be set again.

I don't know the problem with wheel users

**Comment by qooob** [comment]
Alright, I have repacked the theme and with Jamie's patch it will work fine now.

Re-download the theme version 18.03 and re-install it manually.
