### ISSUE TITLE
Theme: Updates does not work?

### ISSUE THREAD

**Issue by netizenuk** [qooob/authentic-theme#491]
Hi all,

I have two servers with virtualmin GPL and the authentic-theme.
Both are set to notify me if updates are available.
One of them works OK (Centos 6) but the other is stuck on version 18.00. It will not notify me for updates of the theme. It will also NOT update itself when I press "Force update". It shows no errors at all and it only brings me to the main virtualmin page.
Very strange.
Is there a log file that can possible reveal more information?

Thank you

**Comment by grimvi** [comment]
I am experiencing this same issue (failure to update past 18.00) on a Debian 7 server with the latest Webmin installed. Notifications are enabled, and I received a notice to update to 18.02 in my notification sidebar, however every attempt fails to find any updates. Force checking, force updating, etc. to get past version 18.00 turn up nothing. 

I'm adding this here since it's the same situation, different OS, can open a new issue if deemed necessary.

Operating system 	Debian Linux 7
Webmin version 	1.801
Virtualmin version 	5.03
Theme version 	Authentic Theme 18.00

As above, I can provide any logs as required.

**Comment by netizenuk** [comment]
Update:

My situation was a bit different than that of grimvi. I was not getting any notification that an update to the theme is available.
I say "was" because by mistake I left the window (default main screen of virtualmin) for several hours and when I returned to it I could see the new notification "bell" with 1 new message. That was about the new theme update (18.02) so I updated it without problems. I say "without problems" as I did not get any error messages on screen and because I see now the 18.02 version running. I don't know if this is actually the case however.
Hope this helps.

**Comment by qooob** [comment]
Hi,

1. In case you don't see notifications in Notification Panel or on System Information page, it's because of disabled theme's notification updates;
2. In case you can't force upgrade - check your Firewall not blocking connection (443)
3. Check that dependencies are installed: https://github.com/qooob/authentic-theme#troubleshoot

**Comment by grimvi** [comment]
Thanks for the prompt response. 

I've checked everything per your instructions and the troubleshoot steps - dependencies, firewall blocks, etc. - everything is solid and in place, no blocks are occurring. 

I think this may just be a fluke as I too like to leave Webmin open in different browsers - however, it still has not prompted to update past 18.00, even though I received the associated notification on my work PC. I've forced theme updates, even restarted Webmin - no go.

Anything else I can provide, please let me know! Thanks again for your time and effort.

**Comment by qooob** [comment]
Do it manually!?

**Comment by grimvi** [comment]
Yes, manually works without any issues as expected.

**Comment by qooob** [comment]
I think it should be working for next 18.02->18.xx.

Other than that I don't see how this could be the theme issue. I remember something familiar was happening but only because Webmin didn't want to download the theme and just skipped download step, as a result leaving it not-updated.

**Comment by qooob** [comment]
This is Webmin 1.800+ bug. Jamie is notified. It will be fixed!

**Comment by qooob** [comment]
Here is Webmin fix for that:

https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139

**Comment by cynetix** [comment]
qooob,

Maybe we are missing something obvious, but on all our installs the theme update options don't appear to be working. We have manually updated one (via deleting the old theme and then uploading a new one), but the rest are stuck on 17.* and we don't have the option to update.

This is what we see on the updated one:
![1 8 04](https://cloud.githubusercontent.com/assets/20661756/17139965/85e744e8-533e-11e6-8c88-d4c0a7c6be58.PNG)

And this for the others:
![1 7 84](https://cloud.githubusercontent.com/assets/20661756/17139972/8d220cca-533e-11e6-89cb-35fe0e3c1b8e.PNG)

It was our understanding that there should be a an update, changelog, donate (etc) buttons next to this text, is this still the case?

For your information all our Webmin's are on 1.801.

Thank you.

**Comment by qooob** [comment]
https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139

**Comment by cynetix** [comment]
Thanks Qooob, we will check it out.

**Comment by cynetix** [comment]
Sadly that didn't work, still not seeing the buttons.

**Comment by qooob** [comment]
After you edited Webmin files, you need to restart _Webmin_.

**Comment by cynetix** [comment]
Yeah we did that, we even restarted the whole box just to make sure.

**Comment by qooob** [comment]
You edited the file that is in the commit?

Did you check in theme settings if checking for updates is Enabled at all (the the very bottom of settings page?)

**Comment by cynetix** [comment]
Hi Qooob,

The file we changed was here:  /user/share/webmin

Is that the correct file because it was the only one we could find that matched the line change required?

We checked the setting, cleared the cache and forced a refresh. We also restarted the box and cleared the browser cache.

**Comment by qooob** [comment]
Yes, on Debian systems it's `/usr/share/webmin`, on RHEL it's `/usr/libexec/webmin`.

It's `web-lib-funcs.pl` and the new line should be `$line =~ /^(\S+):\s*(.*)$/ || last;`.

After I made the change things worked. Please post your comment [here](https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139), let Jamie answer this.

**Comment by qooob** [comment]
Make a ref to this issue.

**Comment by cynetix** [comment]
Ok Qooob, done.

**Comment by netizenuk** [comment]
Hi there.
I have made those changes and the update now works as expected.

Although not directly a problem of the theme I am now encountering a separate problem.
Please have a look here:
https://www.virtualmin.com/node/41542

I'd appreciate your comment/suggestion. Thank you.
PS: It's not a firewall issue.
