### ISSUE TITLE
Theme: Add random password generator button

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#492]
It was usefull to have random password generator button near to password field when you create or modify users.
Might it be implemented?

Maybe some small pop-up window fith few checkboxes 
![pass](https://cloud.githubusercontent.com/assets/14110152/16093640/590f06e0-3345-11e6-93e6-a2eb2fd7ce94.PNG)

**Comment by qooob** [comment]
Yes.

**Comment by qooob** [comment]
I will add to the next release.

Thanks.

**Comment by qooob** [comment]
It will be added in 18.03.

Example:

![password_generation](https://cloud.githubusercontent.com/assets/4426533/16171625/886899ba-3584-11e6-9544-0dc0b701a0e8.png)

**Comment by qooob** [comment]
Please upgrade to 18.03.

How do you like the implementation of new feature? Convenient to use?
