### ISSUE TITLE
Theme: Copying of a string from the logs loses the first character

### ISSUE THREAD

**Issue by pacquo** [qooob/authentic-theme#493]
Often, for verification purposes, one needs  to copy something from the system logs, for example an IP address.
When Webmin uses "Authentic", the copied value "loses" always the first character.

For example: when copying _123.456.789.000_,  the pasted value is _23.456.789.000_.

Issue found using Firefox 47.0 and Chrome 51.0, both with Ubuntu 12.04 and Windows 10.

**Comment by qooob** [comment]
Hi,

Interesting but I can't reproduce it. I went to System Logs, click view on one of the log files, selected the string and copied it. All is fine.

What theme version are you using? Did you try disabling extensions or running in incognito mode? Did you restart Webmin after applying theme update?

**Comment by pacquo** [comment]
Hello,
I'm using the version 18.00 of Authentic, on Webmin 1.801, installed on Ubuntu 14.04.4 (LTS); the browser encoding is set to Unicode.
I've tried also after disabling all the extensions, as well after restarting Webmin, to no avail.
This doesn't happen using the default themes of Webmin; strange problem indeed.

**Comment by qooob** [comment]
Yes, please upgrade to version 18.02 it fixes some CodeMirror issues.

**Comment by pacquo** [comment]
18.02 fixes this issue. I am relieved...thank you for your help.

**Comment by qooob** [comment]
You're welcome!
