### ISSUE TITLE
File Manager: add custom javascript

### ISSUE THREAD

**Issue by zweckh** [qooob/authentic-theme#494]
I added in line 134 of authentic-init.pm a small patch for my personal use
        if (   &get_module_name() eq 'filemin' )
        {
            print '<script src="/js/filemin_extended.js" type="text/javascript"></script>' . "\n";
        }
in the js-file I added some shortcut functions in the "Tools" menu (calling webmin custom scripts).

It would be nice to have an "official" way to add custom javascript to authentic theme, that survives future updates.

**Comment by qooob** [comment]
Theme already has such functionality. Go to theme settings, at the bottom of the page you will find `Extensions` button. Or type `extensions` in search to shortcut there.
