### ISSUE TITLE
webprefix missing in links

### ISSUE THREAD

**Issue by zweckh** [qooob/authentic-theme#495]
in authentic-lib.pm (1.802) line 2396 and line 2398 $gconfig{'webprefix'} is missing in the "a" tag
should be
a class="btn btn-default" id="edit_styles" href="'. $gconfig{'webprefix'}.'/settings-editor_read.cgi">
or
a class="btn btn-default" id="edit_logos" href="'. $gconfig{'webprefix'}.'/settings-upload.cgi">

The funktion print_category_link or its use in line 722+ seems to have the same issue

**Comment by qooob** [comment]
This is true. Added to the distro for the future releases. Thanks!!

**Comment by zweckh** [comment]
in filemin the link help.cgi is missing the webprefix too.

**Comment by qooob** [comment]
Can you please post to the latest issue you opened, so I will not forget.

**Comment by qooob** [comment]
Please upgrade to 18.03, it should fix your issues.
