### ISSUE TITLE
Theme: Missing `webprefix` declarations

### ISSUE THREAD

**Issue by zweckh** [qooob/authentic-theme#496]
I use a webprefix with the authentic theme. When I tried to add a theme extension the "save" button did not work. "save and close" was ok.
The ajax behind the "save" calls (webprefix)/webmin/settings-editor_write.cgi (returns 404)
"save and close" calls (webprefix)/settings-editor_write.cgi (returns 302)

**Comment by qooob** [comment]
I got it. I will fix it upon next release.

What is the main reason why you're using `webprefix`?

**Comment by qooob** [comment]
is missing the webprefix too in filemin the link help.cgi - https://github.com/qooob/authentic-theme/issues/495#issuecomment-226856654

**Comment by qooob** [comment]
Will be fixed in 18.03

**Comment by qooob** [comment]
Please upgrade to 18.03, it should fix your issues.

**Comment by zweckh** [comment]
>What is the main reason why you're using webprefix?
I'm using webmin with webprefix behind an apache reverse proxy. The main reason for this setting is the better/easier support for SSL/TLS in apache than in perl (at least with my experience) plus I can use more admin tools (phpMyAdmin e.a.) with the same domain name.

**Comment by qooob** [comment]
I see, ok!

**Comment by zweckh** [comment]
just upgraded to 18.03, but the problems still exist.
my changes:
authentic-theme/settings-editor_read.cgi line 53
&ui_print_footer( "webmin/edit_themes.cgi", $text{'right_return_theme_options'} );
authentic-theme/settings-editor_write.cgi line 21
&redirect("webmin/edit_themes.cgi?path=lost+found");

ui_print_footer() and redirect() already set the webprefix, so the link/redirect looks like /(webprefix)/(webprefix)/webmin/...

help.cgi in filemin does not function either.

**Comment by qooob** [comment]
Alright, thanks, pal for your fixes. I have added theme to repacked version of 18.03. Please download manually and install via upload. 

The reason why help button in FM didn't work is the stuck cache. I have made a fix to reset cache. If it doesn't happen, please do it manually in your browser.

I truly can't work more on the theme now but what I'm just doing (quickly repacking).

Tell me how did it go.

**Comment by zweckh** [comment]
I really appreciate your theme, and the work you do. Sorry to be a nuisance, but the change in  settings-editor_write.cgi is missing.

index 6099104..ea62be7 100755
--- a/settings-editor_write.cgi
+++ b/settings-editor_write.cgi
@@ -18,4 +18,4 @@ if ( usermin_available() ) {
     unlink_file($_file);
     write_file_contents( $_file, $in{'data'} );
 }
-&redirect($gconfig{'webprefix'} . "/webmin/edit_themes.cgi?path=lost+found");
+&redirect("webmin/edit_themes.cgi?path=lost+found");

**Comment by qooob** [comment]
Oh, right, forgot about this part.

Re-install please. Good?

**Comment by zweckh** [comment]
fine, thanx.

**Comment by qooob** [comment]
You're welcome!
