### ISSUE TITLE
Theme: Make config headers collapsible

### ISSUE THREAD

**Issue by Stinkykiller** [qooob/authentic-theme#499]
To make it clear, this is how it looks now:
http://i.imgur.com/8EMGpZB.jpg

and this is how i think it should look:
http://i.imgur.com/isFNyVa.jpg

Right now it looks like everything is piled up, hard to focus and find stuff. I cant remember but if similar situation is elsewhere (and i think it is in Wmin/Vmin) you should apply same solution.

**Comment by qooob** [comment]
I will try making it able to collapse, if possible in the next release.

**Comment by Stinkykiller** [comment]
It would be great to do same for other similar situations where we have long menu like it is in Usermin.

**Comment by qooob** [comment]
Please specify places where you think it should be done?

**Comment by Stinkykiller** [comment]
Sorry for late reply, i could do that but the problem is right now i have so much work i can not wait to get away from my desk. I will try to find some free time and see if same/similar situation can be found elsewhere. But if anyone else see this conversation free to jump in and check Wmin/Vmin for similar cases like the one in Usermin.

**Comment by qooob** [comment]
No rush, alright!

**Comment by qooob** [comment]
Hi,

I think making it collpaseable is overload and has no particular value.

However, you can control the `color` and `background-color` with using _theme CSS extensions_ by doing something like that:

```CSS
.col_header b {
	background-color: lightBlue !important;
	color: #fff;
}
```
