### ISSUE TITLE
Theme: Chrome throws uncaught security error in console

### ISSUE THREAD

**Issue by tommo27** [qooob/authentic-theme#501]
Have been experiencing this one for a few months.  Sometimes I will logon and it will work fine with no issues then out of nowhere, I'll get the following two errors in the console with the script broken graphic.  Issue is happening in Chrome, have tested with Firefox and Edge and don't seem to have an issue but testing was not complete so I cannot confirm.

```
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://www.mywebsite.co.uk:10000" from accessing a frame with origin "null".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "data". Protocols must match.
contents @ package.min.js?1782:2map @ package.min.js?1782:2n.fn.(anonymous function) @ package.min.js?1782:2(anonymous function) @ init.min.js?1782:6dispatch @ package.min.js?1782:2r.handle @ package.min.js?1782:2
package.min.js?1782:2

```

and 

```
GET https://www.mywebsite.co.uk:10000/virtual-server/list_users.cgi?dom=14655856826454 net::ERR_INSECURE_RESPONSEattr @ package.min.js?1782:2K @ package.min.js?1782:2attr @ package.min.js?1782:2(anonymous function) @ authentic.min.js?1782:6dispatch @ package.min.js?1782:2r.handle @ package.min.js?1782:2
package.min.js?1782:2
```
_(This error changes depending on the action / page that is being attempted)_

Only seem to get the issue when using Authentic theme.  When it starts to happen, I will encounter this between every action / page load and changes applied won't get saved.  If I close down chrome completely then open up, it will behave for a period of time on most occasions although this is a pain with do many tabs open :)

**Comment by qooob** [comment]
Hi,

First of all - update the theme to the latest 18.03.

This error usually happens when your run `https` connection and trying to access pages/links with `http`.

How can I reproduce it? I don't remember having it? Which module does it happen? Do you run `https` connection?

**Comment by qooob** [comment]
:up:

**Comment by tommo27** [comment]
Apologies for the delay in replying, I have been away.

Theme is kept up-to-date at all times although I did check for a newer version.  I can therefore confirm this happens with 18.03.  The issue does not happen at all when using Firefox, Edge or IE 12.

Connection is HTTPS as virtualmin requires this and have copied SSL cert to webmin providing a trusted connection in the browser.

Happens on all modules, when attempting to open any other option (either webmin or virtualmin) the page will often not load.

I am just reinstalling the server (for an unrelated reason) so once I have it up and running I will record a video showing the problem.

**Comment by qooob** [comment]
First, try clearing browser's cache and reload Webmin. Second, try running your Webmin incognito tab as some Chrome's extensions might be causing it.

**Comment by qooob** [comment]
What is up?

**Comment by qooob** [comment]
http://stackoverflow.com/a/31803039/1455661
