### ISSUE TITLE
DHCP: Failed to start daemon - job is already running

### ISSUE THREAD

**Issue by captsmile** [qooob/authentic-theme#502]
Button "start dhcp" always write "Start Server"
On pressed write: 
"Failed to start dhcpd :
start: Job is already running: isc-dhcp-server"

**Comment by qooob** [comment]
What do you get in Gray Theme?

**Comment by qooob** [comment]
Could you please tell me what do you get in Gray Theme?

**Comment by captsmile** [comment]
I am sorry for such a long answer. In Grey theme similar mistake. it's not
your bug ;)

вс, 3 июл. 2016 г. в 20:04, Ilia Rostovtsev <notifications@github.com>:
