### ISSUE TITLE
File Manager: Window width got smaller

### ISSUE THREAD

**Issue by kreationnext** [qooob/authentic-theme#503]
Hi,

Hope you are well. A small talk with you after a long time.
After updating to the latest version the window size of file manager got shrunk.

![file-manager](https://cloud.githubusercontent.com/assets/16913501/16581205/e8f2b3e4-42c5-11e6-8c12-acfb6b536be9.jpg)

**Comment by kreationnext** [comment]
Also please take a look at the mail scanner heading
![mailscanner](https://cloud.githubusercontent.com/assets/16913501/16581481/4d1c8920-42c7-11e6-8b10-0249e4e5c86f.jpg)

**Comment by qooob** [comment]
Hi,

About the File Manager window - well I was trying to make sure that long names are fitting properly. Yes, what you experiencing is normal, when you got long names being displayed. What is your screen resolution?

About the MailScanner - could you downgrade to the version of the theme when it worked? There might be some changes on Webmin side, maybe?

**Comment by qooob** [comment]
I would also recommend disabling Action column, especially when you have insufficiency of the screen-width.

**Comment by kreationnext** [comment]
my screen resolution is 1366x768.

Also I like the action column so  I don't like the idea of disabling it. I
am more a left click guy than a right-click. :)

Well the header on MailScanner is not causing any problem to me though. But
I thought you should know

**Comment by qooob** [comment]
MailScanner: It might theme bug or module's bug. I'd rather know. Ok, I will test it when I'm preparing another release.

File Manager: Sometimes, to reload only right frame (by clicking reload button on navigation) or right-click and reloading current frame. DataTables got stuck sometimes.

**Comment by kreationnext** [comment]
also the small div size is only an issue with the file manager. other modules work fine.

**Comment by qooob** [comment]
> also the small div size is only an issue

Not sure what you mean.

**Comment by kreationnext** [comment]
the narrow div  [ that is not adjusting with the full width of the frame ] is only happening with the file manager module.
If you compare the width of "file manager" and "Mail Scanner" images I sent you earlier in this post, you can see that mail scanner module has adjusted itself and utilized the full width but the file manager module failed to do so.

**Comment by kreationnext** [comment]
As for the mail scanner issue: I switched to "Gray Framed Theme" and "Finally Theme" none of them has this issue with the HEADING text.

**Comment by qooob** [comment]
Alright, I got it. Thanks for reporting.

Will fix it in the next release.

**Comment by kreationnext** [comment]
glad to help

**Comment by qooob** [comment]
Ohhh, you helped me to fix global bug that cause `'floating' %text`. Thanks.

It will be fixed in 18.04!!

**Comment by qooob** [comment]
18.04 is out, please upgrade! :wink:

**Comment by kreationnext** [comment]
Its not showing any option to upgrade in Webmin

Its already set in the theme options


*Check for Authentic Theme updates [YES]*


*Also tried with Force Update*

*but didn't work*

**Comment by qooob** [comment]
Please read post #505 - there is an issue in Webmin. Download the theme to your computer and install using upload.

**Comment by kreationnext** [comment]
But the width issue of file manager you said was fixed? but its not!

Although I was able to update the theme. thanks for the info!

**Comment by qooob** [comment]
Like I mentioned before, it's intended (at least so far) to have such behaviour for long files/directories names. When you list with not that long names, things will display normal.

**Comment by kreationnext** [comment]
I think you got it wrong. I am not talking about file names.
[https://drive.google.com/file/d/0B1yUtDYgrFZwbFZaNVFqS0wyOFU/view?usp=sharing](https://drive.google.com/file/d/0B1yUtDYgrFZwbFZaNVFqS0wyOFU/view?usp=sharing)

Take a look at the link.
Earlier it used to occupy the entire space but now its(file manager) fixed on the size. Its not responding to the width of the window.

And about the 'floating text' issue, Its all what you did and all credit goes to you. I should be thanking and not you.

**Comment by qooob** [comment]
Oh, man! I didn't understand what you meant. Ok, I have just re-built and re-uploaded the theme with this being fixed. I don't remember why I changed container's size from `lg` to `xs`, that was causing this issue.

I fixed on other small bug.

Just go and re-download the theme and upgrade manually once again. You will need to clear browser's cache to make it work. I hope it will what you wanted.

**Comment by kreationnext** [comment]
Thanks man! you are great!

**Comment by kreationnext** [comment]
you got another star. only 25 more to go.

**Comment by qooob** [comment]
:) Great! What is gonna happen after 500 stars? :D
