### ISSUE TITLE
Not an issue just an observation

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#504]
Hi 
if the google chrome extension Ubuntu 10.10 (unified font style) v1.0 is enabled no font awesome characters are rendered they just display as boxes. I just thought this may be useful info which may help future issues

**Comment by qooob** [comment]
Hi, Jim!

> Ubuntu 10.10 Unified font style will work only if the font is installed in your OS. 

You would need to extract `.woff` file from CSS or [use](http://rostovtsev.ru/pub/src/authentic/authentic-18.03.ttf) `.ttf` to install it later on your system.

However, it's not recommended, as bundle will be changing all the time and will force you to update it everytime.
