### ISSUE TITLE
Theme Update fails

### ISSUE THREAD

**Issue by XhmikosR** [qooob/authentic-theme#505]
So for some time now I have observed that automatic theme update doesn't work.

So I went to Webmin Themes -> Install theme -> From ftp or http URL and tried https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz and I get

```
Downloading https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz ..
     Received 1 MB
     Received 2 MB
     Received 3 MB
     Received 4 MB
.. download complete.

: Not a valid module file : gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now 
```

If I do manually
```
wget https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz
tar -xzf ./authentic-theme-latest.wbt.gz
```
the archive is successfully extracted.

Debian 8.5, Webmin 1.801, Authentic Theme 18.02.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/491

https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139

**Comment by XhmikosR** [comment]
I see thanks. Let's hope we'll get a fix soon.

How can one update the theme manually?

**Comment by qooob** [comment]
By downloading it to your local computer and then installing it via upload.

**Comment by XhmikosR** [comment]
In which folder? I looked into /etc/webmin/ but I can't find any relevant folder.

**Comment by qooob** [comment]
Download the [theme](https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz) to your computer, then follow the guide:

[How to install the theme](https://github.com/qooob/authentic-theme#how-to-install-authentic-theme)

**Comment by XhmikosR** [comment]
Duh, thanks!
