### ISSUE TITLE
CSF navigation 

### ISSUE THREAD

**Issue by ScouseTS** [qooob/authentic-theme#506]
Hi,

Just noticed on Chrome I am unable to scroll down on CSF page within webmin with the theme activated.

Authentic Theme 17.84

If I revert the theme to default one it works fine. Tested in IE and I just get the spinning emblem and nothing appears.

Cheers

**Comment by qooob** [comment]
Upgrade the theme manually to the version 18.03.

How to upgrade the theme see this: https://github.com/qooob/authentic-theme/issues/505

**Comment by qooob** [comment]
Oh, I could accidentally reproduce no scroll issue in _Firefox_ on some pages of _ConfigServer Security and Firewall_.

Version **18.04** has just been re-uploaded and fixes the issue. Please upgrade!!
