### ISSUE TITLE
Can scroll down on CSF

### ISSUE THREAD

**Issue by amityweb** [qooob/authentic-theme#507]
I used to be able to, but lately I cant. 

If I remove overflow:hidden on the body tag, it works OK.

**Comment by qooob** [comment]
Hi,

Upgrade the theme manually to the version 18.03.

How to upgrade the theme see this: https://github.com/qooob/authentic-theme/issues/505

**Comment by qooob** [comment]
Oh, I could accidentally reproduce no scroll issue in _Firefox_ on some pages of _ConfigServer Security and Firewall_.

Version **18.04** has just been re-uploaded and fixes the issue. Please upgrade!!

**Comment by amityweb** [comment]
I use virtualmin and will wait for an automated release in there, and not manually update like mentioned before. 

In the meantime I go into inspector in Chrome, and disable "overflow: hidden" in the iframe body. It does not have any negative effects, so I am not sure why overflow is set to hidden.
