### ISSUE TITLE
Theme: Wrongly showing "X package updates are available"

### ISSUE THREAD

**Issue by oswee** [qooob/authentic-theme#508]
Showing "X package updates are available" even if there are no packages to update. Cant tell how do i got that, but this is not the first time. And i cant to clear (reset) that number. That is in dashboard.

**Comment by qooob** [comment]
What Webmin/Theme version do you have installed?

**Comment by qooob** [comment]
..and do you see update message in System Information page (Dashboard)

**Comment by oswee** [comment]
Hi,
Theme version - 17.84.
This error is located in System Information (dashboard) tab. Last bottom entry in that section.
Currently i see "4 package updates are available". After i press Refresh button (at the end of this statuss record) it reload dashboard about 30 seconds and i still see that statuss.

When i click to see available updates i got - "No packages available to be updated were found."

So i think this is coming from some kind of cache or something...

In Notification panel (right side) no updates showing.

**Comment by qooob** [comment]
Going to _System Information_ page and hitting green refresh button will/should solve it. In case it's not, try refreshing packages by hitting little blue refresh button (appears on hovering in same _System Information_ page). Restart _Webmin_ after all by running `/etc/webmin/restart`.

Most importantly, you must upgrade to _Webmin_ 1.803 (or 1.800) at least. Make sure to upgrade the theme to the latest version 18.03. It's known issue with old _Webmin_ versions. Nowadays, I haven't noticed it at all with the recent updates.
