### ISSUE TITLE
Theme: Table icons randomly change on-hover in Microsoft Edge

### ISSUE THREAD

**Issue by ccourson** [qooob/authentic-theme#509]
When I set:
  Animate table icons on focus: Yes
  Grayscale table icons and bring color on focus only: Yes
and mouse around the page, all of the icons except for the one I might be hovering over flicker and change images randomly. I'm using MS Edge.

**Comment by qooob** [comment]
Hi,

Yes, I remember Edge didn't render it properly. I will try to fix it by the next release in case it's technically possible.

Thanks for reporting.

**Comment by ccourson** [comment]
Wow! Certainly appreciate the lightning fast response. Awesome, professional theme. Thank you!

**Comment by qooob** [comment]
Thanks, you're welcome.

**Comment by qooob** [comment]
I have no idea why this is happening. :disappointed:

**Comment by RedstoneFiend** [comment]
I disabled icon animations and all is well since. Very visually appealing theme. I use Webmin a lot and this theme a very comfortable.

**Comment by qooob** [comment]
I will try fixing it but I'm not sure, that it's technically possible.

I would highly recommend using **Google Chrome** or **Mozilla Firefox** for the _best_ experience!

**Comment by lebrach** [comment]
Hello,
@qooob, same behavior on Firefox 47.x
@RedstoneFiend : How do you disabled icon animation?
Thx

_PS I love the theme very much :-)_

**Comment by qooob** [comment]
Not sure what you mean by saying that it's the same in Firefox.

Animation can be disabled in theme settings.

Please provide videoscreencast, I would like to take a look as I can't reproduce it - Firefox works perfect.

What version of the theme are you using?

**Comment by lebrach** [comment]
@qooob yes, you're right, it works well with Firefox... Actually when I stated the issue, I thought I was under Firefox (which I use by default) , but instead I was using IE... Sorry!

**Comment by RedstoneFiend** [comment]
lebrach, the settings are in my original post above. Webmin Configuration -> Webmin Themes -> Table Options section.

**Comment by qooob** [comment]
Alright, it will be fixed in 18.20.

Support for 4 different browsers is really extensively `funny` work to do.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
