### ISSUE TITLE
Theme: Fields are sorted wrong when containing miscellaneous data

### ISSUE THREAD

**Issue by taylankasap** [qooob/authentic-theme#510]
In my case the problem was with this page/column
Virtualmin -> {Any Virtual Server} -> Edit Users -> Last login

You can fix this by adding `data-sort="{timestamp}"` attribute to the <td>. I don't know Perl much & there might be other tables with date columns, so I'm not PRing myself.

**Comment by qooob** [comment]
Hi,

Does this column contain nonnumerical data? Like `none` for example?

Yes your solution would work but it should be done on Virtualmin side.

**Comment by taylankasap** [comment]
Yes actually, there is also the value `Never`.

Will you fix it via JavaScript then?

**Comment by qooob** [comment]
I could but there might be more places where it would require the change. The right way is to do it on Perl side. I would filled an issue to Webmin/Virtualmin repo. `data-sort` is something that _DataTables_ expect.

Joe, do you think we could add it _here and there_ on Perl side? There are some places where natural sorting gets broken as well. For example, when we do sorting by size and a cell in a column contains non-applicable data, like `none`, the whole thing stops working. Having _data_ attr would solve a problem. For size it could be the size in bytes, where `none` would be 0 and for _date/time_ it would be a timestamp, same with 0 for `Never`, and so on. It should work as it is, with the current version of _Authentic Theme_ and at the same time wouldn't have any impact on old themes?

**Comment by qooob** [comment]
Alright, it will be implemented on the theme side in 18.20.

Let me know other places which might need the fix as well.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
