### ISSUE TITLE
Webmin Servers Index: Couldn't edit servers

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#516]
An option to edit servers in "Webmin Servers Index" is not visible as it can be seen in attached image.
After inspection, i can see the edit link container gets visible with absolute position at top but edit icon's class name is invalid and hence no edit icon appears.
icon image as of now is `<i class="fa fa-fw fa-lg fa-pencil-square text-dark text-dark-hoverd"> </i>`
but it should be `<i class="fa fa-fw fa-lg fa-pencil-square-o text-dark text-dark-hoverd"> </i>`

please note the changes... from **fa-pencil-square** to **fa-pencil-square-o**

![untitled](https://cloud.githubusercontent.com/assets/5191867/17170416/8d82259e-5409-11e6-84ce-e0fe0d66cbaa.png)

**Comment by qooob** [comment]
Hi,

Thanks for reporting. I will release bug fix version update 18.05 as soon as possible. Thanks.

**Comment by divyeshsachan** [comment]
Thanks..   :satisfied:

**Comment by qooob** [comment]
Please upgrade to 18.05

**Comment by divyeshsachan** [comment]
Thanks a lot, It's now fixed.
