### ISSUE TITLE
Webmin Servers Index: Error while saving settings (when remotely logged in)

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#517]
Couldn't save "Web Server Options" settings in second webmin server logged on through "Webmin Server Index". "Save" button never works due to error in js.

Steps to reproduce
Navigate to any server through Webmin Server Index, on this second server -> Webmin Configuration -> Web Server Options. (Url would be like https://main_server_ip:10000/servers/link.cgi/1461240051/webmin/edit_web.cgi)
Now a error appears in console. 
```
TypeError: N is undefined
https://main_server_ip:10000/servers/link.cgi/1461240051/unauthenticated/js/jquery.datatables.min.js?1804
Line 4 , col 44834
```

**Comment by qooob** [comment]
I will take a look as soon as possible.

Thanks.

**Comment by qooob** [comment]
That is a weird bug.

It will be fixed in 18.05.

**Comment by qooob** [comment]
Please upgrade to 18.05

**Comment by divyeshsachan** [comment]
Thanks a lot, It's now fixed.
