### ISSUE TITLE
Theme: Virtualmin DNS records coloured syntax

### ISSUE THREAD

**Issue by neubreed** [qooob/authentic-theme#518]
When manually editing DNS records in Webmin -> Servers -> BIND -> Edit Records File
The syntax is highlighted in colour

Whereas in Virtualmin: Server configuration -> DNS records -> Manually Edit Records 
The syntax is mono only

How do I enable coloured syntax on the Virtualmin side?

Using 18.04

Provide the following information:
* What is your server-side OS and its version? Ubuntu 14.04
* What is your client-side OS, browser and its versions? Opera

**Comment by qooob** [comment]
Yes, I will add it to 18.05 as soon as possible.

**Comment by qooob** [comment]
Please upgrade to 18.05
