### ISSUE TITLE
MySQL/PostgreSQL: No "Add row" button for empty tables in manage databases

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#521]
Browse to any virtual server with a database, click Manage on that database.

Open an empty table (or create a new table with fields but no data).

There should be an "Add row" button after the "This table contains no data." message. In Authentic there is none. In the framed theme, it is present.

This lack prevents adding data to an empty table.

**Comment by qooob** [comment]
Hi, Joe.

Confirmed and will be fixed in 18.07

**Comment by qooob** [comment]
Fixed, please upgrade.

**Comment by qooob** [comment]
Joe, please make sure to redownload 18.07 in case you installed it moments after the first notice.

https://github.com/qooob/authentic-theme/issues/522
