### ISSUE TITLE
File Manager: Tries to open last tab of main server (when remotely logged in)

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#523]
When logged in via remote (using webmin server index), file manager tries to open last tab of main server instead of that specific server. However, this is not a serious issue, but since i use file manager of my all servers via webmin remote login, i want to bring it up into your notice.
Steps to reproduce:
1. Open File Manager and navigate to unique folder path.
2. Navigate to "Webmin Servers Index" and open another server from there (webmin remote login to another webmin server).
3. Open "File Manager" on this remotely logged in server.
Now, file manager in remote server tries to open last path of main webmin's file manager and if this path doesn't exists in remote server, it shows an error that directory not found.

I think this issue somehow related to Issue#478. You have fixed it for per user and i think you should also add a check for specific server and open last opened tab of that server.

Thanks for your precious time and effort.

**Comment by qooob** [comment]
Oh, that sounds very possible. It's the last thing I would do/redo again but I'll try.

Thanks for reporting.

**Comment by qooob** [comment]
Enhancements will be done in 18.30. Please be patience.

**Comment by qooob** [comment]
All of the `localStorage` now is tied to the  hostname for all operations. It'll work not only for File Manager tabs but for all other operations.

**Comment by divyeshsachan** [comment]
Will these changes be applied in any upcoming version ?

**Comment by qooob** [comment]
Version 18.30 will drop all of the current settings. Afterwards, it will be preserved in the browser's cache.
