### ISSUE TITLE
ConfigServer Security & Firewall: Save configuration submit doesn't work

### ISSUE THREAD

**Issue by JoaoPauloSouza** [qooob/authentic-theme#524]
[http://prntscr.com/c1xvq8](http://prntscr.com/c1xvq8)
there is some js errors in the console:
[http://prntscr.com/c1xvq8](https://s31.postimg.org/fwvfjbke3/Captura_de_tela_de_2016_08_05_09_11_31.png)

**Comment by qooob** [comment]
It will be fixed in 18.08.

Thanks for reporting!!

**Comment by qooob** [comment]
Please update to 18.08

**Comment by JoaoPauloSouza** [comment]
@qooob thanks, its working again
