### ISSUE TITLE
Theme: CSS link to the custom file

### ISSUE THREAD

**Issue by cynetix** [qooob/authentic-theme#525]
If I wish to link to the logo.png inside the etc/webmin/authentic-theme directory from styles.css in the etc/webmin/authentic-theme directory, what's the relative path?

No matter what I try I can't seem to access it.

Many thanks.

**Comment by qooob** [comment]
What are you trying to do?

Obviously you will not be able to load it from `etc` directory.

Theme automatically does it and copies the logo to the theme's directory/images.

**Comment by cynetix** [comment]
Qooob,

Yes we are just seeing that, I had assumed that was the correct directory based on the CSS file and the logo.png image. However I have located the image in the authentic-theme/images directory but I still can't link to it.

What I am trying to eventually do is add a background image to some CSS. I want to store that image with all the other images and link to it relatively so I can copy the CSS to other installs without having to change the absolute links if possible.

**Comment by cynetix** [comment]
Sorry, I should clarify what I wrote.

I CAN link to logo.png, and any other file that's there, but I can't link to any new file I place in that directory.

**Comment by qooob** [comment]
Do you only need background image?

Do you know that you could encode `background-image` _url_ with base64 and thus not use any files?

[Read more](http://www.hongkiat.com/blog/css-encoded-image/)

**Comment by qooob** [comment]
However, 18.08 will have this new feature:

* Added ability to embed custom _Perl_ scripts under `/etc/webmin/authentic-theme/scripts.pm` to be able to run arbitrary code that surives updates. The file `scripts.pm` must end with `1;` to work successfully 

In case it's not blamed with the team it will go to the next Webmin release.

**Comment by cynetix** [comment]
Hi Qooob,

I have used the base64 approach which has allowed me to do what I needed. Thank you!

**Comment by qooob** [comment]
Sure, cool, no problem, pal! ;)

**Comment by qooob** [comment]
Please update to 18.08.

**Comment by swelljoe** [comment]
Ilia, this change needs to be rolled back out, immediately. There are security issues.
