### ISSUE TITLE
speed. not good.

### ISSUE THREAD

**Issue by perler** [qooob/authentic-theme#528]
hi, because of a bug I recently had to switch back to the old virtualmin framed theme and, man, the speed difference!

with all the bling the authentic theme /feels/ speedy, but when you switch back, the speed difference is enormous. everything just loads instantly. 

I think the team should take a step back and do an optimization round.

for the record: 

server: ubuntu 14.04, 12 core, 12 GB RAM
client: windows 10, chrome, latest, i5, 16gb ram

**Comment by qooob** [comment]
We're working on the speed.

Authentic will never be the same in speed (as I see it), because it's 10 times heavier (has more dependencies).

**Comment by qooob** [comment]
..and we will try to improve..

**Comment by swelljoe** [comment]
Going to a single page app architecture will help; I spent a lot of time trying to solve that in my bootstrap theme, and was pretty close to solving the biggest problems, but Authentic is still framed, which leads to re-loading libraries on every new page. We can solve that, but it's a big project and requires a lot of code changes.

But, it will happen, eventually. We always welcome help!

**Comment by qooob** [comment]
Yes, eventually.

**Comment by Real-Gecko** [comment]
Yeaaah, frames are huuuuge mess :D :D :D

**Comment by qooob** [comment]
I will drop an _iframe_ and will load pages using background requests to prevent menu reloads.

**Comment by qooob** [comment]
However it will not make things _that_ much faster on high quality hardware.
