### ISSUE TITLE
Is it possible to add custom translations?

### ISSUE THREAD

**Issue by cynetix** [qooob/authentic-theme#529]
Hello again Qooob,

Should the authentic-theme/custom-lang override be able to access/override usermin translations?

For example, I am trying to override session_header translation which is located in the /usr/share/usermin/ulang/en file?

**Comment by qooob** [comment]
Hi,

Please have a look here [#39228](https://www.virtualmin.com/node/39228)

**Comment by cynetix** [comment]
Thanks Qooob, it took a bit of reading, but it works! Thank you.

For anyone else trying to do this and you don't want to read through the page: Go to etc/usermin and create a file called custom-lang, in that file put your variables and your translations.

Thanks again Qooob.

**Comment by qooob** [comment]
You're very welcome.
