### ISSUE TITLE
Theme: Undefined subroutine `embed_scripts()` after Webmin 1.810 update

### ISSUE THREAD

**Issue by XDevASM** [qooob/authentic-theme#532]
Hi,

After update the webmin to 1.810 and authentic theme to 18.10 i get this error wen i try to open webmail.

--------------------------------------------

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.690 Date: Wed, 10 Aug 2016 10:37:52 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Undefined subroutine &WebminCore::embed_scripts called at /usr/share/usermin/authentic-theme/authentic.pm line 223.

--------------------------------------------
Server system: Debian 7
My system: Debian 7
My browser: Firefox

Thanks

**Comment by qooob** [comment]
Hi,

This happens because `embed_scripts()` has been removed and _Webmin_ is using cached version of the `authentic.pm`

**Comment by qooob** [comment]
In case the solution above doesn't work, please restart the server.

**Comment by XDevASM** [comment]
The problem is fixed after restart the server.
Thank you qooob

**Comment by mootensai** [comment]
I restart then it's fixed, but when I enter usermin from webmin's "Login to Usermin" from "Users & Groups" module & enter one of user, it happen again. But before it happen, the css & javascript doesnt work.
Here's the screenshoot

![image](https://cloud.githubusercontent.com/assets/5844149/20527287/526f203a-b0fa-11e6-8275-609ff9a2467f.png)

**Comment by qooob** [comment]
You need to upgraded the theme for Usermin from Webmin manually.

**Comment by mootensai** [comment]
It works normally now!! Thanks!!

**Comment by qooob** [comment]
You're welcome.
