### ISSUE TITLE
File Manager:  Rendering problem with Google Chrome

### ISSUE THREAD

**Issue by rantool** [qooob/authentic-theme#533]
Thanks for the excellent work and support
I am seeing transparent areas in file manager since webmin upgrade
This is only happening with chrome and works fine with firefox

![ranerror](https://cloud.githubusercontent.com/assets/17883472/17616920/f77ca246-606e-11e6-85d4-c34addee4fa2.png)

Webmin version	1.810 
Virtualmin version	5.04

**Comment by qooob** [comment]
Hi,

I have just tested it in latest Chrome 53.0.xxxx.xx and things seem to work as expected.

The reason why this is happening is stuck cache. Open DevTools (F12) and hold refresh button (next to the address line), then select `Empty Cache and Hard Reload`.

The other problem might be outdated version of Chrome.

**Comment by rantool** [comment]
Empty Cache and Hard Reload did not fix the problem. 
Upgrading google chrome from 52.0 to 53.0 fixed the issue
Thanks a million for your help
I love the filemanager :)

**Comment by qooob** [comment]
Glad it helped.

I will continue improving it, by adding new features, like viewers/editors including command line and more. 😉

Thanks for using it.
