### ISSUE TITLE
Theme: CodeMirror and some other modules probably extraneous

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#534]
When I watch the network activity, I'm seeing tons of JS libs that aren't used on a given page being loaded. Seems like an unnecessary performance hit. The biggest of them is CodeMirror, but there are a bunch of others.

Wouldn't it be reasonable to only load CodeMirror on pages that have an editor?

**Comment by swelljoe** [comment]
I'm asking, as performance seems to have gotten worse of late. Even on a fast network, I find I'm waiting longer than I used to on page loads.

**Comment by qooob** [comment]
Hi, Joe.

I haven't changed anything in this regard recently. 

Yes, there are a lot of things loaded in _CodeMirror_. I haven't noticed any performance hits due to this issue.

However, having _CodeMirror_ loaded on demand sounds reasonable. Actually, the same way HTML editor is loaded, only on demand.

I'll see what I can do and try to enroll it on the next release.

**Comment by qooob** [comment]
You mentioned, _Extraneous_? What do you mean by that? What is to location of the files that are load and shouldn't be in you opinion?

**Comment by swelljoe** [comment]
I dunno which ones are doing what. But, there's a lot of them! We should maybe see about using a loader or merging them into a single file. I dunno what the right thing is, but performance is maybe the biggest single source of complaints about the theme at this point.

What is jqueryui being used for, for example? If it's just one or two widgets, maybe those could be merged into the authentic js and kill that dependency. Cacheability is valuable, but since we don't use a CDN for Webmin (and realistically can't), our primary goal should be to reduce number and size of JS files loaded for each page.

**Comment by qooob** [comment]
All requests are run in asynchronous way and will not provide a significant boost in case of merging dependencies. I will try do it and ship it as a single file but it will create redundancy, as both frames require the same frameworks.

I will see what I can do in terms of dropping/replacing some dependencies.

We would get an improvement (not enormous though) in case of switching to a single frame app but that will require a lot of work.

Thanks for your thoughts, Joe.

**Comment by qooob** [comment]
Hi, Joe ;)

Ok, I managed to combine styles/scripts in the bundles and avoid redundancy. It's not a single file but make things slimmer as you described above. (making much less server requests)

I could make _CodeMirror_ load on demand but it will break nice UI and at the moment I just added the whole thing at the bundle. In the future, in case I can overcome this issue, I will make it load only on demand.

However, I can't notice a difference not either on 1gbt/s connection nor on 100 mbt/s and things load in a splash in both ways.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

**Comment by qooob** [comment]
Joe, hi.

I managed to remove _CodeMirror_ from default load. It's now loading on demand. It was complicated to make UI look same nice. After some investigation, I managed to do both.

18.30 will have it optimised as well. Probably some other parts too for faster load and better user experience.

I ask you please, let me know how it feels, whenever it's out (beginning of December). I hope you will feel the difference.
