### ISSUE TITLE
Theme: Jittery icons in Microsoft Edge browser

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#535]
In MS Edge (all versions I've tested), the icons are jittery when scrolling in any page that has icons and is big enough to have a scroll bar. They bounce around, change colors, and do other weird stuff. I dunno exactly what is going on with it. Best example I can find is Webmin Configuration page; because it has a lot of icons, there's plenty of jumpiness.

Edge has smallish, but growing market share.

**Comment by qooob** [comment]
I will consider providing workaround for _Edge_ browser.

**Comment by qooob** [comment]
Joe,

I just fixed familiar issue #509 and it think this is tightly related. Expected to be fixed in 18.20.

Thanks for reporting! ;)

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

**Comment by rostovtsev** [comment]
I was _**very frustrated**_ to find out that my new physical installation of Windows 10 had jittery icons  all over the places as well, _in all browsers_, unlike virtual machine.

It's actually happened to be known issue of Font Awesome with certain scaling. 

There are fancy workarounds, and I have finally fixed it, and it looks _**good**_ now in Windows as well.

Example of how it was before and after update (screenshot taken from Firefox).

It's a huge difference. I personally don't like the way fonts are rendered in Windows at all. Linux with Gnome does it many times better, not mentioning MacOS where everything looks candy-like!

**Before/After:** 

![Screenshot_2019-11-22 (1) Dashboard — Webmin 1 932 1103 1604 (Ubuntu Linux 18 04 3)](https://user-images.githubusercontent.com/4426533/69426935-7083ad80-0d3f-11ea-9a33-dd23c235ff3a.png) ![Screenshot_2019-11-22 (1) Dashboard — Webmin 1 932 1103 1604 (Ubuntu Linux 18 04 3)(1)](https://user-images.githubusercontent.com/4426533/69426949-78435200-0d3f-11ea-8651-b256d488d773.png)
