### ISSUE TITLE
Theme: Tooltip help-popup problem on long pages

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#536]
So, popup help tooltips in Virtualmin Configuration, and other places has some weird quirks. Not sure if this behavior is new or has been around for a while, but I'm seeing an issue in both Firefox and Edge, and one extra issue in Firefox.

Problem in both browsers:

1. It doesn't always respond to clicks. Roughly half the time when I click it, it will either do nothing, or act like it is loading, but not actually show the tooltip. This seems most obvious when going from one tooltip to another; e.g. have a tooltip open, click on another item that has a tooltip available. It'll close the open tooltip, but not open the new one, requiring another click. It's also slow, but I think that's just due to network.

Problem just in Firefox (and a bigger one):

1. The further down the page the item is, the more offset the tooltip will be. So, popping up help on an option halfway down the Virtualmin Configuration page will lead to a tooltip at the very bottom of the page (even pushing the bottom of the page down to make room for it). At first I thought it just wasn't working until poking around and noticing that further up the page it is less offset and may remain visible.

I'm working on getting more complete help coverage, so I want it to work well! ;-)

**Comment by qooob** [comment]
Joe, hi!

I managed to reproduce the second problem. I will try fixing it by next release.

**Comment by qooob** [comment]
Joe,

It will be fixed and improved for the next _18.20_ release. I made it also possible to have multiple help _tooltips_ in case it's needed. The _tooltip_ containers will be toggable like ordinary desktop windows.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
