### ISSUE TITLE
Recent Webmin logins bad date format ?

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#537]
Just a small point with the date format 
![image](https://cloud.githubusercontent.com/assets/4038510/17737378/c1b4f004-6484-11e6-9595-56b92bbeb738.png)

as you can see the date is d/M/Y (sorry I have used php date format syntax)
using M, I would not expect to a '/' between the elements of the date, maybe make this configurable

an unrelated point ( I guess a webmin issue ) you will notice the same IP is logged in 3 times !

**Comment by qooob** [comment]
You can go to `Webmin->Webmin Configuration-> User Interface` and set the way you would want to display the date under Webmin in general.

By going to `Webmin->Webmin Users->Current Login Sessions` you can log out of those sessions you need by hitting the `Session ID`.
