### ISSUE TITLE
Perl execution error in usermin

### ISSUE THREAD

**Issue by amir0150** [qooob/authentic-theme#538]
Before posting an issue, please search through README.md and closed/opened issues to make sure that the answer to your questions hasn't been answered/discussed already.

Please make sure that you have latest theme (18.10) and Webmin (1.810) versions installed.

Provide the following information:
* What is your server-side OS and its version?
* What is your client-side OS, browser and its versions?
* What are the steps to reproduce the issue

**Comment by amir0150** [comment]
I am getting a Perl execution error in usermin. I am using the latest webmin 1.810 and latest theme. Server side os is centos 6.8 
And client side browser is Firefox 60 on centos 6.8
Logging in to the mail box of any user is giving the error when you scroll down below.

**Comment by qooob** [comment]
Make sure that you have latest Usermin. Afterwards update the theme manually especially for Usermin (from Webmin, Usermin Cinfiguration).

Afterwards, restart Usermin.

In case it doesn't help, provide a screenshot of what exactly doesn't work and fill required fields properly.

**Comment by amir0150** [comment]
Thank you very much for the reply qooob. I just updated the Authentic theme manually but dont know how to the theme manually for Usermin especially. Please let me know how to do that. Thanks

Rrgards,
Amir

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme#usermin

**Comment by qooob** [comment]
..or when you force upgrade from theme settings - it will upgrade both.
