### ISSUE TITLE
Theme: Taps leaking through in mobile mode

### ISSUE THREAD

**Issue by zelestcarlyone** [qooob/authentic-theme#539]
Whenever I try to navigate using the pop-out menu on a cellphone taps go right through to the element underneath. For instance, if I have opened the list of processes, open the menu and tap to go somewhere, if what is underneath is a link or a button it also receives a click.

Browser version: Chrome 52.0.2743.98 (Sony Xperia Z3)
Theme version: 18.10
Webmin version: 1.810
OS Version: Ubuntu Linux 16.04.1

Tested with the 4.3 version of the Firefox browser for Android. Works there but is mostly unusable for a whole heap of other reasons.

**Comment by qooob** [comment]
Hi,

I can't reproduce your issue on the latest Chrome. Have a look at [video screencast](https://rostovtsev.ru/pub/src/authentic/18.10/leaking_taps_issue_539.mp4).

**Comment by zelestcarlyone** [comment]
The error was there until this morning, however in the afternoon my Xperia had a system update and after that the error magically disappeared. So the issue is resolved.
