### ISSUE TITLE
ConfigServer Security & Firewall: Radios are missing in preconfigured profiles

### ISSUE THREAD

**Issue by jmcguirl** [qooob/authentic-theme#540]
1. Unable to choose Preconfigured Profiles in CSF Module.
2. Unable to have CSF excluded from the in-built rendering mechanism.

* What is your server-side OS and its version?
Module:                  ConfigServer Security & Firewall version 9.11
Operating system:  CentOS Linux 6.8
Webmin version:     1.810 
Theme version:	Authentic Theme 18.10

* What is your client-side OS, browser and its versions?
Operating system:  Windows 10 build 1607
Browser:                  Google Chrome 52.0.2743.116 m (64-bit)
 
* What are the steps to reproduce the issue
The only thing I know of that is NOT default is that using "Module category assignments", I reassigned the CSF module to "Networking" instead of the default "System" Category.

**Comment by qooob** [comment]
This is true, I missed it! I will fix it upon next release.

Thanks for reporting, pal.

P.S.  Exclusion of this module has not been supported yet. I might invent my time in it but I don't see much reason really.

**Comment by jmcguirl** [comment]
I tried to exclude as a workaround for the missing check boxes / radio
buttons.

**Comment by qooob** [comment]
It will be fixed in 18.20

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
