### ISSUE TITLE
Webmin System Stats:  CSS fix for `panorama`

### ISSUE THREAD

**Issue by luison** [qooob/authentic-theme#541]
We've fixed some viewing issues in a webmin module we've been using for years that compiles system stats: Sysstats. The "Panorama" view shows small thumbs for all active modules so you can have a general view of all the system graphics. Images were not showing correctly due to rather strict style in: authentic.min.css with a generic:

`img {max-width: 100%}
`
I imagine this might be causing conflicts in other older modules too.

In case of interest for future releases we've fixed it by adding:

`body.sysstats .graph_table a img {max-width: unset}
`
into our theme extension css file.

**Comment by qooob** [comment]
Please provide the screenshot at first and then after your fix is applied.

**Comment by luison** [comment]
Before:
![30-8-2016 18 8 11 4](https://cloud.githubusercontent.com/assets/745632/18098393/554625d8-6ee2-11e6-814c-5b248dc823a9.jpg)
After:
![30-8-2016 18 8 30 3](https://cloud.githubusercontent.com/assets/745632/18098394/57692298-6ee2-11e6-910f-ce00f5fe8965.jpg)

**Comment by qooob** [comment]
I will add this to the next version soon.

**Comment by qooob** [comment]
It will be fixed in 18.20

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
