### ISSUE TITLE
Console errors in Firefox

### ISSUE THREAD

**Issue by luison** [qooob/authentic-theme#542]
We have some slowness when running the theme particulary in Firefox.
I assume you are aware but I include some console issues that I get under Firefox 47.0.1, specially the third one could be relevant.

```
12:02:15.522 Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.1 (desconocido)
12:02:15.531 'mozHidden' y 'mozVisibilityState' están desaprobados. Use en su lugar las versiones sin prefijo 'hidden' y 'visibilityState'.1 favico.min.js:1:7642
12:02:17.626 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create1 clipboard.min.js:7:8584
```

**Comment by qooob** [comment]
Hi,

No, those are just warning messages coming from the dependencies.

There is Firefox 48 already. I would recommend you to make sure that you have multi-threading enabled in your browser. Firefox Alpha has all of it enabled by default and works much-much faster. Chromium and Chrome as well.

Chromium is the part of the Fedora repos now and can easily be installed.
