### ISSUE TITLE
Theme: Webmin API `ui_form_end` buttons not working

### ISSUE THREAD

**Issue by KramNotlimah** [qooob/authentic-theme#543]
I am writing a module for Virtualmin and I ran across an issue with the `ui_form_end` subroutine in the Webmin core API.  If you open a popup window and use the `popup_header` instead of the `ui_print_header` the buttons all come out with a `value="OK"`.  In the original Virtualmin theme with the same code they came out with the correct values.  When using the `ui_print_header` in the main windows the `ui_form_end` produces buttons fine in the original Virtualmin theme and in the Authentic Theme.  It seems it is only an issue when using the `popup_header` with Authentic.  I worked around the issue by just creating my own buttons but it would be nice to be able to use the API as advertised.

Mark

**Comment by qooob** [comment]
Hi, Mark.

I will run tests a bit later and try fixing it upon next release.

**Comment by KramNotlimah** [comment]
Thanks.  That sounds great.

Mark

**Comment by qooob** [comment]
Mark, where could I test it in VM or WM?

**Comment by qooob** [comment]
Ahh, ok, got it! It will be fixed in 18.20.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

**Comment by KramNotlimah** [comment]
Thanks!  I will get the update.

Mark
