### ISSUE TITLE
Theme: `pam_unix.so` makes the login screen blank

### ISSUE THREAD

**Issue by msp1kpj** [qooob/authentic-theme#544]
Bug report for authentic-theme 18.10 on Webmin 1.810 on CentOS 7.

When Webmin is configured NOT to use "pam_unix.so" in "/etc/pam.d/webmin" and instead uses the system's sssd configuration via "include system-auth" for all "auth/account/session" entries, the login screen is blank.

The following errors show up in the console log for both Firefox 47.0.1 and Chrome 52.0.2743.116:

-----
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
.success() postinit.min.js:6
n.Callbacks/i() jquery.min.js:2
n.Callbacks/j.fireWith() jquery.min.js:2
z() jquery.min.js:2
.send/c/<() jquery.min.js:2
.send() jquery.min.js:2
.ajax() jquery.min.js:2
<anonymous> postinit.min.js:6
1 postinit.min.js:6:3334
-----
ReferenceError: NProgress is not defined
<anonymous> parent.min.js:6
1 parent.min.js:6:7954

Webmin is using "perl-Authen-PAM-0.16-16"

**Comment by qooob** [comment]
Hi,

I will try to reproduce this issue and fix it in the near future.

Thanks for reporting.

**Comment by qooob** [comment]
Just to double-check - if you change to Gray Theme you don't see such issue? Because if you do, it's Webmin bug.

**Comment by msp1kpj** [comment]
That is correct. If we switch to the Gray theme the sign in works correctly.

**Comment by qooob** [comment]
Is there a way you could post a screenshot of how it looks like when error comes?

**Comment by msp1kpj** [comment]
I can. But all or come back with is a Grey screen. Is there something else that would help more? There are JavaScript Errors, about "NProgress is not defined"

`
jquery.min.js?1810:2 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM938:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0success @ postinit.min.js?1810:6i @ jquery.min.js?1810:2fireWith @ jquery.min.js?1810:2z @ jquery.min.js?1810:2(anonymous function) @ jquery.min.js?1810:2send @ jquery.min.js?1810:2ajax @ jquery.min.js?1810:2(anonymous function) @ postinit.min.js?1810:6
VM939:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0success @ postinit.min.js?1810:6i @ jquery.min.js?1810:2fireWith @ jquery.min.js?1810:2z @ jquery.min.js?1810:2(anonymous function) @ jquery.min.js?1810:2send @ jquery.min.js?1810:2ajax @ jquery.min.js?1810:2(anonymous function) @ postinit.min.js?1810:6
parent.min.js?1810:6 Welcome to Authentic Theme 18.10 https://github.com/qooob/authentic-theme
parent.min.js?1810:6 Uncaught ReferenceError: NProgress is not defined(anonymous function) @ parent.min.js?1810:6
`

**Comment by qooob** [comment]
Ah, ok.

What is the page's URL of the right frame? Look at the source of the iFrame to find out.

**Comment by msp1kpj** [comment]
Here is the source code to "/session_login.cgi?logout=1", I could not find an iframe in the html source

`
<!DOCTYPE html>
<html data-background-style="gainsboro">
<head>
<title data-initial=""></title>
<meta charset="UTF-8">
<link rel="shortcut icon" href="/webmin/images/favicon-webmin.ico">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/webmin/unauthenticated/css/bootstrap.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/bootstrap.tagsinput.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/datepicker.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/fontawesome-animation.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/codemirror.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/jquery.jspanel.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/jquery.datatables.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/nprogress.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/authentic.min.css?1810" rel="stylesheet" type="text/css">
<script src="/webmin/unauthenticated/js/jquery.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery-ui.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery.jspanel.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery.scrollintoview.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/momentjs.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/bootbox.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery.purl.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/bootstrap.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/bootstrap.tagsinput.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/datepicker.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/fileinput.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/codemirror.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery.datatables.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery.datatables.plugins.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/jquery.easypiechart.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/clipboard.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/contextmenu.min.js?1810" type="text/javascript"></script>
<script src="/webmin/unauthenticated/js/init.min.js?1810" type="text/javascript"></script>
</head>
<body data-debug="prod" data-usermin="0" data-shell="0" data-theme="" data-level="0" data-user="" data-dashboard="1" data-language="en" data-charset="UTF-8" data-webprefix="/webmin" data-current-product="webmin" data-style="-webkit-filter: grayscale()  saturate() hue-rotate(deg); filter: grayscale()  saturate() hue-rotate(deg);">
<div class="container-fluid col-lg-10 col-lg-offset-1">
<div class="panel panel-default">
<div class="panel-heading">
<table class='header' width=100%><tr>
<td id="headln2l" width="25%" align="left" class="invisible"></td>
<td id='headln2c' align=center width=50%><font size=+2></font></td>
<td id='headln2r' width=25% align=right></td></tr></table>
</div>
<div class="panel-body">
<center>
<h3>Logout successful. Use the form below to login again.</h3><p>

<form class="ui_form" role="form" action="/webmin/pam_login.cgi" method="post" >
<input class='ui_hidden' type='hidden' name="cid" id="cid" value="">
<div class='table-responsive'><table class='table table-striped table-condensed table-subtable' width=40% class='loginform'>
<thead><tr><th class='table-title'><b>Login to Webmin</b></th></tr></thead>
<tbody> <td><table class='sub_table_container' width=100%>
<tr>
<td colspan="2" class="col_value col_header">You must respond to the question below to login to Webmin server on <tt>vts-vb-a</tt>.</td></tr>
<tr>
<td class='col_label'><b>Username</b></td>
<td colspan="1" class="col_value"><input style="display: inline; width: auto; height: 28px; padding-top: 0; padding-bottom: 0; vertical-align: middle" class="form-control ui_textbox" type="text" id="answer" name="answer" value="" size="20" >
</td></tr>
</table></td></tbody></table></div>

<button class="btn btn-default ui_submit ui_form_end_submit" type="button">&nbsp;<span data-entry="pam_login">Continue&nbsp;</span></button>
<input class="hidden" type="submit" >
<button class="btn btn-default ui_reset" style="height: 28px; vertical-align:middle" type="reset" >Clear</button>
</form>
<script type='text/javascript'>
var opts = document.getElementsByClassName('ui_opt_textbox');
for(var i=0; i<opts.length; i++) {
  opts[i].disabled = document.getElementsByName(opts[i].name+'_def')[0].checked;
}
</script>
</center>

<script>
if (window != window.top) {
	window.top.location = window.location;
	}
</script>
</div>
</div>
</div>
<script src="/webmin/unauthenticated/js/postinit.min.js?1810" type="text/javascript"></script><script>___authentic_theme_footer___ = 1;</script>
<script src="/webmin/unauthenticated/js/parent.min.js?1810" type="text/javascript"></script>
</body>
</html>
`

**Comment by qooob** [comment]
Alright, I will take a look. Thanks.

**Comment by msp1kpj** [comment]
It looks like the HTML is there but the JavaScript Exception is not allowing the Opacity on the "body:not(.csf):not(.__e__) .container-fluid " to be set to 1

**Comment by qooob** [comment]
Add the following to the /etc/webmin/authentic-theme/styles.css

```CSS
body:not(.csf):not(.__e__) .container-fluid {
    pointer-events: auto;
    opacity: 0;
}

```

**Comment by msp1kpj** [comment]
This path does not exist on our CentOS box. Is this a new directory or is there another path I should use?

**Comment by msp1kpj** [comment]
I found "/usr/libexec/webmin/authentic-theme/". Would that be the correct path?

**Comment by qooob** [comment]
No. `/etc/webmin/authentic-theme` - create it!

**Comment by msp1kpj** [comment]
I am not seeing that file being loaded in. I create a similar fill in the  

```

<link href="/webmin/unauthenticated/css/bootstrap.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/bootstrap.tagsinput.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/datepicker.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/fontawesome-animation.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/codemirror.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/jquery.jspanel.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/jquery.datatables.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/nprogress.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/authentic.min.css?1810" rel="stylesheet" type="text/css">
```

But I added a similar file in the "/usr/libexec/webmin/authentic-theme/unauthenticated/css/styles.css" directory and it is showing.

```
<link href="/webmin/unauthenticated/css/bootstrap.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/bootstrap.tagsinput.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/datepicker.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/fontawesome-animation.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/codemirror.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/jquery.jspanel.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/jquery.datatables.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/nprogress.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/authentic.min.css?1810" rel="stylesheet" type="text/css">
<link href="/webmin/unauthenticated/css/styles.css?1473172711" rel="stylesheet" type="text/css">
```

I change the CSS to opacity 1. Is is showing the page now but the "Continue" Button does not submit the form.
```
body:not(.csf):not(.__e__) .container-fluid {
    pointer-events: auto;
    opacity: 1;
}
```

**Comment by msp1kpj** [comment]
When doing the AJAX request for"/index.cgi/?xhr-get_theme_language=1" and "/index.cgi/?xhr-get_available_modules=1" it is bring up the "Login to Webmin" page.

**Comment by qooob** [comment]
I got the reason why. I might come back a bit later with a question, otherwise I'll just fix it upon next release.

**Comment by msp1kpj** [comment]
OK, Let me know if you need an further testing.

**Comment by qooob** [comment]
What is your `/etc/pam.d/webmin` content>

**Comment by qooob** [comment]
..I'm trying to reproduce it.

**Comment by qooob** [comment]
If you run in the console `__s___();` will it work?

**Comment by qooob** [comment]
After 18.20 release please double check. It might be working fine. In case it doesn't PLEASE reopen this issue and will try again. I think, I fixed it (theoretially) but I don't know how to make `pam_unix.so` setup work quickly on my system.

In case it's not fixed, please reopen the issue and tell me how to set things up.

18.20 will be release very soon.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

**Comment by qooob** [comment]
I could finally reproduce it and I found out that the login screen in Authentic Theme didn't even consider PAM auth.

https://github.com/qooob/authentic-theme/issues/580

It will be working as expected in 18.30.

Why are you using PAM auth, by the way? Why not using default one?
