### ISSUE TITLE
Firewall - Rules Description

### ISSUE THREAD

**Issue by TechnoKickAss** [qooob/authentic-theme#545]
Hello,

I've no issue but a request, could you please add the firewall rule description to the global overview?
Right now it just shows Action & Condition.
This would help me so much since I have a lot rules there.

Kind regards

**Comment by qooob** [comment]
Hi,

You can do this by going in to module options and enabling `Display comment in rules list?`. Is that what you meant, right? ;)

**Comment by TechnoKickAss** [comment]
Thank you for the fast response but I'm sorry but I don't have any module options for the ip tables.
I'm running Webmin version 1.810 and Authentic Theme 18.10.

Here is a screenshot of the system tab, where should be the options?
[http://i.imgur.com/2HtFtaG.png](link)

**Comment by qooob** [comment]
When you at the Firewall module, there is a cog like button in the header. On your second screenshot you have it on the left from the right page title. Same for Firewall, got it?

**Comment by TechnoKickAss** [comment]
Thank you very much I found it.
Yesterday I just changed my Webmin design for the first time in 4 years,
and there is just way to much information changes at once - like I'm not used to it but I really like this beautiful and useful design, good job!

**Comment by qooob** [comment]
Thanks, pal for your kind words.

It will be getting better and better!
