### ISSUE TITLE
Virtualmin Git: No button clicked

### ISSUE THREAD

**Issue by recursosformacion** [qooob/authentic-theme#546]
Another time!:
When the Virtualmin Git plugin is installed, clicking on "Repository Commands" or "Browse Repository" it will display an error page with the message: "No button clicked!"

 I used version 5.02

**Comment by qooob** [comment]
It was global bug produced by something I wouldn't think to exist (caused by server-side).

It will be fixed in 18.20. Thanks for reporting.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
