### ISSUE TITLE
Theme: ConfigServer Security & Firewall 9.20+ UI is broken with Authentic Theme 18.10

### ISSUE THREAD

**Issue by jobhh** [qooob/authentic-theme#547]
CSF updated their UI for version 9.20, see https://download.configserver.com/csf/changelog.txt. I updated my backup server to test it and it seems like Authentic doesn't know how to handle the new UI and just reloads my Virtualmin home page (System Information).

Steps to reproduce:
1. Update to CSF 9.20
2. Go to the CSF settings page, https://myserver.mine:10000/csf
3. Just wait a second (while looking at the updated UI) and see it return to https://myserver.mine:10000

A complete reboot of the system did not fix it and Incognito mode produced the same results.

Server:
Webmin 1.810 
Virtualmin 5.04
Authentic Theme 18.10
Debian Linux 8.6

PC:
Windows 10 Academic 64bit
Chrome 53 64bit

This is what the CSF page looks like before reloading into the System Information page:
![2016-09-19 1](https://cloud.githubusercontent.com/assets/2331451/18628024/7901cd66-7e5e-11e6-8465-1b27f659667d.png)

Am I correct in assuming quite some theme conversion code can be stripped Authentic now? CSF is now natively based on Bootstrap, so only changing the CSS will already make it fit in quite a bit.

**Comment by qooob** [comment]
I'm glad that I've inspired _CSF_ team to finally move on. :D .. and yes, I expected this after reading logs.

I will take a look at it.

At the moment, the best would be is to comment out `/usr/libexec(share)/webmin/authentic-theme/extensions/csf.min.js`.

It will take much more work to support it.

**Comment by qooob** [comment]
I have made a request, will see if support will be able to provide plain version of the module, without extra stuff loaded.

https://forum.configserver.com/viewtopic.php?f=6&t=9762&p=27029#p27029

**Comment by qooob** [comment]
It will be supported in next version of the theme, presumably **18.20** in the middle of _October_.

**Comment by mvander** [comment]
Great. Thank you!

**Comment by paolokappa** [comment]
Jesus, in the middle of October... can't wait so long :D
We definitely love your theme.
Could you release an intermediate small patch to fix this issue?

**Comment by qooob** [comment]
I explained how to disable it and make it at least work.  (by purging `csf.min.js`)

Well, I will try to make it sooner but I can't promise. I have very serious project to finish right now.

**Comment by paolokappa** [comment]
Thanks Ilia, I did it and now it’s properly working.

Cheers,

Paolo Caparrelli

[logoRidotto]<http://www.goline.ch/>



Da: Ilia Rostovtsev [mailto:notifications@github.com]
Inviato: mercoledì, 21. settembre 2016 11:12
A: qooob/authentic-theme <authentic-theme@noreply.github.com>
Cc: Goline SA - IT Services <it@goline.ch>; Comment <comment@noreply.github.com>
Oggetto: Re: [qooob/authentic-theme] Theme: ConfigServer Security & Firewall 9.20+ UI is broken with Authentic Theme 18.10 (#547)


I explained how to disable it and make it at least work. (by purging csf.min.js)

Well, I will try to make it sooner but I can't promise. I have very serious project to finish right now.

**Comment by alnork** [comment]
temporary solution in centos 6.7:
rm /usr/libexec/webmin/authentic-theme/extensions/csf.min.js -f

**Comment by qooob** [comment]
Yes, exactly!

**Comment by SteffanCline** [comment]
I did the rm trick above to make mine work but the dashboard shows the wrong status on CentOS 7. It says it's not running but when you go to the CSF page, it says it IS running.

**Comment by qooob** [comment]
Yes, there were a lot of changes in CSF recently. They are moving on.

I will fix all of it and try to add new features. Getting back to it on October 12. ;)

**Comment by montgomerykern** [comment]
I have been experiencing the same issues with CSF but in the interim i have been opening a new tab from the dashboard and working in CSF on its own independent tab or window and it seems to have resolved most of my issues. 

Might I suggest that from the left hand menu that its changed to open in a new tab until fixes have been issued by all. 

Cheers!!

**Comment by CanadianJeff** [comment]
whats the status of this bug? is it solved?

**Comment by alnork** [comment]
October 12

**Comment by qooob** [comment]
Yeah, October 12 I'll start and make a fix release within a week or so. There are a lot of issues as you probably saw. 

It works if you delete the file, so its usable for a little while.

**Comment by alnork** [comment]
@qooob What happened with upgrade?

**Comment by jobhh** [comment]
@alnork Qooob said he would start working on it on October 12. I think it's a fair assumption to say he didn't finish it in 1 day. If it's still unreleased in 1-2 weeks we should ask him what's up :p

**Comment by alnork** [comment]
mmmmmm ok.... thanks!

**Comment by qooob** [comment]
Yes, this is correct, @jobhh, thanks. I'm already working on the new release.

**Comment by qooob** [comment]
I have finally fixed that and made it look hot again.

It will take few more days before you guys could enjoy it in 18.20

It took a lot of time. Sorry for delay!!

**Comment by alnork** [comment]
Good news ... Bravo !!!

**Comment by SteffanCline** [comment]
Will this also fix the issue where it says csf is not running when it really is?

**Comment by qooob** [comment]
It should.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

I hope you will enjoy it!

**Comment by alnork** [comment]
thaaaaaaanks a lot @qooob

**Comment by qooob** [comment]
Please read and re-update the theme over again.
https://github.com/qooob/authentic-theme/issues/568

**Comment by qooob** [comment]
Third wave is ready: https://github.com/qooob/authentic-theme/issues/568
