### ISSUE TITLE
Configserver module loads in CSF default style, then returns to Virtualmin 

### ISSUE THREAD

**Issue by UTCWebDev** [qooob/authentic-theme#548]
When CSF module link on Virtualmin home page is clicked, the page begins loading in CSF default style, with a thick red spinner icon. Page goes blank and continues loading, then returns to Virtualmin home page.

Latest theme (18.10) and Webmin (1.810) versions installed. Force updated.

* Amazon Linux 2015
* CSF 9.2.0
* Client: OS X 10.11.6, Safari 9.1.3
* To reproduce: Click Configserver link from main Virtualmin page

![screen-shot 2016-09-20 at 9 04 53 am](https://cloud.githubusercontent.com/assets/2539685/18671272/7d29b602-7f11-11e6-87b4-29187a86a9c2.png)

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/547

**Comment by qooob** [comment]
Version 18.20 is out and support latest CSF. Please upgrade.

I hope you will enjoy it!
