### ISSUE TITLE
File Manager: False positive message: `Directory is empty`

### ISSUE THREAD

**Issue by erdembey** [qooob/authentic-theme#549]
Authentic Theme 18.10
Webmin version 1.810 

There is an error with filemanager. From time to time, in several folders, filemanager displays "Directory empty" message even though there are files and folders.

![filemanager](https://cloud.githubusercontent.com/assets/592237/18810988/0ce35020-82ad-11e6-93bd-75bf30d7c1c6.png)

**Comment by qooob** [comment]
Hi,

I wish I had more details on how to reproduce it.

Could you tell me how do you reproduce it? Do you have filters on or doing anything else?

**Comment by erdembey** [comment]
I am sorry for delay.
I will provide details as soon as possible.
I have several servers but i can not reproduce it right now. My customers are also reporting this but i need to find out the related configuration.

**Comment by qooob** [comment]
Had a chance to reproduce it in past 19 days? In case you can't please close the issue and come back to it in the future, whenever and if it happens again.
