### ISSUE TITLE
Configserver Security & Firewall Page Won't Load & Page Jumping Issue

### ISSUE THREAD

**Issue by applejack1923** [qooob/authentic-theme#550]
Hi

The Configserver Security & Firewall (CSF) page won't load as it re-directs back to the main Virtualmin system info page. As a test I changed to a different theme and it loads fine.

Also after the recent updates when a page needs to update the data shown on the screen such as on system package updates where it can be a long page of information getting updated, the page keeps jumping back to the top of the screen and doesn't show the bottom part of the page until it has finally stopped the process.

Authentic 18.10, Virtualmin 5.04.gpl, Webmin 1.810, CSF 9.22, CentOS 6, Safari 9, Mac

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/547

**Comment by qooob** [comment]
For the jumping page problem start the new issue please and provide more information. Before that clear browsers cache and restart Webmin.

**Comment by qooob** [comment]
Dies it work in Chrome?
