### ISSUE TITLE
Theme: Page jumps to top when server-page refreshes (on Safari)

### ISSUE THREAD

**Issue by applejack1923** [qooob/authentic-theme#551]
When on a page which updates itself during the process such as software update or a verbose cron job the page keeps jumping very quickly back to the top and only stops when the process has finished.

I'm not sure which version this started with as it has been going on for I would say at least a couple of months. I have only tested this in Safari so next time I will try Chrome and the server has been re-booted since it first began.

Authentic 18.10, Virtualmin 5.04.gpl, Webmin 1.810, CSF 9.22, CentOS 6, Safari 9, Mac

**Comment by qooob** [comment]
Alright, I will try to reproduce it in Safari on MacBook.

**Comment by qooob** [comment]
Confirmed and will be fixed in 18.20

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.

**Comment by applejack1923** [comment]
Good job thanks for sorting and also the CSF issue. One point though I see you have added arrows in the drop down menu of the virtual servers under Virtualmin and which arrow depends on whether it is an alias or sub server. Frankly this is somewhat annoying as it now looks too cluttered and is unnecessary as these have different levels of indent anyhow.

**Comment by qooob** [comment]
It was done in response to:

https://github.com/qooob/authentic-theme/issues/466

**Comment by applejack1923** [comment]
I have always been able to view the different padding. There is no mention in that thread about which browser they are using in not being able to see this. Rather than adding the arrows as content surely it would have been better to use the pseudo class before on the li tag then at least one could edit it in the css.

**Comment by qooob** [comment]
I'll try making it optional in 18.30

**Comment by qooob** [comment]
@applejack1923 https://github.com/qooob/authentic-theme/issues/569
