### ISSUE TITLE
Theme: Module's chooser filtering not working

### ISSUE THREAD

**Issue by acosonic** [qooob/authentic-theme#552]
Overflow should be visible, because people might not know what they want to install they might just want to browse modules and install them based on description.

Filter is not working.

![2016-09-27 09_07_53-](https://cloud.githubusercontent.com/assets/862015/18863560/31343d4a-8492-11e6-8edc-752988e5f1d2.png)

**Comment by qooob** [comment]
Yes it should and it was fixed in version 18.10.

Please upgrade your Webmin version which will ship the new version of the theme. (latest 18.10 at the moment).

**Comment by qooob** [comment]
and filter

**Comment by qooob** [comment]
After 18.20 release in few days, I will start working on enhancements. One of them will dropping old popup windows and replacing it with nice modals.

Meanwhile, I will not put effort in fixing it. If I succeeded in it will be resolved by it self if it will not be possible, then I will find the way to fix it.

**Comment by acosonic** [comment]
Ok, if you need my help with something I can work on it.

**Comment by qooob** [comment]
Hi,

I have finally made through replacing old `window.open()` with nice and sleek modals:

[Example](http://rostovtsev.ru/pub/src/authentic/18.30b/new_window_open_replacement_with_modals.webm)

It will also fix your issue. Expect it done in 18.30. ;)
