### ISSUE TITLE
Webmin System Stats: Statistics not scrollable after server refresh

### ISSUE THREAD

**Issue by acosonic** [qooob/authentic-theme#553]
Sysinfo:
Operating system	Ubuntu Linux 14.04.2
Webmin version	1.810 
Virtualmin version	5.04
Theme version	Authentic Theme 18.10

Custom module - historical statistics, unable to scroll down due to overflow hidden, because this module keeps refreshing, seems that it does not load page completley.
![2016-09-27 10_34_4](https://cloud.githubusercontent.com/assets/862015/18865982/289d875c-849e-11e6-9612-b8df3f194eac.png)

**Comment by qooob** [comment]
Thanks, I will take a look and fix it in case it's confirmed upon next release.

**Comment by qooob** [comment]
Alright, it will be fixed in 18.20.

Thanks for reporting.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
