### ISSUE TITLE
Theme: ConfigServer Security & Firewall (csf) doesnt work

### ISSUE THREAD

**Issue by CanadianJeff** [qooob/authentic-theme#555]
clicking on ConfigServer Security & Firewall will attempt to load the page and after its finished loading the page will quickly flash and return back to the home dashboard this only started happening recently so one of the latest updates is causing this issue

**Comment by CanadianJeff** [comment]
oh just to add this does not happen with other themes so it is in fact this theme causing the issue

**Comment by qooob** [comment]
Dupe: https://github.com/qooob/authentic-theme/issues/547

**Comment by qooob** [comment]
Version 18.20 is out and support latest CSF. Please upgrade.

I hope you will enjoy it!
