### ISSUE TITLE
Theme Problem With CSF

### ISSUE THREAD

**Issue by hrace009** [qooob/authentic-theme#557]
Problem with CSF
Webmin 1.810 
Authentic Theme 18.10
CentOS Linux 7.2.1511
Mozilla Firefox 49.01
Video Issue: https://youtu.be/l6ZsLv9MrXc

* What are the steps to reproduce the issue
I don't know
Please help, i love this theme so much.

**Comment by qooob** [comment]
Hi,

This is the dupe: https://github.com/qooob/authentic-theme/issues/547

You can delete your video, I'm aware of the problem and will fix it next release.

**Comment by hrace009** [comment]
okay, thanks

**Comment by qooob** [comment]
Version 18.20 is out and support latest CSF. Please upgrade.

I hope you will enjoy it!

**Comment by hrace009** [comment]
thank you
