### ISSUE TITLE
Webmin Congifg Server module not properly integrated with Theme

### ISSUE THREAD

**Issue by CapstoneWorks** [qooob/authentic-theme#558]
Latest Configserver Firewall installed and webmin module integration installed.

When clicking the Config Server lin k under Webmin Category System, ConfigServer *briefly* displays and then the theme returns to the main home page.

http://www.configserver.com/cp/csf.html 

Operating system	CentOS Linux 6.8
Webmin version	1.810 
Virtualmin version	5.04
Theme version	Authentic Theme 18.10
Time on system	Monday, October 3, 2016 9:47 AM
Kernel and CPU	Linux 2.6.32-642.4.2.el6.x86_64 on x86_64
Processor information	Intel(R) Xeon(R) CPU E5506 @ 2.13GHz, 8 cores
System uptime	31 days, 10 hours, 48 minutes
Running processes	356
CPU load averages	1.97 (1 min) 1.65 (5 mins) 1.64 (15 mins)
Real memory	21.99 GB total / 14.83 GB used
Virtual memory	3.91 GB total / 990.75 MB used
Local disk space	914.76 GB total / 126.96 GB free / 787.80 GB used
Firewall version	ConfigServer Security & Firewall 9.24    
Package updates	All installed packages are up to date 

This was working properly in a recent version of Authentic

**Comment by qooob** [comment]
Dupe https://github.com/qooob/authentic-theme/issues/547
