### ISSUE TITLE
Unable to open UI of CSF

### ISSUE THREAD

**Issue by binyaskk** [qooob/authentic-theme#560]
i installed and configured webmin with CSF, everything is looking good, but when iam trying to go to CSF UI, it opens the CSF UI for few seconds, then it redirects automatically to webmin homepage.

Operating system	CentOS Linux 7.2.1511
Webmin version	1.810 
Virtualmin version	5.04
Theme version	        Authentic Theme 18.10
Firewall version	ConfigServer Security & Firewall 9.24

After some testing found that the UI can be opened if we open in new window, instead of clicking the link from webmin.

feels like "Webmin Main Page" floating button in CSF UI is creating the issue with the theme.

this problem is same in chrome and firefox

any solution?

**Comment by qooob** [comment]
Dupe https://github.com/qooob/authentic-theme/issues/547

**Comment by binyaskk** [comment]
sorry

**Comment by qooob** [comment]
Version 18.20 is out and support latest CSF. Please upgrade.

I hope you will enjoy it!
