### ISSUE TITLE
Theme: Usermin theme is really slow to load

### ISSUE THREAD

**Issue by topstarnetwork** [qooob/authentic-theme#562]
Provide the following information:
* What is your server-side OS and its version?
Ubuntu latest version
* What is your client-side OS, browser and its versions?
windows, chrome and firefox
* What are the steps to reproduce the issue
authentic-theme works really good on ; webmin, cloudmin,  virtualmin but not on usermin wich takes ages to load and crashes my brower.

The following tutoral did not work:  How do I make the theme load faster?

Webmin has in-built option to compress static files. It's possible to enable this feature by going to Webmin->Webmin Configuration->Web Server Options and setting Gzip compress static files option to Use pre-compressed file and compress dynamically.

In this case is it that the usermin authentic-theme bugs?
What and how can we fix this problem?

**Comment by qooob** [comment]
Hi,

I think you have some issues with `Mailbox` module. Try disabling it in `Webmin->Usermin Configuration`. What happens in _Gray Theme_?

**Comment by moshaiky** [comment]
Hi @qooob 

I am a system admin of Heather.
What exactly we need to disable in "Try disabling it in Webmin->Usermin Configuration"?

Actually when we switch theme to authentic-theme it takes long time to apply. Also when we click to any button it takes long time and sometime slow to death.
But switching to other theme works fine. only issue with "authentic-theme".

Webmin version	1.821
Virtualmin version	5.04
Cloudmin version	9.1.kvm
Theme version Authentic Theme 18.10

Is this theme is compatible with webmin version?

**Comment by qooob** [comment]
In Usermin->Configuration->Modules and disabling `Mailbox` module for testing purposes.

Did you install Authentic Theme as it is (using Webmin) or symlink?

**Comment by topstarnetwork** [comment]
We disabled Mailbox module , and it is true it works much better and I canload my emails now but still the page takes a couple of seconds to  load, can we improve the seep od loading?
And can we remain with mailbox module desabled for ever?
What is the mailbox module used for in this case?

**Comment by qooob** [comment]
Actually, I don't understand how you can read mail without `Mailbox` module enabled.

Make it load faster? I don't know what faster means. In my case, it loads in a flash I can't judge it the other way - please be kind making a _videoscreencast_. You can send me the link using my website. (for privacy purposes).

**Comment by qooob** [comment]
What Usermin version do you have installed?

**Comment by topstarnetwork** [comment]
Usermin Version	1.701

**Comment by qooob** [comment]
I see. Please make videoscreencast.

**Comment by topstarnetwork** [comment]
It now works much better but can you tell me if I have to keep Mailbox module desable for ever in order for authentic theme to work???
What is Mailbox module meant for????

**Comment by qooob** [comment]
Hi,

I'm not sure to what you mean but you _can't read your mail_ and have Mailbox (Read Mail) being disabled at the same time.

I think the reason you have it slow is because of the incorrect settings. Your solution could be is to check and tweak `Usermin Configuration -> Usermin Module Configuration -> Read Mail`.

It doesn't seem to me to be the theme's issue. 

However, I'm glad to help.

Good luck,
Ilia

**Comment by moshaiky** [comment]
Hi @qooob 

Now we have migrated all our mailbox to someother webmin working server. Everything was working fine. After changing to authentic-theme the page is loading and loading and it die and never complete..

Even we tried re-login still same issue. The user mailbox size is 31G and for that particular user consuming high memory utilisation.

At present we have below setting:
Usermin Configuration -> Usermin Module Configuration -> Read Mail

For other user it is working fine.

What could be the issue?

Now user not able to access mailbox.

**Comment by qooob** [comment]
Can you go to theme configuration and add exclude for all models `*`. Then reload the theme using `Ctrl+R`.

Afterwards, when going to Usermin, there should be no loader and all should be seen, if I remember correctly.

Can you check if there are errors in console. Can you remove initial loader and see what's on the content?

Other thing is to do all above and then in theme settings set default page for Usermin something else but Mail. How is it then?

**Comment by moshaiky** [comment]
@qooob thanks for your reply.

Still same issue. How i can revert to default theme from backend or from webmin for particular user?

**Comment by qooob** [comment]
Using `Webmin->Change Language and theme`

**Comment by moshaiky** [comment]
This is global webmin theme change.. I asked for particular user theme change, because currently user unable to access usermin so he cant change theme.

**Comment by qooob** [comment]
Do you really believe that the source of the issue is Authentic Theme? You mentioned above that all other users work fine? Did you try to smaller the size of the mailbox to 1.5 GB for example?

I would like to make sure that it's not Authentic Theme problem, so please provide more information after changing the theme.

To change theme manually just go:

   1. `/etc/usermin/config` and add the following: `theme_USERNAME=gray-theme`
   2. `/etc/usermin/miniserv.conf` and add the following:  `preroot_USERNAME=gray-theme`

Tell me, is your issue still persists compare to other users on your system with Authentic Theme?
