### ISSUE TITLE
Theme: Safari on iPad problem

### ISSUE THREAD

**Issue by Martin-By** [qooob/authentic-theme#563]
Hello I am using version 8.10 on ubuntu 16.04 lts on cubietruck.

Only on my Ipad air (win10 and android browsers are fine) I have problems to do some actions.
Changing into an other theme allows same action.

Filemanager (for example)
1. mark file
2. try action (delete)
3. popup window without any function (greyed out)
4. this popup window freezes, so webmin must be reloaded

In addition:
Is it possible to hide/unhide the left main menu to get more display space for small devices?
It seems Ipad is not detected as mobile device.

Best Regards,

Martin

**Comment by qooob** [comment]
Martin, hi.

It's not hiding because the screen resolution is not that small and theme thinks it's ok.

You can smaller the whole left menu size in the theme's settings.

Speaking about Safari. Are you saying that the screen gets dimmed and you don't see modal window for delete action?

**Comment by Martin-By** [comment]
Right, the window is dimmed. Do I have to change some settings on Ipad?

**Comment by qooob** [comment]
No. It seems like either Safari bug. It also could be Bootstrap bug which will be updated in 18.20.

Could you install Chrome and try it again on your iPad please?

**Comment by Martin-By** [comment]
So I tried it with Crome & Firefox with same result as Safari.

Ok, then I have to wait until 18.20.

Thank you very much for your quick response.

Best Regards,

Martin
