### ISSUE TITLE
Auto Scroll

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#564]
The autoscroll in Chrome on Mac is broken. I have not tested it in any other browsers. It's weird. I can see the text being inserted line by line but when I use a scroll wheel or trackpad, it won't scroll but if I manually grab and drag the scroller, it will work. It does not perform this way on the original framed theme.

**Comment by qooob** [comment]
Yeah, I know. It will be fixed in 18.20.

**Comment by qooob** [comment]
Version 18.20 is out, please upgrade.
