### ISSUE TITLE
File Manager: Command line

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#566]
It would be great to have command line interface in File Manager, just the same way it's done in Midnight Commander or Double Commander.

**Comment by qooob** [comment]
It's no use having command line only in File Manager.

Version 18.30 will have drop-down console, like Guake Terminal.

It will port functionality from `shell` module. In case it's available it will work (having the same or a little enhanced functionality).

It will be callable by the hotkey (default is `Alt+L`) and dismissed the same way and/or just hitting escape. History will also work by using up/down arrow keys.

The previously enrolled support for calling the command from the search bar by using `!command` will be passed to the new drop-down console and opened there instead of going to the module.

Here is the little teaser. 

Please share your thought  before the release.

http://rostovtsev.ru/pub/src/authentic/18.30b/new_command_line_port.webm

**Comment by qooob** [comment]
Enrolled additional commands `clear`, `reset`, `history` and `history -c`. Hotkey `Alt+L` will clear console in case it's opened.

**Comment by qooob** [comment]
### Edit:

Hotkey `Alt+K` will clear console in case it's opened.

**Comment by qooob** [comment]
### Edit:

History will be extracted from the shell modules (either Webmin or CM/save_serv.cgi?id=xx&shell=1) and stored. It will provide support for usage with multiple servers.

**Comment by qooob** [comment]
Finally default keys for bringing up the shell is:

`Alt+K`

and for clearing shell:

`Alt+L`

**Comment by neubreed** [comment]
This seems to give the user root access .. When I type whoami is get "root". Is there any configuration for this?

**Comment by qooob** [comment]
That wouldn't be possible. It's just a port of shell module.

**Comment by qooob** [comment]
Configuration in Command Line module.

**Comment by neubreed** [comment]
Take a look at this:

https://i.imgur.com/oiyIPG2.png

I'm root but logged in as ryan.

Do you mean command shell program?

**Comment by qooob** [comment]
What does it mean you are root but logined as ryan? Try running the same command under Command Line module. What is the output? It will be the same anyway.

**Comment by neubreed** [comment]
I've logged into webmin as normal user "ryan". When I use the command shell and type whoami I get root .. I can cd into /root/ and can delete files. Maybe this is not an issue for Authentic Theme. What do you get when you type whoami on your system?

**Comment by qooob** [comment]
When I get home, I'll let you know.

**Comment by qooob** [comment]
Hi,

I tried it under user account (in Usermin) and it returns the correct username.

I think you miss-configured your ACLs.

**Comment by neubreed** [comment]
Oh ok .. I haven't tried in usermin. what do you get in webmin?On 8 Dec 2016 6:57 p.m., Ilia Rostovtsev <notifications@github.com> wrote:Hi,
I tried it under user account (in Usermin) and it returns the correct username.
I think you miss-configured your ACLs.

**Comment by 7starsone** [comment]
Hello, may I know why CLI doesn't run something like htop and other?
eg. `Error opening terminal: unknown.` OR for top `TERM environment variable not set.`
?

**Comment by qooob** [comment]
Yes, because it's not interactive terminal yet. I guess we need to switch to using sockets for webserver. Theme just extends the functionality of Command Line module and it it's not yet interactive.
