### ISSUE TITLE
18.20 has crashed Webmin

### ISSUE THREAD

**Issue by Sarge2013** [qooob/authentic-theme#567]
Hello Ilya,
just now has updated to 18.20 and something is VERY bad !
First time after pressing update button on dashboard I met so terrible result...I don't know what's happenned - but webmin interface completely crashed.
After login - no any possibility even to rule by something, no one link work.
Tried to restart webmin service, tried using Mozilla and Chrome browsers, cleared all cache and logins - no result ! and the WORSE issue I can't even return standard Webmin interface, may be just delete authentic physically at all somewhere ?
Centos 7 - see 2 attachments
![29 10 16 23-18-27](https://cloud.githubusercontent.com/assets/5161375/19832538/7d57c5c4-9e2e-11e6-9d89-1558548ce192.jpg)
![29 10 16 23-17-59](https://cloud.githubusercontent.com/assets/5161375/19832539/8294aeda-9e2e-11e6-9c7f-39eb7cab65cd.jpg)

**Comment by qooob** [comment]
YEAH!! It was 2 minutes time frame when I made false push. Nothing special. Just find 

`/usr/libexec/webmin/authentic-theme/authentic-init.pm`

find `sub isd`

and change `return 'debug';` to `return 'production';`

**Comment by qooob** [comment]
Sorry about that!

**Comment by qooob** [comment]
Here is the direct and fixed link in case you don't want to edit it manually:

`https://github.com/qooob/authentic-theme/releases/download/18.20/authentic-theme-18.20.wbt.gz`

**Comment by qooob** [comment]
..but it's easier to edit it, I think!

**Comment by Sarge2013** [comment]
thanks for flash reaction :) I've returned at-least classic theme when renamed /webmin/authentic-theme/ to /webmin/_authentic-theme_

**Comment by qooob** [comment]
Just install the theme using the link above. It's fixed and working.

I hope you the only one who grabbed it.

**Comment by Sarge2013** [comment]
Now all OK :) wow 👍 thanks !

**Comment by qooob** [comment]
You're welcome!! ;) Enjoy!

**Comment by Sarge2013** [comment]
... just still a little heavy work with csf 9.25 interface...loading circle in the right top corner does not disappear...but no crashes and redirects to dashboard with csf as before - so thank you for that improvement too !
As to this suddenly bad update - please, mark the issue as solved.
Best regards !

**Comment by qooob** [comment]
Serge, you should have no problems with CSF and it seems that you do now.

Because you loaded debug version which loads `src` version of the files you need to either delete the following files and `CTRL+R` (reload) the theme or edit them and replace `src`->`min` in:

`/etc/csf/csf.header`

**Comment by Sarge2013** [comment]
do you mean delete /etc/csf/csf.header ?

**Comment by qooob** [comment]
yes and reload the theme

**Comment by qooob** [comment]
it will be regenerate the correct version of it

**Comment by Sarge2013** [comment]
Yes ! 👍  very good now ! much better then their strange experiment with own csf interface.
Thanks again !
Have a nice weekend !

**Comment by qooob** [comment]
Good to hear. You too!
