### ISSUE TITLE
Theme: Users and groups enhancement

### ISSUE THREAD

**Issue by seansan** [qooob/authentic-theme#570]
latest versions

in users and groups section would it be able to add button/action "copy user"

where everuthing is copied exept username and passwd?

**Comment by qooob** [comment]
Could you please elaborate your request, I haven't understood anything?

**Comment by seansan** [comment]
can you add a button in the list under users/groups so I can duplicate a user?


![image](https://cloud.githubusercontent.com/assets/652395/19925124/fc82e64a-a0ee-11e6-8849-bf1382f3fed4.png)

**Comment by qooob** [comment]
This functionality is already available. Go to the user you need to duplicate, then scroll down the page and click `Clone User`
