### ISSUE TITLE
File Manager: iPad modals do not work

### ISSUE THREAD

**Issue by Martin-By** [qooob/authentic-theme#571]
my setup theme (18.20) and Webmin (1.820) 

Still follwing as 18.10:

-navigating to file
-marking file
-choosing action (here chmod)

pop ups a greyed window without any action (same safari and firefox)

**Comment by qooob** [comment]
I will take a look. However I don't have an iPad to test it.

[First look](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Ipad+bootstrap+modal) tells me there are a lot of issues like that already.

Could you please go to [Bootstrap](http://getbootstrap.com/javascript/#modals) website and check how modals are working there?

**Comment by Martin-By** [comment]
Ok, "launch demo modals" works:

- can open window
- can open window via button
- can close the window with button

**Comment by qooob** [comment]
..your main complain that you can't see modal at all on the iPad and that's it?

**Comment by qooob** [comment]
Hi,

I could really reproduce this bug on iPad Pro. 

I have made [pull-request](https://github.com/webmin/webmin/pull/462) to Webmin repo.

**Comment by qooob** [comment]
I will be fixed on the theme side in 18.30. Webmin fix was incorrect. We keep modals on the inside as it contains form elements. Otherwise it would require a lot of redo.

**Comment by qooob** [comment]
..and other recommendation that will make it work right now - 

Just go to Safari on iPad and `Request desktop version` of the webiste under share icon.
