### ISSUE TITLE
Some CSS/JS Files do not load in Usermin leading to black/white and unusable interface

### ISSUE THREAD

**Issue by ElpyDE** [qooob/authentic-theme#572]
The display of Usermin is completely destroyed. All is default black/white.

Looks like mostly the Menu is shown but the Text that should be menu items is not clickable. Further down is a pretty small iframe with what looks like the main page content.

Screenshot from IEx (in Firefox it looks very similar, only the iframe is further down)

![screenshot-usermin](https://cloud.githubusercontent.com/assets/13076019/19948257/f36831fc-a14b-11e6-891f-a11e334551d0.png)

It looks like some of the stylesheets and javascripts cannot be loaded:

Firefox' Developer Tools Network tab shows 404 Error on the following files (some of them multiple times):

```
DOMAIN:USERMIN-PORT/unauthenticated/css/bundle.min.css?1820
DOMAIN:USERMIN-PORT/unauthenticated/css/content.bundle.min.css?1820
DOMAIN:USERMIN-PORT/unauthenticated/css/parent.bundle.min.css?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/bundle.min.js?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/content.bundle.min.js?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/parent.bundle.min.js?1820
```

It still gets served successfully (Code 200):

```
DOMAIN:USERMIN-PORT/unauthenticated/js/content.min.js?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/init.min.js?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/parent.min.js?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/postinit.min.js?1820
DOMAIN:USERMIN-PORT/unauthenticated/js/settings.js?1478121795
```

Found _all_ the files below `/usr/share/webmin/authentic-theme/`

Most files in this directory have a recent changed time (which is days after the theme update), including files from both above groups. Only notable exception is `settings.js` which was apparently copied from `/etc/webmin/authentic-theme/` during the theme update. File ownership and permissions are all consistent across both groups.

The Usermin logfiles don't offer more information on this:

**/var/usermin/miniserv.log**

```
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/css/parent.bundle.min.css?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/settings.js?1478121795 HTTP/1.1" 200 3437
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/css/bundle.min.css?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/bundle.min.js?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/parent.bundle.min.js?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/bundle.min.js?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/init.min.js?1820 HTTP/1.1" 200 22338
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/parent.bundle.min.js?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET / HTTP/1.1" 200 6798
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/parent.min.js?1820 HTTP/1.1" 200 30762
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /changepass/ HTTP/1.1" 200 6161
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/css/content.bundle.min.css?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/postinit.min.js?1820 HTTP/1.1" 200 77744
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/css/bundle.min.css?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/content.bundle.min.js?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/bundle.min.js?1820 HTTP/1.1" 404 32
_MY-IP_ - _MY-USERNAME_ [02/Nov/2016:22:23:15 +0100] "GET /unauthenticated/js/content.bundle.min.js?1820 HTTP/1.1" 404 32
```

**/var/usermin/miniserv.error**

```
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/css/parent.bundle.min.css : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/css/bundle.min.css : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/bundle.min.js : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/parent.bundle.min.js : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/bundle.min.js : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/parent.bundle.min.js : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/css/content.bundle.min.css : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/css/bundle.min.css : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/content.bundle.min.js : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/bundle.min.js : File not found
[02/Nov/2016:22:23:15 +0100] [_MY-IP_] /unauthenticated/js/content.bundle.min.js : File not found
```

**What is your server-side OS and its version?**
Ubuntu 14.04LTS, up to date
Webmin 1.821, Usermin 1.701
Authentic Theme 18.20

**What is your client-side OS, browser and its versions?**
Windows 10, Firefox 49.0 and Internet Explorer 11.0

**What are the steps to reproduce the issue**
I updated the theme 2 weeks ago to the actual theme version and just didn't realize this earlier. I don't think that I did anything else that could have introduced this behavior.

Other themes work normally (e.g. "Virtualmin Framed Theme"). Changing the theme to another one and back to Authentic Theme does not help. Neither does a restart of Usermin.

Authentic Theme for Virtualmin and Webmin still works as it should.

Thanks very much for any help - and for your work in general on a great theme that makes me enjoy Virtualmin/Webmin every day!

**Comment by qooob** [comment]
All you need is to go to Webmin and manually update the theme for Usermin. Theme didn't get updated automatically. It (automatic update) will work fine since next release.

**Comment by hostlawn** [comment]
Having the same problem.  Please provide more details as to how to update the theme for Usermin.  I see no 'update theme' in 'usermin themses' under usermin config

**Comment by qooob** [comment]
`Webmin->Usermin Configuration->Usermin Themes`. Then `Install Themes` tab, and check radio for remote URL and insert the following to the input field:

`https://github.com/qooob/authentic-theme/releases/download/18.20/authentic-theme-18.20.wbt.gz`

**Comment by ElpyDE** [comment]
That worked! Thanks for the link... made updating a peace of cake!
