### ISSUE TITLE
Login Screen is Hosed UP

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#573]
The login screen presents itself with no CSS or images.
![screen shot 2016-11-02 at 9 28 24 pm](https://cloud.githubusercontent.com/assets/1323544/19956123/d87092be-a145-11e6-854a-ced7cd201e53.png)

**Comment by qooob** [comment]
Please reinstall the theme, you grabbed the very first push, there were few bugs. After reinstalling it, also CSF will be displayed better. Don't forget to clean browser's cache after all.
