### ISSUE TITLE
Fail2Ban with IPtables - Jump to chains repeated

### ISSUE THREAD

**Issue by clawrie** [qooob/authentic-theme#574]
When using Fail2Ban & the Linux Firewall Webmin module on Centos 6, Fail2Bans 'Jump to chain' actions are listed more than once.  Refer attached screens.
![fail2ban-chains](https://cloud.githubusercontent.com/assets/9471257/20023097/99dd14d4-a32d-11e6-9b55-f06b8402ca75.png)
![iptables](https://cloud.githubusercontent.com/assets/9471257/20023102/a2e5c058-a32d-11e6-9ed0-63a26c9c123e.png)

**Comment by qooob** [comment]
Hi,

Isn't the same displayed if you change the theme?

**Comment by clawrie** [comment]
Apologies - I'll try this and get back to you.

**Comment by clawrie** [comment]
Yes it is the same using the Virtualmin theme. Guess that's not your issue then.  Sorry.

**Comment by qooob** [comment]
Please post this issue to Webmin repo.
