### ISSUE TITLE
Apache:  Server Selection Check Boxes are missing in version 18.20

### ISSUE THREAD

**Issue by jmcguirl** [qooob/authentic-theme#575]
I updated to 18.20 on several machines. used different browsers (Chrome,Firefox, Edge, IE11) and tested.

**Comment by qooob** [comment]
Hi,

I'm not sure what you mean. Could you provide the screenshot please?

However, if I'm guessing correctly, goto Apache Module's settings (cog icon at the top), and change `Display virtual servers as` -> `List`.

**Comment by jmcguirl** [comment]
![apache-module-missing-check-boxes](https://cloud.githubusercontent.com/assets/1687213/20158111/814cbad8-a6a6-11e6-93c9-c617dce7271b.png)
![apache-module-with-check-boxes](https://cloud.githubusercontent.com/assets/1687213/20158112/815150ac-a6a6-11e6-8dce-07fef4484694.png)

**Comment by qooob** [comment]
Hi,

Just do right click on the icon to select it. It's default behavior across the theme to select using `right-click`. It hasn't changed since a long time.

**Comment by qooob** [comment]
I understand that right click is not obvious function.

What is your proposal in making it more usable but keeping sleek and beautiful?

**Comment by qooob** [comment]
Did the right click work for you?

**Comment by jmcguirl** [comment]
Yes it did.  Thank you.

**Comment by swelljoe** [comment]
Right click is not very intuitive, and it makes an appearance in a few places in Authentic...and all of those places have caused questions. But, in some of the places where right click is used, it mirrors desktop usage of right click (context menu in File Manager, for example), so it is OK in those places.

Here, I can't think of any common analog where a right click equals "select this thing for acting on it with the button below". It just isn't the way any popular software works. So, I think we're wrong on this one. Bringing back the checkbox would solve it.. I'm willing to believe there are other ways to solve it. But, it's definitely wrong right now, as it is a mystery meat UI.

**Comment by qooob** [comment]
I agree on that. I will find the way to improve it.

**Comment by jmcguirl** [comment]
Just a thought... How about some logic that allows successive clicks.  Like
most PC desktops. one click "select", two clicks "activate" (what single
click does currently)... with some sort of timing to define what two clicks
versus repeated single clicks are.
Suggested Visual queues: single click adds contrasting color to
"unclicked". double click wont need visuale queue... the action happening
should be sufficient.

Just my two cents...

Sincerely,

Joseph B. McGuirl Sr.
J & J Communications LLC
1.888.518.5091
WWW.JJCOM.COM

Please LIKE and FOLLOW us on Facebook <https://www.facebook.com/JJCOMVOIP>

Read our blog on the latest advice, best practices and tips for making the
most of technology. <https://www.jjcom.com/our-blog>

********************************************
The information contained in this e-mail is privileged and confidential
information intended only for the use of the individual or entity to which
it is addressed.  If you are not the intended recipient, you are hereby
notified that any use, dissemination, distribution, copy or taking action
in reliance upon this email is strictly prohibited.  If you have received
this e-mail in error, please immediately notify the sender and then delete
this e-mail in its entirety.
********************************************

**Comment by qooob** [comment]
Hi,

Well it might be but I would stand again double clicks in general. It's also unintuitive for the web apps.

I think I will just make sure that the checkbox is seen in somewhat beautiful way.

**Comment by qooob** [comment]
How about that:

http://rostovtsev.ru/pub/src/authentic/18.30b/improved_checkbox_select_logic_with_icon_container.webm

**Comment by jmcguirl** [comment]
I like it! But, how do you select one vhost and go directly to the configs?

Sincerely,

Joseph B. McGuirl Sr.
J & J Communications LLC
1.888.518.5091
WWW.JJCOM.COM

Please LIKE and FOLLOW us on Facebook <https://www.facebook.com/JJCOMVOIP>

Read our blog on the latest advice, best practices and tips for making the
most of technology. <https://www.jjcom.com/our-blog>

********************************************
The information contained in this e-mail is privileged and confidential
information intended only for the use of the individual or entity to which
it is addressed.  If you are not the intended recipient, you are hereby
notified that any use, dissemination, distribution, copy or taking action
in reliance upon this email is strictly prohibited.  If you have received
this e-mail in error, please immediately notify the sender and then delete
this e-mail in its entirety.
********************************************

**Comment by qooob** [comment]
Yeah, I realised it after making the video. 😂 Well, I think we will have to leave both. Icon and the check box that appears on hover.

**Comment by qooob** [comment]
I start to think that double click for action and single click for select is the solution.

**Comment by qooob** [comment]
Alright, I managed to make things work with click/double-click - very stable.

I don't know how intuitive it is but if it was me, I would first do left click, than right click and if it wouldn't work, I would do double-click.

I don't think there is a 100% proof solution as there will be definitely someone who would run into the confusion anyway.

I think the only fail proof solution here is to display data in modules in _table_, rather than using _icons_. For me it has always been more clear. Table is table. Fancy stuff is cool but not always clear. It would depend on the user.

Thanks for your recommendations.
