### ISSUE TITLE
Mail: Navigation doesn't know what its active menu item is

### ISSUE THREAD

**Issue by Himbern** [qooob/authentic-theme#577]
Currently on the latest theme (18.20) and Webmin (1.821) installed.
Ubuntu Linux 16.04.1
(Client side doesn't seem to make a difference)

When you try to navigate to any items within the Mail section navigation it doesn't change to the current active location on the navigation manu it just updates the Iframe but the active item remains as "Inbox".

![captureinbox](https://cloud.githubusercontent.com/assets/752755/20098375/63185776-a5ab-11e6-9114-2fa86b1a61eb.PNG)
![capturesent](https://cloud.githubusercontent.com/assets/752755/20098376/63196a08-a5ab-11e6-83ea-0b49691392ba.PNG)

It seems the secondary menu below the search box seems to work however.

![capturemanageitems](https://cloud.githubusercontent.com/assets/752755/20098493/103cf97a-a5ac-11e6-81c8-3344c195a97a.PNG)

**Comment by qooob** [comment]
Hi. I'm aware of this bug.

After 18.40 release, I'm starting working on mail. I will not be able to fix this small issue now but will make things just work when I finish new mail.

Please be patient.
