### ISSUE TITLE
Login webmin logo does not appear after update to 18.20

### ISSUE THREAD

**Issue by netizenuk** [qooob/authentic-theme#578]
OS: CentOS Linux 7.2.1511
Client: Windows 7, Browsers: Chrome + Firefox, both latest

Hello,
After going to v18.20 I noticed that the Webmin logo does not appear correctly in the login prompt.
See attachment pic.
The strange part is that I have another server and this is not happening to that server.
Any ideas?

![image](https://cloud.githubusercontent.com/assets/19958560/20136431/a7f614e8-a66c-11e6-8099-44af142b6c75.png)

I tried cleaning cache, force install but no luck. This seems to be related to webmin rather than the theme it self but not sure what to do since I did not make any changes to any webmin UI settings before.

N

**Comment by qooob** [comment]
No, no. I think it's the browser's issue. Try loading in incognito tag to double check.

In case it doesn't check log in and re-install the theme manually:

https://github.com/qooob/authentic-theme/issues/572#issuecomment-258248017

**Comment by netizenuk** [comment]
I had to re-install it and it then it worked.
Thank you.
