### ISSUE TITLE
Usermin theme messed up

### ISSUE THREAD

**Issue by benjamin-dk** [qooob/authentic-theme#579]
I think error started appearing after I logged out of a Usermin session. There were some error messages that I unfortunately did not have time to take note of. They were related to Perl modules.

The next time I tried to login to Usermin, Authentic Theme was messed up. Other themes work fine.

As the issue seems related to #567 I tried installing the latest version of AT 18.21 but no improvements.

Usermin restarted. Issue is present in at least Firefox and Chrome, Mac OSX.

Operating system 	Ubuntu Linux 14.04.2
Webmin version 	1.821
Virtualmin version 	5.04
Theme version 	Authentic Theme 18.20 and 18.21

To reproduce the issue:
Login to Usermin via the Webmin UI: Edit User > Login to Usermin

![usermin 1 690 on my server ubuntu linux 14 04 2 1](https://cloud.githubusercontent.com/assets/1723998/20210119/297deeb4-a7f8-11e6-9584-db890c2153e2.png)

**Comment by qooob** [comment]
Please reinstall the theme for Usermin:

https://github.com/qooob/authentic-theme/issues/572#issuecomment-258248017

**Comment by qooob** [comment]
..and restart `Usermin` and `Webmin` afterwards.

**Comment by benjamin-dk** [comment]
Missed that issue - thanks I will try that!
