### ISSUE TITLE
version 7 | table goes over the div... 

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#58]
hi,

better an image than anything ;-)

![Image of authtable](http://i57.tinypic.com/2gso77r.jpg)
Browser Chrome, this at 1920x1080 so it's even worse at lower resolutions
you just should auto enlarge the blank div to fit...

thank you!
best regards, happy holidays

p.s.: also, sorting of the table values doesn't work (eg. total quota used by domain, it doesn't sort correctly, but it didn't work even before..I remember that I reported it time ago...)
![Image of authtable2](http://i59.tinypic.com/e7idjq.jpg)

**Comment by qooob** [comment]
I will make a work around. As the table very big and there is no space to shrink, it will always stick out (as far as I understand).

I will release version 7.1.0 soon.

Happy New Year! ;)

**Comment by 7starsone** [comment]
thank you, happy 2015 to you too! :-) 
I'm waiting for the new Virtualmin version, about the new language change method and cache issue... hope they can help soon, not yet launched my customer service because of this, my clients are mainly euro (also UK but from other 6 countries...) anyway I think that Virtualmin and your theme are "mature" enough and you're on the right way ;-)
