### ISSUE TITLE
Theme: PAM authentication and login screen

### ISSUE THREAD

**Issue by stuartleeke** [qooob/authentic-theme#580]
* What is your server-side OS and its version? = Redhat 6.7 64bit
* What is your client-side OS, browser and its versions? Firefox 49.0.2 and IE 11.0.9600.184499
* What are the steps to reproduce the issue  = Install Webmin 1.8.20, install the latest theme, configure PAM Security ( and so webmin asks for username and then password as two seperate screens [ think it is pam_login.cgi ]
 ) stop and then start webmin.  Next login stage to login screen doesnt display properly

Screen shots as attached : 
![webminissue](https://cloud.githubusercontent.com/assets/23450512/20266755/80508610-aa6f-11e6-8a23-b96920ed3ca0.png)

**Comment by qooob** [comment]
I have exactly the same OS on debug machine.

Could you please tell me the steps to enable PAM so it works?

**Comment by stuartleeke** [comment]
Hi,

To configure PAM, we install an do some OS config ( All as root ) , then webmin config

First install required OS packages

yum -y install pam-devel.x86_64 perl-Net-SSLeay.x86_64

Compile Authen-PAM ( https://metacpan.org/release/Authen-PAM )

tar xf Authen-PAM-0.16.tar
cd Authen-PAM-0.16.tar
make
make install

Create file in /etc/pam.d/webmin with contents :

#%PAM-1.0
# description: Webmin Authentication
auth sufficient pam_ldap.so
auth include system-auth
account sufficient pam_ldap.so
account required pam_nologin.so
account include system-auth
password required pam_ldap.so
password include system-auth
session sufficient pam_ldap.so
session include system-auth

Install webmin and once up and running do the below :

[cid:image001.png@01D23F80.FB238AE0]

Then we select the below :

[cid:image002.png@01D23F80.FB238AE0]

Out miniserv.conf looks like below ( redacted where appropriate ) :

port=<redacted>
root=<redacted>/webmin/webmin-1.760
mimetypes=<redacted>/webmin/webmin-1.760/mime.types
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=<redacted>/webmin/log/miniserv.log
errorlog=<redacted>/webmin/log/miniserv.error
pidfile=<redacted>/webmin/log/miniserv.pid
logtime=168
ppath=
ssl=1
no_ssl2=1
no_ssl3=1
env_WEBMIN_CONFIG=<redacted>/webmin/config
env_WEBMIN_VAR=<redacted>/webmin/log
atboot=1
logout=<redacted>/webmin/config/logout-flag
listen=10000
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=60
syslog=1
session=1
premodules=WebminCore
server=MiniServ/1.760
userfile=<redacted>/webmin/config/miniserv.users
keyfile=<redacted>/webmin/config/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=gray-theme
passdelay=1
cipher_list_def=1
extracas=
no_sslcompression=
certfile=
no_tls1_2=
ssl_honorcipherorder=0
no_tls1=
no_tls1_1=
ssl_redirect=1
trust_real_ip=0
libwrap=
alwaysresolve=0
allow=<redacted>
pam_end=1
pam_conv=1
blockuser_time=
blocklock=
blockuser_failures=
no_pam=0
logouttime=<redacted>
utmp=
sudo=
pamany=
unixauth=<redacted>
shells_deny=/etc/shells
logouttimes<redacted>

Thanks you for your help on this,

Regards

Stuart

**Comment by qooob** [comment]
I'll try a bit later. If you meant to attach images, they aren't there. 😉

**Comment by stuartleeke** [comment]
Hi,

Apologies, it didnt seem to update images from the email.. oopppss.. uploaded separately now , so hopefully of some use :-)

**Comment by qooob** [comment]
Wow,

I seem to reproduce it. It looks really ugly. I'll try making it great in 18.30..

Working...

**Comment by qooob** [comment]
I manged to rebuild login page for PAM.

I just wanted to know, why are you using it? What is the point?

**Comment by qooob** [comment]
It will be available in 18.30. 

Thanks for reporting.
