### ISSUE TITLE
The latest version for Usermin Authentic Theme, 17.20 or 18.20

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#581]
I use the latest version of Authentic Theme 18.20 but Usermin indicates 17.20 version.... is this correct? I think it is a bug....  please advise

![ddd](https://cloud.githubusercontent.com/assets/7549566/20316880/b4990d9c-ab5b-11e6-8e0a-2c10169fd177.jpg)
![ddd2](https://cloud.githubusercontent.com/assets/7549566/20316879/b497e606-ab5b-11e6-8748-75fb78a00075.jpg)

**Comment by qooob** [comment]
It means it hasn't been updated. The latest is 18.20. Update it manually for Usermin.

**Comment by sz00gun** [comment]
In Authentic Theme on the bottom, was a button: install manually... or something like this,... I have done it.... and that's it. 

Do you prefer install theme manually via webmin/install modules ?

**Comment by qooob** [comment]
Via `Webmin->Usermin Configuration->Themes`

**Comment by sz00gun** [comment]
I didn't update the theme manually, I'm digging a problem, eg. on Debian I have the same version 17.20, but no indication about newest version...:

![debian](https://cloud.githubusercontent.com/assets/7549566/20458157/f875ff7a-ae94-11e6-921c-a831ff66794e.jpg)

**Comment by qooob** [comment]
Either enable automatic updates in theme settings or update the theme manually. There were multiple changes.
