### ISSUE TITLE
Theme: Save does not save manual forms in background calls

### ISSUE THREAD

**Issue by htmltiger** [qooob/authentic-theme#583]
Hi,

I have updated theme to latest update 18.20 but i dont know if its webmin issue or theme issue as both updated recently

Ubuntu 14.10 lts with latest webmin 1820
Servers > Apache > Existing vhosts > pick any server > Edit Directive

make any changes and hit "Save" but will not change the file, notification says changes saved.
it will only save if you hit "Save and Close"

Love the theme!

Thanks.

**Comment by qooob** [comment]
Hi,

That has to be fixed last release. I will take a closer look.

Thanks for reporting.

**Comment by qooob** [comment]
True. Fixed in 18.30.

Thank you very much for reporting! ;)
