### ISSUE TITLE
Theme: top right links need some padding - "Apply ChangesStop ApacheSearch Docs.."

### ISSUE THREAD

**Issue by htmltiger** [qooob/authentic-theme#584]
need some padding, the following css rule fixes it:

#headln2r .ui_link { padding-right: 8px }

**Comment by qooob** [comment]
Hi,

In case they look the same as on the picture - it's intended.

![screenshot from 2016-11-19 20-31-36](https://cloud.githubusercontent.com/assets/4426533/20457219/5419820a-ae97-11e6-857f-71f9db000ae4.png)


You can always use your own CSS extensions for the theme, that is the reason why it's for.

**Comment by htmltiger** [comment]
Thanks, I have just enabled table header icons to fix it
