### ISSUE TITLE
Running Webmin Under Nginx (requires full references)

### ISSUE THREAD

**Issue by oleg-krv** [qooob/authentic-theme#585]
Running Webmin Under Nginx ([for example](https://github.com/webmin/webmin/issues/420)) requires full references in the menu:
now so:
`<a target="page" href="acl/"> Users Webmin</a>`

need to do:
`<a target="page" href="https://site.web/subfolder/acl/"> Users Webmin</a>`

It is necessary to use nginx as a frontend to webmin. It is more convenient than opening a port.

**Comment by qooob** [comment]
What do you see in Gray Theme? Did you set `webprefix` in Webmin config?

**Comment by oleg-krv** [comment]
Sorry. That's my fault. I looked at the source code - and there found the prefix. In the configuration file webmin this line there is no default.
