### ISSUE TITLE
Theme: How to disable notifications

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#586]
I am not a fan of the Notification system, I have ended up with pages of notifications that I have actioned (I assumed clicking on a notification would remove it from the panel)  but it does not .. I looked through the theme settings and can not find a setting to remove this function can you add one ?

**Comment by qooob** [comment]
Hi,

Do you want to disable right slider?

**Comment by JimTR** [comment]
Yes thats right and the notification on the tab  example :- (2)  Virtualmin

**Comment by qooob** [comment]
In theme settings. Set Notifications to off.

**Comment by Sopor-** [comment]
@qooob I also want to turn off notification but i can't find any notification i can set to off. The only thing i have found that have to do with the notification is `Show notifications tab -  Yes No`. I don't know if this is the settings you mean?

**Comment by qooob** [comment]
Yes, go to Theme Configuration, find `Enable slider` and switch it to `Yes`,

**Comment by Sopor-** [comment]
But the slider is already set to Yes. I will do a new report because here is some kind of bug when i change notification to no. It will still show those red numbers so it will not disable it, it will only hide it as it says in the text.

**Comment by qooob** [comment]
I actually meant `No` :D

Please provide the screenshot, as I don't exactly understand what is not working.

**Comment by Sopor-** [comment]
See #673
