### ISSUE TITLE
CSF Configurations button non visible

### ISSUE THREAD

**Issue by netizenuk** [qooob/authentic-theme#588]
Hello,

After updating CSF and authentic theme to the latest versions I realised that the CSF fw configuration button was not visible at all. I found that I had to DISABLE the custom style within the CSF configuration 
`
(via command line  >> STYLE_CUSTOM = "0") as this was enabled (not by me).
`
After that it worked, however my question here is... will this affect the styling imposed by your theme anyhow..or it is OK to leave the above setting disabled?

Thank you.

**Comment by qooob** [comment]
Configuration button defaults to the default place in Webmin - table header.

**Comment by qooob** [comment]
Look up at the table's left. You will find it there.
