### ISSUE TITLE
File Manager: Archive extraction prompt for overwriting existing files

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#589]
The latest theme has a bug, trying unzip an archive files aren't overwritten. There is a missing window: 

![clipboard02](https://cloud.githubusercontent.com/assets/7549566/20633951/8f346e62-b343-11e6-87aa-ebde6be63f0e.jpg)

That would be a very good facility if during unziping the window "Target conflic" appears.
Ps. there is a mistake in "conflic" -> "conflict" ;)

Ps. .tgz overwrites files which is OK, but .zip not to ;(

however "Target conflict" window should informs about overwriting files anyway IMHO ;)

Please advise

**Comment by qooob** [comment]
I think making such _facility_ wouldn't be that easy.

I have made sure that every decompression (`unzip/unrar/7z` and etc) will overwrite existing files, just like `tar` did.

It will be working such way in 18.30.

Thanks for reporting!

**Comment by sz00gun** [comment]
Ok, thanks

However unzip not working on my server. Did you check it recently too? Not sure, but it worked in previous version... I think.

**Comment by qooob** [comment]
I checked it. It works. Make sure that you have `unzip` command on the path.

**Comment by sz00gun** [comment]
Make sure that you have unzip command on the path ?? What do you mean? Sorry

**Comment by qooob** [comment]
Running `unzip` from command line? What is the output? If it's not found then install it.
