### ISSUE TITLE
Switch to script async

### ISSUE THREAD

**Issue by XhmikosR** [qooob/authentic-theme#596]
Might require some internal changes, but ideally you should move at least all JS to the bottom of the HTML before the closing `body` tag. If possible, apply the `async` attribute so that requests do not block the page render.

**Comment by qooob** [comment]
Where do you see non `async`? Single frame mode?

**Comment by XhmikosR** [comment]
Everywhere I just check the page source and see this for example:

```html
<script src="/unauthenticated/js/postinit.min.js?1830" type="text/javascript"></script><script>___authentic_theme_footer___ = 1;</script>
<script src="/unauthenticated/js/content.min.js?1830" type="text/javascript"></script>
```

**Comment by qooob** [comment]
It's fine.

Scripts are loaded in async mode by default. Nothing makes things waiting. 

Why do you think that scripts must be run at the end?

**Comment by XhmikosR** [comment]
How are they being loaded in async mode? I don't see the `async` attribute so this means they load blocking.

**Comment by qooob** [comment]
No. JavaScript all loads links all at once.

Are you sure you not mixing it with _async_ in `.ajax()` calls?

**Comment by qooob** [comment]
Better to say everything loads at once upon request.

**Comment by qooob** [comment]
It's not PHP or Perl.

**Comment by qooob** [comment]
..or you mean `<script async>` attr?

**Comment by XhmikosR** [comment]
At once doesn't mean async. Unless you set the `async` attribute scripts are blocking.

https://css-tricks.com/async-attribute-scripts-bottom/

**Comment by qooob** [comment]
Did you test it? Did it cost an effort??

**Comment by XhmikosR** [comment]
Yeah, I thought it was clear I meant the `async` attribute.

See also https://www.html5rocks.com/en/tutorials/speed/script-loading/

It's definitely worth it in my experience.

**Comment by 7starsone** [comment]
it costs that... to render the page you need to wait for the js execution...

**Comment by Real-Gecko** [comment]
Authentic...Authentic never changes :D :D :D :D

**Comment by XhmikosR** [comment]
If you move all inline JS to external files, you can use `async` easier. Just make sure there are no dependencies between the scripts, because `async` does **not** honor the script order (that's the idea; load scripts as soon as possible without blocking the page load).

**Comment by qooob** [comment]
@7starsone I know what you're talking about. I will test it later but my feeling right now, that it will not change anything (speed-wise). The complexity of the theme is very high and changing such things might end-up in breakge.

@Real-Gecko Sasha, chill-out! ;)

**Comment by XhmikosR** [comment]
@qooob: That might be true indeed. But it's the only proper way to load scripts without blocking.

Everywhere I've done this, the gains are huge. Next step would be to load CSS differently but that's for another time.

**Comment by qooob** [comment]
@XhmikosR It will be possible in single frame mode, right now there are limitations.. but I will take a look.

**Comment by XhmikosR** [comment]
Note that alternatively you can sort of make your own small loader or use an existent loader library for this. Might be worth in your case using something like that.

**Comment by qooob** [comment]
@XhmikosR It would be possible if it was not super complex `WebminCore` and the way it's structured at the moment. In some parts of the code I on purpose made scripts wait for certain things, to provide good UI.

At the moment theme is super fast on my prod server (blazingly fast). It just flies, literally. I don't see why it should be faster. If looking from 18.30, I could make it faster 2x times by putting extra gigantic efforts in it - _**I would do it**_. But if we're talking about 5% gain. It doesn't worth it!

**Comment by XhmikosR** [comment]
I agree, from a maintainer's point of view.

Just give it a go and balance the pros and cons.

**Comment by qooob** [comment]
@XhmikosR Did you see the code? It's complex even for me to understand few weeks after. Restructuring the whole thing? I will only do it _if/when_ we switch to single frame mode and write things from scratch a bit more properly.

Alright, thanks for advising!
