### ISSUE TITLE
Usermin - displaced pop-out window for links/emails

### ISSUE THREAD

**Issue by Stinkykiller** [qooob/authentic-theme#598]
* What is your server-side OS and its version?
VPS, Centos 7.2
* What is your client-side OS, browser and its versions?
Win7Pro, Firefox
* What are the steps to reproduce the issue
Every time when i want to compose email as HTML and use "Link" option, the pop-out window will be placed on the upper part of the browser window.
1. Before i use "Link" option
![usermin_popout_01](https://cloud.githubusercontent.com/assets/8083453/21005611/c0db1c44-bd35-11e6-8bf8-001347f320e8.jpg)
2. Once i highlight the text and press "Link". You can see the position of pop-out window and how bumped entire page up.
![usermin_popout_02](https://cloud.githubusercontent.com/assets/8083453/21005609/c0d962f0-bd35-11e6-8242-f6d3982e1482.jpg)
3. This i just discovered when using right-click on highlighted text (cut/copy/paste). Same as with 2. the browser window bounced up.
![usermin_popout_03](https://cloud.githubusercontent.com/assets/8083453/21005610/c0d98960-bd35-11e6-8295-d39edbcd5a24.jpg)

When you have many things to link, copy or paste it start to be annoying as every time you must scroll up, set everything and then back down to the main text.

Extra: I think the option to link is used in same frequency or even more than cut/copy/paste and it could be integrated with right click on highlighted text.

**Comment by qooob** [comment]
Hi,

We should all get hottest mail possible on next either 18.40 or 19.00 release.

I will rework mail from scratch.

I will not look in to this issue right now, sorry pal.

**Comment by Stinkykiller** [comment]
Speaking from time perspective are we talking here about few weeks or months?

**Comment by qooob** [comment]
Months, but my plan to star working on it in January. It depends on how it goes. If I work on the project I just do it. The whole day. It might be by the end of the January or February.
