### ISSUE TITLE
Incomplet hostname - Realtime Monitoring (Netdata)

### ISSUE THREAD

**Issue by bogdanpuica** [qooob/authentic-theme#599]
Incorect link Realtime Monitoring (Netdata)
![ss](https://cloud.githubusercontent.com/assets/17913749/21010617/bc638708-bd55-11e6-9a6c-a8da0c0c91b7.png)

**Comment by qooob** [comment]
Ok.

But you can tweak it in settings. I will check that it shows the full hostname

**Comment by qooob** [comment]
Will be fixed in 18.31

**Comment by qooob** [comment]
18.31 is out, please upgrade.
