### ISSUE TITLE
authentic-theme-latest.wbt.gz not found

### ISSUE THREAD

**Issue by XDevASM** [qooob/authentic-theme#604]
Hi,
I can not update the theme because authentic-theme-latest.wbt.gz not exits .
https://github.com/qooob/authentic-theme/releases/download/18.30/authentic-theme-latest.wbt.gz

System: Debian 7
Webmin version: 1.821
Current theme version: 18.20

Thank you

**Comment by qooob** [comment]
Hi, just update manually it's changed and not back-compatible.

https://github.com/qooob/authentic-theme/releases/download/18.31/authentic-theme-18.31.wbt.gz
