### ISSUE TITLE
Typo "loacal"

### ISSUE THREAD

**Issue by XhmikosR** [qooob/authentic-theme#605]
Also, I think this sentence could be better: "By using local fonts default is not loaded, which will result in faster theme load"

Maybe: "By using local fonts, the default one is not loaded, which will result in faster theme load."

**Comment by qooob** [comment]
On Sat, Dec 10, 2016 at 6:56 PM, XhmikosR <notifications@github.com> 
wrote:
> By using local fonts, the default one is not loaded, which will 
> result in faster theme load

Sure, thanks.

**Comment by qooob** [comment]
Thanks.

https://github.com/qooob/authentic-theme/commit/897b12baa0040572786601cae53bb911d2690cc0
