### ISSUE TITLE
Theme: Automatic update is broken

### ISSUE THREAD

**Issue by wiserweb** [qooob/authentic-theme#606]
In latest release, the 'download' button in virtualmin points to (https://github.com/qooob/authentic-theme/releases/download/18.30/authentic-theme-18.30.wbt.gz) which gives a 404.

The 'update' button also doesn't appear to work for 18.31. It is likely that these two are related issues, i.e. the script can't find the update package due 404.

**Comment by qooob** [comment]
Hi,

I forgot that it was hardcoded in 18.20 as part of the transition.

Please just upgrade the theme manually.

**Comment by qooob** [comment]
Starting next releases the automatic update will work for both Webmin and Usermin.

**Comment by qooob** [comment]
New Webmin release is coming very soon, that will include latest Authentic Theme 18.31.

**Comment by PartisanEntity** [comment]
I have this same issue, after clicking the update button webmin looks like it is updating, but then when the window loads again it is still on Authentic Theme 18.20.

Can you please share instructions for manual update of the theme?

**Comment by capfive** [comment]
Thanks for the response. Will we just let webmin do it's thing when this update happens? Or will we have to uninstall the custom them and switch to the core authentic one?

@PartisanEntity go to the Webmin panel and go to the following

Webmin:
Webmin configuration >> Webmin themes >> Install theme

Then click "From ftp or http URL" and put this link in [https://github.com/qooob/authentic-theme/releases/download/18.31/authentic-theme-18.31.wbt.gz]

Usermin:

Usermin configuration >> Usermin themes >> Install theme

Then click "From ftp or http URL" and put this link in [https://github.com/qooob/authentic-theme/releases/download/18.31/authentic-theme-18.31.wbt.gz]

The same theme is used for both Webmin and Usermine 👍 

Enjoy!

**Comment by qooob** [comment]
@capfive yes, this is correct to install it.

There is no reason to do anything after Webmin update. It will just work.
