### ISSUE TITLE
From 18.30 can't use it any more in Chrome 

### ISSUE THREAD

**Issue by EmBitz** [qooob/authentic-theme#609]
Since update 18.30 I can't use webmin anymore in Chrome. It endless waits to end with a failure/memory error.  Same with 18.31. Firfox is ok, clearing caches etc didn't help. It hangs.  

I switched to another theme to bypass this problem.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/606

Hard clear browser's cache and restart Webmin. Install theme using `Webmin Configuration->Themes`.
