### ISSUE TITLE
Theme: Doesn't work in Chrome after update 18.31

### ISSUE THREAD

**Issue by EmBitz** [qooob/authentic-theme#610]
After updating to 18.30 this theme is causing Chrome to hang (endless wait) and eventually Chrome quit with an error. 

- Firefox is OK 
- All other themes are OK with Chrome so I switched to "Gray frame"

I have the problem also with 18.31. 
Can I go back to the version before 18.30 in a simple way??

**Comment by qooob** [comment]
Did you try Chrome Incognito mode? One of your extension could cause this issue.

Please open console and see for errors.

**Comment by qooob** [comment]
What OS are you using?

**Comment by qooob** [comment]
How did you install 18.31?

**Comment by EmBitz** [comment]
- Using win7 x64 
- The problem is in both 18.30 and 18.31 (version before 18.30 was ok)
- Chrome error "Aw, snap, Google Chrome ran out of memory while trying to display this webpage" 
- I can't use the Chrome dev (F12)
- Updated theme with the button on the frontpage (beside the theme name)

**Comment by EmBitz** [comment]
Yes, it works in Incognito mode. I will look further.

**Comment by EmBitz** [comment]
Yip, got it.
 
The CanvasFingerprintBlock is the problem.

Thanks for your time!!! you may close it.
