### ISSUE TITLE
Theme: Forced scroll down in Mailman module

### ISSUE THREAD

**Issue by nodo50** [qooob/authentic-theme#613]
Hi, after upgrade from 18.20 to 18.31 I saw a problem when going to Services - Mailing Lists - Manage. It loads the Mailman admin interface into the Virtualmin interface. Then, if you go to "Membership Management..." the page automatically scroll down and lock there. Is not possible to scroll up to access to the options menu or select the first addresses in the suscribers list.

I don't see the issue in others sections of the Mailman web admin.

If you click on any link the browser show the pop-up warning about to leave the page.

The issue is not present if you load the Mailman web interface outside of Webmin using the link in the list name or using the link like https://example.org:10000/virtualmin-mailman/unauthenticated/admin.cgi/listname/members

Tested with Webmin 1.821, Virtualmin 5.05 Pro and Authentic Theme 18.31, on a server with Debian 7.
Client software: Mac OS X 10.11.6 + Chrome 55.0.2883.87 (64-bit) + Firefox 45.6.0 ESR

**Comment by nodo50** [comment]
Tested too with Windows 10 + Chrome 54.0.2840.99 + Firefox 50.02

**Comment by qooob** [comment]
Hi,

Where do I get the mailman? I will try to reproduce it tomorrow and fix it.

**Comment by qooob** [comment]
You could also try to add thus modules to excludes on theme settings.

If you open right frame source, what is the page's URL?

**Comment by nodo50** [comment]
the frame URL is https://host.example.org:10000/virtualmin-mailman/admin.cgi/listname/members

It is a module from Virtualmin, in Debian is the package webmin-virtualmin-mailman (version 6.3)

**Comment by qooob** [comment]
OK. Did you try to add mailman to exclusion list?

**Comment by nodo50** [comment]
Yes, I tried it wih no success, same result. I added to exclude list the module, calling it virtualmin-mailman and mailman. Then clear cache in theme settings, empty browser cache and restart webmin.

Could it be that he is not really being excluded? The HTML style is a few different when you load the Mailman interface outside Webmin with the direct link https://example.org:10000/virtualmin-mailman/unauthenticated/admin.cgi/listname
Inside Webmin the right frame is loading https://example.org:10000/virtualmin-mailman/admin.cgi/listname

**Comment by qooob** [comment]
I'm exactly picking on mailman right now. When I click that `Membership Management`, it just opens things in the new window.

**Comment by qooob** [comment]
Have a look what I got: http://rostovtsev.ru/pub/src/authentic/18.31-patch/mailman_613.webm

**Comment by qooob** [comment]
Stay tuned, let's have it sorted out, before next Webmin release.

**Comment by qooob** [comment]
Actually it's not important bacause exclusion function didn't work correctly. Let me fix it and I will ask you to change one `.js` file, reset cache and try again.

**Comment by nodo50** [comment]
OK, I'm stay tuned, thanks.

**Comment by qooob** [comment]
Please download `init.min.js` and place it into your theme installation and make sure to hard reset cache in browser. If you're using Chrome, just open console, then hover and hold reload button (usually top let part of the screen, near URL bar) and then select `Epmty cache and hard reload`.

It should just work after all. Don't forget to add your module to exclusion list.

**Comment by qooob** [comment]
[init.min.js](https://github.com/qooob/authentic-theme/blob/1a49e317ebc80e42608f5517dd4102cf15ff7e23/unauthenticated/js/init.min.js)

**Comment by nodo50** [comment]
Thanks!, it worked. I replaced /usr/share/webmin/authentic-theme/unauthenticated/js/init.min.js with the new one and maintain virtualmin-mailman in exclusion list.

**Comment by qooob** [comment]
Good to know. :+1: 

However, I don't understand why it works without exclusion on my side and doesn't on your's.

What do you have in the footer on that URL `/virtualmin-mailman/admin.cgi/listname/members`?

Do you have this:

```JavaScript
<script src="/unauthenticated/js/postinit.min.js?1831"></script><script>___authentic_theme_footer___ = 1;</script>
<script src="/unauthenticated/js/content.min.js?1831"></script>
```

**Comment by nodo50** [comment]
Yes, I have the same

`<script src="/unauthenticated/js/postinit.min.js?1831"></script><script>___authentic_theme_footer___ = 1;</script>`
`<script src="/unauthenticated/js/content.min.js?1831"></script>`

**Comment by qooob** [comment]
I think it's because you're using it as _unauthenticated_. How did you set it up?

**Comment by nodo50** [comment]
I think I done nothing special, but is a server installed 8 year ago and upgraded from Debian 4.
I see Virtualmin adds the following rules in Virtualhost.

`RedirectMatch /cgi-bin/mailman/([^/]*)(.*) https://example.org:10000/virtualmin-mailman/unauthenticated/$1.cgi$2`
`RedirectMatch /mailman/([^/]*)(.*) https://example.org:10000/virtualmin-mailman/unauthenticated/$1.cgi$2`

Could be related?

**Comment by qooob** [comment]
Yes, very likely.

Anyway. It seems to be working fine now.

Thanks for reporting.

**Comment by nodo50** [comment]
here my Mailman module config, if you want to check
![mailman-module-conf](https://cloud.githubusercontent.com/assets/11536527/21181470/67f52106-c1fe-11e6-806a-2681b5ed6ec8.png)

**Comment by qooob** [comment]
I have the same one.
