### ISSUE TITLE
Problem after manual update

### ISSUE THREAD

**Issue by acosonic** [qooob/authentic-theme#614]
Hm, am I missing something or?

After manual theme update I'm getting:

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.690 Date: Tue, 13 Dec 2016 20:58:35 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

Undefined subroutine &WebminCore::isd called at /usr/share/usermin/authentic-theme/authentic.pm line 10.

while clicking on login to usermin for some user.

**Comment by qooob** [comment]
You must also install the theme manually for Usermin and restart it.

**Comment by acosonic** [comment]
Hm, ok, thanks.

Perhaps Virtualmin team should be instructed to improve theme installation process.
How can we do that? Maybe via IRC or they use some bug report?

**Comment by qooob** [comment]
This considered to be basic debug level knowledge. I would just recommend to wait/rely on .rpm/.deb repo packages updates.

However, I have fixed Webmin/Usermin automatic updates and automatic updates  will work fine again after 18.31 is installed onwards.

Sorry for any cause incontinence.

Always glad to help. 😉
