### ISSUE TITLE
Theme: In Virtualmin user mode link for Webmin modules is missing now?

### ISSUE THREAD

**Issue by applejack1923** [qooob/authentic-theme#615]
Hi

A virtual servers admin cannot access the Webmin modules as it no longer appears in the menu.

I was only told this by the client as I only have one who uses it but I ran some tests using a prior install and it is definitely the upgrade to Authentic which has caused the issue.

On my test machine I went from version 18.10 to 18.31 but my client has been using this regularly and I always update Authentic etc when they come out so I suspect it is from 18.30+

**Comment by qooob** [comment]
They were moved to the switch. Can you please provide a screenshot?

**Comment by applejack1923** [comment]
Re: They were moved to the switch ??? Meaning ???

Before they were located below Services see enclosed.

![vm](https://cloud.githubusercontent.com/assets/1639744/21188725/34bc08e8-c214-11e6-9161-cafd7ee2985f.jpg)

**Comment by qooob** [comment]
Yes, Jamie and I we agreed to have it only under Webmin switch.

It doesn't suite you?

**Comment by applejack1923** [comment]
A right now I understand. Personally I don't really mind since at the moment I rarely let clients have such privileges but I think it would be easier for a client to have all services they can access under one tab as otherwise it just adds an additional layer of complexity / potential confusion and so even do away with having the Webmin tab when a VS admin / owner is logged in. The moto when dealing with clients "keep it simple !!!"

**Comment by qooob** [comment]
I agree on simplicity but I don't see why that would be complicated. It just makes thinks more clear.

Let's keep it this way.
