### ISSUE TITLE
Theme: Icons' links can't be entered on click

### ISSUE THREAD

**Issue by darren4294** [qooob/authentic-theme#617]
* server-side OS and its version?
CentOS Linux 6.8

* client-side OS, browser and its versions? 
Windows 10 1607, Google Chrome Version 55.0.2883.87 m 

* What are the steps to reproduce the issue
After login, Click Servers, BIND DNS Server.  In the "Existing DNS Zones" area none of the links for the zones work.  Reverting back to old webmin theme and following the steps above allows the links to work.

Nice job with the them! Please keep up the excellent work.

**Comment by qooob** [comment]
In 18.3x the double-click was added to enter the target. This is how it works at the moment. I thought it would be more or the less intuitive. :disappointed:

**Comment by qooob** [comment]
To prevent confusion for users version of the theme 18.32 will have one time message that would explain how to manipulate targets in `Icons Mode`.

Example:

![explanations_for_icon_mode](https://cloud.githubusercontent.com/assets/4426533/21651155/9e7b3bf0-d2b8-11e6-9a34-e870e58d31b0.png)
