### ISSUE TITLE
Problem using File manager since 18.31 update (error in file-manager-lib.pm)

### ISSUE THREAD

**Issue by ZalemCitizen** [qooob/authentic-theme#618]
Hello,

Since last update (18.29 -> 18.31 applied manually since automatic update was not working)
File Manager no more works.
- 4 different servers
- all 4 are ubuntu 14.04 lts kept up-to-date

File manager loads and chrome and Firefox consoles report : 
"Undefined subroutine &extensions::get_selinux_command_type called at /usr/share/webmin/authentic-theme/extensions/file-manager/file-manager-lib.pm line 113"

All further action in file manager won't work then

Can you help ?

**Comment by qooob** [comment]
You apparently made `git pull` instead of using the package from Releases.

**Comment by qooob** [comment]
The `git pull` is only suitable for Webmin 18.30+.

**Comment by ZalemCitizen** [comment]
Well, I'm not sure how I did...
So I only have to replace authentic-theme dir by the one I download from release package ?

**Comment by qooob** [comment]
Just install it using recommendations on main page of the repo.

**Comment by qooob** [comment]
**How to install Authentic Theme?**

_Webmin_

To install Autentic Theme from repository, just clone it into your wherever Webmin binary folder (libexec) is. After that, you must rename authentic-theme-master directory to authentic-theme to make the theme work properly. Besides, you could just download the theme directly and install it using Webmin:

`Webmin->Webmin Configuration->Webmin Themes->Install themes->From uploaded file`

From uploaded file - [link](https://github.com/qooob/authentic-theme/releases/download/18.31/authentic-theme-18.31.wbt.gz)
