### ISSUE TITLE
Virtualmin: Backup schedule chooser doesn't work

### ISSUE THREAD

**Issue by garas** [qooob/authentic-theme#619]
When trying to add complex schedule for backup, popup window opens, but confirming changes fails.

* Go to Virtualmin > Backups and Restore > Scheduled Backups.
* Add new or edit existing backup schedule.
* Under "Schedule and reporting" choose "Complex schedule".
* Click button to open popup `/virtual-server/cron_chooser.cgi`.
* Change any setting, error console gets `TypeError: form.special_def is undefined` error.
* Button "OK" doesn't work, parent window doesn't update.

Using "Virtualmin Framed Theme" works as expected.

Theme 18.31 and Webmin 1.821 versions installed.
Browser Firefox 51

**Comment by qooob** [comment]
Hi,

It's confirmed.

I will try to make a patch within few days.

**Comment by qooob** [comment]
Actually, it works if you hit submit button?

**Comment by garas** [comment]
Yes, it works with _Submit_ button. So the fix is probably to remove one of button, leaving working one.

"Virtualmin Framed Theme" has only _OK_ button.

Error console error happens in both themes, so probably unrelated.

**Comment by qooob** [comment]
Hmm. I'll take a look.
