### ISSUE TITLE
Theme: Awstats Configuration makes left menu reload incorrectly

### ISSUE THREAD

**Issue by netizenuk** [qooob/authentic-theme#620]
Example:
- Host has multiple servers inside so in the left menu -when logged in as root- you see all of them.
- Selecting for example the 5th server (from the left) and then going to menu item (i.e Awstats Reports) works. Then if you go to make changes to the configuration of the Awstats and save, the left menu refreshes itself *however* it goes automatically to the 1st server on the list.
- As the right screen stays the same, you have the impression that you're still working on that server (5th) however this is not the case. You are actually editing now the Awstats of the 1st server!
- The only way to alleviate this is by *constantly* selecting the 5th server on the left and then the Awstats configuration.

Is this normal? I don't remember this happening before.
Am I missing something maybe?

Thank you.

**Comment by qooob** [comment]
Hi,

Which module are you talking about? Is it _Virtulamin_ or _Servers Index_?

**Comment by netizenuk** [comment]
Servers Index? What's that? You confused me....

- Login to the host (which has webmin+virtualmin) as root.
- In the host there are several Virtual Servers (on different plans etc) and you can see them via the pull-down menu (left upper corner).
- Let's say that the first Virtual Server's domain is mydomainA.com and below this mydomainB.com etc
- You select any other than the 1st in order to work with it.
- All ok so far.
- As soon as you select it, on the right hand side you have the server details (the summary)
- You then go (on the left) to "Logs and Reports" >> "Awstat Report". It gets displayed.
- You then go (on the left) to "Awstats Configuration". HERE is where the problem starts. >>
- You see the current server Awstat configuration BUT if yoy pay attention the LEFT MENU has been refreshed and now it has the 1st server selected (instead of the one you were before).
- Say you make a change to the Awstat Configuration and click SAVE.
- You are now effectively looking the Awstat Configuration of the FIRST Virtual Server and not the the configuration of the server you were working on.

Makes sense? Can you replicate it?

**Comment by qooob** [comment]
Hi,

Yes, I can confirm it. I will try making a patch for 18.31 tonight.

**Comment by qooob** [comment]
You will see when it checked. Be patient please.

**Comment by netizenuk** [comment]
Thank you for the update.
Please note that I haven't tested the bug in other sections of the panel so might want to test that as well.
Merry Christmas!

**Comment by qooob** [comment]
I remember it was also extra reloaded in some other places of VM but never changed the left side incorrectly. I'll try to figure this out.

**Comment by qooob** [comment]
Merry Christmas and Happy New Year!

**Comment by qooob** [comment]
Please git it a try.

**Comment by netizenuk** [comment]
I changed manually only the files under /webmin/ and I think it works OK now.
Can you confirm that this is also needed under /usermin/ ?

/usr/libexec/usermin/authentic-theme/unauthenticated/js/postinit.js
**/usr/libexec/webmin/authentic-theme/unauthenticated/js/postinit.js**

and

/usr/libexec/usermin/authentic-theme/unauthenticated/js/postinit.min.js
**/usr/libexec/webmin/authentic-theme/unauthenticated/js/postinit.min.js**

Thank you

**Comment by qooob** [comment]
Yes. It's needed in Usermin as well.
