### ISSUE TITLE
Theme fails to load in Seamonkey 2.40 Linux

### ISSUE THREAD

**Issue by Slugracing** [qooob/authentic-theme#621]
I just loaded Authentic Theme 18.31 in Virtualmin and I am now faced with a spinning wheel that never stops. Doesnt matter what I choose on the left (Virtualmin/webmin) I get nothing but the spinning wheel.

I tried this theme in Chrome and Firefox and it works fine, so its just Seamonkey that its not working in.

Thanks

**Comment by qooob** [comment]
Hi, 

I don't officially support SeaMonkey.

What is the error in console? Did you try incognito mode? Old cache or browser's extensions can cause issues.

**Comment by Slugracing** [comment]
Hi
Only extensions is weather and enigmail, so I think that should be ok. Cache cleared.
Console error is this

Timestamp: 23/12/16 10:30:38
Error: SyntaxError: missing ; before statement
Source File: https://vader.shirehosting.com.au:10000/unauthenticated/js/content.min.js?1831
Line: 6, Column: 128575
Source Code:
n}t___wi.location.href=$(this).find("a").attr("href")});let DELAY=340,clicks=0,timer=null;$("body").on("click",'.icons-r


Timestamp: 23/12/16 10:30:38
Error: TypeError: window.page.f__g is not a function
Source File: https://vader.shirehosting.com.au:10000/unauthenticated/js/parent.min.js?1831
Line: 6

Timestamp: 23/12/16 10:30:42
Error: TypeError: f.data(...) is undefined
Source File: https://vader.shirehosting.com.au:10000/unauthenticated/js/parent.min.js?1831
Line: 6

**Comment by qooob** [comment]
Did you try latest SM 2.46?

**Comment by Slugracing** [comment]
No I havent, I'll give it a go and report back

**Comment by Slugracing** [comment]
Ok, SM 2.46 was just made available from repos and with a large smile I can confirm that it works.

Thanks for your effort.

**Comment by qooob** [comment]
Great to hear! Merry Christmas!
