### ISSUE TITLE
Error after Webmin Update

### ISSUE THREAD

**Issue by FabianGoettl** [qooob/authentic-theme#622]
Updated Webmin to 1.821, Usermin is at Usermin 1.701. I get the following error in https://mydomain:20000:

Undefined subroutine &WebminCore::get_raw called at /usr/share/usermin/authentic-theme/authentic.pm line 170.

Disable authentic_theme, deleted old version of authentic_theme, installed new version 18.31, enabled again. Error stays the same and is not given in the default themes.

**Comment by qooob** [comment]
Hi,

You must install latest theme 18.31 for both Webmin and Usermin.

It's caused because of caching, I think.

**Comment by FabianGoettl** [comment]
Thanks. Fixed the problem.
