### ISSUE TITLE
Theme: Favorites file (favorites.json) might have to get garbage data

### ISSUE THREAD

**Issue by mateusz-szafraniec** [qooob/authentic-theme#623]
System/Webmin language: PL-UTF8

When something from Webmin menu is added to favorites, and it contains national character like "ś", "ó" etc, it causes Webmin crash, displaying blank page:
For example: Dislay system log ("Wyświetl log"):
```
HTTP/1.0 500 Perl execution failed
Server: MiniServ/1.820
Date: Thu, 29 Dec 2016 10:21:22 GMT
Content-type: text/html; Charset=iso-8859-1
Connection: close
<h1>Error - Perl execution failed</h1>
<pre>Wide character in syswrite at /usr/share/webmin/miniserv.pl line 3083.
</pre>
```

Content of favorites.json:
`{"favorites":[
    {
        "link": "/syslog/save_log.cgi?oidx=0&omod=fail2ban&view=1",
        "title": "System/Logi systemowe: Wyświetl log",
        "icon": "webmin"
    }
]}&_=1483006733460
`

**Comment by qooob** [comment]
Hi,

Thanks for reporting.

I will reproduce it and try to fix it a bit later.

**Comment by qooob** [comment]
Hi,

I can't reproduce it.

Are you sure that you have UTF8 language set in both `Webmin Configuration -> Language` and `Change Language and Theme`?

**Comment by mateusz-szafraniec** [comment]
Yes, i have UTF-8 in both options.

**Comment by qooob** [comment]
Could you update to the latest Webmin 1.830?

**Comment by mateusz-szafraniec** [comment]
I have it already, problem still exists. On Ubuntu and Debian. Try something witch character `ś`

**Comment by qooob** [comment]
I still can't reproduce it.

The reason why it fails is because you have `&_=1483006733460` in the file. Remove it manually and try again.

**Comment by mateusz-szafraniec** [comment]
Problem still exists, please have a look:
[https://www.youtube.com/watch?v=yDRnbcV-Fw0&feature=youtu.be](url)

**Comment by qooob** [comment]
Hi,

Mateusz. I have watched closely your video. I will do my best to reproduce it and fix it upon next release.

I have downloaded your video. You can delete it from YouTube.

**Comment by qooob** [comment]
I could reproduce it.

Working on the fix.

**Comment by qooob** [comment]
Have a try with the fix https://github.com/qooob/authentic-theme/commit/945c625646d851d89627307c995fe7c1da06a377

**Comment by mateusz-szafraniec** [comment]
Nope, problem still exists...
`{"favorites":[
    {
        "link": "/fail2ban/",
        "title": "Sieć/Fail2Ban - detektor intruzów: Fail2Ban - detektor intruzów",
        "icon": "webmin"
    },
    {
        "link": "/lpadmin/",
        "title": "Sprzęt/Zarządzanie drukarkami: Zarządzanie drukarkami",
        "icon": "webmin"
    },
    {
        "link": "/package-updates/",
        "title": "System/Aktualizacja pakiet�w oprogramowania: Aktualizacja pakiet�w oprogramowania",
        "icon": "webmin"
    }
]}
`

`
<h1>Error - Perl execution failed</h1>
<p>Wide character in syswrite at /usr/share/webmin/miniserv.pl line 3087.
`

**Comment by qooob** [comment]
I can say that I copy/paste your JSON string. It works just fine. It loads without any problem.

What is your OS and the setup? Can you still reproduce this issue?

**Comment by qooob** [comment]
I even tried over again. 

Here is how my favorites.json look like:

```JSON
{"favorites":[
    {
        "link": "/fail2ban/",
        "title": "Nie-uÅ¼ywane moduÅ‚y/Fail2Ban - detektor intruzÃ³w: Fail2Ban - detektor intruzÃ³w",
        "icon": "webmin"
    },
    {
        "link": "/package-updates/",
        "title": "System/Aktualizacja pakietÃ³w oprogramowania: Aktualizacja pakietÃ³w oprogramowania",
        "icon": "webmin"
    },
    {
        "link": "/lpadmin/",
        "title": "SprzÄ™t/ZarzÄ…dzanie drukarkami: ZarzÄ…dzanie drukarkami",
        "icon": "webmin"
    }
]}
```

**Comment by qooob** [comment]
Try mine, does it fail with your setup?

**Comment by qooob** [comment]
No, really. It just works.
