### ISSUE TITLE
Webmin Gray page after login

### ISSUE THREAD

**Issue by ozmaat** [qooob/authentic-theme#624]
Hi,

I was not able to login to webmin yesterday, and it looks the theme is causing the issue. I have updated the packages, probably after that update issue began.

The steps
 -  the login screen appears as usual
 - enter the login details
 - A complete gray empty page opens - I include the html source code of the page below.
 - Actually it logins correctly but not able to display the dashboard.
 - I have tested it on different browsers, chrome, firefox, IE edge, opera, so not a browser problem
 - restarting webmin, booting OS or disabling CSF didn't help
 
What I did to open the webmin
 - Changed the theme name from webmin config file from ssh
 - And restart the webmin
 
The html code of the webmin after logging in with authentic-them enabled is attached.
[authentic-theme-error-html.txt](https://github.com/qooob/authentic-theme/files/679563/authentic-theme-error-html.txt)

The error on miniserv.error

`Error: Failed to open /etc/webmin/authentic-theme/csf.ui-introduced for writing : No such file or directory
 /images/favicon-webmin.ico : File not found
`

OS version - Centos - 7.3.1611
Browser versions - 
    Chrome - Version 55.0.2883.87 m
    IE edge - Microsoft Edge 38.14393.0.0
Webmin version - 1.830
Authentic-theme version - 18.31

Thank you

**Comment by qooob** [comment]
Hi,

From `ssh` make sure that `/etc/webmin/authentic-theme` is writable for the user you're running Webmin from (usually `root`). 

What is the output of `ls -lsaZ /etc/webmin/authentic-theme`?

**Comment by ozmaat** [comment]
Hi,

Output of the command is

ls: cannot access /etc/webmin/authentic-theme: No such file or directory

There isn't any theme directory in etc/webmin dir, either gray-theme or authentic theme.

I have updated the packages on another server yesterday, and changed the theme now to Authentic, and same problem occurs on that one also, and that server also don't have the theme on etc/webmin. 

I can see the theme files on /usr/libexec /webmin/.  Should it also be on this etc/webmin/ directory?

All dirs on etc/webmin has 0711 permission for the root.

Confused, as I have not played with any security on directories, as both server has the same issue.

Thank you

**Comment by qooob** [comment]
Just `mkdir /etc/webmin/authentic-theme && chmod 711 /etc/webmin/authentic-theme`. It should work then.

Happy New Year.

**Comment by ozmaat** [comment]
Thanks a lot. That did the trick.

Happy New Year.

**Comment by TristanPerry** [comment]
Just a quick note that I also had this issue in the latest upgrade - the file didn't exist, but the mkdir and chmod worked fine. Thanks!

**Comment by qooob** [comment]
It will be fixed and working automatically in 18.32 update.
