### ISSUE TITLE
SSL copy to Webmin copies to Usermin instead

### ISSUE THREAD

**Issue by clawrie** [qooob/authentic-theme#625]
I use a dummy virtual web server with the hostname of my server to allow certificate renewal using Let's Encrypt.  When clicking the copy to Webmin on SSL management of the virtual web server, the cert is copied to /etc/usermin instead of /etc/webmin.  The copy to Usermin button copies to /etc/usermin as well.
Using latest Webmin/Authentic on Centos 6.8

**Comment by qooob** [comment]
What makes you think it's the theme issue? Send most likely happens in Gray Theme?
