### ISSUE TITLE
Update of Webmin produces some errors related to the template

### ISSUE THREAD

**Issue by netizenuk** [qooob/authentic-theme#626]
Hi,

This is not to say that there is problem with the template (I hope at least).
This is to report that updating webmin via yum produces those errors:

`
.....
  Updating   : webmin-1.830-1.noarch                                        2/4
Webmin install complete. You can now login to.....as root with your root password.

  Cleanup    : devtoolset-4-runtime-4.0-9.el6.x86_64                        3/4
  Cleanup    : webmin-1.821-1.noarch                                        4/4
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/unauthenticated/                                                                             js/filtermatch.min.js failed: No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/unauthenticated/                                                                             js/cgi.min.js failed: No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/unauthenticated/                                                                             js/authentic.min.js failed: No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/unauthenticated/                                                                             js/authentic.js failed: No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/lang/ca failed:                                                                              No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/images/__logo.pn                                                                             g failed: No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/help/file-manage                                                                             r.ca.html failed: No such file or directory
warning:    erase unlink of /usr/libexec/webmin/authentic-theme/extensions/csf.j                                                                             s failed: No such file or directory
  Verifying  : webmin-1.830-1.noarch                                        1/4
....
`
Please let us know if those are OK to ignore.
Thank you.

**Comment by qooob** [comment]
Those are just fine. You should have absolute no worry about.
