### ISSUE TITLE
Usermin Login Error

### ISSUE THREAD

**Issue by NettSite** [qooob/authentic-theme#627]
Hi,

I am not sure if this is a theme issue or not, or when it started happening:

When a user logs in to Usermin, the following is displayed:

> HTTP/1.0 500 Perl execution failed Server: MiniServ/1.690 Date: Tue, 3 Jan 2017 10:18:37 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
> 
> Error - Perl execution failed
> 
> Undefined subroutine &amp;WebminCore::isd called at /usr/share/usermin/authentic-theme/authentic.pm line 10.

Operating system	Ubuntu Linux 14.04.4
Usermin Version	1.690
Authentic Theme 18.31

I changed the theme, and the error cleared.

**Comment by qooob** [comment]
Hi,

To fix this issue make sure that you have installed identical versions of the latest version (18.31) of the theme under both Webmin and Usermin.

We're working on patched version of Webmin and Usermin to be released in couple of days.

**Comment by NettSite** [comment]
Hi Ilia,

That fixed it, thank you very much.

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>
