### ISSUE TITLE
Java file manager 

### ISSUE THREAD

**Issue by campones** [qooob/authentic-theme#628]
Hello

I have webmin installed on ubuntu 16.0.4 lts (32bits if it matters).

I enjoy the java file manager because mostly, it offers a tree of directories, which the html one doesn't.

So since Chrome blocked java plugin, I m loading the java manager using a chrome plugin. 
https://chrome.google.com/webstore/detail/ie-tab/hehijbfgiekmjfkfjpbkbammjbdenadd
it basically load IE engine into chrome. 

With webmin default theme, it works fine (in fact it works as it used to work before chrome ended support for java plugin),  but with your theme, it cannot load properly.

**Comment by qooob** [comment]
Hi,

The problem is not in the theme but in the plug-in itself. It works in Firefox and IE as designed. Chrome had reasons for dropping support for it.

Version of the theme 18.31 has better feature than tree-view, from my point of view. You can see it in action in the following [video-screencast](https://github.com/qooob/authentic-theme/issues/442#issuecomment-263130393). 

>P.S. Just a guess but maybe opening it in the separate tab will make it work for you

**Comment by campones** [comment]
ok but however, it works totally fine with webmin default theme!

**Comment by campones** [comment]
yes it works if I write the full url in the browser but then I lose the theme and it looks really terrible

https://i.gyazo.com/c85b8de9a7bab6cb1da8c66a4fb5dfa1.png

https://i.gyazo.com/bb7ff5ff5bbce23f5f556cc1fc611209.png

**Comment by qooob** [comment]
What error in the console you get when loading Java FM in Authentic Theme?

**Comment by qooob** [comment]
Did you try Firefox?

**Comment by campones** [comment]
no I didn't. trying now firefox, java isn't working either.
 
working fine on IE (without the chrome extension then). 

on chrome, when I try to load the java FM , using the plugin, I get this

https://i.gyazo.com/3ee6f8ff0f4f44a218ece7ebf0bd311e.png

that's weird, but I guess I' ll stick to the default theme. 

Thanks

**Comment by qooob** [comment]
Just reload the page and clear cache. What is the error in the console of Chrome? (Call it using F12). Firefox works fine actually checked it fee hours ago.

**Comment by qooob** [comment]
What you're describing has everything to do with your setup, as I see it at the moment.

**Comment by qooob** [comment]
I have made a patch that should completely exclude all theme scripts for Java File Manager. When 18.32 is out. Please upgrade and try again.

**Comment by qooob** [comment]
It's out. Have a look.

**Comment by qooob** [comment]
I see. My friend, it's not the theme issue. I wish I could help but I'm afraid I can't.

I truly recommend to try using non-Java File Manager and report on what is missing. Eventually it will have more features that Java one. Tell me if there is anything else that is missing but tree-view, as you commented on https://github.com/qooob/authentic-theme/issues/629.
