### ISSUE TITLE
Feature request: Add a dashboard restart/ shutdown button.

### ISSUE THREAD

**Issue by Madseason41** [qooob/authentic-theme#630]
Is there any chance a "home page" shutdown or restart button can be added, maybe to the bottom of the dashboard? If this already exists please close. Thanks.

**Comment by qooob** [comment]
Hi,

Yes, there is a chance right now to go to 'Shutdown' page and add it to favorites. Then it will be displayed on the 'Right Slider' in theme version 18.30+

**Comment by qooob** [comment]
I use it personally this way and find it very handy, especially if your 'Right Slider' always visible.

**Comment by qooob** [comment]
However, the things to the System Information paged is push using WebminCore. I would recommend opening such issue on [Webmin](http://github.com/webmin/webmin) repo.

It's possible to add to Bootup and Shutdown module an option to configuration to make those buttons appear in another dropdown.

But again, it's much-much faster and accessible from any page, when using Favorites with Authentic Theme.

**Comment by Madseason41** [comment]
I may do that. The "favorite" method does work, but the true functionality I was looking for was kind of like a "hover over power button, then click restart" function. Thanks again for the help!
