### ISSUE TITLE
Translation into catalan

### ISSUE THREAD

**Issue by diathesaron** [qooob/authentic-theme#633]
Hi

I'm translating the authentic-theme into catalan. Would be possible to incorporate this this language in the next version ?. 

At the moment I have translated the entire file could be sent you. Tell me how can I do to send you the file.

Thanks a lot !

David Canalias

**Comment by qooob** [comment]
Just post it here or send it to me on https://rostovtsev.ru right now. I will add it to new 18.32 within an hour.

**Comment by qooob** [comment]
It's better to post it here.

**Comment by qooob** [comment]
I'm about to release 18.32. When are you planning to send it?

**Comment by diathesaron** [comment]
Today I finished translating the file and send it tomorrow

**Comment by qooob** [comment]
Ok. If you finish today, send today then! ;)

**Comment by qooob** [comment]
Make sure not to mix (sort) current key order. Just edit it as it is, please.

**Comment by qooob** [comment]
Waiting for your post. Thanks.

**Comment by diathesaron** [comment]
Attach file translation. 
T'hanks a lot !

[ca.UTF-8.zip](https://github.com/qooob/authentic-theme/files/685553/ca.UTF-8.zip)

David Canalias Rubió

**Comment by qooob** [comment]
Could you also translate this:

```
#18.32
theme_xhred_display_icons_warning=When display mode in module's configuration is set to <tt>Show Tables</tt> as <tt>Icons</tt>, the targets are displayed in separate icons (current setup), rather than in a table.<br><br>In order to select a target use either single <em>left-click</em> or single <em>right-click</em>; to enter a target use double <em>left-click</em>.

```

**Comment by qooob** [comment]
Thanks!

**Comment by qooob** [comment]
This is great. Thanks. Could you also translate one more string so I could add it to 18.32?

```
#18.32
theme_xhred_display_icons_warning=When display mode in module's configuration is set to <tt>Show Tables</tt> as <tt>Icons</tt>, the targets are displayed in separate icons (current setup), rather than in a table.<br><br>In order to select a target use either single <em>left-click</em> or single <em>right-click</em>; to enter a target use double <em>left-click</em>.

```

**Comment by diathesaron** [comment]
Updated file with 18.32 new string:

[ca.UTF-8.zip](https://github.com/qooob/authentic-theme/files/686986/ca.UTF-8.zip)

**Comment by qooob** [comment]
If you here could you please tweak it as I changed it a little bit since last time I wrote you?

```
theme_xhred_display_icons_warning=When display mode in module's configuration is set to icons, each target is displayed in separate container (current setup), rather than in a table.<br><br>In order to select a target use either single <em>left-click</em> or single <em>right-click</em>; to enter a target use double <em>left-click</em>.
```

**Comment by qooob** [comment]
Perfectly on time! Thanks again, David.

18.32 is about to come.
