### ISSUE TITLE
Configserver configuration

### ISSUE THREAD

**Issue by cloud4g** [qooob/authentic-theme#634]
Operating system	CentOS Linux 7.3.1611
Webmin version	1.830 
Virtualmin version	5.05 
Theme version	Authentic Theme 18.31
Firewall version	ConfigServer Security & Firewall 9.28    

The configserver configuration menu item does not appear. I don't know if this is because of authentic theme or due to default  changes in Centos 7 firewall/firewalld vs iptables.

**Comment by qooob** [comment]
Hi,

Configuration button was moved to default place for Webmin (top left of the table header, cog icon).
