### ISSUE TITLE
Buttons on apache virtual host list act as checkboxes, no links to virtual host config pages

### ISSUE THREAD

**Issue by chrispolley** [qooob/authentic-theme#636]
Running Webmin 1.830 / Authentic 18.32 on debian jessie

The current version of Authentic does a nice job of using the "buttons" in the left column of the virtual host list as check-box selectors, but now there is no way to get to the virtual host control panel page.  I had to switch to the Gray theme (which has separate check-boxes and buttons/links) to get to a page where I could make a needed configuration change.

Hovering over the button shows that it is linked to the virtual host control page, but clicking just toggles the state (yellow or not).  I didn't see whether it actually was a selection since I didn't need to delete any of my virtual hosts.  I didn't see any other area in the list that was hyperlinked.

Not sure which version of the theme caused this since I have not been in that area for a while.

Thanks!

**Comment by qooob** [comment]
Hi,

Just double click on it to enter it.

Doesn't give you a Notice message about how to use it? Are you sure you're on 18.32?

**Comment by chrispolley** [comment]
Yes, I upgraded to 18.32 recently, and double-clicking works but I have to
say it isn't intuitive.  I don't see any obvious note in the 18.30-18.31 or
32 changelog that would tell me this.  Where is this Notice message?

Thanks.

**Comment by chrispolley** [comment]
OT, but related -- I was going to also comment that the change "Added new functionality that replaces old pop-up windows with contemporary modals for file-chooser and other familiar operations #552" in 18.31 doesn't work (clicking on a directory just selects that root-level directory) but I see now that double-clicking opens the subdirectory.

**Comment by qooob** [comment]
Have a look at 18.30 changelog:

>Fixed the logic of selecting/accessing objects in modules for list (icons) mode. For selecting use click/right-click; for accessing double-click #575

**Comment by chrispolley** [comment]
OK, thanks.

**Comment by qooob** [comment]
What you're sating about Apache Webserver is not reproduced in 18.32+.

I made an explicit message on how to use it in icons mode. It will only fail to display if you run incognito mode on Safari (when localStorage is disabled).

This is the message:
![screenshot from 2017-01-07 11-38-33](https://cloud.githubusercontent.com/assets/4426533/21740597/435708d0-d4cf-11e6-896c-67a00d5fddff.png)
