### ISSUE TITLE
No semi-automatic theme update on Ubuntu.

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#638]
**The dedicated server:**
Ubuntu Linux 16.04.1
Webmin version 	1.830
Virtualmin version 	5.05 
Authentic Theme 18.31
Linux 4.4.0-57-generic on x86_64

![image](https://cloud.githubusercontent.com/assets/7549566/21742264/fc44dae4-d4e2-11e6-9fea-ba7c7b375e8b.png)

After clicking on **update** button the website is trying to install a new version, a second later after automatic refresh - nothing happens, version 18.31 still there, but should be 18.32.

**_On Centos all works fine ;)_**

**Is this a bug? Perhaps Ubuntu isn't that well supported as CentOS, however with the latest Debian, there is the same problem with updating like with Ubuntu. **

**Comment by sz00gun** [comment]
PS. Not sure why, however on the fresh system it didn't work as described above, however couple of minutes later I noticed a information about a new version on the right side:
![image](https://cloud.githubusercontent.com/assets/7549566/21742360/1f446800-d4e5-11e6-81cc-a40e3d4b4d61.png)

and clicked there and updated complied successful... not sure what happens.

**Comment by qooob** [comment]
Hi,

I have encountered it on RHEL systems as well. It's only possible when connection to GitHub is dropped.

It's likely not the theme issue and it happens very rarely with me (but I remember this happening). 

I usually waited for few minutes and then trying again always make it work.
