### ISSUE TITLE
Funny Character on config file edits

### ISSUE THREAD

**Issue by lionslair** [qooob/authentic-theme#64]
When viewing any raw config files. eg postfix main.cf or apache.conf files every line space has a funny A character 

See attached image. Has only appeared since version 8.0 update

![screenshot](https://cloud.githubusercontent.com/assets/832259/5609555/4b075fb8-94de-11e4-8fdd-e8d01f80a55b.png)

**Comment by qooob** [comment]
Hmm. Interesting. I would suggest that you have saved your files using `Windows Line Endings`.

I could not reproduce it on neither my debug system nor production. I suppose you mean `Edit Manually` on Apache, BIND, Postfix and so on. You should get CodeMirror loaded (what makes lines numbers on the left and highlight PHP or Apache config files). If it's all true (I don't see line numbers on the left though), than send me that file raw (with out any sensitive data) I will take a look.

What browser are you using?

**Comment by lionslair** [comment]
I'm using chrome on ubunt. Windows line endings is what I thought it was too. However after can cling multiple config files via console and comparing it to that which shows in webmin. Some of the configs have not been editied and are not windows saved files.

Will trying find a file I can send you

**Comment by qooob** [comment]
What happens if you open it (like Postfix main.cf) in Webmin? 1. Do you get line numbers on the left? 2. What if you add/remove couple of empty lines at the end and hit save and open it again - what happens?

**Comment by lionslair** [comment]
I even get Funny characters in the search form logging into the server. This is happening across all servers.
![screenshot](https://cloud.githubusercontent.com/assets/832259/5611037/b5e50af2-94fb-11e4-8838-932277ef438d.png)

not sure if you can see 
![screenshot from 2015-01-05 16 56 10](https://cloud.githubusercontent.com/assets/832259/5611043/cfdbbd8e-94fb-11e4-830b-3d01c1e8f898.png)

eg top and bottom of apache config
![screenshot-apache](https://cloud.githubusercontent.com/assets/832259/5611053/08df32e6-94fc-11e4-94a3-937abf7bae77.png)
![screenshot-apache-bottom](https://cloud.githubusercontent.com/assets/832259/5611057/218ba108-94fc-11e4-9726-f6f76fce37f4.png)

**Comment by qooob** [comment]
Oh.. I see. You must set UTF-8 in Webmin Language preferences. :)

Example:
![screenshot from 2015-01-05 12 04 08](https://cloud.githubusercontent.com/assets/4426533/5611122/351ab106-94d3-11e4-9fc6-3700be81af11.png)

**Comment by qooob** [comment]
Hey, I noticed that you have 2 errors in Chrome console? What are those?? :)

**Comment by lionslair** [comment]
Home on my home ubuntu laptop. Same issue now I just updated the theme on this too. The language is set as described but see the search box on the left. Has the funny characters.

I have refreshed saved and restarted webmin. Still there.

See screenshot
![screenshot](https://cloud.githubusercontent.com/assets/832259/5613087/d9f50dca-9519-11e4-8a5b-4259872306b6.png)

**Comment by qooob** [comment]
Now it's fine. It symbolizes Alt key. ;)

**Comment by lionslair** [comment]
Have you just made an update?

**Comment by qooob** [comment]
No. Why?

**Comment by lionslair** [comment]
What do you mean by ? 
Now it's fine. It symbolizes Alt key. ;)

**Comment by qooob** [comment]
OK, not sure what we say to each other. I say, that your last screenshot is valid. That symbol stands for Alt key (the one that is in search box), for combination shortcut Alt+S.

I didn't do any updates and even if I did they are not automatically applied.

**Comment by lionslair** [comment]
Understand now. So if it is not the language setting why do i see these characters across multiple servers and computers?

**Comment by qooob** [comment]
Do you see that Alt character in search box only or anywhere else?

**Comment by lionslair** [comment]
Was just the easiest example of showing the language setting and the funny characters on the one scree. Still getting funny characters as in previous screenshots earlier.

**Comment by qooob** [comment]
You mean that A character? I need to think.. Not sure where it's coming from. Try to reinstall the theme, restart webmin. I don't have it anywhere. Try `yum reinstall webmin`. If you have a copy try installing old version to see what you get. Try opening `index.cgi` of the theme and remove all Unicode characters, like that Alt character..

**Comment by lionslair** [comment]
Too late here to do tonight. Will try it tomorrow. I will try grab the last version from git. Remove and install the last version. I am 99% positive it wasn't their in last version. I know it was not their Friday. I spent all day doing server migrations so was checking configs etc all day and know it didn't have the A character etc.

**Comment by lionslair** [comment]
I still intend to make a donation to your efforts because you have done such a good job with this theme.

**Comment by qooob** [comment]
Thank you very much. When installing from git, it would be the best just to clone it into webmin directory. If you already cloned it before, I would suggest to download gziped package from the link to see the difference. Have a good night.

**Comment by qooob** [comment]
Thank you very much. When installing from git, it would be the best just to clone it into Webmin directory. If you already cloned it before, I would suggest to download gziped package from the link to see the difference. 

Also try to see what Encoding is set in Chrome `Options->More Tools->Encoding`. Also it's worth trying to close Chrome and before that clear browsers cache and images (leaving the rest). Tell me how it goes later. If it's a bug it must be fixed..

Have a good night.

**Comment by lionslair** [comment]
before and after update language was English US (EN)
ok. my local home server was v7. screenshot attached, 

![screenshot-lng-utf8](https://cloud.githubusercontent.com/assets/832259/5614161/114e1fd2-9529-11e4-886a-c74f9a37b1fb.png)
![screenshot-v7](https://cloud.githubusercontent.com/assets/832259/5614162/115d1028-9529-11e4-9956-a815646f589c.png)
![screenshot-v8](https://cloud.githubusercontent.com/assets/832259/5614163/117276fc-9529-11e4-8e0d-761e522d083f.png)

done update. after screenshot

set language from English US (EN) to English US (UTF-8) still the same.

I am only trying to provide as much info to solve this. It is 100% appeared from the latest update. I made an archive of the 7 theme before updating. Just for security.

**Comment by qooob** [comment]
Yes, also forgot to mention that there are local Webmin Theme/Language settings.

Go to `Webmin->Change Language and Theme`. Take a look at what you got there ;)

**Comment by lionslair** [comment]
Nope didn't work. See attached. Set it to en us UTF-8 refreshed closed chrome cleared cache restarted webmin still same issue.

I saw in the change log you updated an external library. Is it that which is causing this?

**Comment by lionslair** [comment]
![screenshot-core-language](https://cloud.githubusercontent.com/assets/832259/5614297/a45e6e0c-952a-11e4-9175-d6810bcf7c16.png)

**Comment by lionslair** [comment]
I changed theme to grey theme, see screenshot. No issue with funny characters. This is to illustrate I don't believe it is a local console / desktop / OS related issue.

![screenshot-webmin-grey theme](https://cloud.githubusercontent.com/assets/832259/5614342/32dc2a7a-952b-11e4-95a3-d4592b848e83.png)

**Comment by qooob** [comment]
I don't see any problems on the latest screenshots. Do you still have funny `A` when editing manually config files?

**Comment by lionslair** [comment]
That is because the last screenshot is the grey theme
![screenshot-webmin-grey theme](https://cloud.githubusercontent.com/assets/832259/5614451/6ed06a04-952c-11e4-8243-d21448f4c379.png)

then switch to the authentic theme and the issue returns
![screenshot-authentic](https://cloud.githubusercontent.com/assets/832259/5614459/7cbdd75a-952c-11e4-92d5-9f80b1008837.png)

**Comment by qooob** [comment]
My friend, where do you see an issue on the last screenshot? Search field?

**Comment by lionslair** [comment]
Yes search field and all the config edit screens. i just didn't want to go through screen shotting all the different config edit view screens. Was hoping you understood if it is present in one place it is present in all. like when i switch themes its then not present at all.

**Comment by qooob** [comment]
That's the problem. Search field is not a problem!  It's intended. Like I already mentioned, that character symbolises Alt key on MacKeyboard.

Do you still have fancy `A` in editor mode?

**Comment by qooob** [comment]
It tells you to use Alt+S shortkey to toggle focus on search field. ;)

**Comment by swelljoe** [comment]
I find the alt symbol a bit confusing, as well. I don't use a Mac. ;-)

I suspect it might be better to simply use "Alt" there. Maybe switching if the user-agent string indicates Mac OS X, if you wanted to get fancy. I think I prefer a hover to show hotkeys functionality, as well, so the hotkey isn't always displayed. But, I won't argue too strenuously about that. But, the Mac symbols are probably confusing enough to be worth changing for non-Mac users.

**Comment by qooob** [comment]
I am not an Apple user really. I just wanted one single symbol for Alt key. That was the best I could find at the moment. I will fix it by next small release.

**Comment by qooob** [comment]
..and on focus event will also be added.

**Comment by qooob** [comment]
Alright, new Webmin function is easy to understand and apply. I will add new, extended left menu for Virtualmin/Cloudmin by the new 9.0 release within 10 days. Plus I have some other bugs to fix. Thanks.
