### ISSUE TITLE
Theme: Utilize ability to use theme configuration for all users (not just root)

### ISSUE THREAD

**Issue by topstarnetwork** [qooob/authentic-theme#640]
Hello,
Is it possible to revert authentic theme into twitter bootstrap default theme colour?
I like the very minimalist twitter bootstrap default theme such as the one as virtualmin bootstrap theme,
if this is possible is there a guide to change that feature?
thanks

**Comment by qooob** [comment]
Hi,

Do you have a screenshot of how you would want this to look?

Theme has ability to use custom styles that are described on README.md. Isn't it enough?

**Comment by topstarnetwork** [comment]
Pardon me for my ignorance but I am not a coder, I just would like to learn,
my favourite bootstrap theme would be a minimalist such as;
https://bootswatch.com/default/ I love this !!!! Default theme with defaulth colour with no other customisation at all.
I would also want to use a horyzontal   menu bar like here: http://i.imgur.com/e5ilWQh.png
with a left side bar menus as shown in this screenshot. http://i.imgur.com/e5ilWQh.png
And use my own bootstrap glyphicons for each menus.
Is the above possible with authentic theme?
Regards, Heather

**Comment by qooob** [comment]
Hi,

Yes, it's possible to do it using in the theme configuration _Navigation menu color palette_->_User Palette 1_ and the customize it using. + _Extensions CSS_ editor.

However, unless you have basic knowledge in _CSS_ I don't think it would be possible to do.

Did you try choosing `White Snow` palette?

**Comment by topstarnetwork** [comment]
Well as I said I am not a coder,for this task I will have to hire a developer.
In order to get authenticc theme exactly the same way as the original twitter bootstrap theme colour, grid, component, buton, tabs, etc... Howlong, how many hours of work should I expect the developer to use in order to do this task with authentic theme?
Thank you so much for your support.

**Comment by topstarnetwork** [comment]
I don't know how to activate it, woul dyou have some screenshots to see how this looks like?

**Comment by topstarnetwork** [comment]
Could you also tell me if it is possible for you to add on authentic theme the switching ( skin theme ) buton? This would avoide any future user to do some special manipulation in order to activate his or her theme of choice?

**Comment by msimanga** [comment]
Please have a look at these [screenshots](http://imgur.com/a/GMTbL ) to access Authentic theme settings and change the color palette.

**Comment by qooob** [comment]
Do you want me to change your theme using the screenshots above, right?

**Comment by qooob** [comment]
@topstarnetwork 

Hi,

This is how it looks.

![screenshot from 2017-01-11 10-42-29](https://cloud.githubusercontent.com/assets/4426533/21839804/c864c242-d7ea-11e6-8bba-9165f46b4195.png)


To switch the theme you go to Theme Settings and do it there with few clicks.

**Comment by topstarnetwork** [comment]
That looks much nicer then the heavy dolour theme and less exhausting for the sight.
Unfortunatly I am not Madonna yet and I do not can afford $100/hour.
I will have to wait ethen in this case or hire a developer from upwork or freelancer com.
Your support is real great, I appreciate your fast response and the work you are dedicating for authentic theme!!!!!!!!!! You're precious.

**Comment by qooob** [comment]
@topstarnetwork Thank you for your kind words.

I might add new look (palettes) to the theme and one of theme might be _**Plain Bootstrap**_. If you like it than, you could donate.

Read the changelog please, upon the releases.

**Comment by topstarnetwork** [comment]
I tried to activate palet one from your tutoral screenshot but I don't see the top menu bar called "dashboard" and when I click on the buton to change the palet only webmin, virtualmin and cloudmin option are showing, please check the screenshot atatched file.
![usermin palet change](https://cloud.githubusercontent.com/assets/8043598/21841619/45ad2a26-d7e3-11e6-97e1-1ce9b91e363e.png)

**Comment by topstarnetwork** [comment]
There is no usermin option in this radio buton

**Comment by qooob** [comment]
This is not palette choose. This is default tab after you login. The same one exists for `Default tab after logging in to Usermin` (if Usermin is installed).

For choosing the palette just look a bit down or search using `Ctrl+F` (or CMD+F on Mac) for `Navigation menu color palette` it's in **_Global Options_**

**Comment by qooob** [comment]
Heather, what are you using _Webmin/Virtualmin/Cloudmin_ for? Are you a hosting manager?

**Comment by topstarnetwork** [comment]
not yet, I hope I will.
Right now it is for my personal usage.
I tried to use also usermin tab "Default tab after logging in to Usermin "but the theme changed does not exist, please check the screenshot 
![usermin theme buton not showing](https://cloud.githubusercontent.com/assets/8043598/21844583/7f766220-d7ef-11e6-8654-5b526c96796d.png)

**Comment by qooob** [comment]
I see now.

For now it's not possible to choose color for user account (_from user account_). It can be set globally when you logged in by `root`. So if you log in to the server as `root` and change the color palette there it will also change globally for all others, including Usermin.

Did you do it?

**Comment by topstarnetwork** [comment]
You said: qooob commented 2 hours ago
@topstarnetwork Thank you for your kind words.

I might add new look (palettes) to the theme and one of theme might be Plain Bootstrap. If you like it than, you could donate.

Read the changelog please, upon the releases.

Howmuch should I donate? Will it bebootstrap 4?
Regards, Heather

**Comment by topstarnetwork** [comment]
let me try to do it but usermin does not show on root panel as shown in my above root screenshot

**Comment by qooob** [comment]
I can't tell you how much. It's up to you.

It wouldn't be nice to say how much, I don't sell anything.

**UPD:** For the Usermin - You need to make a change in Webmin (logged it as `root`)

**Comment by topstarnetwork** [comment]
I did what you did but there is no change after having changed from root to palet 1. So what can I do?
Would you also have a user glssary guide for it (screenshot) there are so many words I don't know what they means.
![authentic theme setting panel](https://cloud.githubusercontent.com/assets/8043598/21846036/629e1750-d7f5-11e6-9ea4-b288824785c8.png)

**Comment by topstarnetwork** [comment]
Another question, how can I have the palet change buton avalable from usermin as it does not show there and you ask me to change it from root? Do we have to change some permission fromwebmin root sotaht the authentic theme buton shows on usermin?

**Comment by qooob** [comment]
Oh, my! First of all - Update to the latest Webmin that was recent theme. (18.32)

`Webmin->Webmin Configuration->Webmin Themes->Install themes->From uploaded file`

Here is the link to download it first:
https://github.com/qooob/authentic-theme/releases/download/18.32/authentic-theme-18.32.wbt.gz

Then go to the same page and in **Global Options** section you can change the palette, again, from _Webmin_ logged in as `root`.

**Comment by qooob** [comment]
I ask you to change it in _Webmin_ logged in as `root` and it will change it for ALL, including _Usermin_.

**Comment by topstarnetwork** [comment]
Thanks, I will ask my admin to do it and get back to youif any problem arises,
thank you so much !!!!!!!

**Comment by qooob** [comment]
:ok:

**Comment by qooob** [comment]
What we're up to here?

**Comment by qooob** [comment]
Starting from version 18.40 you will be able to configure the theme options even if you're not a root user.

Example:

![screenshot from 2017-03-18 23-28-07](https://cloud.githubusercontent.com/assets/4426533/24075781/fc2f0052-0c32-11e7-9c34-f4069077c65b.png)
