### ISSUE TITLE
"Copy to Webmin"

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#642]
Today I was making use of "Copy to Webmin" from the "Manage SSL Certificate" screen.

When I clicked "Copy to Webmin" it triggered the action of "Copy to Usermin" instead. As a result, I had to manually copy the certificates via SSH.

I'm not sure if this is a theme bug, or a Webmin/Virtualmin bug, so I figured I'd let you know first and take it from there.

OS: CentOS 6.8
Webmin: 1.830
Virtualmin: 5.05 GPL
Authentic Theme: 18.32
![copy-to-webmin](https://cloud.githubusercontent.com/assets/4305218/21781265/8c3c38a0-d663-11e6-857c-d31dea9445ff.png)
![manage-ssl-certificate](https://cloud.githubusercontent.com/assets/4305218/21781266/8c3e2e76-d663-11e6-8e43-a4aa919d76a0.png)

**Comment by qooob** [comment]
Hi, Peter.

We have discussed it recently in another issue. It shouldn't and really can't be theme bug. Can you switch to Gray Theme to double check?

**Comment by tpnsolutions** [comment]
Forwarding issue to Jamie for review as it's replicatable in Gray Theme, cheers!
