### ISSUE TITLE
Theme: Embedding Netdata

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#643]
Is possible (and easy) to add netdata stats into Virtualmin? such us: https://s29.postimg.org/jb3620nd3/virt.jpg

That would be superb panel with it.

**Comment by qooob** [comment]
Hi,

We have a link for _Netdata_ so far, did you see it?

I was thinking of that. But security policy doesn't allow loading code from other resources.

Any idea?

**Comment by sz00gun** [comment]
Yes I know about the link and I use it. I was happy about csf facility and now I'm happy about netdata. Very good developing.

If there is any other option to make it working, that would be great... 

I have a feeling Jamie gives a green light for it ;)

**Comment by qooob** [comment]
We will try to work it out.

**Comment by qooob** [comment]
_Netdata_ is great on it's own as it is (opened in separate tab). I don't see that much reason replicating it into the System Information page. 

We were discussing things about stats and don't seem to come to exact agreement yet, - but we have plans.

We're always working on improving our products. One day, there will be just as good or even better stats inbuilt in _Webmin_. I just would want to make it more usable and _less bulked_. We don't wish to just replicate it from already great product. It makes very little sense.

It's queued to be developed after new mail.

I will close this issue for now.

Thank you very much for sharing your ideas. Have a great day.
