### ISSUE TITLE
Theme: Firefox disfunction

### ISSUE THREAD

**Issue by ddlecrapaud** [qooob/authentic-theme#644]
Please make sure that you have latest theme (18.32) and Webmin (1.830) versions installed.

Provide the following information:
server-side OS Debian Wheezy / Debian Jessie
 client-side OS, browser and its versions: Debian Jessie, Firefox (38.7.1)
Connect to server
Get Left Nav Bar but blank page, Each time  try to change page by navigation bar, get a popup asking if i want to leave or stay on page : "This page is asking you to confirm that you want to leave - data you have entered may not be saved." staying or leaving lead to a blank page 

No issue when using chromium, or when using theme 18.10 or 18.20

Thanks for your help

David

**Comment by qooob** [comment]
Hi,

Did you try to restart _Webmin_ and clearing browser's cache? I have no issue on Firefox. Also closing and opening browser would help sometimes.

**Comment by ddlecrapaud** [comment]
Thanks for answering that fast.

As suggested, i'd just cleared browser's cache, restart Webmin, and firefox.

No success :(

Thanks for you help,

David

**Comment by qooob** [comment]
David,

Next try to reinstall theme manually using Webmin Configuration module. You can download latest theme from release tab.

Other browser also doesn't work? Tried Incognito tab?

Last try is to reboot the server. If it's fixed I'll be very surprised and pass this issue to Jamie.

**Comment by ddlecrapaud** [comment]
Hello,

I tried on 2 servers with the 10.32 version

first server ubuntu 9 which have been rebooted

second server debian wheezy

the issue does not appear with chromium browser

the issue still appears with incognito tab

Thanks for your help,


David

**Comment by qooob** [comment]
David, could you close Firefox, try to store/rename all of it's cache data and config directories to something else (make it if it was fresh installed) and then try it.

It's not the theme issue. I remember this happened in my Firefox. All I needed to do is to exit it. Just `kill -9 firefox`, probably it hangs somewhere in the memory. I bet the issue will not show up on the other computer with Firefox.

**Comment by ddlecrapaud** [comment]
Hello,

i made a fresh install of firefox and everything going right again.

Thanks a lot for your help

David

**Comment by qooob** [comment]
You're welcome!

**Comment by qooob** [comment]
By the way, do you use proxy?

**Comment by ddlecrapaud** [comment]
nop
