### ISSUE TITLE
Theme: Virtualmin password recovery

### ISSUE THREAD

**Issue by ai-hosting** [qooob/authentic-theme#646]
When using Virtualmin Password Recovery and Version 18.30-18.32 the login url for Version 18.30-18.32 is missing at the main page. Works with other themes.

**Comment by qooob** [comment]
Hi,

It's not missing. Have a look at the screenshot.
![screenshot from 2017-01-14 15-01-20](https://cloud.githubusercontent.com/assets/4426533/21954708/6625cc66-da6a-11e6-8ef8-e1e07e7e8477.png)

**Comment by ai-hosting** [comment]
![old theme](https://cloud.githubusercontent.com/assets/11756720/21954750/2bdc91f2-da5b-11e6-925c-4f904effd5d2.png)

**Comment by qooob** [comment]
I know about that text link. We decided to move it to the button.

Maybe the text should be a bit more clear.

**Comment by ai-hosting** [comment]
![new theme](https://cloud.githubusercontent.com/assets/11756720/21954879/6bde457c-da5e-11e6-9397-285bbc9056cf.png)

Missing at 10 different servers when using authentic-theme and centos 7

**Comment by qooob** [comment]
Could you please click _**Reset**_ orange button!?

**Comment by jobhh** [comment]
To be honest, it also is not clear to me that the Reset button is (or should be) a reset password button. It only seems to empty the Username and Password fields.

**Comment by qooob** [comment]
What would be the good name? `Password reset`?

**Comment by jobhh** [comment]
If that is what it does, yes. But currently it only seems to clear the Username en Password fields on Firefox and Chrome. Didn't test any other.

Server is running latest Webmin/Virtualmin running on Debian 64bit.

**Comment by qooob** [comment]
Missing it? Do you have Virtualmin password recovery installed? As far as I remember it requires it to be installed in order to work.

**Comment by jobhh** [comment]
I never heard of the module, so I don't have it installed :p I also cannot find it inside Webmin/Virtualmin as an unused module. The only way to get it seems to be from here http://www.webmin.com/cgi-bin/search_third.cgi?category=Virtualmin.

Maybe the theme shouldn't show the Reset (password) button if the required module is not installed, since the function of the button without this module can be confusing . I assume this lead to @ai-hosting opening this issue.

**Comment by qooob** [comment]
Reset button is not needed I agree. I will see what I can do here.

**Comment by ai-hosting** [comment]
if Virtualmin Password Recovery is installed RESET will take you to the pass recovery url.
Only problem is that is doens't support real password reset. If virtualmin allows plain text password storage it will send the old password by email. A smart admin will store the password in a hashed form. Making the Virtualmin Password Recovery unusable.

**Comment by qooob** [comment]
@ai-hosting Even though I agree, that is not the theme issue. Report it to Webmin repo.

**Comment by qooob** [comment]
What are we talking here? I'm not sure.

I will remove reset button as it's useless. But if you have VM password recovery does it work the same way for you as in old themes?

**Comment by qooob** [comment]
.. I will call the new button for Password recovery as such.

**Comment by qooob** [comment]
Oh, yeah. Don't bother. I see what you mean. I will make a quick fix for you to check.

**Comment by qooob** [comment]
Please have a try this patch.
