### ISSUE TITLE
MySQL/PostgreSQL: Remove button is always disabled in icon mode

### ISSUE THREAD

**Issue by thevukaslt** [qooob/authentic-theme#647]
In the MySQL module red buttons with remove/delete/drop purpose are always disabled. No matter whether you have chose something or not.

I'm running latest Webmin and Authentic on two different servers, issue persist.

Information:
* Both Ubuntu 16.04?
* Win10, Chrome (latest) Version 57.0.2979.2 (Official Build) dev (64-bit)/Opera (latest) 42.0.2393.94 Stable

Visiting to MySQL module and trying to drop chosen database or visiting database and trying to drop selected tables. 

However, after manually (editing DOM content) removing disable attribute from button, it performs well.

![download](https://cloud.githubusercontent.com/assets/9198896/21963910/0ddb82a8-db4b-11e6-917b-2bc1aa5de90b.png)

**Comment by qooob** [comment]
Hi,

Yes, confirmed. The work around is to change display mode to list in mudule configuration and set `Show databases and tables as` to `List`.

Thanks for reporting.

**Comment by thevukaslt** [comment]
Hey,

Cool! Looking forward for an update. 

Thanks for tip.

**Comment by qooob** [comment]
Will do.

**Comment by qooob** [comment]
You can apply the patch above or wait for 18.33 to be released.

**Comment by thevukaslt** [comment]
Cool! I'm sorry but I'm yet to get better with Git system, how do I apply this patch manually? :)

**Comment by qooob** [comment]
Do the following using command line:

1. `cd /usr/share/webmin`
2. `mv authentic-theme _authentic-theme`
3. `git clone https://github.com/qooob/authentic-theme.git`
4. `/etc/webmin/restart`

**Comment by thevukaslt** [comment]
Works like a charm!
