### ISSUE TITLE
Theme not working correctly on ipv6

### ISSUE THREAD

**Issue by henrikx** [qooob/authentic-theme#648]
It seems like when it is hosted on ipv6 some parts of the theme just stops working:
* On the dashboard the status numbers (cpu usage, disk usage and all those) just don't show up (https://puu.sh/tno00/e8fe886053.png)
* The theme settings manager doesn't show. (https://puu.sh/tnono/37a375dc23.png)

This only happens when I'm connected to webmin via IPv6. This is a fresh install so I'm pretty sure this isn't a configuration error on my end.

* Debian 8
* Firefox 50.1
* Host a server on ipv6 to reproduce

**Comment by qooob** [comment]
Hi,

Could you please switch to Gray Theme and try again.

**Comment by henrikx** [comment]
Like, gray and then back to Authentic?

**Comment by henrikx** [comment]
Same result^

**Comment by qooob** [comment]
If it's the same result and you think it's a bug, please fill an issue to [Webmin GitHub repo](https://github.com/webmin/webmin)
