### ISSUE TITLE
Theme: IPv6 connection

### ISSUE THREAD

**Issue by henrikx** [qooob/authentic-theme#649]
**REPOST: I think you misunderstood me in the previous thread. What I meant to say was when I switched to Gray theme and back to Authentic I got the same error. Everything seems to work fine with the default Gray theme.**

It seems like when it is hosted on ipv6 some parts of the theme just stops working:

*On the dashboard the status numbers (cpu usage, disk usage and all those) just don't show up (https://puu.sh/tno00/e8fe886053.png)
*The theme settings manager doesn't show. (https://puu.sh/tnono/37a375dc23.png)

This only happens when I'm connected to webmin via IPv6*. This is a fresh install so I'm pretty sure this isn't a configuration error on my end.

*Debian 8
*Firefox 50.1
*Host a server on IPv6 to reproduce and connect with IPv6, without using a domain name.

EDIT: *This only happens when both a domain name is not used and the address is IPv6. (When the URL host is an IPv6 address).

**Comment by qooob** [comment]
I don't think how it could be the theme issue.

I will try to reproduce it and get back to you a bit later.

**Comment by henrikx** [comment]
I want to add that if the site is accessed via a domain (while still using ipv6), it seems to work correctly, which makes this even weirder. So this only happens if the server is connected directly with an ipv6 address instead of domain.

**Comment by qooob** [comment]
While I will debug it a bit later I have no idea how and why it would be related to the theme. Are you sure that it doesn't work in old themes? System Information Page in old themes is different but uses the same mechanism. Make sure that percent signs are also present when you switch themes.

**Comment by qooob** [comment]
What are the errors in the console?

**Comment by henrikx** [comment]
This is the only one:
`17:16:26.209 TypeError: g.data(...) is undefined 1 parent.min.js:6:3061
	__si__bg_upd_exec/<.success/< https://[2a06:e881:1503:110::1337]/unauthenticated/js/parent.min.js:6:3061
	.each https://[2a06:e881:1503:110::1337]/unauthenticated/js/bundle.min.js:2:2923
	__si__bg_upd_exec/<.success https://[2a06:e881:1503:110::1337]/unauthenticated/js/parent.min.js:6:1768
	bv.Callbacks/l https://[2a06:e881:1503:110::1337]/unauthenticated/js/bundle.min.js:2:28806
	bv.Callbacks/k.fireWith https://[2a06:e881:1503:110::1337]/unauthenticated/js/bundle.min.js:2:29588
	H https://[2a06:e881:1503:110::1337]/unauthenticated/js/bundle.min.js:2:79951
	.send/f/< https://[2a06:e881:1503:110::1337]/unauthenticated/js/bundle.min.js:2:82281
`

**Comment by qooob** [comment]
Did you try Chrome, out of curiosity? Did you try Incognito Mode?

**Comment by henrikx** [comment]
Tried! Same result.

**Comment by qooob** [comment]
Are you using proxy?

**Comment by henrikx** [comment]
Not on my computer or network. Via IPv6 the connection to the server goes directly to webmin, but for IPv4 it goes via an nginx reverse proxy, which forwards the request to Webmin's IPv6 address. This set up works correctly however. It does not matter if the request comes from IPv6 or not, it only happens when both no domain name was used and the connection was on IPv6.

**Comment by qooob** [comment]
I would need your setup to reproduce the problem.

**Comment by henrikx** [comment]
Nope, you can completely ignore the nginx setup, because it is only for v4 compatability, which I normally don't use. Otherwise this setup is completely stock.

**Comment by henrikx** [comment]
Any news?

**Comment by qooob** [comment]
I can't reproduce the problem yet.

**Comment by henrikx** [comment]
Yeah, but why? Is there any specific reason?

**Comment by qooob** [comment]
I was working a lot of time on different parts of the theme. I will come back to your issue a bit later.

**Comment by henrikx** [comment]
Okay, thanks!

**Comment by qooob** [comment]
I don't see the ports in your _error message_ above, are you running behind proxy?

**Comment by henrikx** [comment]
It doesn't show any ports because Webmin is running on default https port (443).

**Comment by henrikx** [comment]
Just noticed something in the address in the error message `https://[[2a06:e88x:150x:11x::1337]`
Notice how there are two "[" marks where there should only be one.

**Comment by qooob** [comment]
What is the output of `/etc/webmin/config`?

You made `miniserv` to run on 443 and want browser to open it as default `https` connection?

**Comment by henrikx** [comment]
I'm not sure if I know what you mean, but here's the output.
> user@server:~$ cat /etc/webmin/config
> by_view=0
> passwd_cindex=2
> find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
> passwd_uindex=0
> tempdelete_days=7
> path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
> passwd_pindex=1
> passwd_mindex=4
> ld_env=LD_LIBRARY_PATH
> passwd_file=/etc/shadow
> os_type=debian-linux
> os_version=8
> real_os_type=Debian Linux
> real_os_version=8
> lang=en.UTF-8
> log=1
> referers_none=1
> md5pass=1
> theme=authentic-theme
> product=webmin
> webprefix=

Here's also miniserv.conf
> user@server:~$ sudo cat /etc/webmin/miniserv.conf
> port=443
> root=/usr/share/webmin
> mimetypes=/usr/share/webmin/mime.types
> addtype_cgi=internal/cgi
> realm=Webmin Server
> logfile=/var/webmin/miniserv.log
> errorlog=/var/webmin/miniserv.error
> pidfile=/var/webmin/miniserv.pid
> logtime=168
> ppath=
> ssl=1
> no_ssl2=1
> no_ssl3=1
> no_tls1=1
> no_tls1_1=1
> ssl_honorcipherorder=1
> no_sslcompression=1
> env_WEBMIN_CONFIG=/etc/webmin
> env_WEBMIN_VAR=/var/webmin
> atboot=1
> logout=/etc/webmin/logout-flag
> listen=10000
> denyfile=\.pl$
> log=1
> blockhost_failures=5
> blockhost_time=60
> syslog=1
> ipv6=1
> session=1
> premodules=WebminCore
> server=MiniServ/1.831
> userfile=/etc/webmin/miniserv.users
> keyfile=/etc/webmin/miniserv.pem
> passwd_file=/etc/shadow
> passwd_uindex=0
> passwd_pindex=1
> passwd_cindex=2
> passwd_mindex=4
> passwd_mode=0
> preroot=authentic-theme
> passdelay=1
> cipher_list_def=1
> failed_script=/etc/webmin/failed.pl
> logout_script=/etc/webmin/logout.pl
> login_script=/etc/webmin/login.pl
> sudo=1
> sockets=
> no_resolv_myname=0
> bind=2a06:e88x:150x:11x::1337
> certfile=/etc/webmin/miniserv.cert
> extracas=
> ssl_redirect=0
> no_tls1_2=
>

**Comment by qooob** [comment]
I still have a feeling that it's not the theme related.

At first glance, why do you have `port=443` and `listen=10000` set at the same time?

What happens if you try to access your page using:

`https://[2a06:e88x:150x:11x::1337]:443`, does it change anything?

**Comment by henrikx** [comment]
If I type `https://[2a06:e88x:150x:11x::1337]:443` the browser removes `:443` from the URL, because it is the default port for https and isn't needed. Looking at console again it looks like the extra `[` there was just a paste error from me (sorry about that). The `listen` option is the port which Webmin will listen to broadcasts from Virtualmin, Cloudmin and other Webmin installs I think, due to the option in the GUI being labeled `Listen for broadcasts on UDP port`.

**Comment by qooob** [comment]
What if you set the port to _1234_ for example and try using:

`https://[2a06:e88x:150x:11x::1337]:1234` instead, what do you get?

**Comment by henrikx** [comment]
It just gives me the same error in console (with the extra port number specified). Here's one line:
`__si__bg_upd_exec/<.success https://[2a06:e88x:150x:11x::133x]:1234/unauthenticated/js/parent.min.js:6:1768` and the same visual error with no Authentic Theme things showing up.
Here's a full picture: https://puu.sh/uucz0/68f0f2dad5.png

**Comment by qooob** [comment]
I think I know what could be causing it.

The cause of the issue could be the browser's extensions. Try either incognito mode, or for instance, Chrome to double check. I remember there were issues like this, that were caused by browser's extensions  (addon's).

**Comment by henrikx** [comment]
It's not.
Here it is in IE: https://puu.sh/uucXY/bfbcec4407.png

**Comment by qooob** [comment]
Tried Firefox incognito mode, I suppose?

**Comment by henrikx** [comment]
Firefox in incognito mode loads all the addons I have (cuz settings lol), but yeah I've tried it. I've also tried it in Chrome stock. Same result in all browsers.

**Comment by qooob** [comment]
I have logged it as IPv6. Yes, there are problems on `XHR` requests. I will try to fix it upon 18.40 release.

**Comment by qooob** [comment]
However, I must admit that everything works great over IPv6 when _not using proxy_ and connecting directly.

You connection is proxied most likely.

**Comment by qooob** [comment]
I have made some testing and sure now that it was noting to do with the theme. Please read: https://github.com/webmin/webmin/issues/505

It's partly related to https://github.com/qooob/authentic-theme/issues/652

**Comment by henrikx** [comment]
Why do you keep ignoring me when I tell you the connection is NOT via a proxy. I have told you this more than once now.  Look at the response
> Auth-type: auth-required=1
> Connection: close
> Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self'; child-src 'self'
> Content-Type: text/html; Charset=UTF-8
> Date: Sun, 5 Mar 2017 16:10:33 GMT
> Server: MiniServ/1.831
> Set-Cookie: redirect=1; path=/
> testing=1; path=/; secure
> X-Frame-Options: SAMEORIGIN
If you look in the `Server` header you can see it clearly comes from Webmin and not nginx, so please stop assuming the connection is proxied, because it's not.

**Comment by henrikx** [comment]
To eliminate any suspicion towards SSL, I tried to disable that, but I got the same result. I honestly cannot see how this could be a problem with my setup. It might very well be a problem with Webmin and not the theme though, but as this only happens when using Authentic Theme I thought the best place to put the issue was here.

**Comment by qooob** [comment]
Oh, man. I didn't expect that. After signing in using IPv6 address only (without domain) I could reproduce all that you're saying for all _XHR_ calls. (like dashboard and theme configuration and other).

Very surprising.

I'll work on it now as I see the problem..

**Comment by qooob** [comment]
Have a look:

http://stackoverflow.com/questions/40611863/ipv6-issues-with-ajax-requests

**Comment by qooob** [comment]
I got the reason why. Fixing it...

**Comment by henrikx** [comment]
That's great! Was it related to the theme only or Webmin as a whole?

**Comment by qooob** [comment]
It was related to the bugged library for parsing URLs..

`$_url.attr("path")` returns `"/sysinfo.cgi"` on IPv4 and the IPv6 address itself on IPv6 connections. (hard to believe)

I didn't expect that happeing.. You can run `$_url.attr("path")` on the console to see what I mean. This is very hard to grasp unless you know what is going on.

Thank you very much for reporting. **_It's not related to the proxy_**, you're right!!

**Comment by henrikx** [comment]
Oh yeah that's really weird! Thanks for looking into it and I'm glad I could help. :)

**Comment by qooob** [comment]
Please give it a try. It's checked.

**Comment by qooob** [comment]
I'm really glad to get rid of that old library. It should work now.

Please report here if you find any bugs!

**Comment by henrikx** [comment]
Did you upload the webmin theme file or do I have to clone the repo?

**Comment by qooob** [comment]
Just clone it.

**Comment by henrikx** [comment]
Works great now! Thanks :D

**Comment by qooob** [comment]
You're welcome.
