### ISSUE TITLE
Can't scroll on iphone

### ISSUE THREAD

**Issue by kizz1337** [qooob/authentic-theme#65]
On iphone 5, all page are partially show, scrolling don't work it's impossible to show anything out of the screen

**Comment by qooob** [comment]
We already had this issue. 
https://github.com/qooob/authentic-theme/issues/54

I though I have fixed it. Well, I will try doing it on the later releases.

Thanks for reporting.

**Comment by qooob** [comment]
I'm releasing new update tonight. iPhone feature should work now. Please report if it is. Thanks.

**Comment by kizz1337** [comment]
issue not resolve.
Scrolling won't work on my Iphone 5.

**Comment by qooob** [comment]
Sorry to hear it. Do you realize that this is Apple bug. Even though it would be possible to solve this using JavaScript, my Apple DevTools make scroll work perfectly. I don't have actual iPhone to test it.

I will ask others to check it on their devices.
