### ISSUE TITLE
Catalan translation improved

### ISSUE THREAD

**Issue by diathesaron** [qooob/authentic-theme#650]
These last few days I've been improving the translation of some texts in Catalan. This is the latest version.
Thanks !!
[[20170118] ca.UTF-8.zip](https://github.com/qooob/authentic-theme/files/713167/20170118.ca.UTF-8.zip)

**Comment by qooob** [comment]
Hi,

Thanks. I will add it to 18.33 soon.

**Comment by diathesaron** [comment]
Perfect ! Thanks a lot !!
