### ISSUE TITLE
Theme: Doesn't work when using reverse proxy

### ISSUE THREAD

**Issue by markisoke** [qooob/authentic-theme#652]
I use a nginx reverse proxy for all my services to eliminate opening ports to the outside world other than port 80, but it seems is doesn't work with this time. I can see the login page and successfully login, but after that stage it's stuck on loading. It shows only the notification button but no info in it: http://imgur.com/a/NN2Jf

Relevant information:

*Nginx webserver with SSL enabled
*Ubuntu 16.04 LTS

Old themes do work with this setup, but this theme doesn't.
Anything you might be able to solve this issue?

**Comment by qooob** [comment]
Hi,

What are the errors in console?

What is your browser?

**Comment by markisoke** [comment]
Hi, thanks for replying to quick.

Console from Chrome (55.0.2883.87):

`Multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, DENY') encountered when loading 'https://webmin.mysite.link/sysinfo.cgi'. Falling back to 'DENY'.
/sysinfo.cgi:1 Refused to display 'https://webmin.mysite.link/sysinfo.cgi' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN, DENY'.
postinit.min.js?1832:6 Uncaught DOMException: Blocked a frame with origin "https://webmin.mysite.link" from accessing a cross-origin frame.
    at __lle (https://webmin.mysite.link/unauthenticated/js/postinit.min.js?1832:6:30246)
    at https://webmin.mysite.link/unauthenticated/js/parent.min.js?1832:6:17057
    at dispatch (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:43460)
    at r.handle (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:41459)
    at Object.trigger (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:71426)
    at H (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:80157)
    at XMLHttpRequest.<anonymous> (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:82281)
__lle @ postinit.min.js?1832:6
(anonymous) @ parent.min.js?1832:6
dispatch @ bundle.min.js?1832:2
r.handle @ bundle.min.js?1832:2
trigger @ bundle.min.js?1832:2
H @ bundle.min.js?1832:2
(anonymous) @ bundle.min.js?1832:2
bundle.min.js?1832:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://webmin.mysite.link" from accessing a cross-origin frame.
    at contents (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:28254)
    at Function.map (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:3482)
    at bv.fn.init.bv.fn.(anonymous function) [as contents] (https://webmin.mysite.link/unauthenticated/js/bundle.min.js?1832:2:28346)
    at __si__bg_upd_exec (https://webmin.mysite.link/unauthenticated/js/parent.min.js?1832:6:1034)
    at https://webmin.mysite.link/unauthenticated/js/parent.min.js?1832:6:16327`

I tried it on Chrome, Firefox, Edge and Internet Explorer.

**Comment by qooob** [comment]
Could you share your httpd setup, so I could reproduce it with ease, please?

**Comment by markisoke** [comment]
Well, its Nginx, so here is my nginx.conf: http://pastebin.com/B4NDXr7t
And also the sites-enabled config: http://pastebin.com/JaHTEX9G

**Comment by rafuz** [comment]
Any news about this issue?

**Comment by qooob** [comment]
Yes, I will take a look at this in few days. Need to finish working on Shell Autocomplete.

**Comment by qooob** [comment]
I have no idea how to reproduce it, sorry.

**Comment by qooob** [comment]
Hi,

`SAMEORIGIN, DENY` error is coming from your setup.

I could _reproduce_ and _fix_ exactly the same error on _Apache_. I bet there is a correspondent option in _Nginx_.

What I did to fix it was adding to `virtualhost` configuration the following:

```BASH
Header always set X-Frame-Options SAMEORIGIN.
```

From reading [an article](https://geekflare.com/add-x-frame-options-nginx/), it's said to do the following in _Nginx_, under server configuration:

```BASH
add_header X-Frame-Options "SAMEORIGIN";
```

**Comment by qooob** [comment]
By the way, this is not a valid statement:

>Old themes do work with this setup, but this theme doesn't.

It also fails in old themes because all of them use frames, I checked it.

**Comment by qooob** [comment]
I have made some testing and sure now that it was noting to do with the theme.

Please read: https://github.com/webmin/webmin/issues/505

**Comment by jcameron** [comment]
Does it make any difference if you edit `/etc/webmin/config` and add the line `no_frame_options=1` ? This turns off the `X-Frame-Options:` header in Webmin.

**Comment by qooob** [comment]
Jamie, no! I have again tried all possible options. Including completely loosening Apache configuration. It's just not working. It keeps toggling between session pages and login page. It's doesn't always toggle in order and look very glitchy when you click around the links.

Try latest Apache with mentioned setup. It just won't work.

**Comment by jcameron** [comment]
Are you proxying a subdirectory on the original Apache virtualhost to Webmin (like http://foo.com/webmin) or is it at the webserver root?

**Comment by qooob** [comment]
It's server root, the last section in the instruction page on the Webmin site.

**Comment by jcameron** [comment]
Ok, let me try setting this up myself, and I'll let you know what I discover.
