### ISSUE TITLE
PaleMoon browser: infinite loop after upgrade to 18.3x

### ISSUE THREAD

**Issue by forofo** [qooob/authentic-theme#653]
With PaleMoon browser it only shows the animated icon without end and the theme doesn't work.

In case you there is not option to solve the issue, please provide a link to download again version 18.2x 

thanks,

**Comment by qooob** [comment]
What is the version of your browser?

**Comment by forofo** [comment]
PaleMoon 26.5.0

**Comment by qooob** [comment]
Please upgrade your browser to 27+

Dupe of https://github.com/qooob/authentic-theme/issues/637

**Comment by forofo** [comment]
oh.. ok, thanks!
