### ISSUE TITLE
Usermin: Create Filter

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#656]
A customer of mine was having some troubles working with Email Filters today. While troubleshooting the matter with him, I discovered a few minor bugs with the UI.

1. When you navigate to the "Email Filters" page from the level navigation, "Forward Email" highlights in the menu instead of "Email Filters". Additionally, the page title reads "Forward Email" instead of "Email Filters".

2. When you click "Add a new email filter" the radio input for "Based on regular expression" is outside the table, and unclickable in at least Google Chrome on Ubuntu. This makes you have to use the "tab" key to navigate to it.

3. Finally, the vertical alignment for "Add a new email filter" page makes the form a bit confusing. Perhaps using "top" vertical alignment for the table would, and/or alternating row highlighting (or via row hover).

*** While perhaps intentional, I also noted a box around the "radio input" fields when clicked. I believe this is related to the "outline" CSS value not being set to "none". Perhaps a cleanup theme wide related to how field borders, outline, and other options are handled would make things a bit more clear going forward. ***

Attached image shows issue noted in bug 1 and 2 above.

![usermin-create-filter](https://cloud.githubusercontent.com/assets/4305218/22268613/fee31e02-e23c-11e6-9eef-c82bdd8de05c.png)

**Comment by qooob** [comment]
Peter, hi!

Thank you for pointing this out. I'm planning to completely `wipe-out` and rebuild mail section from listing mail and manipulating address book, to filters and folders management.

**Comment by qooob** [comment]
Ref: https://github.com/qooob/authentic-theme/issues/431
