### ISSUE TITLE
Theme: Password change button doesn't work

### ISSUE THREAD

**Issue by razor2k** [qooob/authentic-theme#657]
I'm using Webmin 1.831 and authentic-theme 18.32 on Ubuntu 14.04.

When I forced password change on next login for my test user, I realized that the Change button is not working.

I can click as much as I want and nothing is happening. However sending the form by hitting return in an input-field does work.
Using Webmin Old Theme does also work as expected.

**Comment by qooob** [comment]
Hi,

I will fix this in the next small release, 18.33.

Thanks for reporting.

**Comment by qooob** [comment]
Hi,

I have made a [hot-fix](https://github.com/qooob/authentic-theme/commit/ee03493bcfb0ef5eb94f23f78e45c62a6a70ad39) that will work now. It will be added to 18.33.

You can apply it now or wait for the release.

![screenshot from 2017-01-31 14-24-28](https://cloud.githubusercontent.com/assets/4426533/22463167/7f752a0e-e7c1-11e6-9d1a-aa4374ebc3a0.png)
![screenshot from 2017-01-31 14-28-27](https://cloud.githubusercontent.com/assets/4426533/22463237/cb4bad40-e7c1-11e6-9e25-197715dee063.png)
