### ISSUE TITLE
Authentic theme does not work with the Palemoon browser

### ISSUE THREAD

**Issue by jcameron** [qooob/authentic-theme#658]
See this thread : https://sourceforge.net/p/webadmin/mailman/webadmin-list/thread/1c85a63b-0c73-c54c-07ea-ee9eddb3a865%40gmx.com/#msg35628874

**Comment by qooob** [comment]
Jamie, hi.

I read through the thread. I understood that the user doesn't want to register again and that his username is taken.

However I tried I couldn't register at SourceForge. It returned error all the time from different browsers.

Just tell him please that this issue has been discussed multiple times already https://github.com/qooob/authentic-theme/issues/637 and that at the moment all he needs is to apply the latest fix https://github.com/qooob/authentic-theme/commit/4a9cde1c7320222969977d13831c7d29670997f8 by cloning the repo.

I will add this to the 18.33 within next week, as I'm ready to pause current development and go back to fixing those non-critical bugs.

**Comment by qooob** [comment]
It's not a bug actually but limitation of the browser that doesn't support [ES6](https://github.com/lukehoban/es6features#let--const).
