### ISSUE TITLE
File Manager: Copy/paste doesn't work as expected

### ISSUE THREAD

**Issue by chrispolley** [qooob/authentic-theme#660]
Using Authentic 18.32 on Webmin 1.831, on Debian Jessie.

Copy/Cut/Paste in the File Manager module does not work as expected.

Cut, Copy, and Paste icons in toolbar are missing (blank boxes are displayed) but tooltips are present when mousing over the place where they should be.  This does not seem to be context-dependant, because selecting  file(s) does not make the icon for copy/cut visible and Copy/Cut from context menu does not make Paste icon visible.

When selecting a file, choosing "cut" from the context menu, navigating to another folder (in the same tab), and clicking on where the Paste icon should be in the toolbar, the error message "Following errors occured while performing operation \n //{filename} already exists, skipping" {filename} happens to be the first real (non-shortcut) file listed in the root directory, which was not open in any FM tab and was not related in any way to the selected file.

If instead "Paste" is selected from the context menu of a subfolder in the folder the file was cut from, nothing happens.

I didn't find anything in the README.md file regarding this particular feature, and didn't try the keyboard shortcuts yet.

Thanks for a great tool!

**Comment by qooob** [comment]
Hi,

I have tested it and I couldn't reproduce the bug.

Here is the example of how it works for me on the [screencast](http://rostovtsev.ru/pub/src/authentic/18.32/file_manager_working_copy_cut_paste.webm).

Do you have the screenshot at least to see how it's missing?

It seems that there could be something wrong with your Debian package. Could you reinstall the theme using command line?

```BASH
1. `cd /usr/share/webmin`
2. `mv authentic-theme _authentic-theme`
3. `git clone https://github.com/qooob/authentic-theme.git`
4. `/etc/webmin/restart`
```

**Comment by chrispolley** [comment]
Thanks. At first glance, the difference is that you have drop-down menus
instead of icons on the toolbar:

I will reinstall and try it again.

**Comment by qooob** [comment]
Icons??

**Comment by chrispolley** [comment]
By icons, I mean the toobar buttons at the top.

Digging into the code, they are inserted from filemin/filemin-lib.pl:
'sub print_interface {
    # Some vars for "upload" functionality
    local $upid = time().$$;
    $bookmarks = get_bookmarks();
    @allowed_for_edit = split(/\s+/, $access{'allowed_for_edit'});
    %allowed_for_edit = map { $_ => 1} @allowed_for_edit;

    # Set things up according to currently used theme
    if ($current_theme eq 'authentic-theme' or $current_theme eq 'bootstrap') {

...
        # And toolbar
        if($userconfig{'menu_style'}) {
            print_template("unauthenticated/templates/menu.html");
        } else {
            print_template("unauthenticated/templates/quicks.html");
        }'

I didn't find an option on the Authentic Theme configurable options that was easily identifiable as "menu_style" so I'm not sure where that is set.

From the screen you show in your screencast, I think that you have menu_style as true and I have it as false, because the [Create File/Create Folder/Upload File/Get from URL] buttons are grouped on your screen and not on mine.

... 

and looking at filemin/paste.cgi, the function get_paste_buffer_file is pulling data from /root/.filemin/.buffer when I am logged in as user "admin" (with sudo privs, so sommand shell module runs as whoami=root, so this may be expected.)

However, this may be a red herring as the called functions are the same for both toolbars.  After trying the copy/paste function several times I am not certain that the variable $cwd in paste.cgi always represents the folder displayed in the current tab. 

Once it matched the '$from' folder and another time it was the filesystem root, although both times when I tried to test the paste function I had the '/root/.filemin/' folder displayed.  In most cases, the error message displayed is telling me that '$cwd' does not change from the copy folder after navigating to another folder in the same tab, or navigating to another tab.  It will, however, change when starting a new session of webmin.

 I am not sure where the value of '$cwd' comes from, however. I have traced it as far as filemin/filemin-lib.pl:76's "$in{'path'}" and from there am not familiar enough with the WebminCore architecture to figure "$in" out.

**Comment by qooob** [comment]
Can I see the screenshot, please?

**Comment by chrispolley** [comment]
Sorry, I thought email attachments on my first reply would have gone into the github thread.  Here is a screenshot of the toolbar area.

![filemanager](https://cloud.githubusercontent.com/assets/7552908/22445134/a454ea64-e70b-11e6-9991-6fdbd4a4f806.JPG)

**Comment by qooob** [comment]
I see.

What you did is you switched in Authentic Theme from the old theme, while changing there an option that is only displayed in legacy themes.

Switch back to Gray Theme, go to File Manager configuration and toggle to group tools bar.  After that your problem should be solved.

Good luck.

**Comment by qooob** [comment]
https://github.com/webmin/webmin/pull/486

**Comment by chrispolley** [comment]
Confirmed, changing this setting also corrected the problem with
copy/paste.
