### ISSUE TITLE
WebminCore: Inconsistently generated table

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#661]
Hi,

I have the latest Ubuntu 16.04 with the latest Virtualmin, using the latest FF and the latest theme.

When I go: Webmin->System->Software Package Updates->Only new

put in **Find packages matching:** eg.: libjpeg  and **Search**

then I see some packages but the screen goes down and I cannot screen up using mouse scroll ;(

Looks like a bug or conflict with .js ?? (...) Do you have the same issue?

**Comment by qooob** [comment]
Hi,

Yes, this is the Webmin bug that delivers inconsistent, have 5 `<th>` and 4 `<td>` on the rows. It has to be fixed server side. I will let Jamie know.

**Comment by jcameron** [comment]
Ok, this will be fixed in the next Webmin release.

**Comment by qooob** [comment]
Thank you

**Comment by qooob** [comment]
I can confirm that the patch is working fine.
