### ISSUE TITLE
How can I completely remove the terminal functionality

### ISSUE THREAD

**Issue by ftrojahn** [qooob/authentic-theme#662]
Hello,

I like authentic theme very much, but I'd like to completely shut off the terminal code.

Disabling "show terminal button" doesn't do this, as shortkey "k" does open it, then.

So, as stated in subject: how can this "terminal" be completely disabled in Webmin when using authentic-theme?

Thank you very much for your efforts.

**Comment by qooob** [comment]
Hi,

You can do it by disabling `Command Shell` module in user ACL.

**Comment by qooob** [comment]
Why are you trying to do this? Do like terminal or for some other reasons?

**Comment by ftrojahn** [comment]
Thank you for your quick reply. Just found out from virtualmin forum that two-factor-authentication is a way to go. If I have password-less openssh-key only access to ssh, I'd appreciate ssl client certificates for webmin/virtualmin access, but 2FA perhaps is enough.

**Comment by qooob** [comment]
It's possible to edit any file on the system using File Manager for instance and execute any code.

Disabling shell will not save you from anything. 2FA is good.
