### ISSUE TITLE
CSF 9.30 and authentic-them: firewall configuration button is missing

### ISSUE THREAD

**Issue by paolokappa** [qooob/authentic-theme#663]
Hi Ilia,
I tried to re-install your beautiful theme but still having trouble with CSF 9.30.
A button (CSF firewall configuration) is missing :(
Any workaround?

Thanks!
Paolo Caparrelli

![2017-02-18_08-23-58](https://cloud.githubusercontent.com/assets/7937286/23091368/b323e16e-f5b4-11e6-8697-9261837ad110.jpg)

**Comment by qooob** [comment]
Look up-left at the table header (cog). It's where all Webmin configuration buttons are. 😉

**Comment by LazerJD** [comment]
Hi - You closed this too early. The issue still exists with your theme in webmin v10, as well. There are no settings to manage in 'up-left at the table header (cog)' that change the availability of the 'Firewall Configuration' button in the CSF plugin. I've been through the CSF & webmin configuration files and can't see any settings that affect that. Changing back to any other theme returns the button.

**Comment by qooob** [comment]
@LazerJD 
>Hi - You closed this too early. The issue still exists with your theme in webmin v10, as well. There are no settings to manage in 'up-left at the table header (cog)' that change the availability of the 'Firewall Configuration' button in the CSF plugin. I've been through the CSF & webmin configuration files and can't see any settings that affect that. Changing back to any other theme returns the button.

Have a look:

https://rostovtsev.ru/pub/src/authentic/18.40b/working_csf_config_button.webm
