### ISSUE TITLE
File Manager: Does not delete marked files not on current page

### ISSUE THREAD

**Issue by ChriZathens** [qooob/authentic-theme#666]
Hi there!
Thanks for the awesome theme!

I discovered a small bug (I hope it is not a duplicate - did a search but could not locate one, )though:

I have a folder with many files, about 15 pages
I wanted to delete some of the files
I found 3 that were to be deleted on page 2
Skimmed through the rest of the pages until I reached the last one and since I did not find any other useless files, while still in page 15,  I clicked on the delete icon, but nothing happened
On the top left corner I see that 3 files are already selected
![capture](https://cloud.githubusercontent.com/assets/8545172/23126939/b3886656-f781-11e6-8f9d-0d3918a5a0e0.JPG)

As mentioned, I clicked the delete icon while on page 15 and those files were from page 2 
If I go back on page 2 i see them still selected.
I click on delete icon and all work as expected.
If I go to page 15 and select at least one file from that page and click on the delete icon, the window does popup and asks for the confirmation for all the selected items

* What is your server-side OS and its version?
_Ubuntu server 12.04 LTS, webmin 1.831, authentic 18.32_
* What is your client-side OS, browser and its versions?
_Windows 8.1 64bit, Chrome Version 56.0.2924.87_
 * What are the steps to reproduce the issue
_Go to a folder with many files separated in pages
Go to page 1 - select a file
Go to page 2 (notice that file is mentioned as selected)
Click delete -->nothing happens
Do back to page 1 - click delete --> all ok
don't delete anything, go again to page 2, select at least one file there- click delete--> popup appears normally and includes all selected files_

I hope I explained well
Have a nice day and thanks again!

**Comment by qooob** [comment]
Hi,

Thank you for reporting this issue.

I have a question, does the file actually gets deleted? Did you try after failure deletion, to check if the file was deleted. It looks more like an interface problem.

It's ok, you can leave it as it is, if you don't have time to double check. I will manage it from here.
