### ISSUE TITLE
Firefox Locks Up Over Time

### ISSUE THREAD

**Issue by dumorian** [qooob/authentic-theme#669]
Server softwares CentOS 6 and 7
Windows 7 64 Pro
Firefox 51.0.1

I am at the moment running 5 tabs which are Webmin/Virtualmin systems running the Authentic Theme. I also have a number of other varying tabs open at the same time. This has worked fine in the past and only became an issue after switching these system to the Authentic Theme.

After about a day of working, hitting pretty much every interface within multiple Webmin/Virtualmin/Cloudmin systems, suddenly Firefox begins to stall. Checking Task Manager, I have found Firefox is using just under 3 GB of private memory. It goes into and out of a stall mode, eventually becoming totally unusable or it crashes.

Restarting Firefox fixes the issue. After the restart and after waiting plenty of time for it to fully load and settle down, I see it is using right at 500 MB of private memory. I haven't watched task manager over time to see how it gets to almost 3 GB.

**Comment by qooob** [comment]
Hi,

It sounds normal. _Authentic Theme_ runs using frames, with many dependencies and quite resourceful. Having 5 tabs opened, creates even more load. 

Personally, I must say that I have very good hardware and at the same time _Firefox_ feel quite slow for me. At the same time _Chromium_ does it very fast and smooth with even more tabs opened. This is the reason why I personally gave up on _Firefox_.

In the future, when the version [20.00](https://github.com/qooob/authentic-theme/tree/nuevo) is released and as it's going to be a single frame interface, things will get faster.

I already removed all unnecessary and heavy libraries away from constant page load/render. I don't think I can do any better in this regard at this particular moment.

**Comment by dumorian** [comment]
Thanks gooob! Yes, Chrome seems to operate using a separate instance for each tab while Firefox operates under one. Makes sense. Thanks for the great interface!

**Comment by qooob** [comment]
Thanks and you're welcome.

Look for the new 18.40 as it will include the dark palette for the right frame. :wink:
