### ISSUE TITLE
Edit Virtual Server page, missing two categories: Services, Logs and Reports

### ISSUE THREAD

**Issue by jusfreeman** [qooob/authentic-theme#67]
Hi Ilia,

Thanks for your great work, awesome.

I've been testing this theme in a local Virtualmin install and noticed that when I edit a Virtual Server it does not display the two categories: Services, Logs and Reports

In this case, I need to be able to access these to set up Git repository using the Virtualmin Git plugin, https://www.virtualmin.com/documentation/web/git

If I switch back to the default Virtualmin theme I can access the following menu and items for the Virtual Server:
[–] Services
Configure Website
Git Repositories
PHP 5 Configuration
PHP 5.4 Configuration
PHP 5.5 Configuration
PHP 5.6 Configuration
Preview Website
[–] Logs and Reports
Apache Access Log
Apache Error Log
Logged Webmin Actions

Was this an intentional change to not display Services, Logs and Reports categories for the Virtual Server?

Best wishes!

**Comment by qooob** [comment]
Thank you for liking my theme! :) 

What you've reported has already been discussed here: https://github.com/qooob/authentic-theme/issues/7.

I will fix it as soon as I have time to work on the theme - most likely in version 9.0.0.

Best regards,
Ilia
