### ISSUE TITLE
MySQL/PostgreSQL: Deleting a record from the data-view doesn't update the current index

### ISSUE THREAD

**Issue by dovzamir** [qooob/authentic-theme#672]
Webmin 1.831 on ubuntu 16.04lts using firefox 52.0 (64-bit).
When viewing records in a list (view data) in mysql and delete the first record the screen updates to reflect the new state. However if I then choose to edit a subsequent record webmin brings up the wrong record not the record which was chosen.
For example, I delete the first record in view data, mark the second (now first) record for editing, I am actually editing the third record and not the second record.

**Comment by qooob** [comment]
Hi,

:open_mouth:  Confirmed! 

Thanks!

**Comment by qooob** [comment]
Please update the theme from cloning from the repo. Give it a test. It will be added in 18.40 very soon.

**Comment by dovzamir** [comment]
מצטט את Ilia Rostovtsev <notifications@github.com>:

> Please update the theme from cloning from the repo. Give it a test.  
> It will be added in 18.40 very soon.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       

Hi Ilia,

Will try as ASAP and get back to you...

Links:
------
[1] https://github.com/qooob/authentic-theme/issues/672#issuecomment-286404299
[2]

**Comment by dovzamir** [comment]
מצטט את Ilia Rostovtsev <notifications@github.com>:

> Please update the theme from cloning from the repo. Give it a test.  
> It will be added in 18.40 very soon.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       

Hi Ilia,

Installed and tested. Looks good. Thanks!!

Sincerely,
Dov Zamir.

Links:
------
[1] https://github.com/qooob/authentic-theme/issues/672#issuecomment-286404299
[2]

**Comment by qooob** [comment]
:+1:
