### ISSUE TITLE
Configserver firewall, CSF, does not show configuration button/page

### ISSUE THREAD

**Issue by cloud4g** [qooob/authentic-theme#674]
System:
Latest theme (18.32) and Webmin (1.830) versions installed.
Centos 7.3 
Nginx latest
PHP 5.6.9
MariadB 5.5
Epel, remi, virtualmin, and centos repos

I did a fresh install of Centos 7.3 and Virtualmin/Webmin Pro yesterday.  I installed configserver firewall, CSF, and the CSF module was working, including the configuration button on the first/landing page.

Then I disabled Apache, installed and enabled Nginx and did a yum update to assure all are latest versions.

After the change from Apache to Nginx, the configuration button is no longer visible.  This is not a 'problem' in that I had already configured CSF and can edit the csf.conf directly.  However, I would very much like to have the web interface through Webmin again.
![image](https://cloud.githubusercontent.com/assets/3057380/23828266/d79dc874-069a-11e7-85ae-39b8547d9cf6.png)

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/663

**Comment by cloud4g** [comment]
OK, I see the COG button... it changed from a text menu button.  Not as obvious but that works.
