### ISSUE TITLE
Uncaught TypeError: lang(...).toUpperCase is not a function...

### ISSUE THREAD

**Issue by reliq** [qooob/authentic-theme#675]
Hello,

I see the following error in my console. Not sure if this is why the theme is moving slow.

I have the latest theme (18.32) and Webmin (1.830) versions installed.

````
Uncaught TypeError: lang(...).toUpperCase is not a function
    at get_right_panel_sysinfo_data (parent.min.js?1832:6)
    at __si__bg_upd_exec (parent.min.js?1832:6)
    at parent.min.js?1832:6
````

I am running:
* Ubuntu 16.04.2
* Windows 10, Google Chrome 56.0.2924.87 (64-bit)
* I occurs on random pages.

Any help would be appreciated.

**Comment by qooob** [comment]
Hi,

This has been fixed already. It will be fine in 18.40
