### ISSUE TITLE
Theme: User link in navigation menu takes you to the wrong location in sudo-capable session

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#677]
When i press on my user name (in the left blue menu) the url seems to edit my login name but when i press on it i only see a page with `Selected user no longer exists!` (Return to previous page won't even work)
If i instead expand 'Webmin' and press on 'Webmin users' i can only see one user and that is 'root'.
This makes sense because every user that have sudo access can log into Webmin, right? So this will be very confusing when this edit user exists when users can login without having an account in Webmin.
So if the account doesn't exists it should tell me so and then goto the /acl/ page where all accounts exists (or at least have a button that will take me to the Webmin Users). As it is now it is very confusing and not very user friendly. It could even show a second message instead of only `Selected user no longer exists!` that will inform the user that sudo accounts always have access to Webmin.
It is your call but as it is now it doesn't work very smoothly...

**Comment by qooob** [comment]
Hi,

Could you please provide screenshots? I have no idea what you're trying to say. I'm sorry.

**Comment by Sopor-** [comment]
I hope this will make you understand :)

![picpick-2017 03 15-17 23 56](https://cloud.githubusercontent.com/assets/5789283/23960211/a1e71090-09a7-11e7-9bb7-1e7de6980550.png)

**Comment by qooob** [comment]
Yes,

This better. You're not logged in as root? As this administrative user?

**Comment by qooob** [comment]
Switching to Gary Theme produces the same result?

**Comment by Sopor-** [comment]
The Gray Framed Theme doesn't have that shortcut so i can't test it :(

I'm not logged in as root (i have always been told not to use the root account). I login using my regular user that have sudo access.

**Comment by qooob** [comment]
Strange. OK. What if you go to Webmin Users and click on your username, what do you get?

**Comment by Sopor-** [comment]
The only user here is 'root'. The account i'm logged in with only have sudo access and that is enough to log into Webmin.
When you install Webmin this message will show up:
`
Webmin install complete. You can now login to https://ubuntuserver:10000 as root with your root password, or as any user who can use sudo to run commands as root
`

**Comment by qooob** [comment]
Hi,

After discussing few things with Jamie, it appears that it's my bad.

I will fix it in 18.40.

**Comment by qooob** [comment]
Could you please go to line _[49](https://github.com/qooob/authentic-theme/blob/master/buttons.pm#L49)_ of `buttons.pm` and replace it with:

```Perl
. (get_env('base_remote_user') eq "root" ? "root" : $user)
```

Does it display things right for you?

**Comment by Sopor-** [comment]
Yes, this will take me to the root user.
I assume this is only when i use an account that doesn't exists in Webmin but do have sudo access?

**Comment by qooob** [comment]
Yes, this how Jamie explained it to me.

Please try to change available modules and see if it affects your session, just to double check.

**Comment by Sopor-** [comment]
I have created a new user in Webmin and when i press on the user name it will take me to his account and not the root account. So it seems to work perfect :)

**Comment by qooob** [comment]
Good to know.
