### ISSUE TITLE
Two-Factor Authentication have no button for 'Return to user list'

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#678]
In the 'Webmin Users' there are a bunch of buttons that will take me to different thing in Webmin (Convert Unix to Webmin users, Configure Unix User Synchronization...) and one of them will take me to the 'Two-Factor Authentication'. All the other pages have a button to take me back to the user list `Return to user list` except the Two-Factor Authentication page.

Authentic Theme 18.32

**Comment by Sopor-** [comment]
It seems that this 'Return to user list' doesn't exists in the Gray Framed Theme either so i need to talk to Jamie about this button or this is something that you can add in Authentic Theme without Jamie adds it?

**Comment by qooob** [comment]
I could but it's better if it's done on the server side.

**Comment by qooob** [comment]
No worries, I got your idea. You're right, it's missing. I will report it to Jamie, he will fix it.

**Comment by qooob** [comment]
However, it's important to notice, there is no back button only if Tow Factor Auth is not enabled.
