### ISSUE TITLE
Add create subserver link to Add Server page 

### ISSUE THREAD

**Issue by jasonsykoo** [qooob/authentic-theme#68]
When you click the Add Servers link on the sidebar of Virtualmin, you don't get the option to add a sub server that is owned by the current user. You only get the option of adding a new top level server. The only instance you see the option of adding a sub server is when you click list servers from the side bar navigation.

I have provided screenshots to help further understand this issue. 
![screenshot 2015-01-16 21 55 41](https://cloud.githubusercontent.com/assets/2774191/5787911/4cff3330-9dcc-11e4-9774-084d90e71980.png)
![screenshot 2015-01-16 21 58 32](https://cloud.githubusercontent.com/assets/2774191/5787916/889f8ef8-9dcc-11e4-8df1-d904137d4c37.png)

**Comment by qooob** [comment]
Alright, I see. This is the part of next few releases. I will try fixing it soon.

Thanks for reporting.

**Comment by qooob** [comment]
It will be added in version 9.0.0.
