### ISSUE TITLE
This page is asking you to confirm that you want to leave...

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#680]
Let us say we manually edit zones in Shorewall. If i made any changes to this zones file and i press the button 'Go back to zones list' i get a message from Firefox telling me if i want to stay or leave. If i press stay i will get back to where i was but now this button 'Go back to zones list' continues to spin and it will never stop. I can't press on it either because it is grayed out.

I will also report the button 'Undo'. As you can see in the picture the height is wrong.

![picpick-2017 03 19-17 19 33](https://cloud.githubusercontent.com/assets/5789283/24082658/9a25fbd0-0cc9-11e7-80ea-7580a17fea5f.png)

**Comment by qooob** [comment]
Yes, this is a very nasty thing to fix. Gimmi a moment..

**Comment by qooob** [comment]
Test it out.

Also, look at the new sexy hover effects over the action buttons :wink:

**Comment by Sopor-** [comment]
Sorry, but the ' Return to zone list' will still spin forever and i can't use the button.

**Comment by qooob** [comment]
No, it wouldn't. Just _**double**_ checked it for you. It's called cache.

Do the right click and hit reload on that page that you experiencing issue on. 

It will work then ...

**Comment by Sopor-** [comment]
That wasn't so easy to reload that page but i manage to do it and now it is working.
But the Undo button you have removed?

**Comment by qooob** [comment]
Yes, removed it. What the hell in the world it's needed for? 

Could you please report to Jamie that `shorewall6` is missing headers in edit mode!

![screenshot from 2017-03-19 21-42-40](https://cloud.githubusercontent.com/assets/4426533/24083700/2f4e15e4-0ced-11e7-91aa-bace9c7ee462.png)

Finally, I would recommend using _ConfigServer Security & Firewall (csf)_ as your system firewall. We have complete support for it.

**Comment by qooob** [comment]
`Return to` button is also broken..

**Comment by Sopor-** [comment]
Yes but it is sad that Config Server Firewall can't be installed from Debian or Ubuntu repositories :(

**Comment by qooob** [comment]
You don't need repos. It's not available for RHEL as well.

[CSF](https://configserver.com/cp/csf.html) provides straight forward installer. All you need is to [download](https://download.configserver.com/csf.tgz), unpack and run `install.sh` script. It will make things work with ease. 

It will prompt to update itself whenever update is available. _Webmin_ let's you know it in notifications!
