### ISSUE TITLE
theme_xhred_filemanager_selected_entry=Selected: %value entry

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#681]
In the file manager this `theme_xhred_filemanager_selected_entry=Selected: %value entry` should be needed a new string for plurals or else it sounds weird when selecting more than 1 entries ...
`Selected: 1 entry`
`Selected: 2 entries`

And when i'm reporting this i manage to find a typo in this string:
`theme_xhred_filemanager_target_conflict_1=Target conflic`
I believe the letter `t` is missing at the end...

**Comment by qooob** [comment]
Hi,

It's actually has an entry for plural, have a look:

```Text
theme_xhred_filemanager_selected_entries=Selected: %value entries
```
