### ISSUE TITLE
Add tooltip to the quick buttons?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#682]
It would be nice if these buttons (i don't know what you call those buttons?) did have some kind of help text so i know what they do. Tooltip would be nice. The first button that looks like a moon i haven't seen before and the `>_` will bring up a window that fill the screen and then i can't get rid of that window. Shouldn't there be an X somewhere to close it again?
I don't want to press the buttons if i don't know what they do.
![picpick-2017 03 19-22 32 09](https://cloud.githubusercontent.com/assets/5789283/24085016/b63a59f8-0cf4-11e7-87b8-c5527c44128c.png)

**Comment by qooob** [comment]
In case you made the last pull, there is already a tooltip for those. You should see it already? Did you clear the cache?

In order to get rid of something (console), you just need to hit ESC key, as usual.

**Comment by Sopor-** [comment]
The ESC did work, thanks! No tooltip on those buttons. I have forced reload, i even empty my cache but i still can't see any tooltip :(

**Comment by qooob** [comment]
Could you go to theme configuration, hotkeys section and send me the screenshot of it?

It's just should work.

**Comment by Sopor-** [comment]
Hotkeys? That will explains why i didn't got any tooltip, i have turned hotkeys off because i don't use them. I didn't know that tooltip is only visible when hotkeys are enabled. Why can't it still show a tooltip what the buttons do even if i turn off the hotkeys?
Instead of showing `Hotkey for page reload: Alt+R` it could show `Page reload` if i turn off hotkeys? Same for the rest of the buttons.
If i have to move the mouse pointer over a button to read what hotkey this button have i can use the mouse instead of trying to find the hotkey. I already have the mouse pointer over the button :)

**Comment by qooob** [comment]
I will see what I can do. That makes sense.

**Comment by qooob** [comment]
You were right. It's much better now.

Thanks!

**Comment by Sopor-** [comment]
Hmm, and i was almost finished with the sv.UTF-8 and now you add/change the language files... Next time i will let you add the Swedish language before i send in any more reports :)

**Comment by qooob** [comment]
There will be no more changes before the release in 3 hours. Please do it now, if possible and then I will add it to the package 18.40 tonight.
