### ISSUE TITLE
Theme: Operations in icon mode

### ISSUE THREAD

**Issue by lionslair** [qooob/authentic-theme#684]
Trying to edit the items in the DHCP module but when I click the icons to edit any of hosts or subnets it just turns yellow. I am not able to edit.

Provide the following information:
* 	Debian Linux 8
* Linux Ubuntu 16.04 LTS Chrome Version 57.0.2987.110 (64-bit)
* DHCP Server ISC DHCPd version 4.3.1

**Comment by qooob** [comment]
Hi,

In order to do it you need to do double click.

I understand, as it seems to be the basic issue.

**Comment by lionslair** [comment]
Oh..... my fault then. I don't think there is another module where I need to double click. I am used to the single click from the old webmin themes. This far surpasses them though . Great work.

**Comment by qooob** [comment]
No, no. I will finally make this explicit. Not all can guess right and it already happened.

**Comment by qooob** [comment]
Expected in 18.41
https://rostovtsev.ru/pub/src/authentic/18.41b/clearer_icons_actions.webm
