### ISSUE TITLE
Theme: Session check on background calls

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#685]
When i get logged out from Webmin (i don't know why i get logged out because i have disabled it) the green square with the spinning arrow will never stop spinning. Can you do something about this? Instead of only this spinning arrow it could tell me that i have been logged out or pop up a notice about it instead of an endless spinning.
In the Gray Theme it wasn't detectable until i pressed any buttons but in your theme it is different because you have auto update, so there must be a way to detect that i'm logged out?
![authentic_theme_spinning](https://cloud.githubusercontent.com/assets/5789283/24167758/38032580-0e78-11e7-969a-a978eb4eb5ef.gif)

**Comment by qooob** [comment]
Hi,

Hmm, I remember I was making such check-ups for background calls. By design it should redirect you to login page.

Thank you for reporting out. I will add this to my checklist.

**Comment by qooob** [comment]
That is the strange glitch that you have had there. 

I have double checked and anytime the session is expired and the background call happens, it shows the login screen (in call modules). It works for regular authentication and for PAM as well.

Here is the [video-screencast](https://rostovtsev.ru/pub/src/authentic/18.41b/working_auth_call_on_no_session.webm)

You can reproduce/test it your-self, to make sure that it's working!

**Comment by Sopor-** [comment]
I was on my way to report this issue again but now i know when this happens. If i run your theme as per user but i still have the old theme as global. Then it continues to spin and it won't show the login page.
So try again @qooob and see if you can reproduce it now when you know more.
