### ISSUE TITLE
DHCP: Operations in icon mode

### ISSUE THREAD

**Issue by BarryHavenga** [qooob/authentic-theme#686]
Please make sure that you have latest theme (18.40) and Webmin (1.831) versions installed. **Check**

Provide the following information:
* What is your server-side OS and its version?  **Ubuntu Server 16.04 LTS**
* What is your client-side OS, browser and its versions? **KDE Neon 16.04**
* What are the steps to reproduce the issue: **Click on icon of configured host.  Icon turns yellow but configuration screen does not open.**

**Comment by qooob** [comment]
How about double click on it?

**Comment by BarryHavenga** [comment]
Hi Ilia.


I tried: Doesn't work.

To check that it was theme related I also reverted to the default theme 
and then it worked again.


Regards


*Barry Havenga*


*Confidentiality Notice:*

This message contains information intended for the perusal, and/or use 
(if so stated), by the stated addressee(s) only. The information is 
confidential and privileged. If you are not an intended recipient, do 
not peruse, use, disseminate, distribute, copy or in any manner rely 
upon the information contained in this message (directly or indirectly). 
ActiV Capital does not accept responsibility for any amendments made to 
any attached documents without its approval. If you receive this message 
in error, notify the sender immediately by e-mail, fax or telephone and 
return and/or destroy the original message. The views or representations 
contained in this message, whether express or implied, are those of the 
sender only, unless that sender expressly states them to be the views or 
representations of an entity or person, who shall be named by the sender 
and who the sender shall state to represent. No liability shall 
otherwise attach to any other entity or person.

**Comment by qooob** [comment]
Barry, I'm sorry, which module are you talking about?

**Comment by BarryHavenga** [comment]
Hi


Apologies:


*Servers>DHCP Server>Host & Host Groups*


Normally if one clicks on a particular host, the edit host property page 
opens.



Regards


*Barry Havenga*


*Confidentiality Notice:*

This message contains information intended for the perusal, and/or use 
(if so stated), by the stated addressee(s) only. The information is 
confidential and privileged. If you are not an intended recipient, do 
not peruse, use, disseminate, distribute, copy or in any manner rely 
upon the information contained in this message (directly or indirectly). 
ActiV Capital does not accept responsibility for any amendments made to 
any attached documents without its approval. If you receive this message 
in error, notify the sender immediately by e-mail, fax or telephone and 
return and/or destroy the original message. The views or representations 
contained in this message, whether express or implied, are those of the 
sender only, unless that sender expressly states them to be the views or 
representations of an entity or person, who shall be named by the sender 
and who the sender shall state to represent. No liability shall 
otherwise attach to any other entity or person.

**Comment by qooob** [comment]
I added hosts but I could enter them for edit making double click very quickly.

Alright, I see the issue. I will change the way it works. I agree it's not intuitive.

https://github.com/qooob/authentic-theme/issues/684

**Comment by BarryHavenga** [comment]
Many thanks


Regards


*Barry Havenga*


*Confidentiality Notice:*

This message contains information intended for the perusal, and/or use 
(if so stated), by the stated addressee(s) only. The information is 
confidential and privileged. If you are not an intended recipient, do 
not peruse, use, disseminate, distribute, copy or in any manner rely 
upon the information contained in this message (directly or indirectly). 
ActiV Capital does not accept responsibility for any amendments made to 
any attached documents without its approval. If you receive this message 
in error, notify the sender immediately by e-mail, fax or telephone and 
return and/or destroy the original message. The views or representations 
contained in this message, whether express or implied, are those of the 
sender only, unless that sender expressly states them to be the views or 
representations of an entity or person, who shall be named by the sender 
and who the sender shall state to represent. No liability shall 
otherwise attach to any other entity or person.

**Comment by qooob** [comment]
It will be added it 18.41 release quite soon.

https://rostovtsev.ru/pub/src/authentic/18.41b/clearer_icons_actions.webm

**Comment by BarryHavenga** [comment]
Thanks


Regards


*Barry Havenga*


*Confidentiality Notice:*

This message contains information intended for the perusal, and/or use 
(if so stated), by the stated addressee(s) only. The information is 
confidential and privileged. If you are not an intended recipient, do 
not peruse, use, disseminate, distribute, copy or in any manner rely 
upon the information contained in this message (directly or indirectly). 
ActiV Capital does not accept responsibility for any amendments made to 
any attached documents without its approval. If you receive this message 
in error, notify the sender immediately by e-mail, fax or telephone and 
return and/or destroy the original message. The views or representations 
contained in this message, whether express or implied, are those of the 
sender only, unless that sender expressly states them to be the views or 
representations of an entity or person, who shall be named by the sender 
and who the sender shall state to represent. No liability shall 
otherwise attach to any other entity or person.
