### ISSUE TITLE
Linux Firewall displays poorly with multiple IPs 

### ISSUE THREAD

**Issue by adiastra** [qooob/authentic-theme#687]
When adding a long list of IPs to a firewall rule, you can not add spaces so the rules summary screen does not break the line at the comma. This pushes the display off to the right too far. Also when ENTERING this information the provided "text box" is not sufficient and should be a "text area" instead
see http://i.imgur.com/2c9Rpip.jpg for example 

To recreate this just add a large list of comma separated IPs ( 10 or more without spaces[example of formatting 67.174.104.101,96.244.12.80,98.231.163.151,192.88.134.0/23,185.93.228.0/22,66.248.200.0/22,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/12,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,199.27.128.0/21])
 to "Source address or network" in any rule then save it and look at the rules summary screen.

Spaces are not allowed in iptables so a different solution would be to allow for multiple lines to be input and then create the proper formatted input (see above) before adding it to the rule.

**Comment by qooob** [comment]
May be `word-wrap: break-word` on the line would make things look better? Could you try adding using browser's DevTools?

**Comment by adiastra** [comment]
where would you like me to enter word-wrap: break-word ? 
im not a css wiz. in the <label> tag?

**Comment by qooob** [comment]
On the parent container, like `td` I guess or whichever tag is affecting it. Just right click on the text and click inspect. At the top, where element style is, add the line above and see if it works. 

And if it's hard for you, please don't bother. I'll figure this out.

**Comment by adiastra** [comment]
did this 
http://i.imgur.com/DsvfXz5.jpg
no effect

**Comment by adiastra** [comment]
tried this too 
`style="width: 100%; word-wrap: break-word; table-layout: fixed;"` no dice

**Comment by qooob** [comment]
This will fix it for you. :wink: 

Thanks for reporting.

**Comment by adiastra** [comment]
How can I apply the hotfix? or will it be in the next release?

**Comment by qooob** [comment]
It will be. Or you can easily do it using console.

https://github.com/qooob/authentic-theme#how-to-update-authentic-theme-manually

**Comment by adiastra** [comment]
Thanks that's perfect!

**Comment by qooob** [comment]
:wink:  good to know.

**Comment by nsaneman** [comment]
@qoob Hopefully you've got notifications on. This issue is back again.

[Firewall](https://i.imgur.com/yGNXkpO.jpg)

I'm using 19.02. If I downgrade to 19.01 it looks a little better, although it adds a scrollbar to the bottom of the screen.

**Comment by nsaneman** [comment]
@qooob Hopefully you've got notifications on. This issue is back again.

![Firewall](https://i.imgur.com/yGNXkpO.jpg)

I'm using 19.02. If I downgrade to 19.01 it looks a little better, although it adds a scrollbar to the bottom of the screen.

**Comment by qooob** [comment]
What would be expected output?

**Comment by qooob** [comment]
... to wrap?

**Comment by nsaneman** [comment]
Preferably truncate the text with ellipsis so that move/add are always displayed to the right.

Maybe the checkboxes could have a little padding too? They're currently not perfectly positioned.

**Comment by nsaneman** [comment]
Preferably truncate long text with ellipsis so that move/add are always displayed to the right without scrolling. I know that some people might want to see all of the IP addresses though, but I don't think wrapping would work well.

If you don't agree with using ellipsis then just make it use the scrollbar like in 19.01. It'll look a little poor, but it's functional.

**Comment by qooob** [comment]
I do believe that wraping looks great here.

**Comment by qooob** [comment]
Example:

![screenshot from 2017-12-02 18-17-01](https://user-images.githubusercontent.com/4426533/33517008-234dd4bc-d78d-11e7-9fcc-d70decc663d8.png)

**Comment by adiastra** [comment]
I totally agree. I would prefer to see everything wrapped instead of
truncated.

**Comment by nsaneman** [comment]
That actually looks better than I thought it would. Thanks for addressing this issue.
