### ISSUE TITLE
When selecting favorites (the star) the mouse cursor shouldn't be a 'Text select' pointer

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#688]
When i want to add a page as favorite i press the star in front of the name of the page name, but it isn't obvious that this is how i add the page to the favorites. Maybe the star could change to yellow when the mouse pointer hover over the star to indicate this is a button? Maybe you could use the 'Link select' mouse pointer instead so it is easy to understand that this is something you can press on...
![picpick-2017 03 22-17 23 02](https://cloud.githubusercontent.com/assets/5789283/24209441/9417ef1e-0f26-11e7-9bb3-e491cfb54916.png)

**Comment by qooob** [comment]
After you click it turns yellow, right?

**Comment by qooob** [comment]
Adding a tooltip for it as a good idea.

**Comment by Sopor-** [comment]
Yes, it will change to yellow when i press it. What i meant was it could indicate that this is something that you can press on, but your idea about a tooltip should also work :)

**Comment by qooob** [comment]
I think there is no need for the tooltip.

Give it a try.

Thanks for your precious recommendations. Keep up.
