### ISSUE TITLE
Virtualmin: Saving on manual edit DNS Records fails in case of an error

### ISSUE THREAD

**Issue by multiwebinc** [qooob/authentic-theme#689]
Provide the following information:
* What is your server-side OS and its version? **Debian 7**
* What is your client-side OS, browser and its versions? **Chrome**

Steps to reproduce:

- Add a domain with mail enabled
- Go to YourDomain.com > Server configuration > DNS records > Manually edit records
- I want the domain to use Godaddy's MX records, so remove the MX entry and add:

````
example.com.	IN	MX	0 smtp.secureserver.net.
example.com.	IN	MX	10 mailstore1.secureserver.net.
````

- At the bottom you have the option to choose `Save` or `Save and close`. Choose `Save`. A success message then appears, however if you refresh the page, you can see that they are *not* saved.
- If you click on `Save and close` you get an error message saying that you have to first disable email to update the MX records.
- Once you disable email, it works correctly.

**Comment by qooob** [comment]
It's likely that something like this could happen as there is no error handler on the theme side for _Save_ actions. I didn't add it as I couldn't any place where it would be needed.

I tried what you said, but I coudn't reproduce it. Any time I add any other MX record it just saves properly.

I need the screenshot with the exact message? Could you do it?

**Comment by qooob** [comment]
..and one more, what is your Virtualmin version?

**Comment by multiwebinc** [comment]
Weird. I'm unable to reproduce the error after I re-enable mail for the domain and try to re-add those MX records, so it might have been some sort of manual configuration I had done to one of the configuration files somewhere sometime. I'm just going to close this. If anyone else can reproduce the error, feel free to reopen.

**Comment by qooob** [comment]
I wish you just told me an error message?

I would want to make an error handler for this save in background feature.

**Comment by multiwebinc** [comment]
@qooob Unfortunately I didn't copy it down when I got the error last time, however doing a quick Google search I believe it was:

> Error: This domain has email enabled, but none of the MX records point to it.

**Comment by qooob** [comment]
I have this message as not post-save but on the page DNS Records marked red.

It reason why it couldn't be saved is in case of broken config file. For example, if you remove one of `)`, then it will not be saved correctly.

**Comment by qooob** [comment]
You made a good point.

I have added error-handler.
