### ISSUE TITLE
Show Password...

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#69]
I've been noticing that when you click the "Show..." link for showing a password under "Edit Virtual Server > Configurable settings", upon showing the popup window with the username and password the right panel of the main window seems to show the "loading image" and just sits on that until you either click another link from the left panel.

Attached is a screenshot showing you what I'm referring to. I've blacked out sensitive information for security reasons.

![show-password-error](https://cloud.githubusercontent.com/assets/4305218/5792059/ef111ba6-9eb8-11e4-9070-c11694256777.png)

**Comment by qooob** [comment]
I wish I could test it but I don't have this link. I know what is causing the problem though. I will fix it right now but please report back upon next release, if the problem is gone.

So far, to dismiss `stuck` loader, do double right click with your mouse on it.

Thanks for reporting.
