### ISSUE TITLE
Cloudmin: Status creating server not visible

### ISSUE THREAD

**Issue by mariomieldijk** [qooob/authentic-theme#690]
Hi,

During creating a virtual machine within Cloudmin there is no output visible on the screen during the process. On the end the whole output is visible. It would be preferable to see it as well during creating, because you want to see the progress. That is the only withdrawal to use the theme. 

Thanks,

**Comment by qooob** [comment]
What is your theme version?

**Comment by qooob** [comment]
:up:

**Comment by qooob** [comment]
What is your theme version??

**Comment by qooob** [comment]
It's already fixed in [#45770](https://www.virtualmin.com/node/45770)

**Comment by mariomieldijk** [comment]
Hello version 18.32
