### ISSUE TITLE
Serif font used on some pages

### ISSUE THREAD

**Issue by BrettRow** [qooob/authentic-theme#691]
Webmin 1.831 and 18.40 theme running on Ubuntu 16.04 and accessed via MS Edge from Windows 10.

The theme font is set to Roboto (default) but the System pages Bootup & Shutdown, Scheduled Cron Jobs and Software Packages are all using a serif font of some sort, where all other pages are sans-serif.

I have tried clearing the cache but see no difference.

**Comment by qooob** [comment]
Can you provide the screenshot please?

**Comment by qooob** [comment]
I had to boot to Windows 10 to check it using Edge Browser.

I can't reproduce your issue.

The problem could happen, in case you set font first on one machine (Windows) and then load it on the other (Linux or Mac). In case selected previously  fonts ware not available on the current machine, it might look broken.

The theme just adds font files to the header. Nothing special or broken can be here that I could fix.

**Comment by BrettRow** [comment]
![webmin_font_1](https://cloud.githubusercontent.com/assets/8628540/24340507/f0a57500-12b2-11e7-9f2b-63a4258aef7f.png)
![webmin_font_2](https://cloud.githubusercontent.com/assets/8628540/24340510/f0ada5b8-12b2-11e7-9c8a-f114812d6083.png)
![webmin_font_3](https://cloud.githubusercontent.com/assets/8628540/24340509/f0aaf322-12b2-11e7-9d76-adfe5aabf646.png)
![webmin_font_4](https://cloud.githubusercontent.com/assets/8628540/24340508/f0a9c0ce-12b2-11e7-8e22-21767679bcfb.png)

No 1 is the font I see almost everywhere in WebMin using Authentic Theme. The other three are what I am seeing as mentioned previously. WebMin is ONLY accessed via my computer and I only use Windows.

It is not a train smash, just odd that only a few pages show this anomaly.

**Comment by qooob** [comment]
That doesn't look good. Can you right click on the right page and see `frames source code`.

Can you find inside of `head` tag, embedded fonts in all is those pages?

**Comment by BrettRow** [comment]
This is the only font reference I can find inside the head tag:
<link href="/unauthenticated/css/fonts-roboto.min.css?1840" rel="stylesheet">
There is no mention of any font names anywhere else in the page source.

**Comment by BrettRow** [comment]
Missing from above
link href="/unauthenticated/css/fonts-roboto.min.css?1840" rel="stylesheet"

**Comment by qooob** [comment]
Do you have `link href="/unauthenticated/css/fonts-roboto.min.css?1840" rel="stylesheet"` in all of those files, working and not?

Did you try other browser? Or Incognito mode?

**Comment by BrettRow** [comment]
The link is present on all pages I viewed.
Edge in normal or InPrivate shows the font aberration, Chrome shows correctly, IE11 has another set of problems on my computer but does seem to show the fonts correctly.
For the moment I will stick to Chrome for WebMin.

**Comment by qooob** [comment]
Are you saying that Edge is working fine in private mode?

**Comment by BrettRow** [comment]
No, Edge shows the bad font in both modes.

I did notice however on one run in Edge that the Bootup page was rendering in the correct font. I then switched to check if the other pages had changed (they had not) and when I went back to Bootup it was back on the incorrect font.

**Comment by qooob** [comment]
It sounds like local problem.

Why don't you set `Use system fonts`? It looks quite good in Windows?

In case you love Roboto, you could install it locally by [downloading](http://www.fontsquirrel.com/fonts/download/roboto) them.

**Comment by BrettRow** [comment]
I will try both options suggested.
One other anomaly I noticed in Edge: if I view the MIME Types page (which has correct font) followed by one of the problem pages, the problem page now has the correct font. No other combination of pages seems to do this.

**Comment by qooob** [comment]
:open_mouth: 

Please try suggested solution. Let me know how it works for you.

Do you have latest Edge installed?

In my humble opinion, there is nothing better than _Chromium_.

**Comment by BrettRow** [comment]
After installing Roboto locally, the problem seems to have been cured.

My Edge is kept up-to-date as per Windows 10 Updates.

**Comment by qooob** [comment]
Alright! Good to know.

**Comment by qooob** [comment]
https://support.wix.com/en/ticket/dc748d6f-2991-4e84-a5cd-d0eb354c1e1c
