### ISSUE TITLE
Button for Backup logs...

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#692]
Even in the latest theme there is button missing for "Backup logs..." Nice to have it in the next release. Thx

![back](https://cloud.githubusercontent.com/assets/7549566/24301901/b3260ab6-10a8-11e7-9ddd-f3eb4be5cd6f.png)

**Comment by qooob** [comment]
Sure, it seems like a new feature I wasn't aware of.

:wink: 

Try latest commit.
