### ISSUE TITLE
Theme: File chooser click operations

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#693]
When i want to install the CSF module for Webmin i do that by pressing the button after `From uploaded file`. A new window will open so i can browse to the file but if i click on a folder name it will close the window and the same thing happens if i click on the yellow folder to the left of the folder name. So how do i browse into the folder? Of course, i double click on the yellow icon!
Here is the big difference between your theme and the Gray theme. If i single click on the yellow icon nothing will happens in the Gray theme but in your theme it will select it the same way single click do on the folder name. This will make the user very confused (at least i got confused).

I'm using Firefox and 18.40 theme. Tested in both Windows and Ubuntu.

**Comment by qooob** [comment]
Well, maybe. But it's like browsing thing and  all File Managers want you to do double-click by default to descend into folder, right?

There are no much options, that I could use. I know about the way it worked before, I didn't find it anyway better or less confusing.

**Comment by Sopor-** [comment]
If a single click won't work when i press on the yellow folder icon then i will try to double click on it, but if i can single click on it then i believe it work the same way as when i press on the folder name. It took me some time before i figure it out how to do it. I even started to write a report about it but when i was playing around with it i manage to find out how it worked but it was after i have changed to the Gray theme. When i found out that nothing happens when i single click on the yellow icon, i then tried double click on it and it worked. I then change the theme back to Authentic theme and when i tried to double click it worked here too. This is no regular file manager, at least not the one in the Gray theme so you can never anticipate how it should work.

**Comment by qooob** [comment]
OK,

Any direct suggestions of how it _should_ be?

**Comment by Sopor-** [comment]
I vote for the same way as the Gray theme work.
Single click on the name will select it and close the "file browser".
Double click on the yellow folder icon opens the folder and let me continue browse.
Single click on the yellow folder icon do nothing. To select you need to click the name and not the folder icon.

**Comment by qooob** [comment]
Hmm.
It's not the way the default works, in my opinion.

What if you need to select the folder?

**Comment by Sopor-** [comment]
If you need to select the folder you click on the name instead of the icon.
When i tested Gray theme it worked like that, but i can test it again.

**Comment by qooob** [comment]
Ok, 

I will rework it very soon.
