### ISSUE TITLE
Pie charts getting cropped

### ISSUE THREAD

**Issue by kreationnext** [qooob/authentic-theme#694]
Hello,
You changed the canvas width from 160=>170 and the circles are getting cropped.
https://drive.google.com/file/d/0B1yUtDYgrFZwMUY4R2hfX25MLTg/view?usp=sharing

Server OS: centos 6
browser: firefox. chrome
Reproduce: just updated from 18.32=>18.40

Refreshed page/cleared cache but it did not work

**Comment by qooob** [comment]
Yes, right.

Could you make it thinner? Or you don't like it that way?

**Comment by kreationnext** [comment]
I like it at width = 8, changed it 4 but still the same issue

**Comment by qooob** [comment]
What if you changed it to 165 in the code? Is it OK, then?

**Comment by kreationnext** [comment]
don't know which file to change... can you give me the path

**Comment by qooob** [comment]
Search for 170 in content.min.js

**Comment by kreationnext** [comment]
changed it to 165, then to 160 and still almost the same result
https://drive.google.com/file/d/0B1yUtDYgrFZwWnNCU05JSWFEUDg/view?usp=sharing

**Comment by qooob** [comment]
What is the screen res you got?

**Comment by kreationnext** [comment]
1366x768

**Comment by qooob** [comment]
Hey,

I have no clue why you're having such output. I made things more straight forward. You can now set the scales' diameter to satisfy your needs. 

I couldn't reproduce it. As we had already the options for width and scale lengths, adding diameter will not hurt much.

Enjoy ..

**Comment by kreationnext** [comment]
the issue was with scale length. I changed it to 0.01 to 4 and the issue
was gone
