### ISSUE TITLE
Theme: Automatic update

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#695]
I was running Authentic theme 18.30 and i know you released a new version so i activated the 'Check for Authentic Theme updates' and i could see there was a new version available so i pressed the Update button and it started to happen things but after a few seconds i was back to the Dashboard and it was still version 18.30. I then tried again, same thing and it was still version 18.30. I then tried a third time and when it was finished i got the announce window that 18.40 was installed. Why do i need to do it three times? I noticed Github was slow so maybe you need to wait longer for it to download, install and then restart Webmin (or you don't restart Webmin after an update?)?
All four computers are now updated to 18.40 so i can't test it so easy. I can of course download 18.30 and manually install it if you want me to help you find the reason to this issue.

**Comment by qooob** [comment]
I think you will not be able to reproduce it. It happens sometimes, as connection to GitHub is dropped.

It's not the theme issue as far as I'm aware. I could never reproduce it twice.

What happens is when you put a link to input field and hit install, it's just getting dropped/skipped. In ordinary install there could be a message.

**Comment by Sopor-** [comment]
And you are sure about this? It is not because Webmin is running on a Raspberry Pi 2? It will take some time to download and extract on an RPi2.
I updated your theme on my i5 (SSD) by doing a 'git pull' but next time i will use the Update button to see if it happens on that computer too.

**Comment by qooob** [comment]
It happened with me many times. Anytime later it just worked fine.

It's hard to figure out why it was happening..

I will try to add more delay when the file is inserted into the field, it's the only thing I can think of!
