### ISSUE TITLE
'Keep slider always visible' on/off i don't even have to press the Save button

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#697]
When changing 'Keep slider always visible' on/off i don't even have to press the Save button. If you have a Save button it should also have to be used. If i want to undo my changes, how do i do then?
I noticed that if i don't press save and leave the page and when i get back it will still show the slider but 'Keep slider always visible' is still set to 'off'.
I believe it was the same behavior on the notification tab in #673.

v18.40

**Comment by qooob** [comment]
Yes, it's only active until the first full page reload. Right?

**Comment by Sopor-** [comment]
Maybe it is, but it shouldn't be active before i press the Save button. It was the same behavior for the notification tab but you changed that so now i have to press Save for it to get away.
I can see now that you didn't changed it for the notification tab either.
Why do you activate something before the user press the Save button? It will confuse me if something gets activated before i press the Save button. It is a very strange behavior. I don't know why you have made it like this but maybe you have your reasons?

**Comment by qooob** [comment]
Well, I actually did it on purpose. I find this user friendly to make things displayed upon toggling options, when possible.

**Comment by qooob** [comment]
Ok, I have made few tweaks to make sure that the user will be aware that the the settings should be saved.

Other than than, reverting to previous settings, unsaved could be possible but would take much more work and bring extra complexity. I realize that it would be slightly better but I don't think it's gonna worth it especially after this patch.
