### ISSUE TITLE
make the 'slider' a few pixel lower

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#698]
Is it possible to make the 'slider' a few pixel lower so it is possible to see the progress bar even when the slider is open (not set to always visible)?

**Comment by Sopor-** [comment]
As you can see here it will disappear behind the slider

![picpick-2017 03 28-00 11 07](https://cloud.githubusercontent.com/assets/5789283/24380363/322b15f0-134b-11e7-988b-bfff08efd21c.png)

**Comment by qooob** [comment]
This, I need to take a look at tomorrow, when I'm back to PC.

**Comment by qooob** [comment]
Moving it lower would a bad idea. Making loader going above it, makes sense. Take a look at the patch.

**Comment by Sopor-** [comment]
I have empty my cache and reloaded the page several times but i still can't see it :(

**Comment by qooob** [comment]
Which browser?

**Comment by Sopor-** [comment]
Firefox 52.0.2

**Comment by qooob** [comment]
I double-checked it for you.

It woks in Firefox 55.0a1 (2017-03-28) (64-bit) and in Firefox 52.0 (64-bit). 

All works fine. It's the stuck cache, for sure or your update didn't go right for you.

**Comment by Sopor-** [comment]
Tested in Chrome too but i still can't see the progress bar going above the slider.

**Comment by qooob** [comment]
Give it a try.

**Comment by Sopor-** [comment]
Nice! 😃
