### ISSUE TITLE
Don't use red in the slider when virtual memory is 0 bytes total

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#699]
Why is the virtual memory red in the slider when i don't have any virtual memory at all? The red makes me think something is wrong everytime i look at the slider. Another color would be nice or make it an option to select what ever color i want. At least use another color than red.

v18.40

**Comment by qooob** [comment]
Can you make a screenshot, please?

**Comment by Sopor-** [comment]
I tried to attach this file to the above message but it didn't worked... I don't know why i could add it here? Github issue?

![picpick-2017 03 27-23 08 54](https://cloud.githubusercontent.com/assets/5789283/24378766/73c13636-1344-11e7-9b76-b928c7243666.png)

**Comment by qooob** [comment]
Oh. What about piecharts? Do you have 3 or 4 of them?

**Comment by Sopor-** [comment]
3 or 4 of what?
I don't know if you could remove it completely if no virtual memory is installed?
How will it look like if you use piecharts? Any preview to show?

**Comment by qooob** [comment]
Those green circles on System Information page. You have a little part of it on your screenshot above.

**Comment by Sopor-** [comment]
I have 3 :)

**Comment by qooob** [comment]
Ok, this is a bug. I will fix it in 18.41
