### ISSUE TITLE
version is up to date

### ISSUE THREAD

**Issue by wademac** [qooob/authentic-theme#70]
Can't locate object method "parse" via package "version"

I do have version installed on a SLES 11.3 machine
cpan> install version
version is up to date (0.9911).

any advise?

**Comment by qooob** [comment]
Can you please copy/paste complete error message?

**Comment by wademac** [comment]
![screenshot - 15-01-19 - 03 41 09 pm](https://cloud.githubusercontent.com/assets/2419473/5806732/5a0d1d12-9ff2-11e4-837c-1f4fb66257eb.png)

**Comment by qooob** [comment]
Hard to tell. Try installing also `version::regex` and other `version::` like methods.

It should work.

**Comment by wademac** [comment]
cpan[2]> install version::regex
version::regex is up to date (0.9911)

I run SLES 12 and have no issues but something about SLES 11 and below :(

**Comment by qooob** [comment]
Make sure that Perl can find modules. You can just copy them manually to the path. Besides, find out the way to upgrade Perl on those, older, machines. Or just find in my theme, in file `body.cgi` that:
 `version->parse($remote_version) <= version->parse($installed_version)` 
and replace with
 `1 == 1`. 
But you will not be able to see/do automatic updates. If you want to always see buttons you could do `1 != 1`.
I'm closing this issue as it's not Authentic Theme problem.
