### ISSUE TITLE
Usermin - IE11 - Are you sure you want to leave the page prompt

### ISSUE THREAD

**Issue by thehutman** [qooob/authentic-theme#700]
OS: Windows 10 64bit
Browser: IE 11.953.14393.0 / 11.0.40
Usermin: 1.701
Theme Version: 18.40

When browsing anything in Usermin viewing email, any link clicked on causes the following prompt to appear:

![image](https://cloud.githubusercontent.com/assets/4375809/24402527/9f1199ea-137e-11e7-838b-8bfb3ec5fb29.png)

Also, can't click on the "Usermin" link in the left bar (Alt-U) when using IE -- also doesn't seem to be working.  By default, our Usermin starts up in email browsing mode for our users.

For those of us here using Chrome, none of this occurs -- seems to be an IE issue only.

**Comment by qooob** [comment]
Hi,

At the moment I figured out, that some part of the _content.js_ script is failing in IE11.

I will try to fix it ..

Do you have any errors in the IE console? When I open console in IE11, it's failing to load, crashing the browser. 

I'm applying Windows upgrade now in my virtual machine, maybe it will fix the issue and I will be able to debug it.

**Comment by qooob** [comment]
Ok, I got it.

A bit later I will make a patch.

**Comment by thehutman** [comment]
Thanks a bunch!  It will make the one guy who seems stuck with IE complain less :)

These are the errors in my IE console, FWIW:
![image](https://cloud.githubusercontent.com/assets/4375809/24410775/8d4bf424-1399-11e7-99e9-6c2847a1d5d8.png)

**Comment by qooob** [comment]
Please be kind testing it.

I also did few other fixes. Now IE11 works tolerably ok.

**Comment by thehutman** [comment]
Confirmed, it appears to be working.  I agree, IE is not a great browser, but we have a number of employees that seem stuck on using it for whatever reason.

**Comment by qooob** [comment]
Sure, I understand.
