### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by realkot** [qooob/authentic-theme#701]
I have latest theme (18.40) and Webmin (1.831) versions installed.

* What is your server-side OS and its version?
Ubuntu 16.04
* What is your client-side OS, browser and its versions?
Win 8.1 IE11 (latest ver.\build) 
* What are the steps to reproduce the issue
Watch the demo: 
![webmin](https://cloud.githubusercontent.com/assets/24507273/24468213/39da5736-14c0-11e7-8af4-710977f5693e.gif)
![2017-03-29 20 37 25](https://cloud.githubusercontent.com/assets/24507273/24468238/4e0fd8a2-14c0-11e7-91b5-e80dec6b4a8e.png)

FF no any problem.

**Comment by qooob** [comment]
It has been fixed 8 hours ago in this [patch ](https://github.com/qooob/authentic-theme/commit/538dc3f6e32a1deaa7980675110e533a5b19568e).

Please just [update the theme from the repo](https://github.com/qooob/authentic-theme#how-to-update-authentic-theme-manually) and it will go away.

Thanks for reporting.
