### ISSUE TITLE
Theme: Console update script

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#703]
It would be good to have console script that could update the theme with ease, with running something like:

```BASH
./theme-update.sh
```

**Comment by qooob** [comment]
Example:

![screenshot from 2017-03-31 21-04-48](https://cloud.githubusercontent.com/assets/4426533/24563046/c95e761c-1655-11e7-9520-15518ff6fda1.png)

**Comment by qooob** [comment]
Example:
![screenshot from 2017-03-31 21-07-09](https://cloud.githubusercontent.com/assets/4426533/24563187/385a8376-1656-11e7-85fd-cb60e34ccd87.png)

**Comment by neubreed** [comment]
Can this be run from Crontab? I have a few machines and it's a lot of work updating usermin and webmin frequently. I'd like to add a cron job but the script has a prompt in it to start

**Comment by qooob** [comment]
Yes you can, just do the following:

`yes | /path/to/script/theme-update.sh -dev -no-restart`

**Comment by neubreed** [comment]
Great! what do the-beta and -no-restart switches do? Does that install beta version?

**Comment by qooob** [comment]
`-beta` switch will install latest Git version with latest features available. `-no-restart` wouldn't restart Webmin/Usermin.
