### ISSUE TITLE
<<<<<<< HEAD 18.40-git-201703301354

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#705]
When i updated to latest git version i can now read
`<<<<<<< HEAD
18.40-git-201703301354` in the version file. It will also show
`Theme version    Authentic Theme <<<<<<< HEAD`
When i try to manually do a pull i get this message:
```
authentic-theme$ git pull
M       README.md
M       authentic-lib.pm
M       extensions/file-manager/file-manager-lib.pm
M       extensions/file-manager/file-manager.js
U       extensions/file-manager/file-manager.min.js
A       theme-update.sh
M       unauthenticated/css/authentic.css
U       unauthenticated/css/authentic.min.css
U       unauthenticated/css/bundle.min.css
U       version
Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution, or use 'git commit -a'.
```

**Comment by qooob** [comment]
That is something you should Google.

From now on, use  `./theme-update.sh` to update the theme from Git.

**Comment by Sopor-** [comment]
But it can't be my fault if there are CONFLICTS? I even did a `git reset --hard` but that didn't worked.

**Comment by Sopor-** [comment]
You are doing a `clone` every time i run your script?

**Comment by Sopor-** [comment]
It was totally messing up my terminal because i was running it from inside the `authentic-theme` folder. Maybe you should update your script and prevent it from running if i try to run it from inside the authentic-theme folder?

**Comment by Sopor-** [comment]
And correct me if i'm wrong, your script will update even if you don't have any new updates?

**Comment by qooob** [comment]
You don't need to have .Git directory inside after all. Script will delete it for you.

What terminal did you use? I expected things happening from doing things from with the directory that is deleted. But in my case there was no errors. Try adding to the script `cd ..` will it solve the problem?

Do you want me to run `pull` on new updates instead of `clone`? 

I will make blue more bluish.

**Comment by qooob** [comment]
Yes, it doesn't check anything. It just force updates. Theme will do checking.

**Comment by qooob** [comment]
Actually you should run the script to preserve subshell:

`. ./theme-update.sh`

I will post an update tomorrow after more testing. It will stop causing errors even if you run it from inside the changed directory.

**Comment by qooob** [comment]
Actually, no again. There is better way. I'm about to publish the updated script.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/commit/118cfe4abb438bd979eb99f5a5987be28e24db18

**Comment by Sopor-** [comment]
Didn't you change the color for `Pulling in latest changes for`? Dark blue on black background is hard to read :(

![picpick-2017 04 25-20 06 24](https://cloud.githubusercontent.com/assets/5789283/25400423/d64a40b2-29f2-11e7-9b7d-5b2b2aa798ca.png)

**Comment by qooob** [comment]
I actually did and just double checked it. It's not that dark. It's lite in my terminal?
