### ISSUE TITLE
When adding a cron job as favorite they all get the same name

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#706]
If i want to add a cron job as a favorite it will get the name `System/Scheduled Cron Jobs: Edit Cron Job`. If i add another cron job it will be added with the same name and this will make it hard to know which cron job i open.
![picpick-2017 03 31-23 45 14](https://cloud.githubusercontent.com/assets/5789283/24570638/d1051ed6-166c-11e7-8e86-d2b9cb60bd12.png)
Is there a way to make me choose the name?

**Comment by qooob** [comment]
Yes, hover on Favorites and change the name to whatever you want in editor.

**Comment by Sopor-** [comment]
That wasn't easy to find but i did found it :)

**Comment by qooob** [comment]
Yes, I agree. It's better to make it always visible. 

Thanks.
