### ISSUE TITLE
Theme: Patched updates from git using update button from System Information page?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#707]
It would be nice if i could manually update your theme by a simple press on a button.

**Comment by qooob** [comment]
This is how it will look like when `nightly updates` are enabled:

![screenshot from 2017-04-02 15-18-36](https://cloud.githubusercontent.com/assets/4426533/24588623/4b7ef66a-17d4-11e7-94aa-0a4dabea1b2e.png)

**Comment by Sopor-** [comment]
If i have disabled `Including patched versions` it will only show `Authentic Theme 18.40` even if i'm running on a nightly git version. Is this correct?
When will the update button appear because I still can't force an update check :(

**Comment by qooob** [comment]
In case you it enabled, next time I release a patch (new commit), you will see it in notifications.

**Comment by qooob** [comment]
Yeah, why would you want to see git-version if you disabled it? Or maybe you should.. I don't know.. I'll think it over .

**Comment by Sopor-** [comment]
If you manually update i would like to see what version i run. In my opinion it should not be hidden because i have disable nightly updates...

**Comment by qooob** [comment]
OK. I'll brink it back again.

 They are not automatic. It will take you to click update button.

**Comment by qooob** [comment]
Yeah, I agree. It should be displayed no matter what. Because user could run the console script to update it.

Now it seems great.

**Comment by qooob** [comment]
In case patched versions updates are enabled you should see the notification about it.
