### ISSUE TITLE
Not show anything at login page

### ISSUE THREAD

**Issue by hrace009** [qooob/authentic-theme#709]
Hello,

Previously i use this themes for around 1 year, and no problem at all.
Today i wanna check but found my dashboard a blank page, and i have inspect with mozilla firefox, found so many CSS and JS error.
![capture](https://cloud.githubusercontent.com/assets/7691118/24713776/c416730e-1a50-11e7-91a6-c7987dc5cc1c.PNG)

![image](https://cloud.githubusercontent.com/assets/7691118/24713826/ef8de6a2-1a50-11e7-8959-39be276e0615.png)

Provide the following information:
* What is your server-side OS and its version? Centos 7
* What is your client-side OS, browser and its versions? Windows 10 Pro

**Comment by qooob** [comment]
What is your Firefox version?

**Comment by hrace009** [comment]
it's 52

![image](https://cloud.githubusercontent.com/assets/7691118/24715597/2ccafb68-1a56-11e7-9bed-2550179023b3.png)

and this happen with Chrome

**Comment by qooob** [comment]
It's either cache issue or one of your extensions causing it.

Try clearing your browser's cache and restart Webmin.

Second option, is to try disabling all of your browser's extensions. Also try incognito mode.

**Comment by hrace009** [comment]
I have try to clear all cache and use incognito mode, it still same problem.
but with incognito mode, i can't open login screen, then i change it with firefox and change theme to the old one

**Comment by qooob** [comment]
How about Chrome?

**Comment by qooob** [comment]
Did you try Ctrl+Shift+R to hard reload the theme's cache? It's definitely local issue.

**Comment by hrace009** [comment]
i usually use both of it, but my primary is firefox.
For chrome, i still got the same issue. clearing my cache still not resolve it.
And i try to open it at different machine. And i still got the same issue.

**Comment by hrace009** [comment]
weird, after i shutdown my PC and go to sleep. then in the morning i run it again. and everything run like before
