### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by gerbier** [qooob/authentic-theme#71]
I'm working on a linux mageia 4, with webmin 1.730-1 (from rpm), and I can not use the authentic-theme.
I install it as described on https://github.com/qooob/authentic-theme#how-do-i-install-authentic-theme, I have checked for LWP/Simple.pm, Net/SSLeay.pm, Switch.pm, but webmin only tell me "Error - Missing Content-Type Header". 
The /var/webmin/miniserv.error file only contains the same messages :
[20/Jan/2015:13:03:40 +0100] Reloading configuration
[20/Jan/2015:13:03:43 +0100] [127.0.0.1] / : Missing Content-Type Header

**Comment by qooob** [comment]
I case you didn't modify anything on Webmin or Authentic Theme I would think that 99% it's impossible. Try re-installing the theme and/or Webmin.

This issue has nothing to do with the theme most likely.
