### ISSUE TITLE
No custom logos appearing in Usermin

### ISSUE THREAD

**Issue by brianforan** [qooob/authentic-theme#710]
* What is your server-side OS and its version?
Ubuntu 16.04
* What is your client-side OS, browser and its versions?
OSX Sierra / Chrome 56
* What are the steps to reproduce the issue
Installed Authentic theme fresh on Webmin and Usermin and went to Usermin, not logos showing

I'm trying (like in https://github.com/qooob/authentic-theme/issues/639) to get the custom logos working on Usermin. None of the logos are appearing in Usermin although the images are both kept in `/etc/usermin/authentic-theme/images/` and `/etc/usermin/authentic-theme/` - I put them in images as well because I noticed that in the code those directories were references. 

`/usr/share/usermin/authentic-theme/` is also populated.

I'm having difficulties determining why it isn't working because in the `sub embed_logo() { ... }` function it would appear that it would work regardless. We were trying to check where `$root_directory` was initialized to see if maybe that was the issue but couldn't find it so figured it's not on GitHub. 

The page itself does not show anything with the divs that are supposed to be printed, they are just missing completely.

Thanks

**Comment by qooob** [comment]
Did you try to reload the whole page, and not just the right frame?

Do you have proper permissions on the directories?

If I upload the logo in Webmin->Theme Configuration->Logos I can see it in both Webmin and Usermin.

At the same time, there is no option yet to have different logos for Webmin/Usermin

**Comment by brianforan** [comment]
What do you mean by the right frame? I reloaded by refreshing the page/restarting Usermin so I'm pretty sure it was an adequate refresh. I also deleted the theme from Webmin and Usermin and reinstalled to make sure they were the same version because at one point we'd gotten a Perl error because I believe they were mismatched.

This is the permission/info on `/etc/usermin/authentic-theme`: `d-wxr----t   3 root root 4096 Apr  5 16:19 authentic-theme` - sorry, I am not very well versed in *nix command line but trying to pick it up as I go.

The logos were uploaded through `Webmin/Webmin Configuration/Themes/Theme Logos` in the past and are still visible there. The login page/bottom left logo works great in Webmin and it's fine to have the logos be the same on Webmin and Usermin, they just aren't showing up in Usermin I guess.

Thanks for your time.

**Comment by qooob** [comment]
I will test it tomorrow for you one more time.

Do you also have updated version of the theme in Usermin?

**Comment by brianforan** [comment]
Yes, I have the most recent from the list on the Webmin website.

**Comment by qooob** [comment]
So after you set up logos in Webmin do they appear in `/etc/usermin/authentic-theme`?

If you open browsers console, are there any errors?

Are you root user or sudoer?

**Comment by qooob** [comment]
Ok, I got back to my PC.

I see the reason why this is happening. I will make a patch to make sure that `/etc/usermin` and `/etc/usermin/authentic-theme` get proper permissions.

Permissions should be 755 on the directory `/etc/usermin/authentic-theme`. In case you still need that sticky bit on it, run the following:

`chmod 1755 /etc/usermin/authentic-theme` otherwise just `chmod 755 /etc/usermin/authentic-theme`

It will work for you then.

Mentioned directory `/etc/usermin/authentic-theme/images` is not needed. It's a referrer to `/usr/share/usermin/authentic-theme/images`.

**Comment by qooob** [comment]
I also discovered another critical bug there. Thanks for reporting!

Please upgrade the theme from the repo.

**Comment by brianforan** [comment]
Hey Ilia. Thanks for all of your help. To apply the hotfix I cloned the repository, should I just manually upload?

**Comment by qooob** [comment]
Cloning should be enough, to both Webmin and Usermin. After you install it, there is new option to check new version from Git. In the future, you will be able to install new Git version with single click.

**Comment by brianforan** [comment]
Ah.. I cloned to my own host OS so I could upload the files manually. I'm not sure I know how to manually install the theme on my server, although I do know how to clone it. Can you link somewhere I can find how to do this on Webmin? I don't mean to badger you with these questions.

**Comment by qooob** [comment]
Just go on your server to `/usr/share/webmin` and clone it there.

Before that you would need to delete `authentic-theme` directory. Do the same for Usermin.

Like I mentioned, after this manual update you will be able to enable Git updates from settings.

**Comment by brianforan** [comment]
Hey Ilia, sorry to bother you with this ticket but I'm not sure what to do. I'm still not seeing any images appear in my Usermin instance. I reuploaded the images from Webmin to see if maybe they were out of sync but that didn't fix it. Also spun up a new instance of the server as a whole and recreated my Webmin/Usermin configuration and still not having any success stories.

The screenshot shows the login page with nothing on Usermin 
![screen shot 2017-04-10 at 1 40 09 pm](https://cloud.githubusercontent.com/assets/8764279/24874623/4d0a31be-1df3-11e7-8d13-dec85b680de3.png)

Also missing the image that should be on the bottom of the lefthand panel.

**Comment by qooob** [comment]
Is there a way I could login in check? You can share the credentials using my website. I can't tell why it's not working for you other than what I already did. Or you could wait for the other update of Webmin/Usermin that should be coming quite soon. I guest a week or two.

**Comment by brianforan** [comment]
Unfortunately not.. I'm doing this for a work project and don't think it'd be appropriate for me to give out my login details. 

Is there a version of anything that I can check in this to check if it's actually getting the right update?

**Comment by qooob** [comment]
I understand, sure, no problem.

It should be working. After you copied the files or updated the theme and it doesn't work - it might be the _cache_ issue.

You should reload _Webmin_ and _Usermin_. If it still doesn't work, you could find the processes ids by running:

```BASH
ps aux | grep -v grep | grep miniserv
```
The output should be something like:

```BASH
root     1234  0.0  2.7 210316 113748 ?       Ss   11:28   0:03 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
root     5678  0.0  0.4 101656 17672 ?        Ss   10:34   0:00 /usr/bin/perl /usr/libexec/usermin/miniserv.pl /etc/usermin/miniserv.conf

```

and later after you have the process id, kill it manually, like this:

```BASH
kill -9 1234 
kill -9 5678 
```
Where 1234 is the Webmin pid and 5678 Usermin pid.

After that run

```BASH
/etc/webmin/start
```

and 
```BASH
/etc/usermin/start
```

**Comment by brianforan** [comment]
Did that and still no luck. Should I just wait for the next release?

**Comment by qooob** [comment]
It's very strange. Can you login as `root` user and try again, without using `sudo`?

**Comment by brianforan** [comment]
Still nothing. It's so weird because I was thinking maybe the classes were hidden or something but they just aren't even there (classes being `._logo` and `._logo_welcome`and neither is the div they belong in.

**Comment by qooob** [comment]
If you open the source, is it there?

**Comment by qooob** [comment]
I hope permissions on `authentic-theme` folder is 755?

**Comment by qooob** [comment]
Do you have uploaded logos at `/etc/usermin/authentic-theme`?

**Comment by brianforan** [comment]
Logos aren't there. Not sure why, but usermin/ also doesn't have any other files or folders other than authentic-theme. I'm going to reinstall Usermin I think so I can get those files back, I'm not sure where else I'd copy them from.

**Comment by qooob** [comment]
What are the permissions on etc, usermin and authentic-theme?

**Comment by brianforan** [comment]
755 on etc
755 on /etc/usermin
755 on /etc/authentic-theme

I was looking in `/usr/share/usermin/authentic-theme` for images, it's `user/share/usermin/` that only has authentic-theme in it. `/etc/usermin/authentic-theme` has `logo.png` as well as `logo_welcome.png`

**Comment by qooob** [comment]
There should be no /etc/authentic-theme but /etc/usermin/authentic-theme. Are you running as root?

**Comment by brianforan** [comment]
Sorry I missed usermin. The correct third one was `/etc/usermin/authentic-theme` and it had permissions 755.

**Comment by qooob** [comment]
Copy *.png from `/etc/webmin/authentic-theme` to `/etc/usermin/authentic-theme`. Will it work then?

**Comment by brianforan** [comment]
No luck here either

**Comment by qooob** [comment]
Webmin logo works?

**Comment by brianforan** [comment]
Yep

**Comment by qooob** [comment]
After you pit logos to usermin configuration dir. Can you Ctrl+R the page in Webmin on the same machine?

**Comment by brianforan** [comment]
What do you mean on the same machine, my server or my local? My server is an Amazon EC2 instance so can't exactly reload the page on there.

**Comment by brianforan** [comment]
I think I may know what's causing this.. but it hasn't fixed it yet so I'm not sure.

When I installed the usermin module just now from the `Webmin>Webmin Modules` it said that it was available in `/usr/share/webmin/usermin`, are all of these settings going to be under that directory, and the config directory under `/etc/webmin/usermin`?

**Comment by brianforan** [comment]
I copied some directories into the ones mentioned above and that didn't fix the issue. `/usr/share/webmin/usermin` is populated though, and after the install `/usr/share/usermin` is still relatively empty.

**Comment by qooob** [comment]
You're talking about Usermin module for Webmin. Usermin package is separate instance to install. I have absolutely no clue what is going on there on your system.

Usermin must run on the separate port with another instance of miniserv, this is why I don't see how it can be happening.

Even if it's possible, I know nothing about it. I don't have access to Amazon EC2.

**Comment by brianforan** [comment]
The Usermin that I installed from Webmin>Webmin modules>Install `webmin.com/usermin` on the `standard module from ...` textbox uses port 20000, and Webmin runs on port 10000.

**Comment by qooob** [comment]
Very interesting. I will have to take a deeper look into that. I have never heard of installing Usermin itself as a module.

What is the output of `ps` command I mentioned before?

**Comment by qooob** [comment]
..and what is the output of `whereis usermin` and `whereis webmin`?

**Comment by qooob** [comment]
It's important, what is the output of commands above?

**Comment by qooob** [comment]
>The Usermin that I installed from Webmin>Webmin modules>Install webmin.com/usermin on the standard module from ... textbox uses port 20000, and Webmin runs on port 10000.

What you installed is Usermin module for Webmin, that will let you manage installed version Usermin.

**Comment by brianforan** [comment]
Sorry, was probably commuting/sleeping when you responded.

Result of `ps`
`root      3269  0.0  2.7  90312 27756 ?        Ss   Apr10   0:02 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf
root      4363  0.0  2.1  78116 21720 ?        Ss   Apr10   0:00 /usr/bin/perl /usr/local/usermin-1.701/miniserv.pl /etc/usermin/miniserv.conf
`

`usermin: /etc/usermin /usr/share/usermin`

`webmin: /etc/webmin /usr/share/webmin`

**Comment by qooob** [comment]
..and what is the output of `whereis usermin` and `whereis webmin`?

**Comment by brianforan** [comment]
Respectively:

`usermin: /etc/usermin /usr/share/usermin`

`webmin: /etc/webmin /usr/share/webmin`

**Comment by qooob** [comment]
..and at the same time `/usr/share/usermin` is empty?

**Comment by brianforan** [comment]
Not entirely. Here's `ls -lsa /usr/share/usermin` - I just think it's strange that it's so 'empty' compared to the `ls` of `/usr/share/webmin`

```
4 drwxr-xr-x   4 root root 4096 Apr 10 15:40 .
4 drwxr-xr-x 117 root root 4096 Apr  7 16:50 ..
4 drwxr-xr-x  10 root root 4096 Apr 10 13:27 authentic-theme
4 drwxr-xr-x   6 root root 4096 Jan 10 04:13 filemin
```

**Comment by qooob** [comment]
You have strange install. How did you install Usermin?

**Comment by brianforan** [comment]
From within Webmin I went to Webmin Configuration, then Webmin Modules, then where it says install from webmin.com I typed in Usermin and installed like that.

**Comment by qooob** [comment]
No. You could only install Usermin module to control Usermin with it. In case it wasn't installed, you would have to click install button from inside Webmin/Usermin Configuration first to install .deb package. Remember doing it?

**Comment by brianforan** [comment]
Ahh yes I remember what you're talking about now, vaguely. Maybe I should remove Usermin entirely and reinstall so that I can have all of this from scratch.

**Comment by qooob** [comment]
Sure, go ahead. Save configuration first, just in case.

**Comment by brianforan** [comment]
Ok, I uninstalled and reinstalled. Reinstalled theme with direct github link. Still no logos. How I installed was after I ran `/etc/usermin/uninstall.sh` I deleted the `/usr/share/usermin` folder then when I clicked `Usermin Configuration` it said something like `Usermin is not installed, but we can install it automatically for you by clicking here` so I clicked that and it installed the `tar.gz` of Usermin.

Now Usermin works.

**Comment by brianforan** [comment]
I also made sure `/etc/usermin/authentic-theme` was set to `755`.

**Comment by qooob** [comment]
Still no logo?

**Comment by brianforan** [comment]
Yep, I'm going to see about just getting a fresh instance that I can install webmin from scratch on. Something doesn't seem right

**Comment by brianforan** [comment]
The problem is not occurring on my own instance of Webmin/Usermin, which I did a complete fresh install with. So I guess it's somewhere in the actual install of my other instance.

**Comment by qooob** [comment]
It's interesting for me to find out what is that, really.

**Comment by brianforan** [comment]
I'm not sure this issue will ever occur for anyone else. I think the install is from a good amount of time ago. I can try to trace through the folders and see what is in the wrong place, though..

**Comment by brianforan** [comment]
I will note however that the folder `/usr/share/usermin/` _was_ created in this install. It wasn't created in the last. I installed Usermin by wgetting it from the website and then used `dkpg --install`, instead of downloading from the Webmin interface. Maybe I can fix our other server by doing that, I'll try it and let you know.

This has definitely been a learning experience if anything

**Comment by brianforan** [comment]
On the server that this ticket originated with, I reinstalled Usermin and reinstalled the latest version of `authentic` from github. `logo.png` is showing on the bottom left of the authenticated page, but still `logo_welcome.png` is missing. any idea?

Both logos are in `/etc/usermin/authentic-theme/`

**Comment by qooob** [comment]
I don't see how it's possible. The only thing I could recommend is to refresh the page using browser's reload button or just hitting F5.

**Comment by brianforan** [comment]
Yeah I was thinking how is this possible? too. I opened in incognito and it wasn't working there either.. I'll try killing the processes again and rebooting them manually and see if that helps

**Comment by qooob** [comment]
Sure, go ahead.

**Comment by brianforan** [comment]
that did it. all working now with the logos, thanks for your assistance along the way.

**Comment by qooob** [comment]
You're welcome. I'm glad to be helpful.
