### ISSUE TITLE
File Manager not responding on Webmin or Usermin

### ISSUE THREAD

**Issue by brianforan** [qooob/authentic-theme#711]
Provide the following information:
* What is your server-side OS and its version?
Ubuntu 16.04
* What is your client-side OS, browser and its versions?
OSX Sierra / Chrome 57 / Firefox 52
* What are the steps to reproduce the issue
Navigate to either System>File Manager in Webmin or Others>File Manager in Usermin

Not sure if you want two separate issues for this. In Webmin I can go into directories but I can't ascend back out of them by clicking the '..' next to the folder, I just get a spinning wheel. 

On Usermin, I can't descend into any directories, spinning wheel for everything.

Also minor side note - vertical scroll does not work, not sure if this is intended though.

**Comment by brianforan** [comment]
Also tested with a default theme on Webmin and it worked, so assuming it is an authentic issue.

**Comment by qooob** [comment]
In Usermin it's expected. It will be fixed in next the Usermin release as Usermin doesn't have latest `filemin`.

In case your Webmin 18.31+ and latest theme - there should be no problem. If you still experiencing the ptoblem, open the console and make a screenshot with an error message.

**Comment by brianforan** [comment]
![screen shot 2017-04-07 at 2 14 59 pm](https://cloud.githubusercontent.com/assets/8764279/24813641/d633f154-1b9c-11e7-9515-c1cee7e9fe23.png)

Two things from this - first, is there any way that every time I open file manager it opens back up at the default directory? Right now it opens to the last location until I clear cache/open in incognito, or I guess maybe if I closed the browser itself but I didn't try that because I have other windows open. Instead tried in incognito.

Second thing is that in this screenshot I can't get up to the '..' to go up a directory because the scroll bar doesn't let me go up with console open. HOWEVER.. I popped it out and the console showed the same output as in the screenshot.

**Comment by brianforan** [comment]
Two things from this - first, is there any way that every time I open file manager it opens back up at the default directory? Right now it opens to the last location until I clear cache/open in incognito, or I guess maybe if I closed the browser itself but I didn't try that because I have other windows open. Instead tried in incognito.

Second, here is the console output. Had to delete my first comment because the IP was showing in the photo..
![screen shot 2017-04-07 at 2 21 42 pm](https://cloud.githubusercontent.com/assets/8764279/24813823/8f23917e-1b9d-11e7-9402-7ad6f4c664e2.png)

**Comment by qooob** [comment]
What is the Webmin version?

**Comment by qooob** [comment]
Oh, darn. I know why this is happening! Thanks for reporting!

I will fix it shortly!

**Comment by brianforan** [comment]
Working great now, thanks!

**Comment by brianforan** [comment]
Are you sure about 

From the Usermin changelog on webmin.com:

Version 1.680 (5th October 2015)
German and Catalan translation updates.
Added the Filemin File Manager module, which will eventually replace the old Java file manager.

I'm able to navigate through with a theme other than Authentic. I can create another issue if you'd like

**Comment by qooob** [comment]
Yes, I'm sure.

Look, just go to `/usr/share/webmin` and copy/replace `filemin` folder into `/usr/share/usermin`, after

**Comment by brianforan** [comment]
I dunno, I'll take your word for it. I did `sudo cp -rf /usr/share/webmin/filemin /usr/share/usermin` then restarted usermin with authentic theme enabled and it didn't work.

Although I do have this error in console:

`20000/extensions/file-manager/list.cgi?path=&module=filemin Failed to load resource: the server responded with a status of 500 (Perl execution failed)`

**Comment by qooob** [comment]
Try adding `-p` switch to your command.

**Comment by qooob** [comment]
It should be working.

**Comment by qooob** [comment]
`cp -ar ..`

**Comment by brianforan** [comment]
That wasn't working either. The logos still weren't working from the other ticket so I'm going to leave it for now and try to reconfigure Webmin from scratch on a new Ubuntu instance and try to start fresh and hopefully everything will work then. 

Thanks for all of your help so far.

**Comment by qooob** [comment]
Did you delete the directory `filemin` from under Usermin? Try that first.

**Comment by brianforan** [comment]
Same result after removing directory and then `sudo cp -ar ..`

**Comment by qooob** [comment]
What is the output of `ls - lsa /usr/share/usermin/filemin`?

**Comment by qooob** [comment]
..`-a` is already recursive. `-r` switch is not needed.

**Comment by brianforan** [comment]
![screen shot 2017-04-10 at 1 37 40 pm](https://cloud.githubusercontent.com/assets/8764279/24874512/ee54dffc-1df2-11e7-9e5f-2bdc7726b557.png)

**Comment by qooob** [comment]
All looks good.

What is the output of 

`cat /usr/share/usermin/authentic-theme/VERSION.txt`?

**Comment by brianforan** [comment]
18.40

**Comment by qooob** [comment]
Ok, try again please as you don't have correct size over `filemin-lib.pl`:

1. Delete it by running `rm -rf /usr/share/usermin/filemin`
2. Copy it to the destination `cp -a /usr/share/webmin/filemin /usr/share/usermin`
3. Restart Usermin.

It will only work if your Webmin version is 1.831+.

**Comment by brianforan** [comment]
When I do `cat /usr/share/webmin/authentic-theme/VERSION.TXT` I also have version 18.40, but I've run `./theme-update.sh` and it ran its course. I ran steps 1 and 2 per your instruction previously though. My webmin version is 18.31 though, and when I log into webmin I get the pop up about version 18.41 of the theme, but the `cat` still shows 18.40

**Comment by qooob** [comment]
You can't have the message that 18.41 is available unless you are the victim of MITM attack.

By going to `https://github.com/qooob/authentic-theme/blob/master/VERSION.txt` you should only see 18.40 and not 18.41 as it's not released yet.

I will also try to add checking of the signature to the `./theme-update.sh` script.

**Comment by brianforan** [comment]
Sorry, I misread your post before about the file size.

The resulting line of `ls -lsa /usr/share/(webmin/usermin)/filemin` is:

`20 -rw-r--r--   1 root root 16900 Jan  7 01:09 filemin-lib.pl`

where (webmin/usermin) is interchangeable

**Comment by qooob** [comment]
That is strange.

The content should be as such: [`filemin-lib.pl`](https://raw.githubusercontent.com/webmin/webmin/master/filemin/filemin-lib.pl)

**Comment by qooob** [comment]
That is strange.

The content should be as such: [`filemin-lib.pl`](https://raw.githubusercontent.com/webmin/webmin/master/filemin/filemin-lib.pl)

**Comment by brianforan** [comment]
Would it be more likely to break it even more if I clone webmin into my server and then copy `filemin-lib.pl` from the repo folder over to `/usr/share/usermin/filemin` and overwrite the pre-existing one?

**Comment by qooob** [comment]
Here is the copy from my server, which works fine under Usermin.

**Comment by qooob** [comment]
https://rostovtsev.ru/pub/src/authentic/18.41b/filemin-1.831.tar

**Comment by brianforan** [comment]
Says `Module filemin requires Usermin version 1.831 or above`, my Webmin version is 1.831 and my Usermin version is 1.701

**Comment by qooob** [comment]
Are you installing it or just copying it manually?

**Comment by brianforan** [comment]
Installing from Webmin > Usermin configuration > Usermin modules

**Comment by qooob** [comment]
No. Just copy it manually.

**Comment by qooob** [comment]
I didn't export it as module.

**Comment by brianforan** [comment]
Ok, installed manually and reset via the kill -9 commands again, as root. Still not working. Is it possible there's something wrong with the webmin install itself?

**Comment by qooob** [comment]
There is something wrong with your Usermin. You mentioned that there is nothing in /etc/usermin. I'm starting to think that it's not right. Can you download the Debian package from webmin.com, extract it and copy /etc/usermin from there accordingly?

**Comment by brianforan** [comment]
Sorry for the confusion. `/etc/usermin/` is populated as it should be. The only folder in `/usr/share/usermin/` is `authentic-theme` - I mixed the two directories up.

**Comment by qooob** [comment]
What? You don't have Usermin installed at all? Can you just run `apt-get install usermin`?

**Comment by qooob** [comment]
Or did you try logging in as root?

**Comment by brianforan** [comment]
I mean, I was in root. I just got out of root though. This is the result of `ls` in `/usr/share/usermin/`

`authentic-theme  filemin`

apt-get install usermin cannot locate package usermin, but I can install it directly. However.. usermin works fine

**Comment by brianforan** [comment]
With the fresh install of Usermin the other day this is working as well with your copy of filemin

**Comment by qooob** [comment]
Great. However, your fresh install most likely has old version of the theme, this is why it's still working.

New version of Usermin will include latest versions of both Filemin and Authentic Theme.

**Comment by brianforan** [comment]
So the new version of Usermin when it's released won't break anything, will it? If it includes the latest versions of everything... everything seems to be good then.

**Comment by qooob** [comment]
Yes.
