### ISSUE TITLE
Virtualmin site dropdown does not change, while coming from Disk Quotas widget in webmin

### ISSUE THREAD

**Issue by rohanvakharia** [qooob/authentic-theme#713]
To reproduce this issue:
1. Goto webmin Homepage
2. Scroll Down to Disk Quotas widget
3. Click on the virtualmin website from list
4. You will be redirected to correct virtualmin website but if you see the dropdown in virtualmin, it does not change.

**Comment by qooob** [comment]
On your left switch, on top of the navigation menu, do you have Webmin or Virtualmin selected at that point.

Because, I could only reproduce your issue, if I click to virtual-server name from quotas when Webmin switch is opened. In case Virtualmin switch is there, virtual-server opens right.

**Comment by rohanvakharia** [comment]
Yes, dropdown works fine when I am in virtualmin

It does not works when:
I have webmin in the left and virtualmin in the right in the left sidebar.

When I am in webmin, scroll down to disk quotas(this section is in the right side of the webpage) and clicks on virtual-server
It redirects me to virtualmin and in the left it loads the first virtual-server config and in the right it loads the selected virtual-server config.
Exactly there is a problem, because in this case both sidebar and right section have the same virtual-server should be selected.

**Comment by qooob** [comment]
Yes, thanks for reporting.

It's fixed https://github.com/qooob/authentic-theme/commit/df6f3e56c43fee39075e074ed1343611139df814

**Comment by rohanvakharia** [comment]
Yup Thanks :)

**Comment by qooob** [comment]
You're welcome.
