### ISSUE TITLE
Theme: Editor falls into a loop (IE11)

### ISSUE THREAD

**Issue by prohand** [qooob/authentic-theme#714]
Hello,

When editing a file via the webmin editor and saving it, the save button runs in a loop

The problem is present only with IE11

Thank you for your help

**Comment by qooob** [comment]
Hi,

Could you make a screen shot with opened console to see the actual error?

**Comment by prohand** [comment]
![bugie11](https://cloud.githubusercontent.com/assets/20227162/24948867/0213be4e-1f6c-11e7-96dd-53e520d35e79.png)
Here's

**Comment by qooob** [comment]
Well, to open console you need to hit F11 or right click and inspect element.

**Comment by prohand** [comment]
![bugie11_2](https://cloud.githubusercontent.com/assets/20227162/24949551/4dc40dec-1f6e-11e7-8a2e-21c8f219c641.png)
Here's

**Comment by qooob** [comment]
Switching to console tab will show the actual error(s).

**Comment by prohand** [comment]
![bugie11_3](https://cloud.githubusercontent.com/assets/20227162/24951665/7b13795c-1f75-11e7-93bc-11b8ff0844de.png)

**Comment by qooob** [comment]
Thanks, I will fix it in up-coming 18.41.

**Comment by prohand** [comment]
Can you please indicate the correction to be made please
