### ISSUE TITLE
Pure-FTPd: Cannot add user

### ISSUE THREAD

**Issue by criley** [qooob/authentic-theme#715]
I am using the latest version of the theme and webmin on a freebsd server along with the pureftpd webmin module. If I use the standard theme I can add ftp users without issue, however when I try to add them with this theme enabled I get a message saying that the user was not added for the following reason and then no error below. 

If I force an error by removing the home directory for example it shows an error message. If I switch back to say the Grey Framed Theme it works perfectly.

Suggestions?

**Comment by qooob** [comment]
Hi,

I will take a look and fix it, after I finish with other bugs.

Thank you for reporting.

**Comment by qooob** [comment]
Hi,

Can you please open console and make a screenshot with an error?

**Comment by qooob** [comment]
I would also recommend to contact developer of this third-party module and propose to make a review. It's 11 years old.

The module itself is not doing things correctly. Recommend to take as an example `fail2ban` module and do things the better way.

**Comment by qooob** [comment]
I unfortunately can not support such old module. Please contact the developer to ask them to fix an issue.

From module's README:
>Use this module with caution as it is still in beta-test and has 
not been tested on all plateforms and configuration.
2002-12-01 Mike <info \_at\_  lashampoo.com>
