### ISSUE TITLE
Translating - missing string

### ISSUE THREAD

**Issue by diathesaron** [qooob/authentic-theme#717]
Hi, I'm translating the last strings into catalan and cannot find the string: Including beta versions
Thanks !

**Comment by qooob** [comment]
It's no linger there. Please have a look at the latest EN version.

**Comment by diathesaron** [comment]
I send you a updated file with the latest phrases translated. 

Thanks !

[[20170414] ca.UTF-8.txt](https://github.com/qooob/authentic-theme/files/923554/20170414.ca.UTF-8.txt)

**Comment by qooob** [comment]
Thanks.

**Comment by qooob** [comment]
Translate this please:

theme_xhred_filemanager_link_to_clipboard=Symbolic link's name `<strong><em>%value</em></strong>` has been copied to clipboard.

**Comment by diathesaron** [comment]
Hi !

theme_xhred_filemanager_link_to_clipboard=El nom de l'enllaç <strong><em>%value</em></strong> s'ha copiat correctament al porta-retalls.

**Comment by qooob** [comment]
Thanks.
