### ISSUE TITLE
add lines to 'Reassign Modules' so it will be easier...

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#720]
When changing module category assignments it is very hard to see what drop down menu i should change. So if you could add some kind of lines so it will be easier to see which module that belongs to which drop down menu. I have attached a picture on how it could look like.

![picpick-2017 04 19-18 41 52](https://cloud.githubusercontent.com/assets/5789283/25191623/84a3e446-2530-11e7-85e4-b2264640eea2.png)

**Comment by qooob** [comment]
Hi,

Doesn't the latest version of the theme has it?

I'll double-check and if not fix it.

**Comment by qooob** [comment]
Yes, it needs improvement. Going to patch it right now..

**Comment by Sopor-** [comment]
Very nice @qooob
