### ISSUE TITLE
Updating Authentic Theme, failed.

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#723]
When trying to use the theme-update.sh i only get `Updating Authentic Theme, failed.`

I'm running  	Authentic Theme 18.40-git-201704201806

**Comment by Sopor-** [comment]
I believe it has something to do with this line:
`if [ $? -eq 0 ] && [ -f "$DIR/.~authentic-theme/version" ]; then`
because final versions have no version file

**Comment by Sopor-** [comment]
When i changed the `version` to `VERSION.txt` it worked
`Updating to Authentic Theme 18.45, done.`

**Comment by qooob** [comment]
Yes, realised it on 18.45. It's already checked. Update the script manually.

**Comment by qooob** [comment]
There is still one typo that I found. 

It will be fixed in the next commit.
