### ISSUE TITLE
Webmin continues to show the old login page

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#724]
When i logout i only see the old login page from Webmin. It can't be the web browser cache because i have tried login from 4 different web browsers and they all show the old page.

I'm running Authentic Theme 18.45 and i have tried IE, Firefox, Chrome and Opera. I have 4 Webmin but it is only one of them that is showing this login page.

![picpick-2017 04 23-17 26 19](https://cloud.githubusercontent.com/assets/5789283/25314923/001df0fc-284d-11e7-984b-21e5ad1d3520.png)

**Comment by qooob** [comment]
You have this because Gray Theme is set Globally in configuration but Authentic is per user. Check your settings.
