### ISSUE TITLE
manually update without having check for updates enabled?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#725]
I know i can enable `Check for Authentic Theme updates` and if i want patched versions too i also enable `Including patched versions` but if i want to have both these off it could be nice with an option to have this `Update` button enabled all the time so i can manually do an update when i see you have made any commits on Github. I don't like programs that "phone home" so i turn off as many check for updates as i can. I can of course run `sudo /usr/share/webmin/authentic-theme/theme-update.sh` but it would be much easier if it was possible to do it from Webmin.

**Comment by qooob** [comment]
I see the contesting logic here..

Are you talking about notifications that appear on the left if update option is enabled, is that what's annoying to you? It will no be shown if it's disabled.

Well, I think it's one more option to go. But we don't want to make to many options as it's believed what makes users less happy.

There is an very easy solution in your case. Go to custom commands, then create a command to run the script, then add it to the favorites and it will appear on the right and will provide direct access to it.

You would need to pass `echo yes | ...` to the script to make it run. Search through the theme files for `update-theme.sh` to see what I mean.

**Comment by Sopor-** [comment]
@qooob what do you mean? The only sh file i found is `theme-update.sh` and where should i find `echo yes | ...`?

**Comment by qooob** [comment]
I meant the following (no `echo`):

```BASH
yes | $root_directory/authentic-theme/theme-update.sh -no-restart
```

as a command in Custom Command.

**Comment by qooob** [comment]
..wait and `$root_directory` has to be replaced with your lib folder.

**Comment by Sopor-** [comment]
There was an update for a few hours ago but now this update is gone because i saw that you have released a new version (18.46). This is one of the reasons i wanted to force an update. So now i have to wait for your theme to find the new update so i can install it :(

**Comment by qooob** [comment]
OK, I will add force update in the future.

**Comment by Sopor-** [comment]
I will try to see if i manage to create that custom command, thanks!

**Comment by qooob** [comment]
Just run it using console?

**Comment by Sopor-** [comment]
Yes, but if i get it to work as a custom command it will make it easier for me.
Or i could wait until you add 'force update' :)

**Comment by Sopor-** [comment]
When i disable updates the manually update button disappear from the `Update Notice` so that makes me not be able to manually update if i have the check for updates set to No :(
![picpick-2017 05 02-17 44 39](https://cloud.githubusercontent.com/assets/5789283/25626244/2b9d3508-2f5f-11e7-89d1-13b131a34e99.png)

**Comment by Sopor-** [comment]
You should also try to be more consistent. You call it `Update Notice` and `Check for Authentic Theme updates` but you use `Force upgrade the theme, using latest commit from Github`. Why don't use update here too, `Force update the theme, using latest commit from Github`?
This is for not confusing the user so they know it is the same thing. It is up to you of course but at least you you have got my opinion :)

**Comment by Sopor-** [comment]
Btw, an update is more like a patch as you call it and an upgrade is more if you replace the whole program with something completely new.

**Comment by qooob** [comment]
Sure

**Comment by qooob** [comment]
That is the point not to display the button for users not having even releases displayed.

I don't think you should have it displayed unless user enables at least release version updates.

**Comment by Sopor-** [comment]
But then i still have to run your script through my terminal window instead of doing it from Webmin. This issue was about running an update without having check for updates set to Yes, but now i still have to enabled it to manually update. If you remove the ability to manually update there was no reason to add it from the beginning. Then it will show up when a new update is available.
Many users don't like programs that "phone home", so they don't want it to check for updates but they still want to update the easy way (from Webmin) instead the hard way (from a terminal).

**Comment by qooob** [comment]
Hmm. Makes sense. Let's wait for Jamie or Joe's reply.

Releases will not phone you much but Git would.

**Comment by swelljoe** [comment]
The ship has long sailed on making the Theme Options page not have too many options! (i.e. there's already *way* too many options on that page, as with a lot of things in Virtualmin.)

Having the update button appear on the Theme Options at the bottom of the page is OK. I would like to se the "main" pages get simpler going forward, but there probably should be a way to update the theme...just tuck it out of the way on the themes page. Try not to clutter up the dashboard and main menus.

**Comment by qooob** [comment]
Alright, here is what the latest commit will have in few moments:

1. `theme-update.sh` now accepts params to install either beta(git), release(latest) or specific release release:XX.XX. You can run `./theme-update.sh --help` to get the help:

```BASH
Authentic Theme update script
Usage:  ./theme-update.sh { [-beta] | [-release] | [-release:number] }
[root@debug authentic-theme]# 
```
For example to install release with version 18.45 just run: 
```BASH
./theme-update.sh -release:18.45
````



2.  I have removed the button from Update Notice and added it to Theme Settings. Now user can choose if to install development or latest release version.

![screenshot from 2017-05-03 21-46-50](https://cloud.githubusercontent.com/assets/4426533/25676550/14f58dcc-304b-11e7-9f9b-d32528ae082e.png)

**Comment by qooob** [comment]
..done.

**Comment by Sopor-** [comment]
@qooob This `force updates` works great but why update if the version is the same? Maybe it could show installed version and github version and ask the user if it should continue with the update or cancel the update?

**Comment by qooob** [comment]
I don't know about that. It's like adding extra complexity. We have an option check for updates. Making it work the same way, like NetData does and what you're suggesting is cool but again, we have it optional as notifications.
