### ISSUE TITLE
Cant access several pages

### ISSUE THREAD

**Issue by codeclinic** [qooob/authentic-theme#73]
Hi,

From first impressions this looks like a great bug. However, Ive only been using it for a few minutes and have already run into a serious issue. Some pages fail to load properly after setting this as the webmin theme. The page loading spinner just appears and the page fails to load.

This typically happens on the system info page. But it also happens if I run any command from the shell command page.

Also, I am now unable to load the Webmin themes page to return my system to anoter theme. This is really concerning me, as I cant return to anoter theme, and I need to run some commands from the shell page.

If you could look into this issue or at least give me some idea how to reset the theme from the commandline, I can reset it via putty.

Thanks!!!

**Comment by qooob** [comment]
Alright, actually this is very weird! It's probably your case installation as no one every complained about it. Did you just downloaded it and installed it using Webmin?

1. You can dismiss loader by clicking on it with right mouse button 2 times;
2. Type in URL `host.example.com:10000/webmin` and you will be able to get to configuration module to change your page.
3. Just in 3 hours I will release a new 9.0.0. version of the theme, that was re-worked completely and should fix all possible bugs.

Tell me if I could help you any further.

**Comment by 7starsone** [comment]
wow, Ilia is back! :-D can't wait...
@codeclinic , what distro and what Web/Virt version? did you install Virtualmin by install.sh ? maybe after other system managers?

**Comment by codeclinic** [comment]
Hi,

I installed virtualmin via the install.sh on a fresh Azure Ubuntu 14.04 server.

I managed to get back to a crappy interface using the following in putty:

- Edit /etc/webmin/config and add the line  theme=mscstyle3
 - Edit /etc/webmin/miniserv.conf and add the line  preroot=mscstyle3
 - Restart Webmin with the command  /etc/webmin/stop ; /etc/webmin/start

as found here: http://comments.gmane.org/gmane.comp.web.webmin.general/10230

**Comment by codeclinic** [comment]
P.s. for clarity i was able to reach webmin configuration via the gui. However, Webmin Themes would only go as far as the spinner.

**Comment by 7starsone** [comment]
and why are you running an old Webmin version?

**Comment by codeclinic** [comment]
Im not. I just used the 3 lines identified to edit the relevant files so as to return to a working theme.

**Comment by codeclinic** [comment]
It looks like Ive now lost virtualmin as doesnt appear regardless of which theme I use. I only ever get webmin. It looks like creating the symlink to load the theme into virtualmin has somehow killed virtualmin. I followed the instructions given here, to create the symlink. I did it via the command shell, however after pressing execute the spinner appeared and didnt progress. It looks like this is where the apparent damage occurred

**Comment by codeclinic** [comment]
Oddly, if i put the webmin theme back to authentic-theme I now regain the link to virtualmin. Odd!

**Comment by qooob** [comment]
Yes, yes, couple of days ago I fixed this spinner issue with Theme select. Click on loader two time with your right mouse button - loader will go away. Releasing new version very soon.

It will take you far away from all that has been done before far far away very quickly! ;))

**Comment by 7starsone** [comment]
excuse me Ilia...
where are the Start and Stop services now... ?
thanks

**Comment by qooob** [comment]
Do you mean those that were on the right side, under list of virtual servers?

**Comment by 7starsone** [comment]
yes, indeed...

**Comment by qooob** [comment]
Joe proposed to hide it. In default theme it's in System Information page. I will add this in the near future. So far please use Webmin to do that.
