### ISSUE TITLE
Can't edit files in File Manager

### ISSUE THREAD

**Issue by MorningSleeper** [qooob/authentic-theme#731]
Theme 18.46-git-201704252145
Webmin 1.831
Server OS: Ubuntu 14.04.5 LTS
Client OS: Win 10, Chrome and Firefox latest.
Right click file and select edit nothing happens. Chrome console log below.

![image](https://cloud.githubusercontent.com/assets/8920632/25410430/9b16c730-29cb-11e7-8a1a-68353b3bdd2b.png)

**Comment by qooob** [comment]
What exactly the file name that you're trying to edit?

**Comment by qooob** [comment]
..and its path?

**Comment by MorningSleeper** [comment]
Occurs with any file name, extension and location, like robots.txt at /webserver/sites/mysite/robots.txt Used to be able to edit all fine.

**Comment by qooob** [comment]
What if you go to Chrome, open console (F12) and then hold reload button (default one, usually top-left) and from drop down select 3 option?

If doesn't work, can you run in console `localStorage.clear()`, does it help?

What is the exact Chrome version?

**Comment by MorningSleeper** [comment]
Tried both suggestions, still getting error.

Chrome: Version 58.0.3029.81 (64-bit)
Firefox: 53.0 (32-bit)

Attaching Firefox console ...

![capture](https://cloud.githubusercontent.com/assets/8920632/25411506/e9cf4ca2-29d1-11e7-86dd-3146a042ca12.PNG)

**Comment by qooob** [comment]
Now I'm confused..

**Comment by qooob** [comment]
I'm gonna solve the issue hypotheticall. Check the upcoming commit please ..

**Comment by MorningSleeper** [comment]
I tried the latest version, a file editor window now opens but it does not contain the file contents, just blank.

**Comment by qooob** [comment]
Please go to console, to the theme folder and run `theme-updare.sh` to do it manually.

**Comment by MorningSleeper** [comment]
done, same issue, both browsers.

**Comment by qooob** [comment]
Try other machine with browser having no extensions!

**Comment by MorningSleeper** [comment]
Tried another computer, chrome and firefox, no extensions, same result. Disabled all extensions on first computer in both browsers also without change.

**Comment by qooob** [comment]
Then the only last thing I can recommend. Please reboot the server.

**Comment by MorningSleeper** [comment]
Already tried that without change. Is there a way I can downgrade to a previous theme version that I know it worked with to see if it was a change in the theme or something else that caused the change?

**Comment by qooob** [comment]
Yes, download it from releases.

**Comment by MorningSleeper** [comment]
Tried 18.45 same issue, tried 18.40 and it is working again.

**Comment by qooob** [comment]
Can you download Webmin from GutHub, exctarct it and try with `filemin` from downloaded package? 

You would need to replace in `filemin` folder `/usr/bin/local/perl` to `/usr/bin/perl`

**Comment by MorningSleeper** [comment]
Reinstalled webmin and filemin from download, filemin works fine using latest authentic theme. I like the built in version from webmin better as I like to view it in the same tab so was using the built in version. I see from the filemin page it states it does not work with Authentic theme even though it worked just fine up until 18.45.

**Comment by Bulmer** [comment]
+1 same here. I upgraded to Authentic 18.46 last night in Webmin and now i can't edit within File Manager. I have 18.10 on another server and it works fine..

**Comment by qooob** [comment]
What do you mean built-in version from Webmin? Which one you were using before??

**Comment by qooob** [comment]
@Bulmer Which server OS you have that it doesn't work on? Could you try to update `filemin` from Webmin repo to see if it works with the latest 18.46 release?

Please provide the screenshot of the whole page, I wanna take a look.

**Comment by divyeshsachan** [comment]
I just checked on all of my 8 servers. Theme files editor is working normally on 18.45 and 18.46 on all of my servers. Checked on all combination of Ubuntu 16.04 & 14.04, Firefox 50 & Chrome 57.

**Comment by qooob** [comment]
@divyeshsachan Thanks for checking. None of us could reproduce it as well.

**Comment by Bulmer** [comment]
@qooob . I was already using the Authentic theme and upgraded it. Im using the theme with Webmin 1.831 on my Debian 8 (jessie) vps.

**Comment by qooob** [comment]
I finally _**COULD**_ reproduce this issue by running `localStorage.clear()`, reloading page and going straight to File Manager.

Things seem broken.

I suppose you don't have `localStorage` or what else?

**Comment by qooob** [comment]
Does it happen for you to edit the file on the `/` locaton?

**Comment by qooob** [comment]
Whoever faced this issue could you please go to the directory, where you can't edit the file, click refresh button in the File Manager's button bar and try to hit edit again?

Does it work then?

**Comment by qooob** [comment]
..do you also have by any chance tabs disabled in options?

**Comment by qooob** [comment]
It's checked. Please update using Git.

It should be alright now.

Thank you very much for your patience!

**Comment by 7starsone** [comment]
hello,
this happened when trying to retrieve a directory content (eg. /etc)
![Image of error](http://i65.tinypic.com/2ev3o88.jpg)

**Comment by qooob** [comment]
Yes, yes. It's before the latest commit. Please upgrade using Git script.

**Comment by Bulmer** [comment]
@qooob , do you mean 18.46-git-201704271541? I updated to that version and it now opens the files, but they're empty.

**Comment by MorningSleeper** [comment]
What I ment by "built in" one by Webmin is if you go to following page for filemin ...

https://github.com/Real-Gecko/filemin

scroll down it states ...

"###Builtin version Those who want to open Filemin in the same tab where Webmin main menu is, may want to try **built in** version. Works with every theme except Authentic."

So when I install filemin by downloading the file from github,..

![image](https://cloud.githubusercontent.com/assets/8920632/25486538/5e49e05c-2b16-11e7-8ad5-0f9175993267.png)

it worked in latest authentic theme but opens in a new browser window which I did not like but if you install the "built-in" one by downloading from webmin.com like ...

![image](https://cloud.githubusercontent.com/assets/8920632/25485986/a044ee54-2b14-11e7-961a-45516454f74a.png)

it opens in same browser tab in right windows frame. that is what I preferred and was using and where the problem occurs. Tried with latest and still opens file editor in blank window.

**Comment by qooob** [comment]
@Bulmer I can't reproduce it. Please provide a video-screencast.

@MorningSleeper Only file manager shipped with Webmin is supported.

**Comment by MorningSleeper** [comment]
Ok, so to clarify the one that ships with Webmin is the one that opens in new browser window and not the "built in" one that opens in same tab? I guess I was just confused as the built in one had worked fine up till 18.45 but maybe that note on the filemin page about it not working with authentic was added when 18.45 was released.

**Comment by qooob** [comment]
Installing it from Install Modules is not built-in. The one that is in the same tab, that let's you use keyboard for navigation.

**Comment by MorningSleeper** [comment]
Ok, when I install filemin from install modules using 'Standard module from www.webmin.com' I get the version described as built-in on filemin page, that is it appears in same browser tab and let's you use keyboard for navigation as you mention. Anyway, I understand if the "built in" one is not the one that ships with Webmin and guess I'll just stick to using 18.40 since I like to edit in same tab. Was just curious why it stopped working after 18.45.

**Comment by qooob** [comment]
@MorningSleeper One more time - built-in is the one that ships with Webmin, i.e. can be download from Webmin's GitHub page.

**Comment by qooob** [comment]
That one is most likely dated (unless updated manually, which i doubt) and insecure, this is why it's not working.

The File Manager shipped with Webmin is the one that open in the same window and considered to be built-in. You can also open it in separate window if you need.

**Comment by MorningSleeper** [comment]
Ok, thanks for clarifying further, I deleted the likely insecure version of filemin I installed through Webmin's install modules from www.webmin.com and installed the one that ships with Webmin from GitHub and can confirm I am able to edit files again with latest authentic theme.

**Comment by Bulmer** [comment]
@qooob - I will try and get a video done later today, but just letting you know that edit_file.cgi query parameters for "file" and "path" are both empty (edit_file.cgi?file=&path=) when opening the empty file.

**Comment by qooob** [comment]
@Bulmer Do you have latest `filemin` from Webmin repo installed and the latest Git version of the theme? Please make sure that you so, when you test it.

**Comment by sle44102** [comment]
I am also having the same issue (on CentOS 7.23)
I have latest beta Version 18.47beta7 and i BELIEVE latest filemin.  I deleted filemin directory and reinstalled via webmin modules install page, previously i tried by copying github directory, but that was a total failure.

I get blank file when I open for edit.

**Comment by qooob** [comment]
Use one from GitHub and replace Perl shebang. It's described in this post above.

**Comment by sle44102** [comment]
I am will go through the thread again, not sinking in what is the clear directions to fix this.

**Comment by qooob** [comment]
Can you download Webmin from GutHub, exctarct it and try with `filemin` from downloaded package? 

You would need to replace in `filemin` folder `/usr/bin/local/perl` to `/usr/bin/perl`

**Comment by sle44102** [comment]
This might be where some pain is, maybe language barrier.

I do not have a /usr/bin/local/perl directory (is that distro specific?)
  [root@host bin]# cd /usr/bin/local/perl
  /usr/bin/local/perl: No such file or directory

I do have a /usr/local/bin/perl  but dont think that is it.
  [root@host bin]# cd /usr/local/bin/perl
  [root@host perl]# ls
  hello_world.pl

I do have /usr/libexec/webmin/filemin, but if i replace that dir with the one from git download, I get a type error.

**Comment by qooob** [comment]
It's something that has to be replaced in files.

**Comment by MorningSleeper** [comment]
I updated to authentic theme 18.47 today and the files are back to being blank again. Looks like the value of the file query string is blank in edit_file.cgi ...

![18-47](https://cloud.githubusercontent.com/assets/8920632/25542150/35e88bcc-2c06-11e7-8cb7-9febd7650fcc.PNG)

Downgraded to 18.46 and it works again and the value of the file query string is correct in edit_file.cgi

![18-46](https://cloud.githubusercontent.com/assets/8920632/25542142/2c6075ce-2c06-11e7-8a01-feb815ff3b20.PNG)

**Comment by qooob** [comment]
18.47 has never been released.

**Comment by MorningSleeper** [comment]
My bad about the version number, I got the update button like so ...

![image](https://cloud.githubusercontent.com/assets/8920632/25543351/099ec360-2c0b-11e7-9647-6cd8c5d4179a.png)

When I clicked the change log it showed 18.47 so got confused.

![image](https://cloud.githubusercontent.com/assets/8920632/25543493/9b6d8128-2c0b-11e7-9d42-de68f470b618.png)

In any case, what I upgraded to was 18.46-git-201704282201 and the files are back to being blank. Any idea what might cause the file query string to be blank?

**Comment by qooob** [comment]
Try the latest commit. I don't think there could be anything that would make any change. It just should work.

You could always try the other OS, at least, for testing purposes, for instance Fedora Linux.

> Remember: You need latest `filemin` from `webmin/webmin` repo

**Comment by MorningSleeper** [comment]
Definitively using latest filemin from webmin/webmin, reinstalled just now to make sure.

Tried the latest commit again and same result. It showed 18.46-git-201704282201 after installing. When I tried to edit a file, no file contents were displayed in file editor and file query string was blank. When I went back to 18.46-git-201704271541 editor shows file contents and file query string contains file name. Since then I have updated to 18.46-git-201704282348 but issue still occurs so went back to 18.46-git-201704271541 and all is working as expected.

Unfortunately I do not have another server to test a different OS.

**Comment by qooob** [comment]
In Chrome `Ctrl+Shift+R` to hard reload cache?

**Comment by MorningSleeper** [comment]
Tried hard reload of cache as suggested but issue still occurs with any version greater than 18.46-git-201704271541

**Comment by qooob** [comment]
If you look at the [changes made](https://github.com/qooob/authentic-theme/compare/898364ad01bf54e20c414f5c165861a7f394e733...master) - there were no change to File Manager.

I don't see how it can be broken now. I tested it all possible ways on my systems and it works?

**Comment by MorningSleeper** [comment]
I did a bit more testing today and found that when I click the gear icon in upper right of File Manager for the module configuration page and uncheck the checkbox to the left of "Type" the file contents are displayed in file editor with any of the versions greater than 18.46-git-201704271541 including 18.47. If I check the box, issue returns.

Also noticed the fourth checkbox has no description after it but that does not seem related as the results are the same with or without it checked. Hope that helps narrow down the cause.

![image](https://cloud.githubusercontent.com/assets/8920632/25558316/b74e9ca6-2cd8-11e7-8f1b-e77bc4a34cf4.png)

**Comment by qooob** [comment]
Damn, that's true! :disappointed:

**Comment by qooob** [comment]
I made a fix into 18.47, please upgrade and tell m how it is.

**Comment by qooob** [comment]
..description for the checkboxes will be fixed in the next Webmin, it's not the theme issue.

**Comment by MorningSleeper** [comment]
I reinstalled 18.47 from latest commit but issue still occurs when Type checkbox is checked.

**Comment by qooob** [comment]
This time it will load the sane files unless you hard load cache.

It shouldn't be.

By the way, thank you very much!!

**Comment by MorningSleeper** [comment]
Ok got it, after clearing cache it is working with latest theme in both Chrome and Firefox. Thanks for your help.

**Comment by qooob** [comment]
Ok, good to know. And thank you!

**Comment by swelljoe** [comment]
Sounds like we need a more clear way to differentiate Filemin (as developed/maintained by Alexandr, aka Real Gecko) and the forked File Manager in Webmin. It's caused a lot of confusion in this thread.

I'll talk to Jamie about moving the Webmin file manager to another path and removing all mentions of Filemin; they've, unfortunately, diverged and it's confusing that there's two different things with the same name that install in the same path within Webmin.

Ilia, it's usually a bad idea to send folks out to git to grab pieces of Webmin, unless there's something that was hasn't made it into a release. Installing outside of the normal Webmin module install process is confusing for folks who don't know about the shebang. The version of a module from Webmin.com using the Webmin modules page should always be the latest released version of the module (sometimes newer than what's in the latest released Webmin, but never older). It is reasonable to tell people to install using that page.

But, if we get the Webmin file manager moved into its own directory, no one will need to think about it; Filemin and Webmin File Manager won't be able to conflict with each other.
