### ISSUE TITLE
enhancement: centre the pie charts on dashboard

### ISSUE THREAD

**Issue by j-shade** [qooob/authentic-theme#732]
Hi,

Loving the theme! updated recently and noticed the pie charts were out.

I fixed them on my end with a custom css:

.piechart .percent {
   margin-left: 57px;
}

.piechart .label {
   margin-top: 12px;
   text-align: center;
   margin-right: -28px;
   margin-left: 16px;
}

unsure if this affects much else but thought id give my support :)

**Comment by qooob** [comment]
Hi,

Thanks for your suggestion. I'm glad you found your way to custom CSS and that you're enjoying it more now.

I can not added to the package. People got used to it the way it is right now and it looks perfectly fine in most languages. 

Which language are you using?

**Comment by j-shade** [comment]
<img width="1140" alt="screen shot 2017-04-28 at 5 20 59 pm" src="https://cloud.githubusercontent.com/assets/8851024/25522879/2505755a-2c37-11e7-87fd-89a4b2057426.png">

I am using english :) The default was way off centre unless that was the plan! i didn't mean this is an issue, sorry for any inconvenience !

**Comment by qooob** [comment]
Center exactly what? Text, percentage or a pie itself?

**Comment by j-shade** [comment]
The text percentage, though i had thought it was intended to be centred hence my css post.

Thanks again for the great theme :)

**Comment by qooob** [comment]
Yes, it was intended. 😉

You're welcome.
