### ISSUE TITLE
Missing text next to `Columns to display` in module configuration for filemin

### ISSUE THREAD

**Issue by brianforan** [qooob/authentic-theme#733]
![screen shot 2017-04-26 at 2 37 19 pm](https://cloud.githubusercontent.com/assets/8764279/25450740/e48ba738-2a8d-11e7-89c7-11be2926ea60.png)

Should say `Size` or something next to the second checkbox

**Comment by brianforan** [comment]
And `Owner` next to the fourth

**Comment by qooob** [comment]
Yes. It's Webmin bug. It will be fixed with the next  1.840 release.

**Comment by brianforan** [comment]
Is there a way for me to differentiate between what is a Webmin/Usermin issue versus what is a theme issue?

**Comment by qooob** [comment]
Yes there is. Usermin hasn't been updated.
