### ISSUE TITLE
Make it possible to hide the Reboot Now!

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#735]
When i upgrade i sometimes get this message on the dashboard,
```
Warning!
Recent package updates (such as a new kernel version) require a reboot to be fully applied.
Reboot Now!
```
but if i don't want to reboot now i'm stuck with this text. So i wondering if you could make it disappear (a button that will make it go away) until the `reboot-required` get changed again? It must be easy to check the date/time of the file or delete the file `reboot-required`. Use whatever you think is the best way to detect it has been changed (I'm not the expert here). As it is now i have to manually delete the file because this Reboot Now is only annoying to see when i know i won't reboot.

**Comment by qooob** [comment]
Well, I think you should submit it to Webmin repo, as this message coming from it. Theme doesn't do anything in this regard.

**Comment by Sopor-** [comment]
I will do so, thanks!
