### ISSUE TITLE
Updates Won't Work with New Theme (V9.0.0) :: FIXED

### ISSUE THREAD

**Issue by itsbhanusharma** [qooob/authentic-theme#74]
Hi
First of all thanks for a smarter UI.
Second, After Updating theme, The Package Updates Give a Spinning Wheel ... I Had to Forcefully SSH the server and Update the system manually. For More info, Check the Screenshots below.

![issue_2](https://cloud.githubusercontent.com/assets/9054382/5991775/13eb8312-aa2b-11e4-8d4d-b1c7d35407a5.PNG)
![issue_1](https://cloud.githubusercontent.com/assets/9054382/5991776/13f237ac-aa2b-11e4-97d7-26ddf60247aa.PNG)

**Comment by qooob** [comment]
Yes, confirmed in Firefox! Chrome works fine! Will be fixed in the next small release very soon.

Not sure why you used SSH? Why you couldn't go to `Webmin->System->Software Packages Updates` and update it?

**Comment by itsbhanusharma** [comment]
That Also Failed actually Not sure why it happened.

**Comment by qooob** [comment]
That could not fail, I just easily did that.. I could click on the left menu and get to Software Packages Updates.

Anyway, thanks for reporting. I'm very surprised that it's happening. So far can't even think why..

..but will find out and release a patch soon.

**Comment by itsbhanusharma** [comment]
Sure Not an issue :)

**Comment by qooob** [comment]
Found it! I can't believe that Firefox does it!! This is most bizarre I have ever seen and you could remotely think of! Not developer friendly at all.

Actually no other links on the right are clickable in Firefox..

I will fix this in a bit in version 9.0.1

**Comment by qooob** [comment]
Alright, please update, it's fixed now! 

Please be kind reporting if you find anything! There is enormous amount of related stuff, it's hard to grasp all at once.. but I'm trying.

**Comment by itsbhanusharma** [comment]
Just Performed Update. 

Testing it. and would let You know if i Find anything Strange! 

Anyway, That Old </div> Element Issue is All Gone Now :) Happy To See a Clean Code! 

Cheers
