### ISSUE TITLE
Theme: Less frequent Git updates notifications

### ISSUE THREAD

**Issue by adiastra** [qooob/authentic-theme#741]
Mabe have us be able to choose the number of days before checking for git updates.

**Comment by 7starsone** [comment]
maybe enough to decide what to do with regard to the changelog and if you think you need it? Also, you always see the latest...so, honestly, in my opinion this is not an issue...

**Comment by qooob** [comment]
Probably adding a feature when you could manually check for Git updates and also do force upgrade would a convenient thing..

.. will see..

**Comment by Sopor-** [comment]
This was one of the reasons i wanted to add manually check for updates and a force update https://github.com/qooob/authentic-theme/issues/725

**Comment by qooob** [comment]
The next commit will have this ability, to force update the theme from Git. At least `Check for Authentic Theme updates` should be enabled to display the trigger icon. 

![screenshot from 2017-05-01 22-37-46](https://cloud.githubusercontent.com/assets/4426533/25592446/825cb844-2ec1-11e7-8d16-98473b5f7f98.png)

**Comment by qooob** [comment]
1. `theme-update.sh` now accepts params to install either beta(git), release(latest) or specific release release:XX.XX. You can run `./theme-update.sh --help` to get the help:

```BASH
Authentic Theme update script
Usage:  ./theme-update.sh { [-beta] | [-release] | [-release:number] }
[root@debug authentic-theme]# 
```
For example to install release with version 18.45 just run: 
```BASH
./theme-update.sh -release:18.45
````



2.  I have removed the button from Update Notice and added it to Theme Settings. Now user can choose if to install development or latest release version.

![screenshot from 2017-05-03 21-46-50](https://cloud.githubusercontent.com/assets/4426533/25676550/14f58dcc-304b-11e7-9f9b-d32528ae082e.png)
