### ISSUE TITLE
File Manager: Code highlight for certain files

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#742]
Hello Ilia...

all text code now is white, there is no style anymore for
PHP, CSS and so on...

then, is possible to have the code highlighting even for smarty .tpl?

thanks

**Comment by qooob** [comment]
It used to be white for all the time, right?

It would be better to have them colored, is that what you're saying?

**Comment by 7starsone** [comment]
indeed no....before there was the code highlighter...how is it possible? Are you sure that it was white before?

**Comment by qooob** [comment]
Hmm. Something damn happened.. I can't even see the highlight on the .sh scripts.

I will take a look. We need the highlight!

**Comment by 7starsone** [comment]
you're great...please, try to make it for .php .css .tpl... if possible :-D 👍 🥇

**Comment by qooob** [comment]
There are so many little things to watch after certain changes. Not everything happened to be properly abstracted.

Anyway, code highlight is back for _**ALL**_ files, including `.php` and `.tpl` (Smarty) and all other.

Please give it a test.

**Comment by 7starsone** [comment]
ok, now it works... ;-) thank you

**Comment by 7starsone** [comment]
bug is back after latest update....and also it shows 18.47 version instead of 18.48

thanks

**Comment by qooob** [comment]
The funny thing. I had it too on the first install. 

The reason was for that files on Webmin Themes/Install weren't updated :open_mouth: 

I don't know, just update from theme settings or better try to do the same thing again but manually, download the package and feed the link to the installer.

**Comment by qooob** [comment]
..and the reason why the bug is back, because the theme announces itself as 18.47 to the browser and loading old stuff. If you go to `authentic-theme` directory you will see that `authentic-init.pl` and `authentic-lib.pl` weren't updated. I have absolutely no idea why.

I think in the future I will do all updates using Git as it's more stable and reliable.

Re-running update fixes it.

**Comment by 7starsone** [comment]
in theme settings there's no force update anymore....

**Comment by qooob** [comment]
I just explained on the comment above.
