### ISSUE TITLE
Update Notice - missing translation

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#745]
I can find any translation for this text:
`Please be kind reporting bugs to GitHub repository. Follow theme's Twitter channel for the latest updates.`
You will find it at the bottom of the Update Notice window.

**Comment by qooob** [comment]
Yes, I think it's hard-coded will fix tomorrow. Thanks.

**Comment by qooob** [comment]
Translate this, please:
theme_xhred_source_encoding=Source encoding

**Comment by qooob** [comment]
..and this:

`theme_update_footer=Please be kind reporting bugs to $1  repository. Follow theme's $2 channel for the latest updates.`

**Comment by Sopor-** [comment]
@qooob 
`theme_xhred_source_encoding=Källkodning`
`theme_update_footer=Hittar du fel i temat får du gärna rapportera dem på $1. Följ temat på $2 för de senaste uppdateringarna.`
