### ISSUE TITLE
Schedule reboot when required

### ISSUE THREAD

**Issue by adiastra** [qooob/authentic-theme#746]
When receiving the alert 
-------
 Warning!
Recent package updates (such as a new kernel version) require a reboot to be fully applied.
-------

It would be nice to have a button next to "Reboot Now" (which is rarely the correct option for me) that says "Schedule Reboot" and takes you to the appropriate area.

 And while we are at it, how about a dedicated section for scheduling reboots (and recurring scheduled reboots if needed).

**Comment by qooob** [comment]
Hi, we just discussed few days ago. I don't see why this would be the theme issue, please have a look:

https://github.com/qooob/authentic-theme/issues/735

Theme shouldn't schedule anything. It's already doing quite a bit of logic. Probably you could comment to [webmin/webmin](https://github.com/webmin/webmin) repo.
