### ISSUE TITLE
Theme: Proxy-passed configuration doesn't work correctly

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#748]
using webmin 1.831 (latest) and usermin 1.701 (latest) on SuSE Linux leap 42.1
the latest release and develop versions of the theme can not save theme user options because a missing script in usermin:

usermin/save_config.cgi

is the github version webmin only? IMHO it should work also with usermin...

**Comment by qooob** [comment]
Not sure what you mean.

**Comment by gnadelwartz** [comment]
![bildschirmfoto vom 2017-05-03 12-56-13](https://cloud.githubusercontent.com/assets/4593242/25657844/23f6338a-3000-11e7-9bf0-80eff67eb429.png)
![bildschirmfoto vom 2017-05-03 12-58-58](https://cloud.githubusercontent.com/assets/4593242/25657872/4e4201f0-3000-11e7-8e2f-9de0b8fe6fbb.png)

**Comment by qooob** [comment]
Do you also have latest theme for Usermin?

**Comment by gnadelwartz** [comment]
I'm not shure what you mean ... I have installed lastet usermin 1.701 from here http://www.webmin.com/usermin.html

It contains authentic theme 17.72 (working but without theme options) and updated to 18.47 which gave me this error.

Is there a seperate theme repository for usermin?

**Comment by qooob** [comment]
I think you suffering from stuck browser's cache.

That form link is irrelevant and can be anything. Hard reload browser's cache and the issue will go away.

After you hit the button, the form will be submitted in background.

**Comment by gnadelwartz** [comment]
found the issue!

it is not because of browser cache, it is because I proxy webmin via apache as described here in the second section: http://www.webmin.com/uapache.html and webprefix=/usermin set in usermin/config

wenn I access webmin via localhost:20000 it is working

Whats interessting is than I have setup webmin in the same way, and there is no problem ...

**Comment by qooob** [comment]
If you run in the browser's console:

```Javascript
$webprefix_full
```

What do you get on the output?

**Comment by qooob** [comment]
Are there errors in the browser's console?

**Comment by gnadelwartz** [comment]
No errors in console:
```
("Welcome to Authentic Theme 18.47-git-201705061059
https://github.com/qooob/authentic-theme"  parent.min.js:6:169
"nsICookieManager2.getCookiesFromHost()" wurde verändert. Aktualisieren Sie Ihren Code und übergeben Sie die korrekten originAttributes. Lesen Sie mehr auf MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2  cookietracker.js:126:12
)

>> $webprefix_full
<- "/usermin"

```

**Comment by qooob** [comment]
Can you try in incognito mode or disable all of your browser's add-ons?

**Comment by gnadelwartz** [comment]
nothing changed, same issue

**Comment by qooob** [comment]
You can hide preferences for your users with ease using theme's extensions (js) but this is not what you want. Users need to change settings, like colors and stuff. That was the whole point of enrolling it into 18.4x.

Don't know what might be causing an issue. 

Are you sure that you have set up your proxy correctly. Are they configured identically with Webmin? 

**It's the same code for both Webmin and Usermin** - they shouldn't be working differently.

**Comment by qooob** [comment]
Funny, I could reproduce an error using proxy pass. Brr..

Will try to figure this out.

**Comment by qooob** [comment]
Actually it caused whole lot of _**UI issues**_ that were left unnoticed for long time.

For example, try going to _Running Processes_ to see what I mean.

It will be fixed on the next commit.

**Comment by qooob** [comment]
Thank you very much for reporting!

Please test.

**Comment by gnadelwartz** [comment]
saving options is working now!
thanks
