### ISSUE TITLE
Showing error while saving changes in configuration file in "Virtualmin-Nginx"

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#749]
Hi,
Saving configuration files in virtualmin-nginx shows an error message.
Steps to reproduce
1.  Go to "Nginx Webserver" (virtualmin-nginx module)
2. Edit Configuration Files
3. Click "Save"

![error message](https://ibin.co/w800/3LC4ZnypGpuI.png)

**Comment by qooob** [comment]
Does it actually save the file?

**Comment by divyeshsachan** [comment]
Yes, I saves a file, but error shows everytime whether there is an error in config file or not.
