### ISSUE TITLE
Cloudmin system management menu items missing in version 9.0.0 :: FIXED

### ISSUE THREAD

**Issue by jessevl** [qooob/authentic-theme#75]
Somehow the system management menu options for cloudmin are all missing with the latest update. Am I missing something? in 8.0 all options were listed below the list of managed systems but now they should've been moved to the left-side menu but are gone completely instead?

I may be doing something wrong. Using Firefox, latest webmin and cloudmin updates, fresh install (GPL).

[Screenshot (firefox)](https://cloud.githubusercontent.com/assets/6967616/5992368/023a7820-aa27-11e4-93b4-682657ed8e86.png)

**Comment by qooob** [comment]
Hey, I see. Take a look at the video presentation. There is left menu contain all of that stuff from the right, that was located below.

Let me guess. Is your Webmin version below 1.730? What is your Cloudmin version?

**Comment by qooob** [comment]
In case you have latest updates (sorry missed that you said you got latest), then it's the same bug, that just was fixed today for Virtualmin GPL. Developers simply forgot to place new menu generator, a file called `webmin_menu.pl` to GPL version of Cloudmin (and before today to Virtualmin GPL) but _did_ to Pro versions.

Here is the `webmin_menu.pl` file from Cloudmin 8.0 Pro version that wasn't included
https://rostovtsev.ru/pub/src/cloudmin/webmin_menu.pl

You would have to copy it to `/usr/libexec/webmin/server-manager/` to make left menu appear.

If you have problems doing that, just wait for Cloudmin update then. I have just informed Joe, they will be aware.

**Comment by qooob** [comment]
`webmin_menu.pl` is something written by Jamie and it's intact.

**Comment by jessevl** [comment]
That indeed fixed it! Thanks a lot!

I wonder whether there is a better way for the webmin team to manage the GPL and pro versions instead of having two different code bases...

**Comment by qooob** [comment]
I don't think they have different code-bases. It's very new functionality.. It happens. :)

**Comment by qooob** [comment]
Are you on theme version 9.0.1?

**Comment by jessevl** [comment]
You might be right :)

And yes, I am on 9.0.1

**Comment by qooob** [comment]
Alright, thank you for contacting!

**Comment by RobertDeRose** [comment]
This fixed my issue as well! Thanks!
