### ISSUE TITLE
Disable pop up on file upload in Filemin

### ISSUE THREAD

**Issue by brianforan** [qooob/authentic-theme#753]
Provide the following information:
* What is your server-side OS and its version?
Ubuntu 16.04.2
* What is your client-side OS, browser and its versions?
OSX Sierra/Chrome
* What are the steps to reproduce the issue
Upload a file in filemin in Webmin

Right now when you click `File > Upload to current directory` the window forces a pop up that doesn't seem to give much information (maybe because I'm doing single excel spreadsheet uploads). Is there a way to disable this? I was looking for what function is being called but I couldn't find anything in this repo or Real-Gecko's filemin repo that matched `uploadFiles()` to see if I can disable it.

**Comment by qooob** [comment]
No, 

I will replace it with multiple uploads in the near future.

Please see this https://github.com/qooob/authentic-theme/issues/629
