### ISSUE TITLE
Theme: Auto clear linked notifications

### ISSUE THREAD

**Issue by adiastra** [qooob/authentic-theme#754]
If possible it would be nice for the alerts (represented by little red numbers) would clear when their condition has been settled. For example if there are 3 alerts for theme updates and you click "Update" on the main page, all 3 alerts should disappear or at least be marked as read. The same for package updates. There is some easy logic that could be added to the update processes. You just need to check to see if any unread alerts apply to that category and mark them read.

**Comment by qooob** [comment]
Sure, I will add this to the next release.

**Comment by adiastra** [comment]
Awesome!

**Comment by qooob** [comment]
It will be added to the final 19.00 release.
