### ISSUE TITLE
Theme: Improvements for touchscreen devices

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#756]
in general its hard to touch on the correct link in lists of links.
I found two areas in webmin which are difficult to use on touch screens like on a tablet.
![grafik](https://cloud.githubusercontent.com/assets/4593242/25779472/2901ee7a-3319-11e7-9a8f-756dcbc93ce7.png)
![grafik](https://cloud.githubusercontent.com/assets/4593242/25779483/8d42131a-3319-11e7-8518-b0bb3586d84e.png)

may be it can be changed to something like this
![grafik](https://cloud.githubusercontent.com/assets/4593242/25779478/645be084-3319-11e7-95da-abd7f192b2c0.png)

**Comment by qooob** [comment]
Hi, Kay.

I am not sure what you're proposing? It's technically possible to increase padding between elements on devices with small screens.

Overall output for small screens need improvement. I will place it being 3 in my list of priorities (to-do), after File Manager improvements and Mail.

**Comment by gnadelwartz** [comment]
yes,I propose incease vertical padding and may be convert the simple links in the two examples to buttons with an icon :-)

**Comment by qooob** [comment]
I'll keep that in mind, thanks.

**Comment by qooob** [comment]
[Ref.: ](https://www.virtualmin.com/node/56113)Some inputs on focus unusable on mobile.

**Comment by qooob** [comment]
Okay, Kay. I have made a patch for it and navigation menu scrolling now works much better on touch-enabled devices. 

Please give it a try and report back before 19.19 is released (about tomorrow).

**Comment by qooob** [comment]
Okay, I can wait till tomorrow for sure. Thanks.

**Comment by gnadelwartz** [comment]
Done ...
