### ISSUE TITLE
Usermin Filemin no more working since 18.32

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#757]
As last time latest usermin in proxy setup, but it is also not working on localhost.

On Windows 10 latest Firefox and Chrome filemin is no more working since 18.32.
18.31 is ok also original authentic-theme comming with usermin.

I can not change directory or refresh (loading circles forecer).
![grafik](https://cloud.githubusercontent.com/assets/4593242/25779988/b1c64092-3320-11e7-8623-cd7827b5b712.png)

I can create a file, but it is only shown after filemin reload. When editing the file it does open but show no content (I insert something on cammand line), filename is shown as "/" and when try to save message "test is a directory" 
![grafik](https://cloud.githubusercontent.com/assets/4593242/25780003/12ef4c1a-3321-11e7-9abe-382799762076.png)
![grafik](https://cloud.githubusercontent.com/assets/4593242/25780010/34ddd044-3321-11e7-86be-12e68f769862.png)

**Comment by qooob** [comment]
Please wait for latest update of Usermin. It's not the theme issue.

**Comment by gnadelwartz** [comment]
OK, then i stay with 18.31 for my users
Thanks!
