### ISSUE TITLE
keep latest theme-update.sh on downgrade to older release?

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#758]
If you want to test diffrent releases you always have to upgrade with the neweset github and then downgrade to release you want to test. Test other release? same again.

My workaround was to save latest theme-update.sh by hand to be not overwritten from downgrade and use the saved version to go to different release.

BTW: curl on rawgit hangs on my server until timeout

```
++ curl -s -L https://raw.githubusercontent.com/qooob/authentic-theme/master/VERSION.txt
+ RRELEASE=

```
while fetching the webpage with curl works

```
curl  -s -L https://github.com/qooob/authentic-theme/releases/latest | sed -n '/\<title>Release / s/.*\<title>Release \([0-9.]*\) .*/\1/p'
18.48
```

**Comment by qooob** [comment]
Kay, I don't think it's needed or going to be used. 

I have checked the references and GitHub [doesn't let run](https://twitter.com/GitHubHelp/status/322818593748303873) `git archive` against repository to extract single file.

Using `curl` or `wget` could be as simple as that:

```BASH
curl https://raw.githubusercontent.com/qooob/authentic-theme/master/theme-update.sh > theme-update.sh
```

.. but I don't want to add extra complexity for something that might not be used. Besides those commands don't get installed by default on all Linux distros.
