### ISSUE TITLE
File Manager: Switching user mode

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#759]
It would be good to switch to any user when in `root` mode, to make sure that operation will get selected user permissions:

![screenshot from 2017-05-09 20-33-03](https://cloud.githubusercontent.com/assets/4426533/25864204/4ade5d64-34f7-11e7-9f97-4de5c40285b3.png)
![screenshot from 2017-05-09 20-33-07](https://cloud.githubusercontent.com/assets/4426533/25864203/4adc3b4c-34f7-11e7-95d2-3f33ee7a5be9.png)

**Comment by qooob** [comment]
It would be best to detect automatically user-mode upon its home directory entering.

This is what next commit is going to have. The switch will be hidden, unless it's set to `No` (manual mode, as in screenshots above) and detection will work automatically.

![screenshot from 2017-05-10 21-53-00](https://cloud.githubusercontent.com/assets/4426533/25915844/6adb2758-35cb-11e7-8f85-6fa148cc2d80.png)

**Comment by 7starsone** [comment]
I was about to write an issue lol then, read this... you appear and then disappear...
it's magic ahahah :-D 👍

**Comment by qooob** [comment]
So glad to hear you find this useful! 😉
