### ISSUE TITLE
Weird Jump. It Just Goes Insane when Clicked.

### ISSUE THREAD

**Issue by itsbhanusharma** [qooob/authentic-theme#76]
as Again, the OS is Ubuntu 14.04.1

And When The Virtualmin > Services > Configure Website (see the Image below) is Clicked, 

![issue-1](https://cloud.githubusercontent.com/assets/9054382/5995611/045e2f42-aabe-11e4-915f-a98d6f2b0c88.PNG)

it Just Takes me to The Logs (see the Image Below)

![capture](https://cloud.githubusercontent.com/assets/9054382/5995616/254fafaa-aabe-11e4-99b6-58d2c39d26d9.PNG)

Kindly Have a look to it.

**Comment by itsbhanusharma** [comment]
Update:
Links won't Stick to the Service Menu... The System Tries to link them to their Original tag/title.
which (at least for me) is tough to navigate ... entering one way and exiting the other...

**Comment by qooob** [comment]
Yes, thanks, pal! Will be fixed in 9.0.2.

**Comment by itsbhanusharma** [comment]
Yeah Fixed :) Cheers.

Will let You know if anything weird happens.

**Comment by qooob** [comment]
Good to hear. Thanks! :)
