### ISSUE TITLE
Not sure if an issue or not

### ISSUE THREAD

**Issue by jwhulette** [qooob/authentic-theme#760]
Per https://github.com/webmin/webmin/issues/498 Freebsd CPU info should be showing. 
I don't see it listed on System Information page. 

Provide the following information:
* What is your server-side OS and its version?
FreeBSD 11
* What is your client-side OS, browser and its versions?
Mac OS 10.12.4
* What are the steps to reproduce the issue
Load system info page.

Thanks,
Wes

**Comment by qooob** [comment]
What's your Webmin version?

**Comment by jwhulette** [comment]
1.840

**Comment by qooob** [comment]
Interesting. Does it show in old themes?

**Comment by jwhulette** [comment]
I switched to the gray theme and it did not show

**Comment by qooob** [comment]
Hm, ok. I'll come back to you after I have a chance to test it.

**Comment by jwhulette** [comment]
Thanks. Like I said, not sure if it's an issue or not... :)

**Comment by qooob** [comment]
Can you give me the link to FreeBSD 11 iso? I'll install it first thing tomorrow and try to reproduce the bug.

**Comment by jwhulette** [comment]
https://www.freebsd.org/where.html

**Comment by qooob** [comment]
Funny, I couldn't find it last time I was looking for it. Thanks.

**Comment by qooob** [comment]
Installed FreeBSD 11 and latest Webmin.

I _**don't see**_ CPU info in _Authentic Theme_ just as well as in _Gray Theme_.

My best guess that installation requires some library as a dependency. 

**_WebminCore_** does take care about displaying it, this should be addressed to Jamie I think. He might know why or fix it in case it's a bug.
