### ISSUE TITLE
Hotkey for switching Day/Night Mode.

### ISSUE THREAD

**Issue by fastbone** [qooob/authentic-theme#764]
Not really a bug, but an issue.

On a Mac Alt-L is the '@' sign.
So every time you try to enter an email address or a dns entry or whatever with an '@' you will just switch between day and nightmode.

I know you can change the key in config, but I think it would make sense to think about remapping this shortcut by default...

**Comment by qooob** [comment]
Good point. Actually it's easier to make sure it's not triggered when you focused on the input/textarea.

I'll take a look.

**Comment by qooob** [comment]
Fixed in the commit https://github.com/qooob/authentic-theme/commit/2e8403eb471a22fab8c307e4c64688f2e1e00290
