### ISSUE TITLE
Системный журнал не работает на последней версии 9.0.1

### ISSUE THREAD

**Issue by captsmile** [qooob/authentic-theme#77]
Бесконечный статусБар крутится

**Comment by qooob** [comment]
Здравствуйте! Уточните в каком модуле это происходит? Вы можете убрать крутящийся загрузчик нажав на него 2 раза.

**Comment by captsmile** [comment]
Добрый день. Это происходит только в меню "Система" -> "Системный журнал". В других меню статусбар крутится пару секунд и потом отображается информация, а здесь он крутится бесконечно. Двойной клик все исправляет.
ПС. Также некоторые названия меню на русском стали не помещаться. Например "Система" -> "Загрузка и завершение работы системы", "Система" -> "Обновление программный пакетов".

Заранее спасибо :)

**Comment by qooob** [comment]
Понятно. У меня кстати еще не было возможности перевести остальные части на русский. Если есть время и возможность, то сделайте пожалуйста, если нет, я сделаю как-нибудь..

Проблема в том, что я не могу воспроизвести проблему. Перешел на русский (кстати, да вижу выезжает текст). Захожу в системный журнал и у меня рабоает все как обычно, загрузчик уходит. Вы в каком браузере/ОС?

**Comment by captsmile** [comment]
Версия 42.0.2288.6 dev-m (64-bit)

**Comment by captsmile** [comment]
Chrome Версия 42.0.2288.6 dev-m (64-bit)
Ubuntu Linux 14.04

на IE10 аналогичная проблема. Может из-за того что у меня сторонние файлы журналов подключены?

**Comment by captsmile** [comment]
Перевод не так страшен) я почти все на интеллектуальном уровне уже выучил

**Comment by qooob** [comment]
;) откройте консоль браузера (F12), есть какие нибудь ошибки (красненькие кружочки такие). А еще попробуйте хотябы Beta версию 41. (я в ней все проверял)

**Comment by captsmile** [comment]
дело все таки, видимо, в системе моей. потому что режим инкогнито не спасает. InternetExplorer также себя ведет...Ошибок не вижу в консоли

**Comment by qooob** [comment]
А когда вы нажимаете на загрузчик, все нормально? А что за сторонние файлы журналов? Вы их в ручную прописывали? Если так, то это не важно.. Мне даже интересно стало..

**Comment by captsmile** [comment]
перезапуск вебмина все исправил

**Comment by captsmile** [comment]
до этого, когда двойной клик спасал ситуацию не отображались три журнала 

/var/log/apache2/error.log	Да	Apache error log	Просмотреть..
Файл /var/webmin/miniserv.error	Да	Лог ошибок Webmin	Просмотреть..
Output from dmesg   Да	Сообщения ядра	Просмотреть..

**Comment by captsmile** [comment]
где-то на них затык был...или с доступм что-то

**Comment by qooob** [comment]
Ого! Хорошо! Спасибо что обратились! Удачи!
