### ISSUE TITLE
Can you explain these "Warning..." after Webmin update?

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#773]
Hello Ilia,

a bunch of
`warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/jquery.pjax.min.js: remove failed: No such file or directory`
`warning: file /usr/libexec/webmin/authentic-theme/unauthenticated/js/icheck.min.js: remove failed: No such file or directory`
`...`
and so on...

on the update log after the Webmin update...
why? Is Webmin update procedure expecting files in those folders?
Thanks 😃

**Comment by qooob** [comment]
It's very simple. When you install a package using rpm/deb it has a list of tracked/installed files. If you change things outside of the package, then on the next install/upgrade it produces such warnings.

Nothing to worry about.

To avoid those warning, you should stop updating theme outside of Webmin/Usermin, that distributes `authentic-theme` package.
