### ISSUE TITLE
Recent package updates (such as a new kernel version) require a reboot to be fully applied.

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#776]
Is possible to add an option to Authentic Theme about disabling such as information: https://ibb.co/fAB4Y5

it is annoying to restart a server after new kernels ready to install: https://ibb.co/dciCLk

I have the latest Ubuntu with latest Authentic and Webmin/Virtualmin

**Comment by qooob** [comment]
Hi,

You could add to the theme's JS extension the following:

```Javascript
$(function() {
	$('form[action*="/init/reboot.cgi"]').parents('.alert').remove();
})
```

Create custom command in the module, adding it to the favorites for deleting the trigger-file at one click. File to be removed:

```BASH
/var/run/reboot-required
```

Read [this](https://github.com/webmin/webmin/issues/538)
