### ISSUE TITLE
File Manager: Issue on pagenavi hover when overlapping tabs....

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#777]
Hello Ilia,
please consider this situation:

![hover](http://i68.tinypic.com/2ch6mma.jpg)

as you can see, there are tabs close to the page navigation.

In this case, there's some trouble to click on the buttons [1|2|3|4],
often hover doesn't work and you can't click...

tested on Chrome, don't know for Firefox and others...

thank you

**Comment by qooob** [comment]
I'll give it a try tomorrow. Thanks.

By the way you can change pagination, ether with left right buttons or Ctrl+Left/Ctrl+Right (don't remember what it is by heart).

**Comment by 7starsone** [comment]
oh, yes...tried left/right buttons...really useful and quick... 
thanks 😃

**Comment by qooob** [comment]
I actually hoped to add left/right to descend to/from directory like in MC but I already did it for pagination. Ctrl+Left/Right changes tabs.. So I  don't know it would be right to change pagination to Alt+Left/Right.

**Comment by 7starsone** [comment]
In my opinion even Alt+Left/Right could be good... your choice

**Comment by qooob** [comment]
Sounds good. Thanks. Did the refresh feature worked for you?

**Comment by 7starsone** [comment]
yes, that's ok 👍
