### ISSUE TITLE
moduelindex link theme extension and theme logo gives strange result

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#778]
On the theme extension and theme logo page a link "module index" is displayed. Klicking on it provides strange results on Authentic Theme 18.48-git-201705142214

![grafik](https://cloud.githubusercontent.com/assets/4593242/26111397/4de3527c-3a55-11e7-99b7-e2244cd06709.png)
![grafik](https://cloud.githubusercontent.com/assets/4593242/26111413/5dcacc1a-3a55-11e7-9efa-49e55ccc4814.png)

right frame tries a reload, but result is:
![grafik](https://cloud.githubusercontent.com/assets/4593242/26142673/dfbf27c0-3ae1-11e7-93d5-6ab8e050a61c.png)

**Comment by gnadelwartz** [comment]
I had this on my list for 2 or 3 weeks now but forget to open an issue, hopefully its already noticed and fixed :-)

**Comment by gnadelwartz** [comment]
to add an other issue: logo preview is not displayed, may be because of proxy setup
![grafik](https://cloud.githubusercontent.com/assets/4593242/26145373/879d8a86-3aec-11e7-892c-7ee7d533a60d.png)

**Comment by qooob** [comment]
Thanks. 

Why are you having text instead of buttons for Moduleindex?

What is your setting in Table section for `Replace table header's links with icons`?

**Comment by qooob** [comment]
Thy the latest patch.

**Comment by qooob** [comment]
Thy the latest patch.

**Comment by gnadelwartz** [comment]
OK, logo display is solved, but moduleindex link on TOP not .. the button on the bottom works 
Authentic Theme 18.48-git-201705171352
![grafik](https://cloud.githubusercontent.com/assets/4593242/26151679/25f28e0e-3b04-11e7-8eaf-d63988c4cf15.png)

**Comment by qooob** [comment]
I see the source of the issue. Thanks.

**Comment by qooob** [comment]
I don't this option should live. I will remove it. What you think?

**Comment by gnadelwartz** [comment]
agree, it make no sense here

**Comment by qooob** [comment]
Did you check theme's settings and the option I was talking about above?

**Comment by gnadelwartz** [comment]
may be I missed it, I was thinking you refer to the link "module index"

what options do you refer to? the logo option? I love them!

**Comment by qooob** [comment]
Go to theme's settings (just type Authentic in search). See the Tables section and it will be the first option.

**Comment by qooob** [comment]
Set it to yes and take a look. Table's header links will be replaced with buttons.

**Comment by gnadelwartz** [comment]
now I got it! I had the option set to on:  a icon was dipalyed on the settings page, but link on the logo page! If I set option to off, the Icon change to link on settings page also (after reload!)

I vote for icon only, no option to change it.

**Comment by qooob** [comment]
Agree.

**Comment by qooob** [comment]
Check the latest commit. It's gone.

**Comment by gnadelwartz** [comment]
yes the option is gone, but my one problem remains:

main theme option is OK, icon is shown and is working
![grafik](https://cloud.githubusercontent.com/assets/4593242/26249994/db1489c2-3ca8-11e7-9350-d5dc69d9ca08.png)

but link is shown on "sub" pages theme logo and theme extensions.
a klick on the links results in reloading forever :-(

the link point to  URL  `https://mail.rrr.de/webmin//`
If I enter this manually it is working :-(

![grafik](https://cloud.githubusercontent.com/assets/4593242/26250034/0d6d936e-3ca9-11e7-9051-e686001c9c63.png)

can you implement "sub" pages theme logo and theme extension as tabs on the main option page?
this seems to be more logical and teh link problem on "sub" page will also go ...

**Comment by qooob** [comment]
That is strange. 

You must see the nice button + when hovering on it, should show a tooltip saying "Go back on page". Do you see it?

**Comment by gnadelwartz** [comment]
on main page yes, on logo page not, also no popup. Theme 19.49-1
HTML code on logo page:
```
<td id="headln2l" class="" width="25%" align="left">
<div class="btn-group"><a href="/webmin//">Modulindex</a></div><br>
</td>
```
on main page:

```
<td id="headln2l" class="" width="25%" align="left">
<div class="btn-group"><a href="/webmin/webmin/" data-container="body" class="btn btn-link text-lighter" data-original-title="" title="" style="margin-right: 0 !important" aria-describedby="tooltip148014"><i class="fa fa-arrow-left"></i></a></div>
</td>
```

**Comment by qooob** [comment]
Thanks, I've removed those buttons. Not much need in them.

Thanks for double-checking.

**Comment by qooob** [comment]
Meanwhile, you can edit `settings-upload.cgi` and replace:

```Perl
&ui_print_header( $in{'file'}, $Atext{'settings_right_theme_logos_title'}, undef );
```

with:

```Perl
&ui_print_header( $in{'file'}, $Atext{'settings_right_theme_logos_title'}, undef, undef, undef, 1 );
```

To check if it does the trick for you.. well, it should.

**Comment by gnadelwartz** [comment]
link is gone, also no icon but thats OK for me
same has to be done for theme extension

**Comment by qooob** [comment]
Yes, I did it. Thanks.
