### ISSUE TITLE
Usermin: why in english only?

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#779]
Hello,
didn't notice that before or didn't understand how to change.

If i try to enter Usermin with one of my users,
it shows everything in english.

Is it by design? Maybe configurable by Virtualmin or...?
Thanks

**Comment by qooob** [comment]
How do you enter it? Switching to it from root?

In case your users see language correctly, I am be pretty sure that it was done by design, to set the language that `root` is using. Otherwise you might end-up seeing, the language you would never be able to comprehend.

It's not the theme issue, I suppose.

**Comment by 7starsone** [comment]
eg. `https://domain.com:20000`

login by Username and Password
that's english only and can't be changed by user...

so... ?

**Comment by 7starsone** [comment]
but Usermin is for users, not for root...
I can't understand, really....what root language has to do with the user language? Users should be able to choose their own language. Agree? 😃

**Comment by qooob** [comment]
So? You should be able to have this:

![screenshot from 2017-05-17 13-46-02](https://cloud.githubusercontent.com/assets/4426533/26150504/4a5f9a04-3b07-11e7-9b3c-e0bf97cb7ccd.png)

Other than that, you need to go to Usermin Configuration/Available Modules and make sure that it's available.
![screenshot from 2017-05-17 13-47-31](https://cloud.githubusercontent.com/assets/4426533/26150556/877a64f0-3b07-11e7-8cea-0388f0f7ae0c.png)

**Comment by 7starsone** [comment]
ok, that wasn't selected....
BUT, maybe found something...

**File Manager** wasn't selected too, but anyway was there for my user...why?

instead, if I select it and save, on Usermin there is a duplicate **File Manager**

**Comment by qooob** [comment]
Duplicate is java File Manager or manaully installed Filemin from Real-Gecko repo.

If you think there is a bug, please report it to [Usermin repo](https://github.com/webmin/usermin)

**Comment by 7starsone** [comment]
There are 2 File Manager modules....both named `File Manager`, on the left and on the right column...

How i distinguish them? 😃

**Comment by qooob** [comment]
Ok. I will report it to Jamie myself.

**Comment by 7starsone** [comment]
please, where are the translation files for Usermin modules? thanks

**Comment by qooob** [comment]
Each module has its own `/lang` directory containing localization files.

You can find it under Webmin/Usermin directory.

Besides each module contains a file `module.info`, which describes it.

**Comment by 7starsone** [comment]
I can't understand how to translate these buttons text
![change](http://i67.tinypic.com/2lbg9at.jpg)

so, not the relative page content/text
eg. `/usr/libexec/usermin/chfn/lang/`
but the direct buttons text on the left menu...

**Comment by 7starsone** [comment]
I tried to **add desc_xx=...** and **desc_xx.UTF-8=...** to `/usr/libexec/usermin/chfn/module.info`

saved and even restarted usermin, no change...
so, where's the buttons text on the left, please?

**Comment by qooob** [comment]
I think, it's inside `/lang` folder of Usermin. Search through file's content!

**Comment by qooob** [comment]
File Manager can do it. 😉

**Comment by 7starsone** [comment]
no, there's something weird...
```
[root@me ~]# grep -rnw '/usr/libexec/' -e 'Change User Details'
/usr/libexec/usermin/chfn/lang/en:1:index_title=Change User Details
/usr/libexec/usermin/chfn/lang/hu:1:index_title=Change User Details
/usr/libexec/usermin/chfn/lang/en.UTF-8:1:index_title=Change User Details
/usr/libexec/usermin/chfn/lang/hu.UTF-8:1:index_title=Change User Details
/usr/libexec/usermin/chfn/module.info:6:desc=Change User Details
```

the relative files for other langs are already translated but the buttons on the left remain in english...what changes is the page content, not the button text...

**Comment by qooob** [comment]
What language do you have set exactly?

**Comment by 7starsone** [comment]
eg. italian 
```
[root@me ~]# grep -rnw '/usr/libexec/' -e 'modifica dettagli utente'
/usr/libexec/usermin/chfn/lang/it:1:index_title=modifica dettagli utente
/usr/libexec/usermin/chfn/lang/it.UTF-8:1:index_title=modifica dettagli utente
[root@me ~]# grep -rnw '/usr/libexec/' -e 'Modifica Dettagli Utente'
/usr/libexec/usermin/chfn/module.info:12:desc_it=Modifica Dettagli Utente
/usr/libexec/usermin/chfn/module.info:30:desc_it.UTF-8=Modifica Dettagli Utente
```
as you can see, all the 3 files are translated
```
/usr/libexec/usermin/chfn/lang/it
/usr/libexec/usermin/chfn/lang/it.UTF-8
/usr/libexec/usermin/chfn/module.info
```
even restarted usermin, webmin... no change on the buttons on the left menu

**Comment by qooob** [comment]
Probably cache issue? Restart Webmin&Usermin.

**Comment by 7starsone** [comment]
all restarted, even cleared cookies on the browser

no change

**Comment by 7starsone** [comment]
another bug

`/usr/libexec/usermin/mailbox/ulang/en:3:mail_none=There are no messages in folder $1`

`/usr/libexec/usermin/mailbox/ulang/it:3:mail_none=Non ci sono messaggi nella cartella $1`

so, already translated, but that message remain **There are no messages in folder**
even if user lang is italian.

**Comment by 7starsone** [comment]
this is caused by non existing UTF8 files in **/usr/libexec/usermin/mailbox/ulang**

my user is using UTF8 lang
so, after years...still UTF8 issues here, unfortunately...
but for the previous issue I don't know...

**Comment by 7starsone** [comment]
Are you storing user cache files somewhere and you don't delete them? Remember that one time we discussed about this...

**Comment by 7starsone** [comment]
So, there's a problem:

at the moment, you're forced to change language. 
(`Your language → Another language → Your language again`)
If you don't do so...the changes are not applied.

So, it's not an expected behavior.
My user can't be forced to apply another language and then reapply its own language... 😃 
please, test it and you can reproduce it for sure.

**Comment by qooob** [comment]
If you're on Ubuntu, it's possible. It must be reported to Webmin/Usermin repo.

I don't do it. It's WebminCore.

**Comment by 7starsone** [comment]
Some files are not readable/editable (question mark ?)
![notedit](http://i67.tinypic.com/ekn4f7.jpg)

**Comment by qooob** [comment]
It means they are not recognized as text.

At the moment yes, in case you're language set to Unicode.

**Comment by 7starsone** [comment]
this `Your language → Another language → Your language again`
was just a sensation...

doesn't work anymore, I can't understand what's the issue...for the links on the left menu

I wrote here https://www.virtualmin.com/node/52237
hope that Jamie can read...
