### ISSUE TITLE
Behaviour when creating user

### ISSUE THREAD

**Issue by lionslair** [qooob/authentic-theme#78]
When creating a new user. I fill out the username, Full name and then select the bash type to /bin/bash

An auto refresh is happening. I get a white screen and it just stays here. See screen shot. Only started happening on the latest version.
![screenshot](https://cloud.githubusercontent.com/assets/832259/5997824/4034c142-aafb-11e4-9803-e957afcdcbef.png)

**Comment by qooob** [comment]
Oops. Yes, confirmed. To dismiss the loader double click on it.

Will be fixed in 9.0.2

**Comment by qooob** [comment]
Thank you very much for reporting! :) I will release update, probably today..
