### ISSUE TITLE
Updating from 18.47 to 18.49 will show 18.48 as current installed version

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#780]
I was running version 18.47-git-201705032200 and i used the force update and after the update i could see at the bottom of the screen 18.48 but the Dashboard will now show 18.49 after the update.

![screenshot](https://cloud.githubusercontent.com/assets/5789283/26211956/3ae42520-3bf4-11e7-8369-a892dc23edbf.png)
Is this really correct?

**Comment by qooob** [comment]
It's not. I will try to reproduce it. Looks like cache issue.

**Comment by qooob** [comment]
Hi,

I tried two times and I couldn't reproduce this issue. It's practically impossible as the data is derived from the updated version of the theme by reading a file. 

In File Manager, you could go to `/usr/share/webmin/authentic-theme` (as far as I remember you're on Ubuntu) and try to search through files' contents for the match `18.48`. In case it's found then, it mystery cache issue.

Other than that, try hitting force-update one more time.

Script works straight forward way, in case `rm` and `mv` commands are not executed as expected, I can not do much more here.

**Comment by Sopor-** [comment]
I have 4 Webmin and i have updated three of them so far and they all showed 18.48. The fourth i was waiting for your fix to verify it was working.

**Comment by qooob** [comment]
I'm sorry, but there will be no fix this time, as I don't know what to fix. Besides, it's not critical at all and doesn't worth bothering. Please try what I asked in the message above.

However, I will keep it in mind for the future.

**Comment by Sopor-** [comment]
But what should it show here? The updated version or the previous version? I'm at `18.47-git-201705041727` but the `VERSION.txt` will show `18.48` and `version` will show `18.47-git-201705041727`.

**Comment by qooob** [comment]
First of all, it's not correct that you have different versions right now on your system. It should be either 18.47* or 18.48* for both files.

At second, it's not important what versions are there if you do force update.

Can you please run second time force upgrade, what do you get?

In the end, no worries about this. When things come to server side, it's pretty straight forward. One more advice, if it still doesn't work (which I doubt), try using console script and check what it says and what the outcome will be. 😉

**Comment by Sopor-** [comment]
This is not the first time i have seen this but i didn't know if it should show the installed version or the previous version. Sometimes it is a bit hard to understand how you coders are thinking 😄

**Comment by qooob** [comment]
😁 It's written `Currently installed version is xx.xx ` - it sounds very concrete to me. If you want to rephrase it some better way, please let me know. I'm open-minded person.

**Comment by Sopor-** [comment]
Now i did a force update to 18.49-1 but the message was showing 18.49

![picpick-2017 05 20-01 23 43](https://cloud.githubusercontent.com/assets/5789283/26270459/2f6ecd78-3cfb-11e7-9e3f-cf8b6b686d31.png)

**Comment by qooob** [comment]
This is a bug, will fix it in `18.49-2`. Thanks.
