### ISSUE TITLE
Theme: Doesn't work in Microsoft browsers after 18.49 update

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#782]
When i want to change permission this window will popup but as you can see it is not the whole window. It happens if i do it 15 items from the top. I can't even scroll up. The only way to show the complete window is to use the auto scroll (press the wheel button and move the mouse).

![picpick-2017 05 18-21 55 11](https://cloud.githubusercontent.com/assets/5789283/26220912/e9853356-3c14-11e7-8f3c-328080318149.png)

**Comment by Sopor-** [comment]
It seems to be the same for, permissions, ownerships and attributes and you need to have many files/folders so it will make the web browser to show its scrollbar to reproduce it.

**Comment by qooob** [comment]
What is your browser, screen resolution and OS?

**Comment by Sopor-** [comment]
Firefox 53.0.2, 1920x1080 and Windows 8.1.

**Comment by qooob** [comment]
What if you try Chrome, do you get the same result?

**Comment by Sopor-** [comment]
It is working in Chrome.
If i try IE the whole theme won't work but you don't support IE, or do you?

**Comment by qooob** [comment]
I do, it should work in IE but not very well. Edge works much better. Which IE version is that?

About combination of Firefox and Windows 8 - I have encountered mysterious behaviour with my other projects. Things that worked in Firefox in Windows 7 and 10 didn't work on 8.

Did this happen before in previous versions of the theme? Why are you reporting it after the release?

**Comment by Sopor-** [comment]
> I do, it should work in IE but not very well. Edge works much better. Which IE version is that?

IE 11

> About combination of Firefox and Windows 8 - I have encountered mysterious behaviour with my other projects. Things that worked in Firefox in Windows 7 and 10 didn't work on 8.

I'm running 8.1 not 8 😏 

> Did this happen before in previous versions of the theme? Why are you reporting it after the release?

I haven't played around so much with the file manager. I started to use your theme for some weeks ago and it take some time to test everything. I'm not using the file manager so much either but now when i was trying to find those new strings i wanted to translate i manage to find this too.

**Comment by qooob** [comment]
The funny thing and actually very frustrating, that Microsoft thinks that they can build software their own, all-wrong way, hurting developers all over the World, including development process in general. :cry: 

Yes, after I did optimizations, Microsoft Internet Explorer and Microsoft Edge don't work correctly. They handle `load` event in absolutely inappropriate way. 

_I will make a fix tomorrow._

I have made the theme properly get updated from _18.49_ to _18.49-1_ so there should be no problem to release this kind of version.

I think, the best thing to do is to generate a message for Internet Explorer users, asking them to switch away, to at least Edge or other decent browser, like Chrome or Firefox at least. It's easy to do and good for all.

Theme is extremely complex by its nature and I can not combine creativity and amazing features that it brings, with retarded technology that even shouldn't have been existed. 

@Sopor- Thank you for reporting.

**Comment by qooob** [comment]
Hi, 

I have made a fix in _18.49-1_, that supports Microsoft Browsers now. Could you please update and try.

IE11 and Edge should work now.

Make sure that you manually clear browser's cache.

About your initial request, this is how my Firefox on Windows 10 looks like now:

![screenshot from 2017-05-19 12-23-02](https://cloud.githubusercontent.com/assets/4426533/26244723/ab6edf7e-3c99-11e7-96e2-a49c44c9a404.png)

Should I install Windows 8 to my box to try to reproduce your issue?

**Comment by Sopor-** [comment]
In the above picture i see why it is working for you. You need to have more folder or files on your screen. You need to have more than one screen and then you need to scroll down and then change permissions on a file or folder that is not on the first screen.

**Comment by Sopor-** [comment]
> Microsoft Internet Explorer 11 and all Edge browsers should work from now on.

The Dashboard seems to work in IE 11 but not the file manager.

**Comment by qooob** [comment]
I had flashy File Manager in IE11 before the fix I provided above. Afterwards it was all working.

**Comment by qooob** [comment]
It's flickering again. Seem like something needs to be fixed again.

**Comment by qooob** [comment]
I'll take a look.

**Comment by qooob** [comment]
..and modal on many files is off, on Linux as well. I'll take a look. Thanks.

**Comment by qooob** [comment]
Flashing in IE seems to be fixed. However, before I made any changes to the code, after I opened console in IE, and run File Manager again from the left menu - the flashing disappeared. :beetle: 

Let's see how it will work for you after update.

Firefox is doing very strange thing with the modal, absolutely illogical from my point of view. Do you have a clue why this could be happening?

**Comment by qooob** [comment]
Flashing is back in IE11, unless I open console at least once. This is so buggy. I'm willing to fix it, bug as of what I described above, I don't see it's possible to fix. It more looks like IE bug as it works in all other browsers, including Edge.
