### ISSUE TITLE
Theme Does Not Update

### ISSUE THREAD

**Issue by BenchPressesBooks** [qooob/authentic-theme#783]
Clicking the update button on the theme page claims success but the version number of the theme is stuck at 18.48. Latest version is showing as 18.49-1.

Trying to manually download the theme for install fails as the wbt.gz link on this GitHub 404s. After looking further into it, the update button is not pulling update files from what I can tell, just the same as the download button.

OS: Ubuntu 14.04.1 | Webmin version 1.840 | Authentic theme version 18.48

I was able to resolve the issue by downloading the repo, packaging it, and manually installing through the interface.

**Comment by qooob** [comment]
Yes, the full support for patched releases version was only added in 18.49. Updating from 18.48 should return an error.
