### ISSUE TITLE
Theme: Update script improvements

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#784]
may be you have seen my pull request for a script to update webmin/usermin in place.
I like your color coding for messages in theme-update.sh, but it drives me crazy to deal directly with escape sequences.

So I used bash substitions for easyer handling of colors:

```
# predefined colors for echo -e
RED='\e[49;0;31;82m'
BLUE='\e[49;1;34;182m'
GREEN='\e[49;32;5;82m'
ORANGE='\e[49;0;33;82m'
PURPLE='\e[49;1;35;82m'
LGREY='\e[49;1;37;182m'
GREY='\e[1;30m'
NC='\e[0m'
```
so its much easyer to wirte and understand the echo -e commands :-), i.e.

```
echo -e "${BLUE}Pulling in latest release of${NC} ${GREY}${PROD^}${NC} $RRELEASE ($HOST/$REPO)..."
```
may be It's also useful for you ...

**Comment by qooob** [comment]
I'll rather use _tputs_ for colors in the future. 

Thank you for your proposal.
