### ISSUE TITLE
wrong file endocing detected by filemin editor

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#785]
I tested to edit a usermin module.info file in filemin and everyting worked well, expect the detected charset was iso-8859-7. I changed to correct charset iso-8859-1 in editor, but edit window was empty afterwards :-(

how can convince editor to use a specific encoding if he autodetects a wrong one?

**Comment by qooob** [comment]
It's detected by the server. To convert encoding copy the text before changing encoding, change it and then paste it.

**Comment by gnadelwartz** [comment]
OK, ill try it ...

**Comment by gnadelwartz** [comment]
basicly works, but destroys special characters from wrong detected encoding when saving.
how server detects the encoding? it is done by miniserv.pl or like by file command does?

```
file module.info
module.info: Non-ISO extended-ASCII text
```

**Comment by gnadelwartz** [comment]
after reading the documentation detector is simply a wrapper to mozilla encoding detection and can not be influenced. So may be Encode::Guess  may be better, because you can give it a list of charstets to try an retrun an error if he found multiple possible charsets.

**Comment by qooob** [comment]
Well, it's only maybe. Can you make working patch?

**Comment by gnadelwartz** [comment]
my hotfix is:

**Comment by qooob** [comment]
It doesn't look good to me.

**Comment by qooob** [comment]
The problem is, that `UTF-8` encoded file, is pretty much always, not detected as such and the script returns an empty value. This is why by default we fall back to Unicode rather than anything else.

**Comment by gnadelwartz** [comment]
but that file (at the moment) is not UTF its iso-8859-1 mixed with CPXXXX, this was also the intial problem with github. 

currently its retrurned iso-8859-7 converted to UTF-8 and this is definitly wrong. iso-8859-1 -> UTF-8 seems more correct to me. lets discuss with JC:

https://github.com/webmin/webmin/pull/568
