### ISSUE TITLE
File Manager: Modals in Firefox on long screens are offset

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#786]
Something makes modal windows to be offset, in _Firefox_, when the long list of files is in the table. _Chrome_ is displaying content correctly.

Looking for the fix but with no luck so far.

Example:

![screenshot from 2017-05-20 17-16-08](https://cloud.githubusercontent.com/assets/4426533/26276429/2d479194-3d80-11e7-8d70-94d8aaaddd8f.png)

https://github.com/qooob/authentic-theme/issues/782#issue-229788204

**Comment by adiastra** [comment]
Ok this ONLY happens if you scroll down slightly (i just did tests) therefore the modal window is using the top of the page not the top of the visible screen as its marker for top.  The offset exactly matches how far down toy scroll.

**Comment by adiastra** [comment]
THis may help
https://stackoverflow.com/questions/7019353/jquery-how-to-get-the-pages-current-screen-top-position

**Comment by adiastra** [comment]
Seems like you are not the only one 
https://stackoverflow.com/questions/17916442/what-should-i-do-with-css-top-value-differences-in-chrome-and-firefox

**Comment by qooob** [comment]
The point is that it supposed to be done by Bootstrap. Something is going wrong and I can't figure what.

**Comment by qooob** [comment]
> .. offset exactly matches how far down to scroll ..

This is incorrect. It doesn't.

**Comment by adiastra** [comment]
its in the CSS it assumes TOP = 0px when you scroll down that changes. 
![top](https://cloud.githubusercontent.com/assets/1225459/26419739/eaf1d114-407d-11e7-8638-6e7d6ea7adb6.JPG)

**Comment by adiastra** [comment]
can you just make  it relative to the center of the screen instead?

**Comment by qooob** [comment]
It's not the solution.

**Comment by 7starsone** [comment]
please check this
http://output.jsbin.com/tinotavojo

I don't know if can help...because is done on a table with 3 columns
on iframe you should test it

**Comment by qooob** [comment]
This is no longer an issue in 19.00-RC9 that is released within an hour.
