### ISSUE TITLE
Password recovery button still shows after uninstalling 

### ISSUE THREAD

**Issue by NZCyrus** [qooob/authentic-theme#789]
server Operating system: Debian Linux 8
Usermin Version: 1.710
Theme version: Authentic Theme 18.49-4
client-side OS: Archlinux, browser Chromium Version 58.0.3029.110 (64-bit)

I have uninstalled webmin-virtualmin-password-recovery but the orange password recovery button still shows up under the sign in button for Webmin and Usermin.

I presume this is a theme issue?

**Comment by qooob** [comment]
Did you restart Webmin afterwards?

**Comment by NZCyrus** [comment]
No change after restarting webmin
```
# /etc/init.d/webmin restart
Stopping Webmin server in /usr/share/webmin
Starting Webmin server in /usr/share/webmin
Pre-loaded virtual-server/virtual-server-lib-funcs.pl in virtual_server
Pre-loaded virtual-server/feature-unix.pl in virtual_server
Pre-loaded virtual-server/feature-dir.pl in virtual_server
Pre-loaded virtual-server/feature-dns.pl in virtual_server
Pre-loaded virtual-server/feature-mail.pl in virtual_server
Pre-loaded virtual-server/feature-web.pl in virtual_server
Pre-loaded virtual-server/feature-webalizer.pl in virtual_server
Pre-loaded virtual-server/feature-ssl.pl in virtual_server
Pre-loaded virtual-server/feature-logrotate.pl in virtual_server
Pre-loaded virtual-server/feature-mysql.pl in virtual_server
Pre-loaded virtual-server/feature-postgres.pl in virtual_server
Pre-loaded virtual-server/feature-ftp.pl in virtual_server
Pre-loaded virtual-server/feature-spam.pl in virtual_server
Pre-loaded virtual-server/feature-virus.pl in virtual_server
Pre-loaded virtual-server/feature-status.pl in virtual_server
Pre-loaded virtual-server/feature-webmin.pl in virtual_server
Pre-loaded virtual-server/feature-virt.pl in virtual_server
Pre-loaded virtual-server/feature-virt6.pl in virtual_server
Pre-loaded WebminCore
#

```

**Comment by qooob** [comment]
What happens if you click on the button? What is displayed in Gray Theme?

**Comment by qooob** [comment]
Actually this is not the theme issue as it relies on `$text{'session_postfix'}`.

If you really sure that you have uninstalled this module and still see this button (I don't see it, by the way) then report it to the Webmin repo.

When I remove this package `wbm-virtualmin-password-recovery`, the button disappears.

**Comment by NZCyrus** [comment]
Thanks, but in Debian there is no such package. It is `webmin-virtualmin-password-recovery `
I will report it as an issue at Virtualmin. Thanks :)

**Comment by qooob** [comment]
Just search for `password-recovery` using Software Packages module.

**Comment by qooob** [comment]
I think it's just  fancy cache issue.
