### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by adiastra** [qooob/authentic-theme#793]
When trying to update, the update fails. The download link is broken also 
https://github.com/qooob/authentic-theme/releases/download/18.49-5/authentic-theme-18.49-5.wbt.gz

System hostname	SBTWebCentOS7.localdomain (127.0.0.1)
Operating system	CentOS Linux 7.3.1611
Webmin version	1.840 
Virtualmin version	5.07
Theme version	Authentic Theme 18.48. Latest available release 18.49-5   
Time on system	Tuesday, May 23, 2017 1:06 PM
Kernel and CPU	Linux 3.10.0-514.16.1.el7.x86_64 on x86_64
Processor information	Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, 4 cores
System uptime	5 days, 5 hours, 47 minutes
Running processes	178
CPU load averages	0.00 (1 min) 0.01 (5 mins) 0.05 (15 mins)
Real memory	7.61 GB total / 1.22 GB used
Virtual memory	3.91 GB total / 0 bytes used
Local disk space	45.97 GB total / 30.52 GB free / 15.45 GB used
Package updates	All installed packages are up to date

**Comment by ChriZathens** [comment]
I second that.

**Comment by qooob** [comment]
Dupe: https://github.com/qooob/authentic-theme/issues/787
