### ISSUE TITLE
need advise to better integrate module majordomo with authentic theme

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#795]
JC accepted my patches to convert majordomo module from button based to more modern table based layout, see https://github.com/webmin/webmin/pull/572

to work with every theme I placed regular `[edit]` links to call existing cgi's. For better integration (and nicer look) I need some advice how to change HTML Code to display edit Icons if atuthetic theme is used,

HTML Code for a table line looks currently like this;

```
[<td class="td_tag">
<div class="majordomo_icon"><a href="edit_list.cgi?name=admin" style="text-decoration: none;" data-original-title="" title=""><img src="images/smallicon.gif"></a></div></td>
<td class="td_tag">
<a href="edit_list.cgi?name=admin" data-original-title="" title="">admin</a></td>
<td class="td_tag">
<div class="majordomo_edit"><em>Contact the BOSS
</em>&nbsp;&nbsp;<em>[<a href="edit_info.cgi?name=admin" data-original-title="" title="">edit</a>]</em></div></td>
<td class="td_tag">
<em>admin@rrr.de</em></td>
<td class="td_tag">
<em>Nein</em></td>
<td class="td_tag">
<div class="majordomo_edit">4
&nbsp;&nbsp;<em>[<a href="edit_members.cgi?name=admin" data-original-title="" title="">edit</a>]</em></div></td>](url)
```
I put mailinglist icon in a div .majordomo_icon and text+edit links in a div .majordomo_edit

any suggestions for improvements?

**Comment by qooob** [comment]
You better use default output and the theme can replace it with the button

Here is the hint for you. Find right frame url and edit the following command and then run it using console making sure that the frame is selected (not top).

```JavaScript
f__lnk_t_btn(['/virtual-server/', '/virtual-server/index.cgi', '/virtual-server/edit_plan.cgi'], 'form table tbody td', 'a[href*="list_users.cgi?"], a[href*="list_aliases.cgi?"]', 'btn btn-transparent btn-transparent-link-force btn-borderless btn-xxs vertical-align-top margined-top-2', 0, '(~)', ' ~ ', '(~..)');
```

Plain links in the table will be replaced with buttons. This function also receives icon name, replace `0` with `fa-eye` for example to let the button have an icon.

**Comment by gnadelwartz** [comment]
thanks, I'll give it a try. what do you mean with "default output"? Only plain link without div and sourrounding `[]`?

**Comment by gnadelwartz** [comment]
have done like sugested: open Console in FF, make shure right frame is selected and input:

```
f__lnk_t_btn(['/majordomo/', '/majordomo/index.cgi'], 'form table tbody td', 'a[href*="edit_info.cgi?"], a[href*="edit_members.cgi?"]', 'btn btn-transparent btn-transparent-link-force btn-borderless btn-xxs vertical-align-top margined-top-2', 0, '(~)', ' ~ ', '(~..)');
```
Result was:
`undefined`

same happen when I enter `/majordomo/index.cgi`  in the browser and repeat console input

**Comment by qooob** [comment]
It's alright with any output, if you already made a change.

It's messy either way. There is only one clean way to build it. JSON response from the server and then drawing it on the client side using MVVMs. No iframes, no loading/reloading stuff on each page load.

Meanwhile it's not possible, so we deal with bunch of the mess.

We're heading to this direction.

**Comment by qooob** [comment]
Can you please post complete page HTML? Including the page's windows location?

**Comment by gnadelwartz** [comment]
sorry for late resposne, but today is "fathers day" in germany and we went o my father to wish him care :-)

attached you find an zip archive with an example HTML. the frame locations can be `/majordomo/` and `/majordomo/index.cgi`. The links I like to be replaced are `edit_info.cgi?`  and `edit_members.cgi?`
I think about replacing them with an Edit icon like in file manager:  
![grafik](https://cloud.githubusercontent.com/assets/4593242/26447068/1ddc7588-4147-11e7-8029-f3f91236a3c4.png)

[majordomo.zip](https://github.com/qooob/authentic-theme/files/1028722/majordomo.zip)

**Comment by qooob** [comment]
You could add:

f__lnk_t_btn(['/majordomo/', '/majordomo/index.cgi'], 'table tbody td em', 'a[href*="edit_info.cgi?"], a[href*="edit_members.cgi?"]', 'btn btn-transparent btn-xxs vertical-align-top margined-top-2', 'fa-edit fa-xs');

Wrapping links in `[ ]` is not very good, I think. You might need to run some other script to remove it.

**Comment by gnadelwartz** [comment]
Hi again, with a little bit of modification and some aditional JS and CSS I made it working, you can see the result in https://github.com/webmin/webmin/pull/574

**Comment by qooob** [comment]
👍
