### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Madseason41** [qooob/authentic-theme#796]
* What is your server-side OS and its version? Ubuntu 16.04 LTS
* What is your client-side OS, browser and its versions? OSX Safari/ Chrome, iOS Safari/ Chrome/ Mercury, Windows 10/ IE, all latest available versions.
* What are the steps to reproduce the issue: Attempt to login to webmin webui.
Upon updating to the latest webui, I can no longer login. I have attempted to login form the above mentioned browsers, I immediately get returned to the login page with no error or wrong password prompt.

**Comment by qooob** [comment]
Do you use regular session login or PAM?

**Comment by Madseason41** [comment]
Regular as far as I know, not even sure what PAM is.

**Comment by qooob** [comment]
Can you make a screenshot of your login screen?

**Comment by Madseason41** [comment]
![login](https://cloud.githubusercontent.com/assets/6230975/26421963/9fc37142-408d-11e7-9c08-292c5d44f168.png)

**Comment by qooob** [comment]
Check that the `/etc/webmin/miniserv.users` doesn't have ! next to the username.

It should look something like

```Bash
username:x:::::::0::::::::::::::
```

Not


```Bash
username:!x:::::::0::::::::::::::
```

After editing this file you would need to restart Webmin

```Bash
/etc/webmin/restart
```

**Comment by Madseason41** [comment]
no ! was present.

**Comment by Madseason41** [comment]
I uninstalled webmin and reinstalled, that fixed it. Not sure what the deal was. You can close this if no one else is having the same issue.

**Comment by qooob** [comment]
You probably deleted the user or entering the password wrong.

Whatever it is, it's not the theme issue.
