### ISSUE TITLE
buttons floating up if there are more than 2 in a <form>

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#799]
I had a strange issue when converting a majordomo cgi from hand crafted `<input ... type=submit>` to `&ui_submit()`: when I converted the third button in the form, the last two flowed up from there position in a table next to the first button. this does not happen in standard theme.

first button original  `<input ... type=submit>`, next two by `&ui_submit()`

![grafik](https://cloud.githubusercontent.com/assets/4593242/26501591/5b5db752-423a-11e7-8bd1-7b94ea7fd9bd.png)

all buttons created by `&ui_submit()`

![grafik](https://cloud.githubusercontent.com/assets/4593242/26501325/91801c04-4239-11e7-8f0d-f45da683ae35.png)

It has something to do with the class `.ui_form_end_submit` , because when I stay with a the handcrafted input and add the class `.ui_form_end_submit` to it, the same happend.

![grafik](https://cloud.githubusercontent.com/assets/4593242/26501739/b8aede90-423a-11e7-9d80-fa8d5fd42c75.png)

**Comment by qooob** [comment]
That class is assigned programmatically. 

To see how it works, take a look at Bootup and Shutdown module for example and just use what is uses. Don't look to generated HTML, it won't work as you want, I think.

**Comment by gnadelwartz** [comment]
OK, so i stay with my "workaround" only converting 2 input satements over :-(

**Comment by qooob** [comment]
Why not check other modules that work and just use that code with less problems?

**Comment by gnadelwartz** [comment]
ill have a look :-)
