### ISSUE TITLE
Can't loading googleapis in China

### ISSUE THREAD

**Issue by tekintian** [qooob/authentic-theme#80]
Can't loading googleapis in China, Because the fonts.googleapis.com is blocked by GFW OF CHINA, 

<link href="//fonts.googleapis.com/css?family=Roboto:400,700,300,500&subset=latin,cyrillic" rel="stylesheet" type="text/css"> 

I suggest to put the Google CSS and font files into the local folder[unauthenticated\css  font] .......

**Comment by qooob** [comment]
Sorry to hear that, my friend! Alright, I will do this in the next release! ;)

So far just find a font called `Roboto` and install it locally on your computer! It will work, I believe!

**Comment by qooob** [comment]
I will fix this issue in the next release. Sorry. It will take a bit more time and testing.

**Comment by qooob** [comment]
Alright, it's added in version 9.0.4. - it will be out in couple of days. Thanks for pointing out. Good luck!
