### ISSUE TITLE
Loadscreen of death in Firefox

### ISSUE THREAD

**Issue by ikkez** [qooob/authentic-theme#800]
Not sure when it happened but I cannot use firefox anymore, as I don't get pass the initial loading of virtualmin.. the loading spinner keeps spinning and nothing happens. No problem in Chrome though.

Used Firefox 53 and the latest dev beta of authentic-theme. The error console in firefox shows this:

![virlualmin](https://cloud.githubusercontent.com/assets/1177647/26521052/7817e78c-42df-11e7-8aff-60f5ce8b66f5.jpg)

Provide the following information:
* What is your server-side OS and its version?
   debian-7
* What is your client-side OS, browser and its versions?
   macOS 10.11.6, Firefox 53
* What are the steps to reproduce the issue
   just log into virtualmin

**Comment by qooob** [comment]
Hi, Christian.

Practically this is cache issue. Make sure to clear browser cache. In case it doesn't help try incognito mode with disabled extensions.

**Comment by ikkez** [comment]
Browser cache cleared and browser restarted solved the issue. thanks ;)
