### ISSUE TITLE
Theme: Navigation menu URL's prefixes

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#801]
I had the problem that my users (and I) can login to Usermin, but wait forever on loading indicator: 
![grafik](https://cloud.githubusercontent.com/assets/4593242/26526580/2487e53a-4380-11e7-9962-eee03cce2162.png)

after some some investigation  I remembered I change "alway go to module" to file manager. So my first guess was, file manager dont like this, but it happens also when selecting other modules.
![grafik](https://cloud.githubusercontent.com/assets/4593242/26526564/f152b03c-437f-11e7-971e-2bed2a3b6343.png)

I can to reproduce this by change setting and simply reload already open usermin, no need to logout first.
Fix: set to `<none>` and reload usermin in browser.

I case it is "not a bug, its a feature", the setting should be ignored by authentic-theme.

**Comment by gnadelwartz** [comment]
for the records:
proxy setup (as always)
standart thene is working

**Comment by gnadelwartz** [comment]
one more thing: github is not showing your latest commits? updating theme say 18.49-7 but on githup no new commit is shown ...

![grafik](https://cloud.githubusercontent.com/assets/4593242/26526895/c3c9d5f6-4388-11e7-8811-1040d5b76482.png)

**Comment by qooob** [comment]
It's my latest commit.

Are you saying that it's working with non-proxy setup? I have Usermin and it's proxied. All working fine.

The problem that you described happened to me when there was an issue with mailbox and its quota size. Also server-side login to mailbox could cause an issue.

Please investigate more. Double clicking on the empty page should dismiss it. Console errors? Gray Theme results?

**Comment by gnadelwartz** [comment]
grey framed theme is working.
console sows missing `/`:
```
GET 
https://mail.rrr.de/userminlanguage/ [HTTP/1.1 404 Not Found 34ms]
```

**Comment by gnadelwartz** [comment]
I tested diferent proxy configuarions in apache and usermin and it works only if I change:

`webprefix=/webmin` to `webprefix=/webmin/`

in usermin config file, but this is not like described in http://www.webmin.com/uapache.html

**Comment by qooob** [comment]
Yes, I see.

**Comment by qooob** [comment]
I have mine set to 

`webprefix=/webmin`, with out slash at the end and it works fine.

When you hover on the links in the left menu what URL do you see, correct one or the one that misses `/` in the middle?

**Comment by qooob** [comment]
> [Add the following directives to the Apache configuration file](http://www.webmin.com/uapache.html):

```Config
ProxyPass /usermin/ http://localhost:20000/
ProxyPassReverse /usermin/ http://localhost:20000/
```

Is that what you have in your apache config?

**Comment by gnadelwartz** [comment]
```
   # proxy usermin / webmin via apache SSL
   ProxyPass /usermin/ http://localhost:20000/
   ProxyPassReverse /usermin/ http://localhost:20000/
```

**Comment by gnadelwartz** [comment]
refering to the error in console GET 
`https://mail.rrr.de/userminlanguage/ [HTTP/1.1 404 Not Found 34ms]` the easyest way should be to add an extra `/`

**Comment by qooob** [comment]
To add extra `/`? Why does it work flawlessly in my Usermin proxied setup??

I have in my `/etc/usermin/config`, do you?

`webprefix=/usermin`

**Comment by gnadelwartz** [comment]
originally I had `webprefix=/usermin` but was not working, after changing to `webprefix=/usermin/` wich add an extra `/` the problem goes away. I can stay with this setup, but may be others hit the same issue.

why it work for you but not on my box? may be because of some totally unrelated apache settingsr or because my linux box dont like this setting :-(

**Comment by qooob** [comment]
Okay,

Can you share your complete Apache config setup?

**Comment by gnadelwartz** [comment]
will be quite big :-)

**Comment by qooob** [comment]
I mean host configuration, not the whole `httpd.conf`.

**Comment by gnadelwartz** [comment]
```
##
## SSL Virtual Host Context
##

<VirtualHost _default_:443>

        #  General setup for the virtual host
        DocumentRoot "/srv/www/vhosts/mail"
        ServerName mail.rrr.de:443
        #ServerAdmin webmaster@example.com
        ErrorLog /var/log/apache2/ssl-error_log
        TransferLog /var/log/apache2/ssl-access_log

        #   SSL Engine Switch:
        #   Enable/Disable SSL for this virtual host.
        SSLEngine on

        #   SSL Cipher Suite:
        SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL

        #   Server Certificate:
        SSLCertificateFile /etc/ssl/private/mail.rrr.de.crt

        #   Server Private Key:
        SSLCertificateKeyFile /etc/ssl/private/mail.rrr.de.key

        # STARTSSL Intermediate Certificate
        SSLCertificateChainFile /etc/ssl/private/intermediate.crt

        #   SSL Engine Options:
        #SSLOptions +FakeBasicAuth +ExportCertData +CompatEnvVars +StrictRequire
        <Files ~ "\.(cgi|shtml|phtml|php3?)$">
            SSLOptions +StdEnvVars
        </Files>
        <Directory "/srv/www/vhosts/mail/cgi-bin">
            SSLOptions +StdEnvVars
        </Directory>

        #   SSL Protocol Adjustments:
        SetEnvIf User-Agent ".*MSIE.*" \
                 nokeepalive ssl-unclean-shutdown \
                 downgrade-1.0 force-response-1.0

        #   Per-Server Logging:
        #   The home of a custom SSL log file. Use this when you want a
        #   compact non-error SSL logfile on a virtual host basis.
        CustomLog /var/log/apache2/ssl_request_log   ssl_combined



    #
    ScriptAlias /cgi-bin/ "/srv/www/vhosts/mail/cgi-bin/"

    # "/srv/www/cgi-bin" should be changed to whatever your ScriptAliased
    # CGI directory exists, if you have one, and where ScriptAlias points to.
    #
    <Directory "/srv/www/vhosts/mail/cgi-bin">
        AllowOverride None
        Options +ExecCGI -Includes
        Order allow,deny
        Allow from all
    </Directory>

    #
    # This should be changed to whatever you set DocumentRoot to.
    #
    <Directory "/srv/www/vhosts/mail">
        Options FollowSymLinks
        AllowOverride All
        #AllowOverride Options AuthConfig
        Order allow,deny
         Allow from all
    </Directory>


    ## allow password auth against system users
    <IfModule mod_authnz_external.c>
        AddExternalAuth pwauth /usr/bin/pwauth
        SetExternalAuthMethod pwauth pipe
        AddExternalGroup unixgroup /usr/bin/unixgroup
        SetExternalGroupMethod unixgroup environment
    </IfModule>

   # proxy usermin / webmin via apache SSL
   ProxyPass /usermin/ http://localhost:20000/
   ProxyPassReverse /usermin/ http://localhost:20000/

   ProxyPass /webmin/ http://localhost:1000/
   ProxyPassReverse /webmin/ http://localhost:10000/

</VirtualHost>

```

**Comment by qooob** [comment]
Try replacing:

```Config
# proxy usermin / webmin via apache SSL
ProxyPass /usermin/ http://localhost:20000/
ProxyPassReverse /usermin/ http://localhost:20000/
```

With:

```Config
# proxy usermin / webmin via apache SSL
RewriteRule ^/usermin$ /usermin/ [R]
ProxyPass /usermin http://localhost:20000/
ProxyPassReverse /usermin http://localhost:20000/
```

You better use SSL and in order to do this add above proxy config the follwoing (you can read about it more in Apache docs):

```Config
RewriteEngine On
ProxyRequests Off
SSLProxyEngine On
SSLProxyVerify None 
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
SSLProxyCheckPeerExpire Off
```

**Comment by gnadelwartz** [comment]
nothing changes, but as I mentoined: I can stay with `/usermin/`

**Comment by qooob** [comment]
Alright, as you say.

**Comment by qooob** [comment]
Yes, I can also see that in non-proxy setup that there is no slash at the beginning of the URL.

I will keep testing. Thanks for the tip.

Right now it makes no difference to me. But I agree it should correspond with the manual.

**Comment by JialuZhang** [comment]
@iliarostovtsev 

In your posted configuration,
```
RewriteEngine On
ProxyRequests Off
SSLProxyEngine On
SSLProxyVerify None 
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
SSLProxyCheckPeerExpire Off
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by iliarostovtsev** [comment]
You're right, Jialu. Thanks for pointing this out.

**Comment by JialuZhang** [comment]
Thank you!
