### ISSUE TITLE
Theme: Scheduled backups in dark theme not rendered fully

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [qooob/authentic-theme#803]
If it matters, happens on my Virtualmin, Debian Wheezy.

See this screenshot, those white-ish areas shouldn't look like that.

More problematic, it's not just about appearances, it's not clear where one may click inside these, nothing happens when I click the radio buttons, it has to be somewhere on the right of the middle of the name of the entries, to be recognized.

![delete](https://cloud.githubusercontent.com/assets/29028445/26532819/962073e8-440b-11e7-8f26-10b184253f9e.jpg)

Sorry, I doubt I can help more than submitting a bug report, I'm absolutely alien to all this github, code pushing/pulling and all. Good day to everyone !

**Comment by qooob** [comment]
Yes, it's just small CSS bug. It doesn't affect functionality. 

I will fix it as soon as I can.

**Comment by qooob** [comment]
It will be fixed in _18.49-8_ shortly.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
Thank you qooob! Much appreciated :)

**Comment by qooob** [comment]
You're welcome.
