### ISSUE TITLE
Theme: Running refresh modules, must refresh navigation menu

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#804]
When you click "Refresh Modules" in Webmin, after refreshing, the navigation (left panel) does NOT reflect the refreshed results. Instead I am forced to do a full page refresh (F5) to see the changes.

*** just to clarify, the navigation does appear to reload, but the modules that should now be activated are NOT available in their categories until you fully refresh the page. Perhaps a caching issue or similar. ***

I'm sure this is something simple, so perhaps you can see if this can be addressed in a future update, as it'd be nice if the changes could take effect immediately without the full page refresh.

Cheers!

**Comment by qooob** [comment]
Hi, Peter!

Yeah, thanks. I'll fix that!

**Comment by qooob** [comment]
It will be fixed in _18.49-8_ shortly.
