### ISSUE TITLE
Update notification but already running last version

### ISSUE THREAD

**Issue by Stinkykiller** [qooob/authentic-theme#808]
Provide the following information:
* What is your server-side OS and its version?
CentOS Linux 7.3.1611
* What is your client-side OS, browser and its versions?
Different browsers (IE, FF, Opera,...)
* What are the steps to reproduce the issue
Every time i log into Virtualmin after short period of time i will get the notification that new theme is available. This will show as push notification and in right menu under notifications, but not next to the theme version like it shows when there is real (available) update. This bug started with 18.49 or 18.49-1 update and persist until now (v. 18.49-7). Aside of be annoying i didnt see any other downside, but like i said it start to be annoying. If during the day i log 20 times into Virtualmin and stay logged for more than few min the notification will show out.

**Comment by qooob** [comment]
Hi,

In case you use incognito mode for logging in or clear browser's cache it's what happens?

**Comment by qooob** [comment]
In case you're on 18.49-7 it shouldn't be happening. In case you're on previous versions please update manually using instructions from this tread https://github.com/qooob/authentic-theme/issues/787#issuecomment-304617121

**Comment by Stinkykiller** [comment]
I'm on 18.49-7 and all my browsers are set to automatically clear all cache once i close them. Still this should not be relay on my browser cache but it should be 100% handled from the server side.

**Comment by qooob** [comment]
Probably you're right. At the moment it does rely on the browser.

I'll think about if it's possible to move it to the server-side.
