### ISSUE TITLE
File selector filter broken

### ISSUE THREAD

**Issue by samatcd** [qooob/authentic-theme#81]
It looks like the filter filter is broken in version 9.0.2 with Webmin 1.730.

![screen shot 2015-02-03 at 10 18 37 pm](https://cloud.githubusercontent.com/assets/1476991/6017455/a38f3bee-abf2-11e4-828a-aefa0aa5b503.png)

**Comment by qooob** [comment]
Sam, thank you for reporting! I will fix it in the next release!

**Comment by samatcd** [comment]
Thanks :-)

**Comment by qooob** [comment]
I have a problem finding it. Each one I click works fine. Where it didn't work? Which module?

**Comment by qooob** [comment]
Found one place where it didn't work. Fixed it. Most likely it will fix it everywhere. 

..but just send me the module if you remember, where it was to double check..

**Comment by qooob** [comment]
It's fixed in 9.0.3. Please update.

**Comment by samatcd** [comment]
I was using it in Apache Webserver module when setting up a new virtual host. Working well now, thanks :-)
