### ISSUE TITLE
Can't read mailboxes after updating to 18.49-8 :(

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#811]
I updated to `18.49-8` and now i can't read my mailboxes `https://192.168.0.12:10000/mailboxes/`. If i change to `Gray framed` it work.
![picpick-2017 06 01-00 10 06](https://cloud.githubusercontent.com/assets/5789283/26656278/ad788a1c-465e-11e7-8473-64282ef0e304.png)

**Comment by qooob** [comment]
This version for the next release.

Find config file under theme colder and replace:

`cs_header=ffffff" class="thead`

with

`cs_header=ffffff class=`thead`

**Comment by qooob** [comment]
Updated the string above. Check it over again.

**Comment by Sopor-** [comment]
It is working again!
