### ISSUE TITLE
Theme: Drop hardcoded reference to theme's directory

### ISSUE THREAD

**Issue by v1nce** [qooob/authentic-theme#812]
As authentic-theme seem to be the theme of choice for webmin, this is the one I choosed to try to tweak it [*] a bit. So I started to clone the theme (without breaking current installation).
I just exported the theme using webmin. Unzipped the theme.gz. change name of the holding directory. Edit the theme.info to change the name and zipped it back.
I managed to import it back but it is not working. I got messages about file missing.
I guess it's because there are hardcoded reference to "authentic-theme" in a lot of cgi.

It looks to me like there was some attempt to use a var for the theme directory ($config_directory . "/" . $current_theme) 

How difficult would it be (for a total newbie) to replace the hardcoded references ?
If I patched the authentic.pm, authentic-init.pm and authentic-lib.pm would I get a minimal working webmin ? (minimal = UI + dashboard are working ; some modules may crash)

[*] I want to add xhr whenever this is possible and generate most (all ?) of the UI on the client side.

**Comment by qooob** [comment]
Yes, this is the current drawback. I've started on working on completely renewed version 19.00. I will try to make sure that the path is not hardcoded there.

Meanwhile, I don't know how hard it would be. Probably replacing `authentic-theme` with `$current_theme` should do the work.

**Comment by qooob** [comment]
It will be added to 19.00-RC9 about tomorrow.

Thanks.
