### ISSUE TITLE
Latest Webmin 1.844 and extra option for Authentic theme

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#813]
I use latest Webmin 1.844 and latest Ubuntu, I have a problem: https://www.virtualmin.com/node/52431#comment-777429

don't really think Webmin will change it, so perhaps easier method is add option to Authentic Theme to disable information about: **Warning! The 4.38 MB filesystem mounted at /snap/canonical-livepatch/22 has no free disk space!**  from System Information.

Is this possible?

**Comment by qooob** [comment]
It is possible. Theme is hackable.  Add the following to theme's extension (JavaScript):

```JavaScript
$(function() {
     $('div.alert:contains("filesystem mounted")').remove();
});
```

**Comment by Depicus** [comment]
When you say the theme is hackable can you describe where exactly this javascript file is ? As I see no .js files in the theme.

**Comment by qooob** [comment]
It's in Theme Extension manager. Search for `Extension` in the autocomplete bar and choose it. Later you can inject your own JS,CSS, PL files.

Version 19.00 will have better support for JS, letting a user run code exactly on, either load or document ready.
