### ISSUE TITLE
Error Perl execution failed : Wide character in syswrite at miniserv.pl at webmin v. 1.840

### ISSUE THREAD

**Issue by LeonanCarvalho** [qooob/authentic-theme#814]
* What is your server-side OS and its version?
CentOS 7
* What is your client-side OS, browser and its versions?
Any
* What are the steps to reproduce the issue
Install webmin 1.840 from public repo. (or rpm file) and change theme to 'authentic'.

I was using Authentic Theme before, when I updated to latest version the main page wasn't available (img 1).
When you access the main page, the error `: Perl execution failed : Wide character in syswrite at /usr/libexec/webmin/miniserv.pl line 3109.` happens (only in log file).

Its possible to access directly to other pages (img2).

Using bootstrap theme, everything is working(Img3)

Img1:
![image](https://user-images.githubusercontent.com/3593706/26877278-c2bea39c-4b5f-11e7-9728-68b9537a1692.png)

Img2:
![image](https://user-images.githubusercontent.com/3593706/26877160-611fb838-4b5f-11e7-96ba-a8e670d4f895.png)

Img3:

![image](https://user-images.githubusercontent.com/3593706/26877096-3388d3be-4b5f-11e7-8f73-2b104857200b.png)

LOG:
```
[06/Jun/2017:19:45:03 +0000] [127.0.0.1] /unauthenticated/gray-reset-fonts-grids-base.css : File not found
[06/Jun/2017:19:45:03 +0000] [127.0.0.1] /unauthenticated/gray-virtual-server-style.css : File not found
[06/Jun/2017:19:45:03 +0000] [127.0.0.1] /unauthenticated/sorttable.js : File not found
[06/Jun/2017:19:45:04 +0000] [127.0.0.1] / : Perl execution failed : Wide character in syswrite at /usr/libexec/webmin/miniserv.pl line 3109.
```
Additional info:

> Installed Packages
> Name : webmin
> Arch : noarch
> Version : 1.840
> Release : 1
> Size : 77 M
> Repo : installed
> From repo : Webmin
> Summary : A web-based administration interface for Unix systems.
> License : Freeware
> Description : A web-based administration interface for Unix systems. Using Webmin you can
> : configure DNS, Samba, NFS, local/remote filesystems and more using your
> : web browser.
> :
> : After installation, enter the URL http://localhost:10000/ into your
> : browser and login as root with your root password.

To solve that I changed config files to grey(and ungly) theme.

**Comment by qooob** [comment]
Hi,

What you're saying is invalid.

1.840 already has Authentic Theme set as default.

**Comment by qooob** [comment]
The solution could be is hard reload the page.

**Comment by LeonanCarvalho** [comment]
No it's not, the issue is real, and also happened to others:
 https://sourceforge.net/p/webadmin/bugs/4753/.

I forgot to say that started when I updated the webin, (yum update), it's not a fresh install, but I was using  Authentic Theme  before the update and It was working fine.

After the update, the main page wasn't available(img 1) (when this issue started), its possible to access directly to other pages (img2).
Using bootstrap theme, everything is working(Img3)

Img1:
![image](https://user-images.githubusercontent.com/3593706/26877278-c2bea39c-4b5f-11e7-9728-68b9537a1692.png)

Img2:
![image](https://user-images.githubusercontent.com/3593706/26877160-611fb838-4b5f-11e7-96ba-a8e670d4f895.png)

Img3:

![image](https://user-images.githubusercontent.com/3593706/26877096-3388d3be-4b5f-11e7-8f73-2b104857200b.png)

**Comment by qooob** [comment]
Beta1? You updated manually to Beta1? This is preview version and must not be used. There are many things that don't work. Downgrade please to 18.49-8 and things will get back to normal again.

**Comment by LeonanCarvalho** [comment]
It's happening with 1849-8  too.

![image](https://user-images.githubusercontent.com/3593706/26878154-d403b3b0-4b62-11e7-97e7-61cfaf07385f.png)

I tried all last 5 versions, so I forgot to downgrade to stable version when I did this print screens.

**Comment by qooob** [comment]
That is odd. What language/charset do you have set?

**Comment by qooob** [comment]
Tried `update-theme.sh` script to force update the theme?

**Comment by LeonanCarvalho** [comment]
> Tried update-theme.sh script to force update the theme?

How can I do that?
Thanks

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/blob/18/README.md#how-to-update-authentic-theme-manually

**Comment by LeonanCarvalho** [comment]
![image](https://user-images.githubusercontent.com/3593706/26887473-7f291db4-4b7e-11e7-989e-95ad41159e28.png)

Same
My previously webmin version was 1.831, may should I clean up something else?
Thanks

**Comment by qooob** [comment]
It can be anything, I think. It's system specific but not the theme issue.

I would just run `yum reinstall webmin`.

I wish I could help more, but without seeing it, it's very hard to do.

**Comment by qooob** [comment]
What is your language/charset?

**Comment by LeonanCarvalho** [comment]
I had already tried this procedure,
I stopped the service, installed it, ran the update_theme.sh.
I tryed english and portuguese versions.

Note that the error only happens with the authentic theme.

**Comment by qooob** [comment]
I think I know the source of the issue.

I must say that you need to install latest Webmin or previous version of the theme, meaning that it should be lower than 18.49. 18.48 for example.

You can update Webmin from Virtualmin repo.

```Bash
yum update http://software.virtualmin.com/gpl/universal/webmin-1.844-1.noarch.rpm
```

Version of the theme 18.49-8 that you can only install manually, will only work with Webmin 1.844+.

**Comment by LeonanCarvalho** [comment]
![image](https://user-images.githubusercontent.com/3593706/26948628-73c830fa-4c6d-11e7-9715-9b5c41b807a6.png)
