### ISSUE TITLE
Cluster: User and Group - Add User missing fields

### ISSUE THREAD

**Issue by markwillia** [qooob/authentic-theme#816]
Theme: 18.49-8
Webmin: 1.840
Provide the following information:
* What is your server-side OS and its version?
CentOS 7.3
* What is your client-side OS, browser and its versions?
CentOS 7.3 & Ubuntu 16.04
* What are the steps to reproduce the issue
When adding a NEW user via Cluster Users and Group:Add Users.... The field for Username,User ID, Real Name & Office are missing.

**Comment by qooob** [comment]
Hi,

Not sure what you mean? Do you see those fields in one of the old themes?

I can see that you updated manually to the theme that has to be used with Webmin 1.843+. 

I'd recommend downgrading the theme to _18.48_ in case issue persists or upgrade to the latest Webmin, using [Virtualmin repos](http://software.virtualmin.com/gpl/universal/?C=M;O=D).

Here is the screenshot of how it looks on my side with Webmin 1.843 and theme 18.49-8.

![screenshot from 2017-06-15 23-34-01](https://user-images.githubusercontent.com/4426533/27200786-d70b77d8-5223-11e7-821e-bd3fb6f8cf19.png)

**Comment by qooob** [comment]
I will have to update 18.48-8 and make Webmin 1.843+ as minimum required version.
