### ISSUE TITLE
Firewall: Button not rendered correctly with non-unicode charset

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#817]
This may not a problem because we should use UTF-8 whenever possible, but while testing my firewall/firewall6 rework I noticed that buttons are displayed different when using `en` and `en.UTF-8` language, same happen with `de` and `de.UTF-8`.

`en.UTF-8`:

![grafik](https://user-images.githubusercontent.com/4593242/27337444-b81f8758-55d2-11e7-99d1-9ba5f292fcca.png)

`en`:

![grafik](https://user-images.githubusercontent.com/4593242/27337480-d6c634c2-55d2-11e7-9626-496bfef3481e.png)

suprising is also that sometimes the first `Add rule` button is green, sometimes the [last one](https://user-images.githubusercontent.com/4593242/27335859-2f394a90-55ce-11e7-8964-08d2743c4759.png)

**Comment by qooob** [comment]
That is interesting how could this be possible indeed. I will take a look for the cause.

**Comment by qooob** [comment]
It's not because of `non-unicode`/`unicode`. You can reload the page multiple times and see different result each time. 

It's the other issue that _can't be solved_ really at the moment.
