### ISSUE TITLE
Change time on authentic-theme from AM/PM to 24 hour clock?

### ISSUE THREAD

**Issue by TheBudda** [qooob/authentic-theme#819]
Before posting an issue, please search through README.md and closed/opened issues to make sure that the answer to your questions hasn't been answered/discussed already.

Please make sure that you have latest theme (18.49-8) and Webmin (1.850) versions installed.

Provide the following information:
* What is your server-side OS and its version? Debian Linux 9 
* What is your client-side OS, browser and its versions? Chrome or Opera
* What are the steps to reproduce the issue. I would like to have your authentic-theme on a 24 hour clock. I have tried to find an answer but no luck. Can you please help?

Kind regards
Budda

**Comment by qooob** [comment]
Yes, sure, check the theme's settings. It's there.

**Comment by qooob** [comment]
You could set _Full date/time format_ to value:

```Config
MMMM DD, YYYY, H:mm:ss
```

**Comment by TheBudda** [comment]
Yes, that did the trick! Thank you for your help

**Comment by TheBudda** [comment]
Hi, Sorry Guys n Dolls, I can find the time setting any more. It seems in the new theme update there is no setting for this. I have looked everywhere in Webmin. How do I change my servers to 24hr clock in the Webmin?  

webmin: 1.881 | Ubuntu 18.04 | Authentic Theme 19.09.2

Regards
Budda

**Comment by TheBudda** [comment]
Found it DOH!! :/

**Comment by rostovtsev** [comment]
New release of Webmin will bring the latest theme version that will have much better support for locale. It will be controlled from _Webmin/Change Language and Theme_.

**Comment by TheBudda** [comment]
Yes, I have just seen this is Webmin/Change Language and Theme in a thread you replied to about the same time issue a few days back. I have now changed my clock to 24 hr :)
