### ISSUE TITLE
'Apache Webserver' config screen link to external page is broken

### ISSUE THREAD

**Issue by samatcd** [qooob/authentic-theme#82]
Under the URL column, clicking 'Open' is supposed to open a link to the actual website, however it looks like Authentic is hijacking the request, and attempting to AJAX in the page.

![screen shot 2015-02-03 at 10 57 33 pm](https://cloud.githubusercontent.com/assets/1476991/6018234/183a7740-abfa-11e4-9624-354207bcc338.png)

This link only exists after selecting 'Display virtual servers as list' in Module Config.

Console outputs:
Refused to frame 'https://external.domain/' because it violates the following Content Security Policy directive: "frame-src 'self'".

You may need to further filter 'a' elements with href's that begin with an external address.

**Comment by qooob** [comment]
Alright, I fixed it. It's actually Webmin bug I believe, because simply it would be easier just to add to all external links `target="_blank"`.

Now theme will check for all external links on click and if it's the case (if it's external), will open it in new window to prevent errors.

**Comment by qooob** [comment]
It's fixed in 9.0.3. Please update.

**Comment by samatcd** [comment]
Thats great, thanks — works very well :-)
