### ISSUE TITLE
Theme: Night mode doesn't show on login screen

### ISSUE THREAD

**Issue by sinankizar** [qooob/authentic-theme#822]
Hello;
I am a big fan of night mode and lately I am not being able to change it to night mode of login window. I have uninstalled authentic theme and webmin and then reinstalled but that didn't solve the issue. I know it is just an eyecandy but if you can provide a solution I will be more than happy.
Server OS: Ubuntu 16.04
Client OS: Windows 10
Client browsers: Firefox and IE
Webmin: 1.850
Authentic Theme: 18.49-8

Thanks in advance.

**Comment by qooob** [comment]
I think it doesn't work for you, because you login as non-root user. In order to make login screen displayed in dark, you need to login as root and change it to dark being under this user.

**Comment by qooob** [comment]
..and it's pleasure to hear that you use it.. it's been very hard to make it.. and there is space for improvement still.

**Comment by sinankizar** [comment]
Thank you for your great efforts and for your kind and very fast support. I will be lost without authentic theme :)
But here is the issue, I am logging as user "root" as I login to my server's ssh. I have tried to clear caches of the theme, my browsers and my server as well. What else can I do? I don't wan't to bother you with such a little and unimportant issue. If you don't have time for this, I will understand and it's really not important. But again, thank you :)

**Comment by qooob** [comment]
When you login do you see it dark?

**Comment by sinankizar** [comment]
Yes I am seeing the theme in dark mode when I logged in.

**Comment by qooob** [comment]
Oops. I'm very sorry. This is right. I also see it.

I will fix it upon next release.

Thanks!

**Comment by sinankizar** [comment]
Oh it is a bug really then. Glad I had helped to find it. Cheers.

**Comment by qooob** [comment]
It will be working in 19.00-RC9.

I will releases it in an hour or so.

**Comment by Benman2785** [comment]
again not working with 19.75

**Comment by iliarostovtsev** [comment]
It does work. The source of problem is that there were huge change under the hood (code refactoring), and some options names had to be change.

It will work if you re-save it again in theme configuration.

**Comment by Benman2785** [comment]
ok - found the "error"
webmin used "authentic theme" but in webmin config it used "gray" - this is why the login screen was not dark
now i changed it and everything works ;)
