### ISSUE TITLE
error message from snap "filesystem has no space left"

### ISSUE THREAD

**Issue by snickers2k** [qooob/authentic-theme#823]
getting this error:

> Warning! The 80.50 MB filesystem mounted at /snap/core/2381 has no free disk space!

in this topic, they suggest it's an theme "problem" ?

https://askubuntu.com/questions/927315/no-free-diskspace-warning-while-using-transactional-updates

thanks

**Comment by qooob** [comment]
Hi, it's not the theme problem really.

Theme is hackable and you can make things work for your self anyway you want.
