### ISSUE TITLE
File Manger: Using linked server not loading dependencies

### ISSUE THREAD

**Issue by jvenezia52** [qooob/authentic-theme#824]
Main server is Centos 6.4 with linked servers Ubuntu 16.04, Ubuntu 14.04 and Centos 7 all with WebMin 1.85 and current theme

Using Chrome 59 stable on ubuntu 16.04/Gnome

If not using the link.cgi from main server, it loads the theme correctly, with link.cgi, no sorting, filter at top or right click context menu.  It does show like something isn't completely loading.
![file manager webmin 1 850 on mssqlubuntu mga local ubuntu linux 16 04 2](https://user-images.githubusercontent.com/30273122/28339708-ff39c8c4-6bda-11e7-856d-42259fd90665.png)

**Comment by qooob** [comment]
Hi,

Could you please open console, reload File Manager and post me the screenshot?

**Comment by jvenezia52** [comment]
[image: Inline image 1]

**Comment by qooob** [comment]
I see no image?

**Comment by qooob** [comment]
Hi, 

Could you please provide the image? Your inline image doesn't seem to be visible.

**Comment by qooob** [comment]
I need to take a look at the screenshot with an error in console? Could you please do it for me?

**Comment by qooob** [comment]
Do you still have this issue using latest 19.xx?

**Comment by qooob** [comment]
It's fixed. Thanks for reporting.

Ref.: https://github.com/qooob/authentic-theme/issues/925
