### ISSUE TITLE
Cosmetic Bugs

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#825]
I just installed the 19.00 RC1 theme, looks good so far.

Came across one minor bug. The "Time on system" shows twice. See screenshot.
![datetime-dashboard vm-at-19 00-rc1](https://user-images.githubusercontent.com/4305218/28496998-351485b2-6f30-11e7-8ec9-c97fc7122b28.png)

**Comment by tpnsolutions** [comment]
Another bug I just discovered. The pie charts showing usage on the "System Information" page don't render correctly after returning from a few pages.

To replicate:

Login => Theme Configuration (button on bottom left panel) => System Information (bottom of left panel).
![usage-pies vm-at-19 00-rc1](https://user-images.githubusercontent.com/4305218/28497039-3a0ecd2e-6f31-11e7-8f60-59607d7c6035.png)

**Comment by tpnsolutions** [comment]
It should also be noted. The last stable version doesn't show the "percentage" centered, it's shifted to the left of the pie chart.

**Comment by qooob** [comment]
Peter, hi.

Thanks for taking a look. I'm glad someone got interested in first RC.

I'll release RC2 soon with bug fixes and code change.

**Comment by qooob** [comment]
Please for further reports use https://github.com/qooob/authentic-theme/issues/807

**Comment by qooob** [comment]
It will be fixed in RC2.
