### ISSUE TITLE
Large file delete issue

### ISSUE THREAD

**Issue by Lolcsi** [qooob/authentic-theme#827]
I found a bug large file 5GB+ deleting it does not happen. File Manager not responding or freeze.

**Comment by qooob** [comment]
Hi,

What system are you running and what architecture is that? What is the filesystem?


---


I just made a test and deleted **~78Gb file**, and all worked as expected - the file was deleted.


>Hi qooob!
Ubuntu Linux 14.04.3
Webmin version | 1.851
Usermin version | 1.720
Virtualmin version | 5.99
Theme version | Authentic Theme 18.49-8
Kernel and CPU | Linux 3.13.0-24-generic on x86_64
Processor information | Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, 4 cores
Filesystem | ext4
I tested on virtualmin backup file!

I also tested it with ext4 but on RHEL. Are you sure the file size is the issue? If you try to change directory does it work correctly?

Do you maybe get errors in the console? If so, could you share the screenshot?

>Yes I deleted many smaller file

Still, do you have errors in console? Can you try again?

![28678030-9252e314-72ef-11e7-991d-03f289562f7f](https://user-images.githubusercontent.com/4426533/28678200-6f158ede-72f8-11e7-82f4-26c5f90b1676.jpg)

**Comment by qooob** [comment]
Do you login as root, I suppose?

Do you run behind proxy?

**Comment by Lolcsi** [comment]
yep
no

**Comment by qooob** [comment]
Did you try to `Ctrl+Shift+R` to hard reload the page?

**Comment by qooob** [comment]
What is the browsers, by the way?

**Comment by qooob** [comment]
You blacked out the text on the screenshot, can you post it the same format that is there but changing letters only? I just need to know if the path has any non-alphabetic characters?

**Comment by Lolcsi** [comment]
Hard reload working but file is not deleted. I use chrome browser and only alphabetic character in file name and folder name.

**Comment by qooob** [comment]
Can you open console and Network tab. Clear it. Then go to that file and try to delete it. 

In the name column there should be the file name, click it.

What is there in subsequent tabs: _Headers_ and _Response_?

**Comment by Lolcsi** [comment]
Sorry for late reply you. 
![stuck deleting](https://user-images.githubusercontent.com/23224558/28715326-9fb0c4ce-7397-11e7-8fae-e88aae397b60.jpg)
![stuck deleting1](https://user-images.githubusercontent.com/23224558/28715329-a2de3e92-7397-11e7-8853-73c5fdb448ca.jpg)

**Comment by Lolcsi** [comment]
![stuck deleting2](https://user-images.githubusercontent.com/23224558/28717064-8dddd4c2-73a0-11e7-9d1c-f3b2c6cc0911.jpg)

**Comment by qooob** [comment]
Interesting.

Do you have any extensions installed? If so, can you please try doing the same in Incognito Tab?

**Comment by Lolcsi** [comment]
No chrome extension just only one adblocker but not blocking this site.

**Comment by qooob** [comment]
Can you please try Incognito Mode?

**Comment by Lolcsi** [comment]
Of course but result is same

**Comment by qooob** [comment]
I will have to install the same operating system and try to reproduce it. A bit later, when I have spare time for it, most likely after releasing 19.00-RC2.

Did you change miniserv default settings?

**Comment by Lolcsi** [comment]
![stuck deleting3](https://user-images.githubusercontent.com/23224558/28717625-e1f06776-73a2-11e7-9a2a-3478f6411ede.jpg)

**Comment by Lolcsi** [comment]
I don't know. What is that?

**Comment by qooob** [comment]
Webmin/Webmin Configuration/Web Server Options or other configuration options related to Webmin's web server.

**Comment by qooob** [comment]
.. I suppose you didn't..

I will take a look later. No problem. I just don't have this version of Ubuntu installed right now.

**Comment by Lolcsi** [comment]
thank you for help and good support

**Comment by qooob** [comment]
You're welcome.

**Comment by qooob** [comment]
I have just tested it in _Ubuntu_ and latest, upcoming version 19.00-RC9.

**It's working as expected.**

I will close this issue for now. In case, after the release, it will be an issue for you, feel free to reopen this issue.
