### ISSUE TITLE
Theme: Implement `history -d` in terminal

### ISSUE THREAD

**Issue by XhmikosR** [qooob/authentic-theme#828]
https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html

**Comment by qooob** [comment]
Yes, I actually remember.

Thanks, pal for opening an issue. I will try. ;)

**Comment by XhmikosR** [comment]
Yeah, I had forgotten to open an issue :/

I wonder @qooob, would it also be possible to implement <kbd>ctrl+R</kbd> for reverse searching of history?

**Comment by qooob** [comment]
What do you mean by _reverse searching_? Why not use browser search?

My name is Ilia, by the way! ;)

**Comment by XhmikosR** [comment]
But how would you search your terminal history via browser history? That is what <kbd>ctrl+R</kbd> does in unix :)

**Comment by qooob** [comment]
Oh, that's what you want. Sure it's possible.

**Comment by qooob** [comment]
This is actually interesting that you are asking about Ctrl+R search. How about using `history |grep string`?

**Comment by XhmikosR** [comment]
I think `Ctrl+R` is the standard way so that would be the ideal solution.

**Comment by qooob** [comment]
Okay.

**Comment by qooob** [comment]
This functionality been added with https://github.com/qooob/authentic-theme/commit/d270dbfa7435488acda3ca6e95ca58fae01dda5e commit.

To remove from theme's command shell's history use:

```Bash
history -d [n]
```

To show history use:


```Bash
history
```

To clear history use:


```Bash
history -c
```

**Comment by XhmikosR** [comment]
Thanks!

**Comment by qooob** [comment]
> I wonder @qooob, would it also be possible to implement ctrl+R for reverse searching of history?

Now I see this feature is necessary.

I'll try adding it. Thanks.

**Comment by rostovtsev** [comment]
@XhmikosR `Ctrl+R` search in drop-down command shell is now implemented. Give it a try in the latest dev version! :wink: 
![screenshot from 2019-02-19 18-18-24](https://user-images.githubusercontent.com/4426533/53025922-f7cf8800-3472-11e9-9662-c076ad429e2e.png)

**Comment by XhmikosR** [comment]
Thanks, I'll try it in the next stable version :)

**Comment by rostovtsev** [comment]
You can try it already! It would be great actually if you tried it before, to avoid possible bugs in the release.

**Comment by XhmikosR** [comment]
Sorry, I don't have a dev machine available to test :/

**Comment by XhmikosR** [comment]
@rostovtsev: works pretty good, nice!

**Comment by rostovtsev** [comment]
Good to know. :wink: Thanks for giving it a try!
