### ISSUE TITLE
Display of Webmin and Virtualmin

### ISSUE THREAD

**Issue by Bonface-Njuguna** [qooob/authentic-theme#829]
![capture](https://user-images.githubusercontent.com/25118165/29355378-808806a2-8279-11e7-9d6f-b005b819fcd6.PNG)
Hello there,
We have an authentic theme for Webmin, it has been functioning but some weeks back the panel for Webmin and Virtualmin did not show up. It only shows the display of dashboard.

I'm really looking forward to your helpful feedback here in Turkana Kenya. Thanks!

Regards,
Bonface Njuguna

**Comment by qooob** [comment]
Hi,

What Webmin/Theme versions are you using? What is you Linux distro?

**Comment by Bonface-Njuguna** [comment]
Sorry, I'm new to this, I think we are using Webmin version 1.851 but I don't know, the Linux distro is 4.10.0-0-30-generic

**Comment by qooob** [comment]
Do you have anything under Webmin tab?

_Sent from my HTC MSM8996 for arm64 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bonface-Njuguna** [comment]
Nope, when I click the Webmin tab it takes me to the dashboard tab.

**Comment by qooob** [comment]
That is right, but do you have items in the menu? Now it looks empty?

_Sent from my HTC MSM8996 for arm64 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by qooob** [comment]
In case you don't see any modules you need to make sure that they are enabled in ACL.

Please refer to the familiar issue. https://github.com/qooob/authentic-theme/issues/826#issuecomment-318338716

**Comment by qooob** [comment]
Read everything from that comment and below.

**Comment by Bonface-Njuguna** [comment]
Okay thanks, I'll get back to you and sorry for the delay of reply

**Comment by Bonface-Njuguna** [comment]
Hello there, thanks for your help. Using the comments we managed to tackle the problem and our server is back on. Thanks again
