### ISSUE TITLE
Issue with module ConfigServer Security & Firewall (csf)

### ISSUE THREAD

**Issue by TrakerBG** [qooob/authentic-theme#83]
Environment:
VPS 512 MB RAM, ~200 MB used, Authentic Theme 9.0.2, ConfigServer Security & Firewall version 7.60, Webmin version 1.730, CentOS Linux 6.6 32-bit, user root
Only in module ConfigServer Security & Firewall, when clicking on any of the buttons in the module, nothing happens, only loading animation is shown.
Csf reinstalled, webmin restarted and reinstalled (both with forced upgrade), no luck.
![11](https://cloud.githubusercontent.com/assets/10828086/6018811/586e9ede-aba2-11e4-9520-f9f2fa67ff15.jpg)
![22](https://cloud.githubusercontent.com/assets/10828086/6018812/586f2796-aba2-11e4-94ba-08cc36f4f0b6.jpg)

**Comment by qooob** [comment]
Yes, thank you for reporting! I have just fixed it and will release new update shortly.

To workaround before I updated it, use Chrome browser and not Firefox! This issue happened only in Firefox.

**Comment by qooob** [comment]
It's fixed in 9.0.3. Please update.
