### ISSUE TITLE
Display of CPU Raspberry PI temperature

### ISSUE THREAD

**Issue by Jufo84** [qooob/authentic-theme#830]
Hi,

How can you display CPU temperature with Raspberry Pi?
Just enter the command line: "/ opt / vc / bin / vcgencmd measure_temp". We get the answer: "temp = 39.5'C"
I understand that you should modify the file "sysinfo.cgi", very much ask for help as it should look.

Best Regards,
Robert

**Comment by qooob** [comment]
Hi,

Theme is just using data supplied by WebminCore. You should please submit this bug to [Webmin Repo](https://github.com/webmin/webmin).
