### ISSUE TITLE
fix fail2ban input to allow strings in variable input

### ISSUE THREAD

**Issue by kenkit** [qooob/authentic-theme#831]
The following does not work as parameter for fail2ban action
` abuseipdb[abuseipdb_category=22,my_comment="ssh hacking attempt"]`
It endsup being parsed as 
` abuseipdb[abuseipdb_category=22,my_comment=]`

**Comment by qooob** [comment]
Hi,

Do you think it's the theme issue?

It looks more like module's issue. Could you please report it to [Webmin repo](https://GitHub.com/Webmin/Webmin) unless this issue can't be reproduced in Gray Theme.

**Comment by kenkit** [comment]
okay
