### ISSUE TITLE
Notifications about new version keep on alerting, although they have been installed

### ISSUE THREAD

**Issue by siebej** [qooob/authentic-theme#833]
When new versions of authentic theme have been installed, this is not recognized when you visit the site with an other browser. Looks like the info about a new version is stored in a cookie rather than on the server?

**Comment by qooob** [comment]
Hi,

It's stored in localStorage not the cookie.

**Comment by qooob** [comment]
It's not stored on the server yet.

**Comment by siebej** [comment]
Hi qooob,
Hope that you fix this. The notification is not correct. I hate red bullets ;-). 
Succes Siebe

**Comment by qooob** [comment]
Yes, it's on my to-do.

**Comment by qooob** [comment]
It will be added to the final 19.00 release.

However, for a while it will still be browser bind (using localStorage). It will not notify updates twice though and it will mark as read, all previous notifications of the same kind.

**Comment by siebej** [comment]
Nice
