### ISSUE TITLE
IPTables / Firewall Cluster Servers

### ISSUE THREAD

**Issue by quayfee** [qooob/authentic-theme#834]
There's a bug in the generation of the list of clustered servers in the IPtables module.
All of the checkboxes are being assigned no ID and the label associated with the group name (and therefore acting only on the first checkbox and something in the CSS is not quite working correctly with the actual checkboxes visible outside of the table.

I'm seeing this on 
Chrome (latest version)
Webmin 18.52
Athentic 18.49-9
CENTOS 6.9

But has been present in previous versions.

I'm very happy to try and take a look but might need a little guidance.

**Comment by quayfee** [comment]
On a further note: I have looked at the same page in the old virtualmin framed theme and I suspect that it's the default bootstrap behaviour partially kicking in injecting labels and trying to 'prettify' the checkboxes, but something is missing.

**Comment by qooob** [comment]
What is the id of the checkbox? Does it contain special chars? Could you attach a screenshot please?

**Comment by quayfee** [comment]
The checkboxes don't appear to have an id, just a name attribute, which I suspect is part of the issue.
![cluster 2](https://user-images.githubusercontent.com/1534026/30805645-336a5272-a1ea-11e7-8697-89ecfdf3af79.JPG)
![cluster1](https://user-images.githubusercontent.com/1534026/30805647-35b8fd26-a1ea-11e7-8151-22dcdc2dffdb.jpg)

**Comment by qooob** [comment]
I see now. Thanks. I'll take a look. :sweat_smile:

**Comment by quayfee** [comment]
Cool! Happy to help in any way I can

**Comment by gnadelwartz** [comment]
jamie merged a big firewall update a few days ago. does this happen with this update also?

**Comment by qooob** [comment]
@quayfee Do you still see this issue with latest 19.01? Can you give it a try please?

**Comment by qooob** [comment]
It's fixed. Give it a try.

**Comment by quayfee** [comment]
Hi qooob, Just back in the office, I will check it out this afternoon. Thanks
