### ISSUE TITLE
No extraction option

### ISSUE THREAD

**Issue by Keltere** [qooob/authentic-theme#839]
Webmin: 1.850
Authentic-theme: 19

OS:Archlinux 4.13.3-1

I've installed 7z, unrar, zip etc... Everything is updated, i've also installed shared-mime-info and configured MIME on webmin but the extract button won't come out.

I've tried restarting the webmin service, reinstalling, clear cache, different browser (chrome, firefox, edge)
nothing seems to work. I can't understand where is the problem.

![capture](https://user-images.githubusercontent.com/8084245/31132362-43b402be-a865-11e7-9d18-10ad045d09fa.JPG)

![capture2](https://user-images.githubusercontent.com/8084245/31132305-23f82e78-a865-11e7-8587-da49fbb9c88a.JPG)

**Comment by qooob** [comment]
How about `unzip`? :)

**Comment by Keltere** [comment]
Ok that was a quite epicfail...

Really really thanks that worked but i still can't use for rar files... any suggestion?

**Comment by qooob** [comment]
You want to create rar? if so that is not supported yet.

**Comment by Keltere** [comment]
Nope, just extract

**Comment by Keltere** [comment]
I've already installed unrar and rar, but the file is not recognized as archive
![capture3](https://user-images.githubusercontent.com/8084245/31134256-4057fea4-a86a-11e7-9811-82385b690edc.JPG)

**Comment by qooob** [comment]
It should work. Looking at this file, I remember I made it work.

https://github.com/qooob/authentic-theme/blob/master/extensions/file-manager/extract.cgi

**Comment by qooob** [comment]
If you reload with the circle button in File Manager controls, will you have it? Do you happen to have it in context menu?

**Comment by Keltere** [comment]
Yes, i also tried to restart the service but nothing. It won't show up.

**Comment by Keltere** [comment]
tried with 7zip and it's working fine, just rar file

**Comment by Keltere** [comment]
Talked to my friend with manjaro and he has the same problem, everything works except for rar files.

**Comment by qooob** [comment]
I would need to install Archlinux to test it. You most likely would have the same behavior in old themes.

Meanwhile I made a quick test on Debian by installing `unrar` and here is what I got:

![screenshot from 2017-10-03 22-13-03](https://user-images.githubusercontent.com/4426533/31144072-353ce764-a888-11e7-9bf9-33dfe0787c26.png)

You need to make sure that you `unrar` command is on the path. In case you open Command Shell in the theme and execute `unrar`, what is the output?

**Comment by qooob** [comment]
Another possible solution is to manually set `MIME Type Program` for `rar`.

**Comment by Keltere** [comment]
In the command shell it's working. Also i check the MIME configuration for rar and it's everything ok.

Mine rar config vnd.rar.xml
https://pastebin.com/xaB1e9Yf

**Comment by Keltere** [comment]
Tried to refresh mime database with: `update-mime-database /usr/share/mime`
Still not working

**Comment by qooob** [comment]
As you can see on the screenshot, your system doesn't seem to detect MIME type for `rar` files correctly. Try to rename a file manually typing `.rar` at the end. Make sure there is no spaces or foreign characters in the string.

In case it's alright and it still doesn't work, go to _Webmin/System/MIME Type Program_ and set it manually.

**Comment by swelljoe** [comment]
I can add more decompressors to the dependencies in the Virtualmin installer. unzip is already in there, and tar/gz are defaults on all Linux systems regardless, but I can probably add 7z and unrar. Are there any others?

**Comment by qooob** [comment]
Yes, you can see all of the dependencies that are checked in [extract.cgi](https://github.com/qooob/authentic-theme/blob/master/extensions/file-manager/extract.cgi) file. The other is for making `zip` archives.

**Comment by qooob** [comment]
`tar` needs to be checked explicitly as it has `bzip`, `xz` and other dependencies.

**Comment by Keltere** [comment]
Maybe i have found out the problem

https://forum.manjaro.org/t/ark-16-08-1-1-regression-with-rar-files-cant-open-or-extract-them/9622

I will try today to find out some solution... anyway not a webmin problem. Thanks for the support and sorry to have bothered you for nothing.

**Comment by qooob** [comment]
That's okay.

**Comment by Keltere** [comment]
Ok the problem is that they changed "application/x-rar" to "application/vnd.rar"
I've tried to add this custom MIME to webmin but because of the dot i cannot do it.

**Comment by qooob** [comment]
MIME type doesn't need a dot.

https://doxfer.webmin.com/Webmin/MIME_Type_Programs

**Comment by Keltere** [comment]
Yes but shared-mime-info changed from x-rar to vnd.rar so i need to add support to it. I tried editing those 2 file adding vnd.rar but nothing changed. There are other files i need to edit?

/opt/webmin/authentic-theme/extensions/file-manager/extract.cgi
/opt/webmin/filemin/extract.cg

Sorry to bother you.

**Comment by qooob** [comment]
Have a look:

[Arch Linux - Default applications](https://wiki.archlinux.org/index.php/default_applications)

[File Manager - Internal module used to determine the _MIME_ type of a file](https://github.com/webmin/webmin/blob/master/filemin/index.cgi#L7)

**Comment by alexbogias** [comment]
Can you please let me know why I still cant unzip zip files with mime type: application-octet-stream.  Every zip file i upload has this mime type. Why isnt automatically recognized as a zip? Is why my upload machine OS is windows?

**Comment by qooob** [comment]
You upload machine doesn't matter.

Please check _System/MIME Type Programs_.

**Comment by alexbogias** [comment]
Can you give me more info on this?

**Comment by alexbogias** [comment]
I can see that "application/zip" -> "unzip -l %s is enabled! Do I have to add application-octet-stream to unzip -l %s also? Is it safe?

**Comment by qooob** [comment]
This is system specific.

Did you make sure that you have `unzip` installed? I have it displayed as `application/zip` on Ubuntu.

**Comment by alexbogias** [comment]
Yup! I am using Debian 8
And it lists on apt list | grep unzip
unzip/oldstable,oldstable,now 6.0-16+deb8u3 amd64 [installed]

**Comment by alexbogias** [comment]
And I think in Debian 8 there is no update-mime-database

> 
> update-mime-database /usr/share/mime
> -bash: update-mime-database: command not found

**Comment by alexbogias** [comment]
@qooob You mean add application-octet-stream inside those if's ? Isn't application-octet-stream something more general?

**Comment by qooob** [comment]
Oh, man, yeah, I forgot it's the wrong type. Okay.

I'll try to reproduce it on my debug machines.

Is it all Debian 8 machines that affected by this bug or only particular one?

**Comment by alexbogias** [comment]
I just tried in 3x Debian 9 and 1x Debian 8 machine. Everything is **application-octet-stream**
![c354dd97-c283-4127-8d1d-1b4f5d8c4bae](https://user-images.githubusercontent.com/1313467/38336554-d238a126-386a-11e8-80c4-3cf9cc6dc7f0.png)

**Comment by alexbogias** [comment]
Files which are created by virtualmin (backups) looks fine in Debian 9 tho

![ddffdfgd](https://user-images.githubusercontent.com/1313467/38336801-c52842d8-386b-11e8-99a2-a4b83c475670.png)

**Comment by alexbogias** [comment]
And files downloaded with wget by github comes like **application-octet-stream** also
![ddffdfgd](https://user-images.githubusercontent.com/1313467/38336916-2858422c-386c-11e8-8be8-b3c7af4cb164.png)

**Comment by qooob** [comment]
How interesting. I will take a good look tomorrow. 

Thank you for reporting.

**Comment by alexbogias** [comment]
Thank you for making my life easier ;)

**Comment by qooob** [comment]
Can you make a screenshot of MIME type module, as well. Just out of curiosity.

I'll do my best to reproduce it.

Do you exclude permission issue? Do you run SELinux?

**Comment by alexbogias** [comment]
Pemissions?  I am on root:
![sfadfsafsaf](https://user-images.githubusercontent.com/1313467/38338271-8c80e4fc-3871-11e8-8610-7547e79237f6.png)
MIME type module:
![adadad](https://user-images.githubusercontent.com/1313467/38338308-ba664132-3871-11e8-92fb-3615c2a1bff7.png)
SELinux? I am not sure what this does. Firewall? I just use virtualmin's and debian defaults. CSF, IPTables and Fail2Ban on Debian 9

**Comment by qooob** [comment]
Okay, I have exactly the same MIME types sets.

I was looking at _MimeInfo.pm_ file and here is what I found:

```Perl

=head1 METHODS

=item C<mimetype($file)>
If these methods are unsuccessful the file is read and the mimetype defaults
to 'text/plain' or to 'application/octet-stream' when the first ten chars
of the file match ascii control chars (white spaces excluded).
If the file doesn't exist or isn't readable C<undef> is returned.

=item C<default($file)>
This method decides whether a file is binary or plain text by looking at
the first few bytes in the file. Used to decide between "text/plain" and
"application/octet-stream" if all other methods have failed.


```

Looking further in the code I found:


```Perl
no warnings; # warnings can be thrown when input not ascii
if ($] < 5.008 or ! utf8::valid($line)) {
	use bytes; # avoid invalid utf8 chars
	$line =~ s/\s//g; # \m, \n and \t are also control chars
	return 'text/plain' unless $line =~ /[\x00-\x1F\x7F]/;
}
else {
	# use perl to do something intelligent for ascii & utf8
	return 'text/plain' unless $line =~ /[^[:print:]\s]/;
}
```


Now, open console and run:

```Bash
file -b --mime your_file_name.extension
```

.. first for files created manually (those that fail, if I understood correctly) and then for those created by Virtualmin scripts (that work correctly).

What is the output? it should be something like:

```Bash
application/gzip; charset=binary
```

What is the output of the command below if run in browser console?

```JavaScript
get_server_data('charset')
```
