### ISSUE TITLE
Theme: Display left menu when opened from links

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [qooob/authentic-theme#841]
(I'm not familiar with github and issues reporting, sorry about that)

I receive email notifications about virtualmin/webmin/debian updates, as configured by a webmin/virtualmni default module, and the issue is that those emails contain an hyperlink to an internal page of the admin...

... And that internal page, once loaded, doesn't include the left column of the virtualmin administration.

Example of one of those mails:

> Subject: Package updates on (ip)
> 
> Contents: 
> An update to webmin-virtual-server from 6.00.gpl to 6.01.gpl is available.
> 
> Updates can be installed at (ip:port)/security-updates/

And the results, once opened, are:

![delete](https://user-images.githubusercontent.com/29028445/31163376-6861c2fe-a8e2-11e7-9fc4-1bce96152d6f.jpg)

Minor issue, sure. But maybe worth reporting, still. Good day everyone!

**Comment by qooob** [comment]
I see now, thank for reporting.

That is not trivial to fix.

I'll see what I can do.

**Comment by qooob** [comment]
Patched in:
https://github.com/webmin/webmin/pull/724
