### ISSUE TITLE
Sending mails in usermin fails with v19.00

### ISSUE THREAD

**Issue by andyhirsch** [qooob/authentic-theme#842]
With Authentic Theme 19.00 sending mail in usermin produces following error:
Expecting form-data encoding but got normal encoding

If I revert to 18.49-9 everything's fine again.

**Comment by qooob** [comment]
I see the cause of the issue.

Thanks for reporting.

**Comment by alejandromalo** [comment]
I'm getting same "Expecting form-data encoding but got normal encoding" error message when trying to restore backups from different sources (local, FTP or S3) and everything works fine if I change theme.

**Comment by qooob** [comment]
Those forms have enctype set, with `get` method, which is wrong, I think. changing it to `post` should work.

With the next patch, I'll make sure that all of those forms will always be submitted using `post` method.

**Comment by qooob** [comment]
Actually, for the restore page it's not the reason I mentioned above.

**Comment by qooob** [comment]
Both of the issues are going to be fixed on the next commit.

I'm surprised that it's actually possible to fix the issue with progressive output and `multipart/form-data`.

**Comment by qooob** [comment]
It's fixed in latest git version.

Thank you for reporting, appreciate that a lot.
