### ISSUE TITLE
Original File Manager ?

### ISSUE THREAD

**Issue by ochbob** [qooob/authentic-theme#843]
Hello,

i don't understand why i can't have the original File Manager in the webmin page like this:

https://img11.hostingpics.net/pics/735022Capture.jpg

I have only Filemin File manager and Filemin Updater, and when i launch Filemin File manager it open another pager with this interface:

https://img11.hostingpics.net/pics/660985Capture1.jpg

What should i do to have the first filemin manager ? I hate the second one :(

regards

**Comment by qooob** [comment]
You could simply reinstall Webmin via cli. Or you could go to Webmin Configuration/Modules and Install from Standard modules default Filemin package.

**Comment by ochbob** [comment]
Works great !

I reinstall default Filemin package from Standard modules.

Thanks.
