### ISSUE TITLE
File Manager: Character display and opening folder not working properly

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#845]
I have two issues with the File Manager:

1) It is not able to display special characters like ö ű é á ő etc.(part of the Hungarian alphabet)
- consequently when I try to open a folder it fails and show an error that "no such file or directory"
- I have the same issue if I want to rename or delete etc.

2) In this folder  Picture I have 100+ folders and few files but only 11 folder is shown the rest does not. 
- The only way to access these if I open one folder that has no special character and I open the folder dropdown in the path bar (at the top left side of the windows)

![image](https://user-images.githubusercontent.com/32517724/31184246-1e697cf4-a929-11e7-88dd-06f1b44fc443.png)

I have been using the latest chrome

**Comment by qooob** [comment]
You need to set IT FOR chartset in Webmin Configuration or Change Language and Theme module.

**Comment by Abasz** [comment]
Hi, Thanks, although changing language (or changing to any utf-8 char set) did not solve the problem but this issue persist under other themes as well so this is not a Theme issue sorry for the assutpiton :) I just have not noticed this prior to the update to 19.00.

Nevertheless, the difference between e.g. authentic and grey framed theme is that in the latter I am able to open these folders. Also I can brows through the pages (i.e. even though i get an error - HTTP/1.0 500 Perl execution failed Server: MiniServ/1.850 Content-type: text/html; Charset=iso-8859-1 Connection: close - the folders are loaded) and all folders are loaded.

**Comment by swelljoe** [comment]
Can you make an archive of a couple of example files that have this problem and share it with us, so we can reproduce the problem?

**Comment by Abasz** [comment]
Sure:

https://drive.google.com/open?id=0B-yPy8SuM09aTy1vLUVSc0tuNlE

Also I attached the language settings below:

![image](https://user-images.githubusercontent.com/32517724/31219408-7d447384-a9bd-11e7-90e3-d6eca035905f.png)

**Comment by qooob** [comment]
Hi,

I have checked your archive. This is what I get. I don't anything but local issue:

[Video-screencast](https://rostovtsev.ru/pub/src/authentic/19.00/file-manager_unicode_chars_845.webm)

Check if you really have encoding set to UTF8.

Open browser's console and run 

```
dataServer('charset')
```

Check that `Change Language and Theme` doesn't override global settings.

Check that your browser's encoding is set to automatic or Unicode.

**Comment by Abasz** [comment]
Hi! 

The issue is related to character encoding that is sure. I also did extensive testing today and you are right this is not Theme related. It turns out that in the recent update of Chrome automatic character ecoding was introduced and the option to set it for each page was removed. Now if i changed encoding with an extention to iso-8859-2 the characters are displayed correctly. 

Although, dicrectories with ű and ő do no show up. Nevertheless, something needs to be tweak on my side.

thanks for the help

**Comment by qooob** [comment]
I don't think you need any other encoding but Unicode.

Try automatic in your browser and check for:

![screenshot from 2017-10-08 19-37-50](https://user-images.githubusercontent.com/4426533/31318798-53c16aa8-ac60-11e7-9211-045fa1030cf3.png)

**Comment by Abasz** [comment]
I finally found a solution:

This issue was related to my proxypass settings in apache (and the error message I found was "/extensions/file-manager/list.cgi : Perl execution failed : Wide character in syswrite at /usr/share/webmin/miniserv.pl line 3111.". And it turns out that it has nothing to do with the webmin, filemin, or theme settings 

I turns out proxypass needed to be set up with ssl (SSLProxyEngine on, adding the right cert in apache config file etc) and sholud have been referred to https://localhost:10000 instead of http://localhost:10000

I just post this here to help anyone who potentially has similar issue or the same issue.
