### ISSUE TITLE
Theme: Produce user-friendly message in case server can't be reached

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#846]
I shutdown one of my computers running Webmin 1.850 but i did it from a terminal window. So now i see this green square with a spinning arrow and it seems to never stops. Shouldn't there be some kind of timeout and a message that told me that the server is not reachable?

I'm running Authentic Theme 19.00-git-201710041248 in Firefox 56.

**Comment by qooob** [comment]
It would be user friendly, sounds like an enhancement.

**Comment by qooob** [comment]
I've added this functionality.

Here is example message:

![screenshot from 2017-11-15 14-33-53](https://user-images.githubusercontent.com/4426533/32834136-82d1d89e-ca12-11e7-88a2-5f64bcb5a5c2.png)


But that's not all. I'm in the process of adding pop-up authentication screen to let user authenticate without actually going back to login screen.

https://github.com/qooob/authentic-theme/issues/892

**Comment by swelljoe** [comment]
The English in the first suggestion isn't quite right.

Something like "Check if the server is running".

Also, the message about "the proxy and the firewall" will definitely confuse someone. I guarantee we'll get a ticket from someone saying, "But I don't have a proxy!" Maybe just as ", if any" to the end of that one.

**Comment by qooob** [comment]
I will drop the last and the first one been changed already to "Check server status".

If you think latter is still not good, let me know.

**Comment by Sopor-** [comment]
@qooob is it possible to add a retry/reload/try again button to the `connection error` dialog?

**Comment by qooob** [comment]
Yes, in automated mode with, using ticking timeout, would be better than a button, right?

**Comment by Sopor-** [comment]
In that case both.
I was waiting for the server to start so i have to close the dialog, press the Dashboard button, the dialog popped up again, close the dialog, press Dashboard again...
If you only add a timeout i can't force it :(

**Comment by qooob** [comment]
It's been fixed.

https://github.com/qooob/authentic-theme/commit/51127a1606040e827cb9f0b2c0e34077b8bea754

Give it a try. Go to console and run `/etc/webmin/stop` ... then after a while, run `/etc/webmin/start`.

Example in [video-screencast](https://rostovtsev.ru/pub/src/authentic/19.05/connection_re-established_dialog.webm) of how it works.
