### ISSUE TITLE
Tab Function Error on CRON Edit Job

### ISSUE THREAD

**Issue by jbrice** [qooob/authentic-theme#847]
> Please make sure that you have latest theme (19.00) and Webmin (1.852) versions installed.  

Check,

> Provide the following information:
* What is your server-side OS and its version? Ubuntu Server 16.4.02
* What is your client-side OS, browser and its versions? Linux Mint 18.2 /Firefox 56.0
* What are the steps to reproduce the issue?
1 Navigate to webmin > Scheduled Cron Jobs.
2 Click on a CRON job to open "Edit Cron Job" page
3 Click on "Run Now" button

The Cron job will be cloned, not executed. :(( 
(May be an off-by-one error affecting other buttons on this page - and maybe other pages affected as I have seen other buttons misbehaving, but could not easily or safely reproduce.)
Changing the theme from Authentic to V.min Frame Theme and the above WAD.
Deleted, re-installed and reselected Authentic theme and fault returned.

**Comment by 7starsone** [comment]
and another...
before this major update if you cloned a job, the next page was to directly edit the cloned job...now it adds the new cronjob to the list but you have to click again to edit it...

**Comment by qooob** [comment]
Yes, thank you for reporting. It's been fixed already on Webmin side yesterday.

**Comment by jbrice** [comment]
Great response as usual - this one in negative time. ;-) Thanks!

**Comment by swelljoe** [comment]
The patch for that fix is here, if you want to apply it in the meantime: https://github.com/webmin/webmin/pull/646/commits/94a619ffb56a2712af0c0179bdec56d6a1136354

**Comment by swelljoe** [comment]
Also, these are great issues to report! We're confident there's a ton of these little problems with the HTML in Webmin we just don't know where they all are and there's not an easy way to automate finding them.

**Comment by jbrice** [comment]
Have now updated using "Including patched versions", which installed  19.00-git-201710122135. Am still seeing this malfunction. (Yes, browser cache has been cleared.)

**Comment by qooob** [comment]
You need Webmin patch as well https://github.com/webmin/webmin/commit/94a619ffb56a2712af0c0179bdec56d6a1136354

**Comment by jbrice** [comment]
Thanks - I read posts above too quickly.
