### ISSUE TITLE
Usermin starts with empty list of modules

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#849]
I tested AT 19 with usermin and was thinking its broken becaue no usermin modules are shown:

![grafik](https://user-images.githubusercontent.com/4593242/31315101-34994618-ac11-11e7-8b23-24cc65cdfc38.png)

After reinstalletion and several other tests I recognized it was only at startup. After klicking on Usermin the modules are shown:
![grafik](https://user-images.githubusercontent.com/4593242/31315109-77e1c9b8-ac11-11e7-9824-417d3e1121d4.png)

Can you change this please?
(as always proxy setup)

**Comment by qooob** [comment]
Yes, should be fixed with 19.00-patch5.

Please update.

**Comment by gnadelwartz** [comment]
great!
