### ISSUE TITLE
Undefined subroutine &main::parse_virtual_server_access_level

### ISSUE THREAD

**Issue by gtsoulou** [qooob/authentic-theme#85]
Error - Perl execution failed

Undefined subroutine &main::parse_virtual_server_access_level called at /usr/libexec/webmin/authentic-theme-master/index.cgi line 89.

**Comment by qooob** [comment]
How did you install the theme? Which OS you're on? Did you restart Webmin?

**Comment by gtsoulou** [comment]
1. Unzip in /usr/libexec/webmin, because from webmin installer said ": Not a valid module file : tar: This does not look like a tar archive tar"
2. Centos
3. Yes, I restarted

**Comment by qooob** [comment]
Unziped tar.gz or zip from GitHub?

**Comment by qooob** [comment]
Try tar.gz from the readme page, lower there, not GitHub zip. Probably issue in the repo.

**Comment by gtsoulou** [comment]
Yes, i'm using the  GitHub zip. I'll try the tar.gz now...

**Comment by qooob** [comment]
Ahh. OK. Got it. Rename authentic-theme-master to authentic-theme.

**Comment by gtsoulou** [comment]
Yes, that's it!
Now I can login to webmin but it take too long to load the dashboard...

**Comment by qooob** [comment]
Should not be the case really..

**Comment by qooob** [comment]
I will add a fix for those who installs the theme from the repo. Thanks for the idea and your comments.
