### ISSUE TITLE
Theme v19 dose not load defaults from available features

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#850]
Webmin (1.852) versions installed on Debian
Theme  19.00-git-201710041248

With new theme defaults from 
System Settings -> Account Plans ->  Allowed virtual server features -> Default available features
are ignored upon new virtual server creating. All futures always enabled

**Comment by qooob** [comment]
What does it do in old Virtualmin Framed Theme?

**Comment by Romich777** [comment]
Futures unchecked in Default available features was also unchecked in Enabled features in Create Virtual Server dialog 
![screenshot from 2017-10-09 11-22-34](https://user-images.githubusercontent.com/14110152/31329732-2f30ea54-ace4-11e7-9824-3aa73ddfe0c4.png)

v19
![screenshot from 2017-10-09 11-19-43](https://user-images.githubusercontent.com/14110152/31330172-ea24fbf6-ace5-11e7-8127-855e151acfc2.png)

v18
![screenshot from 2017-10-09 11-31-05](https://user-images.githubusercontent.com/14110152/31330190-fc4b7ff8-ace5-11e7-87bf-4c42f2b4f401.png)

**Comment by qooob** [comment]
This is a great thing to fix. 

I have found the way to make old scripts supplied from modules work as they are.

There were other bug reports from other sources. It will just work after next commit.

Thanks a lot.

**Comment by qooob** [comment]
Get latest _git_ version to make it work.
