### ISSUE TITLE
Servers list in left menu does not updating after creation of new server

### ISSUE THREAD

**Issue by Romich777** [qooob/authentic-theme#851]
Webmin (1.852) versions installed on Debian
Theme  19.00-git-201710041248

After creation of new virtual server it cannot be find in servers drop-down list until page not been reloaded.

**Comment by qooob** [comment]
That is something that worked. What is your Virtualmin version?

**Comment by Romich777** [comment]
Virtualmin 6.01

**Comment by qooob** [comment]
Oh, my. Yes, it went broken after progressive output was added. It will be fixed on the next commit.

Thank you very much for reporting.

**Comment by qooob** [comment]
Get latest _git_ version to make it work.

**Comment by Romich777** [comment]
Thanks!
It works fine
