### ISSUE TITLE
wasted space in content pane

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#852]
the conten pane has much unsed spcae on top and left/rigth border:
![grafik](https://user-images.githubusercontent.com/4593242/31336766-a2ada094-acf8-11e7-8c8b-562ac35a74d3.png)

![grafik](https://user-images.githubusercontent.com/4593242/31336803-d3324eb8-acf8-11e7-832a-b14140267489.png)

so i.e. not all content in the firewall module ist listed, I have to scroll let/rigth to see it.
How can we widen the content pane to us as much as possible availible space?

**Comment by qooob** [comment]
What is your screen resolution?

**Comment by qooob** [comment]
Check it out now :wink:

**Comment by gnadelwartz** [comment]
much better now.
on tablet 1920, on desktop 1280 (window size)
