### ISSUE TITLE
19.00-git-201710092120 is showing update notice from 18.40-18.49

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#854]
When i press the i button
![image](https://user-images.githubusercontent.com/5789283/31416496-de656518-ae29-11e7-9d60-affa9d2d6f3a.png)
it will show this information
![image](https://user-images.githubusercontent.com/5789283/31416516-fb1c106c-ae29-11e7-9f77-525e746c05f8.png)

The only thing i did was to update to Webmin 1.860.

**Comment by qooob** [comment]
That's not a problem. When Webmin was installed it kept some files from previous install, while shipping old version of the theme.

We'll ship the new one as soon as it's fully tested. You can go to settings and upgrade to the latest 19.00 version.

**Comment by Sopor-** [comment]
I also need to do two refresh to get your theme visible after the Webmin update...

**Comment by qooob** [comment]
It's browser's cache. No issue here.
