### ISSUE TITLE
Return to package list

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#856]
* What is your server-side OS and its version? CentOS Linux 7.4.1708
* What is your client-side OS, browser and its versions? Windows 10pro 64, Chrome 61.0.3163.100
* What are the steps to reproduce the issue?
When package updates are available, go to update, then click on **Return to package list**
If you don't recollect the system infos, under the "System Information" tab, there's still the tab (now I don't remember its title) where you see the package as not already updated, with a green button.
So, you need to recollect the infos to hide that tab.

Thanks

**Comment by qooob** [comment]
Info is recollected every 5 minutes. I will trigger force-update after packages been installed.

Nice idea, thanks.

**Comment by qooob** [comment]
Added with the latest commit.
