### ISSUE TITLE
module list not shown after "refresh modules"

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#859]
when I click on "refresh modules" I got the the sucess mesage in the rigth panel, but the module list on the left stays empty with a forvever circling loading indicatior. The only posibility is to click on dashboard, but even dashbord is shown, the list stays empty

![grafik](https://user-images.githubusercontent.com/4593242/31584989-d09b572e-b1b9-11e7-9e59-a02404c220d3.png)

If I manually go to enter the webmin base URL e.g. https://mail.rrr.de/webmin/ the module list is correctly displayed. 

as always proxy setup

**Comment by qooob** [comment]
What version of the theme is installed?

**Comment by qooob** [comment]
Yes, I think I also reproduced it on 19 branch.

**Comment by gnadelwartz** [comment]
Ive updated to 19.00-git-201710122135 via wbeinterface and the issue stays.

**Comment by qooob** [comment]
Yes, because version `19.00-git-201710122135` stays the same and makes old files from cache loading. Force reload the cache.

It's fixed, I bet.

**Comment by gnadelwartz** [comment]
ok, i understand.  what about modifying the version number while updating to the date of the latest commit instead of doing manually every 2-3 days? 

my update script for webmin does it this way, because  jamie raise the version number very rarely

**Comment by qooob** [comment]
Maybe. But in this case any time I push an update anyone having `Notify about including patched versions` will see an update notice.

I think I will just make sure that git users will get their cache updated differently.

Good idea.

**Comment by qooob** [comment]
Cache issue is fixed here: https://github.com/qooob/authentic-theme/commit/a52f90a101f42fce8e17a21637243fa2974ab48e

**Comment by Tantawi** [comment]
Thanks @qooob this fixed my login standing issue from the beta days! much appreciated :)

**Comment by qooob** [comment]
You're welcome. I just made 19.01 release 5 minutes ago. :wink: Enjoy.
