### ISSUE TITLE
CSS: system info update message is off screen in Chrome and Pie Charts are not resizing well

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#860]
I noticed that the system info update message goes off screen in case browser is resized (this issue persist in mobile devices as well.

screen shot is below:
![image](https://user-images.githubusercontent.com/32517724/31587020-28cc005e-b1da-11e7-81db-18b07726f62e.png)

EDIT:

issue seems to be two folded 
1) with the margin-left: -270 under @media (max-width: 960px) .messenger.messenger-fixed.messenger-on-top, ul.messenger.messenger-fixed.messenger-on-bottom ; (deleting this puts the message on the screen in almost in the middle when width is below 960px) 

and 
2) there is a left: 58% under ul.messenger.messenger-fixed.messenger-on-top, ul.messenger.messenger-fixed.messenger-on-bottom; (deleting this 58% would set the message to 50% that looks better with screen wider than 960px; actually in case the screen is between 960 and 1020px the messages is more moved to the right. removing the 58% ensures that it is more in the middle)

Also the pie charts are not resizing well. I think this is due to their bootstrap col sizing. Changing them to col-md from col-sm works good in Chrome.

**Comment by qooob** [comment]
Fixed. https://github.com/qooob/authentic-theme/commit/cc725506d48dd2c94ea1b9102b2469381653e6e5
