### ISSUE TITLE
Theme: Reloading page makes navigation menu disappear or/and display security warning

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#861]
I don't know if this has something to do with Webmin or the authentic-theme or both but it has started to show up a lot more than before the update of authentic-theme and Webmin.
The URL didn't look like this before the update`https://192.168.0.12:10000/sysinfo.cgi?xnavigation=1`.
So when i do a refresh this security warning popup and to fix it i need to change the URL to `https://192.168.0.12:10000`.
But as soon as i'm back at the dashboard I then see that the URL `https://192.168.0.12:10000/sysinfo.cgi?xnavigation=1` is back again and if i do a refresh i get the security warning to appear again :(

![image](https://user-images.githubusercontent.com/5789283/31638067-e6e924ac-b2d1-11e7-83c4-99855477bbed.png)

I don't want to change the `referers_none=1` to 0. That sounds like a dirty fix for this issue.

**Comment by qooob** [comment]
Yes, in order to make it work correctly you would need latest patch for Webmin https://github.com/webmin/webmin/pull/654

**Comment by qooob** [comment]
In short and for the future reference - you need to wait until next Webmin/Usermin release or patch `web-lib-funcs.pl` file manually by adding above:


```Comment
# Check the Referer: header for nasty redirects
```

The following:

```Perl
# Check for trigger URL to simply redirect to root: required for Authentic Theme 19.00+
if ($ENV{'REQUEST_URI'} =~ /xnavigation=1/) {
	redirect("/");
}	
```

From [/web-lib-funcs.pl#L4690-L4693](https://github.com/qooob/webmin/blob/68029cf0e872eded1e294e322c98910bd3dd12f7/web-lib-funcs.pl#L4690-L4693)

**Comment by Sopor-** [comment]
This was a new one :)

![image](https://user-images.githubusercontent.com/5789283/32357938-883eae54-c041-11e7-99aa-3ea5554e2a38.png)

I hope there will be a new Webmin release soon...

**Comment by qooob** [comment]
Meanwhile, just patch it manually. It's the matter of few minutes.

**Comment by Sopor-** [comment]
And when i have made the patch on all of my 4 Webmin, a new Webmin is out and it was unnecessary work ...

**Comment by Sopor-** [comment]
I got this message when i was going to update Webmin

![image](https://user-images.githubusercontent.com/5789283/33731638-0887ffcc-db84-11e7-9d70-cb59a78e1533.png)
Is this because the manually changes i did to `web-lib-funcs.pl` ?

**Comment by qooob** [comment]
I honestly have no clue what that script is doing? Never saw it before.
