### ISSUE TITLE
AWstats Configuration link is bonkers

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#862]
Clicking on "Logs and Reports->AWStats Configuration" causes the "System Settings->Virtualmin Configuration" menu to be opened/highlighted. I believe there's some sort of regex checking for "config.cgi" and it's not smart enough to notice that "virtualmin-awstats/config.cgi" is not the same as "config.cgi".

**Comment by qooob** [comment]
Yes, it's confirmed. I also noticed that clicking _AWstats Report_ opens over existing page.

What I could do? I could make such links open in the new tab.

It's also should be possible to edit Perl part and make sure that the content that you want to be displayed is wrapped in:

```HTML
<div data-dcontainer="1">
   ...
</div>
```

**Comment by qooob** [comment]
It's fixed. Links opened in new tab. All works cool.
