### ISSUE TITLE
Side navigation bar: upon page refresh the left navbar disapears

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#863]
When refreshing the page in the browser the left side bar disappears. 

![image](https://user-images.githubusercontent.com/32517724/31651240-2f04bc08-b31b-11e7-8fbf-4a7c6e474910.png)

I am behind proxypass (latest webmin and theme). Accessing webmin via https://IP_address/webmin

**Comment by qooob** [comment]
Duplicate: 
https://github.com/qooob/authentic-theme/issues/861

**Comment by Abasz** [comment]
Sorry, i did not realize that the patch I previously applied (and made this working) was yet to be implemented in webmin (and when I updated webmin the patch disappeared).
