### ISSUE TITLE
Referer failure

### ISSUE THREAD

**Issue by alexnas77** [qooob/authentic-theme#864]
Greetings.
I am using Debian 7 and CentOS 6 and CentOS 7.
I am also using Windows 7 and latest Google Chrome.

You made redirect from main page of Webmin to current module.
But if I refresh page Webmin shows me error page like this:

"Внимание! Webmin определил, что ссылка на программу https://local.pizzasushiwok.ru:10000/sysinfo.cgi?xnavigation=1 была произведена с неизвестного URL, который находится вне сервера Webmin. Это может быть попыткой обмануть ваш сервер с целью запуска опасной команды..
Make sure your browser is configured to send referrer information so that it can be verified by Webmin.

Или же, вы можете настроить Webmin для разрешения ссылок с неизвестными referers:

Войдите как root, и отредактируйте файл </etc/webmin/config.
Найдите строку referers_none=1 и измените её на referers_none=0.
Сохраните файл."

This very inconvenient.

It does not depends of browser or OS on server and client.
This is a major problem.

Thank you for solving this.

And when I open Webmin It may show me frame whithout left menu.

**Comment by qooob** [comment]
Привет! :wink: 

This is related to [#861](https://github.com/qooob/authentic-theme/issues/861) and the dupe of.

You would need to wait until the next version of Webmin or patch `web-lib-funcs.pl` file manually by adding above:


```Comment
# Check the Referer: header for nasty redirects
```

The following:

```Perl
# Check for trigger URL to simply redirect to root: required for Authentic Theme 19.00+
if ($ENV{'REQUEST_URI'} =~ /xnavigation=1/) {
	redirect("/");
}	
```

From [/web-lib-funcs.pl#L4690-L4693](https://github.com/qooob/webmin/blob/68029cf0e872eded1e294e322c98910bd3dd12f7/web-lib-funcs.pl#L4690-L4693)
