### ISSUE TITLE
FreeBSD CPU Graph is showing incorrect

### ISSUE THREAD

**Issue by jwhulette** [qooob/authentic-theme#865]
Before posting an issue, please search through closed/opened issues to make sure that the answer to your questions hasn't been answered already.

Please make sure that you have latest theme (19.01) and Webmin (1.860) versions installed.

Provide the following information:
* What is your server-side OS and its version? FreeBSD 11
* What is your client-side OS, browser and its versions? Mac OS 10.12.6 Chrome Version 62.0.3202.62
* What are the steps to reproduce the issue? Load system info page

![webmin_1_860_on_server2_ckadvertising_com__freebsd_11_0_](https://user-images.githubusercontent.com/4930051/31778666-3da2effa-b4bf-11e7-99da-e2549a4aac44.png)

**Comment by qooob** [comment]
Can you please report it to Webmin repo as it's not the theme issue.

https://github.com/webmin/webmin
