### ISSUE TITLE
Checkboxes gets selected when i press on the line

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#866]
When for example open the email every item i open will select the checkbox before it will open. If i select it and press it it will deselect it. It shouldn't change the checkbox when i press the line. Only if i press inside the checkmark itself (as i do in the second animation on the second line).
It seems to be the same in the File manager but when i press on a file it won't open it, only select it. To select several files/folders you should only be able to do that by pressing inside the chackbox.

I'm running FF 56 with Authentic-theme 19.01

Selecting:
![authentic_theme_checkmark_01](https://user-images.githubusercontent.com/5789283/31865733-cf4ca6d8-b773-11e7-8213-1d2fd30faad6.gif)

Selecting even if another is already selected:
![authentic_theme_checkmark_02](https://user-images.githubusercontent.com/5789283/31865736-d53fb526-b773-11e7-991f-1412b7ed097f.gif)

Unselecting an already selected:
![authentic_theme_checkmark_03](https://user-images.githubusercontent.com/5789283/31865738-da39024e-b773-11e7-8aa2-e7ecc8d615fc.gif)

**Comment by qooob** [comment]
I noticed it before and I agree. 

I will fix it.

Thanks for reporting.

**Comment by qooob** [comment]
Fixed.
