### ISSUE TITLE
info-container cpu-core temperature colouring not working

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#867]
Hi,

I noticed that on the right info bar the cpu temperatures are not colered properly (I discovered this because I wanted to add Fan speed and System temp to the Cpu temp info). 

I think the above is do to the following:
In the bundle.js the bg-info, bg-success has a class of --bg-info and --bg-success so these classes are not recognised. Furthermore, in the CSS bg-info and bg-success needs an !important tag otherwise the general background overrides the colouring.

I do not know whether this is intentional or not (although I remember that in earlier versions of the theme cpu and hdd temp were only visible on the info-container if these were overheating).

![image](https://user-images.githubusercontent.com/32517724/31880039-a158e1b2-b7df-11e7-8ac9-bb97fb11ffea.png)

**Comment by qooob** [comment]
I'm not sure how to add CPU fan to data output?

Yes, there is a bug. Thanks a lot for reporting. Fixing now.

**Comment by Abasz** [comment]
do not worry about CPU fan staff :) (actually webmin system-status-lib.pl needed to be edited for that)

**Comment by qooob** [comment]
Can you give me the RPM speed for 

low, normal, warning and danger?

**Comment by Abasz** [comment]
That depends a lot on the configuration.

For my setting low is below 1600 normal is 1600 to 2100, warning is 2100-2800; danger is above 2800

**Comment by qooob** [comment]
I made a patch for fan speed as well. 

You can also now force to show sensors data in Side Slider.

Please give it a try.

```Changelog
By default, sensor information is hidden in Side Slider, unless warning or danger levels are reached.
Mentioned behaviour can be bypassed and forced to be shown constantly, by adding variables to Theme Extensions/JavaScript:

`config_custom_force_display_cpu_sensors` and/or `config_custom_force_display_drive_sensors`.

```

**Comment by Abasz** [comment]
Tested and it almost works:

For unknown reasons the hdd temp is not loaded properly (only every second span is loaded)

![image](https://user-images.githubusercontent.com/32517724/31887360-54234e5a-b7f8-11e7-9adc-1d158190cb2a.png)

**Comment by qooob** [comment]
What it's shown on System Information page? Can you make screenshot out of it?

**Comment by Abasz** [comment]
![image](https://user-images.githubusercontent.com/32517724/31887631-5b8e2baa-b7f9-11e7-87c4-851f65d83697.png)

**Comment by Abasz** [comment]
One additional though: Would it make sense to implement the same colouring on the main dashboard as on the right info container?

**Comment by qooob** [comment]
Yes, makes senses.
What it's shown on System Information page? Can you make screenshot out of it?

**Comment by qooob** [comment]
Looking at your screenshot I have no idea yet why drive temperature not shown in the Right Slider.

**Comment by Abasz** [comment]
Ok I think I konw where the problem comes from:

When you assemble the spans from the main dash board data I think the &nbsp; is compied instead of the temp data:

```
<span class="badge-custom badge-drivestatus" data-stats="drive" style="margin-right:3px; margin-bottom: 3px">sda: 38°C </span>&nbsp;
<span class="badge-custom badge-drivestatus" data-stats="drive" style="margin-right:3px; margin-bottom: 3px">sdb: 37°C </span>&nbsp;
```

`<span class="badge-custom badge-drivestatus" data-stats="drive" style="margin-right:3px; margin-bottom: 3px">&nbsp;</span>`

This would explain why on the screen shot 37 degrees is shown on as the temp for the 3rd hdd (that is actually the temp for the second)

**Comment by Abasz** [comment]
Hi, I think I found the  solution (and the bug) for the incorrect render of the HDD temp:

In boundle js there is a line:
```

if ("hdd_temperature" == e) {
                            var _ = 0;
                            $.each($(i), function....
```
I was suspecting that the iteration does not go through correctly. So in case we specify the selector as below, the spans are rendered correctly:

` $.each($(".badge-drivestatus:not(.badge-cpustatus)"), function(e, t) {`

by the way I was wondering whether the uniminify js and css is available somewhere (or it is not made public on purpose :))

**Comment by qooob** [comment]
Hi,

How about latest fix https://github.com/qooob/authentic-theme/commit/9bdcff1e87856cd2d04eb637ace65c454f93873d, give it a try please. Does it work perfect now?

**Comment by Abasz** [comment]
Hi,
Thanks for the update, 

I difined the RPM limit in themeextention (really nice touch!)

The colouring logic on the main page is not 100% working on the RPM (the other parts I think working):
![image](https://user-images.githubusercontent.com/32517724/32043524-488a0bf2-ba3b-11e7-9fe7-dad8a359bb8d.png)

function page_sysinfo_update_temperature_labels() {
    var e = $("#system-status .badge-drivestatus");
    e.length && $.each(e, function(e, t) {
        var i = $(this).text()
          , a = parseInt(i.split(":")[1])
          , n = i.indexOf("°C") > -1
          , s = HTML.label.temperature(a, n);
        Test.string(s) && $(this).removeClass(function(e, t) {
            return (t.match(/(^|\s)bg-\S+/g) || []).join(" ")
        }).addClass(s)
    })

I think you might have missed the RPM check from the above code like you included in the information_update

In addition one small note: from a styling perspective I kind of liked the old oval forms for the temperatures:

![image](https://user-images.githubusercontent.com/32517724/32041794-b7e429c0-ba35-11e7-884b-11fef5767040.png)

But of course I can change this in theme extension for if I wan to :)

**Comment by qooob** [comment]
Okay, right.

How about now?

https://github.com/qooob/authentic-theme/commit/cf75446815da83404a202633841bef0e3b2c3fd2

**Comment by Abasz** [comment]
Seems to be working nicely! Thanks for your continuous support

**Comment by iliarostovtsev** [comment]
.. very surprising and confusing at the same time, that that you had RPM output back then .. perhaps, Jamie changed something in the past .. but there should had been no fan speed until now ..

**Comment by jcameron** [comment]
I have accepted some commits to this code a few months ago.
