### ISSUE TITLE
File Manager: Text editor refresh not working

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#869]
Recently I noticed that in case I try to refresh the opened file in the file editor (from the dropdown) it breaks. 

After that I am not able to open a file with the editor until I enter localstorage.Clear()

Below is a video I made with the error:

[ScreenCast](https://abasz-freemail.tinytake.com/sf/MjA1ODc5N182NDgxNjcw)

I am behind proxypass accessing webmin via https://IP/webmin/

**Comment by qooob** [comment]
I don't think it's the theme issue.

Try disabling ADB and other extensions.

I have it working fine, take a look at the [video-screencast](https://rostovtsev.ru/pub/src/authentic/19.01/file_manager_edit_file_working_refresh_869.webm).

-----

A note. Did you try to hit _Alt_ when the dropdown menu in editor is opened to see what happens? :smiley:

**Comment by Abasz** [comment]
This is not a big issue, I do not know the error behind. disabling ADB does not help.

I never tried before (but now I have :)) but what should happen when you press Alt? (the only change I can see is that the window layout of the editors may be change, however, if I press Alt once and I release I need to close and reopen the drop down to work again)

**Comment by qooob** [comment]
I can't reproduce your issue. You saw the video-screencast.

What do you think could cause it?

In case you're in the file editor in File Manager, when you click on the dropdown menu and it stays open, try hitting `Alt` key to see that menu content will change letting you choose to align panels differently.

**Comment by qooob** [comment]
..also try incognito mode..

**Comment by Abasz** [comment]
Hi, Alt key works as expected in this regard (i.e. I can choose to align )

I was trying to the a breakpoint debug (to find out where things go wrong) but to be honest I was not able to find the related javascript part (I fudn the ). If you could point me to the direction where the related script is I will try to find out more.

**Comment by qooob** [comment]
Do you see errors in the console?

**Comment by Abasz** [comment]
No I dont. I think this would not create a console error since text is loaded but the wrong one (part of the page Html code is loaded). So it seems that instead of text area the first lines of the html file is read into the panel

**Comment by qooob** [comment]
What is your browser and OS (server and client)?

**Comment by Abasz** [comment]
OS server: Ubuntu server 16.04
OS Client: Win10
Browser: latest chrome

**Comment by qooob** [comment]
Okay, what kind of error page is that? It's error page loaded? What does it say at the bottom of the screen?

**Comment by Abasz** [comment]
I found the problem... It is actually very funny :)

the issue is that I use a webmin user name that does not exist on my system. If I change to username to e.g. root it works.

So I can create a unix user for my current webmin username, or I can change the current webmin user name to something that does exist on the system. This may be easier than changing the code around.

**Comment by Abasz** [comment]
Or, off course the code may be changed :)

**Comment by qooob** [comment]
That's really cool. :laughing: I reproduced it.. Let's see what I should do.

**Comment by qooob** [comment]
Fixed, give it a try.

**Comment by Abasz** [comment]
Nice one, seems working correctly. Thanks
