### ISSUE TITLE
Weird issue after the last reboot updating kernel on CentOS 7

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#870]
"Please make sure that you have latest theme (19.01) and Webmin (1.860) versions installed."
No, there's the previous concept **Authentic Theme 18.49-9**

Provide the following information:
* What is your server-side OS and its version? **CentOS Linux 7.4.1708**
* What is your client-side OS, browser and its versions? **Windows 10 Pro 1703, Chrome 61.0.3163.100 64bit**
* What are the steps to reproduce the issue?
In the last few days, updated Virtualmin and Webmin to the latest version, then yesterday updated the kernel and others from the packages updates as usual. Then, after the last reboot, I see **Authentic Theme 18.49-9** and the previous behavior, instead of version 19...

why? Maybe latest Virtualmin or Webmin updates as culprits ?
Thanks

**Comment by swelljoe** [comment]
Webmin currently includes the latest stable release of Authentic, which is 18.49-9. You'll need to install the beta version again after updating Webmin. (This isn't ideal, but since the theme is distributed in the Webmin package, it gets replaced on upgrades.)

**Comment by 7starsone** [comment]
ok, thanks
