### ISSUE TITLE
Auto focus first form element when forms are present

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#871]
I've just added some JavaScript to Virtualmin Framed Theme to auto-focus the first field on a page with forms. Can you add something like the following to Authentic?

```js
$(document).ready(function() {
    $('form:first *:input[type!=hidden]:first').focus();
});
```

This is the change I made to Framed Theme to do the same thing:

https://github.com/virtualmin/virtualmin/commit/3b26acd7e7e2f6d9cad246a4a62b14ff8d5215ef

I only add the JS if there is a form on the page, but I dunno if injecting snippets of JS makes sense in Authentic; you may just want it to always be on.

This is to close out this feature request ticket at Virtualmin.com: https://www.virtualmin.com/node/53791

**Comment by qooob** [comment]
Certainly good idea. I will do it.

**Comment by qooob** [comment]
I would do something like:

```JavaScript
$('form:visible:first input:visible:first').focus()
```

**Comment by qooob** [comment]
However, it's also not good because it will focus checkboxes and radios.

Gimme.. :wink:

**Comment by qooob** [comment]
This seems the best to me at the moment:

```JavaScript
$('form:visible:first').find('input:visible:not([type="radio"]):not([type="checkbox"]), textarea:visible')[0].focus()
```

**Comment by qooob** [comment]
On the pages without those elements error will be thrown, so it's better to check for element first:

```JavaScript
var element = $('form:visible:first').find('input:visible:not([type="radio"]):not([type="checkbox"]), textarea:visible');
element.length  && element[0].focus
```

**Comment by qooob** [comment]
Besides `:not([type="submit"])` should also be added.

**Comment by qooob** [comment]
And not `readonly` and not `disabled` so here is the final one, I think it's complete now:

```JS
'input:visible:not([readonly]):not([disabled]):not([type="radio"]):not([type="checkbox"]):not([type="submit"]), textarea:visible:not([readonly]):not([disabled])'
```
