### ISSUE TITLE
Theme: Form submissions don't work on some pages in macOS/iOS

### ISSUE THREAD

**Issue by Madseason41** [qooob/authentic-theme#872]
Server-side OS ubuntu server 16.04.2. 1.860 webmin. 19.01 1023 theme
Client Side OS. MacOS whatever the latest is called, IOS 11, Safari on both and mercury on iOS
I navigate to System tab, then select boot up and shutdown, scroll to bottom, select reboot system, select reboot system on next page. 

Nothing happens. Any ideas?

**Comment by qooob** [comment]
Hi,

I confirm that it doesn't submit the form undef Safari 11 in macOS Sierra.

**Comment by Madseason41** [comment]
Are you saying its an "Apple" issue or a "Safari" issue? I have the same problem with the Mercury browser on iOS. I will try chrome on IOS later today.

**Comment by qooob** [comment]
It's Safari browser. Chrome in macOS works great.

**Comment by Madseason41** [comment]
I went ahead and tried chrome in iOS. It doesn't work.

**Comment by qooob** [comment]
iOS? Chrome browser doesn't work identically on mobile, non-Android devices.

I've made a patch.. Testing now. Will be appreciate if you will be able to test it.

I'll let you know in around 10-15 minutes.

**Comment by Madseason41** [comment]
Yeah I have the same problem on both macOS and iOS (iOS doesn't work with Safari, Mercury, and Chrome). I will only be able to test the patch from mobile (iOS) for now. It will be about 12 hours before I can test on macOS.

Let me know

**Comment by qooob** [comment]
Sounds, great.

It'll just work.

That was a global problem.

Thanks for reporting.

Please give it a try, by force-reinstalling the theme.

**Comment by qooob** [comment]
Looking forward for your test results.

**Comment by Madseason41** [comment]
It worked on iOS with Mercury Browser.

Will test more thoroughly this evening. Thanks!

**Comment by qooob** [comment]
Sure, 

Please let me know if it works fine.

**Comment by gnadelwartz** [comment]
IMHO: iOS Apple does only allow his rendering engine (webkit?), so all browsers has to use it, e.g.

https://arstechnica.com/gadgets/2016/01/new-chrome-for-ios-is-finally-as-fast-and-stable-as-safari/

**Comment by qooob** [comment]
I have made a patch. It's just  working.

Thanks, Kay.

**Comment by Madseason41** [comment]
Seems like I’m having another issue now. I can’t even get to the reboot selection. Once I select system/ boot up and shutdown. Nothing happens. Tried only on iOS Safari, Chrome, Mercury

**Comment by qooob** [comment]
Just try to clear browser cache. It should work.

**Comment by qooob** [comment]
This is endlessly frustrating how Safari works. I could reproduce the `issue` but only every second or third time, I can't load the content page while clicking into navigation menu. Sometimes the same page gets loaded.

The server response is just empty.

I have no idea why this is happening. It shouldn't be. It requires further analysis.

**Comment by qooob** [comment]
At the moment any link without any particular reason can go broken, by when clicking on it - does nothing. For example, reloading a page or clicking somewhere else and then returning to the same page makes previously non-working link work. 😕 

Looking at the headers in Safari here what I have found out.

Non-working:

```
curl 'https://192.168.1.215:10000/fail2ban/edit_config.cgi' \
-XPOST \
-H 'Referer: https://192.168.1.215:10000/fail2ban/edit_config.cgi?xnavigation=1' \
-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
-H 'Origin: https://192.168.1.215:10000' \
-H 'Pragma: no-cache' \
-H 'Accept: text/html, */*; q=0.01' \
-H 'Cache-Control: no-cache' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38' \
-H 'X-PJAX: true' \
-H 'X-PJAX-Container: [data-dcontainer]' \
-H 'X-Requested-With: XMLHttpRequest' \
--data '_pjax=%5Bdata-dcontainer%5D'
```

Working (for the same link)
```
curl 'https://192.168.1.215:10000/fail2ban/edit_manual.cgi' \
-XPOST \
-H 'Referer: https://192.168.1.215:10000/fail2ban/edit_config.cgi?xnavigation=1' \
-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
-H 'Origin: https://192.168.1.215:10000' \
-H 'Host: 192.168.1.215:10000' \
-H 'Pragma: no-cache' \
-H 'Accept: text/html, */*; q=0.01' \
-H 'Cache-Control: no-cache' \
-H 'Accept-Language: en-us' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Connection: keep-alive' \
-H 'Cookie: file-manager-response=; file-manager-response_count=; sid=c1061523ef647daeb74d710efe08a27d; redirect=1; testing=1' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38' \
-H 'Content-Length: 27' \
-H 'X-PJAX: true' \
-H 'X-PJAX-Container: [data-dcontainer]' \
-H 'X-Requested-With: XMLHttpRequest' \
--data '_pjax=%5Bdata-dcontainer%5D'
```

I didn't find the reason yet what makes requests different. I don't see how it could be the theme issue. I will be looking though but I would like others to share some thoughts over it.

**Comment by qooob** [comment]
There are issues with Safari using AJAX but solution is not straight forward.
[JQuery Ajax call often not working on Safari 6](https://stackoverflow.com/questions/18778814/jquery-ajax-call-often-not-working-on-safari-6). 

Will see what I can do about it.

The problem is that the same link both _works_ and _doesn't not work_ based on when you click it.

I wish it would be the theme issue that I could properly address.

I can confirm that this doesn't happen in Chrome on MacOS, only in Safari.

I'm installing update for MacOS with Safari 11.0.1 and Security Update 2017-001 10.12.6. Let's see what happens afterwards.

**Comment by qooob** [comment]
Out of curiosity do you have Xcode installed?

**Comment by qooob** [comment]
Installing latest 11.0.1 doesn't really help.

Upgrading to the latest Xcode 9.1 ..

**Comment by qooob** [comment]
You need to click around the navigation menu. Sometimes, out of no reason, links don't react on click (not loading content). It's also happening if clicking around the module content, not just navigation.

**Comment by fdmgit** [comment]
Currently everything works smoothly. No issues seen at all.

**Comment by qooob** [comment]
@fdmgit Good to know. Do you have Xcode installed? Thank you for giving it a try.

**Comment by fdmgit** [comment]
Yes, Xcode version 8.2.1 is installed

**Comment by qooob** [comment]
Fixed.

**Comment by qooob** [comment]
@Madseason41 Give it a try and tell me if it works fine for you?

@fdmgit I'd be also interested to know if it still works on prior versions after update?

**Comment by Madseason41** [comment]
No change for me. doesn't work on iOS (chrome, safari, or mercury browsers).

**Comment by qooob** [comment]
Mobile doesn't work?

Could anyone else please try it?

How about desktop then?

**Comment by qooob** [comment]
That's odd. I've just tried my iPhone X Xcode emulator. Everything works just fine in Safari iOS.

Could you make sure that you have pulled latest changes and cleared the cache?

**Comment by fdmgit** [comment]
@qooob 

Desktop:
I've pulled latest changes and cleared the cache. 
No issues seen so far.

**Comment by fdmgit** [comment]
@qooob 

iOS:
Just tested it on Chrome for iOS. It works, no issues found.

I'm using iOS V10.3.3

**Comment by qooob** [comment]
@fdmgit Thanks.

**Comment by Madseason41** [comment]
I am on iOS 11.1. Chrome 62.3202.70.

Login to webmin works and load fine. On the left bar I click system, boot up and shutdown and the progress bar goes from far left to far right but the next page never loads. I cleared cache and tried on both an iPad and iPhone and neither work. It works fine on chrome with macos.

**Comment by qooob** [comment]
I suppose iPhone X runs 11 version of iOS in Xcode. Then I will have to find someone with actual device.

Are you sure that you have updated to the latest version. Could you force update one more time?

**Comment by Madseason41** [comment]
So I was updating from my iOS device and Mac from safari. That part “seemed” to work. I took a step back and forced an update from my Mac on chrome and now all seems to work.
Thanks for the help.
