### ISSUE TITLE
Theme: Logo for login page

### ISSUE THREAD

**Issue by webotop** [qooob/authentic-theme#873]
Seems my login page design change since I update to 19.01 version. Any idea?

**Comment by qooob** [comment]
How exactly does it change?

You might see the old theme's login page in case Authentic Theme is not set as global theme.

**Comment by webotop** [comment]
Hi,


Thank you for replying. 

I do have the theme set on global. I used to have the goodlogin.png design and now I do have the newlogin.png

I can compare as I have two server, one has the authentic theme version 18.49.1 and the other has the updated stable version 19.01 


Any other ideas? Cheers

**Comment by qooob** [comment]
I don't understand what you're reporting. 

I just set up logo in 18.49 and then updated to 19.01. All of the logos displayed correctly.

What is `goodlogin.png`?

**Comment by webotop** [comment]
Hi,

You should close the topic. I unistalled webmin and did a re-installation so the issue was fixed. 

TY.




Julien
