### ISSUE TITLE
File Manager not load

### ISSUE THREAD

**Issue by ivanbg** [qooob/authentic-theme#874]
Webmin version | 1.860
Usermin version | 1.720
CentOS Linux 7.4
Authentic Theme 19.01-git-201710231423
Computer: Mac OS X High Sierra

Filemin not load in Chrome 62 and Safari 11. System: Mac OS X High Sierra. See atached images.

Thanks for your work @qooob ! Great Theme!
![file_manager-2](https://user-images.githubusercontent.com/6291747/32183192-f2323700-bd98-11e7-8308-b460d9706b19.jpg)
![file_manager](https://user-images.githubusercontent.com/6291747/32183202-f610c148-bd98-11e7-809d-344d0c631802.jpg)

**Comment by qooob** [comment]
Hi,

Confirmed and fixed. It happened due to code refactoring.

Thank you for reporting.
