### ISSUE TITLE
firewall navigation - Sowing IPTable

### ISSUE THREAD

**Issue by Lexus34** [qooob/authentic-theme#875]
Operating system | CentOS Linux 7.4.1708
Webmin version | 1.860
Theme version | Authentic Theme 19.01
Firefox 56.0.2(x64)

Networking - Linux Firewall - Sowing IPTable - Select [ Packet Alteration ] and Network [ Address Translation ] Does not switch rule lists.

**Comment by qooob** [comment]
Hi,

Does it work in the old theme?

**Comment by Lexus34** [comment]
The latest working version is 18.49

**Comment by qooob** [comment]
This is due to completely broken HTML.

I will make a fix for now, just as for some other parts of the page and as well as for other modules.

I the future, we'll change server part to make sure that all of the HTML is rendered correctly at the first place.

**Comment by qooob** [comment]
It's going to 19.02 release right now.
