### ISSUE TITLE
Running processes -> ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#876]
Hello, on 19.02

I click on the number of procs (to enter the Running Processes)
then, I click on CPU...it gives a
`POST https://domain.com:10000/proc/index_cpu.cgi net::ERR_CONNECTION_RESET VM2969:1` 

Then, also noticed that clicking on "Virtualmin→Domain→Administration Options→Disk usage" it loads the red line until the end and then `../virtual-server/usage.cgi` keeps running among the processes... I need to kill it otherwise it puts load on the server

**Comment by 7starsone** [comment]
also tried to clear cookies/cache and restart browser

it does weird things, randomly... sometimes it loads the link/tab, other times ERR_CONNECTION_RESET

**Comment by 7starsone** [comment]
another: just clicked on "Search" of Running Processes and

`Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by qooob** [comment]
Nothing like that I could reproduce on 3 different machines, one of which was using proxy.

Fedora, Ubuntu and CentOS. All work as expected.

The following error is not related to the theme. Just ignore it.
```JS
Uncaught TypeError: Cannot read property 'length' of undefined
```

**Comment by qooob** [comment]
I could recommend upgrading the theme using `theme-update.sh` from the console in your case. It will also restart Webmin and Usermin.

That could be the issue but I doubt honestly.

Did you try incognito mode?

What is your browser and client OS?

**Comment by 7starsone** [comment]
again, clicked on sysinfo.cgi link (System Information) and

POST https://domain.com:10000/proc/index_tree.cgi net::ERR_CONNECTION_RESET

don't know...will try incognito
Windows 10 pro 64 + Chrome 62

**Comment by 7starsone** [comment]
well, in incognito it seems working good, just the Disk Usage summary is really slow. Will use it in incognito mode and close the issue for now. Thanks
