### ISSUE TITLE
Theme: Make accordions clickable

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#878]
I notice you have changed the theme configuration but when i want to expand a menu it would be nice if i can do that by clicking on the line and not only the text. The text have different length so the click point is different on every line and this make it annoying.

![image](https://user-images.githubusercontent.com/5789283/32400666-605a0628-c103-11e7-9fcd-f822b8893c9c.png)

Btw, is it possible to turn this new look off? Sometime you want to see all the settings :)

**Comment by qooob** [comment]
Hi,

This is why I implemented the filter and expand all on top right. 

Yes, clicking on the accordion body should also just work, I agree. I will change accordion's behavior.

**Comment by qooob** [comment]
Give it a try.

**Comment by Sopor-** [comment]
One question @qooob, why is `Side slider options` the only one that starts expanded?

**Comment by Sopor-** [comment]
I also noticed that if i collapse them all, expand one of them and i then press the expand button they all expand but if i have them all expanded and i collapse one of them and i now press the expand button they all expand instead of collapse. So now i have to press the expand button one more time to collapse them.
Maybe you should have one button for expand and one for collapse?

**Comment by qooob** [comment]
@Sopor- I left it on purpose being working only half way. I was wondering, if there would be anybody who would notice that. I honestly doubted it. You did it! Great level of pickiness. 

I will fix it on the upcoming commits. We don't need two buttons for it. The toggle logic should be improved. 

About Theme Settings and _Side slider options_ being expanded by default .. :) Well, it should be _Global options_ but you obviously don't have _Default pages_. I will also fix that.

Thanks.

-----

_2 improvements to be made._

**Comment by qooob** [comment]
Give it a try.

**Comment by Sopor-** [comment]
Hmm, i'm not sure i like it... If all menus are expanded and i press one of them, they all closes. Shouldn't that one i press continues to be open and all the others should close?

Global options will now be expanded when I open the page. That is correct, yes?

**Comment by qooob** [comment]
2. Global will be opened by default. That was the initial intent. 

1. Damn it. It's not intended. :beetle:

**Comment by qooob** [comment]
Fixed finally. :crossed_fingers:
