### ISSUE TITLE
After update to 19.02 icons not showing on Safari

### ISSUE THREAD

**Issue by fdmgit** [qooob/authentic-theme#879]
Updated theme from 19.01 to 19.02 and all icons disappeared :-( 
(see attached pic)

Server: 
Ubuntu 16.04.2
Winmin 1.860
Usermin 1.721
Virtualmin 6.01-3

Client:
OS X 10.11.6
Safari 11.0.1

With Firefox 56.0.2 and Chrome 62.0.3202.75 the icons are displayed correctly.

![sidebar](https://user-images.githubusercontent.com/29498370/32402918-760a3576-c12e-11e7-9eed-70d7868d9f4c.jpg)

**Comment by qooob** [comment]
There was an update to the icon pack.

I just loaded it in my Safari 11.0 and I can see the icons. Try clearing Safari cache for now.

**Comment by qooob** [comment]
Here is how I see it on my Mac:

![screen shot 2017-11-04 at 09 25 37](https://user-images.githubusercontent.com/4426533/32403021-5834f91e-c142-11e7-9cfa-7933f931a930.png)

**Comment by fdmgit** [comment]
Nope. Clearing the cache does not help for me. Still no icons

**Comment by qooob** [comment]
Does your Safari support woof2?

**Comment by qooob** [comment]
http://caniuse.com/#feat=woff2

**Comment by fdmgit** [comment]
OK, guess we nailed it down.

Authentic theme 19.02 needs WOFF2. 
Safari 11 needs at least macOS 10.12 (Sierra) to support WOFF2.
--> Just verified it on my test machine. 19.02 looks correct, all icons visible

Might be worth to mention the restriction in the README file.

**Comment by qooob** [comment]
Well. I think it's worth using _woof_ instead of _woof2_. Around 5 kb. difference.

When I checked it, I missed the fact that previous MacOS versions doesn't support it.

**Comment by fdmgit** [comment]
would be great if you support WOFF. 5k is not worth the trouble for a lot of people. :-)

**Comment by qooob** [comment]
Git it a try with the latest update.

**Comment by fdmgit** [comment]
Here we go. It works. 
Great, thanks

**Comment by qooob** [comment]
You are welcome.

Could you please also read below [this comment](https://github.com/qooob/authentic-theme/issues/872#issuecomment-341874754) and try how it works for you on your version of software?
