### ISSUE TITLE
Theme: Missing tooltip for the filter and expand buttons

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#880]
In the File Manager all the buttons have tooltips except the new filter button. Same for the expand button in  the Webmin Themes.

![image](https://user-images.githubusercontent.com/5789283/32417310-cbff04aa-c257-11e7-8379-aaff3f89cafa.png)
![image](https://user-images.githubusercontent.com/5789283/32417316-d40e9b60-c257-11e7-8c4c-253574a8b4c9.png)

The filter button doesn't seems to have the same icon in file manager and webmin themes?

**Comment by qooob** [comment]
Thanks for pointing out. :)

I will add it.

Icons are different on purpose. One is for filtering tables and the other for accordions.

**Comment by qooob** [comment]
Fixed.
