### ISSUE TITLE
after update of authentic-theme i was redirected to my 'Default module for Webmin'

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#882]
If i don't have set any 'Default module for Webmin' i get redirected to the Dashboard but if i have set the 'Default module for Webmin' i get redirected to this page after an update of the authentic-theme.
Is this really correct?

**Comment by qooob** [comment]
By default, when you reload the page, you will be taken not to _default module for Webmin_ but to previously used page.

After theme update - page reload happens. You should be taken to Theme Settings in case you run update from there or to System Information page or to any other page, in case you trigger update from the Side Slider.

**Comment by Sopor-** [comment]
I that case something is wrong. I will get to the 'Default module for Webmin' every time after an update. To get to the Dashboard i need to empty the 'Default module for Webmin'...

**Comment by qooob** [comment]
Yes, in case you clear default module, System Information becomes default.

If you go to any page, let's say Webmin Configuration and then reload the page after few seconds. Will you get back to exact the same page after the reload?

**Comment by Sopor-** [comment]
In that case the 'Default module for Webmin' is useless for me. I want to get back to the Dashboard but it is sad that i can't use the Webmin button because now that button do nothing :(

**Comment by qooob** [comment]
When you click Webmin switch (top of navigation menu) you must get to default Webmin module, that is set in theme's settings (that corresponds with Webmin Configuration by the way). Same happens in case you click on Virtualmin/Cloudmin switch.

In case you click on Dashboard switch (which is only visible if there is no Virtualmin/Cloudmin modules installed), then you must get to System Page (always).

If you reload the page, then you should get to the previously used page. Isn't that what's happening for you?

**Comment by Sopor-** [comment]
What i do is:
1. Open theme configuration.
2. Set `Default module for Webmin` to `Read user mail` and save it.
3. Go back to the Dashboard by clicking the Dashboard switch.
4. To update i open the theme configuration.
5. I use the `Force update theme`.
6. When it is finished it will now show the `Read user mail` page instead of the Dashboard.

The Webmin switch seems to be nice to use as a shortcut button or something, but i don't want it to be the default page after an update. But i leave the `Default module for Webmin` empty and use it as i did before, or should i say i don't use it.

**Comment by qooob** [comment]
Alright, I don't disagree. I like the idea is returning to System Information page after update. I will do it.

Plus I will add a control to Side Slider, where you could run theme info, apply update and do more with one click.

**Comment by qooob** [comment]
Give it a try.

Thanks.
