### ISSUE TITLE
changing theme configuration won't trigger 'Changes you made may not be saved' if i press the Dashboard button

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#883]
If i change something in the theme configuration a small window will pop up and tell me "Changes you made may not be saved". This window won't pop up if i press the Dashboard in the upper left (that button to the right of Webmin). What happens then, nothing.

**Comment by qooob** [comment]
Yes, it's in my to-do since 19.01 release. I will fix it in 19.03 very soon.

Thanks for digging it out.

**Comment by qooob** [comment]
Fixed.
