### ISSUE TITLE
Default module for Webmin - add [None] instead of an empty line?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#885]
In the Default module for Webmin there is only an empty line. Why not add [None] instead of this empty line?

![image](https://user-images.githubusercontent.com/5789283/32609935-8fe494dc-c561-11e7-9c97-f1dc8f5c2e5d.png)

**Comment by qooob** [comment]
Hi,

There are a lot of places where Webmin uses empty label in selects, for example in _Module Titles_ or  _Ports and Addresses_  or many other.

I like this idea. For me empty is empty, void. Self-explanatory.
