### ISSUE TITLE
CPU and Drive Temps in Fahrenheit + Dashboard Missing CPU and Drive Temps

### ISSUE THREAD

**Issue by myopenflixr** [qooob/authentic-theme#887]
Hi,

Is there any way to provide and option to have CPU and Drive Temps display in Fahrenheit system wide (or at least on the main System Information page)? All my temps are displaying in Celcius.

There's a Webmin option to change temps to Fahrenheit, but this only seems to work on the Gray Theme and not Authentic Theme.

![temps](https://user-images.githubusercontent.com/33140130/32691081-86010656-c6d0-11e7-99f2-09fb1f2a5ebf.png)

Also, my Dashboard does not display any CPU & Drive Temps. I'm not sure if I'm missing a setting to have them display, but I could not find any settings to display the additional info.

![dashboard](https://user-images.githubusercontent.com/33140130/32691094-c263b922-c6d0-11e7-8490-73e8c77f4c1e.png)

Authentic Theme: 19.02-git-201711102348
Wemin: 1.860
Server Side OS: Ubuntu Server 16.04.3
Client Side OS: Windows 10
Browser: Firefox & Chrome

Thanks,
Mike

**Comment by qooob** [comment]
Hi,

Right Side Panel will show temperatures only if it's overheating.

You could force to show those labels by adding to your theme extensions (js) the following:

```JavaScript
var config_custom_force_display_cpu_sensors=1;
var config_custom_force_display_drive_sensors=1;
```

About Fahrenheit. Well it seems there is a bug there. It doesn't react on `Units for temperatures` in `Background Status Collection`.

I will take a look, right after I'm finishing working on one MacOS bug.

**Comment by myopenflixr** [comment]
Thanks qooob!

Your solution to force the labels worked great!

I'll be on the lookout for the (hopeful) Fahrenheit bug fix.

**Comment by qooob** [comment]
Fixed. Give it a try.

Thank you for reporting it, Mike. :wink:

**Comment by myopenflixr** [comment]
That worked!

However, I have another question regarding the font. I'm not sure if this is how the temps are supposed to look, but the font used to display the temps seems different than everything else. Is this normal?

![webmin](https://user-images.githubusercontent.com/33140130/32692859-b76d969c-c6ed-11e7-9be8-48ba05d4e660.png)

**Comment by qooob** [comment]
Probably not. I'll take a look tomorrow.

**Comment by qooob** [comment]
Fixed in the commit https://github.com/qooob/authentic-theme/commit/27963911ac4408f8b6836ee85f803289004880e9

**Comment by nsaneman** [comment]
@qooob Is the actual temperatures themed correctly? Previously they were circular, lighter, had more padding and didn't have a shadow.

The change occurred in 19.02.

**Comment by nsaneman** [comment]
@qooob Are the temperatures themed correctly? Previously they were circular, lighter, had more padding and didn't have a shadow.

![Virtualmin](https://i.imgur.com/GMj4icC.png)

The change occurred in 19.02 and in my opinion the squared look is worse.

**Comment by qooob** [comment]
We have more like a square design overall. I wanted them to look alike.

You can always tweak it using The Extensions.
