### ISSUE TITLE
Theme Logo Issue

### ISSUE THREAD

**Issue by myopenflixr** [qooob/authentic-theme#888]
Hi,

So, I decided to upload my own "Theme Logos" today. Initially, I uploaded an image and it worked just fine. Then, I decided to utilize a different image and uploaded it. But, it is still using the original image and not the new one I just uploaded.

![logo error](https://user-images.githubusercontent.com/33140130/32692931-3056b8da-c6ef-11e7-92cb-342f1a7a51b5.png)

As you can see from my picture, the image displayed on left menu is different than the image that appears when I hover over "eye" icon. You'll notice a huge cube on the left menu and a subtle "MyOpenFLIXR" when I hover over the "eye" icon. It is still using the very first image and I can't get it to use the new image.

This error is also occurring on the login screen.
![login](https://user-images.githubusercontent.com/33140130/32692972-1dbe493a-c6f0-11e7-9d68-96344de90bbc.png)

I also checked the image stored on my host computer within the following directories and all 4 of these images are the CORRECT image. It's just not using the image saved in these locations:
etc/webmin/authentic-theme/logo.png
etc/webmin/authentic-theme/logo-welcome.png
usr/share/webmin/authentic-theme/images/logo.png
usr/share/webmin/authentic-theme/images/logo-welcome.png

I can only assume that it stored my original image as a different filename in  different location and it is using that original file and not the ones I referenced above.

Authentic Theme: 19.02-git-201711102348
Wemin: 1.860
Server Side OS: Ubuntu Server 16.04.3
Client Side OS: Windows 10
Browser: Firefox & Chrome

Thanks,
Mike

**Comment by qooob** [comment]
I wonder, if you hit reload in the browser, while you're signed, will it get updated?

**Comment by myopenflixr** [comment]
No. I've reloaded browser. I've restarted Webmin. I've rebooted my server. And I've cleared cookies. I also pulled up Webmin with Chrome and same result. That old image is stored somewhere and still getting used.

**Comment by qooob** [comment]
You just uploaded it. Then it appeared? What else? Did you do anything else?

**Comment by myopenflixr** [comment]
I uploaded it and it appeared on the left menu and login screen immediately. Then, I decided to create the new logo and uploaded it maybe 30 minutes later. It used my new image on the left menu. But after I logged out, it reverted back to the old image.

I uploaded the new image again just now and it used the new image instantly on the left menu. I then opened a new "Private Window" in FireFox (no cookies or stored data) and went to my Webmin login screen. There was the old image again. And after I logged in, it's showing the old image .

I went back into the theme and selected "no" to quit using a custom logo. And, when I pulled up the Webmin login screen, the logo was gone. I went back into Theme Logo and uploaded my new logo again and it appeared right away on the left menu. But, when I opened new "Private Window" and navigated to my login screen, there was that damn old logo...and the old logo was there when I logged in.

**Comment by qooob** [comment]
This is absolutely perfect explanation.

I'll find the source of the issue.

Thank you.

**Comment by qooob** [comment]
Fixed. Thanks for reporting.

**Comment by myopenflixr** [comment]
All is working now. Thank You!
