### ISSUE TITLE
Webminstats panorama general won't load anymore

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#889]
Server side OS - Centos 6.9
Client side OS - Windows 7 x64
Browser Palemoon 27.6.0 (32bit).
After upgrading from 18.48 to 19.0.2 I am no longer able to access Panorama general page.
When trying to access panorama general link for the webminstats plugin, it shows the progress bar, and then nothing happens.
Tried to acccess the link both from favorites, and from the plugin menu itself.

**Comment by qooob** [comment]
Hi,

This is actually not the theme issue. That page is progressing constantly for at least 2 or 3 minutes. Whenever it's done, theme displays it.

I added this page to be treated as progressive but this is more module issue that has to be corrected. I will eventually dump the code block that is responsible for such on-the-fly patches.

I think Sysstats module developer would need to update its module to work properly with new 19 branch. 

We're working very hard to deliver new theme version to production Webmin package.

Some third-party modules either has to follow Webmin UI strictly or do patches themselves.

You can pull the latest commit to have working Panorama General.

**Comment by matrix200** [comment]
Thanks.
I think someone needs to inform the Dev.
The webminstats package is pretty common and lots of people are using it.

**Comment by bcutter** [comment]
Here is the bug tracker for webminstats: https://sourceforge.net/p/webminstats/bugs/97/

**Comment by gerbier** [comment]
Finally fix the problem : authentic theme does not support any more processus fork.
Problem will be fixed in webminstat 2.18,  coming soon.

**Comment by qooob** [comment]
Great to know! Thanks! Please give us a note when it's done, so we could test it.
