### ISSUE TITLE
System statistics (from cloudmin) is displayed in both webmin and cloudmin

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#890]
Server side OS - Centos 6.9
Client side OS - Windows 7 x64
Browser Palemoon 27.6.0 (32bit).
I think the system statistics link should only be displayed in cloudmin tab

**Comment by matrix200** [comment]
Fixed by putting a return statement in the first line of print_sysstat_link function :)
The link is available anyway via cloudmin->system monitoring->system statistics graphs.

**Comment by qooob** [comment]
Hi,

I agree. It's the way it was implemented in the old theme. Besides, also I made Netdata link being displayed only in Webmin menu.
