### ISSUE TITLE
Compare.pm

### ISSUE THREAD

**Issue by TMTYD** [qooob/authentic-theme#897]
Before posting an issue, please search through closed/opened issues to make sure that the answer to your questions hasn't been answered already.

Please make sure that you have latest theme (19.02) and Webmin (1.860) versions installed.

Provide the following information:
* What is your server-side OS and its version?
* What is your client-side OS, browser and its versions?
* What are the steps to reproduce the issue?

Hi my OS is Debian Stretch,

Have just looked through my logs and in the file /var/webmin/miniserv.error was the following message:

Argument "git" is not numeric in int at /usr/share/webmin/authentic-theme/lib/Version/Compare.pm line 32.

**Comment by qooob** [comment]
Thanks.
