### ISSUE TITLE
Login page is too slow

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#898]
Hello,
in my opinion the login page **/?virtualmin** is too slow.

There's just a form to login, I don't think that is a good reason to wait seconds the 1st time you visit it.
It should be less than 1 second.

**Comment by qooob** [comment]
Hi,

I don't think there is much to do.

On my Fedora machine it takes ~0.2-0.5 seconds to load.

On my VM Ubuntu around 2 seconds. On same VM CentOS around 1 second.

Besides, restarting Webmin changes time.

**Comment by qooob** [comment]
Okay, let's remove unnecessary JavaScript bundle, it really makes things faster..

**Comment by 7starsone** [comment]
👍 😄
