### ISSUE TITLE
Logout Button...

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#90]
First off bravo on the latest release of your theme, it's come a long way in a very short period!

A few customers who primarily use Usermin provided me some feedback regarding the "logout" button. They indicated at first glance that it didn't look like one existed, then realized it was there however seemed not as obvious to locate.

Honestly, while I do love the sleeker design brought into the latest branch of updates, I do agree with the logout option being a bit hidden. Perhaps this could be re-worked, maybe even placed back up in the right corner as it was before.

Cheers!

**Comment by qooob** [comment]
Uhh.. Putting it back in the right corner is simply impossible, as I completely removed top header.

Nevertheless, I will try to make it more visible!

**Comment by tpnsolutions** [comment]
I hear ya, just needs to be a bit more visible somehow, as in it's current state it can easily be overlooked.

Again, just passing on feedback I received, and vetted :-)

**Comment by qooob** [comment]
I made it visible in Usermin. Your customers should be happy. It will be added in version 9.0.4.

**Comment by qooob** [comment]
Please enjoy theme version 9.5.0, which has fixed logout button for your customers in Usermin.
