### ISSUE TITLE
csf stopped working on theme 18.49-9

### ISSUE THREAD

**Issue by edwardsmarkf** [qooob/authentic-theme#900]
hello - i hope this is the correct place to mention this.  csf stopped loading in my webmin. here is the error i see in the browser-console:

> Uncaught TypeError: Cannot read property '0' of null
>     at csf_init (csf.min.js:6)
>     at 162.###.###.###/:282
> 

changing the STYLE_CUSTOM to zero gets around it, as[ per this suggestion:](https://forum.configserver.com/viewtopic.php?f=6&t=10594&p=28979)

the error seems to be in **/extensions/csf/csf.min.js** - and when i pretty-print it, it shows at line 280:

 ` , O = $('pre:contains("csf:")').text().match(/((?:(\d+).)?(?:(\d+).)?(*|\d+))$/)[0] || "9.xx";`

the end of the line is highlighted:` [0] || "9.xx";`

Operating system | CentOS Linux 7.4.1708
Webmin version | 1.860
Usermin version | 1.720
Virtualmin version | 6.01
Theme version | Authentic Theme 18.49-9
Firewall version | ConfigServer Security & Firewall 11.05

**Comment by qooob** [comment]
Yes. Please upgrade to theme version 19.03.

**Comment by qooob** [comment]
The patch for the latest 11.05  will be released soon.

**Comment by edwardsmarkf** [comment]
should i just wait patiently until the update option is available in my webmin console?   i have never manually updated a theme before.

**Comment by qooob** [comment]
You could got to theme settings and force update the theme at the bottom of the screen.

You could wait as well. It's up to you.

**Comment by edwardsmarkf** [comment]
is that where it says "install latest development version (beta)"?   ;-)

**Comment by qooob** [comment]
You can choose any, as it will anyway lead you to 19.03, because there hasn't been commits yet, since last release.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/commit/35084af5f60317d0b7ef80be59a99991f086736c

It's fixed in the commit above. 

I think version 19.04 will go to the next Webmin release.

You can force upgrade the theme to get latest fixes work.
