### ISSUE TITLE
Monitor if load average comes to...

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#901]
Hello,
sorry, I know that it's not directly related to Authentic,
but I need help...

I want to create a "Load average" monitor and run a command if load average comes to x

On the "Create Monitor" window, from "System and Server Status"
I just have

```
If monitor goes down, run command 
If monitor comes up, run command 
If monitor times out, run command

```
then, on the bottom the field `Maximum load average`
what's the correct option to
run a command **IF** load average is ≥ x ?
I can't understand, thanks

**Comment by qooob** [comment]
It's all coming from [general idea](http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages) of `uptime` command output.

You can define when to trigger command execution, based on _Maximum load average_ value and time interval.

I would make that value set to something like 70%, meaning _**0.7**_. When the average load in relation with time interval, gets to this point you will be notified.

**Comment by 7starsone** [comment]
maybe I wasn't clear: I know about the load average logic...

I need to run a command when load average is ≥ x (eg. ≥ your 70% example)
but there's not a clear option on that windows

What's the option? Isn't it available and so... Do I need to use another app?

**Comment by qooob** [comment]
You don't need another app. :smiley: 

I think, the value for _Maximum load average_ would depend on the number of cores that you have in your CPUs.

Try to install `stress` command to just artificially create load on your system:

```
``

**Comment by qooob** [comment]
After that you will figure out the number that you would want to set in _Maximum load average_.

Create the monitor with the value equals to `1` then save it monitor. It will have a history there after all. Run stress command to figure things out for your self.

**Comment by 7starsone** [comment]
I don't need to "manually" run a command...I need to **auto** run a command **IF**...

here I have:
If monitor **goes down**, run command 
If monitor **comes up**, run command 
If monitor **times out**, run command

simply, they don't make sense with load average, that's it

**Comment by 7starsone** [comment]
Screen:
![Load Average](https://s2.postimg.org/axlodp8yh/load_average.jpg)

**Comment by qooob** [comment]
I understand now.

I don't see an option to run command _IF_, you're right.

The right is to file an issue on Webmin repo, Jamie is the best person on Earth to be asked.

**Comment by jcameron** [comment]
Setting the load average for the alert to be the level at which you want the command to run is the right thing to do - in Webmin, "going down" means the alert has triggered.

However, if you're testing this, make sure the load drops below the target for at least one monitoring cycle, and then ramp it up again. The command will only be run the first time load crosses over, not on every cycle.
