### ISSUE TITLE
File Manager: Post upload unresponsive UI

### ISSUE THREAD

**Issue by fdmgit** [qooob/authentic-theme#903]
I've used the file manager to upload a file to a directory. The file upload completed successfully but then the UI was grayed out and unresponsive (--> any click on the UI did not have any effect). 
I had to refresh the page (browser reload) to get back to normal operation. 
This is happening with Safari, Firefox and Chrome.

Any hints ?

Server:
Ubuntu 16.04.2
Winmin 1.860
Usermin 1.721
Virtualmin 6.01-3
Authentic Theme V 19.03

Client:
OS X 10.11.6
Safari 11.0.1
Firefox 57.0
Chrome 62.0.3202.94

**Comment by qooob** [comment]
Yes,

This part of UI on my closest to do. After 19.04 release I will try enrolling multiple uploads for other modules and for File Manager in particular.

You can see the of upcoming [improvements](https://github.com/qooob/authentic-theme/issues/629) and number 11 in the list.

**Comment by qooob** [comment]
There will be no improvemt, I think. I'll just completely replace it with multiple uploads feature without using old pop-ups.

There is still higher priority issues but it's going to be fixed for sure.

**Comment by qooob** [comment]
This issue has been fixed with the latest commit.

I will try to add nice uploads, without popups quickly. If it works, I will add it to 19.07 release very soon, otherwise it will go for the next 19.10 feature release within next two weeks or so.
