### ISSUE TITLE
login to Usermin from Webmin fails

### ISSUE THREAD

**Issue by brad1001** [qooob/authentic-theme#905]
Using Authentic theme version 19.03 From Webmin > Virtualmin > Edit Users  the "Login to Usermin" fails to login or open a new tab as it did in versions 18.xx 

Thanks
Brad

**Comment by qooob** [comment]
Sounds like possible issue.

I'll take a look tomorrow morning, thanks.

**Comment by qooob** [comment]
Requires more work, even after:
https://github.com/qooob/authentic-theme/issues/896#issuecomment-347474843

**Comment by qooob** [comment]
I found the way to make it work. Give it a try.

Besides, switch to other user and server owner will also work now.

Thank you for reporting!

**Comment by brad1001** [comment]
Great thanks for the update and fix  -  I gather the updated code will also be available in the next theme release.

Kind Regards
Brad
