### ISSUE TITLE
First Capital letter in Username during login

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#906]
Latest theme and Ubuntu.

I have LG G5, Android 7.0 and using latest Chrome app. with Gboard keyboard. On the login page to the server there are 2 input boxes: Username and Password. While typing the username, the first letter is a upper case letter as default instead lower case letter as like for a password for example.

Is possible to add an attribute into the theme, to make sure the phone knows the first let should be lowercase?

**Comment by qooob** [comment]
Yes,

Input field should get an attribute:

```CSS
autocapitalize="off"
```

Finishing first stage of real-time monitoring now and will update this a bit later.

Thanks for advising.

**Comment by qooob** [comment]
However, it seems that `off` value is deprecated, and `none` is what we need.

**Comment by qooob** [comment]
The following commit should fix your issue.
https://github.com/qooob/authentic-theme/commit/bdf6af7b565861ea4f685effa98ac60b2058b38f
