### ISSUE TITLE
Will Terminal be able to run all the commands?

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#907]
Hello,
honestly, at the moment the terminal function has not a great purpose...

eg. I can't enter mysql, can't run a htop command and so on...

your last stats improvement is good for sure, but I would like to be able to run all the commands from that terminal...

will it be possible?
Thank you very much

**Comment by qooob** [comment]
Hi,

It's not limited by the theme but by server side. Yet, it won't but should be in the future.

**Comment by 7starsone** [comment]
Please, could you add a kind of refresh button to "Database Connections", that one which does **show full processlist** ?

**Comment by qooob** [comment]
Which module/file you're talking about?

**Comment by qooob** [comment]
`Alt+R` refreshes current page by default.

**Comment by 7starsone** [comment]
ok, thanks `Alt+R` is enough
