### ISSUE TITLE
Real memory showing weird value after update

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#908]
Something must be wrong with this new live pie charts. As you can see i'm not using 73% of my memory. It is more like it is showing how much i have free.

![image](https://user-images.githubusercontent.com/5789283/33320485-b3b309b2-d442-11e7-8077-35d33140749a.png)

**Comment by qooob** [comment]
What is the output of 

```
free
```

Those numbers must be updated as well. I will add this on the next fix.

**Comment by Sopor-** [comment]
$ free
```
             total       used       free     shared    buffers     cached
Mem:       8172904    5970108    2202796      63252     289956    4724100
-/+ buffers/cache:     956052    7216852
Swap:      4194300      17424    4176876
```

**Comment by qooob** [comment]
73.047572809 = (5970108/8172904)*100.

**Comment by Sopor-** [comment]
19.03 theme:
![image](https://user-images.githubusercontent.com/5789283/33323484-e892a886-d44c-11e7-9a5b-5206ec197e74.png)

**Comment by qooob** [comment]
Because default output was based on Jamies logic. He actually asked me if I could stick to the existing code. I promised to try. It might be not even an issue in a bit.

But you should definitely open on issue at Webmin repo, in case `free` command and `WebminCore` produces really different results and it does.

**Comment by Sopor-** [comment]
I have talked about this before with Jamie and this was the answer:
`The difference is due to the system using RAM to cache data recently read from disk. Webmin considers this free because it can still be used by other programs, but commands like free report it as in use..`

**Comment by qooob** [comment]
We should rely on Jamie. I will use Webmin API then. The only apprehension I have, is whether using WebminCore will be the same fast. I will comeback to it after fixing bunch of upcoming issues.

**Comment by Sopor-** [comment]
This is and old Cubieboard i'm running and here it seems to show totally different values...
![image](https://user-images.githubusercontent.com/5789283/33327853-c1faa0dc-d458-11e7-81f4-90ca5bc3d15d.png)
```
$ free
              total        used        free      shared  buff/cache   available
Mem:        1024696       56068      640808        5360      327820      934036
Swap:        524284           0      524284
```
It must have something to do with the cache, right?

**Comment by swelljoe** [comment]
We definitely want to treat buffer/cache as free memory.

**Comment by qooob** [comment]
I will rely on Jamie's output, if I can make dependencies load that quick.

Otherwise, I will consider buffer in my math.

**Comment by Sopor-** [comment]
@qooob I don't know if i'm too fussy but your pie chart don't show the same CPU usage as TOP. To increase the usage to 22% the CPU usage in TOP seems to be increased to 28% the pie chart go 1 percent up.

![image](https://user-images.githubusercontent.com/5789283/33377797-02a75994-d513-11e7-8b70-5281b87674c5.png)

**Comment by qooob** [comment]
Actually `vmstat` and `top` produce identical results. As they update constantly you probably overlooked something.

**Comment by Sopor-** [comment]
I don't know. That is why i ask you to confirm if this is right or wrong. Webmin shows 21% even if TOP goes up and down between 23% and 27%.

**Comment by qooob** [comment]
I'm looking right now to reworking it a little bit. I will come back to you about tomorrow, I think.

**Comment by swelljoe** [comment]
I don't think any CPU monitoring can ever be "identical". CPU fluctuates wildly from moment to moment, and our puny human minds can't possibly grasp those changes. Depending on when top or vmstat samples the usage, it'll vary. We'll never have an exact measure of CPU usage. If any given measure is within a few percent of any other measure, we're probably fine.

**Comment by qooob** [comment]
We will use Jamie's code base for the real-time stats, so the numbers will be the same across all modules.

This is no longer an issue.

**Comment by qooob** [comment]
You can follow up here:

https://github.com/qooob/authentic-theme/issues/896

**Comment by qooob** [comment]
@Sopor- Check #896.

It's been an update. Give it a try.
