### ISSUE TITLE
Printing from Read User Mail

### ISSUE THREAD

**Issue by nlbailey91** [qooob/authentic-theme#91]
When printing from the Read User Mail module a blank page is added add the end of the email.

**Comment by qooob** [comment]
When I click Print, everything seems normal. New window is opened and message body is ready to be printed. What do you get?

**Comment by nlbailey91** [comment]
I get the message body up fine, but when the print dialog box opens with
the preview (in Chrome) an extra page is added after the main content.

**Comment by qooob** [comment]
Well, that, I'm afraid has nothing to do with Authentic Theme. You get the message that is shorter and that will be alright.

**Comment by nlbailey91** [comment]
But the message is short and involves no scrolling within Webmin itself. If I change the theme to a different one then when I go to print I do not get the extra page added. Please see attachments.
![webmin-print-email-authentic-theme](https://cloud.githubusercontent.com/assets/10864661/6061523/71f50b28-ad40-11e4-9ee7-1946bbe28483.PNG)
![webmin-print-email-bootstrap-theme](https://cloud.githubusercontent.com/assets/10864661/6061524/71f6a690-ad40-11e4-8f07-1c35b9ffe569.PNG)

**Comment by qooob** [comment]
Alright, I will take a closer look. You could always, choose what pages to print. Choose instead of `all` page number, and the empty page will not be printed. (But I think you already know that).

**Comment by qooob** [comment]
I have double checked it again. I have Chrome 41 and I could not reproduce your problem. All messages are displayed as they should be. No extra pages added. Besides you can always set how many pages you're willing to print or which pages in particular.

I will keep this in mind for the future but so far I can not assist here, as it doesn't seem to be a theme bug!
