### ISSUE TITLE
Favorite star disappear after applying changes

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#911]
After i press the `Apply Changes` in the nginx module the favorite star disappear and won't come back (it does in the gif because it is looping):

![2017-12-01_18-00-17](https://user-images.githubusercontent.com/5789283/33493889-d1c06478-d6c1-11e7-89ac-302e2806886b.gif)

**Comment by qooob** [comment]
Hi,

This would also happen in BIND, Apache and other modules without proper redirect. It's not really theme issue though. Theme compares URLs and they are different after Apply/Stop/Start.

The solution would be is to perform redirect on the server to the root folder thus, and not create difference in URLs.

**Comment by qooob** [comment]
https://github.com/webmin/webmin/issues/710

**Comment by qooob** [comment]
Sorry for being funny. It's actually my issue. Fixing ..

**Comment by qooob** [comment]
It's been to much to do recently. Mindoverflow. 😉
