### ISSUE TITLE
very fast progress indicator on slow systems

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#913]
When i for example refresh the modules the red progress indicator at the top of the page goes very quickly from left to right and when there is only a few percent left it will get stuck there for a long time. It is very hard to see if the page is working or if it got stuck or maybe it is already finish.
From 0%-98% it takes 10 seconds and from 98%-100% it takes 37 seconds.
![image](https://user-images.githubusercontent.com/5789283/33518345-b7538c32-d793-11e7-861b-fcd3cf18684c.png)

**Comment by gnadelwartz** [comment]
the progress indicator does not show real progress, its only an indicator that the theme is waiting for data to be transfered.

additional question: which system is slow, client or server running webmin? guessthe latter.

@qooob may be the progress indicator can start over instead of waiting for data and staying at 98%?

**Comment by qooob** [comment]
It's not natural for it to start over. The only thing I can do right now is to decrease its rate and speed. It will go directly to the release within 3 hours.

**Comment by Sopor-** [comment]
No big difference than before. From 0-98 it will take 15 seconds and from 98-100 it will take 32 seconds.

**Comment by qooob** [comment]
Server response can be different. We never know how long is that gonna be. How do you expect progress behave?

**Comment by Sopor-** [comment]
Isn't possible to have something like this?

**Comment by Sopor-** [comment]
Isn't it possible to have something like [this](https://i.pinimg.com/originals/ee/e2/db/eee2db64702fd23c3ed67811814b6454.gif) or [this](http://2.bp.blogspot.com/-O7nsXfmgwSc/T6PQ0PVr6-I/AAAAAAAAAQI/-eXkEXj24-s/s1600/02.gif)?

**Comment by qooob** [comment]
I don't think so..

Unless it's constantly moving and occupying the whole width right at once.

What others think?

**Comment by gnadelwartz** [comment]
I think the simplest way is to start over if the inidicator reaches the end, so you know we are waiting ...

alternative may be switch to a circling loading indicator instead

**Comment by mgancarzdsi** [comment]
If there is no way to know how long, a looping one is only solution. Preferably with some message such as "Waiting for server" or something

**Comment by Sopor-** [comment]
How about having a red line that goes back and forth?
![theme-anim](https://user-images.githubusercontent.com/5789283/33605436-0ace3114-d9ba-11e7-989a-01babf4c037b.gif)

**Comment by Sopor-** [comment]
Maybe the speed could have an option so the user could adjust how fast it should go back and forth?
If your computer is fast and modern the bar need to go faster or else it won't move very far and if you have an older slower computer it will be very annoying to have a bar that goes back and forth very fast.

**Comment by qooob** [comment]
I think I will remove all js libraries for this and simply replace it with few lines of css code. Emplementation of progress is abstracted so replacing it will be very easy.

**Comment by qooob** [comment]
Alright, let's keep it repeating so far. In the future, I will come up with more fancy CSS animation.

Tell me how you like it. It uses no JS now. So one dependency less.

**Comment by gnadelwartz** [comment]
there is not much difference. moves from left to right, sometimes stops and stay at 98% if a module needs log time to load.

if someone is looking for a module with lod loding time, try read user mail :) if you gave zsrs with big mailboxes

**Comment by qooob** [comment]
@gnadelwartz I have no idea what you mean by "no difference".

The loader now automatically restarts. Exactly addresses the initial issue.

Have a look at my [video-screencast](https://rostovtsev.ru/pub/src/authentic/19.04/new_loader_part_1.webm).

**Comment by qooob** [comment]
Okay, I think I know why it's not working for you. Firefox 57 unlike 59a and Chromium doesn't recognize 0 in @keyframes.

I will update it very soon.

**Comment by gnadelwartz** [comment]
yes Im using firefox, but I don't bother because inna few weeks I'll have FF59 😁

**Comment by qooob** [comment]
Okay, I have fixed my local compilers to make sure latest code styles are considered.

You can upgrade now. It will use fancy loaders.

In case it's fast - it will be as used to be.

In case it's slow or something big is updating, it's going to be bouncing back and forth. 

I hope you like it @Sopor- .

Let me know more.

**Comment by Sopor-** [comment]
Now it will work as it did before but if the server is slow it will start to go backwards.
@qooob It looks very nice 👍
