### ISSUE TITLE
Issues with Apache Webserver Add/Edit rules

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#914]
Hello,
that's not easy to explain.

It seems that there are issues when you edit/save the conf files for `Directory ` rules (or even all the settings related to Apache, I don't know)

Eg. you "Create Per-Directory..." into the `Virtual Server`

so, create a directory path
then go to `Edit Directives`

sometimes it seems to save, other times when you go to view the saved directory,
it returns the OLD content, the OLD rules...

how this happens?
And also, now if you use the old framed theme, obviously the browsers complain about the "**frame-src**" matter... for example Chrome doesn't work at all with Virtualmin and the old theme

Please, can you test this situation?
thank you

**Comment by 7starsone** [comment]
another example:
while using Authentic Theme

I was on **https://mydomain.com:10000/apache/**

deleted **2 Virtual Servers** from the list.
Subsequently, they reappeared again.

I had to use Firefox and the old framed theme to delete them.

Actually, they are not there anymore.
Thanks

**Comment by qooob** [comment]
I tried the steps you described - it all worked for me.

I suppose you have some aggressive extensions that multifunction.

Please try again in incognito mode.

**Comment by qooob** [comment]
I have tested it on proxy and non-proxy setups, with different Linux distributions and under Webmin/Virtualmin - all works as design.

In case you still have this issue after next Webmin update and the recent theme, please feel freen to reopen this issue.
