### ISSUE TITLE
Theme: Failed to upgrade due to dependency on Webmin 1.870

### ISSUE THREAD

**Issue by UniverseXXX** [qooob/authentic-theme#916]
Failed to upgrade to 19.04 due to dependency on Webmin 1.870. However, 1.870 wasn't released yet.
Thanks.

**Comment by qooob** [comment]
I know. It hasn't but it's coming. It's really Webmin 1.870+ depended.

**Comment by UniverseXXX** [comment]
Thanks @qooob

**Comment by Sopor-** [comment]
@qooob I was able to update to 19.04 and i'm still running Webmin 1.860 ?

**Comment by qooob** [comment]
Yes, but real-time stats will not work.

**Comment by lunarovic** [comment]
Do you happen to know if Webmin updates are released on a different schedule for CentOS vs. Ubuntu? I know new versions are released at the same time [for all OSs](http://www.webmin.com/download.html) (1.870 was released on 6 Dec 2017), but I mean maybe it's not released at the same time in the update channel in Webmin or something. I can't seem to find this info anywhere.

Because on my CentOS 7.4.1708 machine I already had an update to Webmin 1.870 (and Authentic 19.04), but on my Ubuntu 16.04.3 machine it's still Webmin 1.860 and it says there are no updates.

**Comment by qooob** [comment]
@lunarovic Just go to Software Package Update and hit refresh packages. You could also run 

```Bash
sudo apt-get clean
```

**Comment by lunarovic** [comment]
Thank you for the response. I forgot to mention that I had already tried "_Refresh Available Packages_". I did it again now and this is the result:

> Clearing package caches ..
> .. done
> Re-fetching available packages ..
> .. found 0 possible updates

On Ubuntu on the "_Software Package Updates_" page, when I switch from "_Only updates_" to "_Installed_", and then in the list I click on "webmin", it shows this:

![image](https://user-images.githubusercontent.com/2381553/33795086-2ab320b6-dcda-11e7-8c82-e3a92e03912d.png)

Now compare that with this screenshot from the same page for webmin package info, on CentOS:

![image](https://user-images.githubusercontent.com/2381553/33795149-c331db1a-dcdb-11e7-8499-e3418b940694.png)

So maybe APT doesn't have the newest version yet, but YUM has it? Maybe we can check APT repositories to see which version is hosted there?

(Btw, look at the last field "_Installation Source_" - it just says "_Installed_" on CentOS, isn't that strange?)

Also I tried manually initiating an update on Ubuntu:

![image](https://user-images.githubusercontent.com/2381553/33795102-8586f350-dcda-11e7-9df4-bbecd20e8e8f.png)

I also tried `sudo apt-get clean` and I rebooted the machine, but no results. And I have Ubuntu and CentOS on the same hardware and same Webmin config, so it must be APT/YUM differences?

Thank you.

**Comment by qooob** [comment]
Yes,

I seems like the  package is missing.

Let's figure this out.

Tell me, do you use Virtualmin repo or only Webmin?

**Comment by lunarovic** [comment]
I used http://software.virtualmin.com/gpl/scripts/install.sh if that's what you're asking?

**Comment by qooob** [comment]
It seems that the package is really missing .. I'm letting Joe know.

What you could do, is to download the package from Webmin repo manually.

In case it's urgent, just feed to the installer the link:

```
https://netix.dl.sourceforge.net/project/webadmin/webmin/1.870/webmin_1.870_all.deb
```

**Comment by lunarovic** [comment]
Ok, thank you Ilia for the support even though this was an issue with Webmin, not with Authentic theme :) Maybe an issue should be opened there, or not if you informed them. Thanks again for quick responses.

**Comment by qooob** [comment]
You are welcome. Yes, I did. 

Have a great day.

**Comment by swelljoe** [comment]
I may have forgotten to publish the changes to the Debian/Ubuntu repos. It's been done now. Try it again.

**Comment by lunarovic** [comment]
I don't know if I'm missing anything, I tried again all of the things suggested above and Webmin is still 1.860. Which repos are those exactly? I installed a fresh Ubuntu 16.04 and a fresh Virtualmin again from the install.sh script, updated everything etc.

**Comment by lunarovic** [comment]
@swelljoe 

```
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Hit:5 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-xenial InRelease
Hit:6 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal InRelease
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

http://software.virtualmin.com/vm/6/gpl/apt/dists/virtualmin-universal/
I am a newbie for this, but from this link I see that files have been last modified today, but apt is still not finding a new version there?

Also I ran this command if that's of any help:

```
$ sudo apt-get clean
$ apt-cache policy webmin
webmin:
  Installed: 1.860
  Candidate: 1.860
  Version table:
 *** 1.860 500
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main amd64 Packages
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main i386 Packages
        100 /var/lib/dpkg/status
     1.853 500
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main amd64 Packages
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main i386 Packages
     1.852 500
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main amd64 Packages
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main i386 Packages
     1.851 500
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main amd64 Packages
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main i386 Packages
     1.850 500
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main amd64 Packages
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main i386 Packages
     1.842 500
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main amd64 Packages
        500 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal/main i386 Packages
```

**Comment by swelljoe** [comment]
Crap, you're right. My new Webmin update script didn't include the GPL repos for Debian/Ubuntu. Fixed now, I'm pretty sure. Thanks for the heads up.

**Comment by lunarovic** [comment]
It updated to the latest version now, thank you for your work! 👍

**Comment by qooob** [comment]
@lunarovic Don't forget that you will get bundled theme after upgrading Webmin. Don't forget to pull latest changes.
