### ISSUE TITLE
I suggest you!

### ISSUE THREAD

**Issue by bogdanpuica** [qooob/authentic-theme#918]
![temp](https://user-images.githubusercontent.com/30603097/33594197-98e5b9d2-d99b-11e7-9364-f1a96ac9cf1a.png)

**Comment by qooob** [comment]
Yes, I also like it this way.

It's actually already in the theme! The option called `Show CPU and drives status each on new line`. By default it's set to `false` so in case you intentionally turned it on, you shouldn't be seeing it.

I will actually remove this option. I don't think it's valuable anymore.
