### ISSUE TITLE
Sysstats Panorama Broken

### ISSUE THREAD

**Issue by imfineru** [qooob/authentic-theme#919]
Has version 19 and up broken Sysstats Panorama General for anyone else? Only the CPU graph opens at first, then about 30 seconds later, all graphs open.  Downgrading to Authentic 18.49 fixes it back. Latest version of all software installed, including Webmin itself. Thank you in advance.

**Comment by qooob** [comment]
Could you provide the screenshot?

**Comment by imfineru** [comment]
**Version 18.49 Working excerpt:** 

![18 49](https://user-images.githubusercontent.com/14332041/33619671-d42cbfbe-d9b3-11e7-8277-c513a4a44933.PNG)

**Version 19 and up Non-Working:**

![19 04](https://user-images.githubusercontent.com/14332041/33619679-d9556ab8-d9b3-11e7-98c8-2e54382f4c84.PNG)


Thank you again for taking a look.

**Comment by qooob** [comment]
Are you opening it in the separate window?

**Comment by imfineru** [comment]
No. Same window. All browsers. Also refresh of page loses left menu. Thank you.

________________________________

**Comment by qooob** [comment]
Refresh is part of upcoming Webmin patch. I remember fixing Panorama General. I'll double check.

**Comment by imfineru** [comment]
The rest of the graphs eventually populate, but it takes close to 90 seconds. Yhis is on a i7 2.7 Ghz laptop client.

**Comment by qooob** [comment]
What theme version do you have?

**Comment by imfineru** [comment]
18.49. Anything above 19 breaks Sysstats.

**Comment by qooob** [comment]
I will take a look tomorrow morning.

**Comment by qooob** [comment]
Okay, I have provided a fix but it's better to update Sysstat module after the official release of the next Webmin, with the latest 19.04 theme.

**Comment by imfineru** [comment]
Noob at Git, and updating one file, could you give me quick instructions on how to update?

**Comment by qooob** [comment]
Sure, go to the theme settings and use the button Force Upgrade/Install latest development version.

**Comment by imfineru** [comment]
Thank you. The "fix" just opens a new window, but all graphs show. Thanks for working on that, and EXCELLENT work on this theme. Been using for quite some time.

**Comment by qooob** [comment]
Thank you for your kind words. 😊
