### ISSUE TITLE
Authentic Theme 9.0.3 disables Historic System Statistics

### ISSUE THREAD

**Issue by roydenyates** [qooob/authentic-theme#92]
Hi,

An astonishingly refined look this. Well done!

"System -> Historic System Statistics -> any of categories" do not work under Authentic Theme 9.0.3. They do under the default Webmin theme.

If I recall, this happened with the UI re-design v9.0.0

**Comment by qooob** [comment]
I have applied a patch that made most part of this module work. Not sure what isn't working for you exactly? If you mean stuck loader.. Well, developer (of Webminstats) contacted me about this issue already and promised to rework his module. You can read more about it here: https://github.com/qooob/authentic-theme/issues/1

In case you have a stuck loader, just double click on it to make it disappear.

**Comment by roydenyates** [comment]
Oh ho! That worked. I never saw the loader stuck until 9.0.0.

But thanks for the answer.

**Comment by qooob** [comment]
Alright, glad to be helpful. You might find more interesting things if you read main page of the theme ;) 
https://github.com/qooob/authentic-theme

**Comment by roydenyates** [comment]
Had a look there, thanks.

The vertical column of Historic System Stat icons, is that too an issue for that dev? (Meaning they don't arrange compactly in rows).

**Comment by qooob** [comment]
So far that module uses old mechanisms. Yes, rows are huge, I know. Whenever it's rebuilt, I will try modernize it.
