### ISSUE TITLE
Theme: Dashboard customizable data

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#920]
Now with this new dashboard layout the values will be places on different sides depending on how much info i have on it. I will never know on what side i have updates on or what side i have the system uptime. It makes it much harder to find what i'm looking for because i have to look with my eyes to find it. With the old layout it was much easier to find what i was looking for. For example, i always knew the update was at the bottom.
I have 4 Webmin's and two of them have `System uptime` to the right and the other two to the left.

![image](https://user-images.githubusercontent.com/5789283/33677960-c095986a-daba-11e7-94da-376a5966e595.png)

**Comment by qooob** [comment]
What do you suggest?? 😁

**Comment by Sopor-** [comment]
I also noticed that the blue line that will highlight the line goes from column left to right. Now when it is separated into two columns this blue highlight should not go across both columns.

**Comment by Sopor-** [comment]
> What do you suggest??

I have only one suggestion, make them movable so i can choose my own order.

**Comment by qooob** [comment]
Okay, I will a bit later, though. Let's see how the things go ..

When I add drives graphs and other live stats, I will turn it into controlable widgets, that user could control.

**Comment by gnadelwartz** [comment]
it looks like there is simply different infos displayed, i simply guess the second picture is a VM while first is physical hardware. nevertheless it may annoying.

i would say move the not everywhere availible information to the end of the list.

**Comment by qooob** [comment]
Ref.: Todo #1.
