### ISSUE TITLE
Most buttons don't work in referers_none=1 mode

### ISSUE THREAD

**Issue by yulimoto** [qooob/authentic-theme#922]
With **referers_mode=1** (webmin and usermin) 
 
When I upgrade to 19.01, 19.02, 19.03 some of buttons (white buttons) don't work after time. In Chromium 53 (Linux)  when all cache is cleared they works for  a while.

Version 19.04. I cannot confirm because I use Webmin 1.860 (official debian update is not released yet), but when I installed it 19.04 manually on 1.860  some of buttons didn't work agian. 

Version 18.49 is not impacted.  

Reproduce 

 1.You need to set referers_mode=1 in webmin and usermin
/etc/webmin/config
/etc/usermin/config
2. Use version 19.01 to 19.03 (probably it affect 19.04 also) 
3. For example try to save some settings in theme, or to change theme (If buttons works, please restart browser, login and try again this step, use webmin with *referers_mode=1 for certain tme) 

Browsers: Cromium 53 (Linux), Firfox 45 (Linux)
Webmin 1.860 
Debian GNU/Linux 8 (jessie)

**Comment by yulimoto** [comment]
I  confirm that with webmin 1.870 issue is solved

**Comment by qooob** [comment]
Thank you. Good to know. 😄

**Comment by qooob** [comment]
`referers_mode=1` is default value, by the way.
