### ISSUE TITLE
Virtualmin Configuration help links load into a new empty page rather than pop a tooltip

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#923]
In System Settings->Virtualmin Configuration, the help links don't work right; they load into a blank white page, rather than popping up a tooltip. (Other tooltips seem to work, it's just the Virtualmin Configuration page that does this.)

**Comment by qooob** [comment]
Hi, Joe.

Confirmed. Will be fixed in a bit.

**Comment by qooob** [comment]
Okay, I finally fixed my system after fresh upgrade.

It happened because bind event was destroyed with new new config to accordions feature.

It's fixed on the latest commit.
