### ISSUE TITLE
Webmin Servers  Index not working

### ISSUE THREAD

**Issue by escservices** [qooob/authentic-theme#925]
Server OS Ubuntu 16.04.3 LTS

Webmin latest 1.870
Authentic Theme 19.04
Kernel and CPU | Linux 4.4.0-103-generic on x86_64

Tested in Windows 10 Fall Creators Update
Using Google Chrome Latest, Edge & IE

When clicking on linked servers in Webmin Servers Index it redirects to current servers homepage and not the homepage of the server I was trying to connect to.  Switched to other themes and it works fine and redirect me to selected server.

**Comment by qooob** [comment]
I will take a look. Sorry about that.

**Comment by qooob** [comment]
I see the cause of the issue.

Will fix it in a bit..

**Comment by qooob** [comment]
I fixed redirect loacally but there other issues with this module..

Work in progress ..

**Comment by escservices** [comment]
Understood, thanks for taking a look at it.  This is a really great theme, great job!

**Comment by qooob** [comment]
Okay, it will work with minor issues on redirects. I will fix it, when Jamie provides an ability to get linked server id from environment.

**Comment by qooob** [comment]
This patch we'll make things work completely well. It's going to require upcoming Webmin associated patch as well.
https://github.com/qooob/authentic-theme/commit/e1f0db9da912b44f8df678a36264b2e8aaa92c4c
https://github.com/webmin/webmin/commit/7dfa97c6ca703f814cff4cd1a65c50bf0232315f

**Comment by iliarostovtsev** [comment]
> But when I'm logged in as other users I click on it

What user is this exactly?

**Comment by Rosstarz** [comment]
So I've tested this a bit more.

My main server is https://portal.24lively.com:10000
And I made you a login:
Usertest
uecC#@sWZ4x^!oK

This user has unrestricted privilege level but has access only to Webmin Servers Index (renamed to My Servers)
And this is his module configuration for the Servers Index
![Screenshot_112](https://user-images.githubusercontent.com/56412092/106906938-f948f800-66fd-11eb-90d3-d980270e9df7.png)

When you log in - you will see S2testing that's been assigned to the user. These are S2testing settings:
![image](https://user-images.githubusercontent.com/56412092/106908692-d0296700-66ff-11eb-8bc3-50d9ae48a588.png)

When you click on it, it links to my other server I'm running webmin on. And logs in as a different user using the login with username and password option.

But it stays gray. When you hit the Webmin button next to Dashboard, the correct module appears - My Stream - which is on the slave server (Custom Commands originally).

Now when I change Usertest's module config for the Servers Index (screenshot 1) to be "Can edit servers?" Yes. - Then after clicking on S2testing it opens in a new tab for Usertest. And directly to the module.


My question is can I change where the initial link from Servers Index will point to?
As right now it goes to "https://portal.24lively.com:10000/servers/link.cgi/1611842885/?xnavigation=1" - which stays gray
But it should go straight to the module "https://portal.24lively.com:10000/servers/link.cgi/1611842885/custom/?xnavigation=1"


Thank you in advance for any help
