### ISSUE TITLE
"Download in browser" stopped working in 19.04

### ISSUE THREAD

**Issue by lunarovic** [qooob/authentic-theme#926]
There is this note for Webmin 1.870 and Authentic theme 19.04:
> This is a very large update of the Authentic theme, which likely introduces fun new bugs (we've fixed all the ones we've found over the past couple of months of beta testing, but Webmin is huge), so we need y'all to let us know when you run into UI problems. Specifically, there's a common class of bug where buttons don't work on Webmin pages that have oddly nested forms.

So I decided to try and report a bug.

* What is my Webmin and Authentic version? **1.870** and **19.04**
* What is my server-side OS and its version? **CentOS 7.4.1708**
* What is my client-side OS, browser and its versions? **Windows 10, Chrome 63**
* What are the steps to reproduce the issue?

Basically, "_Download in browser_" functionality seems to be broken in 19.04, wherever it is used. It just hangs and it's loading forever (button spinning and top red line moving), but it will not download the file in browser. Other methods still work fine, so I can workaround it, for example by making a local file and then I would manually download it.

To reproduce, go to for example "_Backup Virtual Servers_" in Virtualmin or "_Backup Configuration Files_" in Webmin, choose "_Download in browser_" and click "_Backup now_".

This is working fine in Authentic 18.49-9.

**Comment by qooob** [comment]
> seems to be broken in 19.04, wherever it is used.

Does it work in Webmin/Upload and Download module?

I will fix it shortly.

**Comment by lunarovic** [comment]
> Does it work in Webmin/Upload and Download module?

Good question. In that module, there is a popup, which is obviously a different method than in the other modules, and then **it works**. (But Chrome first blocks the popup by default unless you allow it for your website, so I had to click the icon for the popup)

**Comment by qooob** [comment]
Yes, without pop-up, I don't think it's possible to make a difference in response, meanwhile.

However, there are ways to make it work using plain XMLHttpRequest and properly handle binary responses. I think this is what I would do but it's not easy, because jQuery AJAX is not able (was not for sure) to do it properly. 

We rely on it at the moment and doing it without popup would be difficult.

**Comment by lunarovic** [comment]
But why did it stop working without the popup in the first place, who knows? :) But don't worry, I don't think there is a great need for doing it without the popup, it's not a crucial function. And for people who use it regularly, they can just click to allow popups from that site, I just tried it and it works great, it instantly opens and closes a tab and it downloads fine.

But could you copy this popup way of downloading to those other modules?

**Comment by qooob** [comment]
Yes, I could and I will for now make it work the same way as in _Upload and Download_ module, only if I don't find better solution to differentiate response type.

Things work completely different on theme 19+.

**Comment by qooob** [comment]
Interesting that I missed the following. The server has a response with _content-disposition_ header and it could be easily controlled.

I will upload the fix in a bit, I would be very appreciate if you could test it.

**Comment by lunarovic** [comment]
I could test, does that require me to install Webmin from scratch?

Also, I just realized that in the File Manager, when you left click on a file to download it, it will use the popup way of downloading, but it will not trigger the popup blocker, because the browser recognizes that you just clicked on something and that you want that to open, that was your intent. The reason it blocks the backup download is because the "Backup now" button does not do it immediately, but after the backup is finished (which is logical), so the browser thinks something is trying to download a file without your consent, because you didn't click anything.

So maybe there could be a way to display a new button "Download now" after the backup is finished. Then the download would not be blocked. But that's too much work for a rare use case, I don't think much people use the "Download in browser" anyway.

**Comment by qooob** [comment]
No, no. You just would have to go to Theme Configuration and hit Force Update from the bottom of the screen, selecting Install Latest Development version.

I'm aware about File Manager. I will just do my best not to come up with fancy stuff and rely on server response. We have already great amount of complexity.

**Comment by lunarovic** [comment]
All right, just tell me when it's ready, I have git installed, so I can force update it.

**Comment by qooob** [comment]
Great. I'm trying to make Dispay In Browser also work when possible.

**Comment by qooob** [comment]
Oh, I've made some great progress!! Now all unsupported links (with out needed container) will be opened to the new tab automatically and those that can be downloaded (`octet-stream` and `application/zip`) will be downloaded without new tab, as they should.

I also fixed it for File Manager!

I was trying to make it for a long time but it seems it's not possible without people's interest. 😉 

Give it a try, now!?!

**Comment by lunarovic** [comment]
YES, I updated theme to dev and download now works without any popups, you are a genius! Great job 🏆

**Comment by qooob** [comment]
😄 I'm glad you enjoy it.

**Comment by lunarovic** [comment]
Here I am again, I hope I am not annoying, I am just trying to help Webmin and Authentic become the best :)

I was digging around a bit, and I found this bug, I don't know if it has to do with the theme or Webmin itself.

Go to "_Backup Configuration Files_", choose any module which is active (don't choose all) and check "Download in browser".

I will get this error:

`Backup failed : Missing or invalid absolute local file`

But strangely, on stable release of 19.04, this happens only the first time for the selected module, then every next time when the same module is selected, it will download (in popup of course). And on this new dev version of 19.04 it will show that error every time and couldn't download.

And I am pretty sure this didn't happen on 1.860 and 18.49-9. But first take a rest 😄

**Comment by qooob** [comment]
It seems there is the same logic applied in Perl as in MySQL/PostgreSQL/Backup.

I will try to find the global solution for it.

**Comment by qooob** [comment]
It took me many hours to figure this out. 🎆 😀 

It will work properly, for sure with the part where download is a progressive output stack.

For regular requests, the third-party library will have to be patched, again.. It's not a problem, though..

I think, I will release a patch for it within an hour after testing it thoroughly.

👷 ...

**Comment by qooob** [comment]
I will also add progress like Mega download have and you will be able to do other things while it's downloading and showing progress in background .. 🏆 

Yay!!

**Comment by qooob** [comment]
Okay, finally finished!

I will have to polish the code before pushing it to the repo, but here is how it's going to look/work?

Example [video-screencast.](https://rostovtsev.ru/pub/src/authentic/19.05/multiple_downloads_progress_example.webm)

Like it? 😆

**Comment by lunarovic** [comment]
This is awesome, well done! 👏 Turning Webmin into a next-generation dashboard :)

**Comment by qooob** [comment]
It's fixed on the latest commit.

There is one thing is still not working, when downloading zip via internal redirect, like in Upload Download module. I will fix it later tonight.

Everything else is working. Please give it a try. ;)

**Comment by fdmgit** [comment]
The browser download with Safari 11.0.2 does not work. Pushing button 'Backup Now' does nothing. 
On Firefox and Chrome it works.

**Comment by fdmgit** [comment]
Forget my last comment. My fault, forgot to clear the cache :-(
It works with Safari 11.0.2 and 11.0.3 (dev edition) as well.

**Comment by lunarovic** [comment]
> Example [video-screencast.](https://rostovtsev.ru/pub/src/authentic/19.05/multiple_downloads_progress_example.webm)

Did you maybe revert this back to the popup / new tab download? Because I experienced that now when I tried it on the latest version (Webmin 1.900, Authentic 19.21, Windows 10, Chrome 70). I used all the default settings on the "Backup virtual servers" page, I just selected one site and I chose "Download in browser".

**Comment by rostovtsev** [comment]
You should have a new tab opening. Check URL bar for the new request to always allow pop-ups from this site.

**Comment by lunarovic** [comment]
Yes, what I'm asking is - is that normal now? Because if you see the video clip you made, it's different - you made it so that new tab isn't necessary for download, and now it's like that in File Manager, but not in "Backup virtual servers".

**Comment by rostovtsev** [comment]
> Yes, what I'm asking is - is that normal now?

Yes, it is. File Manager is an exception. The way it's designed is different from what backups scripted and the way it pushes data. At the moments it's the only best way to do it without redundancy.
