### ISSUE TITLE
Radio button circle not clickable

### ISSUE THREAD

**Issue by lunarovic** [qooob/authentic-theme#927]
There is a small UI issue when a radio button item gets in the next line because there is not enough space (for example, 125% zoom, or a mobile device etc.), and then the radio **circle** isn't clickable anymore. Although you can still click the text belonging to that radio circle and it will select it. By the way, I use 125% zoom and "_Keep slider always visible_" option in the theme, so the space is tight.

You can reproduce this by going to for example "_Backup Virtual Servers_" and then simply zoom in until at least one radio item goes to the next line, like "_Download in browser_". I use Chrome.

**Comment by qooob** [comment]
Yes, I see the cause of the issue.

It seems very easy to fix.

Have a look for the latest commit.
https://github.com/qooob/authentic-theme/commit/481b01bb06d1aac9100a8f163adf0d746db6cbda
