### ISSUE TITLE
Historic System Statistics (webminstats) не обновляет графики

### ISSUE THREAD

**Issue by vladns** [qooob/authentic-theme#929]
Захожу в указаную ветвь, выбираю элемент для просмотра (например ppp0), открывается окно с графиками и всё. Раньше (на старых вебминовских темах) через какое-то время все графики обновлялись в этом окне. Там я не менял настроек, кроме ширины графика.

**Comment by qooob** [comment]
Добрый день,

Все вопросы по данному модули не могут быть исправлены. Необходимо апдейтить сам модуль.

За дополнительной информацией, пожалуйста прочтите:
https://github.com/qooob/authentic-theme/issues/924#issuecomment-351075238
