### ISSUE TITLE
warning  message if noscript or similarmenabled

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#930]
today i was suprised that webmin was no more working in my mobile firefox.
after some testing with older theme versions i saw that the noscript extension was enabled.

i had an exception for webmin configured, this seems to be lost when noscript uodates to the new webextension of firefox.

may be you can place a div with a hint that may be noscript or similar is active and need to be deactivated for webmin. as soon as your first javascriot is running the  div can be removed.

what do you think about the idea?

**Comment by qooob** [comment]
How about some tasty notification?

![screenshot from 2017-12-11 01-09-15](https://user-images.githubusercontent.com/4426533/33810000-199d4a4a-de10-11e7-9fde-7d29db0cae50.png)

**Comment by gnadelwartz** [comment]
looks fine ...

**Comment by qooob** [comment]
Done.

Tell me how it feels?

**Comment by gnadelwartz** [comment]
with noscript enabled no warning is displayed, may be update from within webmin does not fetch the latest patch ... no same when updating from command line

![noscript](https://user-images.githubusercontent.com/4593242/33810687-4ff8199c-de08-11e7-916f-284dcb7232ed.PNG)

**Comment by gnadelwartz** [comment]
i think i know why its not displayed: you used <noscript> tags, but Firefox noscript extension does not disable javascrip.

it filters out bad javascript. so browser does think it's enabled and some simple functions like onclick in a link works but not more danger option's are blocked.
