### ISSUE TITLE
systeminfo causing huge server load

### ISSUE THREAD

**Issue by sle44102** [qooob/authentic-theme#931]
Since update yesterday to webmin 1.870, even with disabling live updates in theme options, i am getting huge server loads.
 
This is on centos 7 latest openvz server.  
can send miniserv.log if you need, but here is excerpt
xxx.xxx.xxx.xxx - root [10/Dec/2017:11:10:26 -0500] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 14955
xxx.xxx.xxx.xxx - root [10/Dec/2017:11:10:27 -0500] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 14956
xxx.xxx.xxx.xxx - root [10/Dec/2017:11:10:28 -0500] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 14956
xxx.xxx.xxx.xxx - root [10/Dec/2017:11:10:29 -0500] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 14955
xxx.xxx.xxx.xxx - root [10/Dec/2017:11:10:34 -0500] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 14955
xxx.xxx.xxx.xxx - root [10/Dec/2017:11:10:36 -0500] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 200 14953

**Comment by sle44102** [comment]
OH should say this only happens after having webmin open in firefox for about 10 min, if you close tab, load drops

**Comment by qooob** [comment]
Hi,

If you open browser's console and run:

```Javascript
settings_side_slider_background_refresh_time
```

What is the output?

**Comment by sle44102** [comment]
Not sure i did it right, but got only "null" as response

**Comment by qooob** [comment]
Can you run in console 

```
settings_side_slider_background_refresh_time = 5
```

Will it stop request for the next 5 minutes?

Besides, what is (if there is) the output of:

```
cat /etc/webmin/authentic-theme/settings.js | grep settings_side_slider_background
```

**Comment by sle44102** [comment]
ok have set ettings_side_slider_background_refresh_time =5 will monitor in htop for overload.

I get nothing from settings.js above, there is no entry matching that.

Wondering if my install got damaged maybe????

**Comment by gnadelwartz** [comment]
I had the same issue and set the refresh time to 3000ms fixed it.

**Comment by qooob** [comment]
If you go to _Webmin Configuration/Background Status Collection_

What is _Collect system status in background?_ value set too?

**Comment by qooob** [comment]
There is already a small bug there, that I see.

**Comment by qooob** [comment]
Oh my God, that is horrible.

If it's set to Never it does crazy things.

**Comment by qooob** [comment]
Creates a load every millisecond.. Did you have it set to Never?

**Comment by sle44102** [comment]
I have it set to never, for many years now since i dont need the stats.

BTW, i have 2 different vps that do the same thing.

Also setting to 5 minutes for the slider above, just delayed it, same thing just happened.  load went above 4 for single core server.

**Comment by qooob** [comment]
If you set it to any value, it will stop doing queries so often.

**Comment by sle44102** [comment]
So it is the webmin background being disabled that is the issue?
Are you saying turn it on and set a value, then can shut off again?  or i will now have to run it at some interval ?

**Comment by qooob** [comment]
Yes 😖 

You can set it to 1000 minutes before I fix it in a bit.

**Comment by sle44102** [comment]
Awesome!  changing it one server now and will report back.
Thanks for you help sir!

**Comment by qooob** [comment]
@sle44102 You are welcome.

I fixed it in the commit above. Go to theme's settings and force upgrade the theme.

**Comment by sle44102** [comment]
O K which options should be set on force update ( I do have git installed)

Check for Authentic Theme updates  Yes             or                            No?
Including patched versions | Yes         or                               No?
and then should i choose stable or beta on button press?    
want to get it right.

**Comment by qooob** [comment]
It's not important which options are set on Force Update.

At this point you should choose Development version.

The options you're asking about is for automatic notifications, and they are self-explanatory.

**Comment by sle44102** [comment]
Thank you!   Done, will monitor and let you know if i have an issue.  
Also, did disable background collection on webmin settings again.
