### ISSUE TITLE
make browser window bigger change sysinfo from two column to one column view

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#932]
I noticed this first on my tablet, but not because of resize but after opening read user mail module.
On desktop in FF and Chrome I can reproduce it this way:

- set Browser window with to something around 1100px and reload webmin
![grafik](https://user-images.githubusercontent.com/4593242/33807553-f0917090-ddd8-11e7-9f60-e675fc9b6c05.png)

- use the left or rigth resize handle and raise with a few pixel e.g. 1120px
![grafik](https://user-images.githubusercontent.com/4593242/33807568-0ccf9084-ddd9-11e7-8f98-b0594f22e433.png)

UPS, changed from two to one column :-O

- reload browser window: two colums again
![grafik](https://user-images.githubusercontent.com/4593242/33807591-75dedb20-ddd9-11e7-9d10-d379b05c9e8c.png)

Not really a bug,  but interesting :-)

**Comment by qooob** [comment]
Kay, hi!

Actually, it's the bug. 

Fixing ..
