### ISSUE TITLE
It is no longer possible to delete logs in webminstats module

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#933]
Steps to reproduce:
1. Go to webminstats module
2. Click on log file.
3. Click on clear.
See the error message that shows up in a screenshot
![screenshot](https://user-images.githubusercontent.com/806758/33808206-073c168a-ddeb-11e7-80aa-d7ae251ad6e6.jpg)

**Comment by qooob** [comment]
Alright, that was theme small issue.

Fixed.

Thank you for reporting! 😉
