### ISSUE TITLE
OpenVPN module no longer working

### ISSUE THREAD

**Issue by SteveHawes** [qooob/authentic-theme#934]
Since upgrading to Webmin 1.87 and Authentic Theme 19.04 I can no longer open the OpenVPN admin in the servers section.

When you select it, it constantly shows the red loading bar at the top of the screen. This is the same as happened with the CSF admin screen in an earlier version.

HOST: Centos 7 Linux 3.10.0-693.11.1.el7.x86_64 on x86_64
Browser: Safari 11.0.1 (13604.3.5) and Chrome 63.0.3239.84 (Official Build) (64-bit)

The error in the browser console for Safari is:
[Error] TypeError: null is not an object (evaluating 'e.match(/<body[^>]*>([\s\S.]*)<\/body>/i)[0]')
	x (bundle.min.js:70:7138)
	success (bundle.min.js:70:2748)
	u (bundle.min.js:2:36985)
	fireWith (bundle.min.js:2:37747)
	r (bundle.min.js:2:75685)
	(anonymous function) (bundle.min.js:2:80532)

And for Chrome it is:
bundle.min.js?19040:70 Uncaught TypeError: Cannot read property '0' of null
    at x (bundle.min.js?19040:70)
    at se.fn.init.e.success (bundle.min.js?19040:70)
    at u (bundle.min.js?19040:2)
    at Object.fireWith [as resolveWith] (bundle.min.js?19040:2)
    at r (bundle.min.js?19040:2)
    at XMLHttpRequest.<anonymous> (bundle.min.js?19040:2)

**Comment by qooob** [comment]
Hi,


This error

```JS
TypeError: null is not an object (evaluating 'e.match(/<body[^>]>([\s\S.])</body>/i)[0]')
```

..means that the module doesn't use Webmin UI library properly.

I will see what I can do.

**Comment by qooob** [comment]
Do you mean Third-party module, from the following link?

```URL
http://www.openit.it/downloads/OpenVPNadmin/openvpn-3.1.wbm.gz
```

**Comment by SteveHawes** [comment]
Yes  - that’s the one.

 

Thanks

Steve

 

 

 

Web:     www.elysiumwebservices.com

Tel:        (+34) 681 25 95 32

**Comment by qooob** [comment]
You can simply right click on the link and use it in separate tab, for now at least.

**Comment by SteveHawes** [comment]
That’s great thanks – gets me out of the hole for the moment ☺

 

Thanks

Steve

 

 

 

Web:     www.elysiumwebservices.com

Tel:        (+34) 681 25 95 32

**Comment by qooob** [comment]
Alright, I took a closer look.

It's interesting why third-party module's developers expect things just work, when not [following basic rules](https://doxfer.webmin.com/Webmin/Module_Development).

Please contact the developer and ask him/her to fix `openvpn/index.cgi`, to make sure that the footer is included. Footer is kinda important, it contains the required minimum, which is closing `</body>` and `</html>` tags. 😉 Regex that extracts parts of HTML has unsatisfied expectations, and fails.

You can simply edit `openvpn/index.cgi` and add at the very bottom:

```Perl
ui_print_footer("/", $text{'index'});
```

Unfortunately, it's not the only issue with this module. There are other issues but at least mentioned fix will make things work.

**Comment by SteveHawes** [comment]
Many thanks for looking into this issue and finding a fix for us. I will get in touch with the developer and pass on the problems.

 

Thanks

Steve
