### ISSUE TITLE
Theme: Encoding issue on System Information page

### ISSUE THREAD

**Issue by alexnas77** [qooob/authentic-theme#935]
Greetings.
You have a disruption of the character encoding in the marked areas on the screenshot.
And they are becoming more.
I ask you to fix them.
![2017-12-11_120708](https://user-images.githubusercontent.com/18441119/33823690-05b8b19c-de6d-11e7-8904-0ed77965a497.jpg)

**Comment by alexnas77** [comment]
It only affects on XHR.
https://domain.ru:10000/stats.cgi?xhr-stats=general
On window.focus() encoding is OK.

**Comment by qooob** [comment]
Dupe:
https://github.com/qooob/authentic-theme/issues/921

**Comment by alexnas77** [comment]
XHR has been fixed. I see.
But Cron menu item in System group still broken.

**Comment by qooob** [comment]
Cron label will be fixed with next Webmin release.

**Comment by alexnas77** [comment]
There is one more thing.
Google Chrome Javascript console 
bundle.js:46270 Refused to create a worker from 'blob:https://domain.ru:10000/6fe6c2b3-a02c-4b03-afd5-0f208bc6bd42' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by alexnas77** [comment]
"Cron label will be fixed with next Webmin release."
Thanks.
It was annoying.
