### ISSUE TITLE
System and Server Status module - unable to delete monitor

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#937]
Steps to reproduce:
1. Open System and Servver Status monitor module
2. Add any monitor (I added SSD wearout).
3. Try to delete monitor (either from the monitor page itself, or by selecting it in main view and deleting it.

Result:
The monitor is not deleted.

**Comment by qooob** [comment]
Yes, my previous Webminstats patch breaks general Webmin actions.

Unrolling ..

Thanks.

**Comment by matrix200** [comment]
How can I fetch the rolled back version?
I tried the usual force update and the bug is still there.

**Comment by qooob** [comment]
Force is upgrade and then reload browsers cache.

**Comment by matrix200** [comment]
After another update it worked.
Thanks.
