### ISSUE TITLE
Display virtual memory in dashboard only if swap is used

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#939]
I actually wrote a small patch myself which I would like to contribute.
            if ( nice_size(($m[2]) * 1000) > 0 )
            {
                $virtual_memory =
                    &Atext('body_used', nice_size(($m[2]) * 1000), nice_size(($m[2] - $m[3]) * 1000));
            }

instead of 
                $virtual_memory =
                    &Atext('body_used', nice_size(($m[2]) * 1000), nice_size(($m[2] - $m[3]) * 1000));
in the authentic-lib.pm file.

**Comment by qooob** [comment]
Thank you for your effort but unfortunately, it will not be possible to add it for all users.

**Comment by matrix200** [comment]
I understand that you are planning to turn the dashboard screen into a collection of widgets, so perhaps it will be possible to turn individual items on and off?

**Comment by qooob** [comment]
Oh, yeah, and that is very likely. I'm in.

**Comment by matrix200** [comment]
Then I guess, this is the answer to my question.
I will keep my fix in the file in the meantime, until you make it possible to turn the virtual memory  display off.
The thing is though, your code is smart enough to not display the virtual memory dial on my system (since I have no swap file enabled), so I thought having the same check on the text display made sense.
Anyway an option to turn it off manually is just as good :+1:
