### ISSUE TITLE
Request: fixed top navigation

### ISSUE THREAD

**Issue by Goeny** [qooob/authentic-theme#94]
First of all, i love this theme. It is really clean and works pretty good. There is, however, 1 thing i would like to see a bit different.

The navigation menu on the left is sometimes a bit "messy".
When, in example, in virtualmin menu you have unfolded a certain section the menu shows: some area's folded, an area unfolded, some areas folded, a searchbar, again some folded area's, system information, user info, etc.

I think it would be nice to see a fixed top navigation with the searchbar integrated, switching to virtualmin/webmin/cloudmin in there, select menu for virtual server choice and active virtual server options in there.

I don't know how difficult it would be to create this and if it's even realistic.
In my mind it just would be a good idea.

Regards,

Goeny

**Comment by qooob** [comment]
Uff.. Sorry pal, I'm afraid I'm not completely understood what you meant!

Alright, do you want to see search bar and select for switching virtual servers same fixed as _Webmin/Virtualmin/Cloudmin_ switches (which are at the very top and which are fixed already)?

**Comment by Goeny** [comment]
Sorry if i was not clear enough.. :)

Right now the fixed part is only in the left menu.
It would be nice if there was a fixed navbar on top of the whole screen with those options in there.

**Comment by qooob** [comment]
With which options??

**Comment by qooob** [comment]
With options from left menu?

**Comment by Goeny** [comment]
Yes, I meant the first few options regarding the active virtual server. 
I.e. Create virtual server, edit virtual server, edit user, install scripts, etc.
And Offcourse the search bar. 
This way i think the left menu will be cleaner.

**Comment by qooob** [comment]
I remotely agree with search bar being fixed - that is great idea. What is the point of all other complexity, like fixed menu for currently selected virtual server? What is going to happen on small devices?

**Comment by Goeny** [comment]
I'm not sure what will happen on small devices. ;-)
It think it would be a bit cleaner if it is found under 1 menu. It might as well be an independant fold out menu in the sidepanel. Maybe with another color? Right now it is just a long list of options with the searchbar in the middle.

![webminsidebar](https://cloud.githubusercontent.com/assets/3872395/6080261/aae04f68-ae0f-11e4-9a5c-4c820f54732f.png)

**Comment by 7starsone** [comment]
"it is just a long list of options with the searchbar in the middle." here I can agree... eg. the second part could be entirely collapsed...or could be placed on top with a modern dropdown (if you mean this...)

**Comment by Goeny** [comment]
Yes, something like that..
The second part in a nice dropdown would be a good idea! Just something to "break up the list".

**Comment by qooob** [comment]
Ohh. You mean first 6 or 7 links, like Create, Edit Virtual server,Edit User, Edit Databases and etc put under one menu?

**Comment by Goeny** [comment]
Exactly!
But any other way to make it a bit cleaner would be good aswell.
I have no idea how webmin or your theme is coded, so i don't know how hard it would be to create something like that.
