### ISSUE TITLE
File Manager: Stays grey and blocked after upload

### ISSUE THREAD

**Issue by Nixellion** [qooob/authentic-theme#942]
Whenever I upload any file with File Manager it stays dark\greyed out and blocked\locked, ie - I can't click anything there. So I have to reload webmin and get into File Manager again to upload any other file.

**Comment by fdmgit** [comment]
@Nixellion 

see https://github.com/qooob/authentic-theme/issues/903

**Comment by qooob** [comment]
Dupe. #903

**Comment by fdmgit** [comment]
@qooob 

Any improvements on this issue ?
The issue makes work annoying
