### ISSUE TITLE
Cosmetic issue in nic diagnostics module due to css styling

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#943]
Steps to reproduce:
1. Install nic diagnostics module.
2. Open it.
Result:
The table shows the last row differently from others due to css styling that adds 4 pixels padding on the last table row everywhere except mysql and postgresql  in bundle.min.css
So I have added the following in the file to resolve it:
Instead of body:not(.mysql):not(.postgresql)
I put body:not(.mysql):not(.postgresql):not(.nicdiag)

And a general question, why did you put that 4 pixel padding to begin with and even added "important!" in the comments?

**Comment by qooob** [comment]
I can't download the module.

**Comment by qooob** [comment]
Strange, now this link works:

```
http://prdownloads.sf.net/nicdiag/nicdiag-2.0.wbm
```
Checking..

**Comment by qooob** [comment]
It requires some additional actions.

```
/sbin/ethtool version is , minimum version required is 1.8
```

This issue is postponed to 19.06

**Comment by matrix200** [comment]
I have fixed it in the meantime as described in my report so no pressure :)
To be honest, I also kind of rewrote it to include some fields that were missing (such as connection speed) and removed some fields which I found useless such as firmware and driver version.

**Comment by qooob** [comment]
Once it's working for you with `:not(.nicdiag)` great. I will added it to the next commit.
