### ISSUE TITLE
Drive stat error not viewable.

### ISSUE THREAD

**Issue by mspecbmw** [qooob/authentic-theme#946]
On main stats page if there are any errors coming through from smart stats you cannot view them unless you select select the area with the mouse.
Changing theme colours makes no difference.
Not really an issue but just something that I have noticed. 
![image](https://user-images.githubusercontent.com/7828510/34067579-991f6b04-e28e-11e7-986b-ef76acf57645.png)

**Comment by qooob** [comment]
Thank you for reporting.

Could you share complete HTML on this element?

Call for context-menu and instect the element, then copy its outer HTML.

**Comment by mspecbmw** [comment]
Hope this is what you were after

`<div class="right-side-tabs-toggler" data-background-style="grey" style="right: 0px;">  		  	<button type="button" class="btn btn-primary btn-menu-toggler" style="padding-left: 6px; padding-right: 5px;">  		  		<span class="badge badge-danger hidden">0</span>  		  		<i class="fa fa-fw fa-lg fa-bell"></i>  		  	</button>  		  </div>`

**Comment by qooob** [comment]
@mspecbmw It's wrong. Could you make sure the the element contains:

```
<span data-id="sysinfo_hdd_temperature"> .. and your number 31 and other data.
```

**Comment by mspecbmw** [comment]
`<tr>
<td style="width:20%;"><strong>Drive temperatures</strong></td>
<td style="width:30%;"><span data-id="sysinfo_hdd_temperature"><span class="badge-custom badge-drivestatus bg-semi-transparent" data-stats="drive" style="margin-right:3px; margin-bottom: 3px">sda: 28°C </span>&nbsp;<span class="badge-custom badge-drivestatus bg-semi-transparent" data-stats="drive" style="margin-right:3px; margin-bottom: 3px">sdb: 26°C &nbsp;&nbsp;<span class="label label-warning bg-warning" style="vertical-align: middle; max-height: 11px; display: inline-block; line-height: 9px;">127 errors!</span></span>&nbsp;</span></td>
<td style="width:15%;"><strong>System uptime</strong></td>
<td style="width:35%;"><span data-id="sysinfo_uptime"><a href="/init"></a>3 days, 18 hours, 42 minutes</span></td>
</tr>`

Ubuntu Linux 17.04
Webmin version	1.870 	Theme version	Authentic Theme 19.04
Kernel and CPU	Linux 4.10.0-42-generic on x86_64

**Comment by qooob** [comment]
Fixed.

Thanks for reporting.
