### ISSUE TITLE
Webmin > Servers > BIND DNS Server

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#948]
When you click "**Apply Configuration**" either inside a zone, or at the main screen, a "blank screen" is produced on the right side of the page. Same thing happens when you click "**Apply Zone**" from inside a zone.

Authentic Theme: 19.04 / Webmin: 1.870 / Usermin: 1.720 / Virtualmin: 6.02

**Comment by qooob** [comment]
This bug was fixed few days ago and going to 19.05.

You can Force Upgrade to development version and clear cache to make it work.

**Comment by tpnsolutions** [comment]
Cheers!
