### ISSUE TITLE
Menu positions sometimes too small

### ISSUE THREAD

**Issue by majk-p** [qooob/authentic-theme#95]
While exploring the menu I've found menu position looking like this:
![webmin-max-height](https://cloud.githubusercontent.com/assets/7260594/6076261/4f81a582-ade1-11e4-88fb-e44190fef6e4.png)
By inspecting the element I've found out that `max-height` property is set to `32px` only:

    #sidebar ul.sub > li:not(.menu-container) {
        max-height: 32px;
        padding-left: 20px;
    }

My suggestion is changing it to at least 42px, which would eliminate such situations even with longer strings.

**Comment by qooob** [comment]
I have already fixed that in version 9.1.0 - which is out in couple of days! ;) Thank you for noticing!
