### ISSUE TITLE
Usermin > Delete Spam

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#953]
I just installed version 19.05 and while it addresses many pressing issues with 19.04, I've discovered that when you press "Delete Spam" button on either the message list, or within a message, it triggers a new window to be launched instead of changing the right panel of the current window.

I've not checked other buttons in the UI, but I suspect it may affect other buttons so might want to check just in case.

**Comment by qooob** [comment]
Hi, Peter. It's not going to affect other buttons. It's just for those specifically.

It will be changed on mail rework completely.
