### ISSUE TITLE
disc and cpu usage not correct on NAS

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#954]
I managed to install webmin on synology NAS.

CPU and disc usage is not displayed correct:
![grafik](https://user-images.githubusercontent.com/4593242/34271095-1c43ef8c-e68b-11e7-8057-7b3e2462e507.png)

```
bash-4.3# df
Filesystem      1K-blocks      Used  Available Use% Mounted on
/dev/root         2451064    963024    1385640  42% /
none               254900         4     254896   1% /dev
/tmp               256796       512     256284   1% /tmp
/run               256796      2016     254780   1% /run
/dev/shm           256796         4     256792   1% /dev/shm
/dev/vg1000/lv 3840953648 471637936 3369213312  13% /volume1
```
what command are you using to get CPU usage?

![grafik](https://user-images.githubusercontent.com/4593242/34271340-32606524-e68c-11e7-90b2-34d99f5ee005.png)

**Comment by qooob** [comment]
Kay, hi.

Looks like I made an error when doing calculations. Just moment.

Danke.

**Comment by qooob** [comment]
Give it a try. Correct now?

**Comment by qooob** [comment]
No, it's incorrect.

**Comment by gnadelwartz** [comment]
yes :-)

**Comment by qooob** [comment]
But it should be right, actually. Commit technically correct but shows incorrect data.

I need to contact Jamie about it, because [`mount-lib.pl` documented](https://github.com/webmin/webmin/blob/master/mount/mount-lib.pl#L295-L380) to return total and free and 1 and second param.

Numbers that say in _**Lokale HDD-**_ are also incorrect?

**Comment by qooob** [comment]
Technically my patch is correct. I let @jcameron know.

**Comment by gnadelwartz** [comment]
yes ist also incorrect, I have ~3.2 TB free

**Comment by qooob** [comment]
Can you switch to Gray Theme and take a look to double check the numbers?

**Comment by gnadelwartz** [comment]
![grafik](https://user-images.githubusercontent.com/4593242/34272479-ba514670-e690-11e7-92eb-bcab6d3cf2cd.png)

**Comment by qooob** [comment]
Also wrong? Are you sure?

**Comment by gnadelwartz** [comment]
```
bash-4.3# df
Filesystem      1K-blocks      Used  Available Use% Mounted on
/dev/root         2451064    963636    1385028  42% /
none               254900         4     254896   1% /dev
/tmp               256796       512     256284   1% /tmp
/run               256796      2016     254780   1% /run
/dev/shm           256796         4     256792   1% /dev/shm
/dev/vg1000/lv 3840953648 484462900 3356388348  13% /volume1
```
![grafik](https://user-images.githubusercontent.com/4593242/34272548-021c290c-e691-11e7-8104-7feb7a6219b2.png)

**Comment by gnadelwartz** [comment]
volume1 consits of 2x4GB HD as RAID1 (mirror)

**Comment by qooob** [comment]
What is the output of:

```
findmnt -r
```

**Comment by gnadelwartz** [comment]
does not exist on NAS

**Comment by qooob** [comment]
It's not the theme issue. You want me to solve it?  Jamie is more efficient on this! 😉

**Comment by gnadelwartz** [comment]
I open an issue for webmin
