### ISSUE TITLE
Issue with box selection in Shorewall module

### ISSUE THREAD

**Issue by BarryHavenga** [qooob/authentic-theme#957]
Before posting an issue, please search through closed/opened issues to make sure that the answer to your questions hasn't been answered already.

Please make sure that you have latest theme (19.05) and Webmin (1.870) versions installed.

Provide the following information:
* What is your server-side OS and its version? Ubuntu Server 17.10
* What is your client-side OS, browser and its versions? KDE-Neon 16.04 Firefox 57.0.1 (I checked in Chrome - same problem)
* What are the steps to reproduce the issue? 1) Invoke Shorewall Firewall module 2) Change a setting (any setting) 3) Return to list of tables 4) Select "Check Firewall" or any other selection box on the lower left hand side and nothing happens.  I changed theme and the module worked so it is definitely a theme issue.

Regards

**Comment by qooob** [comment]
Thank you letting me know.

This is Perl issue. We'll fix it.

**Comment by BarryHavenga** [comment]
Hi there.


Happy New Year


JTLYK I tried Authentic again and there are still problems.


Regards


Barry

**Comment by qooob** [comment]
You need to apply yesterday's patch.
