### ISSUE TITLE
Theme continually requests stats.cgi even when not on the system information page

### ISSUE THREAD

**Issue by jcameron** [qooob/authentic-theme#958]
I see this in the logs, even when I'm on other pages in Virtualmin : 

```
104.132.1.98 - root [21/Dec/2017:17:04:32 -0800] "GET /stats.cgi?xhr-stats=general HTTP/1.1" 200 200
104.132.1.98 - root [21/Dec/2017:17:04:35 -0800] "GET /stats.cgi?xhr-stats=general HTTP/1.1" 200 200
```

is that needed?

**Comment by qooob** [comment]
Hi, Jamie.

Yes, it's needed for updating Information for Side slider. Some people have it always visible and it shows actual data.

I promised to make it work using buffered header. Didn't have a chance to take a closer look yet.

Will do later today.

**Comment by qooob** [comment]
In case you know how to quickly make it return data by keeping connection opened using buffered header function, please make a commit and I will add this to 19.06 release as soon as possible.

**Comment by jcameron** [comment]
Ok, thanks! That makes sense ..

**Comment by gnadelwartz** [comment]
shouldn't  https://github.com/qooob/authentic-theme/commit/c879246584595bc10753ecadd355f4e7de781c8b also fix Jamie's complaint?

**Comment by qooob** [comment]
No, it needs more changes.

**Comment by qooob** [comment]
We'll continue on the email. This issue particularly is resolved.
