### ISSUE TITLE
No option to create sub-servers in virtualmin

### ISSUE THREAD

**Issue by quayfee** [qooob/authentic-theme#96]
Firstly, great theme, much nicer to work with. But there is a show stopping issue (unless I'm being toally inept). When creating a new virtual host in virtualmin, there is no longer an option to create a sub-server or aliases. Screen grab of the missing options below:
![servertypes](https://cloud.githubusercontent.com/assets/1534026/6080504/dfc47e4e-ae09-11e4-838f-db4ae1dcff64.jpg)

It would be great to see this included in the next update :)

Many thanks

**Comment by webdo** [comment]
You are totally right, thoses options are not there anymore, just noticed it!
Also i miss the menu where we could start/stop all services (apache, mysql, proftpd, etc) in virtualmin System informations, would it be possible to add it back?

**Comment by 7starsone** [comment]
"would it be possible to add it back?" hope so soon ;-)

**Comment by qooob** [comment]
Thanks! 
1. About 'missing' options when creating sub-server, alias and etc. This issue should be addressed to Webmin/Virtulamin developers. The thing is that the menu now is generated using certain mechanism that is provided not by theme.
2. Status and Quotas will be added the release after 9.1.0. If lucky 9.1.0 will get this but I can't promise this.

**Comment by webdo** [comment]
For the missing options, its not when creating sub-server, alias and etc, we just can't create them because there is nowhere to click to create alias, sub-server etc, we can only make nornal servers, it is theme-side since we can make it with other themes..

For the status and quotas thank you! :)

**Comment by qooob** [comment]
My, bad, sorry - it's there:

![screenshot from 2015-02-06 18 43 03](https://cloud.githubusercontent.com/assets/4426533/6082189/4b091a04-ae30-11e4-9f75-f18f0b28d04b.png)

**Comment by webdo** [comment]
Ok in fact if we change the server it will appear.

**Comment by qooob** [comment]
Ok, and this is a bug.. Will try fixing it..

**Comment by quayfee** [comment]
Ah, yes, It was coincidence that i was using the first virtual host in the list.

Thanks qooob! great stuff. Thanks for responding so quickly too!

**Comment by webdo** [comment]
I forgot to thank you for all the work you put in this theme, its awesome, its give a new life to webmin/virtualmin! Thank you very much!

**Comment by qooob** [comment]
@webdo, @quayfee You are welcome, my friends!

Thanks for commenting and finding bugs.

Regards,
Ilia

**Comment by qooob** [comment]
@webdo Quota and other additional system information is added in 9.5.0. Enjoy! ;)
