### ISSUE TITLE
Message: Can’t establish a connection to the server at ...

### ISSUE THREAD

**Issue by 1manfactory** [qooob/authentic-theme#960]
I always leave a tab open in the background.

Since the last theme update I get this message pop up

> Can’t establish a connection to the server at <mymachinename>

This NEVER happened before.

**Comment by qooob** [comment]
In case connection breaks, it pops up. When connection is back, you should see green notice and on the tab focus it will disappear.

I never get this error on the other side (I have stable connection though)

**Comment by fdmgit** [comment]
I have from time to time the same effect as 1manfactory. 
I get the red notice that the connection is lost and after a while the green notice that the connection is established. 

I have definitely a stable (100 mb/s) WAN connection to the server.

**Comment by gnadelwartz** [comment]
i had this today also on my local nas, from my guess it happens when my nas was syncing big files in background and responds not fast enough.

**Comment by gnadelwartz** [comment]
BTW: is this message triggered by realtime stats?

**Comment by qooob** [comment]
This message would be triggered by any connection error. Any error would case it.

What do you propose, come on, share your thoughts.

**Comment by gnadelwartz** [comment]
IHMO it should only displayed if multiple errors accour,eg. because internet connection is lost.

**Comment by qooob** [comment]
Hm.. Then I need to differentiate human calls and programmatic.

**Comment by qooob** [comment]
Maybe make it optional?

**Comment by gnadelwartz** [comment]
this was why i asked about realtime stats, these should not trigger the message, optional would be a simple solution. or a checkbox/button in the message box  "do not display again (in current session)" ...

**Comment by gnadelwartz** [comment]
btw. does background collection  of relatime stats also happen when tab/window is hidden?

I use `window.requestAnimationFrame()` to stop execution of periodic events when tab/window is hidden. `requestAnimationFrame()`calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life.
https://developer.mozilla.org/de/docs/Web/API/window/requestAnimationFrame

**Comment by qooob** [comment]
I really should consider stop gathering collecting data on window blur. I should've thought about it right away, strange that I didn't. 

Thank you.

**Comment by qooob** [comment]
Damn it, this absolute must have.

What change I've made!?

1. Live stats will only run when the tab is focused;
2. Connection error will only happen on human's interraction.

Perfect! Thanks for your advices! 😀

**Comment by 1manfactory** [comment]
Hello.
Sorry, I can't follow your dialog.
Is this a bug or not?
Will ist be fixed or not?
Thanks

**Comment by qooob** [comment]
It's been fixed. Please update to the latest version of the theme.

It will not pop up automatically. It will only be shown in case human interaction happens (you make a click) and network is not available. In all other cases it won't be shown.

**Comment by 1manfactory** [comment]
Ok. Just manually uploaded to the newest version.
Thank you SO SO SO much for your afford and hart work - even on christmas.

**Comment by qooob** [comment]
:) You are welcome. I love doing it.
