### ISSUE TITLE
Add a tooltip on hover for long domains on sidebar’s virtual server dropdown selection

### ISSUE THREAD

**Issue by alexbogias** [qooob/authentic-theme#961]
Would be great if you can add a tooltip on hover for long domain names that gets a (...) on sidebar’s virtual server dropdown selection

**Comment by qooob** [comment]
Hi,

It's a very good idea. I have fixed it in both the theme and Vitualmin core.

https://github.com/qooob/authentic-theme/commit/55e7f3bb4438d7ee22a5a6f00362e2ef6e2b8f20
https://github.com/virtualmin/virtualmin-gpl/commit/6eff8539dd8a34e9b52f9221e138954afc29d9f6

**Comment by alexbogias** [comment]
Sorry for bothering again but I dont see it in the latests updates...
Virtualmin version: 6.02
Theme version: Authentic Theme 19.08

**Comment by qooob** [comment]
You don't see it because it's part of the Virtualmin update itself.

**Comment by qooob** [comment]
You could patch the file manually  for now to make it work.

**Comment by alexbogias** [comment]
Oh ok. I ll wait..
Thanks @qooob

**Comment by qooob** [comment]
For now, you could also go to _Virtualin Configuration/User Interface Settings_ and set `Maximum number of domains to display` to 1, for example. Then this feature should work right after saving configuration and reloading left menu.

**Comment by alexbogias** [comment]
@qooob WOW! Thanks a lot again... Didnt know that! The next option Shorten long domain names at the "End" did the job as those were subdomains.

**Comment by qooob** [comment]
You're welcome.
