### ISSUE TITLE
Issue on File Manager

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#962]
Hello,
I don't know what's the trigger in this case, it seems random or a question of time on the page...
I should inspect the code but I have no time at the moment.

If you have minimized files on bottom, often it returns a modal window which warns you that unsaved changes will be lost (even if you didn't change anything into the files) and if you click "Continue" but maybe even "Cancel" it deletes the minimized files.

Once again, at the moment I can't find the trigger for this situation, but for sure it's not an ideal situation, so the minimized files should be stored there on the bottom regardless of the browsed folders and any action on the page....unless the user decides to definitely close them, as usual.

Thank you

**Comment by qooob** [comment]
Yes, I have a clue why this might be happening. Only it doesn't delete files but removes collapseable panels.

**Comment by 7starsone** [comment]
"deletes the minimized files" maybe not the right term, but yes...it just removes them from there, that's it...

Thanks and Merry Christmas! 😄

**Comment by qooob** [comment]
Merry Christmas! 😉

**Comment by qooob** [comment]
I took a closer look. Do you think that edited files should stay intact while navigating away from File Manager? Why?

I don't think it's very good idea. The warning message tells you, in case there are unsaved files, that if you navigate way it would be closed/lost.

I find that everything works fine and as expected.

**Comment by 7starsone** [comment]
No, I stay on File Manager, I don't go away...
and often it returns that window and if you click on "Continue" it removes the minimized files and even it reloads the File Manager completely. So, I think that's not good... I don't want to go away from File Manager for sure, otherwise I would've written exactly that 😉 
thanks

**Comment by 7starsone** [comment]
This happens on Chrome, not tried other browsers....

**Comment by qooob** [comment]
When does this message shows up after? It might only show up if you try to load some link, like you click on something in navigation menu or in side slider.

In case you click around File Manager it shoudln't show up. What exactly do you do?

**Comment by 7starsone** [comment]
I just browse folders, nothing else...hence why I wrote that I don't know the cause... I have an extension called "Distill Web Monitor" but it wasn't ON this page, anyway I disable this and try again...even if I think that's not related

**Comment by 7starsone** [comment]
ok, extension disabled... then I just browse folder and again...
![filemanager](https://s9.postimg.org/6v8bewimn/nodistill.jpg)

**Comment by 7starsone** [comment]
I have some opened tabs, so not just one tab, if this helps...

**Comment by 7starsone** [comment]
ok, on File Manager i have the js console full of errors....

above all
`Cannot read property 'replace' of undefined`
also...
`"Found 2 elements with non-unique id #name_domains...."` index.cgi
then **#name_etc**, **#name_fcgi-bin**...
and many more like that, even **4288 log entries are not shown**

there's something wrong, please check

**Comment by 7starsone** [comment]
also some
`Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED` 10000/index.cgi/?**xhr-error**=1
or 
`Failed to load resource: net::ERR_NAME_NOT_RESOLVED` 10000/index.cgi/?**xhr-check**=1

**Comment by qooob** [comment]
Okay, that's more helpful. I'll take a look tomorrow.

**Comment by qooob** [comment]
I had a thought while watching the movie. What is the complete path that you're opening when this error comes up? Any or some fancy one?

About non-unique id issue, well it's harmless and happened quite a bit around different moduels. Chrome started to produce those messages couple of releases ago.

**Comment by qooob** [comment]
Oh, by the way. Does this also happens with the very latest 19.06? Could you Force Upgrade?

**Comment by 7starsone** [comment]
yes, it happens again on 19.06...

for a while it's ok, then I just click on a folder... that window appears
but, at this point, I don't see any error on console...because at first i cleared the log

so, that window appears even if no error on log

**Comment by qooob** [comment]
What is the folder name and its path?

**Comment by 7starsone** [comment]
that's not relevant...it doesn't happen on a specific folder

**Comment by qooob** [comment]
When I open a file, edit it, don't save it and then collapse the editor's window, I can easily navigate through the folders without any warning messages.

Isn't the same for you?

Did you try incognito mode?

**Comment by 7starsone** [comment]
on incognito it seems that doesn't happen, on normal it happens even with all the extensions **disabled**. Also opened a new tab in Chrome and it behaves like that again. Why am I forced to use incognito?

**Comment by qooob** [comment]
You can try to go to settings and Clear Cache? Maybe something go stuck since transaction from 18 branch.

Have you been using this browser's installation for a long time or it's fresh new? (Like its configuration and cache data)

**Comment by 7starsone** [comment]
cleared the cache and now it doesn't... if it happens again I'll let you know, but this way is difficult to find the cause...from 18 I find it impossible, I recently cleared the cache for sure

**Comment by 7starsone** [comment]
update: I left the Chrome tab opened... then after two hours, it did it again...
so, is it a cookie issue? can you fix it when possible?

**Comment by qooob** [comment]
There are no cookies bug I will focus on finding the cause of the issue.

**Comment by qooob** [comment]
Go the error. Will fix in a bit. 

Thanks!

**Comment by qooob** [comment]
I see this source of the problem. Fixing ..
