### ISSUE TITLE
filemanger lost in space, what dir I'm in??

### ISSUE THREAD

**Issue by gnadelwarty** [qooob/authentic-theme#963]
Hi Ilia, even its holy season we are both working on webmin :-)

not really a problem, but a minor issue. sometimes I open the filemanager and I don't know what dir I opening, beacuse if I'm in the root dir no "/" is shown:
![image](https://user-images.githubusercontent.com/28775666/34341725-f271d4ce-e99d-11e7-91bb-ef3cf8ff749d.png)

if I start travel down  it's more clear:
![image](https://user-images.githubusercontent.com/28775666/34341737-17f883a0-e99e-11e7-8d2a-4c43fd5833ad.png)

same if I'm in my home dir in usermin:
![image](https://user-images.githubusercontent.com/28775666/34341746-5c0cd668-e99e-11e7-9e3c-e6f8b2c7d3d0.png)

it's not obvious to me that the people icon stays for my home dir ... may be diplay here @ least the username "kay/"

may be I'm to much uesed to Linux, but I hate It to not know which real path I'm in :-)

**Comment by qooob** [comment]
I think it would create more confusion for others. It's easy to have root partition `/` identified by number of specific folders in it, same for user login.

It's more like Desktop file-managers, that display an icon for root and home partitions.

You could always use theme's extensions to hack it the way you want?

**Comment by gnadelwarty** [comment]
may be you are rigth and the path is displayed i n the window title, but nevertheless the root  icon looks more like a printer than the server root :-)
![image](https://user-images.githubusercontent.com/28775666/34342009-fced38a2-e9a3-11e7-851f-575f47796fa3.png)

may be this is whats confusion me ...

**Comment by qooob** [comment]
Haha. 😆 Okay, what icon do you recommend?

**Comment by gnadelwarty** [comment]
from font awsome? may be one of these:
![image](https://user-images.githubusercontent.com/28775666/34342149-801960b8-e9a7-11e7-85cf-3e7c183c3edd.png)
in combination with a slash:
![image](https://user-images.githubusercontent.com/28775666/34342232-76ba8662-e9a9-11e7-8d7a-ffd2969aeb1e.png)

or for home dir:
![image](https://user-images.githubusercontent.com/28775666/34342190-80a2962a-e9a8-11e7-9f73-3a47ac8c1e4b.png)

**Comment by qooob** [comment]
Okay, I'll take a look.

**Comment by gnadelwarty** [comment]
not urget :-)

**Comment by swelljoe** [comment]
I don't like the TV icon for root, but fa-home for home is good. I think a computer icon is reasonable for root, as that's what Gnome uses; though I can see how the current icon might be ambiguous (but so is the default icon in Gnome on Fedora). I think Windows uses something similar, too, maybe? I don't use it enough to know for sure.

**Comment by gnadelwarty** [comment]
windows: 
![image](https://user-images.githubusercontent.com/28775666/34343072-f1f4daf2-e9c3-11e7-841c-8f674b3566eb.png)
![image](https://user-images.githubusercontent.com/28775666/34343094-744213a8-e9c4-11e7-8d33-1278c0f3af93.png)


ubuntu:
![image](https://user-images.githubusercontent.com/28775666/34343084-488685e6-e9c4-11e7-8ab0-bd9b552aa675.png)
![image](https://user-images.githubusercontent.com/28775666/34343092-59f1ecc6-e9c4-11e7-8b8f-983bfb69cc36.png)

computer logo is a screen, filesystem logo is a hard disc

**Comment by qooob** [comment]
Honestly, both of them are ridiculous. 

We should come up with something better.

Home for user sounds great.

I should find better icon for root, so it doesn't look like printer or scanner! 😂

**Comment by qooob** [comment]
Try latest commit.

**Comment by gnadelwartz** [comment]
looks great.

BTW, does it make sense to display .files and .dirs dimmed/lighter? to reflect they are hidden files/dirs by ls and only shown with ls -l or ll

**Comment by qooob** [comment]
Maybe.. :)

**Comment by fdmgit** [comment]
The new icon is not visible under Safari. Firefox is OK.

**Comment by qooob** [comment]
Cleared cache?

**Comment by fdmgit** [comment]
forgot, arggh. It's working
