### ISSUE TITLE
usermin Issue with theme

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#964]
since 19.06 the user info in usermin every entry is shown in two lines, wasting much space:
![image](https://user-images.githubusercontent.com/4593242/34361812-128bb308-ea6e-11e7-9747-201ddc0f7762.png)

If I make the browser full screen ist shown in one line as before:
![image](https://user-images.githubusercontent.com/4593242/34361838-5093df0e-ea6e-11e7-915f-fd1be2eb6a22.png)
 
I guess it 's related to  your 2 colums layout for webmin system info ...

**Comment by qooob** [comment]
Yes, true.

Will fix it tomorrow.

Thanks.

**Comment by qooob** [comment]
It will be fixed in up-coming release.
