### ISSUE TITLE
Perl error on usermin login with authentic theme

### ISSUE THREAD

**Issue by davidbenucci** [qooob/authentic-theme#965]
When I try to login to usermin, I get this error:
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.730 Date: Wed, 27 Dec 2017 19:48:40 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Undefined subroutine &main::embed_noscript called at /usr/local/usermin-1.730/authentic-theme/authentic-lib.pm line 1693.
How can I fix this?
In this [post](https://www.virtualmin.com/node/54734) it mentioned the bug was fixed in the latest version but I still encounter it in 19.06. Now I downloaded the gz and installed it I cannot delete the theme from usermin configuration...

**Comment by davidbenucci** [comment]
I solved delete usermin module and reinstall via deb repository. Now everything works well!

**Comment by qooob** [comment]
You could pkill miniserv and then restart Webmin and Usermin.

We'll fix this on the next Webmin/Usermin releases.
