### ISSUE TITLE
try install downloaded 19.06 and see: ": Module authentic-theme requires Webmin version 1.871 or above".

### ISSUE THREAD

**Issue by ChiefPilot14** [qooob/authentic-theme#966]
Hello!
My theme is 19.05 and Webmin 1.870. I try install downloaded 19.06 and see: ": Module authentic-theme requires Webmin version 1.871 or above". Please, help me.

Server operating system: Ubuntu Linux 16.04.3
Client operating system: Windows 10 build 1709
Brovser: Opera 49.0.2725.64 (PGO)

**Comment by qooob** [comment]
It's self-explanatory. It's made for upcoming Webmin release.

You can run `update-from-repo.sh` from `/usr/share/webmin` directory to update to the latest Webmin.

**Comment by ChiefPilot14** [comment]
I change to "depends=1.870" in authentic-theme-19.06.wbt and theme installation was successful. Thanks!

**Comment by qooob** [comment]
I have added a check based on `theme.info` and `depends=` key to check on development versions dependencies.

In case development theme version requires unreleased version of Webmin/Usermin, the user will be notified.

![screenshot from 2018-01-24 12-20-18](https://user-images.githubusercontent.com/4426533/35326185-f3a37c3c-0106-11e8-8823-d6c1eae944c0.png)
