### ISSUE TITLE
Theme: Pinning right side slider

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#968]
Is it possible to add a pin to the slider so it is possible to keep the slider always visible without open the theme settings every time i want it visible?

I also wondering what these buttons do? They have no tooltip either (is it possible to add tooltip?). The button at the bottom left do some kind of refresh but what will it refresh? The button to the bottom right also refresh something... The rightmost button opens a menu with text, so that button is self explained :)

`Recent logins` have two ways to expand. To the left you see the chevron and to the right you see a plus sign and both expand the recent logins.

![image](https://user-images.githubusercontent.com/5789283/34436288-ad7ad31c-ec94-11e7-8bb1-476b980702a1.png)

**Comment by qooob** [comment]
Hi,

I like pinning idea. I will add it. Do you think it should be persistent to the reload/session/or completely change an option in the theme configuration?

Tooltips? Well, yes, maybe. But I think it's self-explanatory.

Opening Recent Logins and other familiar, is possible by clicking on anything in the row. Chevron and +/- is just indicators.

I plan to make right slider more modular and add Mail notifications there as well.

**Comment by Sopor-** [comment]
I don't see any difference when i press those two buttons at the bottom. So it would be great if you could explain them for me... The arrow only spins around and the other button close the slider and shows the dashboard.

**Comment by qooob** [comment]
Which buttons you want me to be explained?

**Comment by Sopor-** [comment]
![image](https://user-images.githubusercontent.com/5789283/34437864-4f177cd6-eca2-11e7-8860-292150d9805c.png)

**Comment by qooob** [comment]
Okay, will be done a bit later though. My family needs me right now, as I've been lost for quite a bit, with the keyboard. 😉

**Comment by gnadelwartz** [comment]
Hm .. without ever used the buttons, I would interpret tme as:

left: refresh content of slider
rigth: open dashboard

To be honest, you will notice the action open dashboard onöly if you are not already on dashbord view :-)

**Comment by qooob** [comment]
This feature has been added in _19.12-beta1_.

It has both the pin functionality and tooltips on the buttons.

You would have to enable it in Theme Configuration for the button to appear.

![screenshot from 2018-03-31 20-12-40](https://user-images.githubusercontent.com/4426533/38165970-a788b54a-3524-11e8-8512-7680dca9dd9a.png)
