### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#969]
Before posting an issue, please search through closed/opened issues to make sure that the answer to your questions hasn't been answered already.

Please make sure that you have latest theme (19.07) and Webmin (1.870) versions installed.

Provide the following information:
* What is your server-side OS and its version? CentOS 7
* What is your client-side OS, browser and its versions? MacOS X Sierra, Firefox, Chrome and Safari
* What are the steps to reproduce the issue? Try to access the interface. You get no menu options or anything. See attached screenshots from Firefox, Safari and Chrome

![screen shot 2017-12-29 at 5 09 45 pm](https://user-images.githubusercontent.com/1323544/34449891-2a0248b8-ecbb-11e7-8213-3ae6691e4b27.png)
![screen shot 2017-12-29 at 5 09 34 pm](https://user-images.githubusercontent.com/1323544/34449892-2a1c3cf0-ecbb-11e7-936d-202bea996553.png)
<img width="1392" alt="screen shot 2017-12-29 at 5 12 17 pm" src="https://user-images.githubusercontent.com/1323544/34449918-91a965c8-ecbb-11e7-9ff8-ce43207aa102.png">

**Comment by qooob** [comment]
Hi, Steffan.

That looks odd.

What do you have in console? What if you open the same page in incognito tab?

Did you try clicking on top left switches? Does it change anything?

**Comment by SteffanCline** [comment]
The Webmin menu tree is there and is functional however when you click on a link, it loads what would previously have been the right frame into the entire window making the left frame disappear. Opening it in incognito mode makes no difference. The console reveals:
```Uncaught the container selector '[data-dcontainer]' did not match anything``` in ```bundle.min.js?19070:76```

**Comment by qooob** [comment]
You would need to beautify the code first to get exact line.

What it the link when you click that returns such response?

What happens if you open it using right click in the separate tab?

**Comment by SteffanCline** [comment]
That error shows up in the console when you simply load the web app. As far as the content loading in the whole window, that happens on any link clicked in the webmin menu tree. Right click to open in another tab does the same thing as if I just left clicked it. The content fills the whole window omitting the menu tree.

**Comment by qooob** [comment]
Okay,

When opened in new tab without the menu, what is source of this page, including body tag and up to including `.container-fluid`?

**Comment by SteffanCline** [comment]
Attached is the source of a page that I opened in another tab.

[page.html.zip](https://github.com/qooob/authentic-theme/files/1594239/page.html.zip)

**Comment by qooob** [comment]
It looks good.

**Comment by qooob** [comment]
If you run in console:

```
get_server_data('level')
```

What is the output?

**Comment by SteffanCline** [comment]
0
<img width="1452" alt="screen shot 2017-12-30 at 2 09 55 am" src="https://user-images.githubusercontent.com/1323544/34452894-94fc0ca8-ed06-11e7-9f34-0979d29e9c3b.png">

**Comment by qooob** [comment]
Does anyone else reading this has an issue in MacOS X Sierra?

I suppose the same would happen for you in Linux or Windows?

I will need time to give it a try.

**Comment by SteffanCline** [comment]
Here is Explorer and Chrome on Win 7

<img width="1425" alt="screen shot 2017-12-30 at 2 24 17 am" src="https://user-images.githubusercontent.com/1323544/34453073-9d481576-ed08-11e7-9b0f-a8c3c3b6fe77.png">
<img width="1425" alt="screen shot 2017-12-30 at 2 22 15 am" src="https://user-images.githubusercontent.com/1323544/34453074-9d5bd85e-ed08-11e7-97b1-d1308a1ea11f.png">

**Comment by fdmgit** [comment]
Just tested it with High Sierra (macOS 10.3.2) and Safari 11.0.2.

No issues at all

**Comment by SteffanCline** [comment]
Which version of the theme are you using?

**Comment by SteffanCline** [comment]
I had to downgrade to 19.05 on CentOS 7 to get it to work.

**Comment by fdmgit** [comment]
@SteffanCline 
 
My environment is:

Ubuntu 16.04
Webmin 1.870
Authentic Theme 19.07

**Comment by qooob** [comment]
@fdmgit Thank you. 

It seems like on of the systemd restart issue.
https://www.virtualmin.com/node/54735

**Comment by qooob** [comment]
And this is also related, I think.
https://sourceforge.net/p/webadmin/bugs/5055/

**Comment by qooob** [comment]
It's not considered to be the theme issue, thus I'll close it for now. If you have any questions feel free to contact me.
