### ISSUE TITLE
Error - Perl execution failed 

### ISSUE THREAD

**Issue by RWOverdijk** [qooob/authentic-theme#97]
I just cloned the theme, and set in in webmin. Now my installation appears to be broken. It's loading infinitely, and when checking out the console (browser) it gives me a 500. When I open the resource directly it says:

Error - Perl execution failed

Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /usr/share/webmin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /usr/share/webmin/ ..) at /usr/share/webmin/authentic-theme/body.cgi line 257.
BEGIN failed--compilation aborted at /usr/share/webmin/authentic-theme/body.cgi line 257.

**Comment by RWOverdijk** [comment]
I only just now read the README... I'll need to install the missing modules. Sorry :)

**Comment by qooob** [comment]
It's ok! Thank you!
