### ISSUE TITLE
Perl error &virtual_server::list_domains 

### ISSUE THREAD

**Issue by hostdog** [qooob/authentic-theme#970]
After authentic-theme update 19.07 and Webmin update 1.871,  Cloudmin sidebar menu is empty with the following error:

Undefined subroutine &virtual_server::list_domains called at /usr/share/webmin/authentic-theme/authentic-lib.pm line 831. Compilation failed in require at /usr/share/webmin/authentic-theme/authentic-lib.pm line 2670. 

Debian 8
Webmin 1.871
Cloudmin version | 9.3

**Comment by qooob** [comment]
Thanks, fixed https://github.com/qooob/authentic-theme/commit/25a94d199cdb7fc34b840f35b7ca086536c7b59f#diff-a713fe06a7b996bc98fd66ec6d9319b4.

It should work, please give it a try.
