### ISSUE TITLE
Theme: Backup and Restore - Unable to Browse to Backup File Folder

### ISSUE THREAD

**Issue by kteruya** [qooob/authentic-theme#971]
Running CentOS 6.9, Virtualmin  6.02Pro, Authentic 19.07
Client Windwos 10, Chrome 63.0.3239.84 or Edge 41.16299.15.0

Backup and Restore -> Restore Backup 
Local file or Directory - Cannot Browse Local File or Directory Tree. This is specific to Authentic Theme, a temporary change to Framed Virtualmin Theme allows for Browse and Selection.

**Comment by qooob** [comment]
Hi,

I'd be greatly appreciated if you could attach the screenshot.

**Comment by kteruya** [comment]
The browse panel only permits the first level to be selected. As an example the home folder was selected but the browse will not open the home folder and allow browsing to the next level of folder or files.

Thank you

**Comment by qooob** [comment]
I took a look.

There is nothing wrong with actual functionality. In order to descend into the folder you would simply need to double-click it. It's common practice.

Example in [video-screencast](https://rostovtsev.ru/pub/src/authentic/19.07/chooser_navigation.webm).

**Comment by kteruya** [comment]
Thanks for looking at this. My chrome browser requires 3-4 rapid mouse clicks for some reason so a double click does nothing, however 3-4 works. The Edge Browser works with a double click.

**Comment by qooob** [comment]
Okay, I'll improve this part of the interface.

**Comment by qooob** [comment]
Okay, I have made delay much more friendly now.
