### ISSUE TITLE
Theme: Dashboard show free memory with and without buffer/cache

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#973]
The  live pie charts was showing free memory based on buffer/cache after you changed it in #908. You then changed it back so it won't include the buffer/cache in free memory but sometimes it would be nice to know how much the buffer/cache are using. 
How about a second indicator inside the memory pie chart that will show how much free memory i have without including the buffer/cache as you do now?

**Comment by qooob** [comment]
Hi, 

Happy New Year!

I'll have to check if WebminCore supplies this data. In case it does, I would be able to make it displayed somehow with the future Dashboard update.

**Comment by qooob** [comment]
Ref.: Todo #2 https://github.com/qooob/authentic-theme/issues/896
