### ISSUE TITLE
Theme: Dashboard CPU temperature graphs

### ISSUE THREAD

**Issue by fOmey** [qooob/authentic-theme#974]
Would love a CPU temp graph !

**Comment by qooob** [comment]
Yes, sure. 

I'm fine with that.

First, I will fix about 20 small bugs that have been in my notepad for quite a while and then finish reconstruction/enhancement of Dashboard.

**Comment by qooob** [comment]
Todo #_3_ https://github.com/qooob/authentic-theme/issues/896
