### ISSUE TITLE
"Webmin Actions Log" and "Webmin Configuration Page" broken on Theme 19.07

### ISSUE THREAD

**Issue by ionbasa** [qooob/authentic-theme#975]
Provide the following information:
* What is your server-side OS and its version?
Ubuntu Server x64 16.04LTS; kernel: Linux 4.4.0-104-generic on x86_64

* What is your client-side OS, browser and its versions?
Windows 10 Pro x64, Chrome 

* What are the steps to reproduce the issue?
Using theme and  Webmin 1.870 results in the pages being broken, see screenshots below. Using Apache reverse proxy.
![actionslog](https://user-images.githubusercontent.com/940050/34508617-588bdb66-eff6-11e7-8d6f-7910b939dc9c.PNG)
![configpage](https://user-images.githubusercontent.com/940050/34508618-58a74a0e-eff6-11e7-93ed-522d3e756424.PNG)

**Comment by gnadelwartz** [comment]
besides its hard to see anything on a black screen, have cleared browser cache or tested an in an other browser?

**Comment by qooob** [comment]
Hi,

You're missing 

```
webprefixnoredir=1
```

set in to `/etc/webmin/config`.

Happy New Year.
