### ISSUE TITLE
Usermin compose window error 

### ISSUE THREAD

**Issue by brad1001** [qooob/authentic-theme#976]
Hi,
I have the same error on two servers which have both just been updated to Webmin 1872 / Usermin 1732 using Authentic Theme 19.07.

Logging into Usermin from Virtualmin  >  Edit Users > UserXYZ  > Login to Usermin 

Trying to compose an email brings up the error below  (using compose button)

**Failed to open /home/xxxxxxx/homes/info/.tmp/.tmp_MTU2NDI3NjA3_usermin_redirected_info.xxxxxxx for writing : No such file or directory**

Switch to the old Usermin theme and the compose button works 

Any assistance would be greatly appreciated 

Kind Regards
Brad

**Comment by qooob** [comment]
Unfortunately latest Usermin still ships old 19.04 theme. Could you please upgrade manually?

**Comment by qooob** [comment]
Okay, hold on. I started thinking that new function for detecting  tmp dir is not working correctly.

If you downgrade to 19.02, for example, will it work?

**Comment by brad1001** [comment]
Hi, thank you for your reply .

I actually forced a Webmin theme update which seems to have  solved the issue 

Kind Regards
Brad

**Comment by qooob** [comment]
Okay, so, Brad, all is working fine now?

**Comment by brad1001** [comment]
Hi, yes just did the same on the second server -  after forcing the theme update I did need to reboot the server.

Thank you for your assistance greatly appreciated

Kind Regards
Brad

**Comment by qooob** [comment]
Brad, did you use proxy with that installation of Usermin?

**Comment by brad1001** [comment]
Hi qooob   -  No I did not, (I don't think..)  just forced Webmin theme update (via git)  on the Webmin theme page - to latest stable.

**Comment by qooob** [comment]
There is an underlying issue in my code for users without having temp directory. I will fix it in a bit.

**Comment by brad1001** [comment]
Ah OK great  - I will await your update 

I have also noted that when using the Server Status on the main page to restart a service the page no longer reloads as expected -  this is minor as it still works you just need to refresh the page (just mentioning it in case you are not aware)

**Comment by qooob** [comment]
> Failed to open /home/xxxxxxx/homes/info/.tmp/.tmp_MTU2NDI3NjA3_usermin_redirected_info.xxxxxxx for writing : No such file or directory

Fixed in the commit above.

> I have also noted that when using the Server Status on the main page to restart a service the page no longer reloads

That has been also fixed in:
https://github.com/qooob/authentic-theme/commit/61121544988dafd62377ecf536715bc385bac498
