### ISSUE TITLE
Theme updated, but usermin still using old buggy version.

### ISSUE THREAD

**Issue by tiagoadp** [qooob/authentic-theme#977]
Hello, i just updated the theme, as my clients are receiving a form encode, error, when sending emails.

So i updated it, everything was normally... Except that, the theme only was updated on virtualmin, usermins still using the old version... check it out:

Image from virtualmin configs:

![chrome_2018-01-04_09-04-34](https://user-images.githubusercontent.com/3828358/34560821-9591546c-f12e-11e7-8235-1ee3bb26ed9f.png)

Image from client userming:

![chrome_2018-01-04_09-05-02](https://user-images.githubusercontent.com/3828358/34560832-a7e1154e-f12e-11e7-93e5-c7865d216d28.png)

I really apreciate any help, tnx for your time. Maybe i am doing something wrong? :(

**Comment by tiagoadp** [comment]
Nevermin, i just followed the issue #976 and forced the update of the theme, everything was updated now, strange is that the normal update is not working, maybe a bug? dunno...

**Comment by tiagoadp** [comment]
Saddly even with the theme updated on userming, the original error still comes, check it out, just tryed to send an mail:

![chrome_2018-01-04_09-15-19](https://user-images.githubusercontent.com/3828358/34561148-cea3775c-f12f-11e7-821a-519dba0c2e4c.png)

I really need a help for this, mails are stuck...

**Comment by qooob** [comment]
Duh.. I'll check this up. Thank you for reporting.

**Comment by qooob** [comment]
The problem is that I can reproduce it on Fedora but not on CentOS, where it just sends the message. This needs more work. I hope to finish all of it tomorrow and release 19.08 though.

**Comment by qooob** [comment]
Yes, this seems only to happen with HTML editor on. I'm coming back tomorrow to fix it.

I have had tons of other things todo with other improvements and bug fixes. Sorry about that.

19.08 is coming.

**Comment by qooob** [comment]
It's going to be fixed upon next Webmin/Usermin release.
