### ISSUE TITLE
Dash board entries the wrong way round

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#978]
I know this is not a bug but may be an enhancement 
on the dashboard
CPU averages reads left to right 
real memory reads right to left
local disk space reads right to left 
virtual memory reads right to left
I prefer reading left to right rather than right to left, so could you put an option in to force either RTL or LTR for these options to suit languages

**Comment by qooob** [comment]
Hi, Jim.

Happy New Year!

Could you provide the screenshot, I don't understand what you mean.

**Comment by JimTR** [comment]
Ok No worries 
I'll try with text first 
CPU reads 1 min-> 5 min-> 15 min eg LTR lowest to highest
![screenshot from 2018-01-04 15-16-13](https://user-images.githubusercontent.com/4038510/34570766-a78e27fe-f164-11e7-8a3f-b308d4c5ed46.png)

Real Memory reads total-> used  eg RTL perhaps it should be used->total
local disk space reads total->free->used perhaps it should be used->free->total

**Comment by qooob** [comment]
Oh, 😄 Jim, I at first was sceptical, but then checked _Gray Theme_ and then _Nautilus_ and they all seem to use logic mentioned by you. Okay, I will change that, no problem! 😉

**Comment by JimTR** [comment]
Great there is the issue, perhaps with users that would prefer the other way around E.G arabic language so perhaps and an option

**Comment by qooob** [comment]
It's done. RTL is also respected.

What you think?

**Comment by qooob** [comment]
Uups. Forgot to fix it for real-time stats.

**Comment by qooob** [comment]
Okay. Done.

**Comment by JimTR** [comment]
Looks Great thanks for that

**Comment by qooob** [comment]
Sure!
