### ISSUE TITLE
I get ERROR text message on screen when i uploading files in public_html with File Manager

### ISSUE THREAD

**Issue by NedDon** [qooob/authentic-theme#979]
I get ERROR text message on screen when i uploading files in public_html with File Manager in Firefox.

Operating system 	Debian Linux 9

Webmin version 	1.872

Virtualmin version 	6.02 

Usermin version 	1.732

Theme version 	Authentic Theme 19.07

Webmin>Others>File Manager> Upload to current directory...

When i upload file i see on screen Error text message.

Thank you!

**Comment by qooob** [comment]
I don't get any errors.

Make sure that you have latest theme installed and cleared browser's cache.

If it still doesn't work, please share:

1. Exact directory name where you uploading;
2. What error do you see;
3. Provide the screenshot.

**Comment by NedDon** [comment]
Hi, the Error appear in all directories.

Screenshot is in the attachment:

![error](https://user-images.githubusercontent.com/35108075/34623860-9983c3f6-f25b-11e7-8d72-ac1f7690a856.jpg)

**Comment by qooob** [comment]
Oh, I see now. You run as a user. Okay. I'll take a look tomorrow.

**Comment by qooob** [comment]
Sorry for the delay. It's postponed till tomorrow.

**Comment by NedDon** [comment]
Do not worry, take your break. It's not urgent. I just wanted you to know about this mistake so you can fix it. Thank you for the work and the wonderful theme!

I love to use Authentic Theme...

Have a nice weekend!

**Comment by qooob** [comment]
This will be fixed in the next Usermin release.

Thank you for reporting.

**Comment by qooob** [comment]
No wrong reference issue.. 😆

**Comment by qooob** [comment]
You, know, I'll just add new type of uploads and the progress, instead of having old `uptracker.cgi` with popup window.

Working ..

**Comment by qooob** [comment]
Finishing ..

This is how it's going to look and feel. Really awesome!

https://rostovtsev.ru/pub/src/authentic/19.08/new_super_awesome_upload.webm

**Comment by qooob** [comment]
I will do more testing tomorrow and make a release of 19.08. All is ready.

**Comment by qooob** [comment]
Okay, I have added a commit that brings new drag and drop and new interface for file uploads in File Manager.

**Please, whoever is reading it give it a try as it's going directly to 19.08 release tonight.**

---

_FYI_. THERE IS A BUG IN USER MODE (where upload progress don't show). I WILL FIX IT ALONG WITH FILENAME ESCAPING BEFORE THE RELEASE.

**Comment by qooob** [comment]
Okay, all bugs are fixed. Progress shows fine for all user modes.

Enjoy.

Rolling out 19.08 ..
