### ISSUE TITLE
Editor for Apache, wrong comment when row doesn't start with....

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#981]
Hello,

when you write
`# something`

it correctly recognizes it as comment

BUT if you write

`ApacheRule ... ... #something`

that's not a comment but is seen as a comment, so that's wrong
and you should set it as comment just when the row starts with one or more **#**

Thanks

**Comment by qooob** [comment]
Hi,

Happy New Year.

This is CodeMirror issue, in case you're right and `ApacheRule ... ... #something` is valid syntax.

Are you sure about that?

Besdies, I don't think CodeMirrow has specific mode for Apache logs. So it's approximate and I don't think I'm going to patch it! ;)

**Comment by qooob** [comment]
I can't find at least one instance on my servers, where `ApacheRule ... ... #something` would be used.

**Comment by qooob** [comment]
Ah, okay,

```
SuexecUserGroup "#1000" "#1000"
```
Would be highlighted wrong.

**Comment by 7starsone** [comment]
yes, exactly 👍 😉

**Comment by qooob** [comment]
Yes, okay, okay.. Patching it and also making highlight apache specific entries to make it look supoer hot. When done let you know so you could test it.

**Comment by qooob** [comment]
It's done! Please give it a try!
