### ISSUE TITLE
Blank screen after DNS apply zone with secondary zone.

### ISSUE THREAD

**Issue by mkinderwater** [qooob/authentic-theme#982]
Create a secondary zone.
Enter domain and master IP
Click Create
Once created click either Apply Zone or Apply Configuration button.
You get a grey screen. Checked syslog and it reports xfer was successful - no errors.

**Comment by mkinderwater** [comment]
Forgot to mention - Running Deb 9; I can repeat on Deb 8 (both are fresh installs as if today using the standard install.sh script on a fresh format server).

**Comment by qooob** [comment]
What is your theme version?

**Comment by qooob** [comment]
I just checked with the latest theme 19.08 and it works/redirects without an issue.

Isn't it the same for you?

**Comment by qooob** [comment]
However, running it from `Edit Slave Zone` returns blank screen, it's true.

**Comment by mkinderwater** [comment]
I am running 19.07 - that said the release notes don't indicate any specific fixes to this issue. I have now upgraded to 19.08 and the issue is still present.

We are in the process of migrating a lot of domains from DNS slave host A to DNS slave host B (the server which has this issue). Would it not be better to have the redirect when a Apply Zone / Apply configuration button is clicked than a grey screen? After all, when you create a Slave DNS - the default page after creation is the "Edit Slave Zone" page.

**Comment by qooob** [comment]
I surely think that redirect is better than blank screen. 😁

I'll find the cause of the issue and fix it a bit later later.

**Comment by qooob** [comment]
Thanks for reporting.

Fixed.
