### ISSUE TITLE
System Information (CSS Improvements)

### ISSUE THREAD

**Issue by tpnsolutions** [qooob/authentic-theme#984]
The below style updates make the System Information page look and feel a bit more cleaner. Use any or all of the below style ideas as you see fit :+1: 

The following sections are affected by the CSS below.

- System Information
- Recent Logins
- Servers Status
- Virtualmin Counts
- Disk Quotas
- Bandwidth Quotas
- Software Versions

*** see attached screenshots ***

`#system-status .panel-body table tbody tr td
{
	text-align: left !important;
}

#system-status .panel-body table tbody tr td:nth-of-type(1)
{
	width: 15% !important;
}

#system-status .panel-body table tbody tr td:nth-of-type(2)
{
	width: 35% !important;
}

#system-status .panel-body table tbody tr td:nth-of-type(3)
{
	width: 15% !important;
}

#system-status .panel-body table tbody tr td:nth-of-type(4)
{
	width: 35% !important;
}

#acl_logins-acl-1-collapse .panel-body .table-responsive table thead tr th
{
	text-align: center !important;
	width: 33.33% !important;
}

#acl_logins-acl-1-collapse .panel-body .table-responsive table tbody tr td
{
	text-align: center !important;
	width: 33.33% !important;
}

#status-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td
{
	width: 50% !important;
}

#status-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:first-child
{
	text-align: left !important;
}

#status-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:last-child
{
	text-align: right !important;
}

#ftypes-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td
{
	width: 50% !important;
}

#ftypes-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:first-child
{
	text-align: left !important;
}

#ftypes-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:last-child
{
	text-align: right !important;
}

#quota-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:nth-of-type(1)
{
	text-align: left !important;
	width: 20% !important;
}

#quota-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:nth-of-type(2)
{
	width: 60% !important;
}

#quota-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:nth-of-type(3)
{
	text-align: right !important;
	width: 20% !important;
}

#bw-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:nth-of-type(1)
{
	text-align: left !important;
	width: 20% !important;
}

#bw-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:nth-of-type(2)
{
	width: 60% !important;
}

#bw-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:nth-of-type(3)
{
	text-align: right !important;
	width: 20% !important;
}

#sysinfo-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td
{
	width: 50% !important;
}

#sysinfo-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:first-child
{
	text-align: left !important;
}

#sysinfo-virtual-server-1-collapse .panel-body .table-responsive table tbody tr td:last-child
{
	text-align: right !important;
}`

![authentic-cleanup-01](https://user-images.githubusercontent.com/4305218/34748140-0e85be88-f550-11e7-97cf-1338fcc57a79.png)
![authentic-cleanup-02](https://user-images.githubusercontent.com/4305218/34748141-0e99e9b2-f550-11e7-9de2-34bd4c514728.png)
![authentic-cleanup-03](https://user-images.githubusercontent.com/4305218/34748142-0eb139f0-f550-11e7-9411-5a0c192d096f.png)

**Comment by qooob** [comment]
Peter, thank you.

I have added some improvements, not all that I like.

But most importantly, we shouldn't invest much time in it, as it's part of the plan to completely rework Dashboard and make it widgetable.
