### ISSUE TITLE
Could you make the 'Recent Logins' stay closed?

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#986]
If more than one user is logged in the `Recent Logins` will stay open all the time. Could you change that so it stay closed all the time?

**Comment by qooob** [comment]
In the future I will make this configurable.

Right now you can just add this code in theme's JavaScript extension:

```JavaScript
$(document).on('ready pjax:end', function() {
  if (v___location_file === "sysinfo.cgi") {
    var target = document.querySelector('[aria-controls="acl_logins-acl-1-collapse"]:not(.collapsed)');
    target && target.click()
  }
});

```

**Comment by Sopor** [comment]
Now when you have added `Disk Usage` below `Recent Logins` could you make them stay closed even if there are more than one entry? The `Disk Usage` is closed but i want to hide them or at least make `Recent Logins` stay closed when i close it.

**Comment by rostovtsev** [comment]
You can disable Disk Usage in Disk and Filesystems module configuration.

**Comment by Sopor** [comment]
It seems that default settings is missing here

![image](https://user-images.githubusercontent.com/5789283/57324478-28d16780-7108-11e9-807c-87c98cb5e7f0.png)

How about the `Recent login`?

**Comment by rostovtsev** [comment]
The default is programmed to _Yes_.

What about Recent Logins? You want to remove them?

**Comment by Sopor** [comment]
In that case you should set it to Yes instead of making both unset as the above picture.

I want it to stay closed. If more than one login exists it will open the Recent login every time i get back to the dashboard.

**Comment by rostovtsev** [comment]
Actually, the latest theme release remembers last opened panels on the Dashboard, right until complete page reload.

Aside, you can keep it closed by applying the code above in theme extensions.

**Comment by Sopor** [comment]
Sorry, but i have no idea where that is :(

**Comment by rostovtsev** [comment]
Put this code:

```JavaScript
$(document).on('ready pjax:end', function() {
  if (v___location_file === "sysinfo.cgi") {
    var target = document.querySelector('[aria-controls="acl_logins-acl-1-collapse"]:not(.collapsed)');
    target && target.click()
  }
});
```

to JavaScript extensions - _Theme Configuration/Extensions_ to _scripts.js_ file.

![image](https://user-images.githubusercontent.com/4426533/57329971-815f2f80-711d-11e9-8cd2-15e1e8045341.png)

**Comment by Sopor** [comment]
Sorry, doesn't work. As soon as i refresh the page it is open again :(

**Comment by rostovtsev** [comment]
Provide me the screenshot please of where and how you're adding it?

**Comment by Sopor** [comment]
![image](https://user-images.githubusercontent.com/5789283/57333931-8ec8e980-711e-11e9-9c25-6e5a1e544826.png)

**Comment by rostovtsev** [comment]
Then it should just work. There is something on your end.

Try Force reloading the page, by clicking Ctrl+Shift+R.

Try other browser, without extensions, maybe.

**Comment by Sopor** [comment]
Same thing in Chrome, it won't stay closed...

This code i have added, what will it do? Will it close the recent logins or will it keep it closed when i have closed it?

Have you tested it so you know it works?

**Comment by rostovtsev** [comment]
Okay, as latest theme version stores current panel state until full page reload, here is the fixed part:

```JavaScript
$(document).on('ready pjax:end', function() {
  if (v___initial_load && v___location_file === "sysinfo.cgi") {
    var target = document.querySelector('[aria-controls="acl_logins-acl-1-collapse"]:not(.collapsed)');
    target && target.click()
  }
});
```

**Comment by Sopor** [comment]
Sorry, but recent login won't stay closed. If i refresh or if the theme do a refresh it will open the recent logins again :(
