### ISSUE TITLE
Cannot connect in "PPTP VPN Client" page

### ISSUE THREAD

**Issue by jgbustos** [qooob/authentic-theme#988]
Hi

After upgrading to the latest versions of Webmin (1.870) and Authentic  (19.08), the buttons to connect/disconnect and connect at boot in the "PPTP VPN Client" no longer work.

In order to replicate:

1. Go to Networking >> PPTP VPN Client
2. Create a new PPTP VPN tunnel entry with valid settings
3. Try to connect using the newly created tunnel entry. 

The buttons in this page no longer allow users to connect, disconnect or select a tunnel for a connection at boot time.

Thanks in advance

**Comment by jgbustos** [comment]
Forgot to mention:
Server is Ubuntu Linux 16.04, browser is Firefox 57.0.4 (64-bit)

**Comment by qooob** [comment]
Source: https://github.com/webmin/webmin/issues/775

**Comment by qooob** [comment]
It's been fixed in:
https://github.com/webmin/webmin/commit/5069a303ee0fe3ff6522521a928cade316ff7beb

It will be added to the next Webmin version.

Thanks for reporting.

**Comment by jgbustos** [comment]
Very much appreciated!
