### ISSUE TITLE
Dumping MySQL database 

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#989]
I don't know weather this is theme or webmin !
When you do a backup in the foreground .. most parts of the backup show copying or backing up the sql databases shows "Dumping MySQL database  <database name>" perhaps the text should be changed to something like this as dumping in some languages could amount to "going to the toilet"  perhaps Extracting Database ?

**Comment by qooob** [comment]
Ha-ha 😂 Okay. This is part of Webmin, I think.

Could you please share a screenshot, so we know exactly what you mean?

**Comment by JimTR** [comment]
Ok look here
![dump](https://user-images.githubusercontent.com/4038510/34961400-ecbd1706-fa36-11e7-9a79-399f6848ed11.png) for the dumping :)

**Comment by qooob** [comment]
Jim, i see now. This is ordinary to use this term. 😁

> A database dump (also: SQL dump) contains a record of the table structure and/or the data from a database and is usually in the form of a list of SQL statements. A database dump is most often used for backing up a databaseso that its contents can be restored in the event of data loss.

[Database dump - Wikipedia](https://www.google.ru/url?sa=t&source=web&rct=j&url=https://en.m.wikipedia.org/wiki/Database_dump&ved=0ahUKEwj91bSl-NvYAhViQZoKHWHNBHcQFggmMAE&usg=AOvVaw1Vx5pV8gHopZ0ERiq28EPn)

**Comment by JimTR** [comment]
I am aware of the concept ... I have been administrating databases since 1980 I was just thinking that users who are not so literate may find the term odd and not quite understand what is going on

**Comment by jcameron** [comment]
The actual command used to perform this backup is `mysqldump` , so I'm in favor of keeping the current wording.

**Comment by JimTR** [comment]
<servername>:10000/virtual-server/pro/history.cgi is referenced as system statistics  on the UI perhaps this should be changed to history.cgi ?     :)

**Comment by swelljoe** [comment]
You can have a custom language you like. Just copy the lang/en file to something like lang/custom (or en/local or whatever) and make the changes you want. Any modules, and any variables, that don't have a "custom" language file will fall back to lang/en, so you only need a file for the modules you want to change, and you only need the items you want to change.

There's also a translation module that gives you a UI for editing Webmin translations. But, I tend to prefer just editing in vim (or whatever editor you like).

**Comment by JimTR** [comment]
cool I'll play with that
