### ISSUE TITLE
Sending HTML email in Usermin fails with : Expecting form-data encoding, but got normal encoding

### ISSUE THREAD

**Issue by jcameron** [qooob/authentic-theme#990]
Steps to re-produce : 

1 - Go to the Inbox, click on Compose
2 - Click the A  button to switch to HTML email
3 - Click the Send button

Somehow the form encoding type isn't being respected. This happens even on a fully updated system with the latest theme code.

**Comment by jcameron** [comment]
Original issue in which this was reported : https://www.virtualmin.com/node/55054#comment-790476

**Comment by qooob** [comment]
Jamie, hi!

We have fixed this issue with my latest commit that you have merged already for Webmin but there is one pull request is still pending. It's exactly the fix for it:

https://github.com/webmin/usermin/pull/27
