### ISSUE TITLE
Webmin Cluster Commands not working properly. ( unusable state )

### ISSUE THREAD

**Issue by Chaots** [qooob/authentic-theme#992]
The Module in "Tab Webmin --> Webmin --> webmin server index" seems to have an issue, and is currently in an unusable state.

for example Adding a new server to the index via the "Register new server" button results navigating to a new page with the address bar showing the http addres with multiple xnavigation entries. The url looks like https://DOM.TLD:12345/servers/edit_serv.cgi?new=1&xnavigation=1&xnavigation=1 and the right hand page stays empty. yet the first add ( no servers registered worked fine )

Same goes for several buttons in the module "Tab Webmin --> Cluster --> cluster webmin servers" or "Tab Webmin --> Cluster --> Cluster Software Packages" ( Add all from group, refresh packages on all hosts for example. button click does not result in any action at all as if the click does not register.

Firefox 57.0.4 (64-bit), Windows 10 Pro, i'll try and install the latest firefox version to see if that fixes the issues.

Steven

**Comment by qooob** [comment]
What is your Webmin/theme version?

This shouldn't be an issue on the development branch.

**Comment by Chaots** [comment]
it happens on several machines in different group combinations:
---------
Webmin version | 1.872 | Usermin version | 1.732
Virtualmin version | 6.02 | Theme version | Authentic Theme 19.09-beta2
-------------
Webmin version | 1.872 | Usermin version | 1.732
Virtualmin version | 6.02 | Theme version | Authentic Theme 19.08.
-------------
System running the combinations is a physical machine with latest up to date CentOS 7 install - Operating system | CentOS Linux 7.4.1708

**Comment by Chaots** [comment]
it happens on several machines in different group combinations:
Webmin version | 1.872 | Usermin version | 1.732
Virtualmin version | 6.02 | Theme version | Authentic Theme 19.09-beta2

Webmin version | 1.872 | Usermin version | 1.732
Virtualmin version | 6.02 | Theme version | Authentic Theme 19.08.

System running the combinations is a physical machine with latest up to date CentOS 7 install - Operating system | CentOS Linux 7.4.1708

**Comment by Chaots** [comment]
Actually looking in to creating a small video i noticed a pattern.

It seems to only happen in the first "form" segment of a module, the second "section" of a "panel" seems to work. Is there an option to send you a private message containing a link to a video showing the behavior?

**Comment by qooob** [comment]
That would be great.

Use my Website. It's secure. https://rostovtsev.ru

**Comment by Chaots** [comment]
it took me a few tries with 2 people to solve the captha, though you should have mail :)

**Comment by qooob** [comment]
I got your mail, if you still could convert your video to mp4/webm format I'd be very appreciate.

**Comment by qooob** [comment]
I think you shouldn't though.

We're finishing going through transitional times. The part of the issue is actually in Perl part that has to be resolved not on the theme side.

I will let Jamie know.

Thanks for reporting.

**Comment by qooob** [comment]
https://github.com/webmin/webmin/issues/784
