### ISSUE TITLE
clicking on "refresh" highlight the previous menu entry

### ISSUE THREAD

**Issue by kintaro1981** [qooob/authentic-theme#994]
Authentic Theme 19.09-beta1

I noticed this some days ago (in 19.08 too).

In the Nginx Error Log page, if I hit refresh the Nginx Access Log page menu entry is highlighted, but I'm still correctly on the Nginx Error Log page.

Here's the video:
http://recordit.co/ijO9pXR8Ik

and the GIF:
![screen](http://g.recordit.co/ijO9pXR8Ik.gif)

**Comment by qooob** [comment]
Thank you for the perfect bug report.

I will fix it in a bit. It's going to 19.09-release.

**Comment by qooob** [comment]
Done.
