### ISSUE TITLE
Usermin Ui

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#998]
Hi 
just looking at usermin UI , perhaps you combine the usermin & login options into one menu  i.e usermin and remove the login sub menu as it will just tidy stuff up
![usermin](https://user-images.githubusercontent.com/4038510/35482670-7b08915e-0430-11e8-9aac-93f78d166310.png)
I would all so think a mail only user should not be able to see the shell option
![sec](https://user-images.githubusercontent.com/4038510/35482831-63f61322-0432-11e8-8d29-0224997c2885.png)

**Comment by JimTR** [comment]
I found this also
![subfolder](https://user-images.githubusercontent.com/4038510/35483064-756dac7a-0435-11e8-9e2e-47b596fd8199.png)
as you can see there is no accordion to show the sub folders in the folder 'Git Hub' 
no unread message count against the folder 'Git Hub' but as you can see from the screen shot there is both unread mail & sub folders

**Comment by qooob** [comment]
Jim,

These are the functional changes your talking about. It could only be done on Usermin part.

Thank you for your ideas, but please report this to Usermin repo on GitHub.

**Comment by qooob** [comment]
About drop down and unread messages, - it will all be there after mail rework.
